>P1;ENSONIG00000005940

MEENDHG-NRDVVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDGGA-NREESS---LA------SRESHN-----SPTAPQTE
----PVGST-VPAEGT-STPHTVT-GTKKPAIAAEEPLKPRG-ENGDQCL
S-SDSDSSQASSNPSMSQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----TTSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQELGLN
ESQIKIWFQNKRAKIKKASGTKNSLALHLMAQGLYNHSTVTSKDEKSDSD

*
>P1;ENSAMXG00000002112

MEEGEQSAPRDEPNRATDRSTDRSTIRPVQGNPP-P-LPHRITNFFIDNI
LHPDFGRKKEASA-LRADSC--PTG------AGDSAG-----SPATPGSG
----RLSVS-GPTEST-STPLPES-AAKKPEIE--EPFTAKGSNSKDQCL
SSSESDTSQPGTNTSQNRPMLWPAWVYCTRYSDRPSSGPRTRKPKKKNTT
TTTTTTTKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQSLAQELGLN
ESQIKIWFQNKRAKIKKASGTKNTLALHLMAQGLYNHATT-TKEDKSDSD

*
>P1;ENSONIG00000009704

MERNARR---DPERPRDSGEQSNRAILPLLQPPGNQ-QSHRITNFYIDNI
LRPDFGLKRKDGAPDRQGDA---LGVL---IQREELTGRKPPKSANPRQG
----GAGGKEEENPGENEDQHPDT-DARRPGVVARDV------AANDRCR
------SPQA-STATAAKPMLWPAWVYCTRYSDRPSSGPRSRKPKKAP--
----TPSKEDKRPRTAFTAEQLQRLKTEFQNNRYLTEQRRQSLARDLGLN
ESQIKIWFQNKRAKIKKASGNKNSLALHLMAQGLYNHST--AKDAKSDSD

*
>P1;ENSTNIG00000012777

MEENDHG-NRDVVERPESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDGGT-NRDESS---LA------SRESHN-----SPAAPQTE
----SEGST-VPAEGT-STPHTVT-GAKKSAIAAEEPLKPRR-ENGDQCL
S-SDSDSSQASSNPSMSQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----STSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQELGLN
ESQIKIWFQNKRAKIKKATGSKNSLALHLMAQGLYNHSTVTSKDEKSDSD

*
>P1;ENSTRUG00000017873

MEENDHG-NRDVVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDGGT-NRDESS---LA------SRESHN-----SPAAPQTE
----SEGST-VPAEGT-STPHTVT-GTKKPAIAAEESLKPRR-ENGDQCL
S-SDSDSSQASSNPSMSKPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----STSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQELGLN
ESQIKIWFQNKRAKIKKATGNKNSLALHLMAQGLYNHSTVTSKDEKSDSD

*
>P1;ENSXMAG00000002496

MEENDHG-NRDAVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDVDA-HLDESS---PA------SRESRG-----SPAAPQTE
----PVGST-VPAEGT-STPHTVT-GPKKPAKAAEESLKPSG-ESGDQCL
S-SDSDSSQASSNPSMSQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----TTSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQELGLN
ESQIKIWFQNKRAKIKKASGTKNSLALHLMAQGLYNHATVTSKDEKSDSD

*
>P1;ENSGACG00000014426

MEENAHR---HPERAEDSGEESNRAIRPLL-PPGNQ-QSHRITNFYIDNI
LRPDFGRKRKNGTLVRDGDR---PGGI---IRRDEQTGRKSSKTRDPQPA
----AAGGEE-EDTGASEEQHPET-EARRPEPI-----------------
--------AG-DGLVKSKPMLWPAWVYCTRYSDRPSAGPRSRKPKKAP--
----TPSKEDKRPRTAFTAEQLHRLKTEFQNNRYLTEQRRQNLALDLGLN
ESQIKIWFQNKRAKIKKATGNKNSLALHLMAQGLYNHAG--SKDAKSDSE

*
>P1;ENSAMXG00000008331

MEEKDRS-PRGA-E--DSGDES-----MLLHAPGNL-HAHRVTNFYIDNI
LRPDFGRRKEGIA-SIPANDHDHHHQHYNHHQHSAVT-----SEPSAATE
----PVGAP-VTGEGT-SGPRPGT-GAKRTSDG------AGA-ESADQCL
S-SDSECSQSSAH-PNSQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----SLSKEDKRPRTAFTAEQLQRLKTEFQTNRYLTEQRRQSLAQELGLN
ESQIKIWFQNKRAKIKKATGTKNSLALHLMAQGLYNHATT-SKDDKSDSD

*
>P1;ENSORLG00000008039

MEEKNPQ---DPGGPQNFRQESSRGVWPLLQPPGH---QHQPTNFYIDNI
LRPDFGLRGKRGK-EAPE---------------------------APERC
-----TGRR-APKPGS-PGAAGPR-GKQSGDLDRGSHLKP-----GDDEV
K-V--RAHEQGTETNAAKPMLWPAWVYCTRYSDRPSAGPRSRKPKTAA--
----APCKEDKRPRTAFTSEQLQRLKEEFQRNRYLTEQRRQSLARDLGLK
ESQIKIWFQNKRAKIKKASGGKNSLALHLMAQGLYNHST--TKDGKSDSD

*
>P1;ENSDARG00000026599

MDENEQS-ARDV-EQRGASDESNSAIRPLLQAPGNLQLPHRITNFFIDNI
LRPDFGRKKEANI-TRYEDN---HG------AREN-H-----NPTGPSTG
----QVGST-VPAEEA-STTHTSS-GGKEAEIESEEPLKPRG-ENVDQCL
G-SESDSSQSNSNGQTGQGMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----AASKEDKRPRTAFTAEQLQRLKAEFQTNRYLTEQRRQSLAQELGLN
ESQIKIWFQNKRAKIKKASGVKNGLAIHLMAQGLYNHSTT-SKEDKSDSD

*
>P1;ENSDARG00000038868

MEENDHS-NRDV-ERQDSGDESNRAILPLLQAPGNV-LPHRITNFYIDNI
LRPDFGRRKEGS--RRDEII---IV------EREN-R-----CPSAPGSG
----QV-AP-VSGEGT-SSPRAVN-ASKKTDISTDESLKSRA-ETGDQCL
S-SDSDCSQSSA-AQAKQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----TPTKEDKRPRTAFTAEQLQRLKNEFQNNRYLTEQRRQALAQELGLN
ESQIKIWFQNKRAKIKKATGNKNTLAVHLMAQGLYNHATV-TKDDKSDSD

*
>P1;ENSGACG00000003888

MEENDRG-NRDAVERQESADESNRAILPLLQPPGNPQIPHRVTNFFIDNI
LRPDFGRKKDGDA-NRDASS---LA------SRESPG-----SPDAPQTE
----PVGNT-VPAEGT-STPHTVTVSSKKPAIAADEPQDPRG-ERGDQCL
S-SDSDSSQASSNPPASKSMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----TTSKEDKRPRTAFTAEQLQRLKTEFQTNRYLTEQRRQNLAQELGLN
ESQIKIWFQNKRAKIKKSTGAKNSLALHLMAQGLYNHATVSSQDAKSDSD

*
>P1;ENSORLG00000010437

MEENDRG-SRDVVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRRKDAGA-NREESL---AG-------EQPQQ-----PRRTPD-R
----ACGEH-RSSRGDLHSTHSHR-RKEAHYIRRGATATPGG-EWRP-VP
K-LRLRQFPSQLEPIRFQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----STSKEDKRPRTAFTAEQLQRLKTEFQTNRYLTEQRRQNLAQELGLN
ESQIKIWFQNKRAKIKKASGTKNTLALHLMAQGLYNHATVTSKDEKSDSD

*
>P1;ENSXMAG00000001344

MEENVQG-EPE--RPKSSGEESNRAILPLLQQPGIQ-QSDRVTNFYIDNI
LRPDFGRKRKKGT-LCVRGGH-GLE------ERSEAS-----GRKASKTD
SKRGRAGGR-EDSLGK-SDHQPA-------ESEASGPGLTAC-DSGISCR
S-PESSEAPAAPAAPAAKPMLWPAWVYCTRYSDRPSSGPRSRKPKKAP--
----TPSKEDKRPRTAFSAEQLQRLKAEFQKNRYLTEQRRQNLALELSLN
ESQIKIWFQNKRAKIKKASGKKNSLAEHLMAQGLYNHSAGREAEAHSDSD

*
>P1;ENSLOCG00000012504

MEENDHS-NREA-DPQESGDESNRAIIPLLQAPGNLQLPHRITNFFIDNI
LRPDFGRRKEVTF-SRDQSH---AS------RREN-L-----TPSAPGTG
----QVGGT-VAGEGS-SNPHPVN-GAKKGDIAIEEPLNSRG-ESGEQCL
S-SDSDSSQASS-TTPSQPMLWPAWVYCTRYSDRPSSGPRSRKPKKK---
----TASKEDKRPRTAFTAEQLQRLKAEFQTNRYLTEQRRQSLAQELSLN
ESQIKIWFQNKRAKIKKASGSKNSLALHLMAQGLYNHATT-PKDDKSDSD

*
