>P1;ENSTRUG00000011436

---------MAVT--VVNKCRG-----SLAFLTRTISAPEFFTQCCYHKK
VVDHYENPRNVGTLDKHSKNVGTGLVGAPACGDVMKLQIQVDDQGKIVDA
RFKTFGCGSAIASSSLATEWIKGKSVDEASTIRNTDIAKELCLPPVKLHC
SMLAEDAIKAAVADYQLKQEDVQ-QEAV---QSSN
*
>P1;ENSDARG00000035596

---------MALA--AAARRCA-----SSALFSKSLSLPELRPACSYHKK
VVDHYENPRNVGSLDKNAKNVGTGLVGAPACGDVMKLQIQVDENGKIIDA
RFKTFGCGSAIASSSLATEWVKGKSIDEALKIKNTEIAKELCLPPVKLHC
SMLAEDAIKAALADYRLKQKDEK-ETLA---EARN
*
>P1;ENSXMAG00000001189

-------------------------------------------------K
VVDHYENPRNVGSLDKNSKKVGTGLVGAPACGDVMKLQIEVDDQGKIVDA
RFKTFGCGSAIASSSLATEWVKGKTLDEALEIKNTDIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQHDDQ-QEAV---RASN
*
>P1;ENSTRUG00000014258

---------MAHV--YLRHPTS------LLLFSRRLFSPQPKVLCSYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIEVDKNGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSIDEALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQDKNR-TEDKE-----S
*
>P1;ENSDARG00000026582

---------MAAS--LAKKCAA-----PQ--ILKTLSAPTLRTQIGYHKK
VVDHYENPRNVGSLDKNAKNVGTGLVGAPACGDVMKLQVEVDEAGKIVNA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTEIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQEGEPVEETA---VARN
*
>P1;ENSONIG00000013921

---------MAGT--VANKCLS-----PLAFLTRRLSAPEFITQCCYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIEVDDQGKIVNA
RFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQQDDQ-QEAV---RASN
*
>P1;ENSGACG00000008801

---------MAMA--SLGSAAS-----SLVLFSRRVLRPELTALCSYHTK
VVDHYENPRNVGTLDKNAKNVGTGLVGAPACGDVMKLQIQVDENGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIRNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRVKQDMEK-NTSS---TNRI
*
>P1;ENSORLG00000006911

---------MAMI--SVRNCAS-----LPSLFCSRLFRPELKSLCSYHKK
VVDHYENPRNVGSLDKNSKSVGTGLVGAPACGDVMKLQIQVDENGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSLDEAMKIKNSDIAKELCLPPVKLHC
SMLAEDAIKAALSDYKIKQDKKE-EHAK---AS-S
*
>P1;ENSXMAG00000018187

---------MAAV--SLRNSGS-----LLSLFSKSFFRPELNALCSYHKK
VVDHYENPRNVGSLDKNKKSVGTGLVGAPACGDVMKLQIQVDENGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQEEKK------------
*
>P1;ENSTNIG00000009075

---------MAGA--VANKCRG-----SLAFLTRTISAPEFFTQCCYHKK
VVDHYENPRNVGTLDKQSKNVGTGLVGAPACGDVMKLQIQVDEQGKIVDA
RFKTFGCGSAIASSSLATEWIKGKSVDEASMIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALADYQLKQQDVQ-QEAV---LSSN
*
>P1;ENSONIG00000013416

FPFAVGAGNMANV--CLRSSSS-----LLLFFSRRIFKPELSAVCLYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIQVDENGKIIDA
KFKTFGCGSAIASSSLATEWVKGKSVDDALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQQDKK-EERV---K--A
*
>P1;ENSGACG00000016973

---------ILLGGVRLFRSATELKVKIPSFITRRLSAPEFITQCCYHKK
VVDHYENPRNVGTLDKSSKNVGTGLVGAPACGDVMKLQIEVDDMGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSVAEALEIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALADYRLKQQDDQ-QEAV---R--A
*
>P1;ENSTNIG00000015868

---------MAGV--YLQKSTS-----SLLLFS-RLFSPQRKVLCSYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIEVDGNGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQDKNR-TEAEKSLPAKN
*
>P1;ENSAMXG00000019258

---------MALS--SMGKCFS-----SFGLFGRTLTGTEAKAVCCYHKK
VVDHYENPRNVGSLDKNARNVGTGLVGAPACGDVMKLQIQVDENGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTEIAKELCLPPVKLHC
SMLAEDAIKAALADYRLKQKDEE-KV-A---EAVN
*
>P1;ENSORLG00000008313

---------MAGT--VMKKCFS-----PLSVLTRRLSVPEYISQCCYHEK
VVDHYENPRNVGSLDKKSKNVGTGLVGAPACGDVMKLQIEVDSQGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQSDGQ-QEAA---KVSI
*
>P1;ENSLOCG00000004690

LAGK-----MAVA--MVKRCCS-----PL-FFFRRLSAPELTVSLPYHKK
VVDHYENPRNVGSLDKNAKNVGTGLVGAPACGDVMKLQIEVDEQGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSIDEALKIKNTEIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQQDND-KT-A---HASN
*
