>P1;ENSXMAG00000016537

--------------------------------------------IMTFEE
VLIQKP------AERAQCAGAALEEVLVSAKDNQSLTVGVYECAKVMNLD
PDSVSFCVLATDEQFEWDVALQIHFTLIQSFCFDNDISIVRVSDTQRLAA
IVGD----EQEDAHCVLIT---VRAGAERRGGLRGAAAQQSYINVLINTN
ITGENELELTEYI--------
*
>P1;ENSTRUG00000015127

---------------------------------------------MTLEE
IHEQENAM--ENTDRVQSAGAALEELLVAAKKQDYITVGVYESAKVMNVD
PDSVAFCVLATDEEYQCDIALQIHFTLIQAFCFDNDINVVRVNDIERLAD
LVGADESGEPKDVHCILVT---SPSANPWK----NP--------SLDKLS
LFCEESRSVYDWVPTITLPER
*
>P1;ENSDARG00000044676

---------------------------------------------M----
----------------VNEGKALSEALLSAKAEGRLTVGVYECAKIMNED
PDSVSFCLLATD-DFECDIALQIHFTLIQAFCFDNDISIVRVNDLKRLNA
LVGG-K-GQLEEAHCVLIT---NPTEDSWE----DP--------ALEKLH
LFCEESRSYNEWVPEITLPER
*
>P1;ENSGACG00000017938

---------------------------------------------MTFEE
VLIQKP------AERAQCTGKALEEVLVSAQDNDALTVGVYECAKVMNLD
PDSVSFCVLAMDEDFQCDIALQIHFTLIQSFCFDNDISIVRVSDTQRVAE
IVGD-K-AQLEDAHCVLIT---NPAEGSWE----DP--------ALEKLH
LFCEESRNVNDWVPEIVLPER
*
>P1;ENSGACG00000006793

---------------------------------------------MTLEE
IRGQENAM--EIPDRVQSAGAALEELLQAAKKQEYLTVGVYESAKVMNVD
PDSVAFCVLATDEEYECDIALQIHFTLIQAFCFDNDINVVRVNDIERLAD
LVSAGEPGEPKDAHCILVT---SPSANPWK----DP--------ALDKLS
GFCEERRSVYDWVPTVTLPER
*
>P1;ENSDARG00000019417

---------------------------------------------MTFEE
LSGQDNTA--TTGDRMQTAGTALEELLVSAKKQDCLTVGVYESAQVMNVD
PDSVAFCVLATDEEYEYDIALQIHFTLIQAFCFDNDINIVRVNDIERLAD
IVGCDQDEEPKDAHCILVT---RPNDDSWK----DS--------ALDKLG
LFCEESRNVYEWVPSITLPER
*
>P1;ENSAMXG00000005863

------------------------------------------S-VMTFEE
VCGQEND----TSDRMRSAGSALEELLLSAKKNDCLTVGVYESAKVMNVD
PDSVAFCVLATDEEYECDMALQIHFTLIQAFCFDNDINIVRVSDIERLAD
IVGNDETGEPKDAHCILVT---NPNLESWK----DP--------SLEKLS
VFCEERRSVYEWVPAITLPER
*
>P1;ENSAMXG00000009069

------------------------------------------L-IMTLEE
VPVQQNN----CIEKARRTGEALQEALESAQANDCLTIGVYESAKVMNVD
PDSVAFCVLAMDEEFECDIALQIHFTLIQAFCFDNDISIVRVSDAQRLAE
LLGD-KAGQLEDAHCVLIT---NPTDGSWE----DP--------ALEKLH
VFCSESRSCHEWVPEVTLPAR
*
>P1;ENSTNIG00000016668

---------------------------------------------MTLEE
IRGQEKDM--ESADRVQSAGAALEELLVAAKKQDYITVGVYESAKVMNVD
PDSVAFCVLATDEEYQCDIALQIHFTLIQAFCFDNDVNVVRVTDIERLAD
IVGADETGESKDVHCILVT---SPSANPWK----NP--------ALDKLG
LFCEESRSVYDWVPTITLPER
*
>P1;ENSONIG00000015195

------------------------------------------IITMTLEE
IHGQENTM--ENADRVQSAGAALEELLIAAKKQDYLTVGVYESAKVMNVD
PDSVAFCILATDEEYECDIALQIHFTLIQAFCFDNDINVVRVNDIDRLAD
LVGADETGEPKDAHCILVTQLQSPSANPWK----DP--------ALDKLS
VFCEERRSVYDWVPTITLPER
*
>P1;ENSORLG00000014766

---------------------------------------------MTFEE
VPIQKP------TERAQCAGKALEEVLETAKDNESLTVGVYESAKVMNLD
PDSVSFCVLAMDEQFQCDIALQIHFTLIQSFCFDNDISIVRVSDMQRLAD
IVGD-KAEELEDAHCVLIT---NPADGSWE----EP--------ALEKLH
LFCEESRRLNDWVPEISLPER
*
>P1;ENSTRUG00000012938

---------------------------------------------MTFEE
VLIQEA------VERVQCTGKALEEVLVSAIENHSVTVGVYECAKVMNVD
PDSVSFCVLAMDEEFECDIALQIHFTLIQSFCFDNDISIVRVSDMQRLAE
IVGN-KADQLEDAHCVLIT---SPAEGSWE----DP--------SLEKLH
LFCEESRRLNDWLPEINLPAR
*
>P1;ENSORLG00000003982

---------------------------------------------MTLEE
INGQCLNEMRFSLFRVQSAGAALEELLLAAKKQDYLTVGVYESAKVMNVD
PDSVAFCVLATDEEYECDIALQIHFTLIQAFCFDNDINVVRVNDIERLAD
LVGADETGEPKDVHCILVT---SPSANPWK----DP--------SLDKLS
LFCEESRNAYDWVPTITLPER
*
>P1;ENSONIG00000012799

---------------------------------------------MTFEE
VLIQKP------AERAQCAGTALEEVLVTAKDNDSLTVGVYECAKVMNLD
PDSVSFCVLAMDEEFECDIALQIHFTLIQSFCFDNDISIVRVSDMQRLVE
IVGD-KAEQFEDAHCVLIT---NPADGSWE----DP--------ALEKLH
LFCEESRRLNDWVPEISLPER
*
>P1;ENSLOCG00000008149

MSTGFEDLKTEARTFRIILRLDLLPRFTHFTFFFLQFTITATC-IMTLEE
VLVQECT-----EARVQSPGKALKDILVSAKAQNCLTVGVYESAKVMNVD
PDSVAFCVLATDEGYEWDIALQIHFTLIQAFCFDNDINIVRVNDIQRLAE
IVGSDESGEPQDAHCILVT---NSADSSFE----DP--------ALEKLN
LFCEKSRGSNEWLPAVSFPER
*
