>P1;ENSAMXG00000011874

----------------------------------------MMRFLLLFSC
QGKLRLQKWFLPTTEREKKKIIRDMTTMVLARKPRTCNFLHWRDLKIVYK
RYASLYFCCGLEDQDNELLALEVLHRYVELLDKYFGSVCELDIIFNFEKA
YFILDEFLMGGEIQETSKQSIAKSIEASDMLQETMEEYMSKPAF------
-----
*
>P1;ENSONIG00000010036

-----------------------------------------MRFMLLFSR
QGKLRLQKWFTSMSDREKKKIIRDMTTMVLARQPRSCNFMQWKDLKIVYK
RYASLYFCLGVESQENELLALEIIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEVQETSKQIVNRSIEASDMLQETLEEYMSKPA-------
----F
*
>P1;ENSDARG00000076073

MWTVPP------------S-------------------GKQMRFLLLFSR
QGKLRLQKWFTVLSDRDKRKIIRDLTQMVLSRPPKACNFLPWRDLKIVYR
RYASLYFCCGLEQDDNELLTLDILHRYVELLDQYFGNVCELDIIFNFEKA
YFILDEFVIGGEVQETSKASVAKSIEEAESLQETMEEYLSKPTY------
-----
*
>P1;ENSXMAG00000015205

-----------------------------------------MRFLLLFSR
QGRLRLQKWYTAISEREKKKIIREMTTMVLARQPRTCNFIQWKDMKIVYK
RYASLYFCLGVEHEENELLALEIIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEIQETSKQIVNRAIESSDMLQETMEEYMSKPA-------
----F
*
>P1;ENSAMXG00000016172

----------------------------------------MMRFLLLFNR
QGRLRLQKWFIPLSNREKNKIVSEMTLTVLARPPKACSFLQWRDLKIVYR
RYASLFFCCGLEDQDNELLTLELLQRYVELLDQYFDNVCELDIIFNFDKA
YFILDEFIMGGEIQETSRLCLARHMEEADAFQETVDEYEKNPTY------
-----
*
>P1;ENSORLG00000009230

LF-------------------------------------FQIHFLLLFSR
QGKLRLQKWFTPLSELEKKKVIRDMTLMVLARPPRTSNFLQWRDLKIVYK
RYASLYFCTGLEEKDNELLALEMIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEILETSKFAVGGSVEEADTLQETMEEYMSKPAY------
-----
*
>P1;ENSGACG00000014035

-----------------------------------------MRFLLLFSR
QGKLRLQKWFTPMSEREKKKIIRDMTTMVLARQPRSCNFLHWKDLKVIYK
RYASLYFCLAIENQENELIALEVIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLIGGEIQETSKQMVNRSIEASDMLQEDVKDTKAPPGGTQC---
TA-YE
*
>P1;ENSTNIG00000014306

L---------------------------------------QMRFLLLFSR
QGKLRLQKWFAPLSEREKKKVTRDMMVLVLGRPPRSCSFLQWRDLKIVYR
RYASLYFCAGLDDHDNELLTLEVLHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEVQETSKVAVAVSMGEADTLQETMEEYMNKPVY------
-----
*
>P1;ENSTRUG00000010174

----------------------------------------QMQFLLLFSR
QGKLRLQKWFTPLTEREKKKVTRDMMMLVLGRPPRSSNFLQWRDMKIVYR
RYASLYFCTGLDDHDNELLALEVLHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEVQETSKLAVALSMEDADTLQEVLQGPLLVLLLNIC---
-----
*
>P1;ENSTRUG00000013671

LETHTH-THIHNPSIEKKK-------------------VLKMRFLLLFSR
QGKLRLQKWFTPMSEREKKKIIREMTSMVLSRQPRSCNFLHWKDLKIIYK
RYASLYFCLAIENQENELLALEVIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEVQETSKQTVNRCIEASDMLQETMEEYMSKPA-------
----F
*
>P1;ENSDARG00000027966

----------------------------------------MMHFLLLFSR
QGKLRLQKWFLPLPERDRKKIVKDMTTMVLARKPRTCNFMHWKDLKIVYK
RYASLYFCCGLENQDNELLALEILHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEIQETSKQSIAKSIEASDMLQETMEEYMSKPAF------
-----
*
>P1;ENSONIG00000014648

MNNVAALESAHDPTVRQGTGILRLQGFITGLQGFIWAAYKMMRFLLLFSR
QGKLRLQKWFTPLTDREKKKVIRDMMMLVLARPPRSCNFLQWRDLKIVYK
RYASLYFCAGLEDKDNELLALEVLHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEILETSKLAVGVSLEEADTLQETLEEYMSKPAY------
-----
*
>P1;ENSTNIG00000000593

----------------------------------------QMRFLLLFSR
QGKLRLQKWFTPMSDREKKKIIREMTSMVLSRQPRSCNFLHWKDLKIIYK
RYASLYFCLAVENQENELLALEVIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEIQETSKQTVNRCIEASDMLQEDDNSDWSLTEEEE----
-V--L
*
>P1;ENSORLG00000015885

----------------------------------------MMRFLLLFSR
QGKLRLQKWFTPITEREKKKIIRDMTTLVLARQPRSCNFLQWKDLKIIYK
RYASLYFCLAVENQENELLALEVIHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEIQETSKQMVNRCI-------------------------
-----
*
>P1;ENSGACG00000000242

-----------------------------------------MRFLLLFSR
QGKLRLQKWFTPLTDREKKKVIRDVMALVLARPPRSCNFLHWRDIKVVYK
RYASLYFCTGLEDQDNELLTLEVLHRYVELLDKYFGNVCELDIIFNFEKA
YYILDEFLMGGEVLETSKVAVSVSMENADTLQEEAGA-LGCPRRE-EEQE
EVGKT
*
>P1;ENSXMAG00000008255

----------------------------------------QLRFLLLFSR
QGKLRLQKWFVPTSEREKKKVIRDMIMLVLPRQPRTCNFLQWKDLKIVYK
RYASLYFCAGLEEHDNELLALEVLHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEVLETSKFAVNVSMEQADTLQETMEEYMSKPAY------
-----
*
>P1;ENSLOCG00000004062

----------------------------------------MMRFMLLFSR
QGKLRLQKWFMAIGEREKKKIIRDMTQMVLARKPKTCNFLTWKDLKIVYK
RYASLYFCCAMEEGDNELLALEILHRYVELLDKYFGNVCELDIIFNFEKA
YFILDEFLMGGEIQETSKLLISKSIEESDMLQETMEEYMSKPAF------
-----
*
