>P1;ENSTRUG00000011903

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTIDVAFPHL
LSGFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSGACG00000009120

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLIFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSXMAG00000001981

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSGACG00000000746

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAELTDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSONIG00000019062

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSAMXG00000016434

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSXMAG00000011177

MYRENSLQQSLKSSRDYHPVLCLLNPAGVLPAVDGSVAAEVRVIMGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSORLG00000007661

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEI-TTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSONIG00000012147

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSTNIG00000014595

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSAMXG00000012959

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSDARG00000036998

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSORLG00000001531

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSTRUG00000011190

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTIVCG----
-LGFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSTNIG00000015063

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--RFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSDARG00000070539

--------------------------------------------MGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAACLYVFATRKEDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
>P1;ENSLOCG00000007812

SHSSRSCQ-------------CPLLPA---PPAEGRT-----AAMGNIFG
NLLKSLIGKKEMRILMVGLDAAGKTTILYKLKLGEIVTTIPTI-------
--GFNVETVEYKNISFTVWDVGGQDKIRPLWRHYFQNTQGLIFVVDSNDR
ERVNEAREELMRMLAEDELRDAV-LLVFAN-KQDLPNAMNAAEITDKLGL
HSLRHRNWYIQATCATSGDGLYEGLDWLANQLKNKK
*
