>P1;ENSGACG00000018437

-MFKNV---FGSGFLVRTAHVILTWVITLILFLHDT--------------
---ELRKQEESGQLVQPVLFVLLVLLSVLLYFAVSLMDPGFYIATSCSEK
FTLGVTEEQQDMIPHTTKSLRQRRCGHCLLQQQPMRSKHCQTCQHCVRRY
DHHCPWIENCVGERNHRWFVLYLAVQLLVLLWALHIAWTGFRHAPGWQLW
LRSNGMLLTVAALVALLSLIVLLLLG-SHVYLVSLNTTTWEFMSRHRISY
LKHCGADENPFDRGTFDNLWCFFCVWGTVVWEQVYFREGSDQV----
*
>P1;ENSTRUG00000005570

-MAQNM---FRSGFLVRTTHTLITWAITLTLFLHNTVNDEKESIQMLIHC
AFPDLRKCEELGELLMPVVFILLVVLSVLLYFAVSLMDPGFVLSDTE--K
GSQDLTEEMESMMES--SAPWLRRCGYCLLQ-QPMRAKHCQICKRCVRRY
DHHCPWIENCVGERNHRWFVIYLLVQLLALLWAFHIALSGLSPSVTWDLW
FRSNGFLLASLVIVGIFSVAVVLLLG-CHLYLVSINCTTWEFMSQHRISY
LKNCDSEYSPFDRGVFCNLWDFFCTCRTVMWEQTFLRKSTSS----I
*
>P1;ENSXMAG00000002879

-MVQSL---FRSGFLVRVGHTVLTWVVTLILFLHNT--------------
---DLRRCEERGELLLPALFFLLVLLSVLLYFTVSLMDPGFVLTDTF--K
GGQGSDEEMELMIPQP-STPRLRRCGFCLLQ-QPMRAKHCKTCKHCVRRF
DHHCPWIENCVGERNHRWFVVYLLVQLLALLWALHIALSGISPGLTWDLW
FRANGFLLAALAVVGVFSGVMLLLLG-CHLYLVSINCTTWEFMSRHRISY
LKNCGGEENPFDRGVFCNLWDFFCICRTVMWEQVYQKNATELNE--F
*
>P1;ENSDARG00000052787

-MFKNV---FGSGFLVRTAHVILTWVITLILFLHDT--------------
---DLRRQEETGELTLPVLFVLLVLVSVLLYFAVSLMDPGFVLTDDCDLQ
FTLGIAEETQDMIPQTTKSIRLRRCGHCLVQ-QPMRSKHCQTCQHCVRRY
DHHCPWIENCVGERNHRWFVLYLAVQFVVLLWGLYMAWSGFSHASTWQQW
LRTNGVLLGAAAVVAILALTVLLLLG-SHLYLVSLNTTTWEFMSRHRISY
LKHCGADENPFDKGILRNLWGFFCAWEPVVWEHVYFKQGNDPI----
*
>P1;ENSTRUG00000013790

-----V---FGSGFVVRTAHVVLTWVITLILFLQDTGKLGPQVH--T--C
SPHRLHLWEETGQLVQPVLFVLLVLVSVLLYFAVSLMDPGFILSEDA-LQ
FPLGVTEEQQDMIQPTSKSLRRRRCGHCLLQQQPMRSKHCQTCQHCVRRY
DHHCPWIENCVGEKNHRWFVLYLLVELLVLLWGLHIACTGFNPTTSWRPW
LHSNGLLLAVVVVVALLSLVVLLLLG-SHLYLISLNTTTWEFMSRHRISY
LRHCGADENPFDRGPAHNLWGFFCVWGTVVWEQVYFRELVEGKSVNI
*
>P1;ENSGACG00000014792

KMVQNM---FRSGFLVRASHTLLTWVITLILFLHDT--------------
---DLRRCEERGELLLPVLFFLLVMLSVLFYFAVSLMDPGFVLSDST--K
Q---ASGEEESMIPQS-STPRPRRCGYCLLQ-QPMRAKHCQTCQRCVRRF
DHHCPWMENCVGERNHRWFLVYLLVQLLALLWALRVALSGLAPGASWDLW
LRANCFLLAALAVLGVFSAVVLLLLG-VHLYLASVNCTTWEFVSRHRVSY
LKNRADERSPFDRGLLCNLWDFFC-----------------------
*
>P1;ENSXMAG00000016743

TMFKNV---FGSGFLVRTAHVVLTWIITLILFLYDT--------------
---ELRKQEETGQLLKPVLFVLLVLVSVLLYFAVSLMDPGFILTEDSDLQ
FTLGVTEEQQDMIPPSTKSLRQRRCGRCLLQ-QPMRSKHCQTCQHCVRRY
DHHCPWIENCVGERNHRWFLLYLALQLLVLLWGLHVAWTGLGHAPSWSRW
LRSNGVLLAVCGLLAPLALVVLLLLG-SHLYLVSMNATTWEFMSRHRISY
LKHCGADQNPFDRGAARNL-GFFCQWGSVVWEQAYFREDSDP----V
*
>P1;ENSAMXG00000012374

-M--RL---FRSGCLVRTTHLILTWVTTLILFLHNT--------------
---DLRKCEERGELLQPVLFFIVVLLSVLMYFTVSLMDPGFVLSDSDT-Q
PSL-EDDELEEMIPNSDVSQRQRRCGYCFLL-QPMRARHCKECKQCVRRY
DHHCPWIENCVGERNHRWFLLYLCVQLLAVSWGLQTAWSGITFVSSWREW
LIQNCFLLGALGVTGVFSVVVVLLLC-IHLYLAAVNTTTWEFMSRHRISY
LKTCDSEENPFDRGLICNLWDFFCVCRTVAWERVYSRRSNSA----V
*
>P1;ENSONIG00000013983

-MVQNV---FRSGFLVRVAHTLLTWIITVILFLHNT--------------
---SLRRCEEQGELLLPALFFLLVVLSVLLYFAVSLMDPGFVLTDTV--K
GAQSPNEEMEAMIPQS-STARVRRCGYCLLQ-QPMRAKHCHMCKRCVHRF
DHHCPWIENCVGERNHRWFIIYLLVQLLTLLWGLHVALSGISPALTWEQW
FRVNGFLLAALCIVGIFSVVVVLLLG-SHLYLISINCTTWEFMSRHRISY
LKTCKDEENPFDRGIFCNLWDFFCICRTVMWEKVYHRNTLNP----V
*
>P1;ENSTNIG00000016721

-MAQNV---FRSGFLVRAAHTLLTWAITLTLFLHNT--------------
---DLRQCEERGELLLPVLFICLVVLSVLLYFAVSLMDPGFVLSDTV--K
SSQDLAEEMESMVET--SAPRLRRCGYCLLQ-QPMRAKHCQTCKRCVRRF
DHHCPWIENCVGERNHRWFVVYLLVQLLALLWAFHIALSGISPRDTWELW
FRSNSFLLASLVLVGVFSLVVLLLLG-CHFYLVSINCTTWEFMSRHRISY
LKHRDSEHSPFDRGVFCNLWDFFCICRTVVWE---------------
*
>P1;ENSTNIG00000002180

NMLRSV---FGSGFAVRTAHVVLTWLITLILFLHDT--------------
---ELRRQEQPGQPGQPVLFVLLVLVSVLLYLAVSLMDPGFILAEDAGLQ
VPLGVTEEQQDMIPPSAASQRRRRCAHCLVQ-QPMRSKHCQACRRCVRRY
DHHCPWMENCVGERNHRWFMLYLLVQLLVLLWGLHIASTGFQAGGAWRPW
LRANDRWFMLYLLVQLLVLLWGLHIGSSHLYLISLNTTTWEFMCRHRISY
LRHCGADQNPFDRGPAHNLWGFFCVWGTVVWEQVYFQEGSDQL---V
*
>P1;ENSAMXG00000015660

-MFKNV---FGSGFLVRTAHVILTWVITLILFLHDT--------------
---DLRKQEETGELLVPVLFVLLVLVSVLLYFAVSLMDPGFVLSDDCDLQ
FTLGLTEEQQDMIPQ-TKTLRLRRCGHCLLQ-QPMRSKHCQTCQHCVRRY
DHHCPWIENCVGERNHRWFVLYLAVQLVVLLWGLHMAWSGFTHAPTWQLW
LKTNSVLLATATVVAVLSLTVLLLLG-SHLYLVSLNTTTWEFMSRHRISY
LKHCGADENPFDRGTLRNLWGFFCVWGTVVWEQVYFRQGCDPT----
*
>P1;ENSDARG00000076632

-MNKSL---FKSGCLVRTAHVILTWIITLILFLHNT--------------
---DLRRCQERGDLLQPLVFSSVLLLSVLLYFTVSLMDPGFVLSDSQTET
ASGDGDEELEAMIPQEQNSIKQRRCGYCFLL-QPMRARHCKWCKRCVRRF
DHHCPWIDNCVGELNHRWFLLYLCVQFTAVCWGLQSAWSGFISAPSWQQW
FTQNVFLLVAFAVTAVFSVVLLLLLC-IHAYLASVNCTTWEFMSRHRILY
LKHVDSEENPFDRGVFCNLWSFCCVCGTVAWEKMYIRHNNAS----V
*
>P1;ENSONIG00000011297

-MFKNV---FGSGFLVRTSHVILTWVITLILFLHDT--------------
---ELRKQEETGQLVQPVLFVLLVLLSVLLYFAVSLMDPGFILSDDTDLQ
FMLGVTEEQQDMIPPATKSLRQRRCGHCLLQ-QPMRSKHCQTCQHCVRRY
DHHCPWIENCVGERNHRWFVLYLAFQLLVLLWGLRIAWTGFTYVPIWHQW
LRTNGVLTAVTMLLALLSLIVLLLLG-SHLYLVSLNTTTWEFMSRHRISY
LKHCGADENPFDRGTFQNLWGFFCVWGTVVWEQVYFKEGSDQV----
*
>P1;ENSORLG00000012692

-RAHWSLDSSSVTFLVRTAHVILTWVVTLILFLYDTGKSIMIFK--QLKV
LPQNLRKQEETGQLIQPVVFVFLVLVSVLLYFAVSLMDPGFILSDNSNLQ
FTLGVTEEQQDMIPPSTKSLRQRRCGHCLLQ-QPMRSKHCQACQHCVRRY
DHHCPWIENCVGERNHRWFVLYLAVQLLVLLWGMHIAWTGWSHAHSWQLW
LRTNGVLLAVTVLLALLSLIVLLLLG-SHFYLISLNITTWEFMSRHRISY
LKHCGADENPFDRGTLQNLWSFFCLWGTVVWEQVYFREESDQVSPME
*
>P1;ENSORLG00000017761

-MVPNM---FRTGFAVRAAHTLLTWVITVTLFLHNTGEPRPPTS--ILSP
PCADLRRCEERGELLPPALFFLLVVVSVILYFTVSLMDPGFVPGDSE--K
GSEASDEESEAMIPRP-LAPQLRRCGFCRLQ-QPMRAKHCRTCRRCVRRF
DHHCPWLENCVGERNHRWFVVYLLVQLLALLWALRTALSGLSPGPTWQQW
LWVNGFLLAALAVVGVFSVVVGLLLG-CHLYLVSINSTTWEFMSRHRILY
LKDCREEDNPFDRGSVCNLWDFFCSCRTVMWEQVY------------
*
>P1;ENSLOCG00000006071

-MFKNV---FGSGFLVRTAHVILTWLTTLILFLHDT--------------
---DLRRQEENGEQLQPVLFVLLVLASVLLYFAVSLMDPGFVLSDSD-AT
FTLGVAEEQQEMIPPVSKAPRQRRCGFCLLQ-QPMRAKHCQTCKRCVRRY
DHHCPWIENCVGERNHRWFVLYLLVQLLALLWGVNLAWSGFSYAPTWKTW
LRQNGFLLAAFLVAAVFVLVVALLLG-SHLYLVSLNTTTWEFMSRHRISY
LKHCGADENPFDRGVPRNLRDFFCVCRAVAWEEVYFRQGSDP----V
*
