>P1;ENSGACG00000020514

--------------------NRIRLHYDSSINRKVQKH--LLS-LSCFSP
NAALHVKDGFHPQVKAACQLQKTDT-----VS-FNLAKVIVVGDVAVGKT
CLISRFRKGAFEKNYKATIGVDFEMERFEVLGVPYSLQLWDTAGQERFKC
IASTYYRGAQAIIVVFDLSSVSSLAHARQWLEDAMRENDPSSVLLFLVGT
KKDLSSPDQLVQIEQEAIRLSEEIKAEYWAVSAKSGDGVRDFFFRVASLT
FEANVLSEIEKSGTRHIGDIIRLTDSTEADCQP-TKRKSNCC--------
------------------
*
>P1;ENSGACG00000011190

MSLRV-------------SAMS-------V-LPPVRKDRIVAQLPRYFRE
EAAFHTADDFNSKVKTACQEQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDAFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQVVIIAFDVNDVASLGHVRQWLEDALRENDPTAVQLFLVGT
KKDLSSPAQYSQIEQDALKLAHEMRAEYWAVSSLTGENVKEFFFRVASLA
FETNVLAELEKSGPRQIGGVVRINSTSNNVYASSKKKQTNCC--------
-----------------Q
*
>P1;ENSTRUG00000005937

--------------------MS-------V-LPPIRKDRVIARLPQCFRK
EAALHTKEDFNNKVKTACQEQRTGT-----VGRFKISKVIVVGDLAVGKT
CLINRFCKDVFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQVVIIAFDVNDIGSFSHVRQWLEDSLKENDPTAVQLFLVGT
KKDLSSPAQYSQMEQEALKLAQELSAEYWAVSSLTGENVNEFFFRVASLA
FETSVLAELEKSGSRQIGEVVRISSNSSNLNRSSKKKQSNCC--------
-----------------Q
*
>P1;ENSDARG00000010977

M-------------------MN-------S-LPPVKGDRIICELPLYFTR
DAAVHTKDGFNITVREACQGQKTG---------LNVAKVIVVGDVGVGKT
CLINRFCKDSFDRTYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFRC
IASTYYRGAQAIIVVFDLSNYESLDHAREWLEDAMRDNDPSSVLLFLVGT
KKDLSHPDLLAQMEQEAIRLSEEIRAEYWAVSALSGASVRDFFLRVASLT
FEATVLSELEKNNSRRAGDIVKISNNCDNN---FKKRQSSCCH-------
------------------
*
>P1;ENSTNIG00000016231

--------------------MS-------V-LPPVRKDRVIARLPQCFRK
DAALHTKEDFSNKVKTACQEQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDVFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQVVIIAFDLNDIGSFSHVRQWLEDSLKENDPTAVQLFLVGT
KKDLSVPARYSQMEQDALKLAQEISAEYWAVSSLTGENVNEFFFRVASLA
FETSVLAELEKSGSRQIGQVVRINSDSRNLYTSSKKKQSNCC--------
-----------------Q
*
>P1;ENSXMAG00000011898

MSLRV-------------SGMS-------V-FPPVRRDRIIAQLPQAFRK
EAALHVTEEFNNKVRTACQEQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDAFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQVVIIAFDVNDIASLGHARQWLEDALKENDPTSVQLFLVGT
KKDLSSPAQYSRIEQDAVKFAREIHAEYWAVSSLTGENVKEFFFRVAGLA
FETNVLAELEKSGSRQIGDVVRINSTSSNLCTTTKKKQANCC--------
-----------------Q
*
>P1;ENSTNIG00000016158

--------------------TS-------M-LPPAKNDRIITQFPKCFSP
SAALQTKPGFHPQVKALCKTHKSGT-----VN-CNVAKVIVVGDVSVGKT
CLISRFCKGFFEKNYKATIGVDFEMERFEVLGVPFSVQLWDTAGQERFKC
IASTYYRGAQAIIVVFDLSSVTSLAHARQWLEDAMKENDPSSVLLFLVGT
KKDLSSPDQLYQTEQEAIRLSEEIKAEYWAVSAKSGDGVRDFFFRVASLT
FEAIVLSELETGGSKHVGDIVKLTDTGEDPDQP-PKKKPNCC--------
-----------------R
*
>P1;ENSORLG00000003119

MRGVLVTATTECVSVTLKTCRS-------M-LPPVKKDRVITHLPKCFSP
HAALHTKEGFHPKVKAACQTQRARA-----LS-FNVAKVIVVGDVAVGKT
CLISRFCKGVFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQAIIVVFDLSSVTSLAHARQWLEDAMKENDPSSVLLFLAGT
KKDLSTPDQLNYIEQEAIRLSEEIKAEYWAVSAKSGDGVRDFFLRVASLT
FEANILAEIEKSGSRQVKDIVRNSLSSSRN--Q-SERIPTLC--------
-----------------R
*
>P1;ENSONIG00000013175

MSVRI-------------SAMS-------V-LPPVRRDRVIAQLPQCFRK
EAAIHTKNDFNNKVKTACQEQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDTFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQVVIIVFDVNDIASLGHARQWLEDALKENDPTAVQLFLVGT
KKDLSSPAQYSQIEQDALKLANEIQAEYWAVSSLTGENVREFFFRVASLA
FETNVLAELEKSGSRQIGDVVRINSNSNSLYAASKKKQSNCC--------
-----------------Q
*
>P1;ENSAMXG00000004005

--------------------MS-------V-LPPVRKDRVIPQLPKFFNE
GAALHTEDEFDTKVKTACQEQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDAFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQAVIIVFDLTDVASLQHTRQWLEDAMKENDPTNVLLFLVGT
KKDLSSPAQYSLIEEDAVKMAAEIKAEYWAVSSLSGENVREFFFRVASLT
FESNVLAELEKSGSRRIGEVVKINSNSPNLYATNKKK-QNCC--------
-----------------H
*
>P1;ENSAMXG00000006018

--------------------MS-------S-LPPIRDDRIICELPLYFTK
DAALHTKDGFHVTVQNACQTQTSDP-----MG-FNVAKVIVVGDVGVGKT
CLINRFCKDTFDKGYKATIGVDFEMERFKVLGVPFNLQLWDTAGQERFKC
IASTYYRGAQAIIVVFDLSNYYSLVNARQWLEDAMIDNDPSSVLLFLVGT
KKDQSHPDLLAQMEEEAIKLSEEIKAEYWAVSALSGESVRQLFLRVASLT
FEASVLAELERKNTRHADNVVKITGDHNDF---RKKKQSNCCN-------
------------------
*
>P1;ENSDARG00000045628

--------------------MS-------V-LPPVRKDRIIGQLPKCFNR
GAALNTENEFHSKVKTACQQQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDVFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQAVIIVFDLTDVASLEHTRQWLEDAMKENDPTSVLLFLVGT
KKDLSSPAQYSLIEQDAIKIADQMKAEYWALSALSGENVRDFFFRVASLT
FEANVLAELEKSGSRRIGEVVQISSNSNNLYATSKKKQSNCWRRPKSGIS
SKGELCREQCGLLFRGCN
*
>P1;ENSTRUG00000014481

--------------------TN-------M-LPPVKNDRIITRFPKCFSP
NAALQTKDSFHPQVKALCQTQKSAT-----VN-CNIAKVIVVGDVAVGKT
CLISRFCKGFFDKNYKATIGVDFEMERFEVLGVPFSVQLWDTAGQERFKC
IASTYYRGAQAIIVVFDLSSVTSLTHARQWLEDAMKENDPSSVLLFLVGT
KRDLSTADQLCQTEQEAIRLSEEIKAEYWAVSAKSGDGVRDFFFRVASLT
FEAVVLSELESSGSKHVSDIVKLTDASEGAERL-SKKKPNCCFC------
-----------------P
*
>P1;ENSXMAG00000014225

---------------------S-------M-LPPVKKDRIITHLPKCFSP
NAALHTKDGFHPQVRAACQVQKTDGESQSLQS-FNIAKVIVVGDVSVGKT
CLISRFCRGAFDRTYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQAIMVVFDLSSVNSLAHAREWLEDAMKENDPSSVLLFLVGT
KKDLSSPDQLAETEQEAIRLSEEIKAEYWAVSAKSGDGVRNLFLRVASLT
FEANVLAELERSGSRHVKDIIRITDSSEAN-HK-QKKKANC---------
-----------------C
*
>P1;ENSONIG00000005519

--------------------IS-------M-LPPVKKDRVITQLPKCFSA
NAALHTKEGFHPHVKAACQVQKAGI-----VS-FNVAKVIVVGDVAVGKT
CLISRFCKGAFEKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQAIIVVFDLSSVGSLAHARQWLEDAMKENDPSSVLLFLVGT
KKDLSSPDLLAQIEQEAMRLSEEIKAEYWAVSANPGDGVKDFFFRVASLT
FEANVLSELERSGSRHVGDIISESTLFSGCYLFLEKTQIVLC--------
-----------------P
*
>P1;ENSORLG00000004394

--------------------MS-------V-LPPVRRDRIIAHLPQPFRQ
EAAVHITGDFNNKVKTACQEQRTGT-----VGRFKISKVIVVGDLAVGKT
CLINRFCKDAFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQVVVIVFDLNDIASLDHSRQWLEDALKENDPTSVQLFLVGT
KKDLSSPAQYSLIEQDALRLAKEIHAEYWAVSSLTGENVREFFFRLASLA
FETNVLAELEKSGSRQIGDVVRINSTSSNLSASSKKKQPNCC--------
-----------------Q
*
>P1;ENSLOCG00000005802

LRAHG-------------SAMS-------V-LPPVRRDRVIPALPQCFSK
DAALHTKDSFHPKVKTACQEQRTGT-----VG-FKISKVIVVGDLAVGKT
CLINRFCKDTFDKNYKATIGVDFEMERFEVLGVPFSLQLWDTAGQERFKC
IASTYYRGAQAIIIVFDVNDVASLAHAKQWLEDALKENDPATVLLFLVGT
KKDLSSPAQYLLIEQDAITLAKEIKAEYWAVSALTGENVKEFFFRVASLT
FEANVLAELEKSGSRRIGDVVRINSSSSNTYVTSKKKQASCCQ-------
------------------
*
