>P1;ENSORLG00000001850

----METIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHNWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTQHEAEKLAGA
YGMRYVETSARDAINVEKAFVDLTRDIFELVRNGDIKIQDGWEGV-----
----------KSGFVPNTVHSSEEVTK-----------------------
--------------------------------------GS----------
--------RQCFC-----
*
>P1;ENSTNIG00000018228

----METIWLYQFRLIVIGDSTVGKSCLI-RFTEGRFAQASDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHNWLEEAQSHVQPHHIVFLLVGHKCDLEALRQVPRQEAERLAGA
FGMRYVETSALDAINVEKAFVDLTRDIFELVRSGDIKIQDGWEGV-----
----------KSGFVPNTVHSSEEVAK-----------------------
--------------------------------------GN----------
--------RQCLC-----
*
>P1;ENSONIG00000006997

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHDWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTRQEAEKLAGA
YGMRYVETSARDAINVEHAFTELTRDIFALVRSGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSTRUG00000003696

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHDWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVCIAAAPQIRAT
-DPYFPPSTLRSALPGDPPGSREVGGGVRHALRGDVRPRRHQRGARLHRA
DERHLRPGAVRRHHDPGGLGGREERLRPQRGALLGGSDEERPPLPMLIRE
RSRGQSGKGGRRTRLEGTVTRIRGVDPSTEGTAGNVAGDDYLSLFNTSFS
STTYITLQKTCTANQAGR
*
>P1;ENSGACG00000001950

---VMEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRVKLQIWDTAGQERFS-RSITRAYYRNSVGGLLLFDITNR
RSFQNVHDWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTRQEAEKLAGA
YGMRYVETSARDAINVEHAFTELTRDIFALVRSGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSAMXG00000005906

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHEWLEEARSHVQPHSIVFLLVGHKCDLDAQRQVSQQEAEKLAAA
YGMRYVETSARDAINVERAFTELTRDIFELVKRGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSTRUG00000009928

----METIWLYQFCLIVVGDSIVGKLCLIRRFTEGRFAQVSDPTVGVDFF
SRLVESDPGKRIKLQIWDTAGQERF--RSITRTYYRNSVGGLLLFNKKRP
KR-------------PQLPHTIVFLLVGQKCDLEALRQV-RQEAEKLVGT
FRMCYVETSVLDAINVEKAFVDLTRDIFLLIQSGDIKIQNGWEGV-----
----------KSGFVPNIIHSSEEVSK-----------------------
--------------------------------------GN----------
--------HQCLC-----
*
>P1;ENSXMAG00000001480

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHDWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTRQEAEKLAGA
YGMRYIETSARDAINVEHAFTELTREIFALVRSGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSDARG00000019312

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHEWLEEARSHVQPHSIVFILVGHKCDLEQQRQVSQQEAEKLAAA
YGMRYVETSARDAINVEKAFTELTRDIFELVKCGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSDARG00000036501

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHEWLEEARSHVQPHSIVFLLVGHKCDLEPQRQVSQQEAEKLAAA
YGMRYVETSARDAINVERAFTELTRDIFELVKNGEISIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------GD----------
--------RRCFC-----
*
>P1;ENSAMXG00000003717

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHEWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTRQEAEKLAAA
YGMRYVETSARDAINVERAFTELTRDIFELVKHGEITIQEDWEGV-----
----------RSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SE----------
--------RRCFC-----
*
>P1;ENSXMAG00000000325

----METIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHNWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTQHEAEKLAGA
YGMRYVETSARDAINVEKAFVDLTREIFELVRSGDIQIQDGWEGV-----
----------KSGFVPNMVHSSEEVTK-----------------------
--------------------------------------GS----------
--------RQCFC-----
*
>P1;ENSTNIG00000003679

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERFRCRSITRAYYRNSVGGLLLFDITNR
RSFQNVHDWLEEARSHVQPHSIVFLLVGHKCDLEAQRQVTRQEAEKLAGA
YGMRYVETSARDAINVEHAFTELTRDIFALVRSGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSONIG00000008545

----METIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHNWLEEAQSHVQPHSIIFLLVGHKCDLEAQRQVTQQEAEKLAGA
YGMRYVETSARDAINVEKAFVDLTKDIFELVRNGDIKIQDGWEGV-----
----------KSGFVPNTVHSSEEVTK-----------------------
--------------------------------------SS----------
--------RQCYC-----
*
>P1;ENSGACG00000020437

----METIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEVEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHNWLEEAQSHVQPHNIVFLLVGHKCDLEEQRQVSQQEAEKLAGA
YGMRYVETSARESVNVEKAFVDLTRDIFELVRSGDIKIQDGWEGV-----
----------KSGFVPNIVHSSEEVTK-----------------------
--------------------------------------GA----------
--------RQCFC-----
*
>P1;ENSORLG00000008345

----MEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIETGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHDWLEEARSHVQPHTIVFMLVGHKCDLETQRQVTQQEAEKLSGA
YGMRYIETSARDAINVEHAFTELTRDIFDLVRSGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVTK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
>P1;ENSLOCG00000014927

MLDNMEAIWLYQFRLIVIGDSTVGKSCLIRRFTEGRFAQVSDPTVGVDFF
SRLVEIEPGKRIKLQIWDTAGQERF--RSITRAYYRNSVGGLLLFDITNR
RSFQNVHEWLEEARSHVQPLQIVFVLVGHKCDLEAQRQVGRQEAEKLAGA
YGMRYVETSARDAINVEKAFTELTRDIFELVKRGDITIQEGWEGV-----
----------KSGFVPNVVHSSEEVMK-----------------------
--------------------------------------SD----------
--------RRCLC-----
*
