>P1;ENSTRUG00000004965

------------------------QAPKKAKRRQQQGEGGSSNVFSMFEQ
SQIQEYKE----------------------------------AFTIIDQN
RDGIISKDDLRDVLATMGQLNVKNEELEAMVKEASGPINFTVFLTMFGEK
LKGADPEDVIVSAFKVLDPEGTGSIKKEFLEELLTTQCDRFTAEEMANLW
AAFPPDVAGNVDYKNI----------------CYVITHGEDKEEE-----
--------------------------------------------------
------------------
*
>P1;ENSONIG00000015965

------------------------MAPKKAKKR---AEGASSNVFSMFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEEIDDMLKEAPGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGKGTLKKEFVTEMLTTQADRFSAEEMEQMF
QAFPPDVAGNLDYKNL----------------VYVITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSORLG00000005736

------------------------MAPKKAKRRQQQGEGGSSNVFSMFEQ
SQIQEYKE----------------------------------AFTIIDQN
RDGIISKDDLRDVLATMGQLNVKNEELEAMVKEASGPINFTVFLTMFGEK
LKGADPEDVIVSAFKVLDPEGTGSIKKEFLEELLTTQCDRFTPEEMTNLW
AAFPPDVAGNVDYKNI----------------CYVITHGEDKE-E-----
--------------------------------------------------
------------------
*
>P1;ENSXMAG00000004161

------------------------QSPKKAKKR---ADGASSNVFSMFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEEIDDMLKEAPGPVNFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGTGTLKKDYVTEMLTTQADRFSAEEMEQMF
VAFPPDVAGNLDYKNL----------------VHIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSAMXG00000006952

------------------------MGD-----------------------
--FKDYDT----------------------------------KI------
-------IIFLIVFGITGRLNVKQEEIDDMLKEASGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGKGVLRKEYVTEMLTTQADRFSKEEMEQMF
TAFPPDVSGNLDYKNL----------------VHIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSONIG00000011532

SLLPLSLTIPQLCFPAKPDAYIISQAPKKAKRRQQQGEGGSSNVFSMFEQ
SQIQEYKEVTFSSSHLKLSIRILLRDTRSLTPLECGPTAGAQAFTIIDQN
RDGIISKDDLRDVLATMGQLNVKNEELEAMVKEASGPINFTVFLTMFGEK
LKGADPEDVILSAFKVLDPEGTGTIKKEFLEELLTTQCDRFTAEEMKNLW
AAFPPDVAGNVDYKNI----------------CYVITHGEDK--E-----
--------------------------------------------------
------------------
*
>P1;ENSTRUG00000015827

------------------------QAPKKAKKR---AEGAGSNVFSMFEQ
TQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEELDEMLKEAPGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGKGTLRKDFVTDMLTTQADRFSPEEMEQMF
AAFPPDVAGNLDYKNL----------------VYVITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSORLG00000015964

TASK--------------------MAPKKAKKR---SEGASSNVFSMFEQ
TQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEEIDDMLKEAPGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGTGTLKKDFVTEMLTTQADRFSAEEMEQMF
VAFPPDVAGNLDYKNL----------------VHIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSTNIG00000011452

SLSPL-------------------QAPKKAKKR---AEGAGSNVFSMFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEELDEMLKE-PGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGKGTLRKDFVTDMLTTQADRFSPEEMEQMF
AAFPPDVAGDLDYKNL----------------VYVITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSDARG00000104722

------------------------MAPKKAKKRA--AEGANSNVFSMFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEEIDEMLKEASGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGKGILKKEYVTEMLTTQADRFSPEEMEQMF
SAFPPDAAGNLDYKNL----------------VHIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSGACG00000007182

------------------------MAPKKAKRRQQQGEGGSSNVFSMFEQ
SQIQEYKE----------------------------------AFTIIDQN
RDGIISKDDLRDVLATMGQLNVKNEELEAMVKEASGPINFTVFLTMFGEK
LKGADPEDVIVTAFKVLDPEATGSIKKEFLEELLTTQCDRFTAEEMTNLW
AAFPPDVAGNVDYKNI----------------CYVITHGEEKEEE-----
--------------------------------------------------
------------------
*
>P1;ENSGACG00000013491

LQKRP-------------------QAPKKAKKR---ADGAGSNVFSMFEQ
ARIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEEIDEMLKEAPGPINFTIFLTMFGEK
LKGADPEETILNAFKVFDPEGKGSLKKDFVTDMLTTQADRFSPEEMEQMF
AAFPPDVAGNLDYNNL----------------VHIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSDARG00000053424

------------------------MAPKKAKKR---AEGANSNVFSMFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEELDEMLKEAPGPINFTVFLTMFGEK
LKGADAEETILNAFKVFDPEGKGTLRKDFLSRMLTTQADRFSPEEMEQMF
SAFPPDAAGNLDYKNL----------------VYIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSTNIG00000000835

------------------------MAPKKAKRRQQQGEGGSSNVFSMFEQ
SQIQEYKE----------------------------------AFTIIDQN
RDGIISKDDLRDVLATMGQLNVKNEELEAMVKEASGPINFTVFLTMFGEK
LKGADPEDVIVSAFKVLDPEGTGSIKKEFLEELLTTQCDRFTAEEMANLW
AAFPPMWLATWTTRTSATSSHTERTRRSKSPSFTILTSGQTLKLAPPSPR
SPPFPPTPWLPRTPSRPIPSPLSFPSRKDLSHFSRRSMRGLAAVGVLVCE
QQQRIMGLFSKIKIILWH
*
>P1;ENSAMXG00000006106

----------------------------------------------MFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQDEIDEMLKEAPGPINFTVFLTMFGEK
LKGADPEETILNSFKVFDPEGKGYLRKDFVTEMLTTQADRFSPEEMEQMF
TAFPPDVSGNLDYKNL----------------VYIITHGEEKDQE-----
--------------------------------------------------
------------------
*
>P1;ENSXMAG00000018436

------------------------MSPKKAKRRQQQGEGGSSNVFSMFEQ
SQIQEYKE----------------------------------AFTIIDQN
RDGIISKDDLRDVLATMGQLNVKSDELEAMVKEASGPINFTVFLTMFGEK
LKGADPEDVIVSAFKVLDPEGTGSIKKEFLQELLTTQCDRFTSEEMTNLW
AAFPPDVAGNVDYKNI----------------CYVITHGEDKE-E-----
--------------------------------------------------
------------------
*
>P1;ENSLOCG00000007405

------------------------MSPKKAKKR---AEGANSNVFSMFEQ
AQIQEFKE----------------------------------AFTIMDQN
RDGFIDKNDLRDTFAALGRLNVKQEEIDEMLKEAPGPINFTVFLTMFGEK
LKGADPEETILNAFKVFDPEGKGILKKDYVTEMLTTQADRFSPEEMEQMF
TAFPPDVSGNLDYKNL----------------VYIITHGEDKDQE-----
--------------------------------------------------
------------------
*
