>P1;ENSONIG00000010659

MCILARY-------HRLP--SSLAL-LILLVACTMGCIQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGVVMPPVPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTLTGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVAMNSVTKERIVLQTVRWRMRVDIAVDPDMPLGSRASLVGRP
YQEQPHILNYQEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPPK----
-------
*
>P1;ENSDARG00000063018

MNILLKF-------ILIF--PSLAT-LTPLISRTMGCIQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGIVMPPVPRNET
WTVGWIQACTQMEFFNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTLSGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVALNADTKERIVLQTVRWRMRVDIEVDPSMPLGSRAKLMGRP
HQEQPHILSNNEPIPPNALGRPNANDAQVLMWRPRRGQPLVVIPPK----
-------
*
>P1;ENSGACG00000012489

FPGP----------GGLT---WLLL-TVTFTFTAMGCIQSIACNKSRLKR
ENIVVCDLSATIDHCPTVIEENSPIVLRYKTPYFKASARVVVPPLPRNET
WVVGWIQACTQMEFYNTYGDVGMSSWELPQLREGLVRAISDSDGVSYPWY
GNTTETVTIVGPTSKPSRFVVSMNDNFYPSVTWAVPVSESNTPLLTNIKR
DQSFTTWLVALNTTSREKILLHTIKWRMRVDVAVDPSLPLGSRARLVGRV
HQDQPRVLSRMEPIPPNAMGRPNANDAQVLMWRPRRGPPLVVIPSK----
-------
*
>P1;ENSXMAG00000012912

MYGLIVLILVESQPAARF---PGPV-RFSFSCAVMGCIQSIACNKSRIKR
ENIVVHDLSATIDHCPTVIEENSPIVLRYKTPYFKAAARIVMPPIPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPQLREGLVRAISDSDGISYPWY
GNTTETVTIVGPTSKPSRFTVSMNDNFYPSVTWAVPVSESNTPLLTNIKR
DQSFTTWLVALNTTSKEKILLHTIKWRMRVDIVVDPAQPLGSRARLVGRL
YQEQPRVLSRMEPVPPNAMGKPNANDAQVLMWRPRRGPPLVVIPPK----
-------
*
>P1;ENSTNIG00000006642

---------------------------------AMGCIHSLACSKSRVKR
ENIVVYELSATIDHCPTLIEESSPIVLRYKTPYFKASARVVMPPIPRNET
WVVGWIQACTQMEFYNTYGDVGMSSWELPQLREGLVRAISDSDGVSYPWY
GNTTETVTIVGPTSKPSRFIVSMNDNFYPSVTWAVPVSKSNTPLLTNIKR
DQSFTTWLVALNTTSKEKILLHTIKWRMRVDIVVDPTLPLGSRARLVGRM
HQDQPRVLTRMEPIPPNSMGKPNANDAQVLMWRPRRGPPLVVIPPNH---
------P
*
>P1;ENSAMXG00000016600

CRS------------------PA-Q-VKTCPSCTMGCIHSIVC-KSRVKR
ENIVVYDVTATIDNTPTAIEENSPIVLRYKTPYFKASARVMMPPIPRNET
WVVGWIQACTHMQFHNNYGEIGMSSWEIPELRDGVVRAISDSDGVSYPWY
GNTTETVTLSGPMAKPSRCIVSMNDNFYPSVTWAVPVSESNVPRLTHITR
DQSFTTWLVALNAATREKILLQTVKWRMRVEIAVDPTMPLGSRARLVGPP
NQDQPKVLTHMEPIPPNAMGKPNANDAQVLMWRPKRGNPLIVIPSK----
-------
*
>P1;ENSORLG00000004207

GCA------------------ASLW-SQPRTRAAMGCIQSIACNKSRIKR
ENILVQDLSATIDHCPTVIEENSPIVLRYKTPYFKASARVVMPPIPRQDT
WVVGWIQACTQMEFYNTYGDIGMSSWELPQLREGLVRAISDSDGVSYPWY
GNTTETVTIVGPTSKPSRFTVSMNDNFYPSVTWAVPVSESNTPLLTNIKR
DQSFTTWLVALNTTSREKILLHTIKWRMRVDVMVDPSQPLGSRARLVGRL
YQDQPRVLARMEPVPSNAMGKPNANDAQVLMWRPRRGPPIVVIPPNH---
------R
*
>P1;ENSGACG00000015993

LPC---R--------RFD--MTAVL-LILLVACTMGCIQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGVVMPPVPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPELRECRVKAISDSDGVSYPWY
GNTTETVTLTGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVAMNSISKERIVLQTVRWRMRVDIAVDPDMPLGSRASLVGRH
YQEQPHILNYQEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPPK----
-------
*
>P1;ENSXMAG00000004478

MSILPRH-------HLVP--PSLFL-LLLLVACTMGCLQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGVVMPPVPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTLTGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVAMNSVTKERIVLQTVRWRMRVDIAVDPDMPLGSRASLVGRP
YQEQPHILNYQEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPPKQK--
-----HR
*
>P1;ENSTRUG00000002265

MFSSPWS-------GSCWSKCQQVF-LILLVACTMGCIQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGVVMPPVPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTLTGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVAMNSVTKERIVLQTVRWRMRVDIAVDPDMPLGSRASLSGPP
YQEQPHILNYQEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPP-----
-------
*
>P1;ENSORLG00000004524

QMS--RY--------HCL--PSLLS-LIALAVCRMGCIQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGVVMPPVPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTLTGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVAMNSVTKERIVLQTVRWRMRVDIAVDPDMPLGSRASLVGRP
YQEQPHILNYQEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPPKGHWH
TLNWRPR
*
>P1;ENSTRUG00000017806

LPRN----------VRLS---WLLL-SITFTCTTMGCIQSIACNKSRVKR
ENIVVYDLSATIDHCPTLIEENSPIVLRYKTPYFKASARVVMPPIPRNET
WVVGWIQACTQMEFYNTYGDVGMSSWELPQLREGLVRAISDSDGVSYPWY
GNTTETVTVVGPTSKPSRFVVSMNDNFYPSVTWAVPVSESNTPLLTNIKR
DQSFTTWLVALNTTSKEKILLHTIKWRMRVDIVVDPTLPLGSRARLVGRM
HQDQPRVLTRMEPIPANAMGRPNANDAQVLMWRPRRGPPLVVIPPK----
-------
*
>P1;ENSDARG00000062889

----------------------------------MGCLQSVAC-KPRIKR
ENIVVYDVSATIDHCPTVIEENSPIVLRYKTPYFKASARIVMPPIPRNET
WVVGWIQACTQMEFYNTYGDLGMSSWELPELREGLVKAISDSDGLSYPWY
GNTTETVTLSGPTSKPSRFTVSMNDNFYPSVTWAVPVSESNVPLLTRIKR
DQSFTTWLVALNVTTQEKILLQTVKWRMKVDIAVDPSKPLSSRARLIGRV
HQDQPKVLTHMEQIPPNALGKPNANDAQVLMWRPKRGPPLVVIPSK----
-------
*
>P1;ENSONIG00000004750

----------------------------------MGCIQSIACNKSRIKR
ESIVVCDLSATIDHCPTVIEESSPIVLRYKTPYFKASARIVMPPVPRNET
WVVGWIQACTHMEFYNTYGDVGMSSWELPQLREGLVRAISDSDGVSYPWY
GNTTETVTIVGPTSKPSRFIVSMNDNFYPSVTWAVPVSESNTPLLTNIKR
DQSFTTWLVALNTTSREKILLHTIKWRMRVDIAVDPSLP-----------
--------------------------------------------------
-------
*
>P1;ENSAMXG00000018730

MNVLVRC-------ILIC--PSLVTLLTLLIARAMGCIQSIAC-KPRVRR
ENIVVYDVSASIDQCPTVIEENSPIVLRYKTPYFRASAGIVMPPVPRNET
WTVGWIQACTQMEFYNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTISGPTSKPSRLTVSMNDNFYPSVTWAVPVSNSNAPMLTRITR
DQSFITWLVALNNATKERIVLQTVRWRMRVDIAVDPSMPLGSRASLVGRA
HQEQPHILANNEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPSK----
-------
*
>P1;ENSTNIG00000007832

PQG-----------DRCA--YWPVF-LVLLVACTMGCIQSIAC-KPRIRR
ENIVVYEVSASIDQCPTIIEENSPIVLRYKTPYFRASAGVVMPPVPRNET
WVVGWIQACTQMEFYNTYGDIGMSSWELPELREGRVKAISDSDGVSYPWY
GNTTETVTLTGPTSKPSRLTVSMNDNFYPSVTWAVPISNSNTPMLTHITR
DQSFITWLVAMNSVTKERIVLQTVRWRMRVDIAVEPDMPLGSRASLAGAP
YQEQPHILNYQEPIPPNALGRPNANDAQVLMWRPRRGAPLVVIPSKH---
------Q
*
>P1;ENSLOCG00000010200

LIYSLI--------YLFM---PLPV-YLLLPWLTMGCIQSITC-KSRIKR
ENIVVYDVSATIDQCPTVIEENSPIVLRYKTPYFKASARVVMPPVPRNET
WVVGWIQACTQMEFYNTYSDIGMSSWELPDLREGRVKAISDSDGVSYPWY
GNTTETVTLIGPTSKVSRFTVSMNDNFYPSVTWAVPVSDSNLPLLTRIKR
DQSFTTWLVALNTGTKEKILLQTIKWRMRVDIEVDPSQPLGSRARLVGRI
QQDQPRILTRMEQIPSNALVKPNANDAQVLMWRPKRGLPLVVIPPK----
-------
*
