>P1;ENSORLG00000010187

-------------------MAPAQSVFLLAVHVLLISEFILAKRDYYDIL
GVPKDATERHIKKAFHKLALKYHPDRNKGPDAEAKFREIAEAYETLSDDK
RRREYDQFGHSASSTDGPGGEG-------SGHYNFKQHYQ--SFNFDDIF
KDFDAFGQ-QR-HQHHFHSHNQAHQKRQFDGHFQAHREAMNKQRRVFQHS
SFGGGVFDDMFEDLEKMFSFN------GHASRTDGRFQGSAKQHCRTVTQ
RRGNMVTTFTDCS--
*
>P1;ENSTRUG00000016807

-------------------MATVQSVLLLAVHVLLISEFILAKRDYYEIL
GVPKDATERQIKKAFHKLALKYHPDRNKGPDAEAKFREIAEAYETLSDDK
RRQEYDQFGHGPSPGDGHRGGGGA----DGGNYNFRQHFQ--SFNFDDIF
KDFSHQ----H-HQHHFHSQNQANHKRHFDSHFQAHQEAMNRHRRQVHRE
GFGGGLFDNMFEDLEKMFSFN------TH--RSESRFQGSAKQHCRTVTQ
RRGNMVTTFTDCS--
*
>P1;ENSGACG00000004142

-------------------MATAQSAVTFAVCIFVIAELILAKKDYYDIL
GVPKDATERQIKKAFHKLAMKHHPDKNKSPDAEVRFREIAEAYETLSDET
KRREYDQFADTSAYFPGKTQGR--------QRQGAHQPF---SFNLNDIF
KDFDTSSQ-NR----------HTRQQRHFNEDSGSHKESNGRHKRHFQ-G
GFGAGVFDDMYDDIERMFTYD------RHAKQSDNRFHGASKQHCRTVTQ
RRGNMVTTYMDCTAS
*
>P1;ENSXMAG00000017111

-------------------MAAVQSVLMFAVCVLVITELILAKKDYYDIL
GVPKGATERQIKKAFHRLAMKFHPDKNKSPDAEVRFREIAEAYEVLSDES
RRREYDQFGDDMYTGQTQRA-------------GTHQPF---TFNFDDMF
KDFNIYSQ-NR----------HSRHRRHFEEHSKSHKESHSRRRRHFQ-G
GFGAGILDDMFDDMDRMFTFD------RHAKQTEGRFHGTTKQHCRTVTQ
RRGNMVTTYTDCTAS
*
>P1;ENSONIG00000016823

-------------------MATAQSTLLLAVHILLISEFILAKRDYYDIL
GVPRDATERQIKKAFHKLALKYHPDRNKDPDAEAKFREIAEAYETLSDDK
KRQEYDQFGHSASSGEGQRGG----------DYDFNQHFKSFNFNFDDLF
KDFDPFGQ-QQQHQHHFHSHSNSHHKRHFDSHFQAHREAMNGHRRQFQQG
SFGGGVFDDMFEDLEKMFSFH------THSSRTENRFQGSGKQHCRTVTQ
RRGNMVTTFTDCS--
*
>P1;ENSONIG00000008679

MTACVERKRQTTPRQDTAAMAAAQSVLTFAVCVLVITELILAKKDYYDIL
GVPKGATERQIKKAFHKLAMKYHPDKNKSPDAEVRFREIAEAYETLSDEA
RRREYDQFGDTDGYFNGETQGK--------HRQGAHQPF---TFSFDDIF
KDFDIYSQ-NR----------HARHRRHFDEHSRSH----SRHKRHFQ-G
GFGAGMINDMFDDIERMFTFD------RHTKQTENRFHGTSKQHCRTVTQ
RRGNMVTTYTDCTSS
*
>P1;ENSXMAG00000009211

-------------------MATAQSTLLLAVHILLISEFILAKRDYYEIL
GVPRDAAERQIKKAFHKLALKYHPDRNKGADAEAKFREIAEAYETLSDDK
RRREYDQFGHSASSGEAYQGGRGSRGGGSGDDYNFRQHYQSFHFNFNDIF
KDFDPFGQ-Q--HQHHFHSHHQSHQKRHFDSHFQAHKEAMNRQRRSFQQG
SFGGGMFDDMFEDLEKMFSFN------THTSRTESRFQGSAKQHCRTVTQ
RRGNMVTTFTDCS--
*
>P1;ENSDARG00000016886

-------------------MATAQSVFTVAVSILLISELILAEKDYYEIL
GVPKDASDRQIKKAFHKLAMRFHPDKNKSPDAEAKFREIAEAYETLSDDN
RRKEYDQTRSRPFSGGG--------------SEHFHQHF---NFNFEDAF
RHSP-----------------HSHNQRHFQSHFKAHEEARSRHRRHFQ-S
SFGGDMFDDVFQDMERMFSFN------GQ----QTRTQGSSRQHCRTVTQ
RRGNMVTTYTECS--
*
>P1;ENSAMXG00000001484

-------------------MATAQSTLMFAVCILMITELILARKDYYDIL
GVPKDASERQIKKAFHKLAMKYHPDKNKSPDAEAKFREAAEAYETLSDEK
RRQDYDKLGHGAFSSEGMRGG----------GQYFHQTF---DFNFDEMF
RDFDIYSQ-NR----------HARPKRHFEDHFRAHQQAHSRHKKHFQ-G
GFGAGVFEDLSDDIERMFTFD------RHSKRTDSRFHGTAKQHCRTVTQ
RRGNMVTTYTDCTSS
*
>P1;ENSGACG00000018888

-------------------MATVQSALVLAVHVLLISEFILAKRDYYDVL
GVPRDATERLIKKAFHKLALKYHPDRNKGPDAESKFREIAEAYETLSDDK
RRREYDQFGHGPSPGEGHRGGR--------GDYNFNQHYQ--SFNFDDLF
KDADTFGQ-H---RHHFHSQNHAHPQGHFDGHFQAHREAMNRQKRQFQQG
GFGGGLFDDMFEDLEKMFSFN------AHGSRTDGRFQGSGKQHCRTVTQ
RRGNMVTTFTDCS--
*
>P1;ENSDARG00000052072

-------------------MATAQSTLMFAVCILMITELILARKDYYDIL
GVPKDASERQIKKAFHKLAMKYHPDKNKSPDAENKFREIAEAYETLSDEK
RRREYDRLGHSAFTNDDTNGGG-------GAGQRFHHSF---DFNFDDMF
RDFDIYSQ-NR----------HARPKRHFEEHFRAHQQQHNRHKRHYQ-G
SFGNGAFEDMFEDMEKMFTFD------RHVKRTDSRFQGTTKQHCRTVTQ
RRGNMVTTYTDCSSS
*
>P1;ENSTNIG00000018514

-------------------MATVQSVLLLAVHVLLISEFILAKRDYYEIL
GVPKDATERQIKKAFHKLALKYHPDRNKGPDAEAKFREIAEAYETLSDDK
RRQEYDQFGHGPSPGEGPRGGS-------NDNYNFREHFQ--SFNFDDIF
KDFNHFGHQQR-HQHHFHSQNQANQKRHFDSHFQAHQEAMNRHRRQFHQG
GFGGGLFDDMFEDLEKMFSFN------TH--RSESRFQGSAKQHCRTVTQ
RRGNMVTTFTDCS--
*
>P1;ENSLOCG00000001014

-RLCDERNVPWVKSRVTNNMATAQSALTFAVCILMISELILAKKDYYNIL
GVPKDASERQIKKAFHKLAMKYHPDKNKSPDAETKFREIAEAYETLSDEK
RRREYDQYGHGAFPNEGTGNG---------HRHHFHQPF---NFNFDEMF
KDFDLFTQ-N-------------RQKKHFENHFRAHQEAHNRNKE----F
SFGGGVFDDMFEDMEKMFTFNGFDSTRRHTVRTESRFQGSSKQHCRTVTQ
RRGNMVTTYTDCSGS
*
