>P1;ENSXMAG00000003552

-----PA--APAP-AAAAAAPTATAA------------------------
-----------------------------TE-----EAPPVEA-AAA--A
APATAAAPAEEEEEEEYVVEKVLDRRVVRGKVEFLLKWKGFSDEDNTWEP
EENLDCPDLIAEYMQKHKEREEKK--K-ESKRKASSEASGDAEERASKKR
KEEGDKARGFGRGLQPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPTEEEEKKEEEKKD
*
>P1;ENSORLG00000012360

DPPAALS--VRKQ-C-CRDSTDVVSSSLSRRRRGGHDTFPCSQASGAFRQ
QINQNNRAAFAQLHARHSPVVVIWCGWKFDIT---NHEAK-LT-AVE-KK
DKKAEDVAEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSEEDNTWEP
EDNLDCPDLIAEFLQSQKAAHD-------GKRKAAGDAE--GDDSKSKKK
KDDTEKLRGFARGLEPERIIGATDSTGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPSEDE-KKDDK--N
*
>P1;ENSTNIG00000003151

--------------------------------------------------
--------------------------------------------AGK--K
GTAPTAAPAEEEEEEEYVVEKVLERRVVKGRVEFLLKWKGFPNEDNTWEP
EENLDCPDLIAEFMQKHKEKEEKK--K-EGKRKVSNEASGDSEERGSKRK
KEEGEKARGFGRGLQPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPSGTEQRCEEK--R
*
>P1;ENSGACG00000005637

--------------------------------------------------
--------------------------------------------------
----------EEEEEEYVVEKVLDRRVVKGRVEFLLKWKGFSDEDNTWEP
HDNLDCPDLIAEYMQKHKEKEEKK--K-EGKRKIVSETSGDSEERGSKRK
KEESEKARGFGRGLQPERIIGATDSSGELMFLMKW---------------
----------------------------------
*
>P1;ENSDARG00000054442

-----MS--QTSE-P-SADAAV-TEA------------------------
-----------------------------P---VSQSEPKQIT-AGK--K
QNKKKVEEVVEEEEEEYVVEKVLDRRVVKGKVEYLLKWKGFSDEDNTWEP
DENLDCPDLIAEFLQSQKTAESG------GKR--RAETDGDGK--ETKKR
KDEPEKLRGFARGLDPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPTEEEEKKDDK--N
*
>P1;ENSAMXG00000010559

-----MS--QITETP-PVEAPKVTEV------------------------
-----------------------------LTDPPPQTEAKPVTAGGK--K
QNKKKVEEVVEEEEEEYVVEKVLDRRIVKGRVEYLLKWKGFTDEDNTWEP
EENLDCPDLITEYLQSQRNASES-----GFKR--RSDTDGDVKESQSKKR
KDEPEKLRGFARGLDPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPTDEEEKKDEK--N
*
>P1;ENSTRUG00000012203

-----MS--QTTE-S-SNDGPTVVVNG-----------------------
-----------------------------LSDP--TETTK-MT-SAE--K
EKKPDDVPEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSDEDNTWEP
EDNLDCPDLIAEFLQSQKSAQE-------GKRKAGGEVE--GEESKAKKK
KDDPEKLRGFARGLVPERIIGATDSTGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPTEDE-KKDDK--N
*
>P1;ENSONIG00000006190

-----VK--LATQ-A-AKKPKKAEEE------------------------
-----------------------------EQ-----PAAAPPA-AAG--A
AAAPVAGAAEEEEEEEYVVEKVLDRRVVKGKVEFLLKWKGFSDEDNTWEP
EENLDCPDLIAEYMQKHKEKEEKK--K-ESKRKAASETSGDGEERGSKRK
KEEGEKARGFGRGLQPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPTEEEEKKEED--K
*
>P1;ENSONIG00000018212

--------------------------------------------------
-----------------------------------------MT-SAE-KK
DKKADEVAEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSDEDNTWEP
EENLDCPDLIAEFLQSQKSAHD-------GKRKAAGEAE--GDDSKSKKK
KDDTEKLRGFARGLDPERIIGATDSTGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPSEDE-KKDEK--N
*
>P1;ENSGACG00000003918

-----MS--LTTE-P-PNDVPAVTQG------------------------
-----------------------------FND---QSNYV-PC-SDPSEP
ESKM-AAVEKDKKPDEYVVERVLNRRVVKGRVEYLLKWKGFSEEDNTWEP
DDNLDCPDLIAEFLQSQKSAHD-------GKRKAAGDAE--GDESKTKKK
KDDTEKLRGFARGLDPERIIGATDSTGELMFLMKWKNSDEADLVPAKEAN
GKCPQVVISFYEERLTWHSYSAEGE-KKEEK--N
*
>P1;ENSDARG00000004189

-----MSMSQPTE-T-VSDAPSVTEE------------------------
-----------------------------VS-----PDSKLAATAGK--K
QTKKKVEDVVEEEEEEYVVEKVLDRRVVKGRVEYLLKWKGFSEEDNTWEP
EDNLDCPDLIAEYMTKHKINDDKK--ESSAKR-KESDTDGGGEDSRPKKR
KDEQDKPRGFARGLDPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPSEEEEKKDDK--N
*
>P1;ENSTNIG00000010097

--------------------------------------------------
-----------------------------------------VT-SAE--K
EKKPDDVPEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSDEDNTWEP
EDNLDCPDLIAEFLQSQKSAQE-------GKRKAGGEVE--GEESKAKKK
KDDPEKLRGFARGLVPERIIGATDSTGELMFLMKWKNSDEADLVPAKEAN
VKCPQVVISFYEERLTWHSYPTEDE-KKEDK--N
*
>P1;ENSLOCG00000013417

-----RSMSQPSA-P-CNDAPTNKAA------------------------
-----------------------------PQ-----PDTKLASTTGK--K
QNKKKVEEVLEEEEEEYVVEKVLDRRVVKGRVEYLLKWKGFSDEDNTWEP
EENLDCPDLIAEFLQSQKTAHEAEKAETGGKRKGESDTEVAGEESRPKKR
KEEPEKPRGFARGLEPERIIGATDSSGELMFLMKWKNSDEADLVPAKEAN
IKCPQVVISFYEERLTWHSYPSEEEEKKDDK--N
*
