>P1;ENSTNIG00000008399

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDSFNTTFISTIGIDFKIRTI
ELDGKRVKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDISNEKSFENIK
NWIRNIEEHASSDVEKMILGNKCDMTDRRQVSKDRGEKLAIDYGVKFLET
SAKSSLNVE------------------EAFYTMARDILHNLSSKTA----
------DPTA--GGSGKPVKITEKKSKKIKFFKCSLV
*
>P1;ENSXMAG00000016094

MAKKYDFLFKLLLIGDSGVGKTCLIIRFAEDNFNSTYISTIGIDFKVKTI
EVDGKKVKLQVWDTAGQERFKTITTAYYRGAMGIILVYDITDEKSFENIQ
NWMKSIKENASAGVSQMLIGNKCDIEPKRKVSKETGEKLAKDHSIRFFET
SAKSSINVEE------------------SFLALARDILHKSTKK------
---------P--GSAGKEVKITSSTAKL--PSKCAIL
*
>P1;ENSXMAG00000003321

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDSFNTTFISTIGIDFKIRTI
ELDGKRVKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDISNEKSFDNIK
NWIRNIEEHASSDVEKMILGNKCDMTDRRQVSKDRGEKLAIDYGVKFLET
SAKSGLNVE------------------EAFYTIARDILNNLCSKTT----
------DSSG--GGTGKPVKITDKKSKRIKFFKCSLL
*
>P1;ENSDARG00000068628

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDAFNTTFISTIGIDFKIRTI
ELDGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFDNIK
NWIRNIEEHASSDVERMILGNKCDMNDKRQVSKERGEKLAIDYGIKFLET
SAKSSTNVEE------------------AFVTLARDIMTRLNRKMN----
------ENNPSGGGGGGAVKITESRSKKPSFFRCILL
*
>P1;ENSDARG00000103934

-----------------------------------------GIDFKIRTI
ELNGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITSEKSFENIK
NWIRNIEEHASSDVEKMILGNKCDMNERRQVSKERGEKLAIDYGIKFLET
SAKTSINVEE------------------AFFTLARDIMARLQN-------
------------------VKLTRNMI----------T
*
>P1;ENSGACG00000017522

--------------------------------------------------
-------TITCRDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFDNIR
NWIRNIQEHASSDVERMILGNKCDMKDRRQVSKERGEKLAIDYGIKFLET
SAKSSINVEE------------------GFLTLGRDIMTRLNRKMS----
------DVGP--SAAGSSVKITESRSKK--TFRCSLL
*
>P1;ENSTRUG00000010479

MAKTYDYLFKLLLIGDSGVGKTCVLFRFSEDAFNSTFISTIGIDFKIRTI
ELDGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFDNIK
NWIRNIEEHASADVEKMVLGNKCDINDKRQVSKDRGEQLALDYGIKFMET
SAKANINVENLLNLSYRISVPHMSLGPQAFLTLARDIKSKMDTKLGIEPF
LWYLQEGNTQ--QGGSHGVKISEPQK-KTSFFRCTLL
*
>P1;ENSORLG00000018512

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDAFNTTFISTIGIDFKIRTV
DLDGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFDNIR
NWIRNIEEHASADVERMVLGNKCDMNDRRQVSKERGEKLAIDYSIKFLET
SAKSSINVEE------------------AFLTLARDIMSRLNRKMH----
------NDSS--AGGGGAIQIKEPRSKK-SLFRCLLL
*
>P1;ENSORLG00000007470

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDSFNTTFISTIGIDFKIRTI
ELDGKRVKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDICNEKSFDNIK
NWIRNIEEHASSDVEKMILGNKCDMTDRRQVSKDRGEKLAIDYRVKFLET
SAKSSLNVE------------------E----------------------
-------------------------------------
*
>P1;ENSTRUG00000012358

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDSFNTTFISTIGIDFKIRTI
ELDGKRVKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDTSNEKSFENIK
NWIRNIEEHASSDVEKMILGNKCDMTDRRQVSKDRGEKLAIDYGVKFMET
SAKSGLNVE------------------EAFYTMARDILHNLSSKTT----
------DSGA--GGSGKPVKITEKKSKKIKFFKCSLV
*
>P1;ENSONIG00000003271

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDAFNTTFISTIGIDFKIRTI
ELDGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFDNIK
NWIRNIEEHASADVEKMVLGNKCDMNDKRQVSKERGEKLAIDYGIKFLET
SAKSSINVEE------------------GFYTLARDIMARLNRKMN----
------DNNP--SGGGGPVKITEPRSKK-SLFRCSLL
*
>P1;ENSGACG00000010417

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDSFNTTFISTIGIDFKIRTI
ELDGKRVKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDISNEKSFENIK
NWIRNIEEHASSDVEKMILGNKCDMSDRRQVSKDRGEKLAIDYGVKFLET
SAKSSLNVE------------------EAFYNMGRDILHNLSSKTT----
------DNNA--GGSGKPVKITEKKSKRIKFFKCTLL
*
>P1;ENSAMXG00000000323

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDAFNTTFISTIGIDFKIRTV
ELNGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITSEKSFENIK
NWIRNIEEHASSDVERMILGNKCDMNDKRQVSKERGEKLAIDYGIKFLET
SAKTSVNVEE------------------AFLTLARDIMSRLNRKMN----
------DGSN--SDGGAPVKITEKRSKKHSFFKCALL
*
>P1;ENSTNIG00000014895

MAKTYDYLFKLLLIGDSGVGKTCVLFRFSEDAFNSTFISTIGIDFKIRTI
ELDGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFDNIK
NWIRNIEEHASADVEKMVLGNKCDINDKRQVSKDRGEKLALDYGIKFMET
SAKANINVE------------------NAFLTLARDIKSKMEHKIE----
------GNAP--QGGTHGVKISEPQK-KSSFFRCSLL
*
>P1;ENSLOCG00000014811

MAKTYDYLFKLLLIGDSGVGKTCLLFRFSEDAFNTTFISTIGIDFKIRTI
ELDGKKIKLQIWDTAGQERFRTITTAYYRGAMGIMLVYDITNEKSFENIK
NWIRNIEEHASSDVERMILGNKCDMNDKRQVSKERGEKLAIDYGIKFLET
SAKSSINVEE------------------AFFTLARDIMTRLNRKMN----
------DNTA--PGGGGPVKITENRSKKSSFFRCTLL
*
