>P1;ENSDARG00000074073

--------------MAWPCITRACCINRFWSELDKGDIAVPLVFTKYSDV
AEV-QHLHPQ-----PKPVL-SQ-----------------------KPVA
TESHLAHS-AHQEA-SSRATHGAADAA----AA-ASQ-DGSGASVMREDF
KAWSVRPERSCKPRNQYQPSKTPFINETQYQKDYKPWPIPKKGDHPWIPK
PTAAAAPCKAESKF---SKHE--QAAAEMETGVEKCEIEEKQHE---KE-
--SKERRKK----VEKKEPV------------SEAS--------------
--------------------------------------------------
--KM----------------------------------------------
---------------------------------------E-----KDVAV
EGKRRS---A-ADALNRQIKQEV--TSG--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYRDIKPVK
PIKAKSQYKLLVGEKTNLETSYSATFKGEQAKPQTTDNKLMEHRRIRSLY
SEPSKESS-KVERHNLSLTKPKKTPS----HSKTVKKAKEKPVAGSQPAK
KKTSVSNQEPKPEGGVTKKSKEMINRLAEAKD------------------
--------------------------------------------------
---------------
*
>P1;ENSTNIG00000008576

DHKQQQTLGMVAMAMAWPCISRACCMARFWNQLDKADIAVPLVFT-YADA
SEM-QHVQPQ-----PS----SQ-----------------------ARVA
IETQPSRA--ESRT-R-TVAR---APR----RC-VSE-ERVCSSVMREDF
KRWNVRPEPSCKPKNEYHEPEAPFYSETQYQKDFKPWPIPKRYDHPWIQK
APRLDN-R-GPDRP---RQPKRAAAPTAADGDVEKSAIADKVQE---KD-
--LLQGHER----KK-GSRREA-----EAR--------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------RAVEG
EGRGRR---S-TDALNRQIKEEIT--GG--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RAEYKAYADVKPTR
MIRAKSQYLP-PEEKTRLETSYSATFRA-QAPAQPADNKALDRRRVRSLY
ADPSKQVD-RYSL---PRSKAKQPGAAASGQGTPLKKAKDKQGGAHRGSR
KMAAE----KQPV-GNKEKSKEMNNKLAEAKE------------------
--------------------------------------------------
---------------
*
>P1;ENSTNIG00000003291

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
QHL-PH---H-----PQPKQSAA-----------------------GAIA
IETQPHPQRAEQEA--------------------GTE-DGLTASVMRQDF
KAWRVRPEPSCKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPK
PSPGSA-SRGPERS---AKLE--HAAGEAESGVEKSEIEEKIHE---KE-
--TKEVTRR----EK-SAER------------DAGE--------------
--------------------------------------------------
--KT----------------------------------------------
---------------------------------------E-----PACAE
ARKGRA---A-ADALNRQLKEVM--STS--SSYRYFCQLPSAGETDRWDW
C-------------------------------------------------
--------------------------------------------------
------------------------------YIPAASTATLHNTSSQVRPV
TVPE-------------RTTEHIRAPCVHRAAAATQLNQQPSETIIHTSP
---------------------------------NFRRTEFKAYKDVKPTK
PIKAPSQYKP-PGEETNLETSYSATFKGEQVKAHPADNKAMERRRIRSLY
SEPSKASP-KVDKP-ASHAKSRKTSSTATTAGKMAKKTKEKQISSSQSAK
KKPPLVTAEPRPEGVITKKSKEISNRLAEAKQ------------------
--------------------------------------------------
---------------
*
>P1;ENSORLG00000012570

--------------MAWPCISRACCMARFWNQLDHADIAVPLVFTKYTDA
SEM-QHIQLQ-----PQ-LPRPQ-----------------------ARVA
IETQPSRS--KPRT-A-PG-K------------------ACPAVLVRKHL
KGN----CPKCRRK-DFFPVDCALSRKPAVQKGFAACRDEEDADPP----
------------------------------SRGSKLLKKKRIPE---KD-
--GWAIYQN----SL-KRINLSYTTTTHLK---SSR----R---------
--------------------------------------------------
---A----------------------------------------------
---------------------------------------S----SSQSRG
DGRGRGVKPG-VDRIHSQPTTNCV--SS--STY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------KDETEFKAYRDVRPVR
MIRAKSQYLP-PDERPSLETSYSATFKV-QTPLQPADNKAQERRRIRSLY
SEPYIDPSKQVDRYSPTCSKPKKSGATSAGQGKPLKKAKDKQTTPLKGSK
KATLENQPQDRPAVGDKEKSKEINNKLAEAKE------------------
--------------------------------------------------
---------------
*
>P1;ENSAMXG00000008868

--------------MAWPCIARACCMARFWTQLDKADIAVPLVFVKYSEV
SEETQQLQRD-----RE-REKDRDRERNRERDREKDRHRDRTRDRLQEKS
QERDPERN--RQEV-----------------TR-DGR-ENAPGSVMRQDF
KAWKVRPEPSCKPKCEYHGPEVPFDSQTQYRQDYKPWPIPRRGDHPWIPK
PA--------------------------LECGLEKSQTADKVQE---KE-
--MLMGEKK----KR-QVKRVE-----KEKKVITGK----E---------
--------------------------------------------------
---G----------------------------------------------
---------------------------------------S----AEAPVN
VGKGRE---A-VDALNRQIKQEVG--GG--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYTDVKPVK
LIRAKSQYHP-PDEKTNLETSYSATFRGEQAKLQPADNKALERRRIRTLY
SEPYLDSS-KGERSSLPRSKPKKTTSSSTSQGKTVKKSKEKQTASVRGSK
KKSSENQPERRAAQGDKEKSKEMNNKLAEAKE------------------
--------------------------------------------------
---------------
*
>P1;ENSDARG00000074521

--------------MAWPCISRACCMARFWSQLDKADIAVPLVFTKYSDV
SEM-QHLHLQ-----QP-VQ---------------------------KIA
IETQPLHH--DHEP-V-T--R---AP-----HA-GHD-EHSFGSVMRQDF
KHWKVRPEPSCKPKNEYHGPEIPFNTETQYQKDYKPWPIPKKGDHPWIPK
PSPSIS-A-GKH----------SSPEMMMDSGVEKSEIADKVPE---KE-
--ILSSERK----KR-QVKKVA-----VVSENNAGV----K---------
--------------------------------------------------
---L----------------------------------------------
---------------------------------------D----RDASAV
EGKGRA---A-VDALNRQIKREVS--SG--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYTDVKPVK
LIRAKSQYKP-PDDKTDLETSYSATYRAYQSSQQPDDNKALERRRIRTLY
HEPYRESS-KVEKTSLPRSKPKKSSSTSATPGKPLKKSKEKQATSVRGSK
KKSSENQPESRAVQADKEKSKEINNKLAEAKEVMLKQYHYIQLCQPIRDI
GWVQTLKQHLWRCALPDPRECESGVGRVSDYYSAGTSGGEP--LVERPEP
R-SRGVVRFAPDVKY
*
>P1;ENSGACG00000010429

--------------MAWPCLTRACCINRYWTELDKADVAVPLVFGKYSDA
ADA-QHLPHH-----PQPRHKRA-----------------------GAIA
IETQPHRA--EQGP-G-KAPP---ATA----AA-AGK-DGSAASVMRQDF
KAWSVRPEPSCKPRNEYQRSAAPFNTETQYQKDYKPWPIPKKRDHPWIPP
QRRERK-A--GSRG-----RE--RRGEERDRGENAGERVNRGGE---DE-
--REEGKVR----RE-GNGR------------EDGQSGARGCERRAEERQ
GGRRRAEQADQAAIGEFI--------PPQPIAIKKPLLRPFQNEF-----
ADIFSRLSTQSSIRVSISTQYFK-----------------WFFNKITPKS
SVIKHL-ENILSKINGARTGMT--NRPCVPVITAVRMCFVSR--KQNTRS
EGQDEA---TWQLSLNYRITYVLIKTLF--SPC-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYKDVKLVK
AIKAPDQYKP-PVKEASLETSYSATYKGEQMKAQPTDNKLVERRRIRSLY
SEPGKEAA-KVDKP-VSRTKQKKTPT--TTTGKMVKKSKEKQIASSQSAK
KKPSSCAPKPKPDGAVTKKSKEISNRLAESKQ------------------
--------------------------------------------------
---------------
*
>P1;ENSONIG00000011169

--------------MAWPCITRACCINRFWSELDKADIAVPLVFARYSDV
ADV-PHVPHH-----PQPKLKKA-----------------------GAIA
IETQPHPG--EQEA-G-KAPP---ATG----AA-AGK-DGSTASVMRQDF
KAWRVRPEASCKPRNEYQPSPAPFNNETQYQKDYKPWPIPKKHDHPWIPK
SSPTAG-G--PERSAGSGKLE--QVAAEAESGVEKSEIEEKTQE---KE-
--SQEVVKRSVKREK-SSER------------KTGE--------------
--------------------------------------------------
--KT----------------------------------------------
---------------------------------------EGQVAADVSAE
QRKGRA---A-ADALNRQIKEVM--STS--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYKDVKPVK
PIKAPSQYKP-PGEETSLETSYSATFKGEQVKAHPMDNKLLERRRIRSLY
SEPSKEPA-KVDKP-VSRTKPKKSSSTPTTTGRMQKKAKEKQISSSQSAK
KKPSLGASEPKPGGAVTKKSKEISNRLAEAGK------------------
--------------------------------------------------
---------------
*
>P1;ENSTRUG00000007180

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHFPHH-----PQPKQNRA-----------------------GAIA
IETQPHPHRGEPEA-G-KAPP---ATG----AA-AGD-D--GLSVMRHDF
KAWRVRPEPSCKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPK
ASPGST-SKGPERS---AKLE--QAASEAESGVEKSEIEEKIHE---KE-
--SKEVTKR----EK-SAER------------EVGE--------------
--------------------------------------------------
--KT----------------------------------------------
---------------------------------------E-----PACAE
TRKGRA---A-ADALNRQLKEVM--STS--SSYRF---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
---------------------------------KKYRTEFKAYKDVKPTK
PIKAPSQYKP-PGEETNLETSYSATYKGEQVKAHPADNKVMERRRIRSLY
SEPSKAGA-KVDKP-ASHTKPKKTPT---TAGKMGKKSKEKQISGSQSAK
KKPSLVSAEPKPEGVITKKSKEISNRLAEAKH------------------
--------------------------------------------------
---------------
*
>P1;ENSXMAG00000001705

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHLPHH-----PQPRQKQA-----------------------AAIA
IETQPHPE--EREA-A-KAPP---AAG----GAAAAKGGASAASVMRQDF
KAWRVRPEPSCKPRNEYQPPPAPFSNETQYQKDYKPWPIPRKHDHPWIPK
PSPTAG-S----KL--EHAAA--AAAGESESGVEKSEIEEKIQE---KE-
--SKEAARR----EK-SAER------------KAAE--------------
--------------------------------------------------
--KT----------------------------------------------
---------------------------------------EGP--AEVSAE
QRRGRA---A-ADALNRQIKEVM--STS--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYKDVKPVK
PIKAPSQYKP-PGEETSLETSYSATYKGEQVKAQPTDNKLLERRRIRSLY
SEPGKEPA-KVDKP-TSRTKPKKAPT--TTTGKMVKKSKEKQIAGSQLAK
KKPSAKTPEAMPEGTVTKKSKEISNRLAEAKH------------------
--------------------------------------------------
---------------
*
>P1;ENSTRUG00000017372

R-PLERSLVFGALAMAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQ-----PS----AQ-----------------------ARVA
IETQPPRA--QSRT-R-TAAH---APR----RC-VSE-ERVCNSVMREDF
KRWNVRPEPSCKPKNEYHEPETPFYSETQYQKDFKPWPIPKRCDHPWIQK
APRVDN-R-VPDRP---R----QQA--AADGEAEKSAVADRVQE---KD-
--LLQGHGR----SK-ASRKEA-----ELK----------K---------
--------------------------------------------------
---V----------------------------------------------
--------------------------------------------VLRVEG
EGRGRR---S-TDAVNRQIKE-IA--GS--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RAEYKAYADVKPTR
MIRAKSQYLP-PDEKTRLETSYSATFKA-QAPAPPADNKALDRRRVRSLY
TDPSKQPP-QMDRYSLPRSKPRQSGAAASGQGTPVKRAKDKQGVAQRGSR
KMAVE----KQPV-GSKEKSKEINNKLAEAKE------------------
--------------------------------------------------
---------------
*
>P1;ENSORLG00000005434

--------------MAWPCITRACCINRFWTELDKGDIAVPLVFTKYSDA
AEV-HHLPHH-----PQPKQRVV-----------------------GTIA
IETQPHPE--EQEA-A-RAPP---ATG----AA-AGR-TGTATSVMRQDF
KAWGVRPEPSCKPRNEYQPPPSPFNNETQYQKDYKPWPIPKKHDHPWIPK
PSSTAA----PERS---SKKE--HAAAEADSGGEESGWQTGAAGVCKGER
RAAEEQGSR----RR-SQQT------------DQGG--------------
-------------HVHFQLLQVNIITPLGPAGRTDHQ--PSPHHLQPIEE
THSMEP---WIKNSMDTSEDH-KSLKKKCSAHCLVGLDDPTPNVKVPRIA
QGLNHFLASLYLRRDTIRLGYLSVRDPKPKR-------IQSRRRYYDAKQ
GGKGSL---S-YFAETMQQEEAA--ASGVQFTC-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RTEFKAYKDVKPVK
AIKATSQYKP-PMEETSLETSYSATYKGEQVKPKESDNKLLERRRIRSLY
SEPGKEAA-KVDKP-ESRLKPKKAP---TTTGKMLKKAKERQIASSQSTK
KKPSAGPSE--PEGTVTKKSKEISNRLAEAKQ------------------
--------------------------------------------------
---------------
*
>P1;ENSGACG00000020200

--------------MAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQ-----PP-LHPPR-----------------------GRVA
IETQPTRA--E---------------------C-VSE-ERVCGSVMREDF
KHWNVRPETSCKPKYEYHEPETPFNCESQYQKDFKPWPIPKRYDHPWIPK
PPASDE-R-APDRS---RH---RKQPAEADSGVEKSAIADKVQE---KD-
--LVQGPHR----KK-KSSKQE-----GPK----------K---------
--------------------------------------------------
---V----------------------------------------------
--------------------------------------------SLKVEG
EGKGRA---A-ADAVNRQIKQEIA--GD--SLYNNQSYVNLGGNV---SW
CAQESPCFRDKRFQPAASQSPAPSGLYLAANQLHYEMEAGKAGSVRSDSG
YVKYCNPIQPAVLTKLSGHWKSSLLRLQKVGVTQKKGPSHTAMYRCSSQL
LAVSIEPLPEKLQRGRELETRPTGPTGKREYRPGARPSPAHTPRNTARTG
SLPPAQIDSFKDHERGGLASETIDAPSYMHASACSCIHTQPCKHLTSTTH
NSGVSEGWGTYINRKLGSLLGLALHKEVELTMSYTNRTEYKAYRDVKPAK
MIRARSQYLP-PDEKTSLETSYSATYKG-QAPLRPAGNKALDRRRIRSLY
SEPYIDPIKQVDRYSALRTKPKKPGASAAGQVKQAKKAKDKQSAGLRGSK
KTASENQLENRPAVGDKEKSKEMNNKLAEAKE------------------
--------------------------------------------------
---------------
*
>P1;ENSLOCG00000004684

R-ILFDLRYFIAFTMAWPCITRACCIARFWNQLDKADIAVPLVFTKYSDV
TEM-QHLHLQHQQKQPHPQA-RA-----------------------ESVA
IETQPSLS--DQEAVA-RATP---APGARAAAA-AAE-ESPGGSVMRQDF
KPWKVRPEPSCKPKNEYHPSEAPFNNETQYQKDFKAWPIPKRGDHPWIPK
SSPSPS-I-AGDRAVEKAKPA--HAPADAESGQEKSEIADKVQE---KE-
--ILSEEKQ----SKKKVKTVTVP-------EGAGK--------------
--------------------------------------------------
--KV----------------------------------------------
---------------------------------------AAK--AEGAVA
EGRGRA---A-ADALNRQIKEEV--ASV--SSY-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------RNEFKAYADVKPVK
LHKARAQYQP-PDKRASLETSYSATFRGEQGKRVPADNKVLERRRIRSLY
SEPSKESP-KVEKPSVPRSKPKKTTA---SHSKPVKKAKEKQISSGRSTK
KKEQENTAESKPEEGDKEKSKEINNKLAEAKEE-----------------
---------------PKVEVCGSG------DHSQGAVGGEPEPQGERPRP
RRGSGVVRFAPDVK-
*
