>P1;ENSONIG00000009048

-------------QDFQALTVWQKVQLFYHGILEKGDKRTDNWLLVYSPV
PISCVFLCYLIIIWVGPKLMARRQPVNLRSVLILYNFAMVCLSAYMFYEF
TTSSWLAGYSLLCQPVDYSDSPLAMRMARVCWWFYFSKVIELCDTIFFIL
RKKNSQLTFLHVYHHATMIFNWWAGVKYVAGGQSFLIGLINSLVHIVMYT
YYGLAAVGPSMTKYLWWKRYLTTLQLLQFFIVTIHTTYNLFADCDFPDSM
NITVLAYSLSLIILFSNFYYRSYLVEKNKKT-------------------
----------------------
*
>P1;ENSXMAG00000011120

-------------QGSNAVTKWQKLLLFYQGILENGDKRTDNWLLVYSPV
PITCIFLCYLITVWAGPKLMANRQPINLKPVLVVYNFAMVCLSAYMFYEF
TASSWLAGYSLLCQPVDYSNNPLALRMARVCWWFYFSKVIELSDTIFFIL
RKKNSQLTFLHVYHHATMIFNWWAGVKYVAGGQSFLIGLINTLVHIVMYL
YYGLAALGPHMNKYLWWKRYLTSLQLLQFFIVTTHTAYNLFVDCNFPDSM
NAVVLAYSLSLIVLFSNFYCQSYLTKKTKST-------------------
----------------------
*
>P1;ENSTNIG00000010693

GTLEEDPQITHSRMA----AAVH--ESVSLCVCHCPDKRTDPWLLVYSPV
PVALIFLLYLCVVWLGPRLMRHRQPVDLRVVLIVYNFAMVGLSAYMFHEF
LVASWLSNYSYLCQPVDYSSSPLAMRMARVCWWFFFSKIIEMSDTIFFIL
RKKDSQVTFLHVYHHATMIFNWWLGVKYVAGGQSFFIGLLNTFVHIIMYS
YYGLAAIGPHMQKYLWWKKYLTSLQLVQFVMFLLHTGYNLLAECDFPDSM
NAFVFGYCVTLIILFSNFYYHSYVTKEKR---------------------
---------------------K
*
>P1;ENSONIG00000002017

-------------MD----SAWQSVLSVHQRIVDNGDKRTDPWLLVYSPV
PVTLIFLLYLFIIWAGPRLMKHREPFELKVVLIVYNFTMVGLSVYMCHEF
LVTSWLLNYSLLCQPVDYSTSPLAMRMARVCWWFFFSKVIELSDTLLIIL
RKKNNQLTFLHVYHHSTMIFNWWSGVKYVAGGQSFFVGLINTFVHVIMYS
YYGLAALGPHMQKYLWWKRYLTSLQLVQFLLILVHTAYNLFADCNYPDAM
NAVVVGYCITLIILFSNFYYQSYLRKTKKHK-------------------
----------------------
*
>P1;ENSGACG00000014352

---------------------------FYEGVLRNGDKRTDSWLLVYSPV
PISFIFLWYLVIIWVGPKLMEKRQPVNLKPVLIVYNFAMVCLSAYMFYEF
TASAWLARYSLLCQPVDYSDSPLATRMASVCWWFYFSKVIELSDTIFFIL
RKKNSQLTFLHIYHHATMIFNWWAGVKFVAGGQSFLIGLINSLVHVVMYL
YYGLAALGPSVSKYLWWKRYLTSLQLLQFFIVTFHTTYNLFVDCDFPDSM
NMAVLAYSLSLIALFSNFYYHTYLAEKKTKT-------------------
----------------------
*
>P1;ENSDARG00000057365

-------------ME----SAWQRLESMHKWIVENGDKRTDPWLLVYSPV
PIICIFLCYLGVIWIGPKLMKNMEPVNLKGLLIVYNFSMVGLSVYMFHEF
LVTSWLANYSYLCQPVDYSTSPLGMRMANVCWWFFFSKVIELSDTVFFIL
RKKNSQLTFLHVYHHGTMIFNWWAGVKYVAGGQSFFIGLLNTFVHIWMYS
YYGLAALGPHLQKYLWWKRYLTSLQLVQFILLTVHTGYNLFTECEFPDSM
NAVVFAYCVSLIILFSNFYYQSYIKRKSKK--------------------
---------------------S
*
>P1;ENSAMXG00000005272

-------------MA----SAWQRFESMHQWILENGDKRTDPWLLVYSPV
PVACIFLCYLGVLWIGPKLMKNREPLNLRVVLIVYNFAMVCLSVYMFHEF
LVTSWLSNYSYLCQPVDYSTSPLAMRMASVCWWFFFSKVIELVDTVFFIL
RKKNSQLTFLHIYHHGTMIFNWWAGVKYVAGGQSFFIGLLNTFVHIVMYS
YYGLAALGPHMQKYLWWKRYLTSLQLLQFVLLTTHTGYNLFTECDFPDSM
NTVVFAYCITLILLFSNFYYQSYISRKSKR--------------------
---------------------S
*
>P1;ENSGACG00000012118

-------------------------------SVASPDKRTDEWLLVYSPV
PVALIFLAYLFVVWAGPRLMKHREPFDLKGVLVLYNFAMVGLSAYMFYEI
LVTAWLSNYSLLCQPVDYSTKPLPLRMAKACWWFFFSKIIELADTMFFIL
RKKNNQLTFLHVYHHGPLMFNWWAGIKYVAGGQSFLICLVNTFIHLVMYS
YYGLAALGPHMQKYLWWKRYLTSLQLVQLFLFLVHSGYNLFTECDFPDSM
NAAVFGYCVVLVILFSNFYYQSYLNKKKQKSCTSPRNGSSSESSPGILGN
EGRRLSTKEKGERRDQTVGVRS
*
>P1;ENSXMAG00000013075

-------------MD----SAWNRVLSVHRWILENGDKRTDPWPLVYSPV
SVTLIFLGYLCMIWAGSHLMKNRKPFELKIVLIVYNFAMVGFSAYMFYEF
LVTSWLSNYSLLCQPVDYSNSPLPLRMARVCWWFFFSKIIELLDTLFFIL
RKKNSQLTFLHVYHHGSMIFNWWAGVKYVAGGQSFFIGLVNTFVHIVMYT
YYCLSAFGPHMQKHLWWKKYLTMLQLLQFLLFFLHTGYNLITECNFPDSM
NIVVFGYVLTLIMLFCNFYYQKYVLKKKQ---------------------
---------------------K
*
>P1;ENSDARG00000068551

-------------MVSVSPSTWQKLQILYERILENGDKRTDGWLLVYSPL
PVGGIFLCYLVMVWFGPKLMVHREPVNIQALLIIYNFSMVCLSAYMFYEF
TASSWLASYSLLCQPVDYTENPLPMRMARVCWWFYFSKVIELADTMFFIL
RKKNNQLTFLHVYHHGTMIFNWWAGVKYVAGGQSFLIGLINSFVHVVMYM
YYGLAALGPQMQKYLWWKRYLTSLQLLQFFIVTIHTAFNLYADCDFPDSM
NMVVLGYALSLIALFSNFYYQSYLSKKTKLA-------------------
----------------------
*
>P1;ENSORLG00000003867

-------------MA----AVWNNVVSLHQTIVENGDKRTDPWLLVYSPV
QVFLIFLVYLGVVWAGPRLMKSREPVDLRVVLMVYNFAMVGLSAYMFYEF
LVTSWLSDYSLLCQPVDYSTRPLPMRMARVCWWFFFSKVIELSDTLFFIL
RKKNNQVTFLHVYHHGTMIFNWWAGVKYVAGGQSFFIGLVNTFVHIIMYS
YYGLAAIGPHMQKYLWWKRYLTSLQLLQFLLFLLHTGYNLFTHCDFPDSM
NAVVFGYCVTLIILFSNFYYQSYVSGKKKE--------------------
----------------------
*
>P1;ENSTRUG00000001208

-------------MA----SLWQSLEAAHQKIVDNGDKRTDPWLLVYSPI
PVAFLFLLYLGVVWLGPRLMRNRQPVDLKVVLIVYNFAMVGLSAYMFHEF
LVTSWLSSYSFLCQPVDYSTSPLAMRMARVCWWFFFSKIIELSDTIFFIL
RKKDSQVTFLHVYHHATMIFNWWLGVKYVAGGQSFFIGLLNTFVHIIMYS
YYGLAAIGPHMQKYLWWKRYLTSLQLVQFVMFLLHTGHNLFTDCDFPDSM
NAFVFGYCVTLIILFSNFYYQSYVNKKKK---------------------
---------------------K
*
>P1;ENSLOCG00000002926

-------------MA----SAWQRIQRYYDWALENGDKRTDPWLLVYSPV
PVSVIFLCYLFLIWAGPRLMRHREPVDLRVVLIVYNFSMVCLSAYMFYEF
FISSYLASYSYLCQPVDYSTSVLGMRMARVCWWFFFSKVIELLDTVFFIL
RKKNSQLTFLHVYHHGTMIFNWWAGVKYVAGGQSFFIGMANTFVHVVMYT
YYGLAACGPRVQRFLWWKRYLTSLQLLQFLAIIAHTAYNLFTDCDFPDAM
NLVVFVYCVTLVLLFSNFYYRSYLAQKSNLQGQ--------PSPPPLIAE
RPPRS-A------------RSS
*
