>P1;ENSDARG00000100835

MSGLI-----QAF---PAHFSMDRDDCRRNKTLGKNLMCRLKSMF--AGS
S---------------VPERLSLEDTQQWSQSLERLLGSKYGLATFRTFL
KSEFSDENIEFWLTCEDYKTITSSHKMSSKARKIFEQFVEAESPKEINID
YQTREEIKRKMKSPTAQCFDEAQKIVYGLMERDSYPRFLRSEMYKSLLET
IAAD--------------------------------DEA-G
*
>P1;ENSTRUG00000009818

M---------------------DPDKR-KGKD----RSRPLRYCLRSSQV
P---------------KTKGLSFEEMTQWSLSLERLLSSKYGIQIFQAFL
KSEFSDENIEFWMVCEDYKKIRSSFRMSSRAKKIFKCYIQAEATREINID
HKTRDLIRRNVAAPTRECFNDAQRIVYNLMEKDSYPRFLRSDIYRSLLDS
TSKDAEKEKR---------LNRLQKSFGDFLPVVPGSECG-
*
>P1;ENSGACG00000005823

LMHFL-----SV-------------------HSGKNFMCRLQCMF--SNS
SSSERIASTLPSFPSMASCRLSLEDTQQWSQSLERLLESKYGLATFRNFL
KSEYSDENIEFWLTCEDYKKIKSSFRMSSRAKKIYEQFIKAESPKEINID
YQTREQIKRNVKTPTVHSFDDAQKIVYGLMERDSYPRFLRSDIYRTLLEN
LAAD--------------------------------A---T
*
>P1;ENSAMXG00000017670

APSSIMTGLISEP--LIKHFSMDRDDRKRSKNLGKNFMCRLQCMF--SRS
S--------------APESRLSLEDTQQWAQSLERLLESKYGLATFRTFL
KSEFSDENIEFWLTCEDYKKIRSSFRMTSRAKKIYEQFVKAESPKEINID
YHTREQIKRNVKSPTAQCFDEAQKIVYGLMERDSYPRFLRSEMYRTLLDS
LAVD--------------------------------AAH-G
*
>P1;ENSXMAG00000002712

MPSIK-----AKPP-STHHFIMDRDDRNRNNTLGKNFMCRLQCMF--SQT
P-------------QCSESGLSLEDTQQWSQSLERLLESKYGLATFRNFL
KSEYSDENIEFWLTCEDYKKIKSSFKLSSRAKKIYEQFIKAESPKEINID
YHTREQIKRNVKTPTMHCFDEAQKIVYGLMERDSYPRFLRSDIYRTLLES
LATD--------------------------------ATT-G
*
>P1;ENSGACG00000016116

MLSLV-----ASPPRELQPLNMDTDNKKRAGN----LKLRLQCRS--SQA
A---------------TTEGICYEEISQWSHSLEGLLSSKYGMKIFQAFL
KSEFSDENIDFWLVCEDYKKIKSSFRMSSRAKKIFKRYIQAEAPREINID
HKTREMIRRNMKTPTAVCFDDARRIVYGLMERDSYPRFLRSDIYQALLDS
TSESIKIR------------------------------KGS
*
>P1;ENSDARG00000017653

MPTIL-----ST-----EIENMNKEDKATNPRRL--EKWRFRCP------
----------------LTEKINPGETSQWSQSLENLLRSKYGMATFHTFL
KSEFSDENIEFWLVCEDFKKTRSLSRLSSRAKKIFERYIKAEAPKEINID
HVTRELIKQNVHAPTKVCFDEAQRIVFGLMERDSYPRFLRSDMYRSLLES
VSNG--------------------------------IK--V
*
>P1;ENSTNIG00000006931

--------------------------------------------------
-------------------RLSFEEMTQWSLSLERLLSSKNGIKVFQAFL
KSEFSDENIEFWLVCEDYKKIGSSFRMSSRARKIFKRYIQADAAREINID
HKTRDLIRRNVAAPTRVCFDDAQRIVYSLMEKDSYPRFLRSDIYHRLLDS
TSKSGM-----------------------------------
*
>P1;ENSORLG00000012336

MCKGL-----ASL--HTCCLERTKEMKARLGN----ILQKPNWTL--SCF
K--------------IGKNKPSLEECLCWKESFEKLLSSKYGLCAFTAFL
VSEFSEENIAFYFACEDYRQTKCPTKLRAKAQKIFDEFFGSDAPREINID
HETRDITKANLQTPTPSCFDLAQHRIYMLMAKDCYPRFLRSPAYRDLVCQ
AKPTTKSSKHSQPDKKSRKQ-ACRR-------ASVDRSKPK
*
>P1;ENSONIG00000010956

MPSLI-----VEPP-NTQRFIMDRDDRNRNKNIGKNFMCRLQCMF--SHS
S--------------SSESRLSLEDTQQWSQSLEKLLESKYGLATFRNFL
KSEYSDENIEFWLTCEDYKKIKSSFRMSSRAKKIYEQFIKAESPKEINID
YHTREQIKRNVKTPTMHCFDDAQKIVYGLMERDSYPRFLRSDIYRTLLES
LAAD--------------------------------ATK-G
*
>P1;ENSTNIG00000012338

--------------------------------------------------
A--------------FSPSRLSLEDTQQWSQSLERLLESKYGLATFRNFL
KSEYSDENIEFWLTCEDYKKIKSSFRMSSRAKKIYEQFIKVESPKEINID
YHTREQIKRNVKTPTLHCFDDAQKIVYGLMERDSYPRFLRSDIYRTLLEN
LAAD--------------------------------AA--K
*
>P1;ENSLOCG00000007328

MPGLMFSQSVTAPLKESDHMSMEQNDKKKAKNLGKDFMCRLQSMF--SNT
TSTD---------ESSKHSRLNQEEILFWSQSLEKLLDSKYGMTMFRAFL
KSEFSDENIEFWLTCEDYKKIKSSSRMTSKAKKIYEQYIQTEAPKEINID
HQTREVIKANVLAPTINCFDEAQKIVYSLMERDSYPRFLRSDIYKSLSSK
--PD--------------------------------SVK-G
*
