>P1;ENSTNIG00000011081

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIAERSAHDE
SPGNNVVDISVPPTTDSQRGGRLQCCQNL
*
>P1;ENSONIG00000002544

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNTLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIADRSAHDE
SPGNNVVDISVPPTTDGQKGNKLQCCQSL
*
>P1;ENSXMAG00000018847

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIAERSAHDE
SPGNNVVDISVPPTTDGQRGSKLQCCQNL
*
>P1;ENSAMXG00000016024

---------MGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNSLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIADRSAHDE
SPGNNVVDISVPPTTDGLKGSKFQCCQNL
*
>P1;ENSGACG00000013297

-------LKMGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENIERWLKELRDHADNNIVIMQVGNKSDLRHLRAVPTDEARA
FAEKNAISFIETSALDSTNVEEAFKNILT--EIYRIVSQKQISDRSAHDE
SPGNNVVDISLPPTTDGQRGNKLPCCQSL
*
>P1;ENSDARG00000041878

---------MGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQMVDRPGHDE
SPGNNVVDISVPPTTDGLKGNKFQCCQNL
*
>P1;ENSONIG00000010435

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIAERSAHDE
SPGNNVVDISVPPTTDGQRGSKLQCCQNL
*
>P1;ENSAMXG00000018933

---------M-------------------------LIC------------
---------------------------------NFPCSYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--GTLC---------------
-----------------------------
*
>P1;ENSORLG00000015307

---------MGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADSNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNTLSFIETSALDSTNVEEAFKNILT--EIYRIVSQRQIADRSAHDD
SPGNNVVDISVPPTMDGQRGNKLPCCQSP
*
>P1;ENSDARG00000090086

---------MANRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIAERSAHDE
SPGNNVVDISVPPTTDGQKSNKLQCCQNL
*
>P1;ENSGACG00000015479

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDSKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIAERSAHDE
SPGNNVVDISVPPTTDGQRGSKLQCCQNL
*
>P1;ENSTRUG00000018273

---------MGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNTLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQISDRSGHDE
SPGNNVVDISLPPTTDSQRGGKLPCCQSQ
*
>P1;ENSTNIG00000013184

---------MGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNTLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQISDRSGHEE
SPGNNVVDISLPPTTDSQRGGKLPCCQSQ
*
>P1;ENSXMAG00000011926

SCLNV---KMGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAPWRDE-------
----------------PPKDRADSA--PSLVGNKSDLRHLRAVPTDEALA
FAEKNTLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIADRSAHDE
SPGNNVVDISVPPTTDGQKGNKLQCCQSL
*
>P1;ENSORLG00000013938

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAVKTKVRVVRGSKLVGERVNKGMMEIET--EIYRIVSQKQIAERSANDE
SPGNNVVDISVPPTTDGQRGSKLQCCQNL
*
>P1;ENSTRUG00000000223

---------MGNRDDEYDFLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTIKAQIWDTAGQERYRAITSAYYRGAVGALLVY
DIAKHLTYENVERWLKELRDHADNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILTETEIYRIVSQKQIAERSAHDE
SPGNNVVDISVPPTTDGQRGSKLQCCQNL
*
>P1;ENSLOCG00000004490

SARNTKHNTMGTRDDEYDYLFKVVLIGDSGVGKSNLLSRFTRNEFNLESK
STIGVEFATRSIQVDGKTI-------------------------------
----------------------NNNIVIMLVGNKSDLRHLRAVPTDEARA
FAEKNNLSFIETSALDSTNVEEAFKNILT--EIYRIVSQKQIADRSAHDE
SPGNNVVDISVPPTTDGQRPSKLQCCQNL
*
