>P1;ENSAMXG00000003841

MPMHPVTSTLMYRGICTIPDILSYRAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTAAGMPDKFNGTDFDSVFWKVIIGLFTLINTDNRHRLFLCCHT-----
---------HTHT-H-NQAKSGTS--------------------------
-----TPTHSL------------YNLTFIT------------QSNK
*
>P1;ENSONIG00000013961

MPVRAVTTRFMYKGLCTIPDVLTYRTPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVGFEEFVTLLGP
KLSAAGMPDKFNGADFDSVFWKCDMQKLTVDELKRLLYDTFRDHLTMKDI
ENIIMTEENHLNSPE-SHVDIDSMSYNIIFIVFHTFLKLHRRSFVLSLLP
FLSAASPTQQEKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSDARG00000060846

MPVRAVTSRFMYRGLCSIPDILSYRAPVSLPEDEVEEIREAFKVFDRDGN
GFISKQELGVAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVALLGP
KLSSAGMPDRFHGAEFDSIFWKCDMQKLTVDELKRLLYETFCDHLTMKDI
ENIIMTEESHLNSPE-CQVDIDK---------------------------
-----SPMQQVKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSGACG00000016943

MPVRAVTTRFMYKGLCTIPDVLSYRTPVILPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDIDGDGQVGFDEFVTLLGP
KLSAAGMPDKFHGADFDSVFWKCDMQKLTVDELKRLLYDTFRDHLTMKDI
ENIIMTEENHLNSPE-SHVDIDT---------------------------
-----SPTQQEKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSXMAG00000002409

MPMHPVTSTLMYRGICTIPDILSYSAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTAAGMPDKFNGTDFDSVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPEDCQVDIDSS--------------------------
-----SPTQQVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSAMXG00000006990

MPVRAVTSRFMYRGLCSIPEILSYRTPVTLPEDEVEEIREAFKVFDRDGN
GFISKQELGVAMRSLGYMPNEVELEVIIKRLDMDGDGQVGFEEFVTLLGP
KLTASTMPDKFHGADFDSIFWKCDMQKLTVDELKRLLYDTFCDHLTMKDI
ENIIMTEESHMNSPE-CQVDIDT---------------------------
-----SPMQQVKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSTNIG00000015602

MPMHPVTSTLMYRGMCTIPDILSYSAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTAAGMPDKFNGTDFDSVFWKCDMQKLTVEELKRLLYDTFCEHLSMKDI
ENIIMTEENHIENPEDCQLDIDSS--------------------------
-----SPTQQVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSDARG00000078272

--------------------------------------------------
---------MAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLSAAGMPDKFNGTNFDSVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPEDCQVDIDTE--------------------------
-----SPTQQVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSORLG00000008135

------------------------------------EIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVGFEEFVTLLGP
KLSATGMPDKFHGADFDSVFWKCDMQKLTVDELKRLLYDTFRDHLTMKDI
ENIIMTEENHLTSPE-SHVDIDT---------------------------
-----SPTQQEKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSGACG00000014070

MPMHPVTSTLMYRGICTIPDILSYSAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTAAGLPDKFHGTDFDSVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPGECQVDIDS---------------------------
-----NPTQHVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSXMAG00000001396

MPVRAVTTRFMYKGLCTIPDVLAYRTPVHLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVGFEEFVTLLGP
KLSAAGMPDKFHGADFDSVFWKCDMQKLTVDELKRLLYDTFRDHLTMKDI
ENIIMTEENHLNSPE-SHVDIDT---------------------------
-----SPTQQEKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSTRUG00000016477

MPMHPVTSTLMYRGMCTIPDILSYSAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTAAGVPDKFNGTDFDSVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPEDCQLDIDSS--------------------------
-----SPTQQVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSTNIG00000009067

MPVRAVTTRFMYKGLCTIPDVLSLRSPVILPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDIDGDGQVGFEEFVTLLGP
KLSSAGMPDKFHGADFDSVFWKCDMQKLTVDELKRLLYDTFRDHLTMKDI
ENIIITEENHLNSPE-CHVDIDT---------------------------
-----SPTQQEKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSONIG00000010625

MPMHPVTSTLMYRGICTIPDILSYSAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTAAGLPDKFSGTDFDSVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPEDCQVDIDSS--------------------------
-----SPTQQVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSORLG00000000855

MPMHPVTSTLMYRGMCTIPDILSYSAPVNLPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KLTASGVPDKFNGTDFDSVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPEDCQVDIDSS--------------------------
-----SPTQHVKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
>P1;ENSTRUG00000012475

MPVRAVTTRFMYKGLCTIPDVLSLRSPVILPEDEVEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDIDGDGQVGFEEFVTLLGP
KLSSAGMPDKFNGADFDSVFWKCDMQKLTVDELKRLLYDTFRDHLTMKDI
ENIIMTEENHLNSPE-CHVDIDT---------------------------
-----SPTQQEKHTCVRKSLICAFAIAFIISVMLIAANQMLRRGMK
*
>P1;ENSLOCG00000003661

MPLHPVTSTLMYRGICTIPDILTYRTPINIPEDELEEIREAFKVFDRDGN
GFISKQELGMAMRSLGYMPNEVELEVIIQRLDMDGDGQVDFEEFVTLLGP
KISTAGMPDKFHGTDFDTVFWKCDMQKLTVEELKRLLYDTFCDHLSMKDI
ENIIMTEENHIENPEECPVDIDT---------------------------
-----SPTQQIKQTCVRKSLICAFAIAFIISVMLIAANQVLRSGMK
*
