>P1;ENSDARG00000074073

--------------MAWPCITRACCINRFWSELDKGDIAVPLVFTKYSDV
AEV-QHLHPQ-----PKPVL-SQ-----------------------KPVA
TESHLAHS-AHQEA-SSRATHGAADAA----AA-ASQ-DGSGASVMREDF
KAWSVRPERSCKPRNQYQPSKTPFINETQYQKDYKPWPIPKKGDHPWIPK
PTAAAAPCKAESKF---SKHE--QAAAEMETGVEKCEIEEKQHE---KE-
--SKERRKK----VEKKEPV------------SEAS--------------
--------------------------------------------------
--KME---------------------------------------------
-------------------------------------------KDVAVEG
KRRS---A-ADALNRQIKQEV--TSG--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYRDIKPVKPI
KAKSQYKLLVGEKTNLETSYSATFKGEQAKPQTTDNKLMEHRRIRSLYSE
PSKESS-KVERHNLSLTKPKKTPS----HSKTVKKAKEKPVAGSQPAKKK
TSVSNQEPKPEGGVTKKSKEMINRLAEAKD--------------------
--------------------------------------------------
-------------
*
>P1;ENSTNIG00000008576

DHKQQQTLGMVAMAMAWPCISRACCMARFWNQLDKADIAVPLVFT-YADA
SEM-QHVQPQ-----PS----SQ-----------------------ARVA
IETQPSRA--ESRT-R-TVAR---APR----RC-VSE-ERVCSSVMREDF
KRWNVRPEPSCKPKNEYHEPEAPFYSETQYQKDFKPWPIPKRYDHPWIQK
APRLDN-R-GPDRP---RQPKRAAAPTAADGDVEKSAIADKVQE---KD-
--LLQGHER----KK-GSRREA-----EAR--------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------RAVEGEG
RGRR---S-TDALNRQIKEEIT--GG--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RAEYKAYADVKPTRMI
RAKSQYLP-PEEKTRLETSYSATFRA-QAPAQPADNKALDRRRVRSLYAD
PSKQVD-RYSL---PRSKAKQPGAAASGQGTPLKKAKDKQGGAHRGSRKM
AAE----KQPV-GNKEKSKEMNNKLAEAKE--------------------
--------------------------------------------------
-------------
*
>P1;ENSTNIG00000003291

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
QHL-PH---H-----PQPKQSAA-----------------------GAIA
IETQPHPQRAEQEA--------------------GTE-DGLTASVMRQDF
KAWRVRPEPSCKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPK
PSPGSA-SRGPERS---AKLE--HAAGEAESGVEKSEIEEKIHE---KE-
--TKEVTRR----EK-SAER------------DAGE--------------
--------------------------------------------------
--KTE---------------------------------------------
-------------------------------------------PACAEAR
KGRA---A-ADALNRQLKEVM--STS--SSYRYFCQLPSAGETDRWDWC-
--------------------------------------------------
--------------------------------------------------
----------------------------YIPAASTATLHNTSSQVRPVTV
PE-------------RTTEHIRAPCVHRAAAATQLNQQPSETIIHTSP--
-------------------------------NFRRTEFKAYKDVKPTKPI
KAPSQYKP-PGEETNLETSYSATFKGEQVKAHPADNKAMERRRIRSLYSE
PSKASP-KVDKP-ASHAKSRKTSSTATTAGKMAKKTKEKQISSSQSAKKK
PPLVTAEPRPEGVITKKSKEISNRLAEAKQ--------------------
--------------------------------------------------
-------------
*
>P1;ENSORLG00000012570

--------------MAWPCISRACCMARFWNQLDHADIAVPLVFTKYTDA
SEM-QHIQLQ-----PQ-LPRPQ-----------------------ARVA
IETQPSRS--KPRT-A-PG-K------------------ACPAVLVRKHL
KGN----CPKCRRK-DFFPVDCALSRKPAVQKGFAACRDEEDADPP----
------------------------------SRGSKLLKKKRIPE---KD-
--GWAIYQN----SL-KRINLSYTTTTHLK---SSR----R---------
--------------------------------------------------
---AS---------------------------------------------
------------------------------------------SSQSRGDG
RGRGVKPG-VDRIHSQPTTNCV--SS--STY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------KDETEFKAYRDVRPVRMI
RAKSQYLP-PDERPSLETSYSATFKV-QTPLQPADNKAQERRRIRSLYSE
PYIDPSKQVDRYSPTCSKPKKSGATSAGQGKPLKKAKDKQTTPLKGSKKA
TLENQPQDRPAVGDKEKSKEINNKLAEAKE--------------------
--------------------------------------------------
-------------
*
>P1;ENSAMXG00000008868

--------------MAWPCIARACCMARFWTQLDKADIAVPLVFVKYSEV
SEETQQLQRD-----RE-REKDRDRERNRERDREKDRHRDRTRDRLQEKS
QERDPERN--RQEV-----------------TR-DGR-ENAPGSVMRQDF
KAWKVRPEPSCKPKCEYHGPEVPFDSQTQYRQDYKPWPIPRRGDHPWIPK
PA--------------------------LECGLEKSQTADKVQE---KE-
--MLMGEKK----KR-QVKRVE-----KEKKVITGK----E---------
--------------------------------------------------
---GS---------------------------------------------
------------------------------------------AEAPVNVG
KGRE---A-VDALNRQIKQEVG--GG--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYTDVKPVKLI
RAKSQYHP-PDEKTNLETSYSATFRGEQAKLQPADNKALERRRIRTLYSE
PYLDSS-KGERSSLPRSKPKKTTSSSTSQGKTVKKSKEKQTASVRGSKKK
SSENQPERRAAQGDKEKSKEMNNKLAEAKE--------------------
--------------------------------------------------
-------------
*
>P1;ENSDARG00000074521

--------------MAWPCISRACCMARFWSQLDKADIAVPLVFTKYSDV
SEM-QHLHLQ-----QP-VQ---------------------------KIA
IETQPLHH--DHEP-V-T--R---AP-----HA-GHD-EHSFGSVMRQDF
KHWKVRPEPSCKPKNEYHGPEIPFNTETQYQKDYKPWPIPKKGDHPWIPK
PSPSIS-A-GKH----------SSPEMMMDSGVEKSEIADKVPE---KE-
--ILSSERK----KR-QVKKVA-----VVSENNAGV----K---------
--------------------------------------------------
---LD---------------------------------------------
------------------------------------------RDASAVEG
KGRA---A-VDALNRQIKREVS--SG--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYTDVKPVKLI
RAKSQYKP-PDDKTDLETSYSATYRAYQSSQQPDDNKALERRRIRTLYHE
PYRESS-KVEKTSLPRSKPKKSSSTSATPGKPLKKSKEKQATSVRGSKKK
SSENQPESRAVQADKEKSKEINNKLAEAKEVMLKQYHYIQLCQPIRDIGW
VQTLKQHLWRCALPDPRECESGVGRVSDYYSAGTSGGEP--LVERPEPR-
SRGVVRFAPDVKY
*
>P1;ENSGACG00000010429

--------------MAWPCLTRACCINRYWTELDKADVAVPLVFGKYSDA
ADA-QHLPHH-----PQPRHKRA-----------------------GAIA
IETQPHRA--EQGP-G-KAPP---ATA----AA-AGK-DGSAASVMRQDF
KAWSVRPEPSCKPRNEYQRSAAPFNTETQYQKDYKPWPIPKKRDHPWIPP
QRRERK-A--GSRG-----RE--RRGEERDRGENAGERVNRGGE---DE-
--REEGKVR----RE-GNGR------------EDGQSGARGCERRAEERQ
GGRRRAEQADQAAIGEFIPP--------QPIAIKKPLLRPFQNEF-----
ADIFSRLSTQSSIRVSISTQYFK-----------------WFFNKITPKS
SVIKH-LENILSKINGARTGMT--NRPCVPVITAVRMCFVSRKQNTRSEG
QDEA---TWQLSLNYRITYVLIKTLF--SPC-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYKDVKLVKAI
KAPDQYKP-PVKEASLETSYSATYKGEQMKAQPTDNKLVERRRIRSLYSE
PGKEAA-KVDKP-VSRTKQKKTPT--TTTGKMVKKSKEKQIASSQSAKKK
PSSCAPKPKPDGAVTKKSKEISNRLAESKQ--------------------
--------------------------------------------------
-------------
*
>P1;ENSONIG00000011169

--------------MAWPCITRACCINRFWSELDKADIAVPLVFARYSDV
ADV-PHVPHH-----PQPKLKKA-----------------------GAIA
IETQPHPG--EQEA-G-KAPP---ATG----AA-AGK-DGSTASVMRQDF
KAWRVRPEASCKPRNEYQPSPAPFNNETQYQKDYKPWPIPKKHDHPWIPK
SSPTAG-G--PERSAGSGKLE--QVAAEAESGVEKSEIEEKTQE---KE-
--SQEVVKRSVKREK-SSER------------KTGE--------------
--------------------------------------------------
--KTE---------------------------------------------
----------------------------------GQ----VAADVSAEQR
KGRA---A-ADALNRQIKEVM--STS--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYKDVKPVKPI
KAPSQYKP-PGEETSLETSYSATFKGEQVKAHPMDNKLLERRRIRSLYSE
PSKEPA-KVDKP-VSRTKPKKSSSTPTTTGRMQKKAKEKQISSSQSAKKK
PSLGASEPKPGGAVTKKSKEISNRLAEAGK--------------------
--------------------------------------------------
-------------
*
>P1;ENSTRUG00000007180

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHFPHH-----PQPKQNRA-----------------------GAIA
IETQPHPHRGEPEA-G-KAPP---ATG----AA-AGD-D--GLSVMRHDF
KAWRVRPEPSCKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPK
ASPGST-SKGPERS---AKLE--QAASEAESGVEKSEIEEKIHE---KE-
--SKEVTKR----EK-SAER------------EVGE--------------
--------------------------------------------------
--KTE---------------------------------------------
-------------------------------------------PACAETR
KGRA---A-ADALNRQLKEVM--STS--SSYRF-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------T--
-------------------------------KKYRTEFKAYKDVKPTKPI
KAPSQYKP-PGEETNLETSYSATYKGEQVKAHPADNKVMERRRIRSLYSE
PSKAGA-KVDKP-ASHTKPKKTPT---TAGKMGKKSKEKQISGSQSAKKK
PSLVSAEPKPEGVITKKSKEISNRLAEAKH--------------------
--------------------------------------------------
-------------
*
>P1;ENSXMAG00000001705

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHLPHH-----PQPRQKQA-----------------------AAIA
IETQPHPE--EREA-A-KAPP---AAG----GAAAAKGGASAASVMRQDF
KAWRVRPEPSCKPRNEYQPPPAPFSNETQYQKDYKPWPIPRKHDHPWIPK
PSPTAG-S----KL--EHAAA--AAAGESESGVEKSEIEEKIQE---KE-
--SKEAARR----EK-SAER------------KAAE--------------
--------------------------------------------------
--KTE---------------------------------------------
----------------------------------GP------AEVSAEQR
RGRA---A-ADALNRQIKEVM--STS--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYKDVKPVKPI
KAPSQYKP-PGEETSLETSYSATYKGEQVKAQPTDNKLLERRRIRSLYSE
PGKEPA-KVDKP-TSRTKPKKAPT--TTTGKMVKKSKEKQIAGSQLAKKK
PSAKTPEAMPEGTVTKKSKEISNRLAEAKH--------------------
--------------------------------------------------
-------------
*
>P1;ENSTRUG00000017372

R-PLERSLVFGALAMAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQ-----PS----AQ-----------------------ARVA
IETQPPRA--QSRT-R-TAAH---APR----RC-VSE-ERVCNSVMREDF
KRWNVRPEPSCKPKNEYHEPETPFYSETQYQKDFKPWPIPKRCDHPWIQK
APRVDN-R-VPDRP---R----QQA--AADGEAEKSAVADRVQE---KD-
--LLQGHGR----SK-ASRKEA-----ELK----------K---------
--------------------------------------------------
---V----------------------------------------------
------------------------------------------VLRVEGEG
RGRR---S-TDAVNRQIKE-IA--GS--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RAEYKAYADVKPTRMI
RAKSQYLP-PDEKTRLETSYSATFKA-QAPAPPADNKALDRRRVRSLYTD
PSKQPP-QMDRYSLPRSKPRQSGAAASGQGTPVKRAKDKQGVAQRGSRKM
AVE----KQPV-GSKEKSKEINNKLAEAKE--------------------
--------------------------------------------------
-------------
*
>P1;ENSORLG00000005434

--------------MAWPCITRACCINRFWTELDKGDIAVPLVFTKYSDA
AEV-HHLPHH-----PQPKQRVV-----------------------GTIA
IETQPHPE--EQEA-A-RAPP---ATG----AA-AGR-TGTATSVMRQDF
KAWGVRPEPSCKPRNEYQPPPSPFNNETQYQKDYKPWPIPKKHDHPWIPK
PSSTAA----PERS---SKKE--HAAAEADSGGEESGWQTGAAGVCKGER
RAAEEQGSR----RR-SQQT------------DQGG--------------
-------------HVHFQLLQVNIITPLGPAGRTDHQ--PSPHHLQPIEE
THSMEP---WIKNSMDTSEDH-KSLKKKCSAHCLVGLDDPTPNVKVPRIA
QGLNHFLASLYLRRDTIRLGYLSVRDPKPKRIQ-SR----RRYYDAKQGG
KGSL---S-YFAETMQQEEAA--ASGVQFTC-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RTEFKAYKDVKPVKAI
KATSQYKP-PMEETSLETSYSATYKGEQVKPKESDNKLLERRRIRSLYSE
PGKEAA-KVDKP-ESRLKPKKAP---TTTGKMLKKAKERQIASSQSTKKK
PSAGPSE--PEGTVTKKSKEISNRLAEAKQ--------------------
--------------------------------------------------
-------------
*
>P1;ENSGACG00000020200

--------------MAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQ-----PP-LHPPR-----------------------GRVA
IETQPTRA--E---------------------C-VSE-ERVCGSVMREDF
KHWNVRPETSCKPKYEYHEPETPFNCESQYQKDFKPWPIPKRYDHPWIPK
PPASDE-R-APDRS---RH---RKQPAEADSGVEKSAIADKVQE---KD-
--LVQGPHR----KK-KSSKQE-----GPK----------K---------
--------------------------------------------------
---V----------------------------------------------
------------------------------------------SLKVEGEG
KGRA---A-ADAVNRQIKQEIA--GD--SLYNNQSYVNLGGNV---SWCA
QESPCFRDKRFQPAASQSPAPSGLYLAANQLHYEMEAGKAGSVRSDSGYV
KYCNPIQPAVLTKLSGHWKSSLLRLQKVGVTQKKGPSHTAMYRCSSQLLA
VSIEPLPEKLQRGRELETRPTGPTGKREYRPGARPSPAHTPRNTARTGSL
PPAQIDSFKDHERGGLASETIDAPSYMHASACSCIHTQPCKHLTSTTHNS
GVSEGWGTYINRKLGSLLGLALHKEVELTMSYTNRTEYKAYRDVKPAKMI
RARSQYLP-PDEKTSLETSYSATYKG-QAPLRPAGNKALDRRRIRSLYSE
PYIDPIKQVDRYSALRTKPKKPGASAAGQVKQAKKAKDKQSAGLRGSKKT
ASENQLENRPAVGDKEKSKEMNNKLAEAKE--------------------
--------------------------------------------------
-------------
*
>P1;ENSLOCG00000004684

R-ILFDLRYFIAFTMAWPCITRACCIARFWNQLDKADIAVPLVFTKYSDV
TEM-QHLHLQHQQKQPHPQA-RA-----------------------ESVA
IETQPSLS--DQEAVA-RATP---APGARAAAA-AAE-ESPGGSVMRQDF
KPWKVRPEPSCKPKNEYHPSEAPFNNETQYQKDFKAWPIPKRGDHPWIPK
SSPSPS-I-AGDRAVEKAKPA--HAPADAESGQEKSEIADKVQE---KE-
--ILSEEKQ----SKKKVKTVTVP-------EGAGK--------------
--------------------------------------------------
--KVA---------------------------------------------
----------------------------------AK------AEGAVAEG
RGRA---A-ADALNRQIKEEV--ASV--SSY-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------RNEFKAYADVKPVKLH
KARAQYQP-PDKRASLETSYSATFRGEQGKRVPADNKVLERRRIRSLYSE
PSKESP-KVEKPSVPRSKPKKTTA---SHSKPVKKAKEKQISSGRSTKKK
EQENTAESKPEEGDKEKSKEINNKLAEAKEE-------------------
-------------PKVEVCGSG------DHSQGAVGGEPEPQGERPRPRR
GSGVVRFAPDVK-
*
