>P1;ENSTRUG00000005896

-----------KPKM-PSKN-DDGGWKKFMWNSETGELLGRTGGSWFKIL
LFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTWQDRVAPPGLSHTPKSDKT
EMSYNPDEFETYLPYTKALREFLSKYDEEAQMDPMKFEDCGEEPADYKNR
GELES-DMGVRKACRFSRTVLGPCSGLDD---REFGFKEGKPCVIVKLNR
IVNFRPRPPSSNDTIPEDAQHKVQPNVIPIFCTNKREEDAGKIGEIKYYG
IGG--GFPMQYYPYYGKLLHSHYLQPLVALQFTNLTRNTELRIECKVFGD
NIDYSEKDRYQGRFDIKFQINT-S
*
>P1;ENSORLG00000020664

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----D-NAGVRKACRFSRTLLGPCSGLED---ETFGFKDGKPCVIVKLNR
IVNFRPRPPSSNDSIPEEAWPKVQPNLIPLFCTNKREEDADKIGEIKYYG
ING--GFPLQYYPYYGKRLHPHYLQPLVAVQFTNLTQNMELRIECKVFGD
NIDYNEKDRYQGRFDLKIQINS-V
*
>P1;ENSONIG00000019331

-----------MS---GNKD-SDGGWKNFVWNSEKKEFLGRTGGSWFKIL
LFYVIFYGCLAGIFVGTIQALLLTLSKDKPTYQDRVAPPGLSHTPRSDKS
EISFTRSDQSSYSKYVQSMNEFLELYNDTKQNG-DPYEECGKFPGTYKDR
SMEE-----KKKVCKFLRSWLKNCSGITD---PDYGFMEGSPCVIIKLNR
IVNFRPKAPS-NNSLLEELQAKITPNEIPIYCKPKRAEDKGQIEEIKYFG
ISQ--GFPLQYYPYYGKQLHPDYLQPLMAVQFVNVTVGKEIRIECKAFGD
NIDYSEKDRYQGRFDIKLTVS---
*
>P1;ENSTNIG00000013777

K----------MS---RNKE-NDGGWRTFLWNSEKGEFLGRTGCSWFKIL
LFYVIFYLCLAGIFAGTIQVLLLTLSSYKPTYQDRVAPPGLSHFPRSDKA
EISFSLSDNKTYGAYIQSISKFLHLYHQDMQTDQMKYEDCAAVPATYTER
EPLES-DAGQRKACRFSASLLGSCSGESD---PTYGFSKGRPCIIVKLNR
IVNYRPKAPS-VESLPEALQGKVSPFVIPIHCKTKRAEDENKIGEINYFG
IGN--GFPLQYYPYYGKLLHPMYLQPLVAVQFNNVTLDQEIRIECKAYGA
NIKYSDKDRYQGRFDIKLTISS--
*
>P1;ENSAMXG00000011833

-----------MP---ANKD-GDGGWKSFLWNSEKKEFLGRTGCSWLKIF
IFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTYQDRVAPPGLSHTPRSEKA
EISYSLSDEDTYRFLTKAMKELLEPYSEEKQTDENQFEDCGENPAMYKNR
GELES-DMGKRKACRFKKSWLGACSGE-DP---HFGFKDGKPCILVKLNR
IVNFRPKAPA-NSSLPVNLQGKVQANLIPIHCSSKKEEDAGKIGEIKYHG
MGS--GFPLQYYPYYGKLLHPQYLQPLVAVQFVNITQNTDLRIECKVYGE
NIDYSEKDRYQGRFDLKLYVK--S
*
>P1;ENSXMAG00000016407

-----------MA---GKKE-SDGGWRKFLWNSEKREFLGRTGGSWLKIF
LFYVIFYGCLAAIFIGTIQALLLTIHEFKPTHQDRVAPPGLSHTPRSDKS
EISFKISDPASYQRYTASMMAFLKPYSKEEQDKDSNYEDCSESPKTYTDR
GKLED-DHGVRKSCYFYRSHLGSCSGETD---ESFGFSEGKPCLIVKLNR
IVNFRPKPPTNNSTLPDGLKGKTFENYIPIHCKNRREEDESKIGEIKYFG
LGGLAGFPLQYYPYYGKRLHPNYLQPLVAIQFTNLTLKEELRIECKVYGD
NIDYNEKDRYQGRFDVKFTVN--S
*
>P1;ENSGACG00000015312

-----------TT-M-SSTK-DDGGWKRFVWDSDKGELLGRTGGSWLKII
GFYIIFYGCLAGVFVGTIQALLLTLSNYKPTWQDRVAPPGLSHTPRSDKS
EVSFNLNDVETYLPYTKALKDFMAKYNEDIQKDQMKFEDCTDSPADYKNR
GDLES-DQGIRKACRFYRNLLGPCSGLDD---PDFGFKEGKPCIIVKLNR
IVNFRPKPPTSNESIPDEAQHKVQPNVIPIYCTNKREEDAGKIGEIKYHG
IGG--GFPLQYYPYYGKLLHPQYLQPLLALQFTNLTLNTELRIECKVFGD
NIGYSEKDRYQGRFEIKLSIN--S
*
>P1;ENSXMAG00000009766

-----------MP---SNK--DDGGWKEFLWNSEKGELLGRTGGSWFKVA
LFYVIFFGILAGIFVGTIQAMLMTLSENKPTWQDRVAPPGLSHTPRVDKA
EVFFNVRESETYLRYVKAMRDFMKLYDDNIQTNNMLFEDCGEQPADYKHR
GDLES-DMGGVKACRFPKTLLGPCSGIED---NDFGFKDGKPCLIVKLNR
IVNFRPRPPSNNDSIPEEAKPKVQANIIPLYCTNKREEDADKIGEIKYYG
IGE--GFPLQYYPYYGKRHHPQYLQPLVALQFTNLTRNTELRIECKVFGE
NLYYNEKDRYQGRFDIKIQVD--S
*
>P1;ENSORLG00000015696

-----------MS---GNKESSDGGWRKFMWNSEKGEFLGRTGCSWFKIF
MFYLIFYGCLAGIFIGTIQALLLTLSNYKPTYQDRVAPPGLSHTPRSDKS
EISFKMSDNSTFKKYVDSMNELLLKYDEDRQTAQGKYESCGENPDTYKEQ
GGLEE-GSGQRTSCRFLRKWLGDCSGLTD---NTYGFKEGKPCLIVKLNR
IVFFRPKGPSNNSTLPEALQGKSYNNLIPVYCKNKRPEDASKIGEIKYFG
FGG--GFPLQYYPYYGKQLHPNYLQPLVAIQFTNLTIGEDLRIDCRVFGD
NIAYSEKDRYMGRFDVKITVN--S
*
>P1;ENSDARG00000076833

NSLLKWTNKTLQYTMPAQNK-DDGGWKKFVWNSEKKEFLGRTGGSWAKIF
LFYLIFYGCLAGIFIGTIQILLLTLSDYKPTWQDRVAPPGLTHFPRSDKS
EIAINLDDEVSFLNYVKVMREFLTSYDQEKQLDNMQFENCGESPLDYKNR
GDLES-DVGVRRACQFSREWLGPCSGLDD---PYFGFKEGKPCLIAKLNR
IVNFRPKPPVSNESIPEEVQHKVQPYLIPIHCTNKKEEDAGKLGEVRYYG
FGG--GFPLQYYPYYGKLLHPQYLQPLVAIQFLNITPNTDMRIECKVYGE
NIYYHDKDRYQGRFDVKFNIKK-S
*
>P1;ENSONIG00000003739

-----------MP---SDKK-DDGGWKKFLWNSETGELLGRTGGSWFKIT
LFYVIFYGCLAGIFIGTIQAMLLTLSEYKPTWQDRVAPPGLTHTPRSDKA
ELAFNPRAVETFLPHTKALREFLNNYDESKQKDQMKYEDCGDEPADYKNR
GDLDS-DVGVRKACRFPRALLGPCSGLED---TEFGFKEGKPCLIVKLNR
IVNYRPRPPTSNESIPEEAQPKVQPNVIPIYCTSKKEEDADKIGEIKYYG
IGE--GFPLQYYPYYGKKLHPQYLQPLVALQFTNLTRNTELRIECKVFGD
NIDYSEKDRYQGRFEIKIQVDE-S
*
>P1;ENSTNIG00000014477

-----------KPKM-PSKN-DDGGWKKFMWNSETGELMGRTAGSWFKII
LFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTWQDRVAPPGLSHTPRADKA
ELSFNILEFETYLPHTKALREFLTKYDDEAQMDSMKFEECGNEPAEYRNR
GELES-DMGVRKACRFNRELLGPCSGLVD---REFGFKEAKPCVIVKLNR
IVNFRPRPPSSNDSIPEEAQYKVQPNVIPLYCTSKKEEDAGKIGEIKYYG
IGG--GFPMQYYPYYGKLLHPHYLQPLVALQFTNLTLNTELRIECKVFGD
NIHYSEKDRYQGRFDIKIQINT-S
*
>P1;ENSDARG00000013144

-----------MP---ANKD-GDGGWKSFIWNSDKKEFLGRTGCSWLKIF
IFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTYQDRVAPPGLSHSPRPDKA
EISYNINDESTYMPYVNHIDAFLKAYNQDIQEDNTKFEDCGDKPEFYTDR
GELES-DNGVRKACRFRREWLGECSGQKDEKQKNYGFDDGQPCLIVKLNR
IVNFMPRPPASNDSIPEAVRPKLQGNVIPIHCSSKREEEANLLGQIKYFG
VGN--GFPLQYYPYYGKLLQPQYLQPLVAIKFYNITTDVDVRVECKVYGE
NIDYSEKDRSQGRFDIKFTIKTKS
*
>P1;ENSTRUG00000004970

FK---------MS---RNKD-NDGGWRTFVWNSEKGEFLGRTGCSWFKIL
MFYVIFYLCLAGIFAGTIQVLLLTLSNYKPTYQDRVAPPGLSHFPRSEKA
EIYFSLSDAGSYQTYTQSIEKFLDVYQDDKQLDQLNYDDCGAAPGTYTER
GSLES-TEGQRKACRFSKSLLGSCSGDGD---PTFGFSQGKPCIIVKLNR
IVNYRPKPPS-NESLPEALQGKVSPNVIPIHCKPKRAEDEDRIGEINYFG
IGN--GFPLQYYPYYGKLLHPMYLQPLVAVQFTNVTLNQEVRIECKAYGK
NIDYSDKDRYQGRFDIKLTISS--
*
>P1;ENSGACG00000013647

-----------MQ---ANKD-SDGGWRTFVWNSEKKEFLGRTGSSWLKIF
LFYVIFYGCLAGIFIGTIQALLLTLSNYKPTYQDRVAPPGLSHTPRSEKS
EIAFSLSDASSYKKYTDAMTKFLKKYDDDKQTDQMKFEDCGGVPENYKDR
GAPEDNNPGQRIGWRLKRSLVGVWPRLGN----RSGFHTREAWLIVKLNR
IVNFSFQPPM-NNSVEEFLLPKLKPNLIPIFCKNKREEDADKIGEIKFFG
LGE--GFPLQYYPYYGKLLHPQYLQPLVAIQFNNLTLNEELRIECKVFGE
NIGYSEKDRYQGRFDVKFNIA--S
*
