>P1;ENSXMAG00000016537

I--MTFEEVLIQKP------AERAQCAGAALEEVLVSAKDNQSLTVGVYE
CAKVMNLDPDSVSFCVLATDEQFEWDVALQIHFTLIQSFCFDNDISIVRV
SDTQRLAAIVGD----EQEDAHCVLIT---VRAGAERRGGLRGAAAQQSY
INVLINTNITGENELELTEYI--------
*
>P1;ENSTRUG00000015127

---MTLEEIHEQENA-M-ENTDRVQSAGAALEELLVAAKKQDYITVGVYE
SAKVMNVDPDSVAFCVLATDEEYQCDIALQIHFTLIQAFCFDNDINVVRV
NDIERLADLVGADESGEPKDVHCILVT---SPSANPWK----NP------
--SLDKLSLFCEESRSVYDWVPTITLPER
*
>P1;ENSDARG00000044676

---MV--------------------NEGKALSEALLSAKAEGRLTVGVYE
CAKIMNEDPDSVSFCLLATD-DFECDIALQIHFTLIQAFCFDNDISIVRV
NDLKRLNALVGG-K-GQLEEAHCVLIT---NPTEDSWE----DP------
--ALEKLHLFCEESRSYNEWVPEITLPER
*
>P1;ENSGACG00000017938

---MTFEEVLIQKP------AERAQCTGKALEEVLVSAQDNDALTVGVYE
CAKVMNLDPDSVSFCVLAMDEDFQCDIALQIHFTLIQSFCFDNDISIVRV
SDTQRVAEIVGD-K-AQLEDAHCVLIT---NPAEGSWE----DP------
--ALEKLHLFCEESRNVNDWVPEIVLPER
*
>P1;ENSGACG00000006793

---MTLEEIRGQENA-M-EIPDRVQSAGAALEELLQAAKKQEYLTVGVYE
SAKVMNVDPDSVAFCVLATDEEYECDIALQIHFTLIQAFCFDNDINVVRV
NDIERLADLVSAGEPGEPKDAHCILVT---SPSANPWK----DP------
--ALDKLSGFCEERRSVYDWVPTVTLPER
*
>P1;ENSDARG00000019417

---MTFEELSGQDNT-A-TTGDRMQTAGTALEELLVSAKKQDCLTVGVYE
SAQVMNVDPDSVAFCVLATDEEYEYDIALQIHFTLIQAFCFDNDINIVRV
NDIERLADIVGCDQDEEPKDAHCILVT---RPNDDSWK----DS------
--ALDKLGLFCEESRNVYEWVPSITLPER
*
>P1;ENSAMXG00000005863

SV-MTFEEVCGQEND----TSDRMRSAGSALEELLLSAKKNDCLTVGVYE
SAKVMNVDPDSVAFCVLATDEEYECDMALQIHFTLIQAFCFDNDINIVRV
SDIERLADIVGNDETGEPKDAHCILVT---NPNLESWK----DP------
--SLEKLSVFCEERRSVYEWVPAITLPER
*
>P1;ENSAMXG00000009069

LI-MTLEEVPVQQNN----CIEKARRTGEALQEALESAQANDCLTIGVYE
SAKVMNVDPDSVAFCVLAMDEEFECDIALQIHFTLIQAFCFDNDISIVRV
SDAQRLAELLGD-KAGQLEDAHCVLIT---NPTDGSWE----DP------
--ALEKLHVFCSESRSCHEWVPEVTLPAR
*
>P1;ENSTNIG00000016668

---MTLEEIRGQEKD-M-ESADRVQSAGAALEELLVAAKKQDYITVGVYE
SAKVMNVDPDSVAFCVLATDEEYQCDIALQIHFTLIQAFCFDNDVNVVRV
TDIERLADIVGADETGESKDVHCILVT---SPSANPWK----NP------
--ALDKLGLFCEESRSVYDWVPTITLPER
*
>P1;ENSONIG00000015195

IITMTLEEIHGQENT-M-ENADRVQSAGAALEELLIAAKKQDYLTVGVYE
SAKVMNVDPDSVAFCILATDEEYECDIALQIHFTLIQAFCFDNDINVVRV
NDIDRLADLVGADETGEPKDAHCILVTQLQSPSANPWK----DP------
--ALDKLSVFCEERRSVYDWVPTITLPER
*
>P1;ENSORLG00000014766

---MTFEEVPIQKP------TERAQCAGKALEEVLETAKDNESLTVGVYE
SAKVMNLDPDSVSFCVLAMDEQFQCDIALQIHFTLIQSFCFDNDISIVRV
SDMQRLADIVGD-KAEELEDAHCVLIT---NPADGSWE----EP------
--ALEKLHLFCEESRRLNDWVPEISLPER
*
>P1;ENSTRUG00000012938

---MTFEEVLIQEA------VERVQCTGKALEEVLVSAIENHSVTVGVYE
CAKVMNVDPDSVSFCVLAMDEEFECDIALQIHFTLIQSFCFDNDISIVRV
SDMQRLAEIVGN-KADQLEDAHCVLIT---SPAEGSWE----DP------
--SLEKLHLFCEESRRLNDWLPEINLPAR
*
>P1;ENSORLG00000003982

---MTLEEINGQCLNEMRFSLFRVQSAGAALEELLLAAKKQDYLTVGVYE
SAKVMNVDPDSVAFCVLATDEEYECDIALQIHFTLIQAFCFDNDINVVRV
NDIERLADLVGADETGEPKDVHCILVT---SPSANPWK----DP------
--SLDKLSLFCEESRNAYDWVPTITLPER
*
>P1;ENSONIG00000012799

---MTFEEVLIQKP------AERAQCAGTALEEVLVTAKDNDSLTVGVYE
CAKVMNLDPDSVSFCVLAMDEEFECDIALQIHFTLIQSFCFDNDISIVRV
SDMQRLVEIVGD-KAEQFEDAHCVLIT---NPADGSWE----DP------
--ALEKLHLFCEESRRLNDWVPEISLPER
*
