>P1;ENSXMAG00000011880

M-----SF--SGEAMLKAVEAPLFWLGVLTAAWLSVCSVYRLLSGFRVWV
LGNGRLISPNKLGKWAVVTGATDGIGKAYAEEL-ARRGFAIV-LISRSQE
KLDDVSKAIASKCGVETKTIAADFSAIDIYAKIEEGLAGLEIGLLVNNVG
TSYSYPEFFLNIPNLDTFIDTMININITSVCQMTRLVLPQ--MVERKKGA
ILNISSASGMYPVPLLTVYSASK--AFVDFFSRGLQAEYKSKGIIIQSIL
PFFVATKMSRIRRPTLDRPSPEHYVAAELNTVGLQTQTNGYLPHAIMGWV
TTALLPAKMLNSYVMGMGLSQRARYLKKQKQ-----G---------
*
>P1;ENSAMXG00000013705

I-----EVFSELEKMLHGAESVLLWVGALTTASLALWILYRLLSGFRIWV
MGNGDLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFSMM-LISRTQE
KLDDVAQSLERRYKVETKTVAVDFGQVDIYPKIETALSGLEIGVLVNNVG
ISYPYPEFFLHIPDLDNFINTMINVNITSVCQMTRLVLPR--MEARAKGV
ILNISSASGMYPVPLLTVYSSTK--AFVDFFSRGLQAEYKSKGIIIQSVL
PFFVATKMTKIRKPTLDKPTPDRYVAAELTTVGLQDQTNGYFPHAVMGWL
TTVLVPINLVIYFGMRMNKAQRGGYLRRRKLR--------------
*
>P1;ENSTRUG00000016257

V-----NTMSTGEALLRAAEAPLFWLGALTASWASLCLVYRLLSGFKVWV
LGNGRFMSPHKLGKWAVVTGATDGIGKAYAEDL-ARRGFAIV-LISRSQD
KLDELSKAIASKCGVETKTIAADFSCLDIYSKIEAGLAGLEIGVLVNNVG
ISYSYPEFFLDVPNLDTVSDSVISGLFVAIFPLAHVSLLS---VCRKRGA
ILNISSASGMYPVPLLTIYSASK--AFVDFFSRGLQAEYKSRGIVIQSVL
PFFVVTKMSKIRRPTLTAPSAEHYVSAELNTVGLQTQTNGYLPHAIMGWV
TTALLPAKILTGHIMRMNLSMRAYNLKKQKE-----K---------
*
>P1;ENSGACG00000006929

M-----QTC--SEQGFP-LKKQQAWLIVMFSLFRGMWLFLFLLSSSADSL
RPPRGLRRP-N-SRGIIVTGATDGIGKSYAEEL-ARRGFAMM-LISRSQD
KLDDVAMSLKEQFKVETRTIAADFGKTDIYNKIEAGLAGLEIGVLVNNVG
VSYPYPEYYLQIPDLDNFITNMINVNITSVCQMTRLVLPK--MTERSKGV
ILNISSASGMYPVPLLTAYSSTK--AFVDFFSRGLHEEYRRQGIIIQSVL
PFFVVTKMTRIKKPTLDKPTPDRYVAAELATVGLQDQTNGYFPHAVMGWL
TTKLVPMKLVIFFGARMNRLQRTGYLQRKKLREQ------------
*
>P1;ENSTNIG00000009599

--------------------------------------------------
-------------SFIVVTGATDGIGKAYAEDL-ARRGFAIV-LISRSQD
KLDEISKAISSKCGVETKTIAADFSCLDIYSKIEAELAGLEIGVLVNNVG
ISYSFPEFFLDVPNLDTFIDTMVNINIMSVCKMTHLVLPQ--MVERKRGA
ILNISSASGMYPVPLLTVYSASK--AFVDFFSRGLQAEYKSRGVVIQSVL
PFFVATKMSKIRRPTLTVPSPESYVSAALSTVGLQTQTNGYLPHAIMGWV
TTALLPAKILTGHVMRMNLSMRAYNLKRQKDKQ---K---------
*
>P1;ENSTNIG00000010384

-----------VEETLRAAEAPLFWVGACTVASLALWLLYRLVSGFRIWV
LGNGSLLSP-KLGKWAVVTGATDGIGKSYAEEVRAAPGVALAWQISRSQE
KLADVAATLKELYSVETKTIAVDFGRSDIYSKIEEGLAGLEIGVLVNNVG
VSYSYPEYYLHIPDLENFITNMIHVNVTSVCQMTRLVLPR--MADRSRGV
ILNISSASGMYPVPLLTVYSATK--AFVDFFSRGLQEEYRRQGIIIQSVL
PFFVATKMTRIRKPTLDKPTPERYVAAELSTVGLQSQTNGYFPHAVMGWV
TTKLVPSSIVIFLGARMNRLQRTGYLQRRRLR--------------
*
>P1;ENSORLG00000001004

M-----SS--SGEAVLRAVEVPLFWLGAVTAVWLSFCSVYRLLSGLRVWV
LGNGRLVSPNRLGKWAVVTGATDGIGKAYAEEL-ARRGFSIV-LISRSQE
KLDEVSKAIAGKCGVETKTIAVDFSSVDIYPKIEAGLAGLEIGVLVNNVG
ISYSHPEFFLNVPNLDTFIDTMVNINITSVCQMTRLVLPR--MVERKKGA
ILNISSASGMYPVPLLTIYSASK--AFVDFFSRGLQAEYKSKGIIIQSVL
PFFVATKLSKIRRATLDKPNPDRYVAAEINTVGLQTQTNGYLPHAVMGWV
TTALLPAKMLTSYMMGMGLSQRARYLKKQKQ-----G---------
*
>P1;ENSDARG00000015709

M-----ESFN-VVETLQPAERALFWVGALITASLALYVVYKTITGFRIWV
LGNGDLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFSMM-LISRSQE
KLDDVAKSLESTYKVETKTIAVDFSQIDVYPKIEKGLAGLEIGILVNNVG
ISYSYPEFFLHIPDLENFITTMINVNITSVCQMTRLVLPR--MEARAKGV
ILNISSASGMFPVPLLTIYSSTKAIAFVDFFSRGLQTEYKCKGIIIQSVL
PFFVATKMTKIRKPTLDKPTPERYVAAELNTVGLQDQTNGYFPHAVMGWV
TTILAPIDLVLNLGLRMNKAQRGGYLRRRKLR--------------
*
>P1;ENSGACG00000017131

M-----WS--AGEAALRAAETPLLWLGALTAAWLSVCSVYRLLSGIRVWG
LGNGRLVSPDKLGKWAVVTGATDGIGKAYAEEL-ARRGFCIV-LISRSQE
KLDDVSKFISSKCGVETRTIVADFSALDIYSRIEDGLVGLEIGVLVNNVG
ISYSYPEFFLNVPSLDTFIDTMVNVNMTSVCQMTRLVLPG--MVERKKGA
ILNISSASGMYPVPLLTVYSASK--AFVDFFSRGLQAEYKSKGIIIQSVL
PFFVATKLSKIRRATLDKPSPERYVSAELNTVGLQAQTNGYLPHAVMGWV
TTSLLPAAILNSHVMGMGLSQRARYLKKQKQ-----G---------
*
>P1;ENSDARG00000035872

M-----E----------PFADALFWVGAVTVLWLSVSSLWSLINGIRVWI
LGNGNLMRASSLGKWAVVTGATDGIGKAYAEEL-ARRGFAIV-LISRTQE
KLDEVSKAIESKYKVETKTISADFGSVDIYPKIESGLAGLEIGVLVNNVG
VSYSYPEFFLNIPDVDSFINNMININIMSVCQMTRLVLPR--MVDRSKGV
ILNVASASGMYPVPLLTLYSSTK--AFVDFFSRGLDAEYKSKGIIIQSVL
PFYVTTKLSKIRKPTLDIPTPERYVKAQLSTIGLQTQSNGYLPHAIMGWV
TASLLPAKLLNKYVMGMGLSQRARYLKKQKQDS---LSFILEL--A
*
>P1;ENSONIG00000015599

V-----NWMN-VEEMISWAETPLFWVGAFTVASLTLWLLYRLLTGFRIWV
LGNGQLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFAMM-LISRSQE
KLDDVARSIEEQFKVETRTIAVDFGKTDIYPKIEEGLAGLEIGVLVNNVG
VSYPYPEYYLHIPDLENFITNTINVNMTSVCQMTRLVLPR--MCERSKGV
ILNISSASGMYPVPLLTVYSATK--AFVDFFSRGLQEEYRRRGIIIQSVL
PFFVATKMTRIRKPTLDKPTPERYVAAELTTVGLQSQTNGYFPHAVMGWA
TTRLVPSSIVIFLGARMNRLQRTGYLHRRKLR--------------
*
>P1;ENSAMXG00000011213

--------------------------------------------------
--------------------------------------------------
---------ESKYKVQTKTISADFGCVDIYPKIQAGLANLQIGILVNNVG
VSYSYPEFFLNVPNLDNVISSMININISSVCQVSTSLQTRICFVLRSKGV
ILNISSASGMYPVPLLTLYSSSK--AFVDFFSRALDAEYKSKGVIIQSVL
PFYVTTKLSKIKRASLDIPTPERYVRSQISTVGLQNQTNGYLPHAVMGWV
TTALLPARLVSNLVMKMGLSQRARYLKKQKQG--------------
*
>P1;ENSONIG00000005893

MCSAAMSF--SGEAVFRAVEAPLFWLGALTAAWLSLCTVYRLLSGFRVWV
LGNGRLLSPAKLGKWAVVTGATDGIGKAYAEEL-ARKGFAIV-LISRSQE
KLDDVSKAIASKCGVETKTIQADFSAVDIYSKIEGGLTGLEIGVLVNNVG
MSYPYPEFFLSVPNVDTFIDTLVNINITSVCQMTRLVLPQ--MVERKKGA
ILNISSASGMYPVPLLTVYSASK--AFVDYFSRGLQAEYKSKGIIIQSVL
PFFVATKLSKIRRATLDKPSPERYVASQLNTVGLQTQTNGYLPHAIMGWV
TTALLPAKILNSYLMGMSLSQRARYLKKQKQ-----G---------
*
>P1;ENSTRUG00000015387

--------------------------------------------------
-----------------------------------------M-LISRSQE
KLDDVARMLQELYNVETKTIAVDFGKSDIYCRIEAALAGLEIGVLVNNVG
VSYSYPEYYLHIPDLENFISNMINVNMTSVCQMTRLVLPR--MAERSKGV
ILNISSASGMYPVPLLTVYSATK--AFVDFFSRGLQEEYRRQGIIIQSVL
PFFVATKMTRIRKPTLDKPTPDRYVAAELSTVGLQSQTNGYFPHAIMGWV
TTKLVPSSIVIFLGARMNRLQRTGYLQRRRLREQRNG---TGLKSE
*
>P1;ENSORLG00000001421

M-----NRMN-AEEMIRRAEPLFFWVGAFTLAFFALWLLYRLVTGFRIWV
LGNGTLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFAMM-LISRSQE
KLDDVAKSLEEQFGVETKTIAVDFGKTDIYPKIEAGLVGLEIGVLVNNVG
VSYHYPEYYLNIPDLDNFLTNMINVNMTSVCQMTRLVLPG--MVSRAKGV
ILNISSASGMYPLPLLTVYSATK--AFMDFFSRGLQEEYRRQGIIIQSVL
PFFVATKMTRIRKPTLDKPTPERYVAAELTTVGLQNQTNGYFPHAVMGWV
TTKLVPTSIVIFLGASMNRVQRSGYLHRRKLREMKNG---ASLKSE
*
