>P1;ENSDARG00000074073

--------------MAWPCITRACCINRFWSELDKGDIAVPLVFTKYSDV
AEV-QHLHPQPKPVL-SQ-----------------------KPVATESHL
AHS-AHQEASSRATHGAADAAAA-ASQ-DGSGASVMREDFKAWSVRPERS
CKPRNQYQPSKTPFINETQYQKDYKPWPIPKKGDHPWIPKPTAAAAPCKA
ESK---FSKHEQ--AAAEMETGVEKCEIEEKQHEKESKERRK--------
------KVEKKEP-------VSEAS-------------------------
------------KME-----------------------------------
----------------------------------------------KDVA
V-EGKRRS---AAD------------------------------------
--------------------------------------------------
-------------------------------ALNRQIKQEV--TSG--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRTEFKAYRDIKPVKPIKAKSQYKLLVGEKTNLETSYSATFKGEQAK
PQTTDNKLMEHRRIRSLYSEPSKESS-KVERHNLSLTKPKKTPS----HS
KTVKKAKEKPVAGSQPAKKKTSVSNQEPKPEGGVTKKSKEMINRLAEAKD
--------------------------------------------------
------------------------------
*
>P1;ENSTNIG00000008576

DHKQQQTLGMVAMAMAWPCISRACCMARFWNQLDKADIAVPLVFT-YADA
SEM-QHVQPQPS----SQ-----------------------ARVAIETQP
SRA--ESRTR-TVA---RAPRRC-VSE-ERVCSSVMREDFKRWNVRPEPS
CKPKNEYHEPEAPFYSETQYQKDFKPWPIPKRYDHPWIQKAPRLDN--RG
PDR---PRQPKRAAAPTAADGDVEKSAIADKVQEKDLLQGHE--------
------RKK-GSRREAE-------A-------------------------
------------RR------------------------------------
-----------------------------------------------AVE
G-EGRGRR---STD------------------------------------
--------------------------------------------------
-------------------------------ALNRQIKEEI--TGG--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRAEYKAYADVKPTRMIRAKSQYLP-PEEKTRLETSYSATFRA-QAP
AQPADNKALDRRRVRSLYADPSKQVD-RYSL---PRSKAKQPGAAASGQG
TPLKKAKDKQGGAHRGSRKMAAEK----QPV-GNKEKSKEMNNKLAEAKE
--------------------------------------------------
------------------------------
*
>P1;ENSTNIG00000003291

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
QHL-PH---HPQPKQSAA-----------------------GAIAIETQP
HPQRAEQEA---------------GTE-DGLTASVMRQDFKAWRVRPEPS
CKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPKPSPGSAS-RG
PER---SAKLEH--AAGEAESGVEKSEIEEKIHEKETKEVTR--------
------REK-SAE-------RDAGE-------------------------
------------KTE-----------------------------------
----------------------------------------------PACA
E-ARKGRA---AAD------------------------------------
--------------------------------------------------
-------------------------------ALNRQLKEVM--STS--SS
YRYFCQLPSAGETDRWDWC-------------------------------
--------------------------------------------------
------------------------------------------------YI
PAASTATLHNTSSQVRPVTVPE-------------RTTEHIRAPCVHRAA
AATQLNQQPSETIIHTSP--------------------------------
-NFRRTEFKAYKDVKPTKPIKAPSQYKP-PGEETNLETSYSATFKGEQVK
AHPADNKAMERRRIRSLYSEPSKASP-KVDKP-ASHAKSRKTSSTATTAG
KMAKKTKEKQISSSQSAKKKPPLVTAEPRPEGVITKKSKEISNRLAEAKQ
--------------------------------------------------
------------------------------
*
>P1;ENSORLG00000012570

--------------MAWPCISRACCMARFWNQLDHADIAVPLVFTKYTDA
SEM-QHIQLQPQ-LPRPQ-----------------------ARVAIETQP
SRS--KPRTA---------------PG-KACPAVLVRKHLKGN----CPK
CRRK-DFFPVDCALSRKPAVQKGFAACRDEEDADPP--------------
--------------------SRGSKLLKKKRIPEKDGWAIYQNSLKRINL
SYTTTTHLK-SSRRASS-------S-------------------------
--------------------------------------------------
-----------------------------------------------QSR
G-DGRGRGVKPGVD------------------------------------
--------------------------------------------------
-------------------------------RIHSQPTTNC--VSS--ST
Y-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--KDETEFKAYRDVRPVRMIRAKSQYLP-PDERPSLETSYSATFKV-QTP
LQPADNKAQERRRIRSLYSEPYIDPSKQVDRYSPTCSKPKKSGATSAGQG
KPLKKAKDKQTTPLKGSKKATLENQPQDRPAVGDKEKSKEINNKLAEAKE
--------------------------------------------------
------------------------------
*
>P1;ENSAMXG00000008868

--------------MAWPCIARACCMARFWTQLDKADIAVPLVFVKYSEV
SEETQQLQRDRE-REKDRDRERNRERDREKDRHRDRTRDRLQEKSQERDP
ERN--RQEV------------TR-DGR-ENAPGSVMRQDFKAWKVRPEPS
CKPKCEYHGPEVPFDSQTQYRQDYKPWPIPRRGDHPWIPKPA--------
------------------LECGLEKSQTADKVQEKEMLMGEK--------
------KKR-QVKRVEKEKKVITGK-------------------------
------------EGS-----------------------------------
--------------------------------------------A-EAPV
N-VGKGRE---AVD------------------------------------
--------------------------------------------------
-------------------------------ALNRQIKQEV--GGG--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRTEFKAYTDVKPVKLIRAKSQYHP-PDEKTNLETSYSATFRGEQAK
LQPADNKALERRRIRTLYSEPYLDSS-KGERSSLPRSKPKKTTSSSTSQG
KTVKKSKEKQTASVRGSKKKSSENQPERRAAQGDKEKSKEMNNKLAEAKE
--------------------------------------------------
------------------------------
*
>P1;ENSDARG00000074521

--------------MAWPCISRACCMARFWSQLDKADIAVPLVFTKYSDV
SEM-QHLHLQQP-VQK---------------------------IAIETQP
LHH--DHEPV---T---RAP-HA-GHD-EHSFGSVMRQDFKHWKVRPEPS
CKPKNEYHGPEIPFNTETQYQKDYKPWPIPKKGDHPWIPKPSPSIS--AG
KH----------SSPEMMMDSGVEKSEIADKVPEKEILSSER--------
------KKR-QVKKVAVVSENNAGV-------------------------
------------KLD-----------------------------------
--------------------------------------------R-DASA
V-EGKGRA---AVD------------------------------------
--------------------------------------------------
-------------------------------ALNRQIKREV--SSG--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRTEFKAYTDVKPVKLIRAKSQYKP-PDDKTDLETSYSATYRAYQSS
QQPDDNKALERRRIRTLYHEPYRESS-KVEKTSLPRSKPKKSSSTSATPG
KPLKKSKEKQATSVRGSKKKSSENQPESRAVQADKEKSKEINNKLAEAKE
VMLKQYHYIQLCQPIRDIGWVQTLKQHLWRCALPDPRECESGVGRVSDYY
SAGTSGGEPLVERPEPRSRGVVRFAPDVKY
*
>P1;ENSGACG00000010429

--------------MAWPCLTRACCINRYWTELDKADVAVPLVFGKYSDA
ADA-QHLPHHPQPRHKRA-----------------------GAIAIETQP
HRA--EQGPG-KAP---PATAAA-AGK-DGSAASVMRQDFKAWSVRPEPS
CKPRNEYQRSAAPFNTETQYQKDYKPWPIPKKRDHPWIPPQRRERK---A
GSR-----GRER--RGEERDRGENAGERVNRGGEDEREEGKV--------
------RRE-GNG-------REDGQ-------------------------
------------SGA------------------------------RG---
--------------------------------------------CERRAE
ERQGGRRR---AEQADQAAIGEFIPPQPIAIKKPLLRPFQNEFADIFSRL
STQSSIRVSISTQYFKWFFNKITPKSSVIKHLENILSKINGARTGMTNRP
CVPVITAVRMCFVSRKQNTRSEGQDEATWQLSLNYRITYVLIKTLF--SP
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---CRTEFKAYKDVKLVKAIKAPDQYKP-PVKEASLETSYSATYKGEQMK
AQPTDNKLVERRRIRSLYSEPGKEAA-KVDKP-VSRTKQKKTPT--TTTG
KMVKKSKEKQIASSQSAKKKPSSCAPKPKPDGAVTKKSKEISNRLAESKQ
--------------------------------------------------
------------------------------
*
>P1;ENSONIG00000011169

--------------MAWPCITRACCINRFWSELDKADIAVPLVFARYSDV
ADV-PHVPHHPQPKLKKA-----------------------GAIAIETQP
HPG--EQEAG-KAP---PATGAA-AGK-DGSTASVMRQDFKAWRVRPEAS
CKPRNEYQPSPAPFNNETQYQKDYKPWPIPKKHDHPWIPKSSPTAG---G
PERSAGSGKLEQ--VAAEAESGVEKSEIEEKTQEKESQEVVKR-------
---SVKREK-SSE-------RKTGE-------------------------
------------KTE------------------------------GQ---
-------------------------------------V-----AA-DVSA
E-QRKGRA---AAD------------------------------------
--------------------------------------------------
-------------------------------ALNRQIKEVM--STS--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRTEFKAYKDVKPVKPIKAPSQYKP-PGEETSLETSYSATFKGEQVK
AHPMDNKLLERRRIRSLYSEPSKEPA-KVDKP-VSRTKPKKSSSTPTTTG
RMQKKAKEKQISSSQSAKKKPSLGASEPKPGGAVTKKSKEISNRLAEAGK
--------------------------------------------------
------------------------------
*
>P1;ENSTRUG00000007180

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHFPHHPQPKQNRA-----------------------GAIAIETQP
HPHRGEPEAG-KAP---PATGAA-AGD-DG--LSVMRHDFKAWRVRPEPS
CKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPKASPGSTS-KG
PER---SAKLEQ--AASEAESGVEKSEIEEKIHEKESKEVTK--------
------REK-SAE-------REVGE-------------------------
------------KTE-----------------------------------
----------------------------------------------PACA
E-TRKGRA---AAD------------------------------------
--------------------------------------------------
-------------------------------ALNRQLKEVM--STS--SS
YRF-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------T--------------------------------
-KKYRTEFKAYKDVKPTKPIKAPSQYKP-PGEETNLETSYSATYKGEQVK
AHPADNKVMERRRIRSLYSEPSKAGA-KVDKP-ASHTKPKKTPT---TAG
KMGKKSKEKQISGSQSAKKKPSLVSAEPKPEGVITKKSKEISNRLAEAKH
--------------------------------------------------
------------------------------
*
>P1;ENSXMAG00000001705

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHLPHHPQPRQKQA-----------------------AAIAIETQP
HPE--EREAA-KAP---PAAGGAAAAKGGASAASVMRQDFKAWRVRPEPS
CKPRNEYQPPPAPFSNETQYQKDYKPWPIPRKHDHPWIPKPSPTAG---S
-KL---EHAAAA--AAGESESGVEKSEIEEKIQEKESKEAAR--------
------REK-SAE-------RKAAE-------------------------
------------KTE------------------------------GP---
--------------------------------------------A-EVSA
E-QRRGRA---AAD------------------------------------
--------------------------------------------------
-------------------------------ALNRQIKEVM--STS--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRTEFKAYKDVKPVKPIKAPSQYKP-PGEETSLETSYSATYKGEQVK
AQPTDNKLLERRRIRSLYSEPGKEPA-KVDKP-TSRTKPKKAPT--TTTG
KMVKKSKEKQIAGSQLAKKKPSAKTPEAMPEGTVTKKSKEISNRLAEAKH
--------------------------------------------------
------------------------------
*
>P1;ENSTRUG00000017372

R-PLERSLVFGALAMAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQPS----AQ-----------------------ARVAIETQP
PRA--QSRTR-TAA---HAPRRC-VSE-ERVCNSVMREDFKRWNVRPEPS
CKPKNEYHEPETPFYSETQYQKDFKPWPIPKRCDHPWIQKAPRVDN--RV
PDR---PR----QQA--AADGEAEKSAVADRVQEKDLLQGHG--------
------RSK-ASRKEAE-------L-------------------------
------------KKV-----------------------------------
--------------------------------------------V-LRVE
G-EGRGRR---STD------------------------------------
--------------------------------------------------
-------------------------------AVNRQIKE-I--AGS--SS
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---YRAEYKAYADVKPTRMIRAKSQYLP-PDEKTRLETSYSATFKA-QAP
APPADNKALDRRRVRSLYTDPSKQPP-QMDRYSLPRSKPRQSGAAASGQG
TPVKRAKDKQGVAQRGSRKMAVEK----QPV-GSKEKSKEINNKLAEAKE
--------------------------------------------------
------------------------------
*
>P1;ENSORLG00000005434

--------------MAWPCITRACCINRFWTELDKGDIAVPLVFTKYSDA
AEV-HHLPHHPQPKQRVV-----------------------GTIAIETQP
HPE--EQEAA-RAP---PATGAA-AGR-TGTATSVMRQDFKAWGVRPEPS
CKPRNEYQPPPSPFNNETQYQKDYKPWPIPKKHDHPWIPKPSSTAA----
PER---SSKKEH--AAAEADSGGEESGWQTGAAG--VCKGERR------A
AEEQGSRRR-SQQ-------TDQGGHVHFQLLQVNIITPLGPAGRTDHQP
SPHHLQPIEETHSMEPWIKNSMDTSEDHKSLKKKCSAHCLVGLDDPTPNV
KVPRIAQGLNHFLASLYLRRDTIRLGYLSVRDPKPKRIQSRRRYY-D-AK
Q-GGKGSL---SYF------------------------------------
--------------------------------------------------
-------------------------------AETMQQEEAA--ASGVQFT
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---CRTEFKAYKDVKPVKAIKATSQYKP-PMEETSLETSYSATYKGEQVK
PKESDNKLLERRRIRSLYSEPGKEAA-KVDKP-ESRLKPKKAP---TTTG
KMLKKAKERQIASSQSTKKKPSAGPSE--PEGTVTKKSKEISNRLAEAKQ
--------------------------------------------------
------------------------------
*
>P1;ENSGACG00000020200

--------------MAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQPP-LHPPR-----------------------GRVAIETQP
TRA--E----------------C-VSE-ERVCGSVMREDFKHWNVRPETS
CKPKYEYHEPETPFNCESQYQKDFKPWPIPKRYDHPWIPKPPASDE--RA
PDR---SRH---RKQPAEADSGVEKSAIADKVQEKDLVQGPH--------
------RKK-KSSKQEG-------P-------------------------
------------KKV-----------------------------------
--------------------------------------------S-LKVE
G-EGKGRA---AAD------------------------------------
--------------------------------------------------
-------------------------------AVNRQIKQEI--AGD--SL
YNNQSYVNLGGNV---SWCAQESPCFRDKRFQPAASQSPAPSGLYLAANQ
LHYEMEAGKAGSVRSDSGYVKYCNPIQPAVLTKLSGHWKSSLLRLQKVGV
TQKKGPSHTAMYRCSSQLLAVSIEPLPEKLQRGRELETRPTGPTGKREYR
PGARPSPAHTPRNTARTGSLPPAQIDSFKDHERGGLASETIDAPSYMHAS
ACSCIHTQPCKHLTSTTHNSGVSEGWGTYINRKLGSLLGLALHKEVELTM
SYTNRTEYKAYRDVKPAKMIRARSQYLP-PDEKTSLETSYSATYKG-QAP
LRPAGNKALDRRRIRSLYSEPYIDPIKQVDRYSALRTKPKKPGASAAGQV
KQAKKAKDKQSAGLRGSKKTASENQLENRPAVGDKEKSKEMNNKLAEAKE
--------------------------------------------------
------------------------------
*
