>P1;ENSTNIG00000010005

----------M---ADRDSGSEQGGAA--MGPG-----------------
---FASMHLATGGAGLASGLQHETQELASKRVDIQNKRFYLDVKQNPKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTHPGLVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPYKVWSKFGNTFSKYAEEMKKIQEKQRE
KRACEE-------MQ-ADDGDED
*
>P1;ENSAMXG00000024949

----------M---ADRDSGSEHGGFA--TGGGGIGGGGGGGPGGGGPGG
GGGLGL--PHPGAVGAASRLQHDTEELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSHPDTAQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRVRQTVNRGPGLGTAQGQT
IALPAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSLAVDNKRFFFDVGA
NKYGVFMRVSEVKPAYRNSITVPCKVWSKFGATFCKYADEMKRIQERSRE
RRARELLPE---GLH-GDDGDED
*
>P1;ENSAMXG00000025364

----------M---ADRDSGSEQGGAP--TGPG-----------------
---VG-LHAVAGGAGSASGLQHDTQELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDAAQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGTSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPYKVWAKFGSTFCKYAEEMKKIQDKQRE
RRACEQQQQQPGEMH-ADDGDED
*
>P1;ENSGACG00000018680

----------GSRGCSRQRETVEGKAGRQHHGGQ----------------
---R----QWQCAMGAMSRLQHDTEELASKRVDIQNKRFYLDVKQNVKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTNPDIVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQT
IALPAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPCKVWSKFGNTFCKYAEEMRKIQERNRE
KRAS-------------------
*
>P1;ENSTNIG00000004639

----------M---ADRDSGSDHGGPT--GGPG-----------------
---S----LPAGAMSAMSRLQHDTEELASKRVDIQNKRFYIDVKQNVKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDVVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQT
IALPAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSFTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPCKVWSRFGNTFCKYAEEMKKIHERSRE
KRASELLPE---GS----HGEDD
*
>P1;ENSDARG00000067591

----------M---ADRDSGSEQGGAA--TGPG-----------------
---VGSMHPVTGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDMPQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGTSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPYKVWSKFGSTFCKYADEMKKIQEKQRE
KRACELQQQQQEEMH-GDDGDED
*
>P1;ENSTRUG00000006789

----------M---ADRDSGSDHGGPT--GGPG-----------------
---S----LPAGAMGAMSRLQHDTEELASKRVDIQNKRFYIDVKQNVKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTNPDIVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQT
IALPAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSFTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPCKVWSRFGNTFCKYAEEMKKIHERSRE
KRASELLPE---GS----HGEED
*
>P1;ENSONIG00000021362

----------M---ADRDSGSEQGGAA--TGPG-----------------
---FGSVHLATGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPGMVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGFTQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEEMKKIQEKQRE
KRACELQQQ--EEMQ-QDDGDED
*
>P1;ENSXMAG00000019887

----------M---ADRDSGSEQGGAA--TGPG-----------------
---FGSMHLAAGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPGMVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEDMKKIQEKQRE
KRACELQQQ--EEMQ-ADDGDED
*
>P1;ENSGACG00000020655

QRGRRQAGSIM---ADRDSGSEQGGAP--TGPG-----------------
---FGSMHPATGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPALVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEEMKKIQEKQRE
KRACELQQQ--EELQ-ADD---D
*
>P1;ENSORLG00000006100

----------M---------------------------------------
-------HLPTGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPGMIQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQT
IALPAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGS
NKYGVFMRVSENYHK---------KEEGKKKSHLCQLMTDKQPAQTVVKV
RR---------------------
*
>P1;ENSDARG00000099614

----------M---ADRDSGSEHGGFA--TGPG-----------------
---AGP--M---HPGAASRLQHDTEELASKRVDIQNKRFYLDVKQNAKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDLVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGTSQGQT
IALPAQGLIEFRDALAKLIDDFGVDEDPAELPEGTSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPCKVWSKFGATFCKYADEMKKIQERSRE
RRAREMLPE---GLH-GDDGDED
*
>P1;ENSONIG00000020655

----------M---ADRDSGSDHGGPT--AGPG-----------------
---S----LPPGAMGAMSRLQHDTEELASKRVDIQNKRFYLDVKQNVKGR
FLKIAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTNPDMVQD
EPRRALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQT
IALPAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSLTVDNKRFFFDVGS
NKYGVFMRVSEVKPTYRNSITVPCKVWSKFGNTFCKYAEEMRKIQERSRE
KRASELLPE---GPHGGDDGDDD
*
