>P1;ENSTRUG00000012428

YKGGLNNRSDCKRSKRRWWQQEMGLFYCSSVFSVSIEQIAVLHKRFRQLS
HNDEKLRREHFMAIPDLACNPIRSQIIQAFFDRRNFHQKDDGTVEEISFE
QFLVVMSHFRPPSPHMTEEQRESVRRDKLRFLFNMHDTDNDGMITLEEYR
HVVEELLSRSGALGKETAKSIADAAMLEVASISMGHMEPDEFYEGITFEH
FLKLLGSFEIESKMSIRFLNMDTFTL-C---K-
*
>P1;ENSORLG00000008146

-MGSLQSSPSHQDYV-----------DLAEKTGFSFEQISILHKRFKQLS
HNEDKLRREHFGQITDLHANPIREQIVEAFFDRRNFYQEIEEPVSEISFE
NFLVVMSNFRPPSDNMSQEKLVKVRKEKLRFLFNMHDTDKDGTITLEEYR
HVVEELLSYYEALETETARGIADAAMLEVASITRGHMEPDEFYEGITFEH
FLKLLEGFDIESRMNIRFMNMDTTTL-CK--L-
*
>P1;ENSGACG00000014094

-MGASQTRPE-HRHQ-----------DLADRTGFSLEQIKNLHKRFQQLS
GDEDTISKENLESIPTLANNPIRKQIIGAFFDKRNQHRGEAGSCDQIGFE
QFLMVMSHFRPPTLKMTAEEKEAMRREKLRFLFNMHDTDNDGTITLVEYR
KVVEELLSKSGSIGQEAAEAIADAAMLEVASTNVPTMGPDDFYEGITFEH
FEQILKGLEMESRMHIRFLDVDTTTMRCGKSTS
*
>P1;ENSORLG00000000922

-MGAATTRIG-QQDP-----------ELVDRTGFSPEQINNLHKRFLQLS
GNKDTISRENLNDIPALTYNPIKSQIIEAFFDKRNQHDSEVGSLEEITFE
QFLMVMSHFRPPTLEMTAEEKQAMRKEKLRFLFNMHDTDGDGKITLEEYR
KVVEELLS-SGSIEQESAKEITDAAMLEVASTNVPHMGPEDFYEGITFEH
FEQILKGLEMESRMHIRFLDTA--TVHCGKS--
*
>P1;ENSTNIG00000015605

-MGASQTRSE-HKYQ-----------SLVEKTGFSLEQIKNLHKRFQQLS
RNEETISREDLNSIPALANNPIRKQIVDAFFDKRNQHQNEVGSLQEISFE
QFLMVMSHFRPPTLKTTEEEKEALRKEKLRFLFNMHDTDHDGTITLEEYR
KVVEELLSKSGAIGQEAAQAIADAAMLEVASTNVPHMDPDDFYEGITFEH
FEQILKGLEMESRMHIRFLDVDTTTMRCGKSSS
*
>P1;ENSGACG00000016945

--------------------------------------------------
--------------------------------------------------
-----MSHFRPPSLHVTEEQREAVRRDKLRFLFNMHDTDNDGTITLEEYR
HVVEELLSLSEALEKDTAKSIADAAMLEVASISMGHMEPDEFYEGITFEH
FLKLLNGFEIESRMNIRFLNMDTTTL-C---K-
*
>P1;ENSXMAG00000002448

-MGATQTHSE-YQYE-----------NMVGKTGFSTEQIKNLHMRFQQLC
GNEKTLRKEHLENIPTLADNPIKTEIIKAFFDKRNQHNNELGSYEEIGFE
EFLMVMSHFRPPSIKTSAEEKAAMRKRKVRFLFNMHDTDGDGKITLEEYR
KIVEGLLSESESIGQEVARAIADAAMLEVASTNVPNMGPDDFYEGITLEH
FEQILKDLEMESRMYVRFLDMNTANLHCGK---
*
>P1;ENSONIG00000013959

-MGALQSLPGRPEYS-----------DLAEKTGFSFEQIGVLHKRFKQLS
HNEETLRRDHFNEIHDLAFNPIRAQIIEAFFDRRNFHQDGEGKVQEIGFE
EFVVVMSHFRPPSDHMTEEQREKTRREKLRFLFNMHDTDNDGTITLEEYR
HVVEELLSRSGTLEKETAKCIADAAMLEVASISVGHMEPDEFYEGITFEH
FLKLLDGFEIESRMTIRFLNMDTTTL-C---K-
*
>P1;ENSTRUG00000016423

-MGASQTRSD-HKYQ-----------NLVEKTGFSLEQIKNLHKRFQQLS
GNEETISKENLNSIPALANNPIRKQIVDAFFDKRNQHQNEVGSFHEISFE
QFLMVMSHFRPPTLKTTEEEKEALRKEKLRFLFNMHDTDNDGTITLEEYR
KVVEELLSKSGAIGQEAAKTIADAAMLEVASTNVPHMAPDDFYEGITFEH
FEQILKGLEMESRMHIRFLDVDTTTMRCG---K
*
>P1;ENSAMXG00000007002

-MGAFHSVPDDHQYH-----------ILSEKTGFSLEQIGILHNRFKQLS
HNSDVLRRDDLNTIPDLASNPIKSQIVEAFFDGRNLRKDSEGPVQEIGFE
EFLIVMSYFRPPSVHMTEEQREGIRRDKLRFLFNMHDTDNDGTITLEEYR
HVVEELLSRSGSLGRETAKGIADAAMLEVANMSVGRMGPDEVYAGITFEH
FLKILKGIEIETRMHIRFLNMDTTVL-C---K-
*
>P1;ENSDARG00000028346

-MGAAQSGGQAQKYQ-----------DLADKTGFSTEQIRKLHSRFQYLT
QDEDTLRREHLENLTNLALNPIKRQIIEAFFDKRNLGQNEKGCLQEIGFE
EFVTVLSVFRPTKPRTAEDKKKTIKEEKLRFLFNMHDTDNDGVITLDEYR
RVVEELLSSYETIEAETAKAISDAAMLEVASVTVGRMSPDEFYEGITFEQ
FMQILKDIEIETKMNVHFWNLDTRTMHCGK---
*
>P1;ENSTNIG00000009068

-MGALQSSPAPRDQA-----------DLAEKTGFSLEQIAVLHKRFKQLS
HNEETLRREHFKAIPDLACNPIRSQIIQAFFDRRNFHQNDDGTVEEISFE
EFLVVMSHFRPPSQHMSEEQRESVRKEKLRFLFNMHDTDNDGMITLEEYR
HVVEELLSRSGALGKETAKSIADAAMLEVASISMGHMEPDEFYEGITFEH
FLKLLGSFEIESKMSIRFLNMDASTL-C---A-
*
>P1;ENSXMAG00000001381

-MGALKSTPDPIEYA-----------DLSEKTGYSLKQIRVLHKRFRELS
DGDDVLRREHFRCISSLKYNPIRVEIIEAFFNRRNFSPSHQGSADEIGFE
EFLVVMSHFRPPSPKITDEQRKNIRREKLQFIFNMHDSDGDGLVTLEDYR
HVVEELLSRSGALGKETAKAIADAAMFEVAR-TVGHKDPNEFYEGITFEH
FLKLLSNFDIESRMNIRFLKSDVNPF-CQLCC-
*
>P1;ENSDARG00000030839

-MGSFQSLPDDHQYR-----------TLSQKTGFSLEQIGILHNRFKQLS
QNEDTLRRDDLKTIQDLESNPIRSQIIEAFFDKRNFQKDATGSVQEIGFE
EFLTVMSYFRAPAHQITEEQREEIRRAKLRFLFNMHDTDNDGTITLEEYR
HVVEELLSRSGALGRETAKGIADAAMLEVASITVGPMAPDEFYEGITFEQ
FLKILKGVEIETRMHIRFLNMDTTVL-C---K-
*
