>P1;ENSTRUG00000011436

---------MAVT--VVNKCRG-----SLAFLTRTISAPEFFTQCCYHKK
VVDHYENPRNVGTLDKHSKNVGTGLVGAPACGDVMKLQIQVDDQGKIVDA
RFKTFGCGSAIASSSLATEWIKGKSVDEASTIRNTDIAKELCLPPVKLHC
SMLAEDAIKAAVADYQLKQEDVQQ-EAV---QSSN
*
>P1;ENSDARG00000035596

---------MALA--AAARRCA-----SSALFSKSLSLPELRPACSYHKK
VVDHYENPRNVGSLDKNAKNVGTGLVGAPACGDVMKLQIQVDENGKIIDA
RFKTFGCGSAIASSSLATEWVKGKSIDEALKIKNTEIAKELCLPPVKLHC
SMLAEDAIKAALADYRLKQKDEKE-TLA---EARN
*
>P1;ENSXMAG00000001189

-------------------------------------------------K
VVDHYENPRNVGSLDKNSKKVGTGLVGAPACGDVMKLQIEVDDQGKIVDA
RFKTFGCGSAIASSSLATEWVKGKTLDEALEIKNTDIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQHDDQQ-EAV---RASN
*
>P1;ENSTRUG00000014258

---------MAHV--YLRHPT------SLLLFSRRLFSPQPKVLCSYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIEVDKNGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSIDEALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQDKNRT-EDKE-----S
*
>P1;ENSDARG00000026582

---------MAAS--LAKKCAA-----PQ--ILKTLSAPTLRTQIGYHKK
VVDHYENPRNVGSLDKNAKNVGTGLVGAPACGDVMKLQVEVDEAGKIVNA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTEIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQEGEPVEETA---VARN
*
>P1;ENSONIG00000013921

---------MAGT--VANKCLS-----PLAFLTRRLSAPEFITQCCYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIEVDDQGKIVNA
RFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQQDDQQ-EAV---RASN
*
>P1;ENSGACG00000008801

---------MAMA--SLGSAAS-----SLVLFSRRVLRPELTALCSYHTK
VVDHYENPRNVGTLDKNAKNVGTGLVGAPACGDVMKLQIQVDENGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIRNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRVKQDMEKN-TSS---TNRI
*
>P1;ENSORLG00000006911

---------MAMI--SVRNCAS-----LPSLFCSRLFRPELKSLCSYHKK
VVDHYENPRNVGSLDKNSKSVGTGLVGAPACGDVMKLQIQVDENGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSLDEAMKIKNSDIAKELCLPPVKLHC
SMLAEDAIKAALSDYKIKQDKKEE-HAK---AS-S
*
>P1;ENSXMAG00000018187

---------MAAV--SLRNSGS-----LLSLFSKSFFRPELNALCSYHKK
VVDHYENPRNVGSLDKNKKSVGTGLVGAPACGDVMKLQIQVDENGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQEEKK------------
*
>P1;ENSTNIG00000009075

---------MAGA--VANKCRG-----SLAFLTRTISAPEFFTQCCYHKK
VVDHYENPRNVGTLDKQSKNVGTGLVGAPACGDVMKLQIQVDEQGKIVDA
RFKTFGCGSAIASSSLATEWIKGKSVDEASMIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALADYQLKQQDVQQ-EAV---LSSN
*
>P1;ENSONIG00000013416

FPFAVGAGNMANV--CLRSSSS-----LLLFFSRRIFKPELSAVCLYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIQVDENGKIIDA
KFKTFGCGSAIASSSLATEWVKGKSVDDALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQQDKKE-ERV---K--A
*
>P1;ENSGACG00000016973

---------ILLGGVRLFRSATELKVKIPSFITRRLSAPEFITQCCYHKK
VVDHYENPRNVGTLDKSSKNVGTGLVGAPACGDVMKLQIEVDDMGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSVAEALEIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALADYRLKQQDDQQ-EAV---R--A
*
>P1;ENSTNIG00000015868

---------MAGV--YLQKSTS-----SLLLFS-RLFSPQRKVLCSYHKK
VVDHYENPRNVGSLDKNSKNVGTGLVGAPACGDVMKLQIEVDGNGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELCLPPVKLHC
SMLAEDAIKAALSDYRLKQDKNRT-EAEKSLPAKN
*
>P1;ENSAMXG00000019258

---------MALS--SMGKCFS-----SFGLFGRTLTGTEAKAVCCYHKK
VVDHYENPRNVGSLDKNARNVGTGLVGAPACGDVMKLQIQVDENGKIVDA
RFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTEIAKELCLPPVKLHC
SMLAEDAIKAALADYRLKQKDEEK--VA---EAVN
*
>P1;ENSORLG00000008313

---------MAGT--VMKKCFS-----PLSVLTRRLSVPEYISQCCYHEK
VVDHYENPRNVGSLDKKSKNVGTGLVGAPACGDVMKLQIEVDSQGKIVDA
KFKTFGCGSAIASSSLATEWVKGKSVDEALKIKNTDIAKELSLPPVKLHC
SMLAEDAIKAALADYRLKQSDGQQ-EAA---KVSI
*
