>P1;ENSGACG00000011447

MGKD----PRKPKGRMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCSE
RWK--TMSQKEKGKFEDMAKLDKVRYEKDMKNYDPPKGQ-KKKRYKDPNA
PKRPPSAFFLFCGDFRPKVKSEHPGLTIGDTAKKLGEMWNGSSAENKQPY
EKKAAKLKEKYEKDVVAYRTKGTVDSPAAAT----------AD-DD-DDE
DED-DD-DD--------DD---------DDDDDE-----
*
>P1;ENSXMAG00000006844

MVKD----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCSE
RWK--TMSPKEKGKFEDMAKQDKLRYEREMKNYVPPKGQ-KKKRFKDPNA
PKRPPSAFFLFCADFRPKVKGESPGLSIGDTAKKLGEMWNSLSGEEKQPY
EKKAAKLKEKYDKDIVAYRTKGSVDSAPAAA----------ANDDEDDDE
EEG-DEEEE--------EE---------EEDDD-----E
*
>P1;ENSAMXG00000014832

MVKD----PRKPRGKMSSYAYFVQTCREEHKKKHPEASVNFSEFSKKCSE
RWK--TMSPKEKSKFEDMAKQDKVRYEREMKNYIPPKGE-KKKRFKDPNA
PKRPPSAFFIFCGDYRPKIKGENPGLSIGDIAKKLGEMWNSSSPEVKQPY
EKKAAKLKEKYDKDIAVYRTKGVAGLSKKAA----------GDEDD-DEE
DED-EDDDE--------ED---------DEEDDE-----
*
>P1;ENSXMAG00000008400

MGKD----PTKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCSE
RWK--TMSAKEKGKFEDLAKQDKARYEREMLSYVPARGG-KKKKFKDPNA
PKRPPSAFFIFCSEFRPKVKGENPGLSIGDVAKRLGEMWNSTASEDKQPY
EKKADKLKEKYKKDIAAYRKMGSSAPA---KAPAK-AE----KDDD-DDD
EDD-DEEEE--------DD---------DDEDDD-----
*
>P1;ENSGACG00000020545

MVRE----PGKPRGKMSSYAYFVQTCREEHKKKHPEASVNFSEFSKKCSE
RWK--TMSLKEKGKFEDLARQDKARYEKEMMSYIPPRGT-KKKKFKDPNA
PKRPPSAFFIFCAEYRSKVKGETPGLTIGDVAKKLGEMWNGTASEDKQPF
EKKASKLKEKYEKDVAAYRAKTKAQPKVEKKVRIMCFEKKKKKTPS-EYG
CVQ-STEDE--------NQKGTHSHTVHCGGNDA-----
*
>P1;ENSORLG00000003400

MGKD----PTKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCSE
RWK--TMSAKEKGKFEDMARQDKVRYDREMMSYVPAKGA-KTKKFKDPNA
PKRPPSAFFIFCSEFRPKVKGESPGLTIGDVAKRLGEMWNSTSAEDKQPY
EKKAAKLKEKYGKDIAAYRAKGKTGGGAPAKAPAK-VEKK-MDDDD-DDD
DDD-EEEEE--------DD---------DDEDDE-----
*
>P1;ENSONIG00000005505

MVKD----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCSE
RWK--TMSPKEKGKFEDMAKQDKLRYEREMKNYVPPKGQ-KKKRFKDPNA
PKRPPSAFFLFCADFRPKIKSEYPGLSIGDTAKKLGEMWNSSSAEEKQPY
EKKAAKLKEKYDKDIVAYRTKGKVDSGPAAA----------ADDDDNEEE
EEEGEEEEE--------ED---------EDDDD-----E
*
>P1;ENSAMXG00000003142

MGKD----PTKPRGKMSSYAYFVQTCREEHKKKHPDTSVNFSEFSKKCSE
RWK--TMSAKEKGKFEEMARLDKARYEREMKNYVPPRGE-KKKRFKDPNA
PKRPPSAFFIFCAEYRPKVKEETPGLSIGDVAKKLGEMWNKTSAEEKQPY
EKKAAKLKEKYEKDIAAYRK-GKVVGGA-AKAPSK-PDKA-NDDDD-DDD
DDD-DDDDD--------DD---------EDDDDE-----
*
>P1;ENSTRUG00000004822

MGKD----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCSE
RWK--TMSPKEKGKFEDMAKQDKVRYEREMKNYVPPKGH-KKKRFKDPNA
PKRPPSAFFLFCAELRPKVKSENPGLTIGDTAKKLGEMWNSKTAEEKQPY
EKKAAKLKEKYDKDIVAYRTKGKVDSESAAT----------AD-DD-EEE
DDE-EEEED--------DD---------DEDDDENDPGP
*
>P1;ENSORLG00000003951

MVKD----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCSE
RWK--TMSPKEKGKFEDMAKQDKVRYEREMKNYVPPKGQ-KKKRFKDPNA
PKRPPSAFFLFCADFRPKIKSESPGLSIGDTAKKLGEMWNSSSAEEKQPY
EKKAAKLKEKYDKDIVAYRTKGKVDSESASA----------AD-------
---------------------------------------
*
>P1;ENSDARG00000030479

MGKD----PRKPRGKMSSYAYFVQTCREEHKKKHPEASVNFSEFSKKCSE
RWK--TMSAKEKGKFEDMAKQDKVRYEREMKNYIPPKGE-KKKRFKDPNA
PKRPPSAFFIFCGDYRPKIKGENPGLSIGDIAKKLGEMWNSSSAEVKQPY
EKKAAKLKEKYDKDIALYRTKGIAGFSKKEG----------GEDDE-EDE
DD--DEEED--------DE---------EEEDDE-----
*
>P1;ENSDARG00000099175

MGKD----PTKPRGKMSSYAYFVQTCREEHKKKHPEATVNFSEFSKKCSE
RWK--TMSAKEKGKFEDMAKLDKARYEREMKNYIPPKGE-KKKRFKDPNA
PKRPPSAFFIFCSEFRPKVKEETPGLSIGDVAKRLGEMWNKISSEEKQPY
EKKAAKLKEKYEKDIAAYRSKGKVGGGA-AKAPSK-PDKA-NDEDE-DDD
EEE-DEDDD--------DE---------EEEDDE-----
*
>P1;ENSONIG00000012706

MGKD----PTKPRGKMSSYAYFVQTCREEHKKKHPEASVNFAEFSKKCSE
RWK--TMSAKEKGKFEDMARQDKARYEREMMNYVPARGGKKKKKYKDPNA
PKRPPSAFFIFCSEFRPKVKGESPGLSIGDVAKRLGEMWNSTAAEDKQPY
EKKAAKLKEKYEKDIAAYRAKGKPGSGAPAKAPAK-AEKK--DDDD-DDD
DED-EEEEE--------DD---------DDEDDD-----
*
>P1;ENSTNIG00000016258

MGKD----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCSE
RWKHKTMSPKEKGKFEDMAKQDKVRYEREMKNYVPPKGH-KKKRFKDPNA
PKRPPSAFFLFCAEFRPKVKSENPGLTIGDTAKKLGEMWNSKTAEDKQPY
EKKAAKLKEKYDKDIVAYRTKGKVDSESAAT----------AD-DN-GEE
EEE-KESRHQRMMLRWQTW---------KSGDD-----E
*
>P1;ENSTNIG00000009909

MGRDSGREAGKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSRKCSE
RWK--TMSVKEKGKFEDMAKQDKVRYDQEME-YVPAKGGKKKKKFKDPNA
PKRPPSAFFIFCSEFRPKVKGEHPGLSIGEVAKKLGELWNNTSSEDKQPY
EKKASKLKEKYEKDVAAYRQKTKGGTGSAGKAPAK-AEKKAAAADD-DDD
DED-EEEED--------DD---------DDDDDE-----
*
