>P1;ENSDARG00000100835

MSGL-----IQAFP---AHFSMDRDDCRRNKTLGKNLMCRLKSMF--AGS
S-V---------------PERLSLEDTQQWSQSLERLLGSKYGLATFRTF
LKSEFSDENIEFWLTCEDYKTITSSHKMSSKARKIFEQFVEAESPKEINI
DYQTREEIKRKMKSPTAQCFDEAQKIVYGLMERDSYPRFLRSEMYKSLLE
TIAADDE-------------------------------A-G
*
>P1;ENSTRUG00000009818

M---------------------DPDKRK-----GKDRSRPLRYCLRSSQV
P-K---------------TKGLSFEEMTQWSLSLERLLSSKYGIQIFQAF
LKSEFSDENIEFWMVCEDYKKIRSSFRMSSRAKKIFKCYIQAEATREINI
DHKTRDLIRRNVAAPTRECFNDAQRIVYNLMEKDSYPRFLRSDIYRSLLD
STSKDAEKEKRL-----N---RLQKSFGDFLPVVPGSEC-G
*
>P1;ENSGACG00000005823

LMHF-----LSV-------------------HSGKNFMCRLQCMF--SNS
S-SSERIASTLPSFPSMASCRLSLEDTQQWSQSLERLLESKYGLATFRNF
LKSEYSDENIEFWLTCEDYKKIKSSFRMSSRAKKIYEQFIKAESPKEINI
DYQTREQIKRNVKTPTVHSFDDAQKIVYGLMERDSYPRFLRSDIYRTLLE
NLAADA----------------------------------T
*
>P1;ENSAMXG00000017670

APSSIMTGLISE-PL-IKHFSMDRDDRKRSKNLGKNFMCRLQCMF--SRS
S-AP--------------ESRLSLEDTQQWAQSLERLLESKYGLATFRTF
LKSEFSDENIEFWLTCEDYKKIRSSFRMTSRAKKIYEQFVKAESPKEINI
DYHTREQIKRNVKSPTAQCFDEAQKIVYGLMERDSYPRFLRSEMYRTLLD
SLAVDAA-------------------------------H-G
*
>P1;ENSXMAG00000002712

MPSI-----KAKPPS-THHFIMDRDDRNRNNTLGKNFMCRLQCMF--SQT
PQCS--------------ESGLSLEDTQQWSQSLERLLESKYGLATFRNF
LKSEYSDENIEFWLTCEDYKKIKSSFKLSSRAKKIYEQFIKAESPKEINI
DYHTREQIKRNVKTPTMHCFDEAQKIVYGLMERDSYPRFLRSDIYRTLLE
SLATDAT-------------------------------T-G
*
>P1;ENSGACG00000016116

MLSL-----VASPPRELQPLNMDTDNKKR----AGNLKLRLQCRS--SQA
A-T---------------TEGICYEEISQWSHSLEGLLSSKYGMKIFQAF
LKSEFSDENIDFWLVCEDYKKIKSSFRMSSRAKKIFKRYIQAEAPREINI
DHKTREMIRRNMKTPTAVCFDDARRIVYGLMERDSYPRFLRSDIYQALLD
STSESIKIRKGS-----------------------------
*
>P1;ENSDARG00000017653

MPTI-----LST-----EIENMNKEDKATNPRRLE--KWRFRC-------
P-L---------------TEKINPGETSQWSQSLENLLRSKYGMATFHTF
LKSEFSDENIEFWLVCEDFKKTRSLSRLSSRAKKIFERYIKAEAPKEINI
DHVTRELIKQNVHAPTKVCFDEAQRIVFGLMERDSYPRFLRSDMYRSLLE
SVSNGIK---------------------------------V
*
>P1;ENSTNIG00000006931

--------------------------------------------------
--------------------RLSFEEMTQWSLSLERLLSSKNGIKVFQAF
LKSEFSDENIEFWLVCEDYKKIGSSFRMSSRARKIFKRYIQADAAREINI
DHKTRDLIRRNVAAPTRVCFDDAQRIVYSLMEKDSYPRFLRSDIYHRLLD
STSKSGM----------------------------------
*
>P1;ENSORLG00000012336

MCKG-----LASLH--TCCLERTKEMKAR----LGNILQKPNWTL--SCF
K-IG--------------KNKPSLEECLCWKESFEKLLSSKYGLCAFTAF
LVSEFSEENIAFYFACEDYRQTKCPTKLRAKAQKIFDEFFGSDAPREINI
DHETRDITKANLQTPTPSCFDLAQHRIYMLMAKDCYPRFLRSPAYRDLVC
QAKPTTKSSKHSQPDKKSRKQACRRAS-------VDRSKPK
*
>P1;ENSONIG00000010956

MPSL-----IVEPPN-TQRFIMDRDDRNRNKNIGKNFMCRLQCMF--SHS
S-SS--------------ESRLSLEDTQQWSQSLEKLLESKYGLATFRNF
LKSEYSDENIEFWLTCEDYKKIKSSFRMSSRAKKIYEQFIKAESPKEINI
DYHTREQIKRNVKTPTMHCFDDAQKIVYGLMERDSYPRFLRSDIYRTLLE
SLAADAT-------------------------------K-G
*
>P1;ENSTNIG00000012338

--------------------------------------------------
A---------------FSPSRLSLEDTQQWSQSLERLLESKYGLATFRNF
LKSEYSDENIEFWLTCEDYKKIKSSFRMSSRAKKIYEQFIKVESPKEINI
DYHTREQIKRNVKTPTLHCFDDAQKIVYGLMERDSYPRFLRSDIYRTLLE
NLAADAA---------------------------------K
*
