>P1;ENSORLG00000004697

--------------------------------------------------
---------------------------------------------MKALV
DRRKLEELFNRYKADPQDENKIGIDGIQKFCDDLALDPASISILVVAWKF
RAATQCEFSKKEFIEGMVDLGCDSTKTLIATLPKLEQELKEAGKFKDFYQ
FTFSFAKNPGQKGLDLDMAIPYWNLVLKGRFKFLDLWNRFLLEHHKRSIA
KDTWNLLLDFSNMIEEDMSNYDEEGAWPVLIDDFVEFARPIVTRNKH---
o
*
>P1;ENSTNIG00000009453

-----------------------------------------HKLKSSQKD
KIRQFMSFTQAGERTAVFCLTQNDWKLEVATDNYFQNPDLYYKESMKSSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLMLDPASVSILVVAWKF
RAATQCVFSRKEFLDGMAELGCDSTEKLKAVLPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLILTGRFKFLELWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDNFVEFARPIVAADKRSLT
o
*
>P1;ENSDARG00000040838

MCVIFSLCMFVCVSFCLYTVLNVFLRLSEFMSEGISFVSTQHKLKSSQKD
KVRQFMSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPDLYHKESMKSSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLNLDPASISVLVVAWKF
RAATQCEFSKKEFIDGMTELGCDSPEKLRALLPRLEQDLKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLAGRFKFLDLWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMo-------------------------------
-
*
>P1;ENSAMXG00000016173

--------------------------------------------------
-----MSFTQAGERTAVYCLTQNDWKLEVATDNYFQNPDLYYKESMKTTV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLTLDPASMSVLVVAWKF
RAATQCEFSRKEFLDGMSELGCDSPEKLKAILPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLTGRFKFLDLWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTSGKRKNL
o
*
>P1;ENSORLG00000012645

----------------------------------------QHKLKSSQRD
KVRQFMSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPELYCKESMKTSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLSLDPASITVLVVAWKF
RAATQCEFTKKEFLDGMTELGCDSPEKLKALLPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLSGRFKFLDLWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTGSKRKTL
o
*
>P1;ENSDARG00000041592

--------------------------------------------------
---------------------------------------------MKTAV
DRRKLDLLYSRYK-DPQDENKIGVDGIQQFCDDLMLDPASVSVLIVAWKF
RAATQCEFSRQEFLDGMTDLGCDSPEKLKSLLPRLEQELKDSGKFRDFYR
FTFSFAKSPGQKCLDLEMAVAYWNLILSGRFKFLGLWNTFLLEHHKKSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTAENLQTL
o
*
>P1;ENSXMAG00000019276

----------------------------------------QHKLKSSQKD
KVRQFISVTQAEDRTAVHCLTQNDWKLEVAIDNYFQNPDLYYKEPMKTSV
DRKKLEQLYNRYK-DPHDDNKIGIDGIQQFCDDLNLDPASISILVVAWKF
RAATQCEFSRKEFFDGMVELGCDSPEKLKAILPRLEQDLKDNGKFKDFYQ
FTFSFAKNPGQKGLELEMAVAYWNLVLTDRFKFLDLWIRFLQEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVAGNKRNMT
o
*
>P1;ENSONIG00000014193

----------------------------------------QHKLKSSQRD
KVRQFMSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPELYCKESMKTSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLSLDPASISVLVIAWKF
RAATQCEFTKKEFMDGMTELGCDSPEKLKALLPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLSGRFKFLDLWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTGSKRKTL
o
*
>P1;ENSGACG00000015337

----------------------------------------QHKLKSSQKD
KTRQFMSFTQAGERTAVYCLTRNDWKLEVATDNYFQNPDLYYKESMKTTA
DRKKLDQLYNRYK-DPQDENKIGIDGIQQFCDDLTLDPASMSILVVAWKF
RAATQCEFSRKEFLDGMAELGCDSPEKLKSILPRLEQDLKDTGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLTGRFKFLDLWNRFLMEHHKRSIP
KDTWNLLLDFGNIIADDMSNYDEEGAWPVLIDDFVEFARPIVT-SKRNIT
o
*
>P1;ENSTRUG00000017216

-----------------------------------------HKLKSSQKD
KIRQFMSFTQAAERTAVYCLAQNDWKLEVATDNYFQNPDLYYKESMKTSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLMLDPASVSILVVAWKF
RAATQCVFSRKEFLDGMAELGCDSTEKLKAILPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLILTERFKFLELWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDNFVEFARPIVTANKRSLT
o
*
>P1;ENSGACG00000003116

---------------------------------------MQHKLKSSQRD
KVRQFMSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPDLYCKESMKTSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLSLDPASISVLVVAWKF
RAATQCEFTKKEFLDGMTELGCDSPEKLKALLPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLSGRFKFLDLWNRFLLEHHKRSIP
KDTWNLLLDFGSMIADDMDNYDEEGAWPVLIDDFVEFARPIVTGSKRKTL
o
*
>P1;ENSAMXG00000002635

--------------------------------------------------
-----MSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPDLYFKESMKTSI
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLNLDPASISVLVVAWKF
RAATQCEFSRKEFLDGMTELGCDSPEKLRAMLPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLTGRFKFLDLWNRFLLEHHKRSIP
RDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTGSKRKAV
o
*
>P1;ENSXMAG00000011683

----------------------------------------MHKLKSSQRD
KVRQFMSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPELYCKESMKTSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLSLDPASITVLVVAWKF
HAATQCEFTKKEFMDGMTELGCDSPEKLKALLPRLEQELKDSGKFKDFYQ
FTFNFAKNPGQKGLDLEMAVAYWNLVLSGRFKFLDLWNRFLLEHHKRSIP
KDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTGSKRKTL
o
*
>P1;ENSTNIG00000013890

--------------------------------------------KSSQRD
KVRQFMSFTQAGEKTAVYCLTQNDWKLEVATDNYFQNPDLYCKESMKTSV
DRKRLEQLYNRYK-DPQDENKIGIDGIQQFCDDLSLDPTSITVLVVAWKF
RAATQCEFSKKEFMDGMTELGCDSPEKLKSILPRLEQELKDSTKFKDFYQ
FTFNFAKNPTQKGLDLEMAVAYWNLVLSGRFKFLDLWNRFLLEHHKRSIP
RDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVTSSKRKPL
o
*
>P1;ENSONIG00000003192

----------------------------------------QHKLKSSQKD
KVRQFMSFTQAGERTAVYCLAQNDWKLEVATDNYFQNPDLYYKESMKTSV
DRKKLEQLYNRYK-DPQDENKIGIDGIQQFCDDLTLDPASMSILVVAWKF
RAATQCEFSRKEFLDGMAELGCDSPEKLKAILPRLEQELKDSGKFKDFYQ
FTFSFAKNPGQKGLDLEMAVAYWNLVLTGRFKFLDLWNRFLLEHHKRSIP
RDTWNLLLDFGNMIADDMSNYDEEGAWPVLIDDFVEFARPIVMGTKRNVT
o
*
