>P1;ENSDARG00000089626

----------M-----------HPAAAKWYDRRDFVFIEFLVEDSKDVKV
NFDKSKFGFSCLSGADNVKYSNEIDLFGSIDQDGSKHKRTDRSILCCLQK
AETGKSWPRLTKDKAKLNWLSVDFNNWKDWEDDSDEEISNYDRFSEMMGN
MGGEDDLPDLDGADD--ESADSDDEKMPDL-E
*
>P1;ENSDARG00000037284

----------M-----------QPATAKWYDRREAVFIEFCIEDSKDVQV
KFDKTKLDFSCVGGTDNMKHHNEVDLLEAIDPNDSKHKRTDRSVFCCLKK
AEPGKSWPRLTKEKAKLNWLSVDFNNWKDWEDDSDEELSSFDRFSEMMNN
MGGEDDLPDVDGADEE-ESPDSDDEKMPDL-E
*
>P1;ENSGACG00000008508

----------M-----------QPATAKWYDRRDAVFVDFCVEDSKNVKV
NFENSKFDFGCVGGTDNIKQQNTVDLFGEINPKDSKYRRTDRSVLVCLRK
VEPGKAWPRLTKDKTKCNWLSVDFNNWKDWEDDSDEDLSSFDKFSEMMNT
MGR-DDVPDFDGAGEEHDFENSDDEQMPAL-E
*
>P1;ENSGACG00000015239

----------M-----------HPATAKWYDRRDSVFIEFCVADSKDVKI
NFDKAKFGFSCFGGTDNVKHENEMDLFEAIDVNESKHNRTDRSVLVYLRK
AQPGKPWPRLTKEKAKLSWLSVDFNNWKDWEDDSDEEMGNFDQFSNIMNN
MGGEDDLADLDGPEE--ESADSDDEKMPDL-E
*
>P1;ENSONIG00000011940

LFLMH-----R-----------QPAAAKWYDRRDSVFIEFCVEDSKDVQV
NFDKSKFSFSCVSGTDDIKHQNAVELFGEIDPKESKHRRTDRSVLCCLRK
AEPGKSWPRLTKDKAKCNWLSVDFNNWKDWEDDSDEDLSSFDKFSEMMNS
MGG-DDLPDLDGADDEHESADSDDEKMPDL-E
*
>P1;ENSORLG00000012236

----------R-----------HPATAKWYDKRDSVIIEFCIADSKDVKV
NFDKTKFAFSCLGGADNEKHENEVELFEAIDENESKHKRTDRSVLCYLRK
AQPGKAWPRLTKDKTKLSWLSVDFNNWKDWEDDSEEEMGNFDQFSDMMNN
MGGEEDLPDLDGADDD-DSADSDDEKMPDL-E
*
>P1;ENSAMXG00000004536

PHFKHVLQNFR-----------QSATAKWYDRRDSVFIEFCVEDSRDVEV
KFDKSKLDFSCVGGVDTVKYHNEVDLFEAIDPNESKHKRTDRSVYCCLKK
AESGKSWPRLTKDKAKLNWLSVDFNNWKDWEDDSDEELSSYDRFSEMMNN
MGGEDDLPDMDGADDE-ESADSDDEKMPDL-E
*
>P1;ENSTRUG00000015676

----------A-----------QHAAARWYDRREAVFVEFCVEDSQDVKV
NFDSSKFEFSCVTGAADKKHHNTVDLFSEINPKESKHKRTDRSVLCCLRK
AQPGISWPRLTKLKEKVSWLSVDFNNWRNWEDDSDDDLSSFDKFSEMINK
MGG-DDLPDLEGVDDE-YEPDSHCRRLSSR-N
*
>P1;ENSAMXG00000002019

----------M-----------HPATAKWYDRRDYVFIEFCVEDSKDVTV
NFETAKFGFSCLGGTDNVKHLNEIDLFGAIDQNESKHRRTDRSVLCCLRK
AESGKAWPRLTKEKAKLNWLSVDFNNWKDWEDDSDEELSNFDRFSEMMNS
MGGDDELPDLDGAEDG-ESADSDDEKMPDL-E
*
>P1;ENSTNIG00000012596

----------M-----------QPATAKWYDTRDIVCIEFCVADSKDVKV
NFAKRKFGFSCVRGTDNIKHEHEIDLFEEIDENESKHKRTDRSVLCYLRK
AQPGKKWPRLTQDKVKLAWLGTDFNNWKDWEDDSDEEMGKFDQLSDMMNS
MGGGDDLPDLDGDD---DSADSDDENLPGLED
*
>P1;ENSTNIG00000015101

MEI-------A-----------QHAAARWYDRTEAVFVEFCVEDSQNVQV
NFDTSKLDFSCVSRTADKKLQNTVDLFSEINPKESKHKRTDRSVLCCLRK
AQPGISWPRLTKLKEKVSWLSVDFINWRNWEEDSDDDLSSFDRFSEMINK
MGG-EDLPDLEGGDDE--SLSSFHSVLVFL-E
*
>P1;ENSTRUG00000002456

----------R-----------QPATAKWYDTRDFVCIEFCVADSKDLKV
NFGKKKCGFSCVRGTDNVKHENEIDLFDEIDENESKHKRTDRSVLCYLRK
AQPGKAWPRLTEDKVKLTWLGTDFNNWKDWEDDSDEEMGKFDQLSDMMNS
MGGGDDLPDLDGDD---DSADSDDENLPGL-E
*
>P1;ENSXMAG00000010616

----------MAHLPQHGPFPTLCAIAKWYDRRDFVFVEFCVEDSKDVHV
QFDKSKFEFSCVSRRD--KYYNDIELFGEIDPKQSKHSRTDRSVQCCLQK
AEVGKPWPRLTKEKAKFKWLSVDFNNWRDWDDDSDEDMSSFDNFSEMMNN
MGG-DDLPDFDGAEEH-DSADGDDEKMPDL-E
*
