>P1;ENSAMXG00000019209

V-MADQQRQRSLSTSGETLYLALGVSKTATPEDIKKCY---RKLALKFHP
DKNPDNPEAAEKFKEINNAHAILIDPTKRNIYDQYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGIATGCYCCCCLCCCCNCCCGKCKPRPPMDH
EPDFYVSPEDLEAQMQSDERD------GDPILVQPSSATETTQLKSDSHH
SS-YRTDTGY-------
*
>P1;ENSXMAG00000011375

--MAEHQRQRSLSTAGESLYHVLGVDKVATSDDIKRSY---RKLALKFHP
DKNPDNPEAAEKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCGLATGCYFCCCLCCCCNCCCGRCKPRPREGQ
EQDFYVSPEDLEAQLQSDERE----AAGEPIVLQPS-ATETTQLTSDGHY
-S-YHTDTGFN------
*
>P1;ENSTRUG00000004830

--MAEHQRQRSLSTAGESLYHVLGVEKVATTDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVVCGLATGCYFCCCLCCCCNCCCGRCKPRPRDAQ
DQDFYVSPEDLEAQLQSDERE----AGGEPIMMQPS-ATETTQLTSDGHY
-S-YHTDTGFN------
*
>P1;ENSONIG00000016790

--MSEQQRQRSLSTAGESLYHVLGVDKMATTDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVLCGLATGCYFCCCLCCCCNCCCGRCKPRPREGQ
EQDFYVSPEDLEAQLQSDERE----AGGEPIVLQPS-ATETTQLTSDGHH
-S-YRTDTGFN------
*
>P1;ENSTNIG00000012487

--MAEHQRQRSLSTAGESLYHVLGVEKVATTDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVACGLAT----------------GRCKPRPRDAQ
DQDFYVSPEDLEAQLQSDERGGATEAGGEPIMMQPS-ATETTQLTSDGHY
-S-YHTDTGFN------
*
>P1;ENSDARG00000004836

--MAEQQRQRALSTSGESLYVVLGVEKNTAQEDIKKSY---RKLALKFHP
DKNPNNPEAADKFKEINNAHAILSDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGVATGCYFCCCLCCCCNCCCGKCKPHPPHSD
DPDFYVSPEDLEAQMQSDERD-----GSSPIMMQPSSATESTQLTADSHH
TS-YRTDANY-------
*
>P1;ENSGACG00000010366

--AMEQQRQRSLSTSGDSLYAVLGVDKSATTEDIKKSY---RKLALKFHP
DKNPDNPDAAEKFKEINNAHSILSDGTKKNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCCLST----------------GKCKPRPPMDQ
EPEFYVSPEDLEAQMTADERD-----GGDPVMVQPSSATENTQLTSDAHQ
-S-YRTD---A------
*
>P1;ENSAMXG00000007551

IAMAEQQRQRTLSTSGESLYHVLGVDKIATNDDIKKSY---RKLALKYHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCGLATGCYFCCCLCCCCNCCCGKCKPRPPEGQ
DPEFYVSPEDLEAQLQSDEREA---GGGEPIVLQPS-ATETTQLTSDGHH
TT-YRTDTGFN------
*
>P1;ENSONIG00000014869

--M-DHQRQRTLSTSGESLYAVLGVDKNATTEDIKKCY-IFRKLALKFHP
DKNPDNPEAAEKFKEINNAHSILVDATKKNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCCLATGCYFCCCLCCCCNCCCGKFKPHPPMDQ
DPEFYVSPEDLEAQMTAEERD-----GGDPIVMQPSSATETTQLTSDAHQ
-S-YKTKSH-S------
*
>P1;ENSORLG00000014705

--MTEQQRQRSLSTAGESLYLVLGVDKLATNDDIKRSY---RKLALKFHP
DKNPENPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGLATG---------------GRCKPRPREGQ
EQDFYVSPEDLEAQLQSDERE----AGGEPIVLQPS-ATETTQLTSDGHY
-S-YHTDTGFNKTKERS
*
>P1;ENSTRUG00000004022

--AMDPQRQRTLSTSGESLYVVLGVDKNATTEDIKKCYRNLRKLALKFHP
DKNPDNLEAAEKFKEINNAHAILSDATKKNIYDKYGSLGLFVAEQFGEEN
VNTYFVLSSWWAKALFVFCCLATGCYFCCCLCCCCNCCCGKCKPRPPMDQ
EPEFYVSPEDLEAQMNVEERG-----------LNPCCLTQTTQLTSDAQH
-TLTHTHTHTH------
*
>P1;ENSGACG00000011986

--MAEHQRQRSLSTAGESLYLVLGVEKVATPDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINSAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCGLAT----------------GKCKPRPREGQ
EQEFYVSPEDLEAQLQSDERA---EAGGDPIMLQPS-ATETTQLTSDGHH
-S-YHTDTGF------N
*
>P1;ENSDARG00000042948

--MAEQQRQRSLSTSGESLYHVLGVDKVATVDDIKKSY---RKLALKYHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGLATGCYFCCCLCCCCNCCCGKCKPRPPDRP
DPEFYVSPEDLEAQLQSDERET---VGGEPIVLQPSSATETTQLTSDGYH
TT-YHTDTGFN------
*
