>P1;ENSORLG00000008564

--------------------------------------------------
------------MALFCGCGHEALTQTEVLVETYFARNVQDYVVMASFIK
YFQYVIYGLASFFFLYGILLLAEGFYATSAVKQTFGEFRSTQCGRCLSLT
FIIVTYILAFIWLAVFAFSAIPVFFLFNMEQTCHNINLLAETTASINQHS
WICMDARQYGLLPW--NAVPGKSCGMTLASICKTSEFHLTYDLYIAAFAG
AGVTLLALFLYLIATTYNYAVLRFLGRKGI--------------------
----------------R
*
>P1;ENSAMXG00000014327

--------------------------------------------------
-------------------------------------DECNSLSLYFSIE
YFQYIIYGLATFFFLYCIALLAEGFYTTSAARQTFGEFRSTVCGRCLSTS
FIVITYFLAVVWLLVFALSALPVFFFYNMSSTCRTVDVLSETPSSINQ--
-LCVDARQYGLLPW--NAMPGKACGMTLSNVCKTREFFLTYDLYIAAFAG
AGITLLALLTYVVSTTYNFAVLRYLGRKGLA-------------------
--------------PRC
*
>P1;ENSDARG00000011929

MAASAVDWLGQLPQRLRGVDVKSSNLRRLRPKVTPGCYDCCIRCLGAVPY
TSLVATLLCYAGVGLFCGAGHEALTHTHTFVELHFARDVQDFTVMADFIK
YFQYVIYGLASFFFLYGLLLLAEGFYTTSAVKQTFGEFRSTQFGRCISLT
FIILTYVLALIWLIVFGFTAVPVLFFINMKSSCHTVNVLSETTL-FNQQS
RVCMDARMYGFLSW--NAMPGVVCGNALANICKAPEFHVTYDLYICAFAG
AGITLLALFVYMVATTYNYAILRFLGRKGIR-------------------
----------------C
*
>P1;ENSXMAG00000009555

----------------------------------MGCYDCCMRCLGGVPY
CSLVATLLCFSGIALFCGCGHQALTETERLIETYFARNLHDYITLAYIIQ
YFQYVIYGLASFFFLYCIALLAEGFYTTSAAKQTFGEFRSTMCGRCLSSS
FIVMTYLLAVLWLLVFAFSALPVYFFYNMDATCSTIAVLTETPASINQ--
-LCVDARQYGLLPW--NAVPGKACGMTLSSICKTREYQMTYNLYVAAFAG
AGITLLALLTYTVSSTYNFAVLRYLGRKGIG-------------------
--------------PRC
*
>P1;ENSXMAG00000011480

----------------------------------MGCYDCCIRCIGAVPY
PSLVATLLCYAGMALFCGCGHEALAQTEELVKT-FARDPKDFEVMASFIK
YFQFVIYGLASFFFLYGILLLAEGFYTTSAVKQTFGEFRSTQCGRCLSLT
FIIVTYILAFIWLAVFAFSAIPVFFLFNMEHTCHNINILAETTPSINQHS
WICMDARQYGLLPW--DAMPGKSCGMTLAAICKTSEFHTTYDLYIATFAG
AGVTLLALILYLAPTTYNYAVLRFLGRKGI--------------------
----------------R
*
>P1;ENSAMXG00000007585

MFPVKQPWLCK----------------------ALGCYDCCVRCLGAIPY
ASLAATLLCYAGVALFCAGGHQALTHTDTLVQMHFARSLQDYVVLADFIK
YFQYVIYGLASFFCLFGILLLAEGFYTTSAVKQTFGEFRSTQCSRCLSLT
LIIVTYVLAVIWLVVFAFAGIPVYFLSNMASTCHTVNILSETTTSLNQHA
WVCMDARQFGLLPW--NAMPGKVCGMTMANICKTPEFYVTYDYYITAFAG
AGITLLSLVLYIVPATYNYAVLRFLGRKGIR-------------------
----------------C
*
>P1;ENSORLG00000006441

-----------------------------------GCYDCCMRCLGGVPY
CSLVATLLCFSGIALFCGCGHQALTETERIIETYFARNLQDYITLAYIIQ
YFQYVIYGLASFFFLYCIVLLAEGFYTTSAAKQTFGEFRSTMCGRCLSSS
FIVMTYVLAVLWLLVFALSALPVYFFYNMDATCHTIDVLTETPASINQ--
-LCVDARQYGLLPW--NAVPGKACGMTLSNVCKTREYQMTYNLYIAAFAG
AGITLMALNHLWTLVKYTFLYFKALVECHLYPPVVNKENKKLSISSNQIE
QFDFHT-----------
*
>P1;ENSDARG00000103732

----------------------------------MGCYECCMRCLGGVPY
VSLAATLLCFSGIALFCGCGHQALTESERLIETYFARDNQDYYTLVYLIE
YFQYIIYGLASFFFLYCIVLLAEGFYTTSAVRQSLGEFRSTVCGRCLSTT
FIVITYFLVVVWLLVFSLSAFPVYFFYNMAKTCQTINFLSETPSSINQ--
-LCIDARQYGLLPW--TAIPGKACGMTLSNVCKTREFSLTYNLYIAAFAG
AGMTVLALLTYTVSTTYNFAVLRYLGRKGIS-------------------
--------------PRC
*
>P1;ENSTRUG00000008916

-----------------------------------GCYDCCMRCLGGVPY
CSLVATLLCFSGIALFCGCGHQALTETERLIETYFARNLQDYITLAYIIQ
YFQYVIYGLASFFFLYCIMLLAEGFYISSAARQTFGEFRSTMCGRCLSSS
FIVMTYGLAALWMLVFALSALPVYFLYNMTSTCNTIDVLTETPASINQ--
-LCVDARQYGVC-WMDNGSEFLKSSHSFIRLCKTREYQMTYTLYVAAFAG
AGITVLALVHCTLHLAANQAYLRKLR-HDMR--------E--ESRS----
-YDLYGRLQRDRGGTLC
*
>P1;ENSTNIG00000011791

MFPVRQPWLCK----------------------ALGCYDSCIRCIGAVPY
PSLVATLLCYAGMALFCGCGHQALSQTQVLVETYFARNAQDFAVMAAFIE
YFQYVIYGLASFFFLYGIFLLAEGFYATSAVKQSFGEFRSTQCGRCLSLT
FIIVTYVLAFIWLAVFAFSAIPVFFLFNMEQTCHNINILAETTPSINQHG
WICMDARQYGLLPW--SALPGKSCGMTLASVCKTTEFYVTYDLYIAAFAG
AGITLLALFVYMIATTYNYAVLRFLGRKGI--------------------
----------------R
*
>P1;ENSGACG00000020371

MFPVRQPWLCK----------------------ALGCYDCCIRCIGAVPY
PSLVATLLFYAGVALFCGCGHEALSQTEVLVETHFARNVQDFVVLASFIK
YFQFVIYGLASFFFLYGILLLAEGFYTTSAVKQTFGEFRSTHCGRCLSLT
FIIVTYILAFIWLAVFAFTAIPVFFLFNMEQTCHNINLLAETTPSINQHG
WICMDARQYGLLPW--NAMPGKACGMTLANICKTSEFHVTYDLYIAAFAG
AGIALLALFVYLAATTYNYAVLRFLGRKGV--------------------
----------------R
*
>P1;ENSONIG00000004332

MFPVRQPWLCK----------------------ALGCYDCCIRCIGAVPY
PSLVATLLCYAGMALFCGCGHEALTQTEVLVETYFARNVQDYVVMASFIK
YFQYVIYGLASFFFLYGILLLAEGFYTTSAVKQTFGEFRSTQCGRCLSLT
FIIVTYILAFIWLAVFAFSAIPVFFLFNMEQTCHTVNILSETTASINQHS
WICMDARQYGLLPW--NAMPGKSCGTTLAAICRTSEFHVTYDLYIAAFAG
AGITLLALFLYLVATTYNYAVLRFLGRKGI--------------------
----------------R
*
>P1;ENSTRUG00000015475

MFPVRQPWLCK----------------------ALGCYDSCIRCIGAVPY
PSLVATLLCYTGMALFCGCGHEALSQTEVLVETYFARNAQDFAVLASFIE
YFQYVIYGLASFFFLYGICLLAEGFYASSAVKQSFGEFRSTQCGRCLSLT
FIIVTYILAFIWLAVFALSAIPVFFLFNMEQTCHNINILAETTPSINQHG
WICMDARQYGLLPW--NAMPGKSCGMTLASICKTSEFYVTYDLYIAAFAG
AGITLLALFVYMIATTYNYAVLRFLGRKGI--------------------
----------------R
*
>P1;ENSTNIG00000008976

AD-IVSMWCGW----------------------VAGCYDCCMRCLGGVPY
CSLVATLLCFSGIALFCGCGHQALTETERLIETYFARNLQDYIALVYIIQ
YFQYVIYGLASFFFLYCIVLLAEGFYTSSAARQTFGEFRSTMCGRCLSSS
FIVMTYVLAALWMLVFALSALPVYFLHNMTSTCRTIDVLTETPASINQ--
-LCVDARQYGLLPW--NAVPGKACGMTLSAVCKTREYQITYNLYVAAFAG
AGITVLALLTYTVSTTYNFAVLRYLGRKGIG-------------------
--------------ARC
*
>P1;ENSGACG00000018292

----------------------------------MGCYDCCMRCLAGVPY
CSLVATLLCFSGIALFCGCGHQALTETERLIENYFARNLQDYITLAYIIQ
YFQYVIYGLASFFFLYCIVLLAEGFYTTNAAKQTFGEFRSTMCGRCLSSS
FIVLTYVLAVLWLLVFAFSALPVYFFYNMDATCHTIDVLTETPASINQ--
-LCVDARQYRLLPW--NAVPGKACGMTLSTICKTREYQTTYDLYIAAFAG
AGITLLALLTYTVSTTYNFAVLRYLGRKGLG-------------------
--------------ARC
*
