>P1;ENSDARG00000038855

MVCIPRPTGRSALWWSAFKYLYKANKCHSHINMNRIFGRSKQ-AASPNLS
DCIGNVDTRIESIDKKIARIDAELMKYKDQMKKMRDGPSKNTVKQKAMRV
LKQKRMYEGQRDQLSQQSFNMEQANYTIQSLRDTKTTVEAMKIGAKEMKK
AYKQVKMDQIEDLQDQLEDMMEEANEVQEALSRSYGTPEIDEDELEA--E
LDALGDELLLDDDSSYLDEASSAPSIPEGMPSDTKTNKDGVLVDEFGLPQ
IPAT
*
>P1;ENSORLG00000017844

--------------------------------MIRIFGRGKPKAPPPNLS
DCISTVDARSESIEKKIGRLDAELLKYKDQLKKMRDGPSKNTVKQKAMRV
LKQKRMYEGQREQLAQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKK
AYKDVKLDQIDDLQDQLEDMMEEAGEVQESLSRSYGTPDIDEEDLEA--E
LDALGDELLLDEDSSYLDEASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQ
IPAT
*
>P1;ENSGACG00000004275

--------------------------------MNRIFGRGKPKGPAPNLT
DCIGNVDSRSESVDKKIARLDVELVKYKDQMKKMRDGPSKNMVKQKALRV
LKQKRMYEGQRDNLMQQSFNMEQTNYTIQTLKDTKTTVDAMKIGLKDMKK
AYKHVKIDQIEDLQDELGDMMEDANDIQEALGRSYGTPELDDDDLEA--E
LDALGDELLMDDDSSYLDEAATAPSIPEGMPGDKSVNRDGVLVDEFGLPQ
IPAT
*
>P1;ENSXMAG00000016811

--------------------------------MNRIFGRGKPKAPPPNLS
DCISTVDARSESIEKKVGRLDAELLKYKDQLKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQREQLAQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKK
AYKDVKLDQIDDLQDQLEDMMEEAGEVQESLSRSYCTPDIDEEDLEA--E
LDALGDELLLDDDTSYLDEASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQ
IPAS
*
>P1;ENSDARG00000103718

--------------------------------MNRIFGRGKPKGPPPNLT
DCISGVDSRAESVDKKIARLDAELMKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQRDQLMQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKK
AYKNVKIDQIEDLQDQLEDMMEDANEVQEALSRSYGTPEIDEDDLEA--E
LDALGDELLLDDDNSYLDEASSAPAIPEGAPGDRTTNRDGVLVDEFGLPQ
IPAT
*
>P1;ENSGACG00000017109

--------------------------------MNRLFGRGKPKTPPPNLS
DCIGSVDARSESIEKKIGRLDAELVKYKDQMKKMREGPSKNMVKQKAMRV
LKQKRMYEGQREQLAQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKR
AYKDVKLDQIDDLQDQLEDMMEDAGEVQEALSRSYGTPEIDEDDLEA--E
LDALGDELLLDDDSSYLDEASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQ
IPAS
*
>P1;ENSORLG00000011425

--------------------------------MNRIFGTGKPKAPPPNLS
DCIGNVDSRTESVDKKIARLDAELVKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQRDNLMQQSFNMEQANYTIQTLKDTKTTVDAMKTGLKEMKK
AYKQVKIDKIEDIQDQLEDMMEDANEIQEAMGRSYGTPEIDEDDLEA--E
LDALGDELLMDDDSSYLDEAATAPSIPEGNPGDRTANRDGVLVDEFGLPQ
IPAT
*
>P1;ENSONIG00000009226

--------------------------------MNRIFGRGKPKAPPPNLS
DCIGTVDARAESIEKKIGRLDAELLKYKDQLKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQREQLAQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKK
AYKDVRLDQIDDLQDQLEDMMDEANEVQEALSRSYGTPDIDEEDLEA--E
LDALGDELLLDDDTSYLDEASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQ
IPAT
*
>P1;ENSTRUG00000006914

--------------------------------MNRIFGSSKPKGPPPNLT
DCIGTVDSRTDSIDKKISKLDAELVKYKDQMKKMKDGPSKNMVKQRAMRI
LKQKKAYENQRDGLAQQSFNMEQANYTIQNLKDTKTTVDAMKTGLKEMKK
AYKKVDINKIEDIQDQLEDMMEDANDIQDALGRSYGTPDIDEADLEAGTE
LDALGDELLFDDDSTYLDEASTAPSIPEGIPGDKSTNRDGVLVDEFGLPQ
IPAS
*
>P1;ENSTRUG00000011216

--------------------------------MNRIFGRSKPNPPPPNLS
DCIGNVDARSESIEKKISRLDAELIKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQREQLAQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKK
AYKDVKLDQIDDLQDQLEDMMDEANDVQEALSRSYGTPDIDEDDLEA--E
LDALGDELLLDDDSSYLDEASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQ
IPAS
*
>P1;ENSXMAG00000002110

--------------------------------MNRIFGRGKAKGPPPNLT
DCIGSVDSRAESIDKKIARLDAELVKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQRDNLMQQSFNMEQANYTIQNLKDTKTTVDAMKVGLKDMKK
AYKNVNIDKIEDIQDQLEDMMEDANEIQEAMSRSYGTPDIDEDDLEA--E
LDALGDELLMDDDSSYLDEAATAPSIPEGIPGDRSTNRDGVLVDEFGLPQ
IPAS
*
>P1;ENSTNIG00000018642

--------------------------------MNRIFGRSKPKTPPPNLS
DCIGNVDARSESIEKKIARLDAELIKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQREQLAQQSFNMEQANYTIQTLKDTKTTVEAMKIGAKEMKK
AYKDVKLDQIDDLQDQLEDMMDEANEVQEALSRSYGTPDIDEDDLEA--E
LDALGDELLLDDDSSYLDEASAAPSIPEGIPNDSKTNK------------
----
*
>P1;ENSAMXG00000018188

--------------------------------MNRIFGRSKN-QPPPNLS
ECIGNVDARAESIDKKIARIDSELVKYKDQMKKMRDGPAKNAVKQKAMRV
LKQKRMYEGQRDQLAQQSFNMEQANYTIQSLKDTKTTVEAMKIGAKEMKK
AYKQVKMDQIEDLQDQLEDMMEEASEVQEALSRSYGTPDIDEDDLEA--E
LDALGDELLLDDDSSYLDEASAAPAIPEGMPSDSKTNKDGVLVDEFGLPQ
IPAT
*
>P1;ENSONIG00000006122

--------------------------------MNRIFGKGKAKGPPPNLT
DCIGSVDSRAESIDKKIARLDAELVKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYESQRDNLMQQSFNMEQTNYTIQNLKDTKTTVDAMKVGLKDMKK
AYKNVKIDKIEDLQDQLEDMMEDANEIQEAMSRSYGTPDIDEDDLEA--E
LDALGDELLMDDDSSYLDEASSAPSIPEGLPGE-KSNRDGVLVDEFGLPQ
IPAS
*
>P1;ENSLOCG00000011176

------------------------------VKMNRLFGRSKPKGPPPNLT
DCIGNVDSRAESIDKKIARLDAELVKYKDQMKKMRDGPSKNMVKQKAMRV
LKQKRMYEGQRDNLMQQSFNMEQANYTIQTLKDTKTTVDAMKIGAKEMKK
AYKQVKIDQIEDLQDQLEDMMEEANDVQEALSRSYGTPEIDEDDLEA--E
LDALGDELLLDEDTSYLDEASSVPSIPEGVPSDIKTNKDGVLVDEFGLPQ
IPAT
*
