>P1;ENSDARG00000074719

---------------------MQKEHLFKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFALKVLHWDSQTVVRLQLWDIA-GQERYGNMTRVYYR
EAVGALIVFDVTRSSTFDAVLKWKDDLDLKVSLNNGKPVPAVLLANKSDQ
SREGLCSQIPKLDTFCKENGFVGWFETSAKENSNIEAAAKCLVDHILAHE
ENIV-N---------NTDPDVVALPGYNNNTKERVRSRCMTCSKS-----
-----
*
>P1;ENSORLG00000001857

-----------------V-EMQQQEFLFKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFVLKVLQWDNDRVVRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDVTRASTFDAVLKWKDDLDSKVTLSHGRPVPAVLLANKSDQ
M----ASQVPKLDSFCRENGFVGWFGTSAKDNTNIEEAARCLVEHILTNE
ESPA-A---------ERESGSLILSGHTNTTKN--HFRCSSCVK------
-----
*
>P1;ENSXMAG00000000327

---------------------MQQELLFKVLVVGDLGVGKTSIIKRYVHQ
IFSQHYRTTIGVDFALKVLQWDSDTVIRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDVTRASTFEAVLKWKDDLDAKVTLNHGRPIPAVLLANKSDQ
I----ACQLPKLDFFCRENGFVGWFETSAKENTNIDEAARCLVEHIMNNE
ESSV-S---------EREPTSILLSGYASTARS--PLNCSSCLK------
-----
*
>P1;ENSTRUG00000004036

---------------------MQHERLLKVLVIGDIGVGKTSIITRYVHQ
VFSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIAEGQERYGNMTRVYYK
EAVGALVVFDMTRLSTFQAVLKWKGDLDSKVALGNGRTVPAVLLANKCDQ
RDHGLCPKLPKLESFSREYGFIGWYETSAKDDTNIDAAITCLVKSIMSLE
EESATA----------DAAGANH---------------------------
-----
*
>P1;ENSAMXG00000005910

---------------------MQQEHLFKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFALKVLNWDSQTVIRLQLWDIA-GQERYGNMTRVYYR
EAVGALIVFDVTRASTFDAVLKWKDDLDSKVTLSNGKPVPAVLLANKSDQ
LREGVCSQIPKLDTFCKENGFVSWFETSAKENTNIEAAARCLVQHILAHE
ENTV-N---------DSDPDTVTLPGYNNNTKDHGRTSCSACSKY-----
-----
*
>P1;ENSGACG00000020438

VM-------LRIKQICSA-ATMQQELLFKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFALKVLQWDRDTVVRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDVTRASTFDAVLKWKEDLDSKVTLNPGRPVPAVLLANKSDQ
L----ASQQPKLDSFCRENGFVGWFETSAKENANIEEAARCLVQHILNNE
ESPA-V---------ERDPGAAVLSAYTNTAKD--HLNCSSC--------
-----
*
>P1;ENSDARG00000036499

---------------------MQQERLLKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFALKVLNWDHRTVVRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDMTRASTFQAVLKWKKDLDSKVALGNGRPLPAVLLANKCDQ
QRYGLCSKLPKLEHFSRDHGFVGWYETSAKDNTNIDAAIMRLVENIMAVE
EENVPV---------ESDPSVLILPAFDYNLKERSDSRCSVCTKFQSSIK
PHSEL
*
>P1;ENSTNIG00000003678

CCGSPPARALAVPTPAPV-SAMQQERLLKVLVIGDLGVGKTSIITRYVHQ
VFSQHYRATIGVDFALRVLDWDHKTVVRLQLWDIA-GQERYGHMTRVYYR
EAVGAL-VFDMTRMSTFQAVLKWKGDLDSKVALGNGRPVPAVLLANKCDQ
RAQGLCPKLPKLEAFCRDSGFIGWYETSAKDDTNIEAAIMCLVRSIMSLE
E-------------------------------------------------
-----
*
>P1;ENSGACG00000001952

-----------------A-RGMQRERLLKVLVIGDLGVGKTSLIKRYVHR
VFSQHYRATIGVDFALKMLSWDQKTVVRLQLWDIAEGQERYGNMTRVYYR
EAVGALVVFDMTRLSTFQAVLKWKEDLDSKVALSNGTPVPAVLLANKCDQ
RSHGLCPKLPKLENFSRQCGFVGWYETSAKDDTNIDAAVTCLVESIMAAE
DERATAA------RDEPEGGVLVLPRLDCDAKEKERRGCSGCASL-----
-----
*
>P1;ENSXMAG00000001484

---------------------MQQERLLKVLVIGDLGVGKTSIIKRYVHQ
VYSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIA-GQERYGNMTRVYYR
EALGALVVFDMTRLATFQAVLKWKRDLDSKVTLSNGKPVPAVLLANKCDQ
RQLGLCPKLPKLEKFSQDHGFVGWFETSAKDDTNIDSAITCLVKAITSAE
EEKVSRDA--A--PSESDGGVIVLPRFDHSAKEKGLNDCAGCTSTKPRPG
A-S-D
*
>P1;ENSONIG00000006996

---------------------MQRERLLKVLVIGDLGVGKTSIIKRYVHQ
VFSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDMTRLSTFQAILKWKGDLDSKVALSNGRPVPAVLLANKCDQ
RRHGLCPKLPKLENFSKEYGFVDWYETSAKDNTNIDAAITCLVKSIMSVE
EERALGEATSGADKGDPDGSVLVLPRFDYNTTEKGLGGCAGCLSIKPKQD
--Q-D
*
>P1;ENSONIG00000008546

-----------------P-AAMQQELLFKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFALKVLQWDSNTVIRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDVTRASTFDAVLKWKDDLDSKVTLNHGRPVPAVLLANKSDQ
L----VSQQPKLDAFCRENGFVGWFETSAKENTNIEEAARCLVEHILRNE
ESLV-T---------EREPGSLILSGCTTTSKE--HLGCSSCSKW-----
-----
*
>P1;ENSAMXG00000003714

---------------------MQQERLLKVLVIGDLGVGKTAIIKRYVHQ
VFSQHYRATIGVDFALKVLNWDHRTVIRLQLWDIA-GQERYGNMTRVYYR
EAVGALVVFDMTRASTFQAVLKWKMDLDSKVALNNGRPVPAVLLANKCDQ
QKQGLCARLPKLDTFSRDHGFVGWYETSAKDNTNIDAAIMCLVENILASD
VENTAV---------DSDPSLLVLPSFDYNLRERSGPGCSACSRRRSTPR
DNSDF
*
>P1;ENSLOCG00000014930

-----------------IMDQPQKEFLFKVLVIGDLGVGKTSIIKRYVHQ
IFSQHYRATIGVDFALKVISWDDHTVIRLQLWDIA-GQERYGNMTRVYYR
EAVGAFVVFDVTRVSTFDTVLKWKGDLDSKVTLAGGKPVPAVLLANKADQ
SREGLSPQLPRLDAFCKDNGFVGWYETSAKENSNIEAAARCLVENILANE
ESSG-T---------DPDPG-LVLPGHNNNAKR-ESSGCATCFKP-----
-----
*
