>P1;ENSDARG00000055383

MEEKKEES-EAEIHEHGPEHWFSKWERQCLAEAEREEPS-EEEVDQDQEK
MWHLFQNSATAVAQLYKDRVCHQ-QGPSLWSPFQNSATAVTNLYKESVDA
HKRSFDLGIQIGHQRRNKDVLAWVKKRRRTIRREDLISFLCGKAPPPRTS
RAAPKMTVMSPIRA-PSSDTVSSVETDLQPFCEAIALHGLSGAMASISVR
SSTPGSPTHVSGSSNAG------------RRRNGLHD--VDLNTFISEEM
ALHLGSA---------GTRKRSSVQCADVITDSPTHKRNRML
*
>P1;ENSORLG00000009153

MEEKKEEG-EAEIQEHGPEHWFSKWERQCLAEAEQDTPN-EEETEQSQQK
LWHLFQNSATAVAQLYKDRVCQQ-QGFSMWVPFQNAATAVTNLYKESMDA
HQRSYDLGIHLGHQRRNKEVIAWVKKRRRTIRREDLISFLCGKAPPPRTA
RAPPRVAMVSSSRS-SPTETDNSVETDLQPFREAIALHGLSGAMASISVR
SGPPGSPTHPAQP--LG------------RRRNGLHD--VDLNTFIAEEM
ALHLDSA---------ANRKRVSAPCSDVITDSPTHKRNRML
*
>P1;ENSDARG00000012458

MEEKKEEG-EAEIQEHGPEHWFSKWERQCLAEAEQEEPA-EEETDQSQQK
LWHLFQNSATAVAQLYKDRVCQQQQGLSLWVPFQNAATAVTNLYKESVDA
HQRSYELGIQIGHQRRNKDVLAWVKKRRRTIRREDLISFLCGKAPPPRSS
RAPPRLAMVSPSRP-TPSETSSSVETDLQPFREAIALHGLSGAMASISMR
SGAPGSPTHLSASSAPS------------RRRNGLHD--VDLNTFIAEEM
ALHLDN----------GTRKRSSAQCNDVITDSPTHKRNRMI
*
>P1;ENSORLG00000012830

MEEKKEDG-DSEIQEHGPEHWFSKWERQCLAEAEQRDLS-EEEADNNQDK
LWHLFQNSATAVAQLYKDRVCHQ-QGLSLWVPFQNAATAVTNIYKESVEA
HQRSFDRGIQIGHQRRNKDMLAWVKKRRRTIRREDLISFLCGKLPPHRSS
RTNSRLAVVAPSRANSPVETGSSVEADLEPFREAIALHGLSGAMASISVR
SGAPGSPTHVSGSSMCR------------GRRNGLQD--VDLNTFISEEM
ALHLDSTGSASAG-GGVTRKRNSTQCSDVITDSPTHKRNRMI
*
>P1;ENSAMXG00000002505

MEEKKEEKRGAEIQEHGPEHWFSSWERQCLAEAEQDEPSGGEEVDQSQEK
LWHLFQNSATAVAQLYKDRVCHQ-QGLSLWVPFQNAATAVTNLYKESVDA
HERSYDLGIQTGHQRRSKDVLAWVKKRRRTIRREDLISFLCGKAPPPRIS
RAAPRLS---PNRQ-PSSDTVSSVETDLQPFREAIALHGLSGAMASISVR
SSTPGSPTHVSSSSNSS------------RRRSGFHD--VDLNTFISEEM
ALHLDSG---------GNRKRTSAQCTDVITDSPTHKRNRMI
*
>P1;ENSTNIG00000011617

MEEKKEEG-DSEIQGHGPEHWFSKWERQCLAEAEQRELS-EEEVDNDQDK
LWHLFQNSATAVAQLYKDRVCHQ-QGLSLWVPFQNSATALTNLYKESVEA
HQRSFDRGIQIGHQRRNKDMLAWVKKRRRTIRREDLISFLCGKAPPHRSS
RANPRLTVGGPSRANSPAETGSSVEADLQPFREAIALHGLSGAMASISVR
SGAPGSPTHVSGSSSGGGGGSSSAVPACRARRNGLQD--VDLNTFISEEM
ALHLDSTGSASAG-GGATRKRSSTQCSDVITDSPTHKRNRMI
*
>P1;ENSTRUG00000009623

MEEKKEEG-DSEIQEHGPEHWFSKWERQCLAEAEQRELS-EEEVDNDQDK
LWHLFQNSATAVAQLYKDRVCHQ-QGLSLWVPFQNSATALTNLYKESVEA
HQRSFDRGIQIGHQRRNKDMLAWVKKRRRTIRREDLISFLCGKAPPHRSS
RANPRLTMVAPSRANSPAETGSSVEADLQPFREAIALHGLSGAMASISVR
SGAPGSPTHVSGSSSTG------------GRRNGLQD--VDLNTFISEEM
ALHLDSTGSASAG-GGGARKRNSTQCSDVITDSPTHKRNRLI
*
>P1;ENSAMXG00000004225

MEEKKEES-EAEIQEHGPEHWFSKWERQCLAEAEQDEQS-EEDVDQSQQK
LWHLFQNSATAVAQLYKDRVCQQ-QGLSLWVPFQNAATAVTNLYKESVEA
HQRSYELGIQIGHQRRNKDVLAWVKKRRRTIRREDLISFLCGKAPPPRNS
RAPPRLAMVSPSRP-ASSETSSSVETDLQPFREAIALHGLSGAMASISMR
SGAPGSPTHLSASSAPG------------RRRNGLHD--VDLNTFIAEEM
ALHLDN----------GTRKRSSAQCNDVITDSPTHKRNRMI
*
>P1;ENSTNIG00000008278

MEERKEES-GAEIQEHGPEHWFSKWERQCLAEAEQSDPS-EEETEQSQQK
LWHLFQNSATAVAQLYKDRVCQQ-QGISLWVPFQNAATAVTNLYKESVEA
RQRSYDLGIHLGYQRRNKDVIAWVKKRRRTIRREDLISFLCGKVPPPRTS
RAPPRVA----SRP-TPTETDSSVETDLQPFREAIALQGLSGAMASISVR
SGAPGSPTHPAQS--LS------------RRRNGLHD--VDLNTFIAEEM
ARHMDST---------ATRKRGPAPCSDVITDSPTHKRNRML
*
>P1;ENSGACG00000016635

MEEKKEEG-EAEIQEHGPEHWFSKWERQCLAEAERTDPN-EEETEQSQQK
LWHLFQNSATAVAQLYKDRVCQQ-QGLSLWVPFQNAATAVTNLYKESMEA
RQRSYDLGIHLGHQRRNKDVIAWVKKRRRTIRREDLISFLCGKVPPPRTA
RAPPRVSMVSASRP-SPPETGSSVETDLQPFREAIALHGLSGAMASISVR
SGPPGSPTHPAQP--LS------------RRRNGLHD--VDLNTFIAEEM
ALHLDST---------ANRKRGPAPCSDVITDSPTHKRNRML
*
>P1;ENSXMAG00000001670

MEEKKEDG-DSEIQEHGPEHWFSKWERQCLAEAETMDPG-EEEADNDQDK
LWHLFQNSATAVAQLYKDRVCHQ-QGLSLWVPFQNAATAVTNLYKESVEA
HQRSCDRGIQIGHQRRNKDMLAWVKKRRRTIRREDLISFLCGKAPPHRSS
RTNSRLAMVAPSRANSPAETGSSVETDLQPFREAIALHGEESCWSRDSVS
CFSHASLPHVTIRQRTR------------RLETGILSCWVELNT-IYEDM
AAHMNLIG------RGGNRKRNSTQCSDVITDSPTHKRNRVI
*
>P1;ENSGACG00000014316

MEEKKEDG-DSEIQEHGPEHWFSKWERQCLAEAEQREPS-EEEADNDQDK
LWHLFQNSATAVAQLYKDRACHQ-QGLSLWVPFQNSATAVTNLYKESAEA
HQRSFDRGIQIGHQRRNKDMLAWVKKRRRTIRREDLISFLCGKAPPHRSS
RANPRLAMVAPSRANSPAETGSSVETDLQPFREAIALHGLSGAMASISVR
SGAPGSPTHVSGSTSNG------------GRRNGLQD--VDLNTFISEEM
ALHLDSTGSASAG-GGGARKRNSTQCSDVITDSPTHKRNRMI
*
>P1;ENSONIG00000015693

MEEKKEDG-DSEIQEHGPEHWFSKWERQCLAEAEQREPS-EEDVDNEQDK
LWHLFQNSATAVAQLYKDRVCHQ-QGLSLWVPFQNAATAVTNLYKESVEA
HQRSFDRGIQIGHQRRNKDMLAWVKKRRRTIRREDLISFLCGKAPPHRSS
RANPRLAMVAPSRANSPAETGSSVEADLQPFREAIALHGLSGAMASISVR
SGAPGSPTHVSGSSSNG------------GRRNGLQD--VDLNTFISEEM
ALHLDSTGATSAGGGGGTRKRNSTQCSDVITDSPTHKRNRMI
*
>P1;ENSLOCG00000006228

MEDKKEEG-ESEIQEHGPEHWFSKWERQCLAEAEQEEPS-EEEADQSQQK
LWHLFQNSATAVAQLYKDRVCQQ-QGLSLWVPFQNAATAVTNLYKESMEA
HQRSYDLGIQIGYQRRNKDVLAWVKKRRRTIRREDLISFLCGKAPPPRTS
RAPPRLTVVSPNRA-PSTETSSSAETDLQPFREAIALHGLSGAMASISVR
SSTPGSPTHVSGGSNPS------------RRRNGLHD--VDLNTFISEEM
ALHLDNG---------GTRKRTSAQCGDVITDSPTHKRNRMI
*
