>P1;ENSAMXG00000018807

--EGLSNFRM-K--LKSSRLGYLLLQFMTLLFYTQ---------------
---------------TTMQSVSVPNFKHHVTEHSRLSDRMSRRLTRTYQL
YSRTSGKHVQVLGNKRVVANGEDGDAH--AKLVVETDTFGSRIRIRGAKT
GFYICMNKKGKLVGRRKGHGRDCIFTEIVLENNYTALQNAKYKGWYMAFT
RKGRPRKATHTRQHQREAHFMKRLPRGHLL---TERKPFDVVP-----YQ
LNKRTKHNHR--PGV----N
*
>P1;ENSXMAG00000000105

MKQYLNYYRM-R--LRTSRLGYLFLQLAALCFYAQ---------------
---------------DTVQS--PPNFKQHVTEQSRLSDRMSRRLTRTYQL
YSRTSGKHVQVLANKRVNANGDDGAVH--AKLEVETDSFGSRVRIKGVKT
GYYICMNKRGKLIGKRKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFT
RKGRPRKASKTKQHQREAHFMKRLPRGHLL---SDRRPFDVLPLPVPVQP
LSRRTKHSHHQRSGG----R
*
>P1;ENSGACG00000003803

---------R-AICFMLPRLNK-CLHLFSFCYFAQ---------------
---------------VTNQS--PPNFTQHVSEQSKVTDRVSRRLIRVYQL
YSRTSGKHVQVLPNKKINAMADDGDVH--AKLIVETDTFGSRVRIKGAET
GFYICMNKKGKLIGKNNGHGRDCIFTEIVLENNYTALRNARYESWYMAFT
RRGRPRKGSRTRQHQREVHFMKRLPKGQQPAHTSHHRPFDFVH-----YP
FRQRTKRTRY--SSE----R
*
>P1;ENSTRUG00000000925

---------M-R--PIPSRLSYLFLHLFAFCYYAQEAFDPTWREFSMELA
AIFIRDHTPQSIVAQVTNQS--PPNFTQHVSEQSKVTDHVSRRLIRVYQL
YSRTSGKHVQVLPNKKINAMADDGDVH--AKLIVETDTFGSRVRIKGAET
GFYICMNKRGKLVGKKNGQGRDCIFTEIVLENNYTALRNARYEGWYMAFT
RRGRPRKGSRTRQHQREVHFMKRLPKGQQPVHPSHHRPFDFIH-----YP
FNQRTKRTRH--SSERPNPR
*
>P1;ENSONIG00000013179

---------M-R--PIPSRLSCVFLHLFALFYYAQ---------------
---------------VTNQS--PPNFTQHVSEQSKVTDRTSRRLIRIYQL
YSRTSGKHVQVLPNKKINAMAEDGDVH--AKLIVETDTFGSRVRIRGAET
GLYICMNKRGKLIGKKNGQGRDCIFTEIVLENNYTALKNVRYEGWYMAFT
RQGRPRKGSRTRQHQREVHFMKRLPKGHQPTHPSHHQPFDFIH-----YP
FSQRTKRT------------
*
>P1;ENSORLG00000000919

---------FTS--LIPPVIGHGFLHLFAFCHYAQ---------------
---------------VTNQS--SPNFTQHVSEQSRVTDHVSRRLIRVYQL
YSRTSGKHVQVLSNKKINAMAEDGDVH--AKLIVETDTFGSQVRIKGAQT
GLYICMNKKGKLIGKKNGQSRDCIFTEIVLENNYTALRNAHYNDWYMAFT
RRGRPRRGSQTRQHQREVHFMKRLPRGQQVIHSSQHRPFDFIH------S
FSQRTKRTRY--SSE----R
*
>P1;ENSONIG00000018818

MKQYLNYYKM-R--LRTSRLGYLLLQFTALCFYAQ---------------
---------------NTVQS--PPNFKHHVTEQSRLSDRMSRRLTRTYQL
YSRTSGKHVQVLANKRVNANGEDGAAH--AKLEVETDSFGSRIRIKGVKT
GYYICMNKKGKLIGKRKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFT
RKGRPRKASKTKQHQREAHFMKRLPRGHLL---SEKRPFDVLPLPVPAHP
FNKRTKHSHHQRSGG----R
*
>P1;ENSTRUG00000014840

---------M-R--LRTSRLGYLLIHFTALCFYAQ---------------
---------------NTAQS--PPNFKHHVTEQSRLSDRMSRRLTRTYQL
YSRTSGKHVQVLANKRVNANGDDGAVY--AKLEVETDSFGSRIRIKGVKT
GYYICMNKRGKLIGKRKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFT
RKGRPKKASKTKQHQREAHFMKRLPRGHLL---SERRPFDVLPLAVPVHS
LNKRTKLPHQQRSAP----R
*
>P1;ENSDARG00000039615

---------M-R--LKSSRLGYLFLQFMTLCFYTQ---------------
---------------MTMQSISMPNFKHHVTEQSRLSDRMSRRLTRTYQL
YSRTSGKHVQVLGNKRVNANAEDGDIHGKAKLVVETDTFGSRVRIRGAKT
GYYICMNKKGKLIGRRKGRGKDCIFTEIVLENNYTALQNAKYKGWYMAFT
RKGRPRKAMQTRQHQREAHFMKRLPRGHLL---TEQKPFDLIP-----YP
LNKRTKHHQR--ASV----N
*
>P1;ENSDARG00000003399

---------M-R--LIPSRLSYLFLHLFAFCYYAQ---------------
---------------VTIQS--PPNFTQHVSEQSKVTDRVSRRLIRTYQL
YSRTSGKHVQVLANKKINAMAEDGDVH--AKLIVETDTFGSRVRIKGAET
GFYICMNRRGKLIGKKNGLGKDCIFTEIVLENNYTALQNVKYEGWYMAFT
RKGRPRKGSKTRQHQREVHFMKRLPKGHQI---AEHRPFDFIN-----YP
FNRRTKRTRY--SGE----R
*
>P1;ENSTNIG00000006362

---------M-Q--TISSRLSYLFLHLFAFCYYAQ---------------
---------------VTNQS--SPNFTQHVSEQSKVTDHVSRR-IRIYQL
YSRTSGKHVQVLPNKKINAMADDGDVHV-AKLIVETDTFGSRVRIKGAET
GFYICMNKRGKLIGKKNGQGRDCIFTEIVLENNYTALRNARYEGWYMAFT
RRGRPRKGSRTRQHQREVHFMKRLPKGQQPVHPSHHRPFDFIH-----YP
FNQRTKRTRY--SSE----S
*
>P1;ENSAMXG00000012018

---------M-R--LIPSRLSYLFLHLFAFCYYAQ---------------
---------------VTIQS--PPNFTQHVNEQSRVTDRVSRRLIRTYQL
YSRTSGKHVQVLANKKINAMADDGDVH--AKLIVETDTFGSRVRIKGAET
GFYICMNRRGKLIGKKNGQGKDCIFTEIVLENNYTALQNVKYEGWYMAFT
RKGRPRKGSKTRQHQREVHFMKRLPKGHHI---AEHRPFDFIN-----YP
FNRRTKRTRY--SGE----R
*
>P1;ENSGACG00000018276

---------M-R--LRTSRLGYLLLQFTALCFYAQ---------------
---------------NTVQS--PPNFKHHVTEQSRLSDRMSRRLTRTYQL
YSRTSGKHVQVLANRRVNANGDDGAVH--AKLEVETDSFGSRVRIKGVKT
GYYICMNKRGKLIGKKKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFT
RKGRPRKASKTKQHQREAHFMKRLPRGHLL---SERRPFDALPLRVPAHP
LSKRTKHSHHQRSGG----R
*
>P1;ENSLOCG00000011679

---------M-R--IIPSRLSYLILHLLALCFHAQ---------------
---------------VTIQS--SPNFTQHVSEQSKVTDRVSRRLIRTYQL
YSRTSGKHVQVLGNKKINAMAEDGDAH--AKLIVETDTFGSRVRIKGAET
GYYICMNKRGKLIGKVGNNI------------------------------
--------------------------------------------------
--------------------
*
