>P1;ENSDARG00000100835

MSGLI-----QAFP---A-------HFSMDRDDCRRNKTLGKNLMCRLKS
MF---------------AGS-S-V---------------PERLSLEDTQQ
WSQSLERLLGSKYGLATFRTFLK-SEFSDENIEFWL--------------
TCEDYKTITSSHKMSSKARKIFEQFVEAESPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------YQTREEIKRK
MK-----SPTAQCFDE----------------------------------
AQKIVYG------------------LMERDSYPRFLRSEMYKSLLETIAA
DDE-----------------------------------A-----G
*
>P1;ENSTRUG00000009818

M----------------------------DPDKRK-----GKDRSRPLRY
CLRS-------------SQV-P-K---------------TKGLSFEEMTQ
WSLSLERLLSSKYGIQIFQAFLK-SEFSDENIEFWM--------------
VCEDYKKIRSSFRMSSRAKKIFKCYIQAEATREINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------HKTRDLIRRN
VA-----APTRECFND----------------------------------
AQRIVYN------------------LMEKDSYPRFLRSDIYRSLLDSTSK
DAEKE--------KRLNRLQKSFGDFLPVVPGSE----C---G--
*
>P1;ENSGACG00000005823

LMHFL-----SV--------------------------HSGKNFMCRLQC
MF---------------SNS-S-SSERIASTLPSFPSMASCRLSLEDTQQ
WSQSLERLLESKYGLATFRNFLK-SEYSDENIEFWL--------------
TCEDYKKIKSSFRMSSRAKKIYEQFIKAESPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------YQTREQIKRN
VK-----TPTVHSFDD----------------------------------
AQKIVYG------------------LMERDSYPRFLRSDIYRTLLENLAA
DA------------------------------------------T
*
>P1;ENSAMXG00000017670

APSSIMTGLISE-PL-IK-------HFSMDRDDRKRSKNLGKNFMCRLQC
MF---------------SRS-S-AP--------------ESRLSLEDTQQ
WAQSLERLLESKYGLATFRTFLK-SEFSDENIEFWL--------------
TCEDYKKIRSSFRMTSRAKKIYEQFVKAESPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------YHTREQIKRN
VK-----SPTAQCFDE----------------------------------
AQKIVYG------------------LMERDSYPRFLRSEMYRTLLDSLAV
DAA-----------------------------------H-----G
*
>P1;ENSXMAG00000002712

MPSIK-----AKPPS-TH-------HFIMDRDDRNRNNTLGKNFMCRLQC
MF---------------SQT-PQCS--------------ESGLSLEDTQQ
WSQSLERLLESKYGLATFRNFLK-SEYSDENIEFWL--------------
TCEDYKKIKSSFKLSSRAKKIYEQFIKAESPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------YHTREQIKRN
VK-----TPTMHCFDE----------------------------------
AQKIVYG------------------LMERDSYPRFLRSDIYRTLLESLAT
DAT-----------------------------------T-----G
*
>P1;ENSGACG00000016116

MLSLV-----ASPPRELQ-------PLNMDTDNKKR----AGNLKLRLQC
RS---------------SQA-A-T---------------TEGICYEEISQ
WSHSLEGLLSSKYGMKIFQAFLK-SEFSDENIDFWL--------------
VCEDYKKIKSSFRMSSRAKKIFKRYIQAEAPREINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------HKTREMIRRN
MK-----TPTAVCFDD----------------------------------
ARRIVYG------------------LMERDSYPRFLRSDIYQALLDSTSE
SIKIR---------------------------------K---G-S
*
>P1;ENSDARG00000017653

MPTIL-----ST-----E-------IENMNKEDKATNPRRLE--KWRFRC
P----------------------L---------------TEKINPGETSQ
WSQSLENLLRSKYGMATFHTFLK-SEFSDENIEFWL--------------
VCEDFKKTRSLSRLSSRAKKIFERYIKAEAPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------HVTRELIKQN
VH-----APTKVCFDE----------------------------------
AQRIVFG------------------LMERDSYPRFLRSDMYRSLLESVSN
GIK-----------------------------------------V
*
>P1;ENSTNIG00000006931

--------------------------------------------------
-----------------------------------------RLSFEEMTQ
WSLSLERLLSSKNGIKVFQAFLK-SEFSDENIEFWL--------------
VCEDYKKIGSSFRMSSRARKIFKRYIQADAAREINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------HKTRDLIRRN
VA-----APTRVCFDD----------------------------------
AQRIVYS------------------LMEKDSYPRFLRSDIYHRLLDSTSK
SGM------------------------------------------
*
>P1;ENSORLG00000012336

MCKGL-----ASLH--TC-------CLERTKEMKAR----LGNILQKPNW
TL---------------SCF-K-IG--------------KNKPSLEECLC
WKESFEKLLSSKYGLCAFTAFLV-SEFSEENIAFYF--------------
ACEDYRQTKCPTKLRAKAQKIFDEFFGSDAPREINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------HETRDITKAN
LQ-----TPTPSCFDL----------------------------------
AQHRIYM------------------LMAKDCYPRFLRSPAYRDLVCQAKP
TTKSSKHSQPDKKSRKQAC-------RRASVDRS----K---P-K
*
>P1;ENSONIG00000010956

MPSLI-----VEPPN-TQ-------RFIMDRDDRNRNKNIGKNFMCRLQC
MF---------------SHS-S-SS--------------ESRLSLEDTQQ
WSQSLEKLLESKYGLATFRNFLK-SEYSDENIEFWL--------------
TCEDYKKIKSSFRMSSRAKKIYEQFIKAESPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------YHTREQIKRN
VK-----TPTMHCFDD----------------------------------
AQKIVYG------------------LMERDSYPRFLRSDIYRTLLESLAA
DAT-----------------------------------K-----G
*
>P1;ENSTNIG00000012338

A-------------------------------------------------
-------------------------------------FSPSRLSLEDTQQ
WSQSLERLLESKYGLATFRNFLK-SEYSDENIEFWL--------------
TCEDYKKIKSSFRMSSRAKKIYEQFIKVESPKEINID-------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------YHTREQIKRN
VK-----TPTLHCFDD----------------------------------
AQKIVYG------------------LMERDSYPRFLRSDIYRTLLENLAA
DAA-----------------------------------------K
*
>P1;ENSLOCG00000009076

MAMSL-----IQACR-SLALSTWLLSFC--------F--------VHLLC
LDFTVAEKEEWYTAFVNITYLD-PA--------------TSEIKTEKTEC
GRYGEHSLKQDAKGVVVMPSSLHDRQACDPNTKFTVPPNANTWIALITRG
NCTFKEKIRHAANQNASAVVIFNVG-SGNANETITMPHPGTGDIVAIMIP
EPKGREIMSLLEKNVTVMMYITIGTRNLQKYVSRTSVVFVSISFIVLMII
SLAWLVFYYIQRFRYANARDRNQRRLGDAAKKAISKLQVRTIKKGDKETE
SDFDNCAVCIEGYKPNDVVRILPCRRHLFHKNCVDPWLQDHRTCPMCKMN
ILKALGIPPNADCSDEILPDYEVSIGGPPTNQVTGASDVTVNESSVVLDP
AVRTV-GLPQVFRDSELLPPAGESNIATRSEQEPTVSSDSDTSLIISVEV
GLSDV----------------------ELSTDQDCEETKTRKNAM
*
