>P1;ENSTNIG00000016719

--------------------------------------------------
-----MAFFVKKKKFKFQTH------------------------------
----LTLEE--LTAVPFVNGVLFCKLRLLE-GDFVATSSR-EEVQENCVR
-----------WRKR-FSFVSKMSA-------------------------
-NPHTGVLDPS--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYTKLGFTDLNMAEFAG-SGSTVRCCLL
EGYDTKNTRQDNSILKVIIGMTLLSGDPCFKTPPSTAKSISVPGREHALQ
LDCKGEGTTQ----------PG-PAG---GV-SLG-RSAKPRPSIV----
-SS-G---------------------------------------------
-------LL--------------------------EDSE--VN-QPGPAD
VFQSGHSRN-SSYASQQSKISG-----------YSTEHSCSSSLSDLT-H
R-----R-NTSTGSS-TSGGLAF--NADTPPEGEK----D--AGRPERPP
RPPASWLLSSSC----PRRKQDTVENHPSWVNDTRMDADDIVE------K
I--VQS----------QNF-------------------------------
-----EDINNTEDSNLRLFVSRDGTTALSG-IRLGN-RVSAGG---YEPV
V-IESH-----
*
>P1;ENSAMXG00000015583

--------------------------------------------------
-----MAFLMKKKKFKFQVH------------------------------
----FTLEE--LTAVPFINGMLFCKIRLLEGGDFAIASSR-QEVQENCVR
-----------WRKK-FSFVCKMSA-------------------------
-NPTTGVLDPC--I--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAFSKLGFADLNMAEFAG-SGSTVRCCIL
EGYDTKNTRQDNSILKVTIGMTLLSGDPCFKTPPSTAKTTAFAGQDPSLQ
LDCKGEGTAD---------KPTAPAGFNPGI-TTS-RSLKSRAPAP----
-CS-G---------------------------------------------
-------LP--------------------------EVLD--EN-LSSPDE
VFHTGHSRN-SSYASQQSKVS-----------GYSTEHSRSSSLTDLSQH
R-----R-NTSTSSSNTSAGAVA--AAESPPEPEK----E--PVKQEKPP
RPPRPAILPNRP----SRRKKDSVENHPTWVDDTRIDADDIVE------K
I--VQS----------QNF-------------------------------
-----ADVSNNEDSNLRLFVSRDGTTALGG-IQLGN-RVSAGV---FEPV
V-IESH-----
*
>P1;ENSGACG00000014808

--------------------------------------------------
-----MAFFAKKKKFKFQTQ------------------------------
----LTLEE--LSAVPFVNGVLFCKIRLLD-GDFVATSSR-HEVHENCVR
-----------WRKR-FSFVSKMSA-------------------------
-NPHTGVLDPS--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYSKLGFTDLNMAEFAG-SGSTVRCCLL
EGYDTKNTRQDNSILKVTIGMTLLSGDPCFKTPQSTAKCISIPGREHTLQ
LDCKGEGTAQ----------PG-PAG---GV-SLG-RASKPRPSIV----
-GS-G---------------------------------------------
-------LL--------------------------EESQ--SS-PLGAA-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------
*
>P1;ENSAMXG00000012124

MHIQCLASLSNFLSEFLLYGRPRVCMCVLFCVCVTHTHTHTHFIRAVGSA
EALQSMAFLVKKKKFKFQTH------------------------------
----FTLEE--LTAVPFVNGVLFCKIRLLDGGDFATSSSR-EEVQENSVR
-----------WRKR-FSFVCKMSA-------------------------
-NPNTGVLDPC--I--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYSKLGFADLNMAEFAG-SGSTVRCSLL
EGYNTKNTRQDNSILKVTIEMTLLSADPCFKAPPSTAKSISVPGREPSLH
LDRKGEGTAV------------------------G-SASKPRPSIL----
-SS-G---------------------------------------------
-------LP--------------------------EEGD--QS-RANADE
TFHTGHSRN-SSYASQQSKLSG-----------VCSGVVCVCVCVC----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------V----
*
>P1;ENSDARG00000016866

--------------------------------------------------
-----MAFLMKKKKFKFQIH------------------------------
----FTLEE--LTAVPFVNGMLFCKIRLLDGGDFSISSSR-QEVQENCVR
-----------WRKK-FSFVCKMSA-------------------------
-SPATGVLDPC--I--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAFSKLGFADLNLAEFAG-SGSTVRCCIL
EGYDTKNTRQDNSILKVTIGMTLLSGDPCFKTPVSTAKTIAMAGQDPSLQ
LDRKGEGTAD---------HP-VPTL---SR-NTR-RSIKSRTPLN----
-NSGG---------------------------------------------
-------LQ--------------------------EGLE--EN-LSSPDE
VFHNGHSRN-SSFASQQSKISGGIQGTNKRISGCSAEHSHSSSLTDLSQH
R-----R-NTSTSSSNTSGGTST--TVESPADQEK----E--LLKPERPP
RPPRPTLPLNRL----SRRKKDSVENHPTWVDDTRIDADDIVE------K
I--VQS----------QNF-------------------------------
-----ADVSNNEDSNLTLFISRDGTTALSG-IQLVN-RVSAGV---FEPV
V-IESH-----
*
>P1;ENSXMAG00000002891

--------------------------------------------------
-----MAFFVKKKKFKFQTQ------------------------------
----LTLEE--LTAVPFVNGVLFCKLRLLD-GDFVATSSR-EEVHENCVR
-----------WRKR-FTFVSKMSA-------------------------
-NPHTGVLDPS--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYSKLGFTDLNMAEFAG-SGSTVRCCLL
EGYDTKNTRQDNSILKVIIGMTLLSGDPCFKTAPSTAKSISIPGREHTLQ
LDCKGEGTAE---------GTG-PAG---GV-SLG-RASKPRPSII----
-SS-G---------------------------------------------
-------LL--------------------------DDSEPNQN-QSGPGE
VFQSGHSRN-SSYASQQSKISG-----------YSTEHSCSSSLSDLT-H
R-----R-NTSTGSS-ASGGLCF--TTDPPPEGDK----D--AGRPERPP
RPPRPVLPPNRP----LRRKQDSVESHPTWVNDTRIDADDIVE------K
I--VQS----------QNF-------------------------------
-----ADINNTEDSNLRLFVSRDGTTALSS-IRLGN-RVSAGG---YEPV
V-IESH-----
*
>P1;ENSDARG00000102566

--------------------------------------------------
-----MAFLVKKKKFKFQTH------------------------------
----VTLEE--LTAVPFVNGVLFCKIRLLDGGDFTASSSR-EEVHQNCVR
-----------WRKR-FSFVCKMSA-------------------------
-NSNTGVLDPC--M--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYSKLGFADLNMAEFAG-SGWTARCCLL
EGYDTKNTRQDNSILKVTIGMTLLSGDPCFKTPPSTAKCISVAGQDPSLQ
LDCKGEGTAE----------VL------------P-RMAKQRPSIL----
-GS-GSNPARPSATAKTHSGPGDTLVRSEVLISKRNPHRLTQKGSEAKRM
ASAGFRSLP--------------------------EEAD--QS--QSPDE
SFHTGHSRN-SSYASQQSKLSG-----------YSTELSCSSSLSDLT-H
R-----R-NTSTGSS-VSA--------DAPSESD---------SRPDRPP
RPPRPILPSSRP----PR--------------------------------
------------------F-------------------------------
-----FPCVCSGGSRIQWRISRRGSTTRAS-MQTTSWRRSCRARTSLTSV
I-MKIVT----
*
>P1;ENSGACG00000018460

--------------------------------------------------
-----MSFLMKKKRFKFQVH------------------------------
----FTLEE--LTAVPFVNGVLFCKIRLIHGGDFAILSSR-EEVQQNCVR
-----------WRKK-FSFVCKMSA-------------------------
-SPNTGVLDPC--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKSFSKLGFADLNIAEFAG-SGSTVRCCIL
EGYDTKNIRQDNSILKVTIETTLLSGDPCFKTLPCTTTSVLVG--DPTLQ
LDCKGESTDS---------TMQ-TLG---GI-FEGPGAFKPKQSSV----
RSS-G---------------------------------------------
-------LP--------------------------EEGR---S-VCSPDE
VFHTAHFRS-SSSASQHSKISG-----------YSTAHSRCSSLTDLS-H
E-----R-NASSSSS-VSCGLAP--PSQIPPSTPTELQPHGTPTRPGRPP
LPSAAALMTNRS----SRRKKESVEKQPSCVDDTRIDADDIVD------K
I--VQS----------QNF-------------------------------
-----SDSSNNEDSNLRLFVCKDGTTALSG-TQLSN-RGTAGV---FEPV
V-IETH-----
*
>P1;ENSONIG00000012588

--------------------------------------------------
-----MAFLMKKKKFKFQVH------------------------------
----FTLEE--LTAVPFVNGVLFCKIRLIDGGDFAILSSR-EEVQQNSVR
-----------WRKK-FSFVCKMSA-------------------------
-NPISGVLDPC--I--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAFSKLGFADLNISEFAG-SGSTVRCCIL
EGYDTKNTRQDNSILKVTIGMTLLSGDPCFKTPPSTAKSISIGDEDPNLQ
LDCKGESTDA---------TLQ-PPG---GI-VEGPRSFKPRQSSV----
RSS-G---------------------------------------------
-------LP--------------------------EEGG---S-VSSPDE
VFQIGHFRS-SSYASQHSKISG-----------YSTGHSRCSSLNDLS-H
H-----R-NASSSSG-ASCGLGH--PSQPPPSTPTEPHHQATLTKPERPP
PPSAAAILSNRSSSPTNRRKKEPVERQPSCVDDTRIDADAIVD------T
I--VKS----------QDF-------------------------------
------DSSNNEDSNLRLFISKDGTTALSG-THLAN-RVTPGI---FEPV
V-IETH-----
*
>P1;ENSONIG00000013986

--------------------------------------------------
-----MAFFVKKKKFKFQTH------------------------------
----LTLEE--LTAVPFVNGVLFCKLRLLD-GDFVATSSR-EEVHNHCVR
-----------WRKR-FTFVSKMSA-------------------------
-NPHTGVLDPS--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYTKLGFTDLNMAEFAG-SGSTVRCCLL
EGYDTKNTRQDNSILKVIIGMTLLSGDPCFKTPQSTAKSISIPGQEHTLQ
LDCKGEGTAE----------TG-PPG---GV-SLG-RASKHRPSII----
-SS-G---------------------------------------------
-------LL--------------------------EESE--VN-QSVPAE
AFQSGHSRN-SSYASQHSKISG-----------YSTEHSCSSSLSDLT-H
R-----R-NTSTGSS-TSGGLCF--TVDTPPDGDK----D--AGRPERPP
RPPRPVLPPNRP----PRRKQDSVESHPSWVNDTRMDADDIVE------K
I--VQS----------QNF-------------------------------
-----ADISHTEDSNLRLFVSRDGTTALSG-IRLGN-GVPAGG---YEPV
V-IESH-----
*
>P1;ENSXMAG00000003827

--------------------------------------------------
-----MAFLIKKKKFKFQVH------------------------------
----FVLEE--LAAVPFVNGVLFCKVRLVDGGDFSISSSR-EEVQQNCVR
-----------WGKK-FSFVCKMSA-------------------------
-SPVTGVLDPC--I--------------------------CR--------
--------------------------------------------------
-----------VSVRKEQKGGKAYSKLGFADLNISEFAG-SGSTVRCCIL
EGYDTKNTRQDNSILKVTIGMTLLSGDPCFKTPPSTAKSVLIGVEDPNLQ
LACKGDSTAS---------L-Q-PPG---GM-VEGPGAVKPRQSSVR--G
LAS-G---------------------------------------------
-------LP--------------------------EHAD---G-LHSPDD
VFLTRHVRS----ASQHSKISGL--------FIHSANHANCWSLTSLT-E
Q-----T-FQQNASL-FFHDYCK--ST-FPLSSTATARETG--SRSDQD-
EIPIGILHGRQH----YRRKKDTVERQRSCVDDTRIDADDIVE------K
I--VQS----------QNF-------------------------------
-----SAGSSDEDSHLRLFVSKDGTTALSG-TQIAT-RGTPGV---FEPV
V-IETH-----
*
>P1;ENSTRUG00000004766

--------------------------------------------------
-----MAFFVKKKKFKFQTH------------------------------
----LTLEE--LTAVPFVNGVLFCKLRLLE-GDFVATSSR-EEVQENCVR
-----------WRKR-FSFVSKMSA-------------------------
-NPHTGVLDPS--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYSKLGFTDLNMAEFAG-SGSTVRCCLL
EGYDTKNTRQDNSILKVIIGMTLLSGDPCFKTPPSTAKSISIPGQEHTLQ
LDCKGEGTTE----------PG-LAG---GV-SLG-RSAKPRPSIINSAV
VPS-G---------------------------------------------
-------LL--------------------------EDSE--AN-HPGPAE
AFQSGHSRN-SSYASQQSKISG-----------YSTEHSCSSSLSDLT-H
R-----R-NTSTGSS-TSGGLAF--NPDTPTESEK----D--AGRPERPP
RPPRPVLLLNRP----SRRKQDSVENHPSWVNDTRMDADDIVE------K
I--VQS----------QNF-------------------------------
-----ADINNTEDSNLRLFVSRDGTTALSG-IRLGN-RVSAGG---YEPV
V-IESH-----
*
>P1;ENSORLG00000017754

--------------------------------------------------
-----MAFFVKKKKFKFQTQ------------------------------
----LTLEE--LTAVPFVNGVLFCKLRLLD-GDFVATSSR-EEVQENCVC
-----------WRKR-FTFVSKMSA-------------------------
-NPHTGVLDPS--V--------------------------CR--------
--------------------------------------------------
-----------VSVRKELKGGKAYMKLGFTDLNMAEFAG-SGSTIRCCLL
EGYDTKNTRQDNSILKVIIGMTLLSGDPCFKRSPEVMRSVSFFFQVSMFL
CSIKGA--AK----------PG-VSA---ETDCLI-RQRNPKHS------
-PP-G---------------------------------------------
-------LL--------------------------DETEGNQN-QSSSTE
AFQSGHSRN-SSYASQHSKISG-----------YSTEHSCSSSLSDLT-H
R-----R-NTSTGSS-ASGGLGF--TADPPLEGEK----D--AGRPEPPN
RPPSVL-----H----FRRKQEAVENRPSWVNDTRMDADDIVE------K
I--VQS----------QNF-------------------------------
-----ADINNSEDSNLRLFVSRDGTTALSG-IRLGN-RVPAGG---YEPV
V-IESH-----
*
>P1;ENSLOCG00000002196

--------------------------------------------------
-----MLGFLARAMAKQAARKPAALVSPVSVTRIPGRYLAHQEGLPKLPV
PPLRQTLERYLLALRPVVSAEELEHTRGLV-EDFQRPGGVGERLQRGLER
RARKMENWLSDWWLQTAYLEYRMPVVIHSSPGVVLPRAEFHDRQGQIRFA
AKLIAGVLDFKTMIDNETLPVEYLGGKPLCMNQYYQVLSSCRIPDPKRDS
VVNYARSKKPPTHITVVHNFQFFVLDVYNSDGSPLTVDQIYIQLEKIWNS
SLQTNKEPIGILTSQHRNTWGKAYNNLIKDKTNKESVRAIQKSIFTVC--
--LDAPKPRVSDELYRSRVGAQMLHGGGSRWNSGNR-------WFDKTLQ
FIIGEDGSCGLIYEHAPAEGPP-IVS---LV-DHV-VEYTKQSEMVRSPM
IPLP----------------------------------------------
-------APQKLRFNITPEIKKDIEKAKQNLNIMVQDLDVKVNVFSHFGK
NFPKSHKMSPDAFIQMALQLAY-----------YRTYHRCCSTYESAS-L
RMFRLGRTDTIR-ST-SVDSLNFVQAMDDPG-------------------
-----------------QQKQEKVALLDKAVKAHRAYTDMAIHGQAIDRH
LLGLRLQSIEDLTSMPEIFMDTSYAVALHFNLSTSQVPAKTDCVMCFGPV
VPDGYGVCYNPMDDHINFAVSAFNSCAETNAARLSQ-SLEEAL---LDMR
ALLEQAPRAKL
*
