>P1;ENSORLG00000015099

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSTRUG00000011714

--------MGK-------------------------VLAKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMKETIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------ADAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATSGDGLFEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSDARG00000052928

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSAMXG00000025290

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSORLG00000016131

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSONIG00000020807

-------KMGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSGACG00000012762

LANERPNTMGK-------------------------MISKIFGNKEMRIL
MLGLDAAGK----TTVLYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEAKQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYK--------
*
>P1;ENSTRUG00000018080

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIISDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATSGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSDARG00000101626

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSGACG00000007970

--------MGK-------------------------VLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSXMAG00000020342

-------KMGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAMILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSTNIG00000019582

--------MGK-------------------------VLAKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMKETIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------ADAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLFEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSONIG00000000864

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNCLD--------------------------------
--------------------------------------------------
-----------------------TWRQK---K-------
*
>P1;ENSAMXG00000025904

-------KMGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNYKS-------
*
>P1;ENSXMAG00000019478

--------MGK-------------------------MLSKIFGNKEMRIL
MLGLDAAGK----TTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWD
VGGQDKIRPLWRHYYTGT--------------------------------
-----QGLIFVVDCADR---------------------------------
-----------------------------------DRIDEARQE------
-LHRIINDREMRDAIILI--FANKQ-------------------------
--------------------------------------------------
-------DL-----------------------------------------
--------------------PDAMKPHEIQEKL-----------------
--------------------------------------------------
---GLTR---IRDRNWYVQPSCATTGDGLYEGL-----------------
--------------------------------------------------
-----------------------TWLTSNY---------
*
>P1;ENSLOCG00000011160

--------MATNMEVLAQQIVDTEQVAEVQTVQTSTPDSSVMSSSPQRIQ
IISADSAVTSPQRIQIVTDQQTGQKIQIVTAVDP--SSTSKQQFILATPD
GAGAGKVI-LASPETSNTKQLIFTTTDNIVPGRIQIVTDAASVERLLGKA
DVGRSQPVEYCVVCGDKASGRHYGAVSCEGCKGFFKRSVRKNLTYSCRSN
QDCIVNKHHRNRCQFCRLKKCLEMGMKMESVQSERKPIDLPREKPANCAA
STEKIYIRKDLRSPLIATPTFITEKDGSRSSLLDPGMLVNIQQPLIQADG
TLLLATDSKAESSQGDLGTLANVVTSLANLNESLNNGDASEMQQEDQSAS
EITRAFDTLAKALNPTDTTAVQNLTEGTDTGGGASIQVISRDQSTPIIEV
EGPLLTDTHVSFKLTMPSPMPEYLNVHYICESASRLLFLSMHWARSIPAF
QALGQDCNTSLVRACWNELFTLGLAQCAQVMSLSTILAAIVNHLQNSIQD
DKLSGDRIKLVMEHIWKLQEFCNSMAKLEIDGYEYAYLKAIVLFSPDHPG
LSSTSQIEKFQEKAQMELQDYVQKTYPDDTYRLARILMRLPALRLMSSGI
TEELFFTGLIGNVPIDSIIPYILKMETAEYNSQITGTSA
*
