>P1;ENSDARG00000037042

MSACQDKSSLSCSESRE-NVSGSEWGRMDDGCASCFND-PTGDAIHGGMD
AVQPGITLDGHLP-------LPPGQLMLGLVEEGFAGYHSHLGSDP----
-----DTD---YLDIP---GDPNYSE-SD----GNV-ATKKRNRS--NSS
RHRG-EVVT--ELGPEEVRWFYKEDKRTWKPFVGHDSLK-------IELA
YRKYCE-LNPEEV--KRRD-AT-EEAEDLF----ES---SSGCEEPAVRR
QSA-AV-AAQPV------------P-DSADA-------G-C-SADDSV-F
RSDSVNV--------DAVCVRGGLYEVDIKGKSCYPVYWNQQ-----DHI
PVMRGQWFTDGTWLP-L------------EEEDSDLIELEHLACFRGQQM
KDTFDTEAVATTVDSKD--------------------------------A
IHSLKLSRSHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEAALEDTPPETTHIVFVVHGIGQKMDQGRIIRNTSMMRDAARK
MEEKHFSDRINEHVEFLPVEWRSKLALDGDTVDSITPDKV----------
---R---GLRDMLNSSAMDIMYY-TSPLYRDEITRGLTKELNRLYMLFCE
RNPEFAEK-GKVSIV-------SHSLGCV----I--------TFDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFVHED-----------------------
--------------------------------------------------
---------------------------------------VPDV-MEAD--
-VSRQERQLLEELRLTYLRIRDLEDRLQ--------------NFQTSSSR
PSP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---VRPGSGGTQDHILP--TSICQRLFNIFHPTDPVAYRLEP
LILKHYSNI--T-PVQIHWY---NTTSPTPYDQIRPTLLNPSKENASVSD
TESLPSPCTSPPQ------PRRHYSESITNLGKASIMGAASIGKGIGGIL
---FSRFSRSSGQVGGVEEETSDSEG--------------GTC-EKGDEN
RSVDLDDKPDEKTEEKIEEKTGDTSM---SQSA------S-TIMDYSS--
-----------------------------------------LELEKRIDF
---------------------ELREGLVESRYWSAVTSHTAYWCSHDVAL
FLLTF---------------------------------------------
--------------------------LYRPNEANDMA-------------
--------------------------------------EDNLE---S
*
>P1;ENSTNIG00000017233

--------------------------------------------------
--------------------------------------------------
---------------------------------GPLFERRKRTRS--NSS
RHHFSDVVT--ELGPEEVRWFYKEDKKNWKPFVGHDSLK-------IEIM
FRKYCE-LNCVAA--ASRG-GC-SEE-ESD---------DPGGESRGL--
-NG-AA-PPETA------------AG-GGDRRQGSLDTSSV-ALDEGN-H
VGVEINV--------EPVCVRGGLYEVDIKERECKPVYWMQQ-----DHI
PVMRGQWFIDGSWLP-L------------EEEESDLIEQEHLNHFRGQQI
QDTFETDLIVKTVDSKD--------------------------------A
IHSLKLSRTHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASPEDRPPQTTHVVFVVHGIGQKMDQGRIIKNTGMLRECVRK
MEEKHFLDHNEEHVEFLPVEWRSKLQLDGDTVDSITPDKV----------
---R---GLRDLLNSSAMDIMYY-NSPLYRDEITRGLTQELNRLYMLFCS
RNPEFEERGGKVSIV-------SHSLGCV----I--------TYDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLQE-----------------------
--------------------------------------------------
---------------------------------------HQAVEEQLELH
WMSYEEQRLLEQLRLTRTRLRELENQLL--------------TLEASKPS
TPP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGSSCHQDHILP--TTICSRLFNVFHPTDPVAYRLEP
LILKHYSNI--A-PIQIHWYKKCSASNPTPYDEIRPTYLNPVKDP--TSD
TESIPSPSTSPVL------ARRHYGESITSLGKASILGAASIGKGIGGIL
---FSRFSRSNSQPS------------------VSSGLEGGAAAE-EEEP
KQTES------------QSAYGLSTI---TRPT------S-PTAD-T---
----------------------------------------SLELEQRMDF
---------------------ELREGLVESRYWSAVTSHTGYWCSHDIAL
FLLTF---------------------------------------------
--------------------------IYKQKTLSSEAA------------
--------------------------------------TDMSE---P
*
>P1;ENSORLG00000015417

SS--------------------SEWDMANDVFVTGYDD-------HASGE
VFDSGLCSDGHLP-------LRRADS------EPLSQDCLMLGLPG----
-----P-D---YPDPSFLNIEPDFTD-AE----RNL--SERRILS--NSS
RHRG-EIVT--ELGPEEIRWFYKEDKRTWKPFAGTDSLK-------IERL
YRRRTEQLDPGSD--P-AG-GD-GE-QN----------------------
--------------------------------------P-V-PEEVK---
SPSDVKA--------EAVCVRGGLYEVHIREKECCPVYWNQQ-----ESI
PVMRGQWFVDGTWLP-L------------EEEDSNPIEMEHLSHFRGQQM
RDVSEVETAPSTVDSKD--------------------------------A
VYSLKLSRSHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LRRGYFEEAVPEETPSETTHIVFVVHGIGQKMDQGRIIRNTSMMRDAARK
MEERHFPDRTTEHVEFLPVEWRSKLYLDGDTVDSITPDKV----------
---R---GIRDMLNSSAMDIMYY-TSPLYRDEITRGLTQELNRLYSLFCS
RNPDFEKN-GKVSIV-------AHSLGCV----I--------TFDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFHHQQ-----------------------
--------------------------------------------------
---------------------------------------MLDP-EKTKIR
WPSEEERQLQEQLRVLRLRLRDLEDQFR--------------GLQTSSSV
AVP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGNNTMQDHILS--TSICKRLFNLFHPTDPVAYRLEP
LILKHYSNI--A-PVQIDWY---NTTSPTLYNQIRPTRLNLMKDTSFVSE
AELITSPCTSPPQ------TKRPYGESITSLGKASIMGAASIGKGIGGIL
---FSRFSRSSGQVGGVEEEPSDSEGGVCEVENLVSGENGEVAVESGETE
KQAEE------------EVEDGEPSI---PQST------S-VAVDNSS--
-----------------------------------------LELERRIDF
---------------------ELREGLVENRYWSAVTSHTAYWCSYDVAL
FLLTF---------------------------------------------
--------------------------MYRPQELPESV-------------
--------------------------------------EDHQD---A
*
>P1;ENSONIG00000001652

--------------------------------------------------
--------------------------------------------------
------------------------------------------------SS
RHRG-DIVT--ELGPEEVRWFYKEDKRTWKPFVGHDSLK-------IEII
YRRLVD-QNQDKA--VDPN-EA-DEKETAG---------SSELQ-PESSA
VDSASF-RAEPA------------V-QQL---------S-V-SEQITEPV
HNGGTSV--------EAVCVRGGLYEVDIKEKECYPVYWNQQ-----DRI
PVMRGQWFIDGTWLP-L------------EEDESDLIEQEHLLCFRGQQM
RDTYEIEAVTTTVDSKD--------------------------------A
IHSLKLNRSHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEAAPEDTPPETTHIVFVVHGIGQKMDQGRIIRNTSMMRDAARK
MEEKHFSDRTTEHVEFLPVEWRSKLCLDGDTVDSITPDKV----------
---R---GLRDMLNSSAMDIMYY-TSPLYRDEITRGLTLELNRLYSLFCS
RNPDFEKN-GKVSIV-------SHSLGCV----I--------TFDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVHFHHPE-----------------------
--------------------------------------------------
---------------------------------------ALDP-EDTRLH
WPTDEKHHLQEQLRLTRLRLRDLEDQFQ--------------GLQTSSCV
PVP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGNNGMQDHILP--KSICNRLFNIFHPTDPVVTNHNN
SRLKALYIVSKD-PTTIQR---------NPNNQITPYKKKTAAEQG-SGR
GGHLPRPVVVRIK------KQKHLKLNISLKFKGKITCAASLGKGIGGIL
---FSRFSRSSGQRANRS---------------------------TEYSI
TITRK------------SSAYPGS-S---RRCTMTIKGYS-ILFFDEK--
-----------------------------------------VELERRIDF
---------------------ELREGLVESRYWSAVTSHTAYWCSYDVAL
FLLTF---------------------------------------------
--------------------------MYRQHELPEPA-------------
--------------------------------------EDNSDT--T
*
>P1;ENSAMXG00000014813

MQAVQA-----------------------------------------G--
-------VERHLP-------PLLRSR-------HRAVDGVTPGLDDQYTG
YPSPSSANEDDGAASDH----LLYSE-SDGN-VSPL-ESRKRARSGAASS
RHRL-EVVT--ELGAEELRWFYKEDKKTWKPFAGHDSLK-------IELM
YRKFCE-LNPVEL--DQDHNEDQHQD-QEGASAALSEEGEHAAEVMDR--
-VG-TC-GPGSA------------AG-QVEEG-ASVETP-E-SAGES--D
VDVSISV--------EAVCVRGGLYQVDVREKECYPVYWNQQ-----DRI
PVMRGQWFIDGTWMP-M------------EEDESDLIEREHLTSFRGQQM
QDSFENDVVVKTVDTKD--------------------------------A
IHSLKLSRSHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASLEDKPPQTTHIVFVVHGIGQKMDKDRIIKNTGMLREAVRK
MEEKHFADHTEEHVEFLPVEWRSKLALDGDTVDSITPDKV----------
---R---GLRDLLNSSAMDIMYY-TSPLYRDEITKGLTQELNRLYALFCS
RNPEFEEKGGKVSII-------SHSLGCV----I--------AYDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLLE-----------------------
--------------------------------------------------
---------------------------------------QQEPDE-EEMR
WMSYEERHLLEQVHLTRQRLRELEDKLQ--------------GLEASKPL
QLP------ALKFKVENYFCMGSPLA------------------------
-VFLALRG---IRPGSTGYQDHIMP--KSICKRLFNIFHPTDPVAYRLEP
LVLKHYSNI--A-PVQIHWC---NTTSPTPYDEMKPTFLNPVKDP--VSD
TESLPSPSTSPVM------NRRHYGESITNLGKASLLGAASIGKGIGGML
---FSRFSRSSSQPS---------------------GVDSGVVET-E---
--EKS------------QSAYGLSTM---SQST------S-TIID-T---
----------------------------------------AVEMEHRIDF
---------------------ELREGLVESRYWSAVTSHTAYWTSHDVAL
FLLTF---------------------------------------------
--------------------------IYKSQSSSQAS-------------
--------------------------------------EDSLDP--E
*
>P1;ENSGACG00000005668

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-DTYEMEVVTTTVDSKD--------------------------------A
IDSLKLSRSHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEAAPEDTPPETTHIVFVVHGIGQKMDQGRIIRNTSMMRDAARK
MEEKHFSNHTTEHVEFFPVEWRSKLSLDGDTVDSITPDKV----------
---R---GLREMLNGSAMDIMYY-TSPLYRDEITRGLTLELNRLYTLFCS
RNPDFEKN-GKVSIV-------SHSLGCV----I--------TFDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFHHEA-----------------------
--------------------------------------------------
---------------------------------------ELDP-EETKVR
WPSDEERHLQEQLRVTRLRLRDLENQFQ--------------GLRTSIC-
EVP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGNNGVQDHILP--TSICKRLFNIFHPTDPVAYRLEP
LILKHYNRI--A-PVQIHWY---NTTSPTRYDEIRQTLLNPS-----LSD
SESIPSPCTSPTQ------ARRHYGESITSLGKASIMGAASLGKGIGGIL
---FSRFSRSGGQVG-VD-------A-------------GAAVAEIEEEE
KELEQ------------GRAEVEPAL---YQSA------S-AVLENTS--
-----------------------------------------MELERRIDF
---------------------ELREGLVESRYWSAVTSHTAYWCSYDVAL
FLLTF---------------------------------------------
--------------------------MYRPQEPFEPA-------------
--------------------------------------EDNLEMLSP
*
>P1;ENSXMAG00000009680

------------------------------------------------MS
SVQPG--LDGHLP-------LIRAQD-------HGSQDGIFLELGS----
-----PED---YLDSSP----LEYRD-SDGNGVGPLFERRKRSRS--NSS
RHRFNEVVS--ELVPEEVRWFYKEDKKTWKPFIGHDSLK-------IELM
FRKYCE-LNPGAI--RSGV-GD-GEE-ETG---------GKCVDSPGQ--
-NG-AV-PVDTG------------TS-SVDEGRGSLDTSTV-SFDGTD-P
ECTEINV--------ERVCVRGGLYEVDIKERKCYPVYWKQQ-----DHI
SVMRGQWFIDGSWLP-L------------EEEESDLIEQEHLNHFRGQHL
QDTFETDLVVKTVDSKD--------------------------------A
IHHLKLSRTHVDWHSVEEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASPEDRPPQTTHVVFVVHGIGQKMDQGRIIKNTGMLREGVRK
MEEKHFSEHNDEHVEFLPVEWRSKLALDGDTVDSITPDKV----------
---R---GLRDLLNSSAMDIMYY-NSPLYRDEITKGLTEELNRLYSLFCS
RNPDFEERGGKVSIV-------SHSLGCV----I--------TYDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLQE-----------------------
--------------------------------------------------
---------------------------------------HCAVEEEQDFR
WMSYEERQLLEELRLTKNRLRELENQLV--------------KLEASNPS
APP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGTSGHQNHILP--TSICSRLFNVFHPTDPVAYRLEP
LILKHYSNV--A-PVQIHW---CSATNPSSYDEVRPTFLNPVKDP--ASD
TESIPSPSTSPVL------ARKHYGESITSLGKASILGAASIGKGLGGIL
---FSRFSRSNSQPS------------------VSLGVEGGANAE-EEEE
KRTES------------QSSYGLSTI---TRPT------S-PTGD-A---
----------------------------------------LLELERRIDF
---------------------ELREGLVESRYWSAVTSHTGYWCSHDIAL
FLLTF---------------------------------------------
--------------------------IYRNEMP-FEIS------------
--------------------------------------PKMLQ---I
*
>P1;ENSORLG00000013291

SCLRKDSESPGVSAESS-NNNKKKWALGDDVFC-CHEMSFVDESVQAGMS
SVQSG--LEGHLP-------LLHR----------GAQSELLLDLNS----
-----PEA---YLDGSP----LDFAD-PDRNNGSPQFERRKRSRS--NSS
RHRFNEVVT--ELVPEEVRWFYKEDKKTWKPFLGHDSLK-------MELM
FRKYCE-LNPSCSAAVRRKVSG-ERR-ESG---------STGPESPEP--
-NG-AAVPGETA------------SC-SAREGRG--------SSDERD-P
DGIEINV--------EPVCVRGGLYEVDIKEKECFPVYWKQQ-----DHI
PVMRGQWFIDGTWLP-L------------EEEESDLIEEEHLNHFRGQQM
QDTIETDLVVKTVDSKD--------------------------------A
IHSLKLSRTHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASPEDRPPHTTHIVFVVHGIGQKMDQGRIIKNTGMLREGVRK
MEDKHFSKHKDEHVEFLPVEWRSKLTLDGDTVESITPDKV----------
---R---GLRDLLNSSAMDIMYY-NSPLYRDEITKGLTQELNRLYSLFCS
RNPEFEEKGGKVSIV-------AHSLGCV----I--------TYDIIT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLQE-----------------------
--------------------------------------------------
---------------------------------------HRAVEEETDLR
WMSYEEKQLLQQLKNTRSRLLDLENQLV--------------ALEASRPS
VPP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGISCHQDHILP--TSICSRLFNVFHPTDPVAYRLEP
LILKHYSNI--A-PVQIHW---SSATNPTPYDEIRPSFLNPVKDP--PSD
TESIPSPSTSPVL------LRKNYGESITSLGKASILGAASIGKGIGGIL
---FSRFSRSNSQPS------------------VSLGLEGGPNCE-EEEQ
SRTES------------QSAYGLSTM---IRPM------S-PTAD-TSC-
EFIRSSI-----------------------------RTLSPVELERRIDF
---------------------ELREGLVESRYWSTVTSHTGYWCSHDIAL
FLLTF---------------------------------------------
--------------------------IYKQKSTISAPL------------
--------------------------------------EDTPE---S
*
>P1;ENSDARG00000086808

MSALTKKTRFINNPGNKLSFGNRDWN---DAF-----FSLCDESIGRGMY
-------MERHPPHRDGMTLALRNPT-------RDALSGDHLDLSTT---
----SVAN---YLHNSN----TSYCTSPVSDCHGKA--LDIRKRS--CAP
RHRF-EVVT--ELGPEEVRWFYKEDKKTWKPFMGHDSLN-------IEIM
YRRFTQ-LNPGGS--VNQER-------------------------FGE--
-DG-A--P------------------------------------LER--R
ESVDAGV--------EAVCVRGGLYEVDVRSKECYPVYWNQQ-----ERI
PVMRGQWFTDATWAP-V------------EEDESELIEKEHLTCFRGQQI
QDNFDTDALAKTVDRKDVLSHFPPFYLPFLFKWSGYQTGAKSHKRKRCQA
IHSVQLSRSHVDWYSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASLDDKPPNTTHIVFVIHGIGQKMDKDRIIKNTGMLREAVRK
MEEKHYSEQTEEHVEFLPVEWRSKLALDGDTVESITPDKV----------
---R---GLRDLLNSSAMDIMYY-TSPLYRDEITKGLTQELNRLYSLFCS
RNPQFEGDGGKVSII-------SHSLGCV----I--------TFDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLQE-----------------------
--------------------------------------------------
---------------------------------------HHDQLEAEDSQ
WSSYEERHLLEEVQLTRQRLHELRDQLH--------------GLKESKPA
SFP------TLKFKVENFFCMGCPLA------------------------
-VFLALRG---IRPGNTGHQDHIMP--KSICRRLFNIFHPTDPVAYRLEP
LVLKHYSKI--A-PVQIHWC---NTINPTPYDEIRPTYLSTSKDT--ASD
MENGSSPSTSPVL------ARRHYGESITNLGKASILGAASLGKGIGGIL
---FSHFSRSPSLPS---------------------AVDSGMGDS-----
--EDS------------QSTFTFSAI---PPSS------SSSLFD-A---
----------------------------------------TVEMEHRIDF
---------------------ELREGMVESRYWSAVTSHTAYWTSHDVAL
FLLTF---------------------------------------------
--------------------------IYKQQSTEQTE-------------
--------------------------------------T-STA---M
*
>P1;ENSONIG00000001367

MS-------------------------------------LADETLQAGMS
SVQSG--LEGQLP-------LLHARH-------HSAQGGLVLDLNS----
-----QED---YLSSSS----PEY-D-SYGNNTGPLFERRKRSRS--NSS
RHRFNEVVT--ELGPEEVRWFYKEDKKTWKPFLGHDSLN-------IELM
FRKYCE-LNPGAA--CPQA-SG-GED-ESG---------SRDLESRGM--
-NG-AV-PAETR------------TS-SVHGGRGSLDTSTV-SSDERD-A
ESIELNV--------ESVCVRGGLYQVDIIQRQCYPVYWKQQ-----DHI
PVMRGQWFIDGTWLP-L------------DEDESDLIEREHLNHFRGQHV
QDTFEMDLVPRTIDSKD--------------------------------A
IHSLKLSRSHVDWHSVDEIYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASPEDRPPQTTHIVFVVHGIGQKMDQGRIIKNTGMLREGVRK
MEEKHFSEHNEEHVEFLPVEWRSKLTLDGDTVDSITPDKV----------
---R---GLRDLLNSSAMDIMYY-NSPLYRDEITKGLTEELNKLYSLFCS
RNPEFEERGGKVSIV-------SHSLGCV----I--------TYDIIT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLQE-----------------------
--------------------------------------------------
---------------------------------------HRVVEEDLDLR
WMSYEERRLLEQQRQTRNRLQELENQLA--------------TLEAAKPS
APP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGTSVHQDHILP--TSICSRLFNVFHPTDPVAYRLEP
LILKHYSNI--A-PVQIHW---CSATNPTSYDEIRPTFLNPVKDP--TSD
TESIPSPSTSPVL------PRRHYGESITNLGKASILGAASIGKGIGGIL
---FSRFSRSNSQPS------------------VSLGLEGGASAE-EEEQ
KRTES------------QSAYGLSML---TRPT------S-PTAD-T---
----------------------------------------SLELERRIDF
---------------------ELREGLVESRYWSAVTSHTSYWCSHDIAL
FLLTF---------------------------------------------
--------------------------IYKQKATPSNP-------------
--------------------------------------ADTPDP--E
*
>P1;ENSAMXG00000009383

--------------------------------------------------
--------------------------------------------------
----------------------------------------RRSRA--GSS
RHRG-EVVT--ELGPEEVRWFYKEDKRTWKPFVGHDSLQ-------IELT
YRKLCE-LNPGKA--SEQD-EW-EELGG------------SGGDSEGV--
-EG-QK--GQTE------------ASVSKEV-------A-G-PAEEID-V
DSIDIGV--------EAVCVRGGLYEVDVKEKESYPVYWNQQ-----ERI
PVMRGQWFTDGTWLP-L------------EEEDSDLIELEHLSRFRGHQM
KDTFETEN--TAVDSKD--------------------------------A
IHSLKLSRSHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEAAPEDMPPAATHIVFVVHGIGQKMDQGRIIRNTSMMRDAARK
MEEKHFSDRTTEHVEFLPVEWRSKLSLDGDTVDSITPDKV----------
---R---GLRDMLNSSAMDIMYY-TSPLYRDEITRGLTKELNRLYTLFCS
RNPEFEEK-GKVSIV-------SHSLGCV----I--------TFDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFHHQE-----------------------
--------------------------------------------------
---------------------------------------APDA-METEQR
RRGCEEQRLLEELHLTRMRLRDLEDQFQ--------------GLKTSSSR
TSP------PLKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGNNGTQDHILP--RSICQRLLNIFHPTDPVAYRLEP
LILKHYSNI--S-PVQIHWY---NTSSPTPYDQIRPTLLNPLKESVSVSD
SESLPSPCTSPPQ------NRRHYGESITNLGKASIMGAASIGKGIGGIF
---FSRFSRSSGQEAE------------------------------EKME
----------DKVED--KREGSAGCM---SQST------S-TIMDNSTC-
EFPFSLHDTKAAALRHQNKFFQNPQTSSHGQGILQKMEGVLSQLDRRIDF
---------------------ELREGLVESRYWSAVTSHTAYWCSHDIAL
FLLTF---------------------------------------------
--------------------------MYGPNTPNETT-------------
--------------------------------------EDN-----L
*
>P1;ENSTRUG00000014479

--------------------------------------------------
--------------------------------------------------
---------------------------------------RKRTRS--NSS
RHHFSDVVT--ELGPEEVRWFYKEDKKNWKPFVGHDSLT-------IEIM
FRKYCE-LNCVEA--ASQG-GR-GVE-ESG---------DNGVESGGL--
-NG-AA-PPDTG------------AG-GVEG-PGR--------RGHVR-R
VPGGINV--------DPVCVRGGLYEVDIKERECKPVYWMQQ-----DHI
PVMRGQWFIDGSWLP-L------------EEEESDLIEQEHLNHFRGQQI
QDTFETDLIVKTVDSKD--------------------------------A
IHSLKLSRTHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGFVEEASPEDRPPQTTHVVFVVHGIGQKMDQGRIIKNTGMLRECGRK
MEEKHFLDHNDEHVEFLPVEWRSKLQLDGDTVDSITPDKV----------
---R---GLRDLLNSSAMDIMYY-NSPLYRDEITKGLTQELNRLYTLFCS
RNPEFEERGGKVSIV-------SHSLGCV----I--------TYDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCLQE-----------------------
--------------------------------------------------
---------------------------------------HQAVEEQLELH
WMSYEEQHLIEQLRQTRTRLRELENQLL--------------TLEASKPS
APP------ALKFKVENFFCMGSPLA------------------------
-VFLALRG---IRPGSSCHQDHILP--TTICSRLFNVFHPTDPVAYRLEP
LILKHYSNI--A-PIQIHW---CSASNPTPYDEIRPTYLNPVKDP--TSD
TESIPSPSTSPVL------TRRYYGESITSLGKASILGAASIGKGIGGIL
---FSRFSRSNSQPS------------------VSSGLEGGANVE-EEEP
KQAES------------QSAYGLSTI---TRPT------S-PTAD-TTQI
SFSERML---------------------------MPLFCLPVELERRIDF
---------------------ELREGLVESRYWSAVTSHTGYWCSHDIAL
FLLTF---------------------------------------------
--------------------------IYKQKTPSCDG-------------
----------------------------------------------A
*
>P1;ENSGACG00000010372

TSAVSSPLNADGSP-VN-NNINRDWALGGDAFSCCYEMSPMDDTMQAGMS
SVQSG--LDGHLP-------LLYAGN-------CGTQDGLMLDLNS----
-----PAA---FLD-------PDY-------SAGPLFERRKRSRS--NSS
RQRFNEVVT--ELGPEEVRWFYKEDKKTWKAFLGHDSLN-------IEHM
FRRYCE-RNPGAT--ADRVVDG-GEE-DRG---------NNGEEGRGL--
-NG-AV-SPEAR------------TG-SADG-------SAVSSSEVRD-P
DGIEINI--------EPVCVRGGLYEVDVKERECKPVYWKQQ-----DNI
PVIRGQWFIDGTWVL-L------------EEEESDLIEQEHLNRFRGQQM
QDTFETDMLVGTVDSKD--------------------------------A
IHHLKLSRTHVDWHSVDEVYLYSDATTSKIA-RTVTQKLGFSKASSSGTR
LHRGYVEEASPEDRPPQTTHIVFVVHGIGQKMDIGRIIKNTGMLREGVRK
MEEKHFSEHNGEHVEFLPVEWRSKLALDGDTVDSITPDKV----------
---R---GLRDLLNSSAMDIMYY-NSPLYRDEITKGLTQELNRLYTLFCY
RNPEFEERGGKVSIV-------SHSLGCV----I--------TYDIMT--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------GWDPVRFCQQE-----------------------
--------------------------------------------------
---------------------------------------HHAVEEELDLR
WMSYEEKHILEQLQLTRKRLQELESQLL--------------TLEASKPP
ARP------ALKFKIENFFCMGSPLA------------------------
-VFLALRG---IRPGISCHQDHILP--TSICGRFFNVFHPTDPVAYRLEP
LILKHYSNV--A-PVQIHW---CSAINPTHYDELRPTYLSPVKDP--PSD
TESIPSPSTSPVL------ARRHYGESITNLGKASIMGAASIGKGIGGIL
---FSRFSRSNSQPS------------------VSLGLEGGANAE-EEEQ
KRTES------------QSAYGLSTL---IRPT------S-PVTD-TSLV
QISDDVS-----------------------------ISVLAVELERRVDF
---------------------ELREGLVENRYWSAVTSHTGYWCSHDIAL
FLLTF---------------------------------------------
--------------------------IYKQKTTPSSPS------------
--------------------------------------GDTPE---T
*
>P1;ENSLOCG00000013516

MAAVLE--------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----SVLQRKVEASQAVRWIRNEQKNGAEALVSIGIQRKDFVPFLLNFL
REQACH-VLANG-PSTPAKTPGPQGTRTPS----------FLGDRRGC--
-RGPSK--GASRVQLFSPPPCGSPA-EQDPPGAHSL--S-G-ISALSSPS
FSSGWSPAPRPSAPERRSAQRASLGDFLLSPPEQQPAQRRGRRRSGGAGR
PAGRGQSEEQGRWDSPVGGAGRKSGGSKAEPPVSPQLNLNNLEDFPPVGA
SPASPVRTKPS---------------------------------------
---------------------------RRINPTPVSQERPLSKPKNCF--
-------TSTPVSKPPSPPSIPESPGAAPQRGTPNALQEERELLRRERSK
LAQQNFSPASP-------------------VLDPCTPTKPGSRASSHMQA
DPLASCADLCKVTFSSELDLLAQLYCTCVAENLVPSVILELFFVLQLLTS
RAPLPAKE-GKLSLGESDDVLDRHYLGTLHNCVFFAVRVLENQFELMSHL
DHDTLRLLAENERVALFSPALRDRLMDAHENSTAKVSPTLLPVILSVSFQ
PDTDNRSNFPNERAFHIFKKQRDIFYELLREWEDYHKEPEWEFDRVLGNR
IRAMVSQLTAAGNHSHFARLFQKQLLQMCKGPHLPGAGDEAPDADLLGML
GADNLSRLKRLQERLIQPQSIMGPCPPPSFPGHQEFFRDFLQAASSCQLN
QHLTDSLCQQILELDSIAILGPGCAKDEGEGDMEQQNEKLRFTSVLMTTR
LLAKFLGFITFLPYQTAETPSREIQESAVAIRNKSAPVLDVSSVLRRAVE
KQRTVLTVPWLVEFLSMVDYTTPFLLYYRAVFAMLLQVYRQMVLGRHGEM
TYLNRLLLVSVLGWLFQIPAFPEELFFGSEFEEGLKTMERSAASEG--LD
CLSLVDQHLLYTCCPYLSEFRKLLAAFVAGSTAKNGGIIRKITPTSAEPQ
QPPVPLSQQKLQAELEQAFFHNQPPSLRRTVEFVAERVGSNCVKHIKATL
VSELVQRGEAMLREGLSEDQASVLKLRDSICTQLCEKGR-----------
--------V--ALDCGRQFC---AAKGPEAIRVLLP--------------
-----EETSAAVLQTSKDITVRLATE------KACNWLSTNIAALIKREL
KSAFDRVTKAQSLSS------------------VP--GEGDMGAV-KEQL
PSVVS------------ETGATGSRCPAGCQHT------ARLPSD-L---
----------------------------------------IIEIKEVLSF
AFGPRTEEEQVGFLQLWDLLLGVREALHCGKFVSAVPEQMLARCTVLLAS
KLVSGELPLRSADLPETVSEPEADPVKGLLELLLNLWSQDFCTPAPLQLL
FTEYNMAAILRAGDTQRSHFLFLTKQLLKKGLLGQEEVAASWKRLLGQEE
EGVCWKELSDLSCPTDCKGKPEGVCTGSLLLSLTQQNHEDALQSTD-
*
