>P1;ENSTNIG00000013112

MGAVV-----G-TLT------MQT-----------------------KQ-
-------RR-PS-----------------------RDKIDDDLEMTMVCH
RPEGLEQLEAQTNFSKRELQVLYRGFKNECPSGVVNEDTFKQIYSQFFPH
G------------------------DASTYAHFLFNAFDSAHTGSIKFED
FVT-ALSILLRGSITEKLQWTFNLYDINRDGYINKEEMTDIVKAIYDMMG
KY-TYPVLKTD------A----PKQHVDAFFQ--------------KMDK
NRDGVVTLDEFILSCQEDENIMRSLQLFENVI------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSDARG00000102210

--------------------------------------------------
-----------------------------------------DLELSIVCH
RPEGLEQLEAQTNFNKKELQVLYRGFKQECPSGVVNEETFKQIYSQFFPH
G------------------------DASTYAHYLFNAFDSSHNGSIKFED
FVT-ALSILLRGTTTEKLEWTFNLYDINRDGYINKE--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSTRUG00000007648

MGAVV-----G-TLT------MQAKQ------------------------
-------RR-PS-----------------------RDKADDELEMTTVCH
RPEALDQLEAQTNFSKQELQILYRGFKNECPSGVVNEETFKHIYAQFFPH
GGCTEGC---------VA-DVMCAAYASMYAHYLFNAFDTANNGSIKFKD
FVT-GMSILLRGTVREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMG
KY-TYPALKGD------V----PQQHVDAFFQ--------------KMDK
NKDGVVTLEEFVIACQEDETMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSORLG00000010149

MGAVV-----G-TLT------MQTKQ------------------------
-------RR-PS-----------------------RDKTEDELEMTTVCH
RPEGLDQLEAQTNFTKQELQILYRGFKNECPSGVVNEETFKHIYAQFFPH
GGRFYFLCNFLLNDLFVNRLIAVVADASTYAHYLFNAFDTTNNGSIKFKD
FVM-GLSTLLRGTLREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMG
KY-TYPAIKGD------V----PQQHVDAFFQ-------------QKMDK
NKDGVVTLEEFVVACQEDETMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSGACG00000020318

MGAVV-----G-TLT------MQTKQ------------------------
-------RR-PS-----------------------RDKIDDELEMTTVCY
RPEGLDQLEAQTNFSKQELQILYRGFKNECPSGVVDEDTFKHIYAQFFPH
GA-----------------------DASMYAHYLFNAFDTTNNGSIKFKD
FVV-GLSTLLRGSMREKLEWTFYLYDINRDGYINREEMTEIVRAIYDMMG
KY-TYPALKGD------V----PQQHVDAFFQ--------------KMDK
NKDGVVTLEEFIMACQEDETMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSAMXG00000010139

MAGCTSRCRQG-VLK-----LIQSFQRLV--------------------S
-------GT-LT-----------------------KDKVDDELEMTMVCH
RPEGLEQLEAQTNFSKQELQVLYRGFKNECPSGVVNEETFKHIYAQFFPH
G------------------------DASTYAHYLFRAFDTTNNGSIKFEE
FVM-GLSTLLRGTVRDKLEWTFHLYDINRDGFISKEEMTDIVRAIYDMMG
KY-TYPALKGD------V----PKQHVDAFFQ--------------KMDK
NKDGVVTLEEFVLACQEDETMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSONIG00000001865

MGAVV-----G-TLT------MQTKQ-----------------------N
-------RR-PS-----------------------RDKTDDELEMTMVCH
RPEGLEQLEAQTNFTKQELQILYRGFKNECPSGVVNEETFKHIYAQFFPH
G------------------------DASMYAHYLFNAFDTANNGSIKFKD
FVM-GLSILLRGTLREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMG
KY-TYPALKGD------V----PQQHVDAFFQ--------------KMDK
NKDGVVTLEEFIVACQEDETMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSGACG00000017881

MGAVV-----G-TLT------MQTKTRRLSRGEKSLFVL-----TLSYAL
-------HT-DK-----------------------SDKADDDLEMTTVCH
RPEGLDQLEALTNFNKRELQVLYRGFKNECPSGIVSEETFKQIYAQFFPH
GA-----------------------DASTYAHYLFNAFDTAHSGSIKFED
FVT-ALSILLRGSITEKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMG
KY-TYPVLKNE------A----PKQHVEAFFL--------------KMDK
NRDGVVTLDEFILSCQEDENIMRSLQLFENVI------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSDARG00000034808

MGVVL-----G-TFS------MHTKQ------------------------
-------VS-YR-----------------------TDKVDDELEMTMVCH
RPEGLEQLEAQTNFSKQELQVLYRGFKNECPSGVVNEDTFKHIYAQFFPH
G------------------------DASTYAHYLFHAFDTRNNGSIKFED
FVM-GLSTLLRGTVRDKLEWTFHLYDINKDGFINKEEMTEIVRAIYDMMG
KY-TYPALKGD------V----PKAHVDAFFE--------------KMDK
NKDGVVTLEEFVLACQEDENMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSXMAG00000011426

MEGEE-----QRDNS------LQTIAIVL-LCCG-AAKL-----LHLLG-
-------VI-AV-----------------------EDKADDDLEMTIVCH
RPEGLDQLEAQTNFSKRELQVLYRGFKNECPSGVVNEETFKQIYSQFFPH
G------------------------DASTYAHYLFNAFDTGHTGSIKFED
FVT-ALSILLRGSVTEKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMG
KY-TYPVLKTD------A----PKQHVDAFFQ--------------KMDK
NRDGVVTLDEFIFSCQEDENIMRSLQLFENVI------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSTNIG00000010772

MGAVV-----G-TLT------MQAKQ------------------------
-------RR-PS-----------------------RDKVDDELEMTTVCH
RPEGLEQLEAQTNFSKQELQILYRGFKNECPSGVVNEETFKHIYAQFFPH
GD------------------------ASMYAHYLFNAFDTSNNGSIKFKD
FVT-GLSILLRGTVREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMG
KY-TYPALKGD------V----PQQHVDAFFQ--------------KMDK
NKDGVVTLEEFIIACQEDETMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSTRUG00000010568

RMERE-----QRDNS------LHTIVIIL-LCCT-AVKL-----LHLLGV
-------IS-VE-----------------------ADKIDDDLEMTMVCH
RPEGLEQLEALTNFSKRELQVLYRGFKNECPSGVVNEDTFKQIYSQFFPH
G------------------------DASTYAHFLFNAFDSAHTGSIKFED
FVT-ALSILLRGSITEKLQWTFNLYDINRDGYINKEEMTDIVKAIYDMMG
KY-TYPVLKTD------A----PKQQVDAFFQ--------------KMDK
NRDGVVTLDEFILSCQEDENIMRSLQLFENVI------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSORLG00000003933

MEGEE-----QSENT------LQTIVIVL-LGCL-AVKM-----LHLLGV
-------IT-VK-----------------------VDNADDDFEMTVVCH
RPEGLDKLEAQTNFNKRELQVLYRGFKNECPSGAVNEDTFKQIYSQFFPH
G------------------------DASTYAHYLFNAFDTGHTGSIKFED
FVT-ALSILLRGSVTEKLQWTFNLYDINRDGYINKEEMMDIVRAIYDMMG
KF-TYPVLKTD------A----PKQHVDAFFQ--------------KMDK
NRDGVVTLDEFILSCQEDENIMRSLQLFENVI------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSXMAG00000000405

MAGCT-----S-RCRQGVQKLIQSLQRLV--------------------S
-------GT-LT-----------------------KDKADDELEMTMVCH
RPEGLEQLEAQTNFSKQELQILYRGFKNECPSGVVNEETFKHIYAQFFPH
G------------------------DASMYAHYLFNAFDTTNNGSIKFKD
FVV-GLSILLRGTLREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMG
KY-TYPALKGD------V----PQQHVDAFFQ--------------KMDK
NKDGVVTMEEFIIACQEDENMMRSMQLFENVM------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSONIG00000005028

Y-------------------------------------------------
-------YF-YP-----------------------LDKADDDLEMTMVCH
RPEGLDQLEAQTNFSKRELQVLYRGFKNECPSGVVNEDTFKQIYSQFFPH
G------------------------DASTYAHYLFNAFDTGHTGSIKFED
FVT-ALSILLRGSVTEKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMG
KY-TYPVLKND------A----PKQHVDAFFQ--------------KMDK
NRDGVVTLDEFIFSCQEDENIMRSLQLFENVI------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------
*
>P1;ENSLOCG00000006632

MADSA-----S-ESDTD---GAGSSSAAPPSS---TSSSSSSKPGIVISP
FRLEELTNRLASLQQENKVLKIELETYKLKCKALQEENRDLRKASVTIQA
RAEQEEEFISNTLFKK--IQALQK----EKE-------------------
---------------------------------------TLAVNYEKEEE
FLTNELSRKLMQLQHEKAELEQHLEQ-EQEFQVNK-LMKKIKKLENDTIS
KQLTLEQLRREKIDLENTLEQEQEALVNRLWKRMDKLEAEKRILQEKLDQ
PVSAPPSPRDISMEIDSPENMMRHIRFLKNEVERLKKQLRTAQLQHTEKM
AQYIEEERHMREENIRLQRKLQREMERREALCRQLSESESSLEMDDERYF
NEMSAQGLRPRTVSSPIPYTPSPSSSRPISPGLSYASHTVGFTPPASLTR
AGMSYYNAPGLHVHAGSSHGIARPSPRRSNSPDKFKRPTPPPSPNTQSGV
QPAPPPPPPAQPMAQSGSSQAATSQHSVHPSSQP
*
