>P1;ENSDARG00000038855

MVCIPRPTGRSALWWSAFKYLYKANKCHSHINMNRIFG------------
-----------------------------RSKQ-----------------
--------AASPN-------------------------------------
------------------------LSDCIG-NVDTRIESIDKKIARIDAE
LMKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNTVKQKAMRVLKQKRMYEGQRDQLS-QQSFNMEQANYTIQ
SL-----------------------------RDTKTTVEAMKIGAKEMKK
AYK------------------QVKMDQIEDLQDQLEDMM-----------
-----------------------------------EEANEVQEALSRSYG
TPEIDEDEL-----------------EA--ELDALGDELLLDDDSSYLDE
ASSAPSIPEGMPSDTKTNKDGVLVDEFGLPQIPAT
*
>P1;ENSORLG00000017844

--------------------------------MIRIFG------------
-----------------------------RGKPK----------------
--------APPPN-------------------------------------
------------------------LSDCIS-TVDARSESIEKKIGRLDAE
LLKYKDQLK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNTVKQKAMRVLKQKRMYEGQREQLA-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------DVKLDQIDDLQDQLEDMM-----------
-----------------------------------EEAGEVQESLSRSYG
TPDIDEEDL-----------------EA--ELDALGDELLLDEDSSYLDE
ASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQIPAT
*
>P1;ENSGACG00000004275

--------------------------------MNRIFG------------
-----------------------------RGKPK----------------
--------GPAPN-------------------------------------
------------------------LTDCIG-NVDSRSESVDKKIARLDVE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKALRVLKQKRMYEGQRDNLM-QQSFNMEQTNYTIQ
TL-----------------------------KDTKTTVDAMKIGLKDMKK
AYK------------------HVKIDQIEDLQDELGDMM-----------
-----------------------------------EDANDIQEALGRSYG
TPELDDDDL-----------------EA--ELDALGDELLMDDDSSYLDE
AATAPSIPEGMPGDKSVNRDGVLVDEFGLPQIPAT
*
>P1;ENSXMAG00000016811

--------------------------------MNRIFG------------
-----------------------------RGKPK----------------
--------APPPN-------------------------------------
------------------------LSDCIS-TVDARSESIEKKVGRLDAE
LLKYKDQLK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQREQLA-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------DVKLDQIDDLQDQLEDMM-----------
-----------------------------------EEAGEVQESLSRSYC
TPDIDEEDL-----------------EA--ELDALGDELLLDDDTSYLDE
ASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQIPAS
*
>P1;ENSDARG00000103718

--------------------------------MNRIFG------------
-----------------------------RGKPK----------------
--------GPPPN-------------------------------------
------------------------LTDCIS-GVDSRAESVDKKIARLDAE
LMKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQRDQLM-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------NVKIDQIEDLQDQLEDMM-----------
-----------------------------------EDANEVQEALSRSYG
TPEIDEDDL-----------------EA--ELDALGDELLLDDDNSYLDE
ASSAPAIPEGAPGDRTTNRDGVLVDEFGLPQIPAT
*
>P1;ENSGACG00000017109

--------------------------------MNRLFG------------
-----------------------------RGKPK----------------
--------TPPPN-------------------------------------
------------------------LSDCIG-SVDARSESIEKKIGRLDAE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMREGPS-KNMVKQKAMRVLKQKRMYEGQREQLA-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKR
AYK------------------DVKLDQIDDLQDQLEDMM-----------
-----------------------------------EDAGEVQEALSRSYG
TPEIDEDDL-----------------EA--ELDALGDELLLDDDSSYLDE
ASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQIPAS
*
>P1;ENSORLG00000011425

--------------------------------MNRIFG------------
-----------------------------TGKPK----------------
--------APPPN-------------------------------------
------------------------LSDCIG-NVDSRTESVDKKIARLDAE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQRDNLM-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVDAMKTGLKEMKK
AYK------------------QVKIDKIEDIQDQLEDMM-----------
-----------------------------------EDANEIQEAMGRSYG
TPEIDEDDL-----------------EA--ELDALGDELLMDDDSSYLDE
AATAPSIPEGNPGDRTANRDGVLVDEFGLPQIPAT
*
>P1;ENSONIG00000009226

--------------------------------MNRIFG------------
-----------------------------RGKPK----------------
--------APPPN-------------------------------------
------------------------LSDCIG-TVDARAESIEKKIGRLDAE
LLKYKDQLK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQREQLA-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------DVRLDQIDDLQDQLEDMM-----------
-----------------------------------DEANEVQEALSRSYG
TPDIDEEDL-----------------EA--ELDALGDELLLDDDTSYLDE
ASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQIPAT
*
>P1;ENSTRUG00000006914

--------------------------------MNRIFG------------
-----------------------------SSKPK----------------
--------GPPPN-------------------------------------
------------------------LTDCIG-TVDSRTDSIDKKISKLDAE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMKDGPS-KNMVKQRAMRILKQKKAYENQRDGLA-QQSFNMEQANYTIQ
NL-----------------------------KDTKTTVDAMKTGLKEMKK
AYK------------------KVDINKIEDIQDQLEDMM-----------
-----------------------------------EDANDIQDALGRSYG
TPDIDEADL-----------------EAGTELDALGDELLFDDDSTYLDE
ASTAPSIPEGIPGDKSTNRDGVLVDEFGLPQIPAS
*
>P1;ENSTRUG00000011216

--------------------------------MNRIFG------------
-----------------------------RSKPN----------------
--------PPPPN-------------------------------------
------------------------LSDCIG-NVDARSESIEKKISRLDAE
LIKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQREQLA-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------DVKLDQIDDLQDQLEDMM-----------
-----------------------------------DEANDVQEALSRSYG
TPDIDEDDL-----------------EA--ELDALGDELLLDDDSSYLDE
ASAAPSIPEGIPSDSKTNKDGVLVDEFGLPQIPAS
*
>P1;ENSXMAG00000002110

--------------------------------MNRIFG------------
-----------------------------RGKAK----------------
--------GPPPN-------------------------------------
------------------------LTDCIG-SVDSRAESIDKKIARLDAE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQRDNLM-QQSFNMEQANYTIQ
NL-----------------------------KDTKTTVDAMKVGLKDMKK
AYK------------------NVNIDKIEDIQDQLEDMM-----------
-----------------------------------EDANEIQEAMSRSYG
TPDIDEDDL-----------------EA--ELDALGDELLMDDDSSYLDE
AATAPSIPEGIPGDRSTNRDGVLVDEFGLPQIPAS
*
>P1;ENSTNIG00000018642

--------------------------------MNRIFG------------
-----------------------------RSKPK----------------
--------TPPPN-------------------------------------
------------------------LSDCIG-NVDARSESIEKKIARLDAE
LIKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYEGQREQLA-QQSFNMEQANYTIQ
TL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------DVKLDQIDDLQDQLEDMM-----------
-----------------------------------DEANEVQEALSRSYG
TPDIDEDDL-----------------EA--ELDALGDELLLDDDSSYLDE
ASAAPSIPEGIPNDSKTNK----------------
*
>P1;ENSAMXG00000018188

--------------------------------MNRIFG------------
-----------------------------RSKN-----------------
--------QPPPN-------------------------------------
------------------------LSECIG-NVDARAESIDKKIARIDSE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPA-KNAVKQKAMRVLKQKRMYEGQRDQLA-QQSFNMEQANYTIQ
SL-----------------------------KDTKTTVEAMKIGAKEMKK
AYK------------------QVKMDQIEDLQDQLEDMM-----------
-----------------------------------EEASEVQEALSRSYG
TPDIDEDDL-----------------EA--ELDALGDELLLDDDSSYLDE
ASAAPAIPEGMPSDSKTNKDGVLVDEFGLPQIPAT
*
>P1;ENSONIG00000006122

--------------------------------MNRIFG------------
-----------------------------KGKAK----------------
--------GPPPN-------------------------------------
------------------------LTDCIG-SVDSRAESIDKKIARLDAE
LVKYKDQMK-----------------------------------------
--------------------------------------------------
-KMRDGPS-KNMVKQKAMRVLKQKRMYESQRDNLM-QQSFNMEQTNYTIQ
NL-----------------------------KDTKTTVDAMKVGLKDMKK
AYK------------------NVKIDKIEDLQDQLEDMM-----------
-----------------------------------EDANEIQEAMSRSYG
TPDIDEDDL-----------------EA--ELDALGDELLMDDDSSYLDE
ASSAPSIPEGLPGE-KSNRDGVLVDEFGLPQIPAS
*
>P1;ENSLOCG00000008090

--------------------------------PSAILAMLGAVGRCCTGA
LQALKPGVNPLKVFSGTPAALYSRRNYAAQASPSAKPVTANGRIVAVIGA
VVDVQFDEGLPPILNALEVAGRDTRLVLEVAQHLGESTVRTIAMDGTEGL
VRGQKVIDTGAPIRIPVGPETLGRIMNVIGEPIDERGPISTKQTAPIHAE
APEFTDMSVEQEILVTGIKVVDLLAPYAKGGKIGLFGGAGVGKTVLIMEL
INNVAKAHGGYSVFAGVGERTREGNDLYHEMIESGVINLKDTTSKVALVY
GQMNEPPGARARVALTGLTVAEYFRDQEGQDVLLFIDNIFRFTQAGSEVS
ALLGRIPSAVGYQPTLATDMGTMQERITTTKKGSITSVQAIYVPADDLTD
PAPATTFAHLDATTVLSRAIAELGIYPAVDPLDSTSRIMDPNIVGAEHYD
VARGVQKILQDYKSLQDIIAILGMDELSEEDKLTVARARKIQRFLSQPFQ
VAEVFTGHLGKLVPLKETIKGFKSILAG--EYDGLPEQAFY---------
--------MVGPIEEVVQKAEKLAEEH-------S
*
