>P1;ENSGACG00000018427

-----MSASPAKVNRKE-NSNHD----------------AADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSDL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKA---LSKEFNVNESGDPVSKSSEIKWKAGKDLTKRTG
QTSNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLV-----------------------------------------------
------------
*
>P1;ENSAMXG00000012408

-----MSASAAKVSKKELNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLTRVEVTEFEDIKSGYRI
DFYFDENMYFENKV---LSKEIHLNESGDPTPKSTEIKWKPGKDLTNRPS
QTQSKAGKKRQHEE-PESFFTW-FTDHSDSGADELGEVIKDDIWPNPLQY
YLVPDMEDE-EGEGED--EDEDEEGLEDIDEEGEE-DGEEE-D-DDGE--
--D---DDGEDD
*
>P1;ENSXMAG00000002845

-----MSATATKVSKKELNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKV---LSKEFHLNESGDPSSKSTEIKWKSGKDLTKRSS
QTQNKAGRKRQHEE-PESFFTW-FTDHADAGADELGEVIKDDIWPNPLQY
YLVPDMDDE-EGEGEE--DEEDEEGLEDIDEEGDE-DGEDD-EEDEGE--
--EGEEDEGEDD
*
>P1;ENSXMAG00000013718

-----MSASAAKVSRKE-NSNHD----------------AGDETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSKVEVTEFEDIKSGYRI
DFSFDENPYFENKV---LSKEFNVNEGGDPVSKSTEIKWKTGKDLTKRSS
QTPNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLVPDMEDE-EGED-D--EEEDEEGLEDIDEGEEE-EGEDE--DGEGE--
--DGE-DDGEDD
*
>P1;ENSTNIG00000016723

-----MSASAAKVSKKELNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKV---LSKEFHLNESGDPSSKSTEIKWKSGKDLTKRSS
QTQNKAGRKRQHEE-PESFFTW-FTDHADAGADELGEVIKDDIWPNPLQY
YLVPDMDEE-EGEGEE--DEEDEEGLEDIDEEGDE-DGEDD-EEDDGE--
--DGEVRQ---T
*
>P1;ENSDARG00000031495

-----MSASAAKVSKKELNSNHD----------------GGDETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLTRVEVTEFEDIKSGYRI
DFYFDENMYFENKV---LSKEIHLNESGDPTSKSTEIKWKPGKDLTSRSS
QTQSKAGKKRQHEE-PESFFTW-FTDHADSGADELGEVIKDDIWPNPLQY
YLVPDMEDE-EGEGED--EDDDEEGLDDIDEEGDD-DGEEE-DDDDGE--
--D---DEGDDD
*
>P1;ENSORLG00000017766

-----MSASAAKASKKELNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKV---LSKEFHLNESGDPSSKSTEIKWKSGKDLTKRSS
QTQNKAGRKRQHEENPLQYYLWCFTFHSEA--------------------
--------------------------------------------------
------------
*
>P1;ENSORLG00000012750

-----MSA---KASRKE-NSNHD----------------AADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEDDEEALHYLSKVEVTEFEDIKSGYRI
DFCFDENPYFENKT---LSKEFNVNEGGDPISKSTEIKWKTGKDLTKRSG
QTSNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLVPDMEDE-EGDGDD--DDDDEEGLEDIDEGEEE-GGEDD--DGEGD--
--DGE-DDGDED
*
>P1;ENSONIG00000011282

-----MSASSAKVSRKE-NSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEI
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKA---LSKEFNVNESGDPVSKSSEIKWKAGKDLTKRTG
QTPNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLVPDMEDE-EGDGDD--DDEEEEGLEDIDEGEEE-EGEDEDEDGDGE--
--DGEHDDGEDD
*
>P1;ENSDARG00000003920

-----MSASAAKVSRKEQNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLTRVEVTEFEDIKSGYRI
DFYFDENPYFENKV---FSKEFHLNESGDPSSKSTEIKWKAGKDLTKRTG
QTPNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLVPDMDEE-EGEGEEEDDEEEEEGLEDIDEEGDEDDGEEDEEEDEGE--
--DGE-DDGEDD
*
>P1;ENSGACG00000014785

-----MSASAAKVSKKELNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKL---LSKEFHLNESGDPSSKSTEIKWKSGKDLTKRSS
QTQNKAGRKRQHEE-PESFFTW-FTDHADAGADELGEVIKDDIWPNPLQY
YLVCSPDN------------------------------------------
------------
*
>P1;ENSAMXG00000010484

-----MSASAAKVSRKEQNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLTRVEVTEFEDIKSGYRI
DFYFDENPYFENKV---LSKEFHLNESGDPSSKSTEIKWKAGKDLTKRAG
QTQNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLVPDMDDE-EGEGEDE-DDEEEEGLEDIDEEGDEDEGEEDEEEDEGE--
--DGE-DDGEDD
*
>P1;ENSTRUG00000013980

-----MSASSTKVSRKE-NSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSDL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSKVEVTEFEDIKSGYRI
EFFFDENPYFDNKV---LSKEFNVNESGNPVSKSTEIKWRSGKDLTKRTG
QTPNKAGKKRQHEE-PESFFTW-FTDHSDAGADELGEVIKDDIWPNPLQY
YLVPDMEEEDEGEGDE--DDDEEEGLEDIDEGEEE-EGEDD--DEDGEVS
RRRGPHDDGEED
*
>P1;ENSTRUG00000006019

PACENMSASAAKVSKKELNSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEEILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSRVEVTEFEDIKSGYRI
DFYFDENPYFENKV---LSKEFHLNESGDPSSKSTEIKWKSGKDLTKRSS
QTQNKAGRKRQHEE-PESFFTW-FTDHADAGADELGEVIKDDIWPNPLQY
YLVPDMDEE-EGEGEE--DEEDEEGLEDIDEEGDE-DGEDD-EEDDGE--
--DGEDDEGEDD
*
>P1;ENSTNIG00000003141

PQTATMSASSAKVTRKE-NSNHD----------------GADETSEKE--
--QQEAIEHIDEVQNEIDRLNEQASEDILKVEQKYNKL-RQPFFQKRSEL
IAKIPNFWVTTFVNHPQVSALLGEEDEEALHYLSKVEVTEFEDIKSGYRI
EFFFDENPCFDNKV---LSKEFNVSESGHPVSKATEIKWKAGKDLTKRTG
QTPNKAGKKRQHEE-PESFFTW-FSDHSDAGSDELGEVIKDDIWPNPLQY
YLV-----------------------------------------------
------------
*
>P1;ENSLOCG00000002663

-----MTAGTVVITGGILATVILLCIIAVLCYCRLQYYCCKKEESEEDEE
EPDFAMHSHLPPVHCNQNVVAATAAATAN-----GPALFTPPPARKLVR-
-------------------------------------SRTYCPNCTHYEL
PFYLQHPDGLRNGGERVSYRTVQQEDLDLPLDLPSMHKLNLARSVTMKEV
FTRSRS--------------------------------ISTDV-------
--------------------------------------------------
------------
*
