>P1;ENSORLG00000004731

MNADTC---VSYCDMTSMDSYYSAST-AQ--GRDHQTNPFRTFPTTETKY
SPT-FLPGKGQ-AYGEKPRSPFQP-----ECHSLDGA--EESSFNKYQLF
MQRPTCKTPPEGGKLHLD-SAHNG--TLIPCYGKDN--------------
-------------------S-----LTESELPPSVDPPGMEGSYLNLKEP
GLKGSSER-PGSELSSPL-----------------------------DKS
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNSSWIGSSSGASPVPGCVVPCDTVSSCMPPHP
HGPGGVSDFLGVPSPGSSHM--------G-----QTHMGSLFGG-AGISG
---------------------------GINGYDLNVDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSAMXG00000004649

MNAETC---VSYCDMSSMEPYYGPQA-P----REQHSNPFRTFPAAEAKY
SPA-FPGAKAQ-A-----RSPFQPQQPQPDCPSSA-D--AESTFNKYHLF
MQRGACKTPPEGGKGHQE-SGHNGGGGLLSCYGKDS--------------
-------------------T--G--LTDSELPPNTDPAGMDGSYLSVKEP
GSKGPQER-PSSELASPL-----------------------------DKG
E-GESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGSSAASPVPGCVVPCDSVTSCMTPHP
HAASGVSDFLGVPSPG-SHM--------G-----QSHMGSLFGS-PGMST
---------------------------GINGYDLNMDPDRKSSSIATLRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSGACG00000009885

MNAAAC---VSYCDMTSMDSYYSAST-AQ--GRDHQANPFRTFPTSETKY
SPT-FVPGKGQ-AYGEKSRSPFQP-----ECQSLDGA--EDSGYNKYQLF
MQRPTCKTPPEGGKLHQD-SGHNG--TLMPCYGKDN--------------
-------------------S--G--LTESELPPSVDPPGMEGSYLNLKSP
GEKGLSER-PGSDYSSPL-----------------------------DKS
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLAMRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERYGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGSSSGASPVPGCVVPCDSVSSCMPPHP
HGPGGISDFLGVPSPGSSHM--------G-----QTHMGSLFGG-PGMGG
---------------------------GINGYDLNLDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWTT---
*
>P1;ENSDARG00000088332

MNAETC---VSYCEMTSMDSYYSPSA-PQ--GRDHQANPFRTFQASDTKY
SPA-FLTNKGQ-GYGEKSGSPFQQ-----ECQSLDAT-AGEGTFNKYHLF
MQRSSCKTPPDSSKLQQENSGHNG--GLIACYGKDS--------------
-------------------T--G--LTDSELPQNSDPAGMDGSYLSVKDS
GVKSPQ-Q-ATSELASPL-----------------------------DKT
E-GESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGSSAASPVPGCVVPCDSVTSCMPPHP
HAASGVSDFLGVPSPG-SHM--------G-----QTHMGSLFGS-PGMGT
---------------------------GINGYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSTRUG00000017056

MNA-AC---VSYCDMTSMDSYYSTST-AQ--GRDHQ---FRTFPTAETKY
SPT-FIPGKGQPPYAEKSRSPFQQ-----ECQSLDGA--EDSTFNKYQLF
MQRPTCKTPPEGSKLHSD-SGLNG--TLVSCYGKDN--------------
-------------------S--S--LTESELPSSVDPSGMEGSYLNLKAP
GEKVQSER-PGSELSSPL-----------------------------DKT
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPILTRPENYAQIQNPTWIGSSSGASPVPGCVVPCDPVSSCMPPHP
HGPAGVADFLGVPSPGGSHM--------G-----QTHMGSLFGG-PGMGS
---------------------------GINGYDLNVDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSDARG00000074442

MNADTC---VSYCDMTSMDSYYSPAAPGQ--GRVQQANPYRTFQSSDSKY
SPT-FLPAKGQT-YGEKPRSPFHQ-----DCPTLDDS-TAEGAYSKYHLF
MQRPACKSPSEDSKLE------DG--ALISCYGKDG--------------
-------------------T--G--LTDTDMPQSADPTALDGSFISVKDA
GVKGQSDR-PVSDLGSAL-----------------------------DKS
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AN-GKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWLSGSSSASPVPGCVVPCDTVSSCMTPHP
HSASGVSDFLGMPSPG-GSM--------A-----QTHMGSLFGS-SGVGG
---------------------------TINGYDLSVEPDRKSSSIASLRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSONIG00000006176

MNTETC---VSYSDMTSMDSYYSSSA-AQ--GRDHQTDHFRTFHATDTKY
SPAAFLPNKGQG-YGEKSRSPFQQ-----ECQSLDAAAAGQGTFSKYHLF
MQRSSCKTPPEEDKLHQE-RGHNG--SLISCYGKDS--------------
-------------------S--G--LADSDLAPDSDTPGMDTRYLAVKDQ
GVKAASDRTPGTDLASPL-----------------------------EKA
DGGESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGSSAASPVPGCVVPCDTVAPCMTPHP
HSASGVSDFLGVPSPG-GHV--------G-----QAHMGSLFGGSPGMAG
---------------------------GINTYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSTNIG00000016041

MNA-AC---VSYCDMTSMDSYYSTST-AQ--GRDHQ---FRTFPTAETKY
SPT-FIPGKGQ-PYAERSRSPFQQ-----ECQSLDGA--EESTFNKYQLF
MQRPSCKTPPEGSKLHPD-SGLNG--TLVPCYGKDN--------------
-------------------G--S--LTESELPPSVDPSGMEGSYLNLKAP
GDKVQSER-PGSELPSPL-----------------------------DKT
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPILTRPENYAQIQNPTWIGSSSGASPVPGCVVPCDPVPSCMPPHP
HAPAGVTDFLGVPSPGSSHM--------G-----QTHMGSLFGG-PGMGS
---------------------------GINGYDLNVDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSGACG00000015616

MNAETC---VSYSDMTSMDSYYSPSA-AQ--SRDHQTDHFRTLPAPDTKY
PAA-FLANKGQA-YGDRSRSPFQQ-----ECQSLDAASAGQGTFSKYHLF
MQRSSCKTPPEDGKLHQE-SGHNG--ALISCYGKAS--------------
-------------------S--G--LADSDLAQDSDPAGMDSSYLAVKGP
GGKSASDRQPGTELSSPL-----------------------------DKG
DGGESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGGSAASPVPGCVVPCDTVSPCMTPHP
HSASGMSDFLGMSGPG-GHV--------G-----QAHMGSLFGGPPGMAT
---------------------------GINAYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSTRUG00000017295

MNAEIC---ISYSDMTSMDSYYSPSA-VQ--SRDHQTDHFRTFPAPDTKY
SPTAFLPNKGHA-YGEKSRSPFQQ-----ECPSLDAAAAGQGTFSKYHLF
TQRSSCKTPPEEGKLQQD-GGHGG--ALVSCYGKDG--------------
-------------------S--G--LADS--APDSEPPGMDSSYLAVKDS
GMKATSDS-P-------------------------------------DKG
DGGESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGSSAASPVPGCVVPCDTVTSCMTPHP
HSASGVSDFLGMPSPA-SHM--------G-----QAHMGSLFGGSPGIPA
---------------------------GINTYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSXMAG00000007283

MNADTC---VSYCDMTSMDSYYSAST-AQ--SRDHQANPFRTFQTTETKY
SPT-FIPGKG-------SRSPFQT-----ECQSLDGT--EESNFNKYQLF
MQRPTCKTPPEGGKLHPD-SGHNG--TLIPCYGKDH--------------
-------------------S--G--LTESELPPSVDPPGMEGSYLNLKEP
VVKGPSER-SGSDLSSPL-----------------------------EKS
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGSSSAASPVPGCVVPCDSVPSCMAPHP
HAPGGVSDFLGVPSPGSSHM--------G-----QTHMGSLFGG-AGIGG
---------------------------GINGYDLNVDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSTNIG00000009388

MNAEIC---ISYSDMTSMDSYYGHSA-VQ---RDQQADHFRTFPAPDTKY
GPTAFLPNKGQA-YGEKPRSPFQQ-----ECPSLDAAAAGQGTFSKYHLF
MQR-SCKTPPEEGKLQPD-GGHSG--ALVSCYGKDS--------------
-------------------S--G--LADS--APDSDPPGMDSSYLAVKDP
GMKATSDRPPGTELSSPL-----------------------------DKG
D-AQSNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGSSAASPVPGCVVPCDTVTPCMTPHP
HSASGVSDFLGVPSPA-GHM--------G-----QAHMGSLFGGSPGIPA
---------------------------GINTYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSORLG00000006554

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------G--LTDSDLAPDSDPAGMDNRYLSVKDP
SVKAGSDRPPGHDLASTL-----------------------------DKP
DGSESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWLSGSSAASPVPGCVVPCDTITPCMTPHP
HSASGVSDFLGVPSPG-GHM--------G-----QPHMGSLFGGS----P
---------------------------GINTYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSXMAG00000007187

MNAETC---VPYSDMTSMDSYYSPSA-AQ--GRDHQADHFRTFPASDIKY
SSTAFLSSKGQA-YGEKSRSPFQQ-----ECQSLDAAAAGQGSFSKYHLF
MQRSSCKTPPAEDKLLPE-RGHNG--ALVPCYGKDS--------------
-------------------S--G--LTDSDLAPDSDPPGMDSRYLAVKDQ
GVKAASERSPSNELASPL-----------------------------EKV
DGGESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGGSSAASPVPGCVVPCDTVTTCMTPHP
HSASGVSDFLGVSSPS-GHV--------G-----QPHMGSLFGGSPGMAA
---------------------------GINAYDLNMDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSONIG00000008457

MNADTC---VSYCDMTSMDSYYSTST-AQ--SRDHQANPFRTFPTTETKY
SPT-FIPGKGQ-AYGEKSRSPFQP-----DCQSLDGA--EEGTFNKYQLF
MQRPTCKTPPEGSKLHPD-SAHNG--TLISCYGKDS--------------
-------------------S--S--LTESELPQSVDPPGMESSYLNLKET
GVKGQSER-PGSDLSSPL-----------------------------EKS
E-AESNKGKKR---------------------------------------
-------------------------------------------------R
NRTTFTSYQLEELEKVFQKTHYPDVYAREQLALRTD--------------
------------------------------------------------L-
TEARVQVWFQNRR----------------AKWRKRERFGQMQQVRTHFST
AY-ELPLLTRPENYAQIQNPSWIGSSSGASPVPGCVVPCDSVPSCMPPHP
HGPGGVSDFLGVPSPGSSHM--------G-----QTHMGSLFGG-AGIGG
---------------------------GINGYDLNVDPDRKSSSIAALRM
KAKEHSA-------------------------------------------
--------------------------------------------------
----------------------------------------AISWAT---
*
>P1;ENSLOCG00000004220

MGTASMDTSVAVETNPALNPLCQDCG-QQHWSRENHLYNYRHEVDD--DL
V----------------CHICLQP-----LVQPLDTPCGHTFCFKCLRNF
LQEKD-FCPLDRKKLHFK-VCKKS--SILVHKLLDKLPVSCPFSAACPDS
MPRCDLEAHLKHRCPGALNHRAGLERRRSERLPAPDG-GGEGRAMGMEPP
-DSAHSPE-PGSAGDSPPGGSTACAAVPMWTDEHGLDNPAFEESTEEDSV
HSLDCNPARAKRPLSNPCIHLHRTSSTNSSGWDIPEDGPPPPAEEGCPKV
PGLPEGEITTIDIQRSNPYMELGISVVGGNETPLINLVIQEVYRDGIIAR
DGRLLAGDQILQVNGV-DISNVPHNFARATLSQPCPALQLTVLRERRFSG
RPGASAATTACWASTGTTCGTAPPSSPLRSSRYCGDRGTGILGVVYTCMK
DSVKIHIWNIQRLGISTRIRRLLFLQRLQKMFEKTRRILQASGERVHLVI
CRPSKPLPPLPSANAN--------------AVR--DAGCHTIALPHPLHP
PVS-TAMQHLGRPSTHATHRVSPPPRHPGDRSESPLHHTLQFGV-TGDRG
NCQRARRAQPGVCSSRCCSLEAGDVLLSINGMDLTSL--SHSEAVATLKA
SAASSSVLLRALEVQTIEEQGQAAEETLPAAHDNDYDASWSPSWVMWLGL
PSYLHSCHEIVLRRSSLGSWGFSIVGGYEESHTNQPFFIKTIVLGTPAYY
DGRLKCGDMIVAVNGLSTAGMSHSALVPMLKEQRNKVALTVVSWPGSLV
*
