>P1;ENSDARG00000104847

MLSIQQYNSTV---LA---ED-E---A--LVN-QSH--HYVAP-LRCREN
LTTT-----SP-------------------------TAAGLSMTLGIVSN
IIALAILANAYS---------------------------------RRSKT
TKATFL--------------------------------------------
------------LFA-----------------------------------
--------SSLVVTDLVGHVIPGAL-------------------------
--------------------------------------------------
------------VLHLYLSGTGPC--------L-----PAVPDG--TCQF
LGGSM---------------VFFGLCPLFLGCAMAVERCIG-VTRPLLHK
RLVCTTQTKIVMVMV-----------------------------------
---WLLALSVA------FLPFFRLGSY-----------------------
-------------------TYQYPWTWCFINVLDE-TNVTDVIF------
--------------------------------------------------
-----------------------------------------------VVL
FSGLGLASLAVALVC-----------------------------------
NTISGVTLVAARLR-KKQKQESIRQSKKDKQESVRLS-------------
-----------RKDKQNKSSKT-------------HDIEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------FGLMSVIRSSISS-MGDDLE
MSYRTLL---------------------------------VMGVRLASWN
QIL---------------DPWVYILL------------RRAILR------
------------------------KI------------YYLTTGRTG---
---------------------RKGSTFR--RWEASSFQNSVKKA-I----
-----------------------------N-QT---
*
>P1;ENSONIG00000008088

MLAMQHSNSSGISA--LLPLS-N---H--TVV-AKE--PKMEAVVAK---
--NTTQPRSDP-------------------------TAAGLTMTLGIIFN
VVALIILVKAYN---------------------------------RFRRR
TKASFL--------------------------------------------
------------LFA-----------------------------------
--------SCLVATDLAGHVIPGSL-------------------------
--------------------------------------------------
------------VLSRYSTSTEAEAGLGSTFQD----NSTDQDA--SCLF
LGGCM---------------VFFGLCPLFLGCAMAAERCLG-ITSPLLHA
RLVTTARTKMALILI-----------------------------------
---WLLALCVA------LLPFISLGDY-----------------------
-------------------TSQFPGTWCFIRVMEG-TKATDLAF------
--------------------------------------------------
-----------------------------------------------MIL
FSGLALSSLALAFVC-----------------------------------
NTISGITLVRARLK-RS---------------------------------
-------------CSQRYTTRS-------------HDTEMVVQLVGIMVT
------------------SSICWSPL------------------------
----------------LI------------FGLISAIRSYTSS-TFSDKE
-TYKHLM---------------------------------MTGVRMATCN
QIL---------------DPWVYILL------------RRAILR------
------------------------KI------------YRITKKQAS---
---------------------FKGSTLR--RWEFGSFQNSEKNK-V----
-----------------------------D-PKSFK
*
>P1;ENSXMAG00000008865

MEIKPDSNSSDFNS--N---I-N---S--STM--------APE-VDC---
--PHNSVPSNP-------------------------IIASLTMTLGILFN
VVALIILIKAYT---------------------------------RFRRR
SKATFL--------------------------------------------
------------LFA-----------------------------------
--------SSLVVTDLTGHVVSGGL-------------------------
--------------------------------------------------
------------VLRRYTTANLTS-------LD----GPRDPDS--PCQF
LGGCL---------------VFFGLCPLFLGCAMAAERCLG-VTKPLLHA
RLVTTARTKIALSMI-----------------------------------
---WFLALCVA------LLPVFQLGDY-----------------------
-------------------TYQYPGTWCFIKVMD--TNAKDLTF------
--------------------------------------------------
-----------------------------------------------VTL
FSGLALSSLALAFIC-----------------------------------
NTISGMTLIRARLK-KN---------------------------------
------------SYSQRFSARS-------------HDTEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LV------------FSLMSAARSYSESHLGEEVT
CTYSKLM---------------------------------MTGVRMATWN
QIL---------------DPWVYILL------------RRAILR------
------------------------KI------------YRITKKQAS---
---------------------FKGSTFRSVRWDVGSLQKPDSMP-V----
-----------------------------K-K---T
*
>P1;ENSDARG00000078605

MHHA---NSSGAVP--LNPFS-N---R--SQW-EGQ--AGSLS-LADPSN
VTSSRPILSGP-------------------------IAAMLSMTLGILSN
IVALLILANAYA---------------------------------RLRRR
SKA-FL--------------------------------------------
------------LFA-----------------------------------
--------GSLVATDFVGHVIPGAI-------------------------
--------------------------------------------------
------------VMRLYLSGGVPA--------E----EYNRADP--LCQF
LGGSM---------------VFFGLCPLFLGCAMAAERCLG-VTKPLLHA
SLVTTTRTKLSLSVI-----------------------------------
---WLAALCVA------LLPCFQLGSY-----------------------
-------------------TYQYPGTWCFIKVLED-AEKADMAF------
--------------------------------------------------
-----------------------------------------------VML
FSGLGLTSLAVALVC-----------------------------------
NTISGLTLVLGRIR-KK---------------------------------
-------------PCNRRSARS-------------HDIEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------VGLITVKQSYEHS-IGDDLA
-TYKTLM---------------------------------IMGVRIASWN
QIL---------------DPWVYILL------------RRSVLQ------
------------------------KI------------YFITKRQTD---
---------------------LKESTLR--CWEIHSFPSSEKNP-V----
-----------------------------S-R---V
*
>P1;ENSGACG00000006265

FNVTPV--------------V-Q---E--LR---------VEA-VAC---
--NTTRPPSNP-------------------------ASAGLSMTLGILFN
AVALIILAKAYN---------------------------------RFRRR
SKATFL--------------------------------------------
------------LSA-----------------------------------
--------SSLVATNLAGHVILGAL-------------------------
--------------------------------------------------
------------VLKKYSEGTGSA--------------ADNPDR--PCLF
LGSCM---------------VFFGLCPLFLGCGMAAERCLG-VTRPLLHA
RLVTTARTKMALALI-----------------------------------
---WLLALCVA------VLPFFSLGAY-----------------------
-------------------TYQHPGTWCFIRVTEG-TRTTDLVF------
--------------------------------------------------
-----------------------------------------------LML
FSVLALSSLASAFVC-----------------------------------
NTISGITLVRARLK-KR---------------------------------
------------SCSGRRSGGS-------------QDTEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------FGLVLAIKSYSGS-LGGERD
-TYNSLM---------------------------------MTGVRMATYN
QIL---------------DPWVYILL------------RRAVLR------
------------------------KI------------YRVTKR------
--------------------------------------------------
------------------------------------
*
>P1;ENSORLG00000016366

--------------------------------------------------
---------SP-------------------------TSASLNMTLGILFN
MVALIILVKAYN---------------------------------RFRRR
SKATFL--------------------------------------------
------------LFA-----------------------------------
--------SSLVATDLAGHIISGSL-------------------------
--------------------------------------------------
------------VLSRYSASTSSSNNGTFCFQG----DPDNPDP--SCQF
LGGCM---------------VFFGLCPLFLGCAMAAERCLG-ITMPLLHA
RLLTTARTKMALAVI-----------------------------------
---WFLALFVA------LLPVFHLGDY-----------------------
-------------------TYQYPWTWCFIRVMHG-TKATDLAY------
--------------------------------------------------
-----------------------------------------------MIL
FSSLALSSLAVAFVC-----------------------------------
NTISGITLVKARLR-TR---------------------------------
------------CPSQRFSVRS-------------HDTEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LV------------FGLISATLSYTGS-LDTDKT
TQYSKLM---------------------------------VTGVRMATWN
QIL---------------DPWVYILL------------RRAVLR------
------------------------RI------------YRITKKRAS---
---------------------FKGRALRSSRWETSSLSNSVKNS-V----
-----------------------------K-K---I
*
>P1;ENSTRUG00000007446

NS-------SA---FPHLPRS-S---A--VTVAEVG--MRDDG-PSQPGN
NSSLQPTTGGI-------------------------FVVTLSMTLGIISN
IVALCILVTAYT---------------------------------RQRRR
KKATFL--------------------------------------------
------------LFA-----------------------------------
--------TSLVVTDFVGHLVPGAL-------------------------
--------------------------------------------------
------------VLRLYLNGGVRP--------K----DFNSSDT--LCQF
LGGSM---------------VFFGLCPLFLGCAMAAERCLG-ITKPLLHS
TLITKSRAKTCLSII-----------------------------------
---WMAALCVA------LLPCFKLGSY-----------------------
-------------------AYQDPGTWCFINVLNR-TEKTDVAF------
--------------------------------------------------
-----------------------------------------------MML
FSGLGLASLGVALVC-----------------------------------
NTISGLTLMLARVRGRR---------------------------------
-------------PFSHCSNKS-------------HDIEMVAQLVGIMIT
------------------SCICWCPLLQNIVNFVRKDAAVTFSRILLPAK
GFKLCLVLTICAAIPSLI------------FGLRSALHSYSGS-IGDNLS
-SYQTLM---------------------------------MTGVRLATWN
QIL---------------DPWVYILL------------RRAVLH------
------------------------KI------------YLIVKC------
--------------------------------------------------
------------------------------------
*
>P1;ENSTNIG00000012058

IS-----------------AE-R---T--AQM-EST--VAMEK-VRQPEN
GTSVNTHPTRV-------------------------FLVTLPMTLGIISN
IVALCILATAYR---------------------------------RQRRR
SKATFL--------------------------------------------
------------LFA-----------------------------------
--------TSLVVTDFFGHLVPGAL-------------------------
--------------------------------------------------
------------VLCLYSGGIT-----------------SDCNS--LCQI
LGGSM---------------VFFGLCPLFLGCAMAAERCLG-ITKPLLHA
SLVTKTRAKVCLLVI-----------------------------------
---WVLALCVA------ILPCFKLGSY-----------------------
-------------------TYQHPGKWSFVNVLNE-TKEVDVAF------
--------------------------------------------------
-----------------------------------------------VAL
FSGLCLTLLLVALVC-----------------------------------
NTLSGVTLVLARFK-RS---------------------------------
-------------PLSRRSAKS-------------NDIEMVVQLVGIMTT
------------------SCICWCPLL-----------------------
-----------------I------------TL---THASLTGS-IGGNLS
-DYQDLM---------------------------------YLGVRLATWN
QIL---------------DPWVYILL------------RRSVLR------
------------------------KI------------YLIVKCQAQ---
---------------------LNNHRLG--RWEPNSFAGSL---------
------------------------------------
*
>P1;ENSXMAG00000005260

MFTLKHFNSSL---LPRWGDG-S---A--SVV-EAM--VKA-M-EQQQEN
VTVVQNQTSGV-------------------------ISVVLPMSLGIISN
TVALFILVNAYS---------------------------------LQRRR
SKATFL--------------------------------------------
------------LFA-----------------------------------
--------TSLVITDFFGHVIPGAL-------------------------
--------------------------------------------------
------------VLRLYLTGGQST--------E------DSSDS--MCQF
LGGSM---------------VFFGLCPLFMGCAMAAERCLG-VSKPLLHS
SLVTKTRTKVCLSVI-----------------------------------
---WLAALCVA------LLPCFQLGSY-----------------------
-------------------TYQEPKTWCFINVLND-TMGVDVAF------
--------------------------------------------------
-----------------------------------------------VAL
FSGLGLTSLAVALVC-----------------------------------
NTMSGLTLVLARIR-RQ---------------------------------
-------------PGSHHSARS-------------HDIEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------FALMSVIHSSSRT-VGENLT
-NYQTLM---------------------------------HIGVRLATWN
QIL---------------DPWVYILL------------RRTVLR------
------------------------KI------------YLIVKCQAG---
---------------------LKDTVTG--RWEKSFLPSLDQKE-V----
-----------------------------Q-QV---
*
>P1;ENSGACG00000019103

SLNCGPLD-----------LH-S-------S---VM--VAVEG-LSLQEN
HTHGQPTTGGV-------------------------VVVILSMTLGIISN
IVALFILANAYS---------------------------------LQRRR
TKATFL--------------------------------------------
------------LFA-----------------------------------
--------SSLVVTDFVGHVIPGAL-------------------------
--------------------------------------------------
------------VLRLYLSGGAHP--------E----DFNDSDR--MCQF
LGGSM---------------VFFGLCPLFMGCAMAAERCLG-VTKPLLHS
SLVTKTRTKICLSVI-----------------------------------
---WLVPLCVA------MLPCLRLGSY-----------------------
-------------------TYQEPGTWCFIKVLSD-TQEVDLVF------
--------------------------------------------------
-----------------------------------------------VVL
FSGLGLTSLAVALVC-----------------------------------
NTISGLTLVLARLR-RK---------------------------------
-------------PGSHHSAKS-------------HDIEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------LALMSVIHSYTGS-IGEDFS
-SYKTLM---------------------------------VMSVRLATWN
QIL---------------DPWVYILL------------RRTVLR------
------------------------KI------------YLIAKCQAG---
---------------------LRANVLG--RWEPSSFRSSEKN--V----
-----------------------------N-QV---
*
>P1;ENSAMXG00000020714

MAVMGPK-------------D--------------------NQ-TKS---
--EDATSAMNP-------------------------TAAGLSMTLGVLSN
IIALFILSKAYA---------------------------------RLRRR
SKATFL--------------------------------------------
------------LFA-----------------------------------
--------SSLVATDFAGHIIPGAL-------------------------
--------------------------------------------------
------------VLHLYSNGVSQE--------------RKDPDP--CCLF
LGGSM---------------VFFGLCPLFLGCAMAAERCLG-VTRPLLHA
RLVSTTRTKMAVVTI-----------------------------------
---WLVALVVA------LLPISNLGEY-----------------------
-------------------TYQYPGTWCFIRVLRK-SKATDVVF------
--------------------------------------------------
-----------------------------------------------VLL
FSVLGLTSLAMSLVC-----------------------------------
NTISGITLVLARLR-RR---------------------------------
-------------KCHRRSAKS-------------HDIEMVVQLVGIMVT
------------------SCICWCPL------------------------
----------------LI------------FGLMSVRHSYSSS-VPE-QD
-PYRFLM---------------------------------VMGVRLASYN
QIL---------------DPWVYILL------------RRAVLR------
------------------------KI------------YRLTTGRTH---
---------------------IRGSTFR--RWEISSFQNSEKNT-V----
-----------------------------K-RI---
*
>P1;ENSONIG00000018911

MLALSHYNSSASLLLPHVAND-S---G--GKV-EVR--AAVEG-LSHHEN
LTFEEPTAGGA-------------------------FIVILSMTLGIISN
IVALFILVNAYS---------------------------------LQRRR
SKATFL--------------------------------------------
------------LFA-----------------------------------
--------TSLVITDSIGHVIPGAL-------------------------
--------------------------------------------------
------------VLRLYLSGAARP--------Q----FVNSSDG--MCQF
LGGSM---------------VFFGLCPLFMGCAMAAERCLG-VTKPLLHS
SLVTKTRAKICLSVI-----------------------------------
---WLAALSVA------LLPCFQLGSY-----------------------
-------------------TYQEPGTWCFIKVLSD-TKEVDVAF------
--------------------------------------------------
-----------------------------------------------VVL
FSGLGLTSLAVALVC-----------------------------------
NTISGLTLVLARLR-RQ---------------------------------
-------------PGSHHSAKS-------------HDIEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------FGLMSAIHSYTGT-IGQSLS
-YYETLM---------------------------------VMGVRLATWN
QIL---------------DPWVYILL------------RRTVLR------
------------------------KI------------YLIAKCQAG---
---------------------LRGTILG--RWEPSSFPSSEKND-V----
-----------------------------D-QV---
*
>P1;ENSAMXG00000010123

KQTA---NSSGTLP--VLLFS-K---L--SEL-ESH--VTLPL-LGGNEN
ASSDRPALSGP-------------------------IVAVVSMTLGILSN
IVALLILVNSYA---------------------------------HLRRR
SKAAFL--------------------------------------------
------------FFA-----------------------------------
--------TSLVATDFVGHVIPGAI-------------------------
--------------------------------------------------
------------VLKLYLSRSVPV--------T----HYTQPDA--LCQF
LGGSM---------------VFFGLCPLFLGSAMAAERCLG-ITRPLLHA
SLVSTTRTKLSLSII-----------------------------------
---WLAALSVS------LLPCFRLGSY-----------------------
-------------------SYQHPGTWCFIKVLED-TGKVDVAF------
--------------------------------------------------
-----------------------------------------------VLL
FSGLGLGSLALALVC-----------------------------------
NTVSGLALLYGRMR-TQ---------------------------------
-------------RCSRQMAKS-------------HDIEMVVQLVGIMVT
------------------SCICWSPL------------------------
----------------LI------------FGLMSVMRSFEGS-VGDDLA
-TYRTLM---------------------------------ITGVRMASWN
QIL---------------DPWVYILL------------RRAVLR------
------------------------KI------------YLITKRQVN---
---------------------L--STLR--RWEASSIHSTEKKT-V----
-----------------------------SNR---V
*
>P1;ENSLOCG00000015521

MDSYR---ISVLFL-VLFSLLNNLSSTEPFPS-QILIKAWVDK---MQEE
LVTLAETASGVKHLIQIFTDKRKLYSVETNNASQLVESAARNIEKLLLNR
SRALETLATSAENFQMEHGWKHEFADDDIVYYNAKDDLYSDTNKTDGRRR
IKPDFKEDPAFKRRISYNHSAVHIPTDIYEGSTVVLNELSWTEALENIFK
KNREEDPTLLWQVFGSATGLARYYPASPWKDSRNTASKIDLYDVRRRPWY
IQGAASPKDMLILVDVSGSVSGLTLKLIRTSVSEMLETLSDDDFVNVVSF
NKEANYVGCFHHLVQANVRNKKKLKDDVQNITAKGITDYKKGFKFAFEQL
SEFNGSRAHCNKIIMLFTDGGEER-------AEEIFKEYNPERKVRVFTF
SVGQHNYDKGPIQWMACANKGYYYEIPSIGAIRINTQEYLDVLGRPMVLA
DK---KAKQVQWTNVYLDALDLGLVITGTLPVFNKTEIKDNSGQTKHQNQ
LILGVMAIDVSLDDIKRLTPRFTIGPNGYYFAIDPNGYVLLHPNLQPKPV
GLGIPKVLTGIWKPVFQNPKFQEPVTLDFLDAELENDIKVQIRKDMIDGK
KGERTIHTLVKSQDERYIDRGDRTYTWAPVNGTDYSLAMVLPEYSLHYIR
ARIGDTITQAKFSESMQLENFNENGYTLIAPREYCKDLKPSENRTQFLMD
FNEFIDRKTPNNPTCNAMLVNRLLLDAGITSELVQHWKKQSLTGVVARFV
ATDGGITRVYPKSA-GE-DWKE-------------SAETYEASFYKRSLD
NDFYIFTAPYFNNSGSGESGFDSGILVSRAVDLTIDGKKMKPAVVGVKIS
IAEWMANFTNATIRKGCNSEICGCEK------------------------
----------------NSKLVDCVILDDGGFLLMSNQDEYIDE-IGWFFG
-EIDPILMTNLVNTSLYAFNKSYDYQSVCDPDRGPKAAAGLRSVFVPTIA
DILNIGWWASAAAWSIVQQLFVSFTFPNFLEAADTEEEQTAALSKESCIT
EQTQYYFDNNNKSFSGVLDCENCSRIYRAEKLPNTNLLFLIVDAKETCPC
SSTKPLIQAEQPSKGPDPCDLVHNPRYR--KGPEVCFDNDENDEPICTTS
RASTMASTPLFILLQVFMWCKGRIILTAVGSLV---
*
