>P1;ENSORLG00000017848

AAARMSSKRAKGKNTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPTDEYLE---AMMNEAPGPVNFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGLIQEEFLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEDVDELFREAPIDKK
GNFNYVAFTRI---------------------------------------
-------LKHGAKD-----------------------------KD-----
---------------------------------------------
*
>P1;ENSONIG00000006115

----MSSKRAKGKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPNDDYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGFIQEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
NNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSONIG00000009221

----MSSKRAKGKNTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPTDEYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPEE-------VIRNAFACFDEEGTGVIQEEFLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
GNFNYVAFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSTNIG00000018645

---KMSSKRAKGKNTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPTDEYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGMIQEEHLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
GNFNYVAFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSTNIG00000017122

----MSSKRTKAKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPTDEYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGFIQEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
NNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSDARG00000025326

----MSSKRAKGKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPTDEYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIKNAFACFDEEGTGFIQEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
GNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSXMAG00000016792

----MSSKRAKGKNTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPTDEYLE---TMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGVIQEEYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
GNFNYVAFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSTRUG00000006716

----MSSKRTKAKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPTDEYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGFIQEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
SNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSGACG00000017102

----MSSKRAKGKNTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPTEEYLE---TMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEATGIIQEENLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFSDEEVDELFREAPIDKK
GNFNYVAFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSDARG00000099766

----MSSKRAKGKITKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGK----NPADDYLE---AMMTEAPGPINFTMFLTMFGE
KLNGTDPEE-------VIRNAFACFDEEGTGFIHEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
SNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSAMXG00000011297

----MSSKRAKGKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPTDDYLE---AMMTEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGFIQEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
SNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSXMAG00000002121

----MSSKRAKGKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPNDDYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGFIPEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
NNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSORLG00000011406

----MASKKAKVKSTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPNDDYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGFIQEDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTEEEVDELFREAPIDKK
SNFNYVEFTRI---------------------------------------
-------LKHGARD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSTRUG00000011112

G--NMSSKRAKGKNTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFI
DKEDLHDMLASLGKSNSKNPTEEYLE---AMMNEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGMIQEEFLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
GNFNYVAFTRI---------------------------------------
-------LKHGAKD-----------------------------KD-----
---------------------------------------------
*
>P1;ENSGACG00000004252

----MSSKRAKGKTTKKRPQRATSNVFAMFDQS-QIQEFKEA--------
-------------------------------FNMIDQ-------NRDGFV
DKEDLHDMLASLGK----NPTDEYLE---AMMMEAPGPINFTMFLTMFGE
KLNGTDPED-------VIRNAFACFDEEGTGSIQDDYLRELLTTMG----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------D-RFTDEEVDELFREAPIDKK
SNFNYVEFTRI---------------------------------------
-------LKHGAKD-----------------------------KDD----
---------------------------------------------
*
>P1;ENSLOCG00000008262

----MAEQ-SDSPVHVQNPQPAPTTSWPITRESYELQEVIGSGATAVVQA
ALCKPRQERVAIKRINLEKCQTSMDELLKEIQAMSQCNHPNVVTYYTSFV
VKDELWLVMKLLSG----GSMLDIIKYIFSKGEHKNGVLDEPIIATILKE
VLEGLDYLHRNGQIHRDVKAGNILLGEDGSVQIADFGVSAFLATGGDVTR
NKVRKTFVGTPCWMAPEVMEQVRGYDFKADIWSFGITAIELATGAAPYHR
YPPMKVLMLTLQNDPPTLETGVEDKEMLKKYGKSFRKLITLCLQKDPTKR
PTAAELLKCKFFQKAKNREYLIEKLLHKAPNITQRAKKEPEQKPGKTTLV
PGSEREHEGIRRVRRVPGSSGHLHKTEDGDWEWSDDEMDEKSEEG----K
AAFNQGRSRRVQQQNEANEVNANNIPIGGLSIQHPQVQPYEHSPYIQGQT
AVNMVLRLRNSRKELNDIRFEFTPGRDTADGVSQELFSAGLVDGHDVVIV
AANLQKIVDDPVTYKVLTFKLASGCDGSEMPDEVKLIGFAQLSVS
*
