>P1;ENSTRUG00000012428

---------------YKGGLNN----------------------------
--R---S----------------------------D--------------
--------------------------------------CKRSKRRWWQQE
MGLFYCSSVFSV-SIEQIAVLHKRFRQLSHNDEKLRREHFMAIPDLACNP
IRSQIIQAFFDRRNFHQKDDGTVEEISF-EQFLVVMSH---FRPPSP-HM
TEEQRESVRRDKLRFLFNMHDTDNDGMITLE------EYRHVVEE-----
------------------------------------------LLSRSGAL
GKETAKSIADAAMLEVAS--------------------------------
ISMGHMEPDEFYEGITFEHFLKLLGSFEIESKMS------------IRFL
NMDTFTL-C---K-
*
>P1;ENSORLG00000008146

----------------MGSLQS----------------------------
--S---P----------------------------S--------------
--------------------------------------HQDYV-------
----DLAEKTGF-SFEQISILHKRFKQLSHNEDKLRREHFGQITDLHANP
IREQIVEAFFDRRNFYQEIEEPVSEISF-ENFLVVMSN---FRPPSD-NM
SQEKLVKVRKEKLRFLFNMHDTDKDGTITLE------EYRHVVEE-----
------------------------------------------LLSYYEAL
ETETARGIADAAMLEVAS--------------------------------
ITRGHMEPDEFYEGITFEHFLKLLEGFDIESRMN------------IRFM
NMDTTTL-CK--L-
*
>P1;ENSGACG00000014094

----------------MGASQT----------------------------
--R---P----------------------------E--------------
---------------------------------------HRHQ-------
----DLADRTGF-SLEQIKNLHKRFQQLSGDEDTISKENLESIPTLANNP
IRKQIIGAFFDKRNQHRGEAGSCDQIGF-EQFLMVMSH---FRPPTL-KM
TAEEKEAMRREKLRFLFNMHDTDNDGTITLV------EYRKVVEE-----
------------------------------------------LLSKSGSI
GQEAAEAIADAAMLEVAS--------------------------------
TNVPTMGPDDFYEGITFEHFEQILKGLEMESRMH------------IRFL
DVDTTTMRCGKSTS
*
>P1;ENSORLG00000000922

----------------MGAATT----------------------------
--R---I----------------------------G--------------
---------------------------------------QQDP-------
----ELVDRTGF-SPEQINNLHKRFLQLSGNKDTISRENLNDIPALTYNP
IKSQIIEAFFDKRNQHDSEVGSLEEITF-EQFLMVMSH---FRPPTL-EM
TAEEKQAMRKEKLRFLFNMHDTDGDGKITLE------EYRKVVEE-----
------------------------------------------LLS-SGSI
EQESAKEITDAAMLEVAS--------------------------------
TNVPHMGPEDFYEGITFEHFEQILKGLEMESRMH------------IRFL
DTA--TVHCGKS--
*
>P1;ENSTNIG00000015605

----------------MGASQT----------------------------
--R---S----------------------------E--------------
---------------------------------------HKYQ-------
----SLVEKTGF-SLEQIKNLHKRFQQLSRNEETISREDLNSIPALANNP
IRKQIVDAFFDKRNQHQNEVGSLQEISF-EQFLMVMSH---FRPPTL-KT
TEEEKEALRKEKLRFLFNMHDTDHDGTITLE------EYRKVVEE-----
------------------------------------------LLSKSGAI
GQEAAQAIADAAMLEVAS--------------------------------
TNVPHMDPDDFYEGITFEHFEQILKGLEMESRMH------------IRFL
DVDTTTMRCGKSSS
*
>P1;ENSGACG00000016945

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------MSH---FRPPSL-HV
TEEQREAVRRDKLRFLFNMHDTDNDGTITLE------EYRHVVEE-----
------------------------------------------LLSLSEAL
EKDTAKSIADAAMLEVAS--------------------------------
ISMGHMEPDEFYEGITFEHFLKLLNGFEIESRMN------------IRFL
NMDTTTL-C---K-
*
>P1;ENSXMAG00000002448

----------------MGATQT----------------------------
--H---S----------------------------E--------------
---------------------------------------YQYE-------
----NMVGKTGF-STEQIKNLHMRFQQLCGNEKTLRKEHLENIPTLADNP
IKTEIIKAFFDKRNQHNNELGSYEEIGF-EEFLMVMSH---FRPPSI-KT
SAEEKAAMRKRKVRFLFNMHDTDGDGKITLE------EYRKIVEG-----
------------------------------------------LLSESESI
GQEVARAIADAAMLEVAS--------------------------------
TNVPNMGPDDFYEGITLEHFEQILKDLEMESRMY------------VRFL
DMNTANLHCGK---
*
>P1;ENSONIG00000013959

----------------MGALQS----------------------------
--L---P----------------------------G--------------
--------------------------------------RPEYS-------
----DLAEKTGF-SFEQIGVLHKRFKQLSHNEETLRRDHFNEIHDLAFNP
IRAQIIEAFFDRRNFHQDGEGKVQEIGF-EEFVVVMSH---FRPPSD-HM
TEEQREKTRREKLRFLFNMHDTDNDGTITLE------EYRHVVEE-----
------------------------------------------LLSRSGTL
EKETAKCIADAAMLEVAS--------------------------------
ISVGHMEPDEFYEGITFEHFLKLLDGFEIESRMT------------IRFL
NMDTTTL-C---K-
*
>P1;ENSTRUG00000016423

----------------MGASQT----------------------------
--R---S----------------------------D--------------
---------------------------------------HKYQ-------
----NLVEKTGF-SLEQIKNLHKRFQQLSGNEETISKENLNSIPALANNP
IRKQIVDAFFDKRNQHQNEVGSFHEISF-EQFLMVMSH---FRPPTL-KT
TEEEKEALRKEKLRFLFNMHDTDNDGTITLE------EYRKVVEE-----
------------------------------------------LLSKSGAI
GQEAAKTIADAAMLEVAS--------------------------------
TNVPHMAPDDFYEGITFEHFEQILKGLEMESRMH------------IRFL
DVDTTTMRCG---K
*
>P1;ENSAMXG00000007002

----------------MGAFHS----------------------------
--V---P----------------------------D--------------
--------------------------------------DHQYH-------
----ILSEKTGF-SLEQIGILHNRFKQLSHNSDVLRRDDLNTIPDLASNP
IKSQIVEAFFDGRNLRKDSEGPVQEIGF-EEFLIVMSY---FRPPSV-HM
TEEQREGIRRDKLRFLFNMHDTDNDGTITLE------EYRHVVEE-----
------------------------------------------LLSRSGSL
GRETAKGIADAAMLEVAN--------------------------------
MSVGRMGPDEVYAGITFEHFLKILKGIEIETRMH------------IRFL
NMDTTVL-C---K-
*
>P1;ENSDARG00000028346

----------------MGAAQS----------------------------
--G---G----------------------------Q--------------
--------------------------------------AQKYQ-------
----DLADKTGF-STEQIRKLHSRFQYLTQDEDTLRREHLENLTNLALNP
IKRQIIEAFFDKRNLGQNEKGCLQEIGF-EEFVTVLSV---FRPTKP-RT
AEDKKKTIKEEKLRFLFNMHDTDNDGVITLD------EYRRVVEE-----
------------------------------------------LLSSYETI
EAETAKAISDAAMLEVAS--------------------------------
VTVGRMSPDEFYEGITFEQFMQILKDIEIETKMN------------VHFW
NLDTRTMHCGK---
*
>P1;ENSTNIG00000009068

----------------MGALQS----------------------------
--S---P----------------------------A--------------
--------------------------------------PRDQA-------
----DLAEKTGF-SLEQIAVLHKRFKQLSHNEETLRREHFKAIPDLACNP
IRSQIIQAFFDRRNFHQNDDGTVEEISF-EEFLVVMSH---FRPPSQ-HM
SEEQRESVRKEKLRFLFNMHDTDNDGMITLE------EYRHVVEE-----
------------------------------------------LLSRSGAL
GKETAKSIADAAMLEVAS--------------------------------
ISMGHMEPDEFYEGITFEHFLKLLGSFEIESKMS------------IRFL
NMDASTL-C---A-
*
>P1;ENSXMAG00000001381

----------------MGALKS----------------------------
--T---P----------------------------D--------------
--------------------------------------PIEYA-------
----DLSEKTGY-SLKQIRVLHKRFRELSDGDDVLRREHFRCISSLKYNP
IRVEIIEAFFNRRNFSPSHQGSADEIGF-EEFLVVMSH---FRPPSP-KI
TDEQRKNIRREKLQFIFNMHDSDGDGLVTLE------DYRHVVEE-----
------------------------------------------LLSRSGAL
GKETAKAIADAAMFEVAR--------------------------------
-TVGHKDPNEFYEGITFEHFLKLLSNFDIESRMN------------IRFL
KSDVNPF-CQLCC-
*
>P1;ENSDARG00000030839

----------------MGSFQS----------------------------
--L---P----------------------------D--------------
--------------------------------------DHQYR-------
----TLSQKTGF-SLEQIGILHNRFKQLSQNEDTLRRDDLKTIQDLESNP
IRSQIIEAFFDKRNFQKDATGSVQEIGF-EEFLTVMSY---FRAPAH-QI
TEEQREEIRRAKLRFLFNMHDTDNDGTITLE------EYRHVVEE-----
------------------------------------------LLSRSGAL
GRETAKGIADAAMLEVAS--------------------------------
ITVGPMAPDEFYEGITFEQFLKILKGVEIETRMH------------IRFL
NMDTTVL-C---K-
*
>P1;ENSLOCG00000006474

PCRLRQSACLRFRSPAMALLKSCKVFSSLGAYSPSLAAFPVRARCSSWWS
SVEMGPPDPILGVTEAFKRDGNPKKMNLGVGAYRDDQGKPYVLSCVRKAE
ALIAAKKLDKEYLPIGGLAEFAKASAELALGPSNEVLKSGRYI-------
----TVQTISGTGSLRVGANFLSRFHTASRDVYLPKPSWGNHTPIFRDAG
MQ-LKAYRYYDPKTCGFDFAGALDDISKIPEKSIILFHACAHNPTGVDPR
PEEWKEICDLVKKRNLFVFFDMAYQGFASGDIDRDALAVRHFIEQGHNIV
LSQSYAKNMGLYGERVGAFTVVCSDVEEAKRVESQLKILIRPMYSNPPMN
GARIAATIMNAPELRQEWLEEVKGMANRIISMREQLVSNLKKEGSIHNWQ
HVVNQI-GMFCFTGLKPEQVERLIKEFSVYMTKDGRISMAGVSSANVGYL
AHGIHQV-T----K
*
