>P1;ENSTNIG00000007008

VFLSLLMDT-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
VAEEDKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTR----------
-------------------------------PPFLTFQGEVLTDVNKIEE
YLEEMLAP--------PKYPTLAAKNRQS--DTAGNDI------------
--------------------------------------------------
------FAKFSTYVKNTRP-------------------------------
-DKHRAALEKSLDKA-LAQLDHYLTSPLPGEPQT------GTSSRKYLDG
EE---LTLADCNLLPKLHVVKVVTKKYRNYDIPSEFRGLWRYLSNAYSRD
EFTSTCPSDLEIELAYKDVAKRLGK-
*
>P1;ENSTRUG00000000491

S-----ATDRARRIMDNISDNEKTVRE-----ERGRGSDSSHSSESDHDS
SGEAVVQVHSPVQVHAS-ADEERSSPDYMETRDREERSRSSSSSSDDEKE
KAEEEAAATPAVEPLEEVNGEAHDGSRRSSSSSASSASSASPADPCDDPP
NPPRL---DDGMEGLLLAFKQQ--------ESVQHNAVALDKV----TLD
ASADPSQPLITLFVKAGNDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFVTFNGEVKTDINKIEE
FLEEMLSP--------PKYPKLAAKQRES--NTAGNDI------------
--------------------------------------------------
------FAKFSAYIKNTKL-------------------------------
-DAN-SALEKGLTRA-LIKLDDYLNNPLPDEIDADSLEEQKFSTRSFLDG
NE---LTLADCNLLPKLHIVKVVAKKYRNYEIPSEMSGVWRYLKNAYKRD
EFTNTCAADAEIEMAYKDVVKRLAK-
*
>P1;ENSDARG00000070584

M-----AANVQENIYEQVQEKTENFYE-----KPYDKTTNA---EPKYEN
HD-AGQQSP-EEPIYS-TLDQPEYTPDYMDTRGTSPDEEDQPSASSDREE
TADS----GVMVASLSNGDGDGY-G----SGRS---SSLENYGDPCDDQP
SL--------AQDDLLMAFSLPEDGSPEPEEIVDYSLKNMESCAAAEETT
EVADPNQPQVALFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFNGEVKTDVNKIEE
FLEEVLAP--------PKYPKLAARHRES--NAAGNDI------------
--------------------------------------------------
------FAKFSAFIKNTKP-------------------------------
-DAN-EALEKGLTKA-LKKLDEYLNSPLPDEVDADSMEEEKASNRRFLDG
ND---LTLADCNLLPKLHIVKVVAKKYRNFDIPSDLTGVWRYLNSAYAQE
EFTNTCAADNEIESAYLDVAKRLTK-
*
>P1;ENSORLG00000010204

S-----KSK-----------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------PSN
MSTDSKEPDIELFVKAGSDGESV---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPTDLHNLAPGTH----------
-------------------------------PPFLTFDGEVRTDTNKIEE
FLEATLCP--------PKYPKLAARHRES--NTAGNDI------------
--------------------------------------------------
------FAKFSAFIKNTKP-------------------------------
-EAN-DALEKGLTKA-LKKLDDYLNSPLPGEADANDS--EEGSSRSFLDG
NE---LTLADCNLLPKLHIVKVVAKKYRNYDIPADMKGVWRYLNKAYARD
EFTNTCADTTEIETAYKDVARRLAK-
*
>P1;ENSONIG00000012034

M-----TDT-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
AAEEDKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFEGEVYSDVNKIEE
FLEEKLAP--------PKYPKLAAKNRES--NTAGNDI------------
--------------------------------------------------
------FARFSAFVKNTKP-------------------------------
-DKN-QALEANLNKA-LAKLDEYLISPLPDEADE------GESTRKFLDG
NE---LTLADCNLLPKLHVVKVVAKKYRNYDIPSEFRGLWRYLGNAYKQD
EFINTCAADVEIELAYKDVARRLGK-
*
>P1;ENSTNIG00000009686

V-----GPG-----------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------T----MSA
MVFQDKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLRRKPADLHNLAPGTH----------
-------------------------------PPFVTFNGEVKTDINKIEE
FLEEMLGP--------PKYPKLAAKHRES--NTAGNDI------------
--------------------------------------------------
------FAKFSAYIKNTKP-------------------------------
-EAN-SGLEKGLTRA-LNKLDDYLNNPLPDEIDADSMEEQKFSTRSFLDG
DQ---LTLADCNLLPKLHIVKVVAKKYRNYDIPSDMSGVWRYLKNAYKRD
EFTNTCAADGEIETAYKDVAKRLAK-
*
>P1;ENSGACG00000012318

M-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
TNSQDRDPDIELFVKAGNDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFNGEVKTDINKIEE
FLEETLSP--------PKYPKLAAKQRES--NTA----------------
--------------------------------------------------
-------AKFSAYIKNTRP-------------------------------
-EAN-AVLEKGLTKA-LKKLDDYLNSPLPDEIDADSLEEEKGSERSFLDG
SE---LTLADCNLLPKLHIVKVVAKKYRNYDIPSDMSGVWRYLKNAYTRD
EFTNTCAADGEIETAYMDVARRLA--
*
>P1;ENSAMXG00000000879

M-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--GEDKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFNGEVQTDVNKIEE
YLEEMLAP--------PKYPKLAAKNRES--NTAGNDI------------
--------------------------------------------------
------FSKFSAYVKNTQP-------------------------------
-EAN-ASLENGLLKA-LRKLDNYLNTPLPEEIDADSMEEEKCSTRKYLDS
NE---LTLADCNLLPKLHVVKVVSKKYRNFDIPSEYTGVWRYLQNAYARD
EFINTCAADKEIELAYQDVARRLTK-
*
>P1;ENSORLG00000004371

FLLT-MTDT-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
VGEEDRDPDIELFVKAGSDGEAI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTN----------
-------------------------------PPFLTFKEEVLTDVNKIEE
YLEQMLAP--------PKYPKLAPKNRDS--NTAGIDI------------
--------------------------------------------------
------FAKFSAYVKNTRP-------------------------------
-DKN-RALEQALNKA-LMKLDEYLMSPVPEEVQKGRHH-EEPSTRKYLDG
DE---LTLADCNLLPKLHVLKVVAKKYRNYEIPSDLKGVWRYLGNAYERD
EFINTCPADEEIELAYRDVAKRLGK-
*
>P1;ENSONIG00000001031

M-----QLNTGEHRKWKIQKEMDNIYETLDHDDVPAGRDRV---EPKYEN
PGEAREQLYSEVLVHRSSREEDRSSPDYMEIREGGKHSDSSSSSSDDEDA
KTRKEKVE----AQVQEVSGEAHNGSRRSSSSS---DSSASPGDPCDDPP
FQRKIQEEDNAEDGMMMAYSRPKT-DPEPQESVDYTLKTLESVTLDESSS
APADPNQPNIALYIKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVMFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFEGEVKTDVNKIEE
FLEETLCP--------PKYPRLAAKHRES--NTAGNDI------------
--------------------------------------------------
------FAKFSAYIKNTKP-------------------------------
-EAN-AALEKGLTRA-LKKLDDYLNNPLPDEIDANSMEEEKGSNRCFLDG
NE---FTLADCNLLPKLYIVKVVAKKYRNYDIPAEMSGVWRYLNNAFTHD
EFTNTCAADTEIETAYKDVARRLAK-
*
>P1;ENSGACG00000014937

M-----TDT-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
AAGEDKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFQGEVLTDVNKIEE
YLEEMLVP--------PKYPKLASKNRES--NTAGNDI------------
--------------------------------------------------
------FAKFSAYVKNKRP-------------------------------
-DKN-RALEKSLDKS-LAKLNTYLESPLPDELQVGHNRGEGESKRKYLDG
DE---LTLADCNLLPKLHVVKVVSKKYRNYEIPSEFRGLWRYLGNAYERD
EFTNTCAADVEIELAYKDVAKRLGKS
*
>P1;ENSDARG00000075993

M-----TS------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-NEEGKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTP----------
-------------------------------PPFLTFNGEVRTDVNKIEE
FLEEMLAP--------PKYPKLAAKNKES--NTAGNDI------------
--------------------------------------------------
------FAKFSAYIKNTKP-------------------------------
-EAN-ASLEKGLLKV-LKKLDSFLNSPLPDEIDAESTGEEKSSNRKYLDG
NE---LTLADCNLLPKLHVVKVVSKKYRNFEIPSDLSGVWRYLQNAYSRD
EFTNTCAADREIELAYQDVAKRLGK-
*
>P1;ENSXMAG00000007839

M-----TDT-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
VTEEEKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTH----------
-------------------------------PPFLTFEGNVLTDVNKIEE
YLEEILGP--------PKYPRLATKNRES--NVAGNDI------------
--------------------------------------------------
------FARFSAYVKNTRP-------------------------------
-EKN-RSLEKSLNKA-LAKLDEYLMRPIPDEVQSGRHSGEGPSSRKYLDG
DE---LTLADCNLLPKLHVVKVVAKKYRNYDVPSEFKGVWRYLDNAYKRD
EFTNTCAADVEIELAYQAVAKRLEK-
*
>P1;ENSTRUG00000012502

LFSSIMTDT-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
AAEEDKDPDIELFVKAGSDGESI---------------------------
---------GNCPFSQRLFMILW---------------------------
------------LKGVVFNVTTVDLKRKPADLHNLAPGTR----------
-------------------------------PPFLTFQGEVLTDVNKIEE
YLEEMLAP--------PKYPKLAAKYRQS--NTAGNDI------------
--------------------------------------------------
------FAKFSTYVKNTRP-------------------------------
-DKH-RTLEKSLDKA-LAQLDDYLTTPLPDEAQT------VKSTRKYLDG
EE---LTLADCNLLPKLHVVKVVAKKYRNYDMPSVFTGLWRYLSNAYSRD
EFSSTCASDLEIELAYKDVAKRLGK-
*
>P1;ENSLOCG00000011884

P----MRPW-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
EIAVNRRPPTAPFNQRRFPGEPCNSPAHLRRRNSPPVRRQWGRRDRPSLH
NSLHQDENFHHPLFSQHQQQISLDESRPYSHTSVPPRMLHPAAHPPQQNP
IMVDLHEQMHQGPVPISYTVTTVTTHGFPLHAGQPIPGCNTQQLPACSVM
FSGQHSLLCCLPPPLIQACTMQHLPVSYQAFPPLISSEHFILHPPPPVPP
HQPPHLAPLSQFVPLQPQHPRMPLQRVENEVDLRGDQHPVGGFSYPPTHH
PPAMPPSVPLQYLPHDPLHQELPFGVPYPHVLPRRVSGQRYRLQQPLPPP
PPPPPYYPSFLPYFLSMLPVPPTAVGPAISLDLDVDDVEMENYEALLNLA
ERLG-EAKPRGLTKADIEQLPSYRFNPENHQSEQ------TLCVVCFSDF
ESRQLLRVLPCNH-----------------EFHAK------CVDKWLKTN
RTCPICRADA--SEVHRDVE------
*
