>P1;ENSDARG00000034453

--------------------------------------------------
--------MKVKQGC---DAGVPYTTEEDLLNSPEITPEDVLGLQKIT--
DNYLCGPEQNVHKIDFTRFKIRDMETGTVLFEITKPPTS--ETGEDRMDF
EQNAGRFVRYQFTPAFLRLRQVGATVEFTVGDSPINNFRMIERHYFRGQL
LKS--FDFEFGFCIPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDIMREMILHPYETQSDSFYFVDNKLVMHNKADYSYNGGP
*
>P1;ENSAMXG00000024390

--------------------------------------------------
--------MK------------------------KILMDN-ILLCFFT--
LDYLCSPEDNVYNIDFTRFKIRDMETGTVLFEITKPPAL--DKGGDKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMIERHYFRDQL
LKS--FDFEFGFCIPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDIMREMILHPYETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSGACG00000008624

--------------------------------------------------
--------MKVQQGCHSSNMGIPVTTEEELRRNTVITPDDVLGLQKIT--
KNYLCSPEENVHMIDFTRFKIRDMETGTVLFEITKPPTDVSRQAEGRKQC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDQL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDIMREMILNPYETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSTRUG00000012195

MSYSCTNRGNSQDPSSAKKAAGNNPGRDT------GG-TD----------
SSPKQTATMKVKKGCNSAEVGVPVTTEEDLLTSAVVTPEDVLGLQKIT--
ENYLCSPDENIFNIDFTRFKIRDMETGTVLFEITKPPST--DKTGDKRDM
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDLPIENFRMIERHYFRERL
LKS--FDFEFGFCMPKSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDSIREMILHPYETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSORLG00000002577

SS----------------------------------G------------T
SSPKQT-AMRVKKGCNSAEVGVPETTEEDLLANAVISPEDVLGLQKIT--
ENYLCSPDENIYNIDFTRFKIRDMETGTVLFEITKPPST--DKSGEKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPIENFRMIERHYFREKL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDVIREMILHPYETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSGACG00000020475

---------------AAKKPAGDNPGRDT------GG-TD------RSSS
SSPQDTAAMKVKKGCNATDAGVPVTTEEDLLGGSGVTPEDVLGLQKIT--
ENYLCSPDENIFNIDFTRFRIRDMETATVLFEITKPPAA--DKAGEKRDV
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPIENFRMIERHYFREKL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDIIREMVLHPYETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSTRUG00000016070

--------------------------------------------------
--------MKVQQGCNSSDMGIPVRTEEELRRNTVITPEDVLGLQKIHKD
VNYLCSPEDNVHMIDFTRFKIRDMETGTVLFEITKPPTP----AGDKKLS
DPNAGRFVRYQFTPAFLHLRQVGATVEFTVGETPINNFRMIERHYFRDQL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPALS
EEIMREMILHPYETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSONIG00000008183

--------------------------------------------------
--------MKVQQGCNSSDMGIPVTTEEELRKHTVITPEDVLGLQKIT--
KNYLCSPEENVHMIDFTRFKIRDMETGTVLFEITKPPTP----AGGKKQC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDQL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPTLS
EETMREMILHPYETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSONIG00000008702

MSYSCTSRGNSQDPSSAKKPAGSNPARDA------GG-TDSG--TDSTSN
GSPKQTAAMKVKKGCNSTDVGVPVTTEEQLLASTVITPEDVLGLQKIT--
ENYLCSPEENIYNIDFTRFKIRDMETGTVLFEITKPPST--DKASEKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDRPIENFRMIERHYFREKL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDIIREMILHPYETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSTNIG00000016130

MSYSCTNRGNSQDPSSAKDAAGDNPGRDT------GG-TD----------
ASPKQTAAMKVKKGCNSAEVGVPVTTEEDLLSSAVITPEDVLGLQKIT--
ENYLCSPDENIFSIDFTRFKIRDMETGTVLFEITKPPTT--DKTGDKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDLPIENFRMIERHYFRERL
LKS--FDFEFGFCMPRSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDSIQEMILHPYETQSDSFYFVDNKLVMHNKADYSYNGGR
*
>P1;ENSXMAG00000007806

MSYSCTSRGNSQDPSNA------NPARTT------GG-TDGG--TDSTGN
GSPKQTAVMKVKKGCNSAEVEVPVTTEEELLGRTVITPEDVLGLQKIT--
EHYLCSPDENVFNIDFTRFKIRDMETSTVLFEITKPPST--DKSGEKRDI
DLNAGRFVRYQFTPAFLRLRQVGATVEFTVGDMPIENFRMIERHYFREKL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDTIREMVLHPYETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSXMAG00000011781

--------------------------------------------------
--------MKVQQGCNSSDMGIPVRTEEELRKNTVITPEDVLGLQKIT--
ENYLCAPEENVHMIDFTRFKIRDMETGTVLFEITKPPTP-----GGLKQC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDKL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPTLS
EETMHEMIQHPYETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSORLG00000008116

--------------------------------------------------
--------MKVQQDCNSADMGIPVRTEEELRKNTVITPEDVLGLQKIT--
KNYLCSPEENVHRIDFTRFKIRDMETGTVLFEITKPPTP-----GGVKLC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDKL
LKS--FDFEFGFCMPSSK----------------------------NTCE
HIY-----------------------------------------EFPALS
EEMMREMIQHPYETQSDSFYFVDNKLVMHNKADYSYCGGP
*
>P1;ENSAMXG00000017747

--------------------------------------------------
--------MRVKAGN---DAGLPCTTEQELLQNQTIRPEDVLGLQNIT--
ENYLCSPDDNVHKIDFTRFKIRDMETGIVLFEITKPPLA--ESSEDRKDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMIERHYFRGQL
LKS--FDFEFGFCIPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EELIHEMILHPYETQSDSFYFVDNKLVMHNKADYSYTGAQ
*
>P1;ENSDARG00000044362

MSYSCTSTGNSQDPSSSKKSGGVNPGSCSSSNGDTGNGNNRHSIRGSKAN
SKPDSTEAMKVKKGCNTTDLGVPVTTEEELLANKTISPEDVLGLQKIT--
ENYLCSPEDNLYNIDFTRFKIRDMETGTVLFEITKPPST--DR-GDKRDV
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMIERHYFREQL
LKS--FDFEFGFCIPSSK----------------------------NTCE
HIY-----------------------------------------EFPPLS
EDLIREMILHPYETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSLOCG00000012706

MSCTVSSFFATLA-------------------------------------
-VLLLWRVKEIAEGCSCS----PVHPQQAFCNADVVIRAKVIGGKEVD--
S-------------------------------------------------
-----------------------------GNDIYGNPIKRIQYEIKQIKM
FKGPDRDIETVFTAPSSAVCGVTLETNGKKEYLISGKAEADGKMHVTLCD
FIVPWESMSATQKKSLNQRYQMGCECKVRRDRSGHGCLGSLLSCLWPSLC
SDVQ------------------------------------
*
