>P1;ENSORLG00000007358

----NMASSDV-----HVRLCEQEILKYDLEIKALIQDISECSGPPSKLT
ELNGDIKKCFHNLRSRIEDLKQTALEQDKLSDKQTFMLQVEGHQKQMLSN
QTAWRKANLASKFSIDNTEKQSLLINGTD-NTARQRKLTKEGLAQTTSDI
TENLMSISRMMAQQVQQSEESI-T--SLATSSKTVQETNEEFKAMTGTIH
FGRKLITKYNRRELTDKLLIFLALALFFATVLYILKKRLFPFL
*
>P1;ENSXMAG00000010268

----M-ATSDV-----HVRVCEQEILKYDLEIKALIQDITECDGPQSKLT
EINTDVKKHFHNLRLRIQDFERMAMEQDRESDKQALLSQVEGHRKQMLSN
QTAWRKANLASKLSMDKMEKQALLN-GAD-GAVRKRKMTKEGLAQSASDI
TENLMSISRMMAQQVQQSEDSI-T--TLATSSRTIQETNEEFKAMTGTIQ
LGRKLITKYNRRELTDKLLIFLALALFFATVLYILKKRLFPFL
*
>P1;ENSAMXG00000018460

----M---ADV-----HVRICEQEIIKYDLEIKALIQDISECTGPHNELT
ELNCKVKERFSRLRQRIQDLEQMGKEQDKESDKQVLLKEVEAHRKQMLSN
QTAWRKANLASNLAIDKLEKEDLLN-VGG-TGARQRKMTKESLAQTSSDI
TESLMSISRMMSQQVKQSEETI-S--TLSTSSRTVLETNEEFKAMTGTIQ
LGRKLITKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFL
*
>P1;ENSGACG00000018435

----NMASSDV-----HVRICEQEILKYDIEIKALIQDITEYKGPKNKLT
ELNADVKKSFHKLRLRIQDFEQIAMEQDKESEKQALMSQVEGHRKQMLSN
QTGWRKANLASKLSLDNVEKQALLY-GAG-GGVRQRKTTKEGLAQTTSDI
TENLMSISRMMAQRVEQSEETM-T--SLATSSRTIQETNEEFKAMTGTIQ
HGRKLITKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFL
*
>P1;ENSTRUG00000013480

----MSTLGDV-----HVRICGQEIIKYDLEIKAQIQDIRDCHGPQSSLL
ELNSQVKEKFIKLRMRIQDLELMAREQDRETDRQSIQAEAESQRRQMLSN
QTAWRKANLCCQLLIDNMEIDELLH-GGDNQSMRHRKVTKESLVESSSNI
TESLMSISRMMAERVKQSEDSI-G--VLATSSRTVQETNEEFKNMTGTIH
LGRKLILKYNRRELTDKLLIFLALALFLATVLYILKKRFFPFI
*
>P1;ENSDARG00000078259

----MAASADV-----HVRICEQEIIKFDLELKALVQDVNECTGPQSKLT
DLNLIVKEKFNKLRQRIQDLEQMGKEQDKESDKLMLLLKVEGHRKQMLSN
QTAWRKANLACKLSIDKLEKEDLLN-SED-MSVRHRKMTKESLAQTSSDI
TESLMSISRMMSQQVQQSEETM-G--TLATSSRTVLETHEEFKAMTGTIQ
LGRKLIIKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFF
*
>P1;ENSTRUG00000010743

----NMASADV-----HVRICEQEILKYDLEIKALIQDVKECPGPQSKLT
ELNADVKKNFHNLRSRIQDLEQMAMEQDRESDKQVILSQVEGHRKQMLSN
QTSWRKANLASKLSIDNKEKQELLC-GPD-GAARHRKMTKECLAETSSGI
TENLMSISRMMAQQVQQSEETV-T--SLATSSRTIQETNDEFKTMTGTIQ
LGRKLITKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFL
*
>P1;ENSONIG00000017678

----M-ASSDV-----HVRICEQEILKYDLEIKALIQDISECTGPQSKLT
ELNGEVKKNFLSLRLRIQDLEQMAMEQDKESDKQALMTQVEGHRKQMLSN
QTTWRKANLASKLTVDNMEKQALLN-GAD-DSVRQRKMTKEGLAQTTSDI
TENLMSISRMMAQQVQQSEDTI-T--SLATSSRTIQETNDEFKTMTGTIQ
IGRKLITKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFL
*
>P1;ENSONIG00000008646

T--TMASSTDV-----HVRICAQEIIKYDLEIKALIQDIRDCPGPQSALV
ELNAQVKEKFNKLRLRIQDLEQMAKEQDKESDGLAIQTETESQWKQMLSN
QTAWRKANLACKLAIDNMEKDELLH-GGENHNTRQRKATKENLVETSSNI
TESLMSISRMMSEQVKQSEDTI-G--TLATSSRTVQETNEEFKSMTGTIH
LGRKLILKYNRRELTDKLLIFLALALFFATVLYILKKRLFPFI
*
>P1;ENSORLG00000002369

----MASSTDV-----HVRICAQEIIKYDLEIKALVQDIRDCSGPQYSLM
ELNSQIKEKFNKLRLRIQDLEQMAIEQDRETDRLAVQAETESQRRQMVSN
QTAWRKANLACKLAIDNMEKNELLH-AGENRSPRQRKVTKESLVETSGNI
TESLMSISRMMAEQVKQSEDTI-G--TLATSSRTVQETNEEFKSMTGTIH
LGRKLILKYNRRELTDKLLIFLALALFFATVLYILKKRLFPFI
*
>P1;ENSGACG00000020461

-------------------------------------------------M
ELNSQVKEKFNKLRIRIQDLEQMAREQDRETDRLAIQEETESQRKQMLSN
QTAWRKANLACKLAIDVTEKNELLQ-GVEHQGTRQRKVTKESLAETSSNI
TESLMSMSRRMAEQVKQSEDTI-G--TLATSSRTVQETNEEFKSMTGTIH
LGRKLILKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFI
*
>P1;ENSTNIG00000017073

----M-ASPDV-----HVRICEQEILKYDLEIKALIQDIKRCTGPQSKLT
ELNADVKKNFHNLRSRIQDLEQMAMEQDKESNKQTLLSQVEGHRKQMLSN
QTSWRKANLASKLSIDNMEKQELLE-GPD-GSVRQRKKTKESLAQTSSDI
TENLMSISRMMAQQVQQSEETV-T--SLATSSRTIQETNDEFKTMTGTIQ
LGRKLITKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFL
*
>P1;ENSDARG00000104280

MTTNMASSSDV-----HVRICGQEIIKYDLEIKAIIQDIRECCGPQAVLM
ELNSTVKEKFSLLRQRIQDMEQMAKEQDRETDKQALLSETEGHRKQMLSN
QMAWRKANLACKLAIDNLEKDELLQ-GGD--AVRQRKATKESLVQTSSDI
TESLMSISRMMSQQVQQSDETI-G--TLVTSSRTVQETNEEFKAMTGTIH
LGRKLILKYNRRELTDKLLIFLAIALFLATVLYILKKRLFPFI
*
>P1;ENSTNIG00000016143

----MSAYGDV-----HVRICGQEIIKYDLEIKALIQDIRDCHGPQSSLL
ELSSQVKDKFNKVKKRIQDLELMAKELDRESDRQSVQAEADSQRRQMLSN
QTAWRKASLACQLAIDNLEKDELLH-GGDNQSTRQRKATKESLVESSSSI
TESLMSISRMMAEQVKQSEDSI-G--VLATSSRTVQETNEEFKNMTGTIH
LGRRLILKYNRRELTDKLLIFLALALFLATVLYILKKRLFPFI
*
>P1;ENSXMAG00000000497

----MASSEDV-----NVRICGQEIIKYDLEIKALTQDIINCPGPHSALA
ELNSRVKEKFNKLRLRIQDLEQMAQEQDTESTRLPILMEMESQRRQMLSN
QTAWRKANLACKLAIDNMEKDELLH-GGESPSTRQRKVTKESLVESSSNI
TESLMSISRMMSEQVKQSEDTI-G--TLATSSKTVQEANEEFKTMTGTIH
LGRKLILKYNRRELTDKLLIFLALALFFATVLYILKKRLIPFV
*
>P1;ENSLOCG00000011653

----MQSTLGLWAGVLAVAFCTLICAGTPAEAYPPRPDNPG---------
--------------------------------------------------
-----------------------------------EDAPAEDLARYYSAL
RHYINLITRQRYGKRS-SPDSLFSDLLLRESTESIPRTRFEDPTLW----
-------------------------------------------
*
