>P1;ENSORLG00000008777

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------MNTCKY
NGGVVRPLVGSLASSSRRNLAELDSETQPLQTLHSSGLEVVVSKGNSGED
PSKASNESLVREGSGRGGGRAPQKKNRDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKSTVSEHVYVFDLRCVFVSLYVFFPFG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQAQKLRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDSVTGSLQALP
CLISQAISQQQQDFLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FVHR----------------------------------FRPASLASERS
ERSERSWTSTTRRRRS-------PSTAPHTSSDSG
*
>P1;ENSAMXG00000014379

MRLVLVKPANETSLLDSTGVARSPRAPDPCSAQRPEQQQQQQQQHQPAGG
EEEEEEEEEEEEEEEEVMQHRQPAAVHHQYQQYQQQHHQYQQQHQQQQQQ
QQHQQPLPPPLPPLCSLPPPPPPA----HSNHQRRCSRTQPGRS------
-------------------CSAYPRPPPAPSN-VKSPSRQTH------AA
SPTPPPP---PPPRR---SCQHEL--------------LVLESKQQQQH-
-QQQRCVCGTPPVQSDPFAGLLLL---QSPVTSDPPAEPQEPILQVQQQR
LVRSSLP-NCCV----------QQPALLQQHTQPQQQQQAPHAEWQQRKQ
QDREHDAKPKPQPHCLC--------LQPG----------SQPATARCGKS
SP---GGRR--NEGHQVSPDASRLSHAWSRSSLSPSGPPVPQIAMNSCKY
NGGVVRPL-SSLG-ASRRNLADLDSETQPLQTLHTSGLEVVVSKGN-GDD
PGKASRESLVREG----GSNAPQKRNKDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTLILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERILFIVLELLVCAIHPIPGHY
VFTWTARLAFTYAPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGQLEEKLDSITSSLQALP
GLLSQAILQQQHHLLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-LIQH----------------------------------G--LTLTRPSS
QASERSWSSSVRRRRS-------PSTAPHTSSDSG
*
>P1;ENSXMAG00000008788

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------ESGSVQ
NGDAVRPL-SSLG-TLSSSFADFPSDQQQLQLLQSAILEDAFSKVI-GDD
SSKANSENLITT-----EGNKPQKKTKDISYRLGQRRALFGKRKQLSDYA
LVCGMFGIIAMVIETELSRTFYTKESI----YSYVLKGL-ISISTAILLG
LILMYHAREIQLFMVDNGADDWRIAMTFERILFIVLELLICAIHPIPGQY
VFTWTARLAFNYTASVADADVDIILSVPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFDTRFVMKTLMTICPGTVLLVFSVSCWIIAAWTVR
VCESRYHDAQEVTSTFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKSELTRAEKHVHNFMMDTQLYKKIKNTAANVLR
ETWLIYKNTKLVKKIDHGRVRQHQRKFLQAIHQ---LRRLKMEQRKLTDQ
ANTVADLAKTQNMMYDLVLDLQHRTGELDRRIVALEEKLDSILIGVQSLP
VVLSQAIAKLQKDFLDD---------------------------------
--------------------------------------------------
--------------------------------------------------
-LACR---------------------------------------------
-----------------------------------
*
>P1;ENSONIG00000010506

M-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------ATTEQKKLSHAGSKPSLSESCGRLPQIAMNTCKY
NGGVVRPLVGSLASSSRRNLAELDSETQPLQTLHSSGLEVVVSKGNGGED
PSKASNESLVREGSGRGGGRAPQKKNRDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDSVTGSLQALP
CLISQAITQQQQDFLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FVHR----------------------------------FRPASLASERS
ERSERSWTSTARRRRS-------PSTAPHTSSDSG
*
>P1;ENSTNIG00000010071

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------SGSSLSEVGSSQYPLRLLHSAILEDAFSKGV-GED
SSKANSDNPTRE-----EGNAKQKKTKDIGYRLGQRKALFGKRKLLSDYA
LVCGMFGILVMVVETELSRGIYSKESV----YSHVLKGL-ISVSTAVLLV
LIVMYHAREIQLFMVDNGADDWRIAMTFERILFVVLELLVCSIHPVPGQY
VFSWTTRLARSYTPAAVDADVDVILSVPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFDTRFVMKTLMTICPGTVLLVFSVTCWIIAAWTVR
VCE-RYHNAQEVTSTFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKSELTRAEKHVHNFMMDTQLYKKIKNTAANVLR
ETWLIYKNTKLVKKVDRAKIRHHQRKFLQSIHQ---LRALKMEQRKLTDQ
ANTVADLAKTQNMMYELLAELQHRSEELDRRITALEGKLDSILLCIQSLP
VVLSQAITKLQKEFLDE---------------------------------
--------------------------------------------------
--------------------------------------------------
-LACRV--------------------------------HFLSSSLSSE--
----CC-SVPARQLYA-------EPSTPETSCS-S
*
>P1;ENSGACG00000015576

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------MNSCKY
NGGVVRPLVGSLASSSRRNLAELDSETQPLQTLHSSGLEVVVSKGNGGED
PSKASNESLVREGSARGGGRAPQKKNRDIGYRLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDSVTGSLQALP
CLISQAITQQQQDFLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FVHR----------------------------------FRPASLASERS
ERSERSWTSTARRRRS-------PSTAPHTSSDSG
*
>P1;ENSDARG00000091306

A------HRNEWVSVL----------------------------------
--YKAKEQPQQDADIEGMRHRHAGAVH--------------QQHSNDADA
RDSPKEASCPVAPLFSLPPPPPSIKERSTSSHNNRHVQSCPDRGTRNDEC
LPLTGHCSLAQGARTDRQPYDNLPHPFPGASSGYQCHSEGSHSPQQRSSV
SPQPSPSELLPPPLPSHISNTRDTRQKSANYKQDIVQRRVGEGGRRDQYQ
LLQQPCY----NQQRDPSFKPLLPNSSQGHVNEREEAEKERQLIEPQAQL
LLGSSLPINYCIGGSGQVCRNKQAPLLQHQHQQARAQEHSL---Q----Q
QHSDRDSRYQEGKIALCQPYRCERALERNSSVSSSEASSPPYGSSSQLWP
EPHDKEEKKNRAGKHKAHAERTKLSHAGSKASVSESSHSLPQIAMNSCKY
NGGVVRPL-GSLA-ASRRNLAEHDSETQPLQTLHSSGLEVVVSKGG-GED
PSKASNESLVRE-----SGNAPQKKNKDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYVPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDAVTGSLQALP
CLISQAITQQQQDLLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FVHR----------------------------------FRPPSLGS---
---DRSWTP-SRRRRS-------PSTAPHTSSDSG
*
>P1;ENSTRUG00000010293

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------SRSTLSDVGSGQHPLRLLHSAILEDAFSKVI-RED
SNKANSENATGE-----EGSAKQKKTKDIGYRLGQRKALFGKRKLLSDYA
LVCGMFGILVMVIETELSRVFYSKESI----YSHVLKGM-ISTSTAVLLV
LIVMYHAREIQLFMVDNGADDWRIAMTFERILFVLLELLVCAIHPVPGQS
VFSWTTRLARSYTAAAADADVDVLLSVPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKISFDTRFVMKTLMTICPGTVLLVFSVSCWIIAAWTVR
VCE-RYHNAHEVTSTFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKSELTRAEKHVHNFMMDTQLYKKIKNTAANVLR
ETWLIYKNTKLVKKVDRAKIRHHQRKFLQSIHQ---LRALKMEQRKLTDQ
ANTVADLAKTQNMMYDLLTELQHRREDLDRRIVALEEKLDSVLLCVQSLP
VVLSQAITKLQ---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------
*
>P1;ENSGACG00000008741

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------ETANIV
NGYTVRPL-SSHV-NLRSSLANPQSGEQPPQLLHSAILEDAFSKVI-RED
SSKASSENQTRE-----EGSVLQKKTKDISYRLGQRKALYGKRKQLSDYA
LVCGMFGIIVMVIETELSRGFYSKESM----CSYVLKGL-ISLSTAVLLG
LIVMYHAREIQLFMVDNGADDWRIAMTFERILFVAFELLICAIHPIPRQY
VFTWTARLAFSYTASVADADIDIILSVPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKISFDTRFVMKTLMTICPGTVLLVFSVSCWIIAAWTVR
VCE-RYHDAKEVTSTFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKSELTRAEKHVHNFMMDTQLYKKVKNTAANVLR
ETWLIYKNTKLVKKIDHARVRHHQRKFLQAIHQCFRLRRVKMEQRKLADQ
ANTVADLAKTQNMMYDLVLELQHRSEQLDRRIVALEEKLDSILRDVQSLP
VVLSQAITKLQKDFLD----------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------
*
>P1;ENSXMAG00000013964

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------HAGSKPSLSESSGRLPQIAMNTCKY
NGGVVRPLVGSLASSSRRNLAELDSETQPLQTLHSSGLEVVVSKGNGGED
PSKASNESLVREGSGRGGGRAPQKKNKDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDSVAGSLQALP
CLISQAITQQQQDFLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FVHR----------------------------------FRPASLASERS
ERSDRSWTSTTRRRRS-------PSTAPHTSSDSG
*
>P1;ENSTRUG00000008844

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------HAGSKPSLSESSGRLPQIAMNTCRY
NGGVVRPLVGSLASSSRRNLADIDSETQPLQTLHSSGLEVVVSKGNGGED
PSKASNESLVREGSGRRGGRAPQKKNKDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVANADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RNRPEGNLSSFFFLSLSISLCNCYRSISGGASKPRTDCQKVQLSLT
SLVSYGPKSEVWYIILTRTLLFLKEKSQVVVLLSCFGTKRLKTASLHVIR
ESHTFSFVTTRGGKYRFLLSPEHAQRVERATSR---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDSVTGSLQALP
CLISQAITQQQQDFLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FIHR----------------------------------FRPASLASERS
ERSERSWTSTTRRRRS-------PSTAPHTSSDSG
*
>P1;ENSDARG00000023546

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------MNSCKY
NGGIVRPL-GSLG-ASRRNLAELDSETQPLQTLHTSGLEVVVSKGN-GED
PSKQSSENLVTQR----PCSAPHKKNKDIGYKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLC
LIIMYHAREIQLFMVDNGADDWRIAMTYERILFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVH
VCE-RYHDKVEVTSNFLGAMW-LISITFLSIGYGDMVPNTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELEKRIGHLETKLDSINSSLQALP
GLLSQAIQQQQHHLLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-LTQR----------------------------------G--FTLTRPSS
QTSERSWASSVHRRRS-------PSTAPHTSSDSG
*
>P1;ENSONIG00000012591

MDEKT---------------------------------------------
------------------RQ------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------RQSQTVSQGSKVYLPKHTPPPLEALQSSGIL
NGDAVRPL-SSHG-TLRSSFSDLPSGQQPIQLLHSAILEDAFSKVI-RED
SSKANGEE----------GSTPPKKTKDISYRLGQRRALFGKRKQLSDYA
LVCGMFGIIVMVIETELSRGFYTKESM----YSYVLKGL-ISLSTAILLG
LIVMYHAREIQLFMVDNGADDWRIAMTFERLVFIVLELLICAIHPIPGKY
VFTWTTRLAFSYAASVTYADIDIILSVPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFDTRFVMKTLMTICPGTVLLVFSVSCWIIAAWTVR
VCE-RYHDAQEVTSTFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKSELTRAEKHVHNFMMDTQIYKKIKNTAANVLR
ETWLIYKNTKLVNKIDHARVRHHQRKFLQAIHQ---LRRVKMEQRKLTDQ
ANTVADLAKTQNMMYDLVSELQHRSGELDTRIVALEEKLDSILQCVQSLP
VVLSQAIAKLQKDFLDD---------------------------------
--------------------------------------------------
--------------------------------------------------
-LACRV--------------------------------HFLSSSLSSE--
----CC-SVPARQLCP-------GSTAPETPY--N
*
>P1;ENSTNIG00000011058

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------HAGSKPSLSESSGRLPQIAMNTCKY
NGGVVRPLVGSLASSSRRNLADIDSETQPLQTLHSSGLEVVVSKGNGGED
PSKASNESLVREGSGRRGGRAPQKKNKDIGDKLGHRRALFEKRKRLSDYA
LIFGMFGIVVMVTETELSWGVYTKESS----YSFALKCL-ISLSTVILLG
LIIMYHAREIQLFMVDNGADDWRIAMTYERIFFIVLELLVCAIHPIPGQY
VFTWTARLAFTYTPSVADADVDIILSIPMFLRLYLIG-RV--MLLHSKLF
TDASSRSIGALNKINFNTRFVMKTLMTICPGTVLLVFSISSWIIAAWTVR
VCE-RYHDKQEVTSNFLGAMW-LISITFLSIGYGDMVPHTYCGKGVCLLT
GIMGAGCTALVVAVVARKLELTKAEKHVHNFMMDTQLCKRVKNTAANVLR
ETWLIYKHTKLVKKIDHAKVRKHQRKFLQAIHQ---LRSVKMEQRKLNDQ
ANTLVDLAKTQNVMYDLVSELQERSEELDKRIGTLEDKLDSVTGSLQALP
CLISQAITQQQQDFLDG---------------------------------
--------------------------------------------------
--------------------------------------------------
-FIHR----------------------------------FRPASLASERS
ERSERSWTSTTRRRRS-------PSTAPHTSSDSG
*
>P1;ENSLOCG00000009048

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------MA----
--------------------AGPISERNQDATVYVGGLDEKVSEP-----
--------------------------------------------------
LLWELFLQAGPVVNTHMPKDRVT---------------------------
-----------------------------------------------G--
-----QHQGYGFVEFLSEEDADYAIKIMNMIKLYGKPIRVNKASAHNKNL
DVGANIFIGNLDP-EIDEKLLYDTF--------------SAFGVILQTPK
IM------RDPDTGNSKGY----AFINFASFDASDAAIEAMNGQYLCN--
--------RPITVSYAFK-KDSKGERH-----------------------
--------------------------------------------------
-------------------------GSAAERLLAAQ--------------
NPLSQADRP-HQLFADAPPPPSAPTPVLTALGPGVHHPGIPPPGAFPPPV
PPPGSMPPGMPPGLPPPPMPPSSGTPGPPTGGAPGSGPPPGPPPFPPGAI
PPPGMPQMPMPPPGPPGMVPPPPGPPGTGGQGHPRPPPPPGMPHHGHPHM
GMPHRGPFGPPMGHPGPMHPPGMRGPPPPMPPPGYGSGPPRPPPFGFQ--
----RGPHMPPRPNNRPPAPPRGPMRGPMPP----
*
