>P1;ENSGACG00000013981

MGCTLSAEERAALDRSKAIEKNLKEDGVTAAKDVKLLLLGAGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAIVRAMDTLGLEYGDKER
KADAKMVCDVVSRMEDTEPYSAELLSAMIRLWSDSGIQECFSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----TDYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSALSIC--------------FPEY---------
-------------------------TGPNTYDDAAAYIQAQFESKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSXMAG00000005960

MGCTLSAEERAALDRSKAIEKNLKEDGLTAAKDVKLLLLGAGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAIVRAMDTLGLEYGDKER
KADAKMVCDVVSRMEDTEPYSAELLGAMMRLWADSGIQECFSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSALSIC--------------FPEY---------
-------------------------TGPNTYEDAAAYIQAQFESKNRS-P
NKEIY----CHMTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSORLG00000008848

MGCTLSAEERAALDRSKAIEKNLKEDGMVAAKDVKLLLLGGGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAILRAMDSLGIEFGDKDR
KADAKLVCDVVSRMEDTEPYSAELLAAMKRLWADAGTQECFNRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----GDYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLTIC--------------FPEY---------
-------------------------TGANTYDDATAYIQVQFESKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSDARG00000016676

MGCTLSAEERAALDRSKAIEKNLKEDGITAAKDVKLLLLGAGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAIVRAMDTLGLEYGDKER
KADAKMVCDVVSRMEDTEPYSPELLSAMIRLWSDSGIQECFSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLSIC--------------FPEY---------
-------------------------TGPNTYDDAAAYIQAQFESKNRS-P
NKEIY----CHMTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSORLG00000013739

--------------------------------------------------
--------------------------------------------------
QADAKMVCDVVSRMEDTEPFSAELLSAMMRLWSDSGLQECFSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----TDYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESMKLFDSICNNKWFKDTS
IILFLNKKDLFENKITKSPLSIC--------------FPEY---------
-------------------------SGPSTYQDGIDYIKAQYDGKNKS-P
NKEVY----SHVTCATDTNNIQFVFDA---VTDVIIAKNLRGCGLY----

*
>P1;ENSDARG00000036058

MGCTLSAEERAALDRSRAIEKNLKEDGISAAKDVKLLLLGGGESGKSTIV
KQMKIIHEDGFSGDDVKQFKPVVYSNTIQSLSAILRAMETLGIEYSDKDR
LADAKMVFDVVGRMEDTEPYSTELLAAMIRLWTDTGTQACFNRSREYQLN
D----SAQYYLDSLQRIGS-------------------------------
-----PDYLPTEQD-ILRTRVKTTGIVETHFS------------------
-------------------------FKNLNFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVAMSGYDQMLHEDETTNRMHESLMLFDSICNNKFFVDTS
IILFLNKKDLFGEKIVKSPLSIC--------------FPEY---------
-------------------------TGPNTFEAAASYIQGQFETKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSTNIG00000009309

MGCTLSAEERAALDRSRAIEKNLKEDGMVAAKDVKLLLLGGGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAILRAMDSLGIEFGDKDR
KADAKLVCDVVSRMEDTEPYSAELLTAMKRLWADAGTQECFSRAREYQLN
D----SAKYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLTIC--------------FPEY---------
-------------------------TGANTYDDATAYIQVQFESKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSXMAG00000014106

MGCTLSAEERAALDRSKAIEKNLKEDGLVAAKDVKLLLLGGGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAILRAMDSLTIEFGDKDR
KADAKLVCDVVSRMEDTEPYSAELLAAMKRLWADPGTQECFNRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLTIC--------------FPEY---------
-------------------------TGANTYEDATAYIQVQFESKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSGACG00000015873

MGCTLSAEERAALDRSKAIEKNLKEDGVVAAKDVKLLLLGGGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAILRAMDSLGIEFGDKDR
KADAKLVCDVVSRMEDTEPYSAELLTAMKRVWTDAGTQECFSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----PDYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVAMSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLTIC--------------FPEY---------
-------------------------TGANTYDDATAYIQVQFESKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSONIG00000010197

MGCTLSAEERAALDRSKAIEKNLKEDGLTAAKDVKLLLLGAGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAIVRAMDTLGLEYGDKER
KADAKMVCDVVSRMEDTEPYSAELLSAMMRLWSDSGIQECFSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLSIC--------------FPEY---------
-------------------------TGPNTYEDAAAYIQAQFESKNRS-P
NKEIY----CHMTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSAMXG00000020447

MGCTLSAEERAALDRSKAIEKNLKEDGITAAKDVKLLLLGAGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAIVRAMDTLGLEYGDKER
KAEEKQVCDELLRLDYRHPLERTCISGQVRLWADSGIQECLSRAREYQLN
D----SAQYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLKLFDSICNNKWFTSTS
IILFLNKKDIFEEKIKKSPLTIC--------------FPEY---------
-------------------------TGPDTFTEGVEYIQSQYESKNKS-F
HKEVY----AHTTCATDTNNIQFVFDA---VTDVIIANNLRFCGLY----

*
>P1;ENSTRUG00000017975

MGCTLSAEERAALDRSRAIEKNLKEDGMVAAKDVKLLLLGGGESGKSTIV
KQMKIIHEDGFSGDDVKQYKPVVYSNTIQSLAAILRAMDSLGIEFGDKDR
KADAKLVCDVVSRMEDTEPYSAELLTAMKRLWADAGTQECFSRAREYQLN
D----SAKYYLDSLDRIGA-------------------------------
-----ADYQPTEQD-ILRTRVKTTGIVETHFT------------------
-------------------------FKNLHFRLFDVGGQRS-ERKKWIHC
FEDVTAIIF-CVALSGYDQVLHEDETTNRMHESLMLFDSICNNKFFIDTS
IILFLNKKDLFAEKIKKSPLTIC--------------FPEY---------
-------------------------TGANTYDDATAYIQVQFESKNRS-P
NKEIY----CHLTCATDTGNIQVVFDA---VTDIIIANNLRGCGLY----

*
>P1;ENSLOCG00000016879

MAEG-------EINSAGTVE------------------------------
-----VEENEESGDSDLQVELSAF--RAQWMSELMPPAGSSGANRGPLSR
SADLKRKQEMA-RE--------------------EKARELFLKAVEEEQN
GAVYEAIKYYRRAMQLVPDIEFKINYTRSPDPDGVGVNYMDENESDGEVA
DLLTYFQQQLTLQDSSLKICQPETDISQMHISALPLEVLMYIFRWVVSSD
LDLRALEQLALVCRGFYICARDPEIWRSACFRVWGRNCTKTNPFNSWREM
FLERPRVRFDGVYISKTTYIRQGEESLDGFYRAWHQVEYYRYLRFFPDGQ
VMMLTTPEDP---------LSIVPRLRSRNTRMESVLLGHYRLSQDTDNQ
TKVFAVVSKRKDEKPAEYQKSRYFRRGPVQDTEHSFHVGLQLCSGGRQRF
NKLTWIHHSCHITYRSSEETVVTAFEVDKMYTPLFFARVKSYTALSEKPL

*
