>P1;ENSAMXG00000004364

RMYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SNNFMHQGLWRYCTPGKCFTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---SLLACFFGIIIGIMAFIHYSTF--E----------
----------------------RFDKTFAAGTLFFISCFFV---------
-----------------------------------FLAMAVYTGV-TMNY
YGKRYGSWRFSW---------------------SYIIGWVAVVLTFFS-G
IFYM--------------------CAYRMHECPR----------------
----------N-------PAPH----------------------------
-----
*
>P1;ENSONIG00000011143

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SSNYMHQGLWRYCVPGKCMTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---SLLACFIGIVIGVMAFIHYSSF--D----------
----------------------GFDKTFAAGILFFISCFFV---------
-----------------------------------LLAMAVYTGV-TVNY
YGKRYGSWRFSW---------------------SYIMGWVAVVLTFFS-G
IFYM--------------------CAYRMHECPR----------------
----------N-------SNSR----------------------------
-----
*
>P1;ENSGACG00000010543

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SSNYMHQGLWRYCVPGKCMTHTDS-
-------------I----------------------AYWDAT--------
------RALMIL---SLLACFIGIVIGVMAFIHYSS---E----------
----------------------GFDKTFAAGILFFISCFFV---------
-----------------------------------LLAMAVYTGV-TVNY
YGKRYGSWRFSW---------------------SYIMGWVSVVLTFFS-G
IFYM--------------------CAYRMHECPR----------------
----------N-------ST-R----------------------------
-----
*
>P1;ENSGACG00000020121

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------Q----------------SSNYMHQGLWRYCIPGKCFPHNDS-
-------------I----------------------AHLDAT--------
------RALMIL---SLLACFIGIIIGIMAFIHYSSF--D----------
----------------------RFDKTFAAGILFFISCFLV---------
-----------------------------------FLAMAVYTGV-TINY
YGKRYGNWRFSW---------------------SYIIGWVSVVLTFFS-G
IFYL--------------------CAYRMHECPR----------------
----------S-------NNSH----------------------------
-----
*
>P1;ENSAMXG00000003038

-MYSFMGGG-----LFCAGVGNILLVVSTAT-------------------
---DYWMQYR----------------------------------------
--------Q----------------SSGYMHMGLWRYCMPGKCMTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---AVLACFFGLMIGVMAFINYSSF--G----------
----------------------GFDKTFAAGILYFISCFFV---------
-----------------------------------LLAMAIYTGV-TVNY
YGKRYGNWRFSW---------------------SYIMGWVSVVLTFFS-G
IFYM--------------------CAYRMHV-PR----------------
----------G-------PMSR----------------------------
-----
*
>P1;ENSDARG00000037402

-MYSFMGGG-----LFCAGVGNILLVISTAT-------------------
---DYWMQYR----------------------------------------
--------Q----------------SSSYMHQGLWRYCVPGKCMTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---ATLACFFGMIIGVMAFINYSSF--T----------
----------------------GFDRTFAAGILYFISCFFV---------
-----------------------------------LLAMAVYTGM-TVNY
YGKRYGNWRFSW---------------------SYIMGWVSVVLTFFS-G
IFYM--------------------CAYRMHE-PR----------------
----------G-------PMSR----------------------------
-----
*
>P1;ENSTNIG00000016178

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SSNYMHQGLWRYCVPGKCMTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---SLLACFIGIVIGVMAFIHYSSF--D----------
----------------------GFDKTFAAGILFFISCFFV---------
-----------------------------------LLAMAVYTGV-TVNY
YGKRYGSWRFSW---------------------SYIMGWVAVVLTFFS-G
IFYM--------------------CAYRMHECPR----------------
----------N-------SNSR----------------------------
-----
*
>P1;ENSORLG00000005308

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SSSYMHQGLWRYCVPGKCIAHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---SLLACFIGIVIGIMAFIHYSSF--D----------
----------------------GFDKTFAAGILFFISCFFV---------
-----------------------------------LLAMAVYTGV-TVNY
YGKRYGNWRFSW---------------------SYIMGWVAVVLTFFS-G
IFFM--------------------CAYRMHECPR----------------
----------N-------SNSR----------------------------
-----
*
>P1;ENSDARG00000068974

-MYSFLGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SNNYMHQGLWRYCTPGKCFTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---SLLACFIGIIIGIMAFIHYSSF--D----------
----------------------RFDKTFAAGILFFISCFFV---------
-----------------------------------FLAMAVYTGV-TINY
YGKRYGNWRFSW---------------------SYIIGWVSVVLTFFS-G
MFYM--------------------CAYRMHECPR----------------
----------S-------SNPH----------------------------
-----
*
>P1;ENSXMAG00000001731

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SSNYMHQGLWRYCVPGKCMTHTDS-
-------------I----------------------AYWDAT--------
------RAFMIL---SLLACFIGIVIGIMAFIHYSSF--D----------
----------------------GFDKTFAAGILFFISCFFV---------
-----------------------------------LLAMAVYTGV-TVNY
YGKRYGSWRFSW---------------------SYIMGWVAVVLTFFS-G
IFYM--------------------CAYRMHECPR----------------
----------N-------SN-S----------------------------
-----
*
>P1;ENSTRUG00000005724

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------Q----------------SGNYMHQGLWRYCMPGKCFPHSES-
-------------IGSAILHLLSFM------PDSSTAHLDAT--------
------RALMIL---SLLACFFGIIIGIMAFIHYSSF--D----------
----------------------RFDKTFAAGVLFFISCFLV---------
-----------------------------------FLAMAVYTGV-TINY
HGKRYGNWRFSW---------------------SYIIGWVSVVLTFFS-G
IFYL--------------------CAYRMHECPR----------------
----------T-------TNAH----------------------------
-----
*
>P1;ENSTNIG00000008604

-MYSFMGGG-----LICAGVGNILLIVYTAT-------------------
---DYWMQYR----------------------------------------
--------Q----------------SGNYMHQGLWRYCMPRKCFPHSES-
-------------I----------------------GLCNKE--------
------P-FSQTAFNSMVPIF------KPGSAERSSLLKR----------
----------------------IFSPATALTWGFGIQSFLV---------
-----------------------------------FLAMAVYTGV-TINY
YGKRYGNWRFSW---------------------SYIIGWVSVVLTFFSAG
IFYL--------------------CAYRMHECPR----------------
----------T-------TNSH----------------------------
-----
*
>P1;ENSTRUG00000005013

-MYSFMGGG-----LFCAGVGNILLIVSTAT-------------------
---DYWMQYR----------------------------------------
--------H----------------SSNYMHQGLWRYCVPGKCMTHTDS-
-------------IGKSRQSVTSRPTPPSTHTHTHTAYWDAT--------
------RAFMIL---SLLACFIGIIIGVMAFIHYSSF--D----------
----------------------GFDKTFAAGILFFISCFFV---------
-----------------------------------LLAMAVYTGV-TVNY
YGKRYGSWRFSW---------------------SYIMGWVAVVLTFFS-G
IFYM--------------------CAYRMHECPR----------------
----------N-------SNSR----------------------------
-----
*
>P1;ENSLOCG00000002057

-AVMMAAASLALQNTLKKGVVPPLVVILGATGTGKSKLAIEIGRRMQGEI
ISADSMQVYRGLDIITNKVTAEEQELCPHHMISFVDPLVSSFTVVDFRNR
ALPLISSRHIEDMHQREKMPIIVGGTNYYIESILWKVLLDTKQDDGQGNG
AGDSPRRRAELEKLGGPELHR-------------RLAEVDPDMASMLHPH
NTRKIARSLQVL---QEMG----IPHSRLLQ-EQREQ--EGADGLGGPLR
FDGPCIFWLHAELPALDARLEERVEDMLSAGLLEELKDFHERYNEQKLQD
SGQDYQHGIFQSIGFKEFHEYLTAGTDRSEEERQKLM----SKGIEALKQ
ATKRYARKQNKWVRNRFLKRPGSSAPPVYGLDVTDVSHWDETVLAPAL-Q
ILDSLRKGQRPAAEPLAPGAEERGSKRRRHACELCERVIIGDLEWTAHLK
SKSHLHQVRKKKKKLESASGSQGSSCVSPRQAGVANIHPGSDPACRTDSA
AGTAV
*
