>P1;ENSGACG00000005128

-----------------------M------------A------------L
IPR------EVFSFKDTELSSHLLVQLNILRQERILTDVLLCTEHQE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSNFLESSQ---------------------------------------
ARVNLKGISSNVLVG-----------------------------------
------------------------------------IMDYVYT------G
CITITMEIVLPLMQAASMLHYGSLFEACSMFLQEQLS-PENCLSMIRLSE
ILHCESLRERAKEMAVRCFSDVAATEDFCELS---LPELMCYLEDDRLCA
EEEQVFE------TLL-----------------------AWIHHDPFSRR
GAIHDLFKKV-----------RLRYIHPTYL-------FQFIANDPLV-Q
SSTLCTEIIESVRRLML-----------------------TVSTKCSR--
--ELKPLWTTPRRYTCSETLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALLYDERTHRWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPLRLYKAAYVCI
HSILYVVGGLSLCMTSGDSSVSATVYTLSLKTNQWRTAEPMLEPRYAHQS
VSYLH--------------------FIFVLGGIGVDKKISRS--------
----VERYNSMFNQWEAMAAMPTAVLHPAVAASDQRIYVFGGEDAMQNPV
RLIQVYHIARDLWSSLETRTVKNVCAPAAVIEDKIYIIGGY----TRRMI
AYDTKANKFVKCENLKERRMH-----------------------------
---HSATVINNKLFVTGGRILNGHDVIEDSDCFECYDPKADVWTSKGSLP
YKLFDHGSLPLVCVSNRPNPP
*
>P1;ENSAMXG00000016790

-----------------------MLNLLSPLLLNSID------------G
PIT------EVLHYKDKELMEALPLQLNNLRKEQILTDVVLCSDGKE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFYA--------
MFCSNFRESQQ---------------------------------------
SCVDVKDVPFEILSS-----------------------------------
------------------------------------IVDYVYT------G
SISISMELVLPLMQAAAMLQYVRLFEACSTFLQAQLS-PDNCLSMIRLSE
ILHCVSLQEKARELAVRSFSDVASSEDFCELS---LHELVGYLEDDQLCA
EEEQVFE------ILL-----------------------AWIHHDPFARR
GSIHDLFRRV-----------RLRHVHPSYL-------FQFIANDPLV-Q
SSSLCTEIIESVRRLLF-----------------------SVGSCCPG--
--DLQPLWETPRRHTCKEALVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNERTSREAMLFDEQTQRWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPVRLYRASYVCM
HSILYVLGGLTIRSG-GGTVPSTTVYTLSLKTNQWRMAEPMLTPRFAHQS
ISYLH--------------------FIFVIGGITDDGQISNG--------
----VERYNTMFNQWELMSPMPTAVQHPAVAAHNQRIYVFGGEDAMQNPV
RMIQVYHIGRNLWCRMENRTVKNVCAPAAVIDNKIYIIGGY----TRRVV
AYDIKANQFIKCKNMKERRMH-----------------------------
---HSATVINSELYVTGGRYINGQDVIEDLDSVDCYNPETDTWMSKGNLP
FKLFDHGAVPLVYVSDKHLPT
*
>P1;ENSORLG00000012386

-----------------------M------------A------------V
TPQ------KVFSFKDSEHPCYLLGQLNTLRQERILTDVLLCSEHQE---
------------IPCHRSVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSNFVESSQ---------------------------------------
ARVNLKGISSNVLSG-----------------------------------
------------------------------------IVHYVYT------G
CISITMEIVLPLMQAASMLHYGNLFEACSMFLQEQLS-PENCLSMIRLSE
ILHCESLKERAKEMAVRCFSDVATTEDFCELS---LPELMCYLEDDRLCA
EEEQVFE------TLL-----------------------AWIHHDPFSRS
GAIHDLFKKV-----------RLRYIHPTYL-------FQFIANDPLV-Q
SSTLCTEIIDSVRRLML-----------------------TASAKCSR--
--ELKPLWTTPRRYTCRETLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALLYDERTHRWEWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPLRLYKAAYVCI
HSILYVLGGLSLCLGSGDSSVSATVYTLSLKTNQWRTAEPMLEPRYAHQS
VSYLH--------------------FIFVLGGIGVDKRISPS--------
----VERYNSMFNHWETMAPMPTAALHPAVAASDQRIYVFGGEDAMQNPV
RLIQVYHISRNLWSKLETRTVKNVCAPAAVIEEKIYIVGGY----TKRMI
AYDTKANKFVKCENLRERRMH-----------------------------
---HSATVIHNKLYVTGGRILNGHDTIEDSDCFECYDPKTDSWTSKGSLP
YKLFDHGSLPLHQLDRKLFIL
*
>P1;ENSDARG00000040278

-----------------------MCFKSA---ETSLD------------G
PVS------EILHFKDKDLISNLLLELNTLRKDRILTDVVLCSENKE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFHA--------
MFCSNFLETQK---------------------------------------
SRINLEGVPHEILAM-----------------------------------
------------------------------------IVEYVYT------G
SISISMELVLPLIQTASMLQYGRLFEACSTFLQAQLS-ADNCLSMIRLSE
ILHCSSLHEKARELAIKSFSDVVVSEDFCELS---LPELVSYLEDDKLCV
EEEQVFE------TLL-----------------------AWIHHDPFSRH
GTIHDLFRRV-----------RLRHVHPYYL-------FQFIANDPLV-Q
SSSLCTDIIESVRRLLF-----------------------SVGTHCPG--
--DLEPLWRTPRRQNCKEGLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NGEQTSREALLYDEQSHCWKWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKIPLRLYRPAYVCM
HSILYVLGGLTMKSG-SQCTPSNTVYTLSLKTNQWRMGESMLTSRYGHQS
ATYLH--------------------FIFVLGGLGADGQLSNE--------
----VERYDTMFNQWEAMAPMPTAVLHPAVAAHNQRIYVFGGEDAMQKPV
RMIQVYHIGRNMWCRIENRTVKNVCAPAAVIDDKIYIVGGY----TRRMV
AYDVKSNTFEKCENMKARKMH-----------------------------
---HSATVVNGKIYVTGGRFFNSHERVEDSDSFDCFDPKTDAWTSMGKLP
FKLFDHGSVPLVYLSDKFLPT
*
>P1;ENSGACG00000006167

-----------------------M------------E------------R
PGA------QTFLYKDKEQSSSVLLQLNRLRQENILTDVSLCSDNTE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCNNFMETQQ---------------------------------------
TKIDLKDITSAILST-----------------------------------
------------------------------------VIDYVYT------G
LVSISVDVVLPLMQAASMLQYGRLFEACSSFLQEQLS-PDNCLSMIRLSE
ILNCSSLKDKAKEMAMKSFSAVSASEDLCELS---LPELMGYLEDDGLYA
EEEQVFE------TLV-----------------------AWIHHDPLSRR
GAISELFKKV-----------RLRHIHPTYL-------FQFIANDPLI-Q
SSTLCAELIDSVRRLMF-----------------------SVSTKCLGDS
AVDFKPLWVAPRRSSCHDMLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALVFDERSETWQQL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPVRLYKASYVAL
HSVLYVIGGMTTNT--QDGQVSMTVYTLSLKTNQWRTAEPMPTARFAHQS
VSYLH--------------------FIFVLGGLGSDRRLTNS--------
----AERYNSMFNQWEAMAPMPEAVLHPAVAVANQRIYVFGGEDAMQNPV
RIIQVYHIARNMWSRLENRTVKNVSAPAATVDDKIYIIGGY----TRRTI
AYDIKTNRFIKCANLKERRMH-----------------------------
---HSATVLNNKVYVTGGRHINGHDVIEDSDNFECYDTKTDTWTSKGTLP
YKLFDHGSLTLTYVSNHGQNH
*
>P1;ENSONIG00000007206

-----------------------M------------D------------Q
PAR------EVYHFKDKEQSSNLLLQLNRLRQENILTDVLLCSDNTE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSNFVERQQ---------------------------------------
TKIDLKGITSTILSS-----------------------------------
------------------------------------IIDYVYT------G
LISISMDDVLPLMQAASMLQYGRLFEACSSFLQKQLS-PDNCLSMIRLSD
IMSCKSLRDKAKEIAMKSFCDVSISEDLCELS---LPELMGYLEDDSLCA
EEEQVFE------TLV-----------------------AWIHHDPLSRR
GAISDLFKKV-----------RLRYIHPTYL-------FQFIANDPLI-Q
SSTLCTELIESVRRLMF-----------------------SVSTKCSGDI
AADFKHPWVAPRRYSYHDMLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREAIVFDERSQMWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPVRLYKASYVAL
HSVLYVIGGLTTNP--KNSEVSRTVYTLSLKTNHWRTAEPMLEPRFAHQS
ISYLH--------------------FIFALGGLGPDRRLTGS--------
----VERYNSMFNLWESMAPMPEAVLHPAVAATNQRIYMFGGEDAMHNPV
RMTQVYHIARNMWSKMENRTVKNVSAPAVVMDEKIYIIGGY----TRRMI
AYDTKANRFIKCASLRERRMH-----------------------------
---HSATVLSNKLYVTGGRYINGHDVIEDSDAFECYDPKTDTWTSKGSLP
YKLFDHGSVTLTCVSQTWSKS
*
>P1;ENSXMAG00000003337

-----------------------M-----------MA------------G
RRA------GIFSFKDSELPCHLLIQLNILRQERILTDVLLCTEHQE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCNNFLESSQ---------------------------------------
ARVNLKGISSSVLTG-----------------------------------
------------------------------------IVDYVYT------G
CVTITMENVLPLMQAASMLHYGGLFEACSTFLQEQLS-PENCLSMIRLSE
ILHCESLKEKAKEMAVRCFSDVAATEDFCELS---LPELMCYLEDDRLCA
EEEQVFE------TLL-----------------------AWIHHDPFSRR
GAIHDLFKKV-----------RLRYIHPTYL-------FQFIANDPLV-Q
SSTLCTEIIDSVRRLML-----------------------TASTKCSR--
--ELKPLWTTPRRYTCRETLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALLYDERTHRWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPLRLYKAAYVCI
HSILYVLGGLSLCMASGDSSVSSTVYTLSLKTNQWRTAEPMLEPRYAHQS
VSYLH--------------------FIFVLGGIGVDKRISQS--------
----MERYNSMFNQWEAMAPMPTAVLHPAVAASDQRIYVFGGEDAMQNPV
RLIQVYHISRNLWSRLETRTVKNVCAPAAVIEEKIYIIGGY----TRRMI
AYDTKANKFFKCANLKERRMH-----------------------------
---HSATVINNKLYVTGGRILNGHDVIEDSDCFECYDPKTDVWTSKGSLP
YKLFDHGSLPLVCVSNRPNPP
*
>P1;ENSXMAG00000008658

-----------------------M------------D------------P
PGA------EVLHYSDEEQSSTLLLRLHKLRAENILTDVILCAGHTE---
------------IPCHRNVL------------------------------
---------------------------------ASSSAYFRA--------
MFCNDFMETRQ---------------------------------------
TKVDIKGVGPVILTS-----------------------------------
------------------------------------IVDYVYT------G
LISISLDNVLHLMQAASMLQFGRLFEACSCFLQSQLR-PDNCLSMFRLSD
VMNCDSLRKKAKEMAMESFTDVSSSEDLCELS---LQELMGYLEDDSLCA
QEEQVFE------TLI-----------------------GWIRHDPVSRR
GTISSLFKKV-----------RLRHLHPTYL-------FQFIANDPLI-Q
SSTLCTEIIESVRRLMF-----------------------SIGTRSIRDF
VVDFKPLWAAPQRCSYDDTLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------R------NNELTSREALVFDEKKQKWQRL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------TKLPVRLYKASYVAL
HSILYVLGGLTTNT--SSSQVSRTVYTLSLKTNQWRTAEPMLEPRFAHQS
VFYLH--------------------FIFVLGGLGSDRHLTAS--------
----VERYNSMFNQWEAVAPMPETVLYPAVAATNQRIYMFGGQDATHNPV
RLIQVYHIGRNMWCTMENRTVKNVSAPAVVLDEKIYIIGGY----TRRVM
AYDTEANRFAKCASLKERRMH-----------------------------
---HAATGLNNKLYVTGGRYVSGHDAVEDTDTFECFDPKTDTWTCKGRLP
FKLFDHGCLTLTCVTQNWKKS
*
>P1;ENSORLG00000005665

-----------------------E------------SLTVYVRKNERKMG
GKT------EVHHYRDKEQSSSLLLQLNRLRQENILTDVLLCSGTTQ---
------------IPCHRAVL------------------------------
---------------------------------VSSSPYFRA--------
MFCHDFAEKQK---------------------------------------
TKIDLKGISPTILSS-----------------------------------
------------------------------------IVDYVYT------G
LVSLRMDVVLPLMQVASMLQYIRLFEICSSFLQEHLI-PDNCLSMIRLSE
IMNCSSLRVKAKEMAMKSFSEVSACEDLCELS---LSELMGYLDDDNLCA
EEEQVFE------TLV-----------------------AWIHHDPMSRR
RTISDLFKKV-----------RLRHIHPTYL-------FQFIANDPLI-Q
SSTLCTELIDSVRRLMF-----------------------CVDLKCIQNF
AVDFSPLWHAPRRCTYQEMLVVIGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NSEQTSREALAFDESSQRWKLL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKVPVRLHKPSYVAL
HSVLYVIGGLTTNT--KHSQVSKSVYTLSLKSNQWRTAESMLEPRFAHQS
VSYLH--------------------FIFVLGGLGPDRRLTSSVQSTSISI
RKCTIERYNSMFNQWEWIAPMPEAVLHPAVAATNQRIYVFGGEDVLKNPV
RLIQVYHIGRNMWSKMENRTVKNVSAPAVVLKELIYIVGVSAYFTYRRML
AYDAKTNRFTVCANLKERKMH-----------------------------
---HSAIVLNNKLYITGGRYLTGQDDVEDSNSFEVYDSLTDSWTSAGSLP
HKLFDHGSVTLTFHWKSVK-L
*
>P1;ENSTNIG00000019106

-----------------------M------------E------------Q
PAG------EVLRYHDKEQSSALLLQLNALRREEILTDVSLCSESTE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCGSFLERQQ---------------------------------------
TKITLKGVPSAILSS-----------------------------------
------------------------------------IVDYVYT------G
LVDISMEIVLPLMQAASLLQYGRLFEACSSYLQEQLS-PDNCLSMIRLSE
ILSCDSLRNKAKEMAMQRFSDISGSEDLCELS---LPELLGYLEDDGLCA
EEEQVFE------TLV-----------------------SWIHHDPITRG
GAISDLFKKV-----------RLRYIHPTYL-------FQFIANDPLI-Q
SSTLCTELIESVRRLMF-----------------------SVSTKCTSDT
SIDFKPLWVAPRRYACQDMLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NSEQTSREALVYDETTRTWRQL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPVRLYKPSYVTL
HSVLYVLGGLTTNT--EQAQVSSSVYTLSLKTNQWRMAEPMLVPRFAHQS
VSYLH--------------------FIFVLGGFGPDRRLTSS--------
----VERFNSMFNQWERMSAMPEAVLHPAVAATNQRIYVFGGEDPMQNPV
RIIQVYHIARNMWCKMENRMVKNVSAPAAIIKDKIYIIGGY----TRRVI
AYDTKANRFVKCANLKERRMH-----------------------------
---HSATVLKNKLYITGGRFINSCDVVEDSDHFDCFDPQTDSWTSQGALP
YKLFDHGSLTLAHVSQTWAKS
*
>P1;ENSDARG00000031383

-----------------------M------------A------------S
TST------EVFPFKDQELSTQLLFQLNILRQEQIFTDVILCTEDKE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSNFRESSQ---------------------------------------
ARVDLKGIASEVIEC-----------------------------------
------------------------------------VVDYIYT------G
SITITMELVLPLMQAASMLQYGRLFEACSTFLQEQLN-PENCLSMIRLSE
ILHCETLKERAKEMAVRCFSDVAASEDFCELT---LPELMCYLEDDRLCA
EEEQVFE------TLL-----------------------AWIHHDPFSRR
GAIHDLFKKV-----------RLRFIHPTYL-------FQFIANDPLV-Q
SSTLCTEIIESVRRLMF-----------------------SVSAKCTK--
--ELKPLWTTPRRYTCRETLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALLYDERTQRWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPLRLYKAAYVCI
HSILYVVGGLSLSLVSGDSAVSATVYTLSLKTNQWRTAEPMLEPRYAHQC
VSYLH--------------------FIFALGGIGQDKQISNT--------
----VERYNSMFNQWEVMAPMPTAVLHPAVAANDQRIYVFGGEDALQNPV
RLIQVYHISRNLWSRLETRTVKNVCAPAAVIEDKIYIVGGY----TRRVI
AYDTKANKFVKCTNMKERRMH-----------------------------
---HAATVINNKLYVTGGRFLNSHDVIEDSDCFECYDPKTDVWTSKGSLP
YKLFDHGSLPLICVSNRPNPP
*
>P1;ENSTRUG00000005434

GNELNRLECGETQASADQEKVFQM------------E------------R
PAV------KVFQYQDQEQSSDLLLQLNTLRQEQILTDVSLCADSTE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSSFMERRQ---------------------------------------
TKITLKGVTSAILSS-----------------------------------
------------------------------------IIDYVYT------G
LIDISMEIVLPLMQAASMLQYGRLFEACSSYLQEQLS-PDNCLSMMRLSE
IMNCDSLRNKAKEMAVKRFSDISGSEDLRELS---LPELLGYLEDDSLCA
QEEQVFE------TLL-----------------------SWIHHDPLTRR
GAVSDLFKKV-----------RLRYIHPTYL-------FQFIANDPLI-Q
SSTLCTELIDSVRRLMF-----------------------SVGSETS---
-IDFQPLWVAPRRYAYQDMLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NSEQTSREALVFDEETRKWRRL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPVRLYKASCVTL
HGVLYVLGGLTTNT--EQAQVSTSVYTLSLKTNRWRTAESMLVPRFAHQS
VSYLH--------------------FLFVLGGFGPDRQLTSS--------
----TERFNSMFNQWEHMSAMPEAVLHPAVAATNQRIYVFGGEDAMQNPV
RIIQVYHIARNMWCKMDNRMVKNVSAPAAIIEDKIYIIGGY----TRRVI
AYDAKANRFIKCANLKERRMH-----------------------------
---HSAAVLKNKLYITGGRLINGRDEVEDSDNFECYDPTTDSWTSQGALP
YKLFDHASLTLTHVSHTWAKS
*
>P1;ENSAMXG00000011422

-----------------------M------------A------------C
SSL------EVFSFKDQELPAHLLCQLNILRLERIFTDVLLCTEDKE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSNFRESSQ---------------------------------------
ARVDLKGISSEVLAG-----------------------------------
------------------------------------IVDYIYT------G
SITITMELVLPLMQAASMLQYVRLFEACSTFLQEQLN-PDNCLSMIRLSE
ILHCDSLRDRAKEMAVRCFSDVAASEDFCELS---LPELMCYLEDDRLCA
EEEQVFE------TLL-----------------------AWIHHDPFSRR
GAIHDLFKKV-----------RLRYIHPTYL-------FQFIANDPLV-Q
SSTLCTEIIESVRRLMF-----------------------SVSAKCTR--
--ELKPLWTTPRRYTCRETLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALLYDERTQRWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPLRLYKAAYVCI
HSILYVVGGLSLSLASGDSAVSATVYTLSLKTNQWRTAEPMLEPRYAHQS
VSYLH--------------------FIFALGGIGADKQISNT--------
----VERYNSMFNQWEAMAPMPTAVLHPAVAANDQRIYVFGGEDSMQNPV
RLIQVYHISRNMWSRLETRTVKNVCAPAAVIEDKIYIIGGY----TRRVI
AYDTKANKFVKCENMKERRMH-----------------------------
---HSATVINNKVYVTGGRFLNSHDVIEDSDCFECYDPKADAWSSKGSLP
YKLFDHGSLPLICVSNRPNPP
*
>P1;ENSONIG00000002463

-----------------------M------------A------------T
RPQ------DVFSFKDAELPSHLLAKLNVLRQERILTDVLLCTEHQE---
------------IPCHRNVL------------------------------
---------------------------------VSSSPYFRA--------
MFCSNFLESSQ---------------------------------------
ARVNLKGISSNVLIG-----------------------------------
------------------------------------IVDYVYT------G
CITITMDIVLPLMQAASMLHYGSLFEACSVFLQEQLS-PENCLSMIRLSE
ILHCESLKERAKEMAVRSFSDVAATEDFCELS---LPELMCYLEDDRLCA
EEEQVFE------TLL-----------------------AWIHHDPFSRR
GAIHDLFKKV-----------RLRYIHPTYL-------FQFIANDPLV-Q
SSSLCTEIIESVRRLML-----------------------TVSAKCSR--
--ELKPLWTTPRRYTCRETLVVVGGR------------------------
--------------------------------------------------
--------------------------------------------------
-------K------NNEQTSREALLYDERTQRWQWL--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------AKLPLRLYKAAYVCI
HSILYVLGGLSLCMTSGDSSVSATVYTLSLKTNQWRTAEPMLEPRYAHQS
VSYLH--------------------FIFVLGGIGVDKRISQS--------
----VERYNSMFNQWEAMAPMPTAVLHPAVAASDQKIYVFGGEDAMQNPV
RLIQVYHIARNLWSKLETRTVKNVCAPAAVIDDKIYIIGGY----TTRMI
AYDTKANKFFKCENLKERRMH-----------------------------
---HSATVINGKIYVTGGRILNGHDVIEDSDCFECYDPKTDVWTSKGSLP
YKLFDHGSLPLVCVSNRPNPP
*
>P1;ENSLOCG00000016548

-----------------------M------------A------------F
ASLFANPPNPVL---DKNMTDSELAGDESQREDGELEDGEIDDEGIGIEE
EGKELKEEKEKEEKTHRRSRKRHRKEREKRKSKKRRRDRQKHHSPSSEDG
SGSYDSDYEHSERLHKKNAGTYRDYDSQFTQHGQSSGGYMKCQKTTQHKN
NEFDKFSDYSEEKYDYEGDDNDFADELNQYRQAKEATASGPNKGPPKEQM
KKLNMKGVQKGPGQKGRGRGAGRGRGMQKNKKQKGKNWGRGRGRGADQGA
DGLKEEGKGPAVIQKKRPIMTQEFINQHTVEHNGRYICKYFLEGRCIKGD
QCKFEHELVVPD----------KKKEICKFYLQGFCSKGDNCIYMHN---
EYPCKFFHTGAKCY----------QGDNCKFSHDPLTDLTRELLEKVLNT
EEEPVNEDEQELEDLRKQGIAPLPKPPPGVGLLPTPGPNSPQEGSPCSGQ
KKIPSLFEIVVQPTVDLAQKIGLRP---NFYNSSSPPGPQFQGNGPPPPQ
MFGGGTDDMPGPNMMPPGPNGPPVPPPGSPGSLGPAHHGGPPGVHCP---
-----PIPQSPPRQPVPHGFPGAHGPPMHPPPPGVPPAFHGNSHGNRSRD
TPPQTAPGPPFQQMSDHQMQQNIPFQAMPNTTDFFNNYYTNQTVHSLETA
PLQEEEALNMDQLTYSCVQDSQHSGTDSDGSSNHKPPVHVPDFLPAMQKA
LFLRLSQKQHEGDHQKEENKGQKMSNKEKDDAVNWYSSDEEDGSSVTAIL
KTLKKQNEIIKTQQQSVTQQTASQGPCDPRLQKDKNIPCDPRTKCDPRHR
ASGEVRKSGDGTVDPRLVRDPRKIKPSDPSSTKPDVHHSHGSFAHKQQTG
DDDEEGERELREKAAIIPLEPLPGIALRDPRCQLKQFSHIKVDIILSRPA
FAKNVVWAPEDLIPLLIPKQEPSINLPLPPLIADSRLNRNNSVLNDSNQN
TLLQDPRLVGGRGKDNFHKAGGHTIKPLEPKSSPEKPLDPRLHKAVDPRV
RGPLNIDSKH--------SVVKDP--------------NTTADPRLQRGS
ISAFQTSGTPTVKSEPEKLPPYAPKLSSSSGGLGSPTTLLGG--------
----ISLYDPR------------------------NQTLQSSKDDVENPK
RLSILKQTVKQENT-----QS----SPL--AASKAGAVPDT----KTTDI
SSDATVDKYSSYNRQRPTPMAAQSSTAPAVHNLPIQALAGLIRPPYSDPR
QSRQSGQVNAPQESDTNGE----SDDKPLKDVFKTFDPTASPFC------
---------------------
*
