>P1;ENSDARG00000039220

RV---FQRHGVAVFLAITMCTSLL---------------FVYN---VSY-
NNNSTTAASAS--KGA--S----GETVEPTRAA-RAHPALQGYS------
---------------------------------SIIEHKPLK--------
--------------------------------MHCRS-------------
------------------------------------------------CA
LVTSSGHLTGGGRGKEIDQAECVIRMNDAPIARGYGADVGHRTSLRVIAH
SSM------QRVLRSRHELLNSSQETVFIFWG-PSSYMRRDGKGLVYNNL
RLMNQVLPKLKVYIISWQKMLQFDDLFKRETGKD-RRITNSWLSTGWFTM
TIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVPPDFC
-RES-QHSSVPYHYYEPTGPDECAMYI------------------SHERG
RRGSHHRFITEKRV-FANWARTFNIHFYQPDWSPPPLPRNSTAT------
-----------AA-FPRPQ----------------KT---
*
>P1;ENSTNIG00000010702

MKI--RVCQGVGGIIIVAIVTSFM---------------LVYH---SSG-
-DRSSSVMS-------RHTV-----EPAPTQKLPQRASTLEGYL------
---------------------------------RVVDHKPLK--------
--------------------------------MHCSS-------------
------------------------------------------------CS
LVTSSGRLIGSRRGGQIDRSDCVIRMNDAPTV-GHQRDVGRRTSLRVVAH
SSL------QRVLRSRRELLNASQGAAYIFWG-PSSCMRRDGKGQVYNSL
RLMNQLLPRLELYIISRNKMLKFDELFKKETGMD-RKSSNSWLSTGWFTM
AIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRV-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------DVFGMVPPEFC
SRSS-SHPSVPYHYYEPGGPDECSMYL------------------SHERS
RRGSHHRFITEKVV-FANWARSLNIHFHQPDWEPTAATAGSNRS------
-----------RV-F-LQR----------------GS---
*
>P1;ENSORLG00000003305

--------------------------------------------------
------------------------------------------FL------
---------------------------------PCID-QPLR--------
--------------------------------MHCST-------------
------------------------------------------------CS
LVTSSGHLIGGGRGEEIDRAECIIRMNDAPTARGYARDVGRRTSLRVIAH
SSM------QRVLRSRHELLNASQDTVFIFWG-PSNYMRRDGKGLVYNNL
RLMNQVLPKLKVYIISWQKMLQFDELFKKETGKD-RRISNSWLSTGWFTM
TIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVAPDFC
-REP-QHQSVPYHYYEPRGPDECAMYI------------------SHERG
RRGSHHRFITEKRV-FADWARTFDIHFYQPEWSPAPLPANRTLE------
-----------AV---EPA-------------------G-
*
>P1;ENSONIG00000018361

--------------------------------------------------
--------------------------------------------------
---------------------------------TMAQHKPLR--------
--------------------------------MHCHT-------------
------------------------------------------------CA
LVTSSGHLIGGGRGEEIDRAECVIRMNDAPTARGYAHDVGRRTSLRVIAH
SSM------QRVLRSRNELLNASQDTVFIFWG-PSNYMRHDGKGLVYNNL
RLMKEVLPKLKVYMISWQKMLQFDELFKKETGKD-RKISKTWLSTGWFTM
TIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVAPDFC
-REP-QNHSVPYHYYEPRGPDECAMYI------------------SHERG
RRGSHHRFITEKRV-FANWARTFDIHFYQPDWSPPPLPANRTLE------
-----------GTVTAAPL----------------K--T-
*
>P1;ENSDARG00000057433

MKT--RTRHGIILIGVVTVLTSLL---------------FVYN---STS-
ADTP--GDQLH--SDG-------HQI---DAAS-RQTFSLEGYI------
---------------------------------SIIDHKPLK--------
--------------------------------THCRS-------------
------------------------------------------------CA
LVTSSGHMTGSGRGAEIDETECVIRMNDAPTR-RYQKDVGQHTNLRVIAH
SSM------QRVLRNRYELLNSSQDTFFIFWG-PGNYMRRDGKGLVYNNL
RLMKQLMPKLQVYIISRPKMLQFDELFKKETGKD-RKRSNSWLSTGWFTM
AIAIEMC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVPPEFC
-KSPHTKPSVPYHYYEPSGTDECTMYV------------------THEQG
RHGSHHRFITEKRV-FAKWARMFNIHFYQPDWGPPPVINNNNNT------
-----------NS---------------------------
*
>P1;ENSGACG00000016532

SL---CQRHGMAVLLVLLLCASLF---------------LVYN---GGF-
NGASRDANDTR--VRQ--HEHLRRPTEAPVRVAKPHPPVLQGYS------
---------------------------------SIIDHKPPR--------
--------------------------------MHCQT-------------
------------------------------------------------CA
LVTSSGHLVGGGRGEEIDRAECVIRMNDAPTARGYARDVGRRTSLRVIAH
SSM------QRVLRNRHELLNASQDTTFIFWG-PSSYMRRDGKGLVYNNL
RLMNQVLPRLRVYIISWQKMLQFDELFKKETGKDSRRISNSWLSTGWFTM
TIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVAPDFC
SREP-QHHSVPYHYYEPRGPDECAMYI------------------SHERG
RRGSHHRFITEKRV-FANWARTFDIHFYQPDWSPPPLPAN----------
----------------------------------------
*
>P1;ENSGACG00000011969

MKC-----QGVSGIIFVTMVTSFM---------------LVYN---NGSF
GNRSPSSSSPS--S--RRPNGTAPTKKKPDGPRRLPTPTLEGYT------
---------------------------------SVMDHKPLK--------
--------------------------------MHCGT-------------
------------------------------------------------CA
LVTSSGQLTGSRRGEEIDRSECVIRMNDAPSV-NHQRDVGRRTSLRVVAH
SSL------QRVLRSRQELLNASQDTAFVFWG-PNSCMRRDGKGHVYNNL
RLLKQLLPKLKVYIISRVKMLKFDELFKKETGID-RKSSNSWLSTGWFTM
AIAVELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
GRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------DVYGMVPPDYC
-RSP-SHPSLPYHYYEPSGPDECSMYL------------------SHERS
RRGSHHRFLTEKAV-FADWARTLDIHFHRPDWEPAAAANG---S------
-----------RA-P-APG-----------------W---
*
>P1;ENSTRUG00000017634

MKM--RVCQGVGGIIIVTIVTSFM---------------VAYN---SSG-
-DTSSSLTS-------HRVA-----EPVPSKKQPKGGFTLEGYT------
---------------------------------RVVDHQPLK--------
--------------------------------MHCGT-------------
------------------------------------------------CA
LVTSSGRLIRSKRGQEIDRSDCVIRMNDAPTV-GHQRDVGQRTSLRVIAH
SSL------QRVLQSRQELLNSSQDVAYVFWG-PSSCMRRDGKGHVYNSL
RLMKQLMPALKLYIISRPKMLKFDELFKKETGID-RKSSNSWLSTGWFTM
AIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRV-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------DVFGMVPPEFC
-RSS-SHPSVPYHYYEPNGPDECSMYL------------------SHERS
RQGSHHRFITEKAV-FANWARTLNVHFHQPDWKPMAVVSGPNSS------
-----------RT-L-AER----------------DH---
*
>P1;ENSAMXG00000019059

------------------MCTSLF---------------FVYN---VNN-
SDGGRSSDGSA--QTV-------KPTKAPARPR-PAPPALQGYT------
---------------------------------SIIDHSPLK--------
--------------------------------MHCGS-------------
------------------------------------------------CA
LVTSSGHLTGGGRGQEIDQAECVIRMNDAPTGRGFGLDVGHRTSLRVIAH
SSM------QRVLRSRHELLNSSQDTVFIFWG-PSNYMRRDGKGLVYNNL
RLMNQVLPKLKVYIISWQKMLQFDDLFKRETGKD-RKISNSWLSTGWFTM
TIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVPPDFC
-KEA-QRPSVPYHYYEPLGPDECAMYI------------------SHERG
RRGSHHRFITEKRV-FANWARTYNIHFYQPDWSPPPLPKNTTGT------
-----------TA-QSR------------------RT---
*
>P1;ENSONIG00000002068

MKMKIKVCQGVSGIIIVTMVTGFL---------------LVYN---SSS-
GDRSASSSSSSSSSSSYRLDARVQSTKAPDRSQRLQTTSLEGYS------
---------------------------------GVMDHKLLK--------
--------------------------------MHCRT-------------
------------------------------------------------CA
LVTSSGQLTASKRGEEIDRSECVIRMNDAPSL-GHQQDVGRRTSLRVIAH
SSL------QRVLRSRQELLNMSQDTVFIFWG-PSSCMRRDGKGHVYDNL
KLLNQLLPKLKIYIISRIKMLKFDELFKKETGID-RKSSNSWLSTGWFTM
AIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVPPDFC
-RSS-SHPTVPYHYYEPSGPSECSMYL------------------SHERN
RRGSHHRFITEKAV-FANWARTRDIHFYQPNWKPSPIVTTVNGS------
-----------YT-A-NPA----------------GS---
*
>P1;ENSXMAG00000013162

MKI--R--VGVGGIIIVTMVTGFM---------------VVYN---SSS-
GGRWPSSASRS--LHSHHKD-----APGTKRKQSVQVSTLEGVA------
---------------------------------GIMDLKPLK--------
--------------------------------MHCRT-------------
------------------------------------------------CA
LVTSSGHLTGSNRGEEIDHSDCVIRMNDAPCA-GHHPDVGRRTSLRVVAH
SSL------QRVLRGRQELLNRSQDTVFIFWG-PSSCMRRDGRGHVYNNL
RLLKHLLPKLKVYTISRSKMLKFDELFKKETGID-RKSSNSWLSTGWFTM
AMALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVFGMVPPNFC
-RSS-LHPTVPYHYYEPSGPDECAMYL------------------LHERS
RKGSHHRFITEKTV-FSNWAQTLNIHFYQPDWKPSPVITHVNNS------
-----------RA-P-SPA----------------GS---
*
>P1;ENSXMAG00000016398

MKT--PMRHGVAVLLVLLLCASLF---------------LVYN---GSF-
HSPSRETNDTH--VRQ--HEHLQQPPEASGSAAKPHLPALQGYI------
---------------------------------GIIDHKPLR--------
--------------------------------MHCHT-------------
------------------------------------------------CS
LITSSGHLIGGRRGKEIDRAECVIRMNDAPTAGAYGQDVGRRTSLRVIAH
SSM------QRVLRSRHELLNASQDTVFIFWG-PSNYMRRDGKGLVYNNL
RLMNQVLPKLKVYIISWQKMLQFDELFKKETGKD-RKISNSWLSTGWFTM
TIALELC-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
DRI-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------NVYGMVAPDFC
-REP-QHQSVPYHYYEPRGPDECAMYI------------------SHERG
KRGSHHRFITEKRA-FANWARTFDIHFFQPDWSPPASPRQPDTA------
-----------GN---GHRRCRRYRSAEYVTASGAGMRF-
*
>P1;ENSLOCG00000014377

MRS--TVL--------LAPVTALEFLGEEYLLSGEGPVLSVYSLHTSST-
APRQPGATLSV--LRNHRIH---GIRPAPRRQE-----SGEGGSQQQPRP
HEEREGGALLAVFGGKAVCVVELREEERAGGSPRLAELCPLWELQDWVWD
AHWLQGRRHLAVALAHNAVVLCDPWARVALALSRCAEGCLLYSALLLGPS
WAGLVVVGGTVFSQLVLWGPAQGESAGGGGGGPAVQRRLEGHEGVVFGIA
YLPESGWLA----SASDDRSACLWQVGS---L-GGPAGCGSESPVRLWAL
YGHQARVFAVRLL--RGRLLSAGEDSLCLLWDGHRGSVARRFKGHRAGGV
RALAVSE----------------------------GGGGGHWAATGGADG
GIRVWRIGGDGEGEGGPGRGCASAPRRSLCDLRFRGRGSPKVVRLAGFGA
QGHLRVVVLTDEGCVYLHSSGEGGGEGWQPLGGEGDPEFRSYSVLELAEA
GGGAALCAVGNLAGGVRVFALEQPGGALELRAGRGKVHSLHWASERGRGG
EEEPGRWQLFASGPEGQVYRWEVCAAGGRGGQQALGVRPLRPLLLPACAK
RWLTAVAALPGRGALWAAGDRRGSVLLYRGAREGRGGPDEPPLGPVSVLF
GLHGKQGVTSLRAQGGLLYSTGRDGCVRVLGVRSGDEAEERPDTLEVLRA
QRTCRGMDWVERVLFPETGRFLVLGFHSVDFVVWDPVRRERLLSVPCGGG
HRSWSYCAPSRANAGPGWTPSLGDGFAFIKQGGVFLSRGRGPPLSGFGVP
LELKEGVHGRGVACVCRVGAVRSEAGAWWEVLVTGGEDTTLTVLGVQPDC
GSVRVLSIIADHISSVRALATVPQPEGETGAQEPSCLSALLFSGGGRAQL
QSYRLLIGWNRQEGTPSCQVIQVAGHRLAEQWEKRRNRHKMLKMDPETRM
IEWSVCWLRVTDALLLPRLFSLHESLRRLVLLWGSLHHQRCVLSVAPFSL
CSPQGTRSQFLCSAATDGRIALWDLTEVVEGAEGLTAAPQCWGEGSPCLC
-VPA-HQSGVNSLAVWGSASSECLLLASGGDDGSLTVSRIGVQYNTRDTG
GASASLRLLGQTSAPCAHAAPLTALQFLTSDLLATVSVDQRVALWRLCGE
GRLRWQGALFSHV-A-DAA----------------GLVVW
*
