>P1;ENSDARG00000074719

--------------------------------------------------
-------------------MQKEHLFKVLVIGDLGVGKTSIIK-RYVHQI
FSQHYRATIGVDFALKVLHWDSQTVVRLQLWDIA-G--------QERYGN
MTRVYYREAVGALIVFDVTRSSTFDAVLKWK--DDLDLKVSLN-------
---------------------NGKPVPAVLLANKSDQSREGLCSQIPKLD
TFCK-------ENGFVGWFETSAKENSNIEAAAKCLVDHILAHEENIV-N
-N---------TDPDVVALPGYNNNTKERVRSRCMTCSKS----------

*
>P1;ENSORLG00000001857

--------------------------------------------------
----------------VEMQQQEFLFKVLVIGDLGVGKTSIIK-RYVHQI
FSQHYRATIGVDFVLKVLQWDNDRVVRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDVTRASTFDAVLKWK--DDLDSKVTLS-------
---------------------HGRPVPAVLLANKSDQM----ASQVPKLD
SFCR-------ENGFVGWFGTSAKDNTNIEEAARCLVEHILTNEESPA-A
-E---------RESGSLILSGHTNTTKN--HFRCSSCVK-----------

*
>P1;ENSXMAG00000000327

--------------------------------------------------
-------------------MQQELLFKVLVVGDLGVGKTSIIK-RYVHQI
FSQHYRTTIGVDFALKVLQWDSDTVIRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDVTRASTFEAVLKWK--DDLDAKVTLN-------
---------------------HGRPIPAVLLANKSDQI----ACQLPKLD
FFCR-------ENGFVGWFETSAKENTNIDEAARCLVEHIMNNEESSV-S
-E---------REPTSILLSGYASTARS--PLNCSSCL-K----------

*
>P1;ENSTRUG00000004036

--------------------------------------------------
-------------------MQHERLLKVLVIGDIGVGKTSIIT-RYVHQV
FSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIAEG--------QERYGN
MTRVYYKEAVGALVVFDMTRLSTFQAVLKWK--GDLDSKVALG-------
---------------------NGRTVPAVLLANKCDQRDHGLCPKLPKLE
SFSR-------EYGFIGWYETSAKDDTNIDAAITCLVKSIMSLEEESATA
-D----------AAGANH--------------------------------

*
>P1;ENSAMXG00000005910

--------------------------------------------------
-------------------MQQEHLFKVLVIGDLGVGKTSIIK-RYVHQI
FSQHYRATIGVDFALKVLNWDSQTVIRLQLWDIA-G--------QERYGN
MTRVYYREAVGALIVFDVTRASTFDAVLKWK--DDLDSKVTLS-------
---------------------NGKPVPAVLLANKSDQLREGVCSQIPKLD
TFCK-------ENGFVSWFETSAKENTNIEAAARCLVQHILAHEENTV-N
-D---------SDPDTVTLPGYNNNTKDHGRTSCSACSKY----------

*
>P1;ENSGACG00000020438

-------------------------------------------------V
M-------LRIKQICSAATMQQELLFKVLVIGDLGVGKTSIIK-RYVHQI
FSQHYRATIGVDFALKVLQWDRDTVVRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDVTRASTFDAVLKWK--EDLDSKVTLN-------
---------------------PGRPVPAVLLANKSDQL----ASQQPKLD
SFCR-------ENGFVGWFETSAKENANIEEAARCLVQHILNNEESPA-V
-E---------RDPGAAVLSAYTNTAKD--HLNCSSC-------------

*
>P1;ENSDARG00000036499

--------------------------------------------------
-------------------MQQERLLKVLVIGDLGVGKTSIIK-RYVHQI
FSQHYRATIGVDFALKVLNWDHRTVVRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDMTRASTFQAVLKWK--KDLDSKVALG-------
---------------------NGRPLPAVLLANKCDQQRYGLCSKLPKLE
HFSR-------DHGFVGWYETSAKDNTNIDAAIMRLVENIMAVEEENVPV
-E---------SDPSVLILPAFDYNLKERSDSRCSVCTKFQSSIKPHSEL

*
>P1;ENSTNIG00000003678

-------------------------------------------------C
CGSPPARALAVPTPAPVSAMQQERLLKVLVIGDLGVGKTSIIT-RYVHQV
FSQHYRATIGVDFALRVLDWDHKTVVRLQLWDIA-G--------QERYGH
MTRVYYREAVGAL-VFDMTRMSTFQAVLKWK--GDLDSKVALG-------
---------------------NGRPVPAVLLANKCDQRAQGLCPKLPKLE
AFCR-------DSGFIGWYETSAKDDTNIEAAIMCLVRSIMSLEE-----
--------------------------------------------------

*
>P1;ENSGACG00000001952

--------------------------------------------------
----------------ARGMQRERLLKVLVIGDLGVGKTSLIK-RYVHRV
FSQHYRATIGVDFALKMLSWDQKTVVRLQLWDIAEG--------QERYGN
MTRVYYREAVGALVVFDMTRLSTFQAVLKWK--EDLDSKVALS-------
---------------------NGTPVPAVLLANKCDQRSHGLCPKLPKLE
NFSR-------QCGFVGWYETSAKDDTNIDAAVTCLVESIMAAEDERATA
AR-------DEPEGGVLVLPRLDCDAKEKERRGCSGCASL----------

*
>P1;ENSXMAG00000001484

--------------------------------------------------
-------------------MQQERLLKVLVIGDLGVGKTSIIK-RYVHQV
YSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIA-G--------QERYGN
MTRVYYREALGALVVFDMTRLATFQAVLKWK--RDLDSKVTLS-------
---------------------NGKPVPAVLLANKCDQRQLGLCPKLPKLE
KFSQ-------DHGFVGWFETSAKDDTNIDSAITCLVKAITSAEEEKVSR
-DAA--P--SESDGGVIVLPRFDHSAKEKGLNDCAGCTSTKPRP--GASD

*
>P1;ENSONIG00000006996

--------------------------------------------------
-------------------MQRERLLKVLVIGDLGVGKTSIIK-RYVHQV
FSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDMTRLSTFQAILKWK--GDLDSKVALS-------
---------------------NGRPVPAVLLANKCDQRRHGLCPKLPKLE
NFSK-------EYGFVDWYETSAKDNTNIDAAITCLVKSIMSVEEERALG
-EATSGADKGDPDGSVLVLPRFDYNTTEKGLGGCAGCLSIKPKQ--DQ-D

*
>P1;ENSONIG00000008546

--------------------------------------------------
----------------PAAMQQELLFKVLVIGDLGVGKTSIIK-RYVHQI
FSQHYRATIGVDFALKVLQWDSNTVIRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDVTRASTFDAVLKWK--DDLDSKVTLN-------
---------------------HGRPVPAVLLANKSDQL----VSQQPKLD
AFCR-------ENGFVGWFETSAKENTNIEEAARCLVEHILRNEESLV-T
-E---------REPGSLILSGCTTTSKE--HLGCSSCSKW----------

*
>P1;ENSAMXG00000003714

--------------------------------------------------
-------------------MQQERLLKVLVIGDLGVGKTAIIK-RYVHQV
FSQHYRATIGVDFALKVLNWDHRTVIRLQLWDIA-G--------QERYGN
MTRVYYREAVGALVVFDMTRASTFQAVLKWK--MDLDSKVALN-------
---------------------NGRPVPAVLLANKCDQQKQGLCARLPKLD
TFSR-------DHGFVGWYETSAKDNTNIDAAIMCLVENILASDVENTAV
-D---------SDPSLLVLPSFDYNLRERSGPGCSACSRRRSTPRDNSDF

*
>P1;ENSLOCG00000009050

ILRMLPSPVTSTPFSVKDILNLEQQSQQHQALHLEHPHAHLHQEVQPPPH
FQSPSCMLAAGESPSFSDGEEKMSFLNSLSVRDS-HGEASISPELYVQAA
LGHSA--DTKLEGDLEEQETKSCSITKSQECDDS-RHSDSERPQKQRTRR
KPRVLF----SQAQVFELERRFKQQRYLSAPEREHLASTLKLTSTQVKIW
FQNRRYKCKRQRQDKSLEMAGHHHPPPPRRVAVPVLVRDGKPC--LGGSQ
NYNAPYTVGANPYTYNG-YPAYTYSNPAYNSSYSCTYSSIPALPPTTT-A
-NAF----MNMNLGNIASLSSS-SQPQTHQGTAVSPCQGTLQGIRA---W

*
