>P1;ENSXMAG00000001259

------------------MEASL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------AY--------------------------------TSES
AFLDNLRKRFHENLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKDLDIYSKKQMDTY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNVFRTMLSEFNN------------
----------HFILISGESGAGKTEASKKI--LQFYAVSCPSTKLLNNV-
------------------------------------------RDRLLLSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDHRGGAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEDLLRWLGLERNCKNYRYLVQGDCAKVSSINDK------SDWKTVR
KALSVIDFSESDTE-HLFGIIASVLHL--GNLK------FEA-DARGYAT
IK-N---NQE--MHWVSKLLGIP---------------------------
-------------------------------------------NQVLQQG
LTHRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------EEVLSPFSVEHAVYARDALAKAVYG
R-TFDWLVN--------------------KINESLANQ------------
-----------D-----SSRKRVVGLLDIYGF-EVFSV-------NR--F
--------DHFQAKTLN---------IIIPFPLFHFSCSCAKWEPVPYFN
NKIICDLVEEKFRGIISLLDEECLRPGEATDLTFLEKM------------
---EEKIGGHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADKNTRKTLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNNLLYRSGKEVMQHSKNGIIKHCFPSSEPDSK
KRPETVVTQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLVGLTEILMS-------------------
-------------KEPW---------------------------------
------------------------YVRCIKPNESKQPAKFDDVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEL----------------------------
--------------------------------------------------
----FLQRY----KALC---------------------------------
----------------------------PDTWPNWKGTPAEGVRCLIKHL
GYKTDEYKLGRTKI-FIRHPRTLFATEDAF--------------------
--QVCKHQLATRI-------------------------------------
--------QA-------KYKGYRVKEEYLKQKAAATKIENCWRGLMARKE
RERRAWAVKVIKKFIKGFMTRNQPACIDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLVYVRQNYLTRLKENLPKSVLDMDSWLTPPPILKEVSLL---LQNVF
----------VRYLVRQYVREITPQRKAQ-LLLKAQTSSMFKGKKENYPL
SVC----------------------SPFVDT-------------RIA--F
EDI-----------------------------------------------
----------------------------------NLKVLQTIQHEHLKYG
VP---VVKY---DRNGFRP---RLR-LLIFTQEAAYLVEETK--------
------------------IKQRIDFTSLKGVSVSNLS------DNFLILH
VTCDDIKQ-KGDLVLQCDFLY-----------------------------
---------------------EALTKLSFIADKQSCIKVVQGSVRFDIQP
GREGFVDFKSGQESMVYRAKNGHLMVVSVEA-------------------
--------------------------------------------------
-------------NT-------Q--------
*
>P1;ENSTRUG00000011919

------------------MESSL---------------------------
-------------------------------------NARDRVGI-----
------QDFVLLD-------------------------------------
------------AH--------------------------------TSES
AFLDNLRKRFHENLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELDIYSKKQMDTY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNVFRTMQSEYNN------------
----------HFILISGESGAGKTEASKKI--LQFYAVSCPSTRLLNNI-
------------------------------------------RDRLLLSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDHQGGAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEDLLRWLGLERNCKHYSYLVQGDCAKVSSINDK------SDWKIVR
KALSVIEFSESDIE-DLFGIIASVLHL--GNIK------FDV-DSEGYAS
LN-NS-SNNE--MHWVSKLLGIP---------------------------
-------------------------------------------TEVLHRG
LTHRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------EEVFSPFSEDHAVYARDALAKAVYG
R-TFNWLVN--------------------KINESLANK------------
-----------D-----SSRKTVIGLLDIYGF-EVFNV-------NSFSF
--------EQFCINYCNEKLQQLFIQLTLKSEQEEYEMEGIEWEPVPYFN
NKIICELVEAKHRGIISLLDEECLLPGEASDLTFLAKM------------
---EEKIGSHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADQKTRKTLERGEFRLLHYAGEVS-------YSVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRSGKEVMRQSKNAIIKLCFPSTESDSK
KRPETVVTQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLTGLTEILLS-------------------
-------------KEPW---------------------------------
------------------------YVRCIKPNEAKQPGRFDDVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEV----------------------------
--------------------------------------------------
----FLQRY----KPLC---------------------------------
----------------------------PDTWPNWKGTAAEGVKRLIVHL
GYKRDEYKMGRTKI-FIRHPRTLFATEDAF--------------------
--QVCKHKLATRI-------------------------------------
--------QA-------KYKGYRMKGDYQRQREAATRIENCWRGLMARKE
REKRAWAVKVIKRFIKGFITRNQPLCTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAYVRYSYLTRLRENLPKTVLEKDSWLTPPPIMQEASQL---LKKLY
----------IRHMVRKYVGEVTPQRKAQ-LQLKLQTSSMFKGKKENYPF
SVC----------------------RPFVDT-------------RIG--V
EDI-----------------------------------------------
----------------------------------NIKVLQMIQHEHIKYS
VP---VVKY---DRNRFRP---RLR-QLVFTQEAAYLVEEAK--------
------------------IKQRISHSSLKGVSVSNLS------DNFLILH
VTCDDIKQ-KGDLVLQCDYLF-----------------------------
---------------------EALTKLSVIANKQKSIHVVQGSARFDIHP
GREGFVDFKSGQESTVYRAKNGHLMVVSADL-------------------
--------------------------------------------------
-------------MS-------S--------
*
>P1;ENSAMXG00000006820

------------KLGLLDLEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------AH--------------------------------NSET
AFLDNLKKRFSEDLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---ISVNPYKELDMYSKKHMDLY-------------MG
VNFYELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYHTMLTEANN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSSALLDTV-
------------------------------------------RDRMLMSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDINFNFNGDPTGGHINNYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEDLLRQLGLERDTKHYNYLAQGECSSVISINDK------NDWKTVR
NALSVVHFDDTDII-NHVYILFFIISL--RKSQ------FYDSYSLRNKC
IT-D---TYR--QCVVIPPMGFFI--------------------------
-------------------------------------------SCVLVDC
LT---LVLK-----------------------------------------
----------------------------------T---------------
-------------------------VTVLCPFTVDHAIYVRDALAKAIYG
R-TFTWLVN--------------------RINESLENQ------------
-----------D-----ASRKTVIGLLDIYGF-EVFYV-------NR--Y
-LLTPNTKHRFCINYCNEKLQQLFIQLTLKAEQEEYEAE-VNW------S
DKILNISVSLSLCVCVCVQDEECVRPGDATDLTFLEKL------------
---EEKMGNHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADKKTRKTLDRGDFRLLHYAGEVT-------YCVV-GKRYH-----
--------------------------------------------------
-----------------NKHLIINTTVNITLNTRITLVNTT-------IN
NEYITVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLLGLTEILMA-------------------
-------------KEAW---------------------------------
------------------------YVRCLKSNDNKQSGKFDDVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRRYEE----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWRGVPSEGVEKLVKHL
GYQPDEYKMGRTKI-FIRYARTLFATEDAY--------------------
--EICKHELATRI-------------------------------------
--------QA-------KYKGYRAKGEFKKQKEAATKIETCWRGVQARKE
REKRAWAVKVIKKILHVANDDPKQKS------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----VVL-------------------------------NST---LHMLV
----------FSLLLKKFLGAASEQQHCV-MISVQQQNDQPTNDRFKFIF
TLF----------------------SAILNY-------------MLKSSS
HAF-----------------------------------------------
----------------------------------SLLPLNKLSVFQLKYK
SCTGLDNLY---DWNSTTEVAKRVT-RVALLSVAAGMVKCAV--------
------------------I------NFCATIKITTLS------LGYSKSS
LKCLDMND-KGDVVLQCDHLF-----------------------------
---------------------EAVTKLSVLTKKQDAIKAVQGSIKFQFHG
GKEGFVDFSTGQEPMVYKGKNGHLTVVAPRT-------------------
--------------------------------------------------
-------------RGR---------------
*
>P1;ENSORLG00000008264

------------------MEASL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------PY--------------------------------TSET
AFLDNLRKRFHENLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELDIYNKKQMDTY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNVFRTMQSESNN------------
----------HFILISGESGAGKTEASKKI--LQFYAVSCPSTKLLNNV-
------------------------------------------RDRLLLSN
PVL-EA---------------------------------FGNAKTLKNNN
SSRFGKYMDIQFDHQGGAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEDLLRWLGLERNCTKYNFLVQGGCAKVSSINDK------SDWKTVR
KALSIIEFSESETEQQLFGIIASVLHL--GNIK------FEA-NGQGYAT
VN-N---NQG--MHWVSKLLGIP---------------------------
-------------------------------------------NQVLQQG
LTHRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------EEVLSPFSVDHAVYARDALAKAIYG
R-TFNWLVN--------------------KINESLANK------------
-----------D-----SSRKTVIGLLDIYGF-EVFNL-------NS--F
--------EQFCINYCNEKLQQLFIQLTLKSEQEEYETEGIEWEPVPYFN
NKIICELVEEKFRGIISLLDEECLRPGEATDLTFLEKM------------
---EEEIGGHPHFTT-----------------------------------
------------------HKL-----------------------------
----ADKKTRKTLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRSGKEVMQQSKNAIIRHCFPFTEPDSK
RRPETVVTQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLADLAEILMA-------------------
-------------KEAW---------------------------------
------------------------YVRCIKPNEAKQPGHFDDVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEI----------------------------
--------------------------------------------------
----FLQRY----KALC---------------------------------
----------------------------PETWPNWKGTAAEGVQCLIKHL
GFKPDEYKLGRTKI-FIRHPRTLFATEDAF--------------------
--QVCKHKLATRI-------------------------------------
--------QA-------KYKGHRVKEGYLRQKEAATKIENCWRGLMARKE
RERRAWAVKVIKKFIKGFMTRNQPACVDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLTYVRLNYLTRLKENLPKTVLEKDSWLTPPPIMTEVSHL---LKAIY
----------IRCMVRRYIRGLSVQRKAQ-LLLKSLTSSMFKGKKENYPF
SVS----------------------RTFLDT-------------RIA--L
ENI-----------------------------------------------
----------------------------------NTRVLQMIRHEHIKYS
VP---VVKY---DRNGFRP---RLR-LLIFTQEAAYLVEEAK--------
------------------IKQRIDYSSLKGVSVSNLS------DNFLILH
VTCDDSKQ-KGDLVLQCDHLF-----------------------------
---------------------EALTKLSVIADKQNCIKVVQGSVRFDIQP
GREGFIDFKSGQEFMVYRAKNGHLMVVSLKS-------------------
--------------------------------------------------
-------------ERV----KFN--------
*
>P1;ENSONIG00000013496

------------------MEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------E---------------------------------TTEA
AFLSNLKKRFSKDLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELDIYNKKQMDIY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYHTMLTEFNN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSTTLLNTV-
------------------------------------------RDKMLMSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDGQGDAVGGHILNYLLEKSRVVHQNHGERNFHIFYQLV
EGGSDDLLHQLGLERGCQHYNYLTQGQCAIVQSINDK------NDWKTVK
NALQIINFDETATN-HLFEVIASVLHL--GNVR------FDS-DSKGHAL
LN-N---NTE--LHWVSNLLGVD---------------------------
-------------------------------------------AHRLQEG
LTFRKIEAK-----------------------------------------
----------------------------------K---------------
-------------------------DQVLSPFTTDHAIYARDALAKAIYG
Q-TFTWLVN--------------------RINESMENK------------
-----------D-----PSRKTVIGLLDIYGF-EVFYV-------NS--F
--------EQFCINYCNEKLQQLFIELTLKSEQEEYEAEGIEWEPVQFFN
NKIICDLIEEKHRGIISLLDEECLRPGDATDLTFLERL------------
---EEKMGNHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADKMTRKTLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRNIKDLMCQSKNDIVKECFSSMDPDSR
RRPETVVTQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------SSLQKLTEILMA-------------------
-------------KEAW---------------------------------
------------------------YIRCLKSNESKQSGQFDEALIRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYDV----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWRGVAADGVEVLVQHL
GYLPDEYKMGRTKI-FIRHPRTLFATEDAY--------------------
--EKCKHELATRI-------------------------------------
--------QA-------KYKGYRAKGEYRKQKEAATKIESCWRGTQARKE
KEKRAWAVKVIKKFIKGYMTRGQAKNTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQNYLNRLRDNLPKTVLDKTTWLTPPAVLTETSEM---LRKLH
----------YRLMVRKYVRGITPQKKAQ-FQMKLITSSIFKGKKDSYPQ
SVA----------------------HPFADS-------------RIS--E
EDI-----------------------------------------------
----------------------------------NPRVIQMIRNERIKYC
VP---VIKY---DRNGFKP---RQR-QLILTQTAVYVIEEAK--------
------------------IKQRVLYTSLKGISVSNLT------DSTIVFH
ITREEPKQ-KGDLVVQCDHLF-----------------------------
---------------------ELLTKLCVIANKQNAIKVVQGSINFEIQA
GKGGAVDFSTGPEPMVYKAKNGHLMVVATRA-------------------
--------------------------------------------------
-------------RT-------R--------
*
>P1;ENSDARG00000061968

---------------QLDLEGAL---------------------------
-------------------------------------IARDRVGI-----
------QDFVLLD-------------------------------------
------------AH--------------------------------NSET
AFLDNLKKRFTEDLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---ISVNPYKELDIYTKKQMDLY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYHTMLSEANN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSSTLLDTV-
------------------------------------------RDRMLMSN
PVL-EA---------------------------------FGNAKTMKNDN
SSRFGKYMDIQFDIQGDAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEDLLRQLGLERDTKRYCYLVQGECSNVSSINDK------NDWKTVK
NALSVIDFDASDTE-HLFGIISSVLHL--GNVH------FDR-DTKGYAI
LN-S---NAA--LRWVSKLLGVH---------------------------
-------------------------------------------VQVLHGA
LTFRKIEAK-----------------------------------------
----------------------------------S---------------
-------------------------EEVLSPYTVDHAIYARDALAKAIYD
R-AFTWLVN--------------------RINESLENKV-----------
--------SKSD-----SERKTVIGLLDIYGF-EVFTA-------NS--F
--------EQFCINYCNEKLQQLFIQLTLKAEQEEYEAEGIGWEPVQFFN
NKIICDLVEEKHRGIISVLDEECVRPGDATDLTFLEKL------------
---EEKMGNHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADKKTRKSLERGDFRLLHYAGEVT-------YCVV-GFIDK-----
--------------------------------------------------
-----------------NNDLLYKNIKDMMRLSKNPIIQQCFPATKAESR
RRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLLRLTEILTA-------------------
-------------KEAW---------------------------------
------------------------YVRCLKSNDNKQQGKFDEVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEV----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWRGVPSEGVEKLVQHL
GYQPDEYKMGRTKI-FIRYARTLFATEDAF--------------------
--EICKHELATKL-------------------------------------
--------QA-------KYKGYKVKGEFRKQKEAATKIETCWRGVQARKE
RDRRAWAVKVIKKFIKGYLTRREAKTTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQSYLNRLKANLPKTVLDKTTWLTPPPVMTETSEI---LRKLH
----------TRMMVRKYVRGITPQKKAQ-MQQKVVTSAIFKGKKDSYPS
SIA----------------------VPFVDT-------------RIN--E
QDI-----------------------------------------------
----------------------------------NMRVLQTIRHERIKYS
VP---VVKY---DRNGFKP---RQR-QLILTQAAAHLVEEAK--------
------------------IKQRVDYVSLKGASVSNLG------DSVMILH
VAFNDPKQKKGDLVLQCDHLF-----------------------------
---------------------EALTKLAMIANKQNNITVVQGSIKFEIQA
GKQNAVDFSTGQEPMIYKGPNGHLMVVAPRI-------------------
--------------------------------------------------
-------------KS-------R--------
*
>P1;ENSGACG00000009207

------------------MEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------E---------------------------------TTDA
AFLSNLTKRFSKDLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELDIYNNKQMDLY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYHTMLTEFNN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSTTLLNTV-
------------------------------------------RDKMLMSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDSQGDAVGGHILNYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEGLLHQLGLERDCQHYDYLTQGECAIVSSINDR------NDWKTVK
NALQIINIDEININ-HLFGTVASVLHL--GNVR------FDS-DSKGRAQ
LNEN---NAE--LRWVSDLLGVD---------------------------
-------------------------------------------AHSLQEG
LTYRKIEAK-----------------------------------------
----------------------------------K---------------
-------------------------DQVLSPFTIDHAIYVRDALAKAIYG
Q-TFTWLVN--------------------RINESMENK------------
-----------VGRRRAGDRKNVIGLLDIYGF-EVFYV-------NSE-L
--------GPFVMTYF-----QLFIQLTLKAEQEEYEAEDIEWEPVQFFN
NKIICDLVEEKHRGIISILDEECLRPGDATDLTFLERL------------
---EERMSNHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADKMTRKTLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYKNIKDLICQSKNAIISESFSTMDSDSM
RRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------SSLLKLTDILMA-------------------
-------------KDAW---------------------------------
------------------------YIRCLKPNESKQPGHFDEALVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEV----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWRGLPADGVEVLVQHL
GYLPDEYKMGRTKI-FIRHPRTLYATEDAF--------------------
--EKCKHDLATRL-------------------------------------
--------QA-------KYKGYKAKGEFRKQREAATKIETCWRGVQARKE
RDRRAWAVKVIKKFIKGYMTRGQAKNTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQNYLNRLKGNLPKTVLDKTTWQTPPAVLAETSEI---LRKLH
----------YRLMVRKYVRGITPQKKAQ-FQMKLLTSSIFKGKKESYPQ
SVA----------------------QPFVDT-------------RIS--E
QDI-----------------------------------------------
----------------------------------NMRVLQMIRNEHIKYG
VP---VIKY---DRNGFKP---RPR-QLVLTQRAAHVIEEAN--------
------------------IKQTVPYTSLKGISVSNLT------DGIVVFH
IACEVPKQ-KGALIMQCDTLF-----------------------------
---------------------EFLTKLSIIANKQNAIQVVHGSIQFEIQA
GKESAVDFSSGQEPTVYKAKNGHLMVVAARA-------------------
--------------------------------------------------
-------------RT-------R--------
*
>P1;ENSXMAG00000007888

--------LILVAQGRLDMEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------E---------------------------------TTEV
AVISNLKKRFSKDLIYTYI-------------------------------
--------------------------------------------------
--------GTLI---VSVNPYKDLDIYNKKQMDVY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYHTMLTEFNN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSTTLMNTV-
------------------------------------------RDKMLMSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDSQGDAVGGHILNYLLEKSRVVHQNHGERNFHVFYQLV
EGGSDDLLTQLGLERDVQHYYYLTQGECAIVSSINDK------NDWKSVK
NALQVIEFDETNTN-HLFRVVASVLHL--GNVH------FDP-DSKGHAL
LK-N---NTE--LNWVSDLLGVD---------------------------
-------------------------------------------ANNLKEG
LTFRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------EQVLSPFTIDHAIYVRDALAKAIYG
Q-TFTWLVN--------------------RINESMENK------------
-----------D-----SSRKTVIGLLDIYGF-EVFYV-------NR--I
--------KPNATNIHKFSIKTEIFALFVISCKTDQNMENEKWEPVQFFN
NKIICDLVEEKHRGIISILDEECLRPGDATDLTFLDRL------------
---EEKMGNHPHFVT-----------------------------------
------------------HRL-----------------------------
----ADKMTRKTLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRNIKNLVCQSKNTIVRECFSAVDTTNK
RRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLQKLTEMLMA-------------------
-------------KEAW---------------------------------
------------------------YIRCLKSNESKQPGQFDEALIRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYED----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWRGMPADGVEVLAQHL
GYLPDEYKMGRTKI-FIRHPRTLYATEDAY--------------------
--EKCKHDLASKL-------------------------------------
--------QA-------KYKGYKVKGEFKKQKEAATKIETCWRGAQARKE
KEKRAWAVKVIKKFIKAYINRGEAKSTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQSYLNRLKNNLPKTVLDKTTWLTPPAVLTEASEI---LRKLH
----------YRLMVRKYVRGIPPQKKAQ-LQMKVVTSAIFKGKKENYPP
SIP----------------------QLFLDT-------------RIS--E
QEI-----------------------------------------------
----------------------------------NIRVLSMIRNEQIKYS
VP---VIKY---DRNGFKP---RPR-QFILTKTAAYLVEEAK--------
------------------IKQRVSYNSLQGISVSSLS------DGIIAIH
ITCEDPKQ-KGDLIIQCEHLY-----------------------------
---------------------EFLTKLSIIANKQDAIKVVQGSIKIKIQS
GKESSVDFTTGQEPMVYKAKNGHLMVVATRT-------------------
--------------------------------------------------
-------------RT-------R--------
*
>P1;ENSORLG00000007579

VP---KLLTAFLQQGQLDMEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLE-------------------------------------
------------E---------------------------------TNEA
AFISNLKKRYSKDLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELDIYNKKQMDTY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYHTMLTEFNN------------
----------HFILISGESGAGKTEASKKI--LQFYSVSCPSTTLMSTV-
------------------------------------------RDKMLMSN
PVL-EA---------------------------------FGNAKTLKNNN
SSRFGKYMDIQFDSQGDAVGGHILNYLLEKSRVVHQNHGERNFHIFYQLV
EGASDSLLQQLGLERDCQHYNYLTQGECATVPSINDK------NDWKSVK
NALQVIEFDEVNTK-HLFEVVASVLHL--GNVQ------FDT-DNRDRAL
LN-D---NTE--LQWVSKLLGVD---------------------------
-------------------------------------------AHSLQEE
LTFRKIEAK-----------------------------------------
----------------------------------Q---------------
-------------------------EQVLSPFTTDHAIYGRDALAKAIYG
Q-TFTWLVH--------------------RINDSTENKI-----------
-------LLSQD-----ASKKTVIGLLDIYGF-EVFYV-------NS--F
--------EQFCINYCNEKLQQLFIQLTLKAEQDEYEAEGIEWEPVQFFN
NKIICDLVEEKHRGIISLLDEECLRPGDVTDLTFLERL------------
---EEKMGNHPHFVT-----------------------------------
------------------HRL-----------------------------
----ADKTTRRTLERGDFRLLHYAGEVT-------YCVILGFLDK-----
--------------------------------------------------
-----------------NNDLLYKNIKDLMCQSKNAIVSECFSNMDRGNK
RRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------SSLLKLTEMLMA-------------------
-------------KQAW---------------------------------
------------------------YIRCLKSNESKQPGQFDEALIRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYED----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWRGFPSDGVEVLVQHL
GYLPDEYKMGRTKI-FIRHPRTLYATEDAY--------------------
--ERCKHELATRL-------------------------------------
--------QA-------KYKGYKAKGEFKKQKEAATKIESCWRGTQARKE
REKREWAIKVIKKFINGYLNRGEAKTTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQSYLNRLRGNLPKTVLDKTTWLTPPSVVKETSEI---LRKLH
----------YRLMVRKYVRGLTPQRKAQQLQLKLVTSTIFKGNKDSYPQ
SVP----------------------QPFLET-------------RIS--D
QEI-----------------------------------------------
----------------------------------NPKILQTIRNERIKYS
VP---VIKY---DRNGFKP---RPR-QLILTQTAAYLIEESK--------
------------------VKQRLVYASLKGISVSNLT------DGIIVLH
ISSEDPKQ-KGDLVIQCDHLY-----------------------------
---------------------EFLTKLCVIANKQSAVRIVQGSIKIEIQA
GKESAVDFSTGQEAMVYKAKNGHLMVVATRA-------------------
--------------------------------------------------
-------------RV-------R--------
*
>P1;ENSTRUG00000015306

SNFRNNVVGVEMKKGQLDMEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------E---------------------------------TTEV
AFLGNLQKRFSKDLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKDLDIYNKKDMELY-------------KG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNAYQTMLAEFNN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSTALLNTV-
------------------------------------------RDKMLMSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDSQGDAVGGHILNYLLEKSRVVHQNHGERNFHIFYQIV
EGGDDHLLRQLGLERDPQKYNYLTQGQCAIVSSINDR------NDWKTVK
NALQIMNIDEINTK-DLFGIVASVLHL--GNVC------FDS-DGTGQAV
LR-D---SAE--LHWVSNLLGVD---------------------------
-------------------------------------------APSLQEG
LTYRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------DQVFSPFTVDHALYARDALAKAIYG
H-TFTWLVN--------------------KINASMENK------------
-----------D-----SSQKTVIGLLDIYGF-EVFCV-------NS--F
--------EQFCINYCNEKLQQLFIQLTLKAEQEEYQAEDIEWEPVQFFN
NKIICDLVEEKHRGIISILDEECLRPGDATDLTFLERL------------
---EENMGNHPHFVS-----------------------------------
------------------HKL-----------------------------
----ADKMTRKTLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRNLKDLICQSKNAIVKECFSTLDRDSR
RRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------SSLLKLTEILVA-------------------
-------------KEAW---------------------------------
------------------------YIRCLKSNESKHPGQFDEVLIRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKFDV----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWTGMPADGVEVLVQHL
GYLPNEYKMGRTKI-FIRHPRTLYATEDAF--------------------
--EKCKHELATRL-------------------------------------
--------QA-------KYKGYRAHGEFRKQKEAATKIESCWRGAQARKE
RERRAWAVKVIRQFIKGYMSRGQAKTTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQNYLNRLRNNLPKTVLDKTTWLPAPAVLAETSEL---LRKLH
----------YRLMVRRYVRGLTPQKKAQ-FQLKFITSCVFKGKKDSYPQ
SVA----------------------QPFMDT-------------RIS--E
QDI-----------------------------------------------
----------------------------------NIRVLQTIRNEHIKYG
VP---VIKY---HRNGFKP---RAR-QLVLTQTAAYVVEEAK--------
------------------IKQRVLYTVLKGVSVSNLT------DSIIVFH
ITCEDPKQ-KGDLVLQCDHLF-----------------------------
---------------------ELLTKLCVIANKQNAVKVVQGSVKIEIQP
GKESAVDFSTGQEPMIYKAKNGHLMVVSPRA-------------------
--------------------------------------------------
-------------RT-------R--------
*
>P1;ENSGACG00000016954

------------------MEASL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------AY--------------------------------MSES
AFLDNLRKRFHENLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELNIYNKKQMDTY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNVFRTMLSEFNN------------
----------HFILISGESGAGKTEASKKI--LQFYAVSCPSTKLLNNV-
------------------------------------------RDRLLLSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDHQGGAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEELLRWLGLERNCQNYSYLVQGDCAKVSSINDK------SDWRTVR
GALSVIHFSESDIE-DLFGIIASVLHL--GNIK------FEA-DVRGYAS
LN-N---DQE--MHWVSKLLGIP---------------------------
-------------------------------------------TQVLKQG
LTHRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------EEVLSPFSVDHAVYARDALAKAIYG
R-TFNWLVN--------------------KINESLVNT------------
-----------D-----FSRKTVIGLLDIYGF-EVFYV-------NS--R
FT-----HEEHNTNCASDRL-QLFIQLTLKSEQEEYEMEGIEWEPVPFFN
NKIICDLVEEKHRGMISLLDEECLRPGEATDLTFLEKL------------
---EETIGGHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADIKTRKTLDRGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRNGKEVMRQSKNAIIKHCFPSSEPDSK
KRPETVVTQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------SSLVGLTEILMS-------------------
-------------KEPW---------------------------------
------------------------YVRCIKPNDAKQPGRFDDVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEI----------------------------
--------------------------------------------------
----FLQRY----KALC---------------------------------
----------------------------PDTWPHWKGTAAEGVRCLIQHL
GYKPDEYKMGRTKI-FIRHPRTLFATEDTF--------------------
--QVCKHRLATRI-------------------------------------
--------QA-------KYKGYRVKGHYLKQREAATKIETCWRGMLARKE
REKRAWAVKVIKKFIKGFMTRNQPACVDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAYVRQNYLTRLRDTLPKTVLEKDSWLTPPPIMEELSQL---LKKLY
----------IRHMVRKYVGGITPQRKAE-LLLKAEASSIFKGKKESYAL
SVC----------------------RPFVDT-------------RIN--A
EDT-----------------------------------------------
----------------------------------SAKVLQMIRHEHIKYS
VP---VVKY---DRNGFRP---RLR-QLIFTREAAYLVEEAK--------
------------------IKQRINYISLKGVSVSNLS------DNFLILH
VSCDDIKQ-KGDLVLQCDHLF-----------------------------
---------------------EALTQLSLIANKQNCIKVVQGSVRFDIQP
GREGFVDFKSGQESMVYRAKNGHLMVESTRT-------------------
--------------------------------------------------
-------------KS-------R--------
*
>P1;ENSTNIG00000015893

R-----LKAELVAQGQLDMEGAL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------E---------------------------------TTEA
AFLGNLKKRFSKDLIYTYV-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELDIYNKKDMELY-------------KG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HLYALADNAYQTMLAEFNN------------
----------HFILISGESGAGKTEASKKI--LQYYAVSCPSTALLNTV-
------------------------------------------RDKMLMSN
PIL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIEFDSQGDAVGGHILNYLLEKSRVVHQNHGERNFHIFYQIV
EGGDDDLLHQLGLERDPQKYKYLTQGQCAVVSSINDR------NDWKTVK
NALQIINIDEINTK-ELFGVVASVLHL--GNIR------FGS-DSAGQAV
LN-N---NAE--LHRVSDLLGVD---------------------------
-------------------------------------------ALSLQEG
LTYRKIEAR-----------------------------------------
----------------------------------T---------------
-------------------------DQVLSPFTVDHALYARDALAKAIYG
H-TFTWLVN--------------------KINASIENK------------
-----------D-----SSQKTVIGLLDIYGF-EVFCV-------NS--F
--------EQFCINYCNEKLQQLFIQLTLKAEQEEYQAENIEWEPVHFFN
NKIICDLVEEKHRGIISILDEECLRPGDATDLTFLERL------------
---EEKMGNHPHFVS-----------------------------------
------------------HKL-----------------------------
----ADKMTRKSLERGDFRLLHYAGEVT-------YCVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRNIKDLVCQSKNAIVKECFSTMDRDSR
RRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------SSLLKLTEILVA-------------------
-------------KEAW---------------------------------
------------------------YIRCLKSNESKHPGRFDDVLIRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKFEV----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PATWPHWNGVPADGVEVLVQHL
GYLPNEYKMGRTKI-FIRHPRTLYATEDAF--------------------
--EKCKHELATRL-------------------------------------
--------QA-------KYKGYRAHGEFKKQKEAATKIESCWRGAQARKE
RERRAWAVKVIKQFIKGYMSRGQAKTTDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQNYLNRLKDNLPKTVLDKTTWLPPPAVLAETSEL---LRKLH
----------YRLMVRKYVRGLTPQKKAQ-FQLKFITSSVFKGKKDSYPQ
SVA----------------------QPFVDT-------------RIS--E
QDI-----------------------------------------------
----------------------------------NIRVLQMIRNEHIKYS
VP---VVKY---NRNGFKP---RAR-QLILTQTAAYVVEEAK--------
------------------IKQRVLYTFLKGISVSNLT------DSIIVFH
ITCEDPKQ-KGDLVLQCDHLF-----------------------------
---------------------ELLTKLCVIANKQSAVKVVQGSIRIEVQL
GKENTVDFSAGQEPMIYKAKSGHLMVVRQRC-------------------
--------------------------------------------------
-------------WS-------E--------
*
>P1;ENSDARG00000078603

------------------MEGSL---------------------------
-------------------------------------TARDRVGI-----
------QDFVLLD-------------------------------------
------------AY--------------------------------TSET
AFMDNLKKRFNENLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKELGIYTKKQMDIY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIFALADNVYRTMISETSN------------
----------HFILISGESGAGKTEASKKV--LQFYAVSCPSTRLLDNV-
------------------------------------------RDRLLLSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDHQGAAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEDELLRWLGLERNCQSYRYLIQGECAKVSSINDK------SDWKTVQ
KALTIIEFSEKDIE-HLFAIIASVLHL--GN-------------------
------------------LLGIP---------------------------
-------------------------------------------SDMLQEG
LTHRKIEAK-----------------------------------------
----------------------------------A---------------
-------------------------EEVLSPFTAEHAKYARDALAKAIYG
R-TFSWLVN--------------------KINESLANK------------
-----------D-----STRKTVIGLLDIYGF-EVFDV-------NS--F
--------EQFCINFCNEKLQQLFIQLTLKSEQEEYEMEGIEWEPVPYFN
NKIICDLVEEKHRGIISVLDEECLRPGEATDFTFLEKL------------
---EGKMSGHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADQKTRKTLERGDFRLLHYAGEVT-------YSVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRNIKEVMRQSKNSIIQHCFHTIEPDGK
KRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLAGLTEILMT-------------------
-------------KEPW---------------------------------
------------------------YVRCLKPNHCKQPDRFDDVMVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRRYEV----------------------------
--------------------------------------------------
----FLKRY----KALC---------------------------------
----------------------------PDTWPHWKGTPAEGVQRLIKHL
GYKTDEYKMGRTKI-FIRHPRTLFATEDAF--------------------
--EVCKHELATRI-------------------------------------
--------QA-------KYKGYRVKGDYLRQREAATKIETCWRGLQARRE
RERRAWAVKVIKKFIKGFMNRNQPVSMDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQSYLTRLKENLPKSVLDKTTWLTPPPIMQEASVL---LRNLY
----------TRLLVRKYVRGISAQRKMQ-LQTKALTSEIFRGRKESYPQ
SVC----------------------QPFADT-------------RIS--E
QDI-----------------------------------------------
----------------------------------NIKVLQLICPEGIKYS
VP---VIKY---DRNGFRP---RFR-QLIFTQAAAYLVEEAK--------
------------------IKQRVNYSSLKGVSVSNLS------DNFLILH
VACEDTKQ-KGDLVLQCSYLF-----------------------------
---------------------EALTKICVVTKNRSLIKVVQESVRFDIQP
GKEGFVDFKSSSESMVYRAKNGHLMVV-----------------------
--------------------------------------------------
----------------------X--------
*
>P1;ENSAMXG00000006824

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------FALADNVYRTMISEINN------------
----------HFILISGESGAGKTEASKKI--LQFYAVSCVRTEVLDIV-
------------------------------------------RDRLLLSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDHQGAAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEDELLHRLGLERNSENYMYLVEGECVQVGSINDQ------SDWKTVR
KALTVIDFSERDIE-HLFAVIASVLHL--GNIH------FEA--SRGYAT
LN-S---SEE--IHWLSKLLGIS---------------------------
-------------------------------------------ANLLQEA
LTHRKIEAK-----------------------------------------
----------------------------------G---------------
-------------------------EEVLSPFTVDHAKYARDALAKAVYG
R-TFTWLVN--------------------KTNESLENK------------
-----------D-----SSRKTVIGLLDIYGF-EVFDV-------NS--F
--------EQFCINYCNEKLQQLFIQLTIKSEQEEYEMEGIEWQPVPFFN
NKIICDLVEEKHRGIISVLDEECLRPGEPTDLTFLEKL------------
---EEKLAGHPHFVT-----------------------------------
------------------HML-----------------------------
----ADQKTRKTLGRGEFRLMHYAGEVT-------YSVT-GFVDK-----
--------------------------------------------------
-----------------NNDLLYRNIKDVMRQSKNPIIQQCFPSSEPDSK
KRPETVATQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NNLFSLTQILMS-------------------
-------------KEPW---------------------------------
------------------------YVRCLKPNNDKRPGHFDDVLVRHQVK
YLALME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRRYEV----------------------------
--------------------------------------------------
----FLKRY----KPLC---------------------------------
----------------------------PDTWPNWKGTAAEGVELLVKHL
GYRPSEYKLTRSKI-FIRHPRTLFATEDAF--------------------
--DICRHELATRI-------------------------------------
--------QA-------KYKGYRTKGDYLKQKEAATKIEACWRGLQARKE
RERRAWAVKVIKKFIKGFMNRNQPVSMDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAFVRQSYLTRLRENLPTSVLDRTSWLTPPPIMQEASVI---LQKVY
----------TRHLVRKYVRGITAQRKAQ-LQMKALISDIFKGKKENYPQ
SVH----------------------QPFADT-------------RIS--E
KDI-----------------------------------------------
----------------------------------NIRVLQVMCPEGIKYS
VP---VIKY---DRNGFRP---RFR-QLVLTQKAAYLVEEAK--------
------------------IKQRVEYSSLKGVSVSNLS------DNFLIFH
VTCEDIKQ-KGDLVLQCSYLF-----------------------------
---------------------EALTKLCLVMKNHKFIKVVDGSVRFDIQP
GREGVIDFKSSSESMVYRAKNGHLIVVSQYC-------------------
--------------------------------------------------
-------------TV-------C--------
*
>P1;ENSTNIG00000009071

------------------MESSL---------------------------
-------------------------------------NARDRVGI-----
------QDFVLLD-------------------------------------
------------AH--------------------------------TSES
AFLDNLRKRFHENLIYTYI-------------------------------
--------------------------------------------------
--------GTLL---VSVNPYKQLDIYSKKQMDTY-------------MG
VNFFELPP------------------------------------------
--------------------------------------------------
-------------------HIYALADNVFRTMQSEYNN------------
----------HFILISGESGAGKTEASKKI--LQFYAVSCPSTRLLNNI-
------------------------------------------RDRLVLSN
PVL-EA---------------------------------FGNAKTLKNDN
SSRFGKYMDIQFDHQGGAVGGHILSYLLEKSRVVHQNHGERNFHIFYQLV
EGGEEDLLRWLGLERNCKCYSYLVQGDCAKVSSINDK------SDWKTVR
KALSVIEFSEADIE-HLFGIIASVLHL--GNIK------FDD-DVTGYAS
LS-SSSNNNE--MHWVSKLLGIP---------------------------
-------------------------------------------AEVLHQG
LTHRKIEAK-----------------------------------------
----------------------------------T---------------
-------------------------EEVFSPFSVEHAVYARDALAKAIYG
R-TFNWLVN--------------------KINESLANK------------
-----------D-----SSRKTVIGLLDIYGF-EVFNI-------NS--F
--------EQFCINYCNEKLQQLFIQLTLKSEQEEYEMEGIEWEPVPYFN
NKIICELVEAKHRGIISLLDEECLLPGEASDLTFLVKM------------
---EEKMGGHPHFVT-----------------------------------
------------------HKL-----------------------------
----ADQKTRKTLERGEFRLLHYAGEVT-------YSVV-GFLDK-----
--------------------------------------------------
-----------------NNDLLYRSGKEVMQQSKNAVIKLCFPSTEKDSK
KRPETVVTQFK---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------NSLTGLTEILLS-------------------
-------------KEPW---------------------------------
------------------------YVRCIKPNEAKQPGRFDDVLVRHQVK
YLGLME--------------------------------------------
--------------------------------------------------
-----HLRVRRAGFAYRRKYEI----------------------------
--------------------------------------------------
----FLQRY----KPLC---------------------------------
----------------------------PDTWPNWKGTAAEGVKRLIRHL
GYKRDEYKMGRTKI-FIRHPRTLFATEDAF--------------------
--QVCKHNLATRI-------------------------------------
--------QA-------KYKGYRMKGDFQRQREAATRIENCWRGMMARKE
REKRAWAVKVIKRFIKGFIMRNQPMCIDNS--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-EYLAYVRHSYLARLRENLPKTVLEKDSWLTPPPVMQEASQL---LKKLY
----------VRHMVRKYVREVTPQRKAQ-LQLKLQTSSMFKGKKENYPF
SVC----------------------RPFEDT-------------RIE--V
EDI-----------------------------------------------
----------------------------------NIKVLQMIQHEHIKYS
VP---VVKY---DRNGFRP---RLR-QLIFTQEAAYLVGENK--------
------------------IKQRISYSSLKGVSVSNLS------DNFLILH
VTCDDNKQ-KGDLVLQCDYLF-----------------------------
---------------------EALTKLSVIANKQKCIQVVQGSARFDIHP
GREGFVDFKSGQEPTVYRAKNGHLMVLLPRP-------------------
--------------------------------------------------
-------------VNS------L--------
*
>P1;ENSLOCG00000007225

------------------MDFFDDPSLFVGGLDGLSDEGFAGSGPVSLVD
ELNLGAEFEPLQVEPLGGGKHPGMAPPPASASSQAGLPFEQQLGQFDVLK
GPLPLGQPFSLAEGGAAGGGRNALHPQYHSSPVHQPPQPNGLFPDSSPMW
GNQEQSGNVFHQPAPSQSSQLGQQQHQQHHHHHHHHHHHLPQPQYMSSQP
GQPPTLAPRFQSRVFHQHKPGLIHREKLVRHEACRTGATRSRYSSSAGTR
ASNPEPASHEGRDLPVALEGWRTLASPDLPVADRRSAVLFGFCCPSVRER
CIYQQPKSGTLFSCSFAEASYVELSISVKKHPQVHALRLLSYSSAWFFCA
VSFVRRPCWHGRYGLCVLHEETCGCKEVMSQPGALVTAAPYQQGAAAGRC
AAGHQVLLSCSSGLQFPCPGTVSYCPSQDGFPTPSLCPARSSLGPLHSVH
ASFHTQTGCSLSVFLLSGYWIYWNTVAPFRSAQGEVIAFVEADWLCRLSG
AREYSFRQKQEMLCVLVDNLAAFTSRGKKSQNWSLIVISCHKTKPFKNTN
GSSGHTRVLSPQLKSGTSSSSSSSSSSSEKRQKKKPLMEQALEDKQEKAN
RIISEAIAKARERGEKNIPRVMSPESFPCSSTPPRQDHKPHHAKAPPTDP
PSRKAKGPAASRSKQKTKIGKIVIKFGKKKKRKTESSEELSDTEPLPRRC
SKDDD---SKRRSNRQVKRKKYAEEGECKVS-DEEVKVIVKAKKTASGSR
KEQPVQLFVENPSE-EDAAVVDKIMSSRIGKKEVSPGVVVEV--EEFYVK
YK-N---YSYLHCEWATEQQLVKDKRIQQKIKRFKIKQAQRAHFFADMEE
EPFNPDYVEVDRVLEVSYCKDKDTGEPVVYYLVKWCSLPYEDSTWELKED
VDQSKIEEFEQLQAARPDPRRVERPPASMWKKTEQSREYRNGNRLRDYQL
EGVNWLLFNWYNRRNCILADEMGLGKTIQSITFLEEIFLTGIRGPFLIIA
PLSTIANWEREFRTWTDLNVIVYHGSMVSRQMLQQYEMYFRDSQGRVIRG
AYKFHAIVTTFEMILGGCPELNAIEWRCVIIDEAHRLKNKNCKLLEGFKL
MSLEHKVLLTGT-----PLQNTVEELFSLLHFLEPLRFPSESTFMQE--F
--------GDLKTEEQVQKLQAILKPMMLRRLKEDVEK-----KLAPKEE
TIIEVELTNIQKKYYRAILE---------KNFSFLSKGAGQANVPNLVNT
MMELRKCCNHPYLIKGAEEKILEEFREVHNPAALDFHLQAMVQSAGKLVL
IDKLLPKMKAGGHKVLIFSQMVRCLDILEDYLIQRRYLYERIDGRVRGNL
RQAAIDRFSKPDSDRFVFLLCTRAGGLGINLTAADTCII-FDSDWNPQND
LQAQARCHRIGQNKAVKVYRLITRNSYEREMFDRASLKLGLDKAVLQSMS
GRENSVGGVIQQLSKKEIEDLLRRGAYGAIMDEEDEGSKFCEEDIDQILQ
RRTKTITIESEGRGSTFAKASFVASGNRTDISLDDPNFWDKWAKKAEIDL
DTINGRNSLVIDTPRVRKQTRPFSATKDELAELSEPESEGDDKPKLRRPY
DRLNGYGRTECFRVEKNLLVYGWGRWKDILLHGRFKRQLNEHDVEIICRA
LLAYCLVHYRGDDKIKSFMWDLIAPTEDGQTKELQNHLGLSAPVPRGRKG
KKVKTQPSSFDIQKAEWIRKHNPEHLLQDDGYKKHLKHHCNKVLLRVRML
YYLKQEVIGDQSQKVLDGVDSSETEIWVPEPDHSELPAHWWDTEADKSL-
LIGVYKHGYEKYNTIRADPALIFLERVGRPDDKAIAAEQRANDFMDGDGD
DPEYKPAPALLKDDIEDDASSPGDLVIADGGGDLPPEGGMLMEGDALYWP
PPSALTTRLRRLITAYQRNTKNRQIQHIQQALPAQPSALLSTLNDNINPK
IAAKIERQQRWTRREEADFYRVVSTFGVVFDPEQGRFDWTKFRAMARLHK
KTDDSLQKYLCAFTAMCRRVCRLPPREGESVDPSISIQPITEERASRTLY
RIELLRKVREQVLRHPQLYERLQLCQPGPD-LPVWWEPGAHDRDLLIGA-
----AKHGVSRTDYHILRDPELCFMTAQSNYSQNKGAQSRTPTPLLLPQY
QAMVAGSPLAAQPRPPDPRTAQVEEPRQRAEHLKEEPPTSEEEGAERKGK
AEQWSPRSGAQTQGLVDSKAGGQVKGESERRSMVAARTEPLTPNSVAKKQ
KRGSK----------RGRRQGRRASCTDSDTEQDSDSDREDRKASALIPL
TCSEISATVRSGRSVIEENFTHNSILPSIRYDAIFRRIDYLKEIAEAAKI
KGFDEDSVASLSTTQDETQDSFLTDNGLHSSSHAFQGGYMLAASYWPKDR
VMINRLDSICQAVLKGAWPAARRGYEGSAVSSFYTTKLLDSPSDQGGPPG
PREDPAQSPQMSKVKKHVREKEFTVKINDQEGSLKLTFQKQGLPQKRPLE
GEDGPLGQQQYLARLRELQSASDTSLADFTKPLPTAAAVSPGAAGPVRAN
GALDGQPVVKKRRGRRKNVEGM---------------DLLFLNKNRSTPD
HVGPGVGGSAQASPAVVPGLGYGPSQAPVDTESRVPVINLKDGTRLA--G
DDAPKKKDLEQWLKEHPGYVADVGAFIPPLQGLNKMTFQDGRPRQKRHRC
RNPNKIDINSLTGEERVQIINRRNARKVGGAFAPPLKDLCRFLKENPEYG
VP---PEWADVVKRSGFLP---ESMFDRILT--GPIVREEVSRRGRRPKS
EMAKAAAAAANASAATLSINPLLSNGLLSGMDLSSLQALQQNLQSLQSLH
LTAGLMGL-PGGLAAAGDANNLAAMFPMMLSGMAGLPNLLGMGGLLGKPQ
EGAGVSEDGTKKGNGGSGDSSSSASKTPVPTDTKGERTEGQGADQCPSDP
STSGATAPLSASAVAAAAASSNHPLALNPLLLSSMLYPGMLLTPGLNLPI
SALSQSGVFDAQQQSTSARPAATASGETPRGAGGSTPAKGQEPGEQKENS
AEEGSEKAGSSSSESEGSSSSSEDSDSSNED
*
