>P1;ENSGACG00000004472

CL---NGGSSV----------------------------------PSLAS
GDHLFCLCAD-GFQGS-------------R----CETVDGADCY--EGLG
L------FYRGTQSRTESGR--TCEEWDSNTRERF--MAA----------
-------------------DVYSGRH------------------------
------------------NYCRN------LLYKRRPWCF-VWENRRLVWE
YCRVPRCAR------------------QLSAE---------STCGLRSRR
KQLKIVGGTVAAVESHP-----WVAAIFWRGRSKEKVFRCGGSLISACWV
L-------------------TAAHCFPDRSS----TKPRRFSVVL-GK--
NAMNETNAAVEQTFRVEQIILH-------E--------------------
-GYDNS-AENYNNDIALLQLKARRG-RCSIESDSVRPVCLPPPGQKLHP-
--------------------------------------------------
------------------GFTCEVTGYGKENQSLWYNSPVLREAQVNL--
-----------------IAGDVCRQPDYYAS---LISDNMFCAGRTDWSR
DACEGDSGGPLVC-------EVGERLFLFGVISWGDGCAKEKR-------
-------------PGVYTQVTNYNWWVEE-----KT--------------
-----GLSS--------------------------------
*
>P1;ENSTNIG00000016543

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--NKIVNGSFAAVESHP-----WIAAIFSR------RFLCGGSLISPCWV
V-------------------TAAHCFDG--------DINSLSVHL-GK--
KATNETDATKEQIFSVEDLIIH-------P--------------------
-HFDSS---SNNNDIGVY----AYG-ACAVKSASVRVVCLPPLHTRIPA-
--------------------------------------------------
------------------GFQCTVAGYGKERYLG-LYSQYLKKTEVNL--
-----------------ISHKLCQSPSYYGK---RITDNMLCAGSPDWTT
DSCNGDSGGPLVC-------EASGRMFLFGIVSWGEGCAGKNK-------
-------------PGVYTQVTNYNKWIA----------------------
-----------------------------------------
*
>P1;ENSTRUG00000014454

QMKLLVILVIF---------------------------------------
----VAFCSD-VV-SR-------------N--LEDITSSTETCW--PGER
S------SYTGDVSKSLGGR--RCLNWRNVFNP----WGD----------
-------------------SNGIGDH------------------------
------------------NYCRN------PDQSGRPWCY-VRRGRRIVWE
FCVVPMCPKT-T-------VP-P-RPVALDTA---------LSCGERQEQ
RTNKIVNGSFADVESHP-----WIAAIFGQ------RSLCGGSLISPCWV
V-------------------TAAHCFDDGDA----TDIRQLSVHL-GK--
KAINETNAKKEQAFLVEKLIIH-------Q--------------------
-HFDSS---DLNNDIALLKIKRRDG-SCAAKSASARVVCLPPLRTQLPA-
--------------------------------------------------
------------------GFQCTVAGYGHESYQG-SYSQYLKKTEVKL--
-----------------ISHSLCQSPSYYGK---RITDNMLCAGSPDWTT
DSCSGDSGGPLVC-------EAAGRMFLFGVVSWGDECAKKNK-------
-------------PGVYTQVTNYNKWIAD-----ET--------------
-----GLSE--------------------------------
*
>P1;ENSXMAG00000010473

MV-L----------------------------------------------
--------------SR-------------R--CFTKREASAECR--FGKG
T------RYRGTVSVSSNGH--RCLKWSKTQHS----WSD----------
-------------------SNGVGNH------------------------
------------------NYCRN------PNNSRRPWCY-VKTRSQVKRE
YCDIPKFCPNTGSTVTARPTT-T-PPRAVDTE---------RTCGERSER
RTNKIVGGSFVPIETQP-----WIAAIFQN------RFLCGGSLIAPGWV
L-------------------TAAHCFFDGSQ----TRLQRLRVYL-GK--
SDTNNTDPDREQLFSVEKLIIH-------Q--------------------
-KYNPS---TYDNDIALLKISNTKG-QGALKTASVRTVCLPPLNTYLPV-
--------------------------------------------------
------------------GFTCSIAGFGKEAYSSLSYSNQLKQANVRL--
-----------------LSSTNCKVEEHYKA---LLTDNMICAASPDWSI
DACKGDSGGPLVC-------EASGRMFLFGVVSWGEGCASENK-------
-------------PGVYTKVTHYNNWIAD-----NT--------------
-----GLSEYTKGLMYPQK----------------------
*
>P1;ENSGACG00000006694

--------------------------------------------------
-----------------------------------------MCW--SGDG
S------SYRGFASESTSGR--RCLNWNMFTYS-----GA----------
-------------------SNGLGDH------------------------
------------------SYCRN------PDESLMPWCR-VRRGRRIVRE
FCDIPRCTSA-GPTP----TS-R-PPSAVDTE---------RTCGERSVQ
RLHKIVGGSFTPVESHP-----WVAALFHQR----TGFLCGGSLIAPCWV
L-------------------TAAHCFSDGES----TTIRHLSVYL-GK--
SAINATDADKEQRFTVEKVIIH-------Q--------------------
-KYNLD---NYDNDIALLKIKSSNG-GCAVRSSSARTVCLAPSHTQLPA-
--------------------------------------------------
------------------GFQCSIAGFGNERFFG-HYSQIMKQAVVQL--
-----------------LPQTDCASQSYYGH---LITENMLCAGSPDWST
DACKGDSGGPLVC-------EVAGRMFLFGVVSWGEGCAKRNK-------
-------------PGVYTRVTNYNKWIED-----GT--------------
-----GLSKYTKGFMYPQK----------------------
*
>P1;ENSAMXG00000004782

MR-CLVITLLVA--------------------------------------
----CAFAASS-AL--KHKPWKNNDILSVRANKYAADDESTRCIAEGSDG
S------EYRGTVSVTAKGH--GCLRWNRFRSL----GSA----------
----------------V--TCGLGSH------------------------
------------------NYCRN------PDKSIMPWCR-VKRGTRIMRE
FCDIPRCEAKPTESP-T-EPTEP-TEPEQDTE---------RTCGERSLN
SIYRIIGGYRTTVESQP-----WMASIFVNK-----CFKCGGTLIAPCWV
L-------------------TAAHCFPSGRR----NKLEHISVYL-GK--
NAINETDHNKEQKFKVTKLIIH-------E--------------------
-DFDNTISENYNNDIALMQIVDSSG-QCAQRTRTVRTVCLPPSKHMMPY-
--------------------------------------------------
------------------GSFCTTAGYGTVKSNGFEYSKFLKEARLEL--
-----------------ISPKVCHQDNYYGKSEVPLTDNMVCAGSPTWKD
DACQ----------------------------------------------
---------------VYIYIFNMNFLT-----------------------
-----------------------------------------
*
>P1;ENSONIG00000009640

MN-FFVLVVIL---------------------------------------
----AAVSMD-VAFSQ-------------R----SSKQARQRCL--SGDG
S------EYSGKVGKSSTGR--SCLYWNRVKPQ----WNN----------
-------------------VPGLGRH------------------------
------------------RYCRN------PDNSGMPWCF-VTKEMRTVRE
YCDIPRCTTHIGPAS----QT-P-PQLPVDTA---------QTCGETSEK
KMYKIVGGSFTPIESQP-----WVAAIFHKR----YGFLCGGTLISPSWI
L-------------------TAAHCFSDGEN----TRLTHLSIYL-GK--
SAINETNAGSEQRFAVERLIMH-------E--------------------
-GYDDT---TYNNDIALIKLKGRGR-GYAVKSASVRIACLPPFHTELPP-
--------------------------------------------------
------------------GFTCSIAGFGKESAGSFQFSQYLKQAEVKL--
-----------------MSNADCSKEVHYGT---RITDNMFCAASPDWST
DACKGDSGGPLVC-------GASGRMFLFGVVSWGEGCARKNK-------
-------------PGVYTKVTNYNRWIAG-----KT--------------
-----GLIEYAKGLMYPLK----------------------
*
>P1;ENSDARG00000039145

MSGILVWSLILALTALTVCKAQRRPFPSESHDKPGVLCLNGGSSLSSL-S
GRHLLCLCAE-GFSGS-------------R----CETDTSVSCF--DGIG
Q------LYVGPVSKSASGR--ECLEWDSEKALEIGVYLK----------
-------------------SLIVGGH------------------------
------------------KHCRQELYRENIHFSRRPWCF-VKTPSGIMKE
DCDIPRCSKDHGS------DQ-D-SLAVSQSG---------WRCGQA-EG
RSMKVVGGALSMLERHP-----WMAAIYSRKS-RGRFFTCGGSLISPCWI
L-------------------TAAHCFPDGAQ----TLVHKLSVVL-GK--
KAINETDVQSEQEFRVSELFIH-------E--------------------
-HFDNT-DGNFNNDIALLKIRGPDG-RCAKESSSVKTVCIPGPNVSLSD-
--------------------------------------------------
------------------GTSCTVTGYGREHEGSWFYSQYLKEAQVKI--
-----------------LSQDLCSSKEYYGN---MITENMLCAGSPDWSS
DACKGDSGGPLVC-------RVQDRVFLFGVVSWGEGCSRAFR-------
-------------PGVYAKVSNYYHWILE-----KS--------------
-----GLTSL--------S----------------------
*
>P1;ENSORLG00000009387

LL------------------------------------------------
--------------------------------------------------
-----------------LIR--FCISLN----------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------AIK---------FTCGERHEG
RKNKVVGGSFTTVESQP-----WISAIFKKK-----RFLCGGSLISPCWV
L-------------------TATHCFSDEID----AKAEDLTVFL-GK--
SAINDTDSEREQKFTVEKMIIH-------P--------------------
-KYN-----NFNNDIALLKIRGAEG-GCAVKTPSVRTVCLPPLHTQLPP-
--------------------------------------------------
------------------GFKCSIAGFGKESSESWQYSQILKQADVNL--
-----------------MSSTECKREPNYQR---MLTENMLCAAGPDWST
DSCQGDSGGPLVC-------EASGRMFLFGVVSWGDGCASKDM-------
-------------PGVYTKLTNYNKWIAE-----ET--------------
-----ALS---------------------------------
*
>P1;ENSDARG00000075265

MK-CILGGFLLT--------------------------------------
----CVLCWTEAIIGEMDERWKS-----------SSTSVNGKCI-LDRDE
S------KYTGKVSVTVSGR--ICAPWNSIQGS----RYS----------
----------------A---FKNCYH------------------------
------------------NYCRN------PDDWTQPWCV-VKKRNRYVRE
YCNIPQEAIKPVKRP----PT-P-EPIKQDTE---------LTCGERRLD
RQTKIIGGLRSTVESQP-----WMAAIFKGD-----GFICGGTLITPCWV
L-------------------TAAHCFPTGKR----TQINRYSVVL-GK--
NAINETDPVKEQKFTVSRLVIH-------E--------------------
-DFDYS-TENYTHDIALLKIEDCNG-QCAVKTKTVRTACLPPFQQMLPV-
--------------------------------------------------
------------------GFYCEIAGYGRYQKGTFKFSRYLKQTEVKL--
-----------------ISQKVCQRTYYNKD---EVNENMLCANGRDWKT
DACQGDSGGPLVC-------EVNNIMFLFGIISWGKECAEKNQ-------
-------------PGVYTQVSNYNQWISQ-----HT--------------
-----GLPRYTAGSRYPQK---------------------D
*
>P1;ENSLOCG00000016445

LT-QNQ-ESSL----------------------------------RMIT-
----------AA--------------------EYGNTSWELTVQI-DHDE
TKMDYKLRVKGDLH--IGGLMLKLVEKIQIPRD----WSDYALWWEQKNC
WLLKTHWTLDKYGVQADAKLLYTPQHKPLRLQLPNMKTVKLTVSYSAVVF
KTVTEICRALNIRRPEELSLLKS------PDDAMKKKKKKDKQKDTIIEE
ILDMDGLNISAGNTASPGLYS-KTMIPTYDPENGTPASATSLWFG-----
-------DN-PLTVSQPNLQHDELIKMYQP------LQLVDKAIMNSGWL
DSSRSLMEQDIHEGDKLLLRFKYHCFFDLNPKYDAVRINQI--YEQARWA
ILLEEIDCTEEEMLIFAALQYHISKLTMSSEPLNSSKEPDEDEVEAALTS
LEVTLE---GGNSDRILEDITDIPKLADTLKLFRPKRLTLKPYKEYWFVF
KDTTISYYKNKESATAEPIEQFHLRGCEVVPDVNVSDKKFGIKLLLPVAD
GINEVYIRCENETQYAKWKAACILASKGKTMAYS-SYRSEVRNIQSFLQM
KNLATPSGQTSLDPETMEMNSECFVSPRYGK---KYKSKQLSARILEAHQ
NVAQL-----SLMEAKMRFIQAWQSLPEFGIKYYIVRFRGSKKDEILGIS
YNRLIRIDMSTGLPITTWRFSNMKQWNVNWEIRQVTIDFDQNVSIAFSCQ
SCDCKVVHEYIGGYIFLSTRSKDQNETLDEELFHKLTGGQE
*
