>P1;ENSXMAG00000011449

EYS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
---CF-----------------------LFQIYPEPKNDGECL-------
----SNIKEFLKGCTSFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEASDLL------
-----------------------------------------LGLNFSKVL
SSLVALNKVTA--DIGVG-SDSVCARHSS-A---HRIKSFESLSS-----
-----QASLGRSSKLLQN--QFRSLVGLALLQDMSENSG-QQLLVKARFN
FQQTNEDELTFTKGDII---SVTRQEEGGWWEGILNGKTGWFP--SNYVR
EIK----------------------------GSA----------------
------------------------DKQV-SPKSVTL-----KSPPKGF--
-----DTSV-----------------------------ISKTYYNLVL--
---QNILETETEYSKD--LQSLLTNY------LR----------------
--------------------------------PLQNIDKLSSADVALILG
NLEEISTFQQMLVQSLEESTKLPESQQ-RVGSFFLNLMPQMKAL------
-------YVGYCSNHPSAVNVLTQHGLSETLRDFMEGHGAV---------
----------------APGILTLTTGLSKPFMR-------LDKYPT-LLK
ELERHMEEN-HADRPDILKCMGSFRNLSAHCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TETIRLW-EGDD
IKTLGSVIYMSQVLVQSPMSEVC---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------TS------------------------------SLHT
DKSH----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------VTSTVYSV-------
--------------------------------------------------
------------------------------------------MQK-----
--------------------------------------------------
-------------TLENRDAKSNKCHYESISLYKFMM---------
*
>P1;ENSONIG00000014144

MNSAEQTVTWLITLGVLES---------------PKKTISDP--------
--------------------------------------------------
---------EAFLQTSLK------------------------------DG
VVLCRLLERLSPGS--------------TEKVYQEPKNDGECL-------
----SNIKEFLKGCTAFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEASDLL------
-----------------------------------------LGLNFSKVL
SSLVTLNKVTA--DIGVG-SDSVCARHSS-A---HRIKSFESLSS-----
-----QASLGRSSKLLQN--QFRSL-------DMSENSG-QQLLVKARFN
FQQTNEDELTFAKGDFI---SVTRQEEGGWWEGTLNGKTGWFP--SNYVR
EVK----------------------------GS-----------------
------------------------DKQV-SPKSGTL-----KSPPKGF--
-----DTSA-----------------------------ISKTYYNLVL--
---QNILETETEYSKD--LQSLLMNY------LR----------------
--------------------------------PLQNIEKLSSSDVALILG
NLEEISTFQQMLVQSLEECTKLPESQQ-RVGSFFLKHMPQMKAL------
-------YVGYCSNHPSAVNVLTQY--GEVLGEFMEGRGAV---------
----------------SPGILTLTTGLSKPFMR-------LDKYPT-LLK
ELERHMEEN-HPDRPDIQKCMTSFKSLSAQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TESIRLW-EGDD
IKTLGSVIYMSQVLVQSQLSEEKNERYLML--------------------
--------------FPHILLMLSASPRMSGFIFQGKL-------------
--------------------------------------------------
-------------PLAGMAVTQLEDCEAHKNAF--ELN-GTMF-------
-------DRLLVICTNQQDLQDWVEHLTRQIKHTAATAPSHKPLTVPCHT
LPSHPL-------------------TPSRHAENRALTVAPTYHTLPHPS-
-----SHGTPH-N-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---NT--------PKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKSVKKLLPKRKPERKQS------------------
EEEFALRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADVD
QSCVDSPGRRSSVSRPELTSDLSEDSDYDSIWTTHSYRMG----------
------SVPRAQRE-T-------GL----------HVIIPGEEKVLLE--
--DPSRNGQST---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------LEEK---------------------------------
----------------------------------SLVDVVYALR------
----------------DE--------------------------------
--------------------------------VQELKQDNKKMKR-----
--------------------------------------------------
-------------SLEEEQRARKDLEKVVRNVLKSINDPAWDETNL
*
>P1;ENSTRUG00000014456

--------------------------------------------------
--------------------------------------------------
-----------F--------------------------------------
-----------------------------LQIYQEPKNDGECL-------
----YNIKEFLKGCTSFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEASDLL------
-----------------------------------------LGLNFSKVL
SSLVALNKVTA--DISVG-SDSVSARHSS-S---HRIKSFESLSC-----
-----QTSLGRSSKLLQN--QFRSL-------DMSENSG-QQLLVKARFN
FQQTNEDELTFTKGDII---SVSRQEEGGWWEGTLNGRTGWFP--SNYVR
EVK----------------------------GS-----------------
------------------------DKQV-SPKSGTL-----KSPPKGF--
-----DTSA-----------------------------ISKTYYNLVL--
---QNILETETEYSKD--LQSLLTNY------LR----------------
--------------------------------PLQNTDKLSSSDVALILG
NLEEICTFQQMLVQSLEECTKLPESQQ-RVGGFFINQMPQMKAL------
-------YNSYCSNHPSAVNVLTQQ--SEVLGEFMEGRGAV---------
----------------SPGILTLTTGLSKPFMR-------LDKYPT-LLK
ELERHMEEG-HPDRPDIQKCMAAFKSLSVQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TESIRLW-EGDD
IKTLGSVLFMSQVLVQSPGSEEKSERYLML--------------------
--------------FPHVLLMLSASPRMSGFIFQGKL-------------
--------------------------------------------------
-------------PLAGMTVSKLEDCDAHKNAF--ELN-GTMF-------
-------DRLQVICTHKQDLQDWVELLSRQIKHTAATAPSHKPLTVPCHT
LPSHPV-------------------TLSRHAEGKAMTVAPTYHTLPHPS-
-----SHGTSLSS-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---NT--------PKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKSVKKLLPKRKPERKQS------------------
EEEFALRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADVD
RSCMDLPGRRSSVSRPELSSDLSEDSDYDSIWTSHSYRMG----------
------SVPRPRTE-M-------GL----------HVIIPGEKKVQGE--
--GPSRNGQSA---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------DEEK---------------------------------
----------------------------------SLVDVVYALR------
----------------DE--------------------------------
--------------------------------VQELKQENKKMKR-----
--------------------------------------------------
-------------SLEEEQRARKDLEKVVRRVLKSINDPTWDETNL
*
>P1;ENSDARG00000073848

MNSAEQTITWLITLGVLES---------------PKKTLSDP--------
--------------------------------------------------
---------EGFLQASLR------------------------------DG
VVLCKLLERLRPGS--------------VHTIYQDPRKD-ECL-------
----SNIREFVKGCALYH--IEV---------------------------
--------------------------------------------------
-------------------------------------FEANDLL------
-----------------------------------------QGQNFSKVL
NCLVALNKATS--ESGGG-SNSVCSRQSS-S---LRIKSFDSLNC-----
-----SSTHRRSSRHKFN--QYRSL-------DMSENSA-PQVLVKARFN
FQQTNEDELSFSKGDII---QVTRQEEGGWWEGALNGKTGWFP--SNYVK
EIK----------------------------GS-----------------
------------------------DKPV-SPKTGTL-----KSPPKAI--
-----ESAN-----------------------------FCKTYYNVVV--
---QNILQTETEYCKE--LQNLLSVY------LR----------------
--------------------------------ALQPTDRLSVSDISHIMG
NLEEISSFQQTLVHSLEENVKVSDSQQ-RIGGFFLSLLTQMRSL------
-------YVTYCSNHPSAVNVLTQH--SEELGEFMESKGAN---------
----------------TPGILTLTTGLSKPFLR-------LEKYPT-LLK
EMERHMEPL-HPDYPDIQKSMTLFKNLSAQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------MESIRGW-EGEG
IKTLGTVLFMSQVIIQNHGAEEKNERYLLL--------------------
--------------FPHILLMLSASPRMSGFIYQGKL-------------
--------------------------------------------------
-------------PLTGMSVSKTEDSDGTKHAF--EIS-GNMI-------
-------ERIQVICNNQQDLQDWVDHLHRQTKRIS--TSSLKPQSVPCHT
LPSHPL-------------------TPSRHSESRGVSGSPVYHTLPHLS-
-----SLGTPH-S-GMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---KT--------QKPWSLSCLRPAPPLKPS-------------------
AALCYKEDLSKS--PKNMKKLLPKRKPERKPS------------------
DEEFAVRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADVH
QSCVDAVGCRSSG---FPSSDQSEDSDYDSIWITHTNRIG----------
------SVSRSRKE-S-------GP----------HMLFPEEEKIIVE--
--ETKSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------IEER---------------------------------
----------------------------------SLVDTVYALR------
----------------DE--------------------------------
--------------------------------VQELKQDNKRMKR-----
--------------------------------------------------
-------------TLEEEQKARKELEKVVRRVLKSMNDPSWDETNL
*
>P1;ENSAMXG00000005405

MNPAEQTVTWLITLGVLES---------------PKKTVSDP--------
--------------------------------------------------
---------EGFLQSALK------------------------------DG
VVLCRLLERLRPGS--------------TEKVFHDPKNDSECL-------
----NNIKEFLKGCAAFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEPSDLV------
-----------------------------------------QGQNFSKVL
TTLVALNKVTAGKDIGIG-SDSVCTRHSS-A---HRIKSFESLVS-----
-----QTSLGRSSKLLHN--QFRSL-------DMTENSN-AQLVVKARFN
FQQTNEDELSFNKGDII---NVTRTEEGGWWEGSINGKTGWFP--SNYVR
EVK----------------------------GS-----------------
------------------------DKQV-SPKSGTL-----KSPPKGF--
-----DTTA-----------------------------LSKTYYNLVL--
---QNILETETEYSKD--LQSLLSNY------LR----------------
--------------------------------PLQNTEKLSSADASVILG
NLEEISTFQQTLVQSLEDCTKLPELQQ-KVGGFFLNLMPKMRAL------
-------YLGYCSNHPSAVNILTDH--SEELGEFMEGRGAS---------
----------------SPGILILTTGLSKPFMR-------LDKYPT-LLK
ELERHMEEG-HPDRMEIQKCMTAFKNLSGQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TESVRLW-EGED
IKTLGSVLFMSQAMVQNHGCEERNERYLML--------------------
--------------FPHVLLILSASPRMSGFIYQGKL-------------
--------------------------------------------------
-------------PLSCMTVTPLEDCESYKNAF--ELS-GSMF-------
-------ERLKVVCFNKQDQQDWLEHLNRQTKHTTMTAPSMKPLTVPCHT
LPSHPL-------------------TPSRHAESRGLTVAPAYHTLPHPS-
-----SHGAPH-S-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---KT--------QKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKSMKKLLPKRKPERKPS------------------
DEEFALRKKTGTVALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLD---
QSSVDSLGRRSSISRPEATSDLSEDSDYDSIWTAHSYRMG----------
------SVSRQRRD-T-------AP----------ALIVPTEEKMTVE--
--GLKSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------IGEK---------------------------------
----------------------------------SLVDVVYALR------
----------------EE--------------------------------
--------------------------------VQELKQDNKKMKH-----
--------------------------------------------------
-------------SLEEEQRARKDLERIVRKVLKNLNDPTWDETNL
*
>P1;ENSAMXG00000018379

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------MSDNSS-AQLLVKARFN
FQQNNEDELCFNKGDII---QVTRQEDGGWWEGTFNGRTGWFP--SNYVK
EVK----------------------------GS-----------------
------------------------DKPI-SPKSGTQ-----KSPPKGF--
-----ETNA-----------------------------VTKTYYNLVV--
---QNILQTETEYCKE--LQTLLSTY------LR----------------
--------------------------------LLQPTDRLTVADIAHILG
NLEEISSFQQTLVQSLEECTKLPENQQ-RVGGFFLSLMTQMKSL------
-------YVAYCSNHPHAVSVLTQH--SEELGEFMESKGAS---------
----------------VPGILTLTTNLSKPFMR-------LDKYPT-LLQ
ELDRHMEDC-HPDRPDIQKSLPTFKNLSAQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TDPVRNW-EGEG
IKTLGSVIYMSQVLLQNHGSEEKNERYLLL--------------------
--------------FPHVLLVLSASPRMSCFIYQGKL-------------
--------------------------------------------------
-------------PLTGMMVTKCED---ARNTF--EIS-GTMI-------
-------DRIQVICNNQQDLLEWVEHLTRQTKRTSSCTSSLKPQSVPCHT
LPSHPV-------------------TPSRHSESRGTSGTPAYHTLPHPS-
-----SHGTPH-S-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---KT--------QKPWSLSCLRPAPPLKPS-------------------
AALSYKEDLSKS--PKSMKKLLHKRKPERKPS------------------
EEEFAVRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADVD
QSCVEAVGCRTSMLRLEPSSDQSEDSDYDSIWTAHSYRMG----------
------SISRSRKE-S-------GP----------HMLFPEEEKIIVE--
--ETKSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------IEER---------------------------------
----------------------------------SLVDTVYALR------
----------------DE--------------------------------
--------------------------------VQELKQDNKRMKR-----
--------------------------------------------------
-------------TLEEEQKARKELEKIVRRVLKSMNDPSWDETNL
*
>P1;ENSORLG00000012157

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------PLQIYPEPKNDGECL-------
----SNIKEFLKGCTSFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEASDLL------
-----------------------------------------LGLNFSKVL
NSLVALNKVTA--DIGVG-SDSVCARHSS-A---HRIKSFESLSS-----
-----QASLGRSSKLLQS--QFRSL-------DMSENSG-QQLLVKARFN
FQQTNEDELTFNKGDII---NVTRQEEGGWWEGTLSGRTGWFP--SNYVR
EVK----------------------------GS-----------------
------------------------DKQV-SPKSGTL-----KSPPKGF--
-----EPPA-----------------------------ISKTYYNLVL--
---QNILETETAYSKD--IQSLLTNY------LR----------------
--------------------------------PLQNSDKLSSSDVALILG
NMEEISTFQQMLVQSLEECTKLPESHQ-RVGSFFLNLMPQMKAL------
-------YIGYCSNHPSAVNVLTQH--SEALGEFMEGRGAV---------
----------------SPGILTLTTGLSKPFMR-------LDKYPT-LLK
ELERHMEEI-HLDRPDIQKCMVSFKNLSAQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TESIRLW-EGDD
IKTLGSVIYMSQVLVQSPMTEEKSERYLLL--------------------
--------------FPHVLLMLSASPRMSGFIFQGKL-------------
--------------------------------------------------
-------------PLTGMMVTKLEDCEAHKNTF--ELN-GTLF-------
-------DRLQVICTNQQDLQDWVEHLTRQIKHATATAPSHKPLTVPCHT
LPSHPV-------------------TPSRHAEGRAMTVAPTYHTLPHPS-
-----SHGTSH-S-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---NT--------PKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKSVKKLLPKRKPERKQS------------------
EEEFALRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADVD
RSCAESPGRRSSMSRPELSSDLSEDSDYDSIWTSHSYRMG----------
------SVPRKRRE-T-------GL----------HVIIPGEDKVFVE--
--DPSRNGPNA---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------LEEK---------------------------------
----------------------------------SLVDVVYALR------
----------------DE--------------------------------
--------------------------------VQELKQDNKKMKR-----
--------------------------------------------------
-------------TLEEEQRARKDLEKVVRRVLKSINDPTWDETNL
*
>P1;ENSTNIG00000013868

MNSAEQTVTWLITLGVLES---------------PKKTISDP--------
--------------------------------------------------
---------EAFLQSSLK------------------------------DG
VVLCRLLERLSPGS--------------TEKVYQEPKNDGECL-------
----HNIKEFLRAAHHFASTWQP---------------------------
--------------------------------------------------
-------------------------------------FEAGDLL------
-----------------------------------------LGLNFSKVL
SSLVALNKVTA--DISVG-SDTVSARHSS-S---HRIKSFESLSC-----
-----QSSLGRSSKLLQN--QFRSL-------DMSENSG-QQLLVKARFN
FQQTNEDELTFTKGDLI---SVSRQEEGGWWEGTLNGRTGWFP--SNYVR
EVR----------------------------GS-----------------
------------------------DKQV-SPKSGAL-----KSPPKGF--
-----DTSA-----------------------------ISKTYYNLVL--
---QNILETETEYSKD--LQSLLTIY------LR----------------
--------------------------------PLQNTDKLSALDVALILG
NLEEICTFQQMLVQSLEECTKLPETQQ-RVGGFFLNLMPQMRAL------
-------YSSYCSNHPSAVNVLTQQ--SEVLGDFMEGRGAV---------
----------------SPGILTLTTGLSKPFMR-------LDKYPT-LLK
ELERHMEEA-HPDRPEIQKCMAAFKNLSVQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------TESIRLW-EGDD
IKTLGSVLYMSQVLVQSPGSEEKSERYLML--------------------
--------------FPHVLLLLSASPRMSGFIFQGKL-------------
--------------------------------------------------
-------------PLAGMSVSKLEDCEAHKNAF--ELN-GTMF-------
-------DRLQVICTHKQDLQDWVEHLSRQIKHTAATAPSHKPLTVPCHT
LPSHPV-------------------TPSRHAEGKAMTVAPTYHTLPHPS-
-----SHGTSLSS-TLMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---NT--------PKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKSVKKLLPKRKPERKQS------------------
EEEFALRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSR----------------
--------------------------------------------------
----------PRTE-T-------GL----------HVIIPGEKKVQVE--
--GPSRNGQSG---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------DDEK---------------------------------
----------------------------------SLVDVVYALR------
----------------DE--------------------------------
--------------------------------VQELKQENKKMKR-----
--------------------------------------------------
-------------SLEEEQRARKDLEKVVRKVLKSMNDPTWDETNL
*
>P1;ENSDARG00000006299

MNPAEQTVTWLITLGVLES---------------PKKTISDP--------
--------------------------------------------------
---------DGFLQASLK------------------------------DG
VVLCRLLERLRPGT--------------TDKIIQDPKNDSECL-------
----SNITEFLKGCAVFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEAGDLL------
-----------------------------------------QGHNISRVL
TTLVALNKVTA--DIGIG-SDSVCTRHSS-A---HRIKSFESLAS-----
-----QSSLGRSSKLLHN--QFRSL-------DMTDNSN-AQLVVKARFN
FQQTNEDELTFSKGDLI---SVTRTEEGGWWEGILNGKTGWFP--SNYVK
EVK----------------------------GS-----------------
------------------------DKQV-SPKSGNL-----KSPPKGF--
-----DTAS-----------------------------ISKTYYNLVL--
---QNILETETEYSRE--LQNLLTSY------LR----------------
--------------------------------PLQMTERLSPADVSVILG
NLEEISTFQQTLVQSLEDLTKLPELQQ-KVGGFFLNLMPQMRSL------
-------NVSYCSNHPSTVNVLTVH--SEELGEFMEARGAS---------
----------------VPGILTLTSGLSKPFMR-------LDRYPT-LLK
ELERHMEEG-HPDRTEIQKCMTAFKNLSAQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------AETIRLW-EGED
IKTLGSVLYMSQAMVQNHGCEEKNERYLLL--------------------
--------------FPHVLLILSASPRMSGFIYQGKL-------------
--------------------------------------------------
-------------PLSGMTVTPLEDCESHKDAF--ELS-GSMF-------
-------ERLQVICYNKQDLHDWLEHLNRQTKHTTMAAPSMKPLTVPCHT
LPSHPL-------------------TPSRHGESRGLTVAPAYHTLPHPS-
-----SHGTPH-S-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---KT--------QKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKTMKKLLPKRKPERKPS------------------
DEEFALRKST--VALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLD---
QSSADSLGRRSSISRPEATSDLSEDSDYDSIWTAHSYRMG----------
------SVTRQWKD-G-------SP----------ALIVPGDEKFSVD--
--ELKSNGQTL---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------LEEK---------------------------------
----------------------------------SLVDVVYALR------
----------------DE--------------------------------
--------------------------------VQELKQDYKKMKK-----
--------------------------------------------------
-------------SLEEEQRARKDLERIVKKMLKNMNDPSWDETNL
*
>P1;ENSTNIG00000014507

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------DNVCLPPSS-T---LRIKSFDSLNT-----
-----QN--TCSSKLLQP--QYRSL-------DMSEGNSCGNLLVKARFA
FQQTN-DELSFSKGDII---IVTRQEDGGWWEGSLNGKSGWFP--SNYVR
EMK----------------------------VD-----------------
------------------------KAS-DKARSSTM-----KSPPKTF--
-----DTTI-----------------------------ITKTYYNVVL--
---QNILDAETEFSRE--LQSVLGSY------LR----------------
--------------------------------SLHPTDRISSADISHILG
NLEEISTFQQMLVQSLEEHTKLPENQQ-RIGGFFLSLMPQMKSM------
-------YVAYCSNHPSAVSVLTQH--SQELGEYMESKGAS---------
----------------SPGILILTTSLSKPFTR-------LERYPA-LLK
ELDRHMQDQ-HPDRADLHTCMTAFKNLETMCQEMRKKKDLELQIL-----
--------------------------------------------------
--------------------------------------TEPIRNW-EGDD
IKTLGPILH--QTTVHTPICQKLSECYLVL--------------------
--------------FPHTLLMLSASPRMSGFIYQGRM-------------
--------------------------------------------------
-------------SLSGMLISRIEDGETLRNAF--EIS-GSHN-------
-------ERMQVACNTPQDLQDWLDLLTKHTHTPAPHTPSYKHQSV-CHT
LPSHPG-------------------TPSRLSESHSGSAGQLYHTLPHPS-
-----SFGTAH-SNSLTWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---ST--------PKPWSLSCLRPAPPLRPS-------------------
AA--QKEDMSKS--PKNMKKLLPKRKPERKPS------------------
EEDFTVRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADNS
LTVAGFPGN-------APCSDQSEDSDYDSIWTATSYRTA----------
------SFSRSSRK---------DV----------QMLFPEEEKIIIE--
--ETKSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------VEER---------------------------------
----------------------------------SLVDTIYSLK------
----------------DE--------------------------------
--------------------------------VQELKQDNKRMRR-----
--------------------------------------------------
-------------TLEEEQRARKELERIIRRVLKNMNDPSWDETNL
*
>P1;ENSORLG00000005832

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------KLQFFPEPRSDSDFQ-------
----KNIAEFLKGLAAFG--VEP---------------------------
--------------------------------------------------
-------------------------------------FEVSDLL------
-----------------------------------------QGFNFSKVL
NSLVALNKATE--GLGVSGDDGGGAPHSSAS---SRIKSFDSLNT-----
-----Q---GRSSKLLLP--QYRSL-------DMSEGSGCGQPLVKARFP
FQQTNEDELSFSKGDII---VVRRQEEGGWWEGSLNGKTGWFP--SNYVR
ELK----------------------------GS-----------------
------------------------DKTADKPKSGTL-----KSPPKGF--
-----DTSI-----------------------------ISKTYYNVVL--
---QNILEAETEYSRE--LQSLLGSY------LR----------------
--------------------------------SLQPTDRLSSGDISHIQA
NLEEISTFQQMLVQSLDDQTKLPENQQ-RIGGFFLSLMPQMKTI------
-------YVSYCSNHPSAVGVLTRH--SEELGGFMESKGAS---------
----------------SPGILALTTSLSKPFTR-------LDRYPA-LLK
ELERHMEDQ-HPDRADLHAVMAAFKHLAAECQEVRKRKDLELQIL-----
--------------------------------------------------
--------------------------------------TEPIRNW-EGED
IKSLGAVLHMSQVTVHSQNCQEVNERYLVL--------------------
--------------FPHTLLVLSASLRMSGFIYQGRM-------------
--------------------------------------------------
-------------PLSGMLISRIEDGENWRNAF--EISAGGQC-------
-------ERMQVACNSQRDLQDWLDLLTKHTHT---PAHTHRP--P-CHT
LPSHTV-------------------TSSRHSEARAGS--SAYHTLPHLS-
-----SCETSH-S-APSWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---ST--------PKPWSLSCLRPAPPLRPS-------------------
AALCFKEDMSKS--PKNMKKLLPKRKPERKPS------------------
EEDVTVRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADGG
LAPASLPGN-------QPCSDQSEDSDYDSIWTAHSHRTA----------
------SFSRCSRK---------DV----------QMLFPEEEKIIVE--
--ETRSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------VEER---------------------------------
----------------------------------SLVDTVYSLK------
----------------DE--------------------------------
--------------------------------VQELKQDNKRMKR-----
--------------------------------------------------
-------------TLEEEQRARKELERIVRRVLKNMNDPTWDETNL
*
>P1;ENSTRUG00000017333

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------IFQFLPEPRSDNECQ-------
----RNITEFINGCGAFG--VET---------------------------
--------------------------------------------------
-------------------------------------FEVSDLL------
-----------------------------------------QGLNFSKVL
NALVALNKATE--GLGVP-EDNVCVPPSS-T---LRIKSFDSLNT-----
-----QT--TRSSKLLQP--QYRSL-------DMSEGNGCGNLLVKARFA
FQQTNEDELSFSKGDII---IVSRQEDGGWWEGSYNGKSGWFP--SNYVR
ELK----------------------------GS-----------------
------------------------DKTSDKPKSLTM-----KSPPKVF--
-----DTTV-----------------------------ITKTYYNVVL--
---QNILEAETEFSRE--LQSVLGSY------LR----------------
--------------------------------SLHPTDRISSADIGHILG
NLEEISTFQQMLVQSLEEHTKLPDSQQ-RIGGFFLSLMPQMKSI------
-------YVAYCSNHPSAVNVLMQH--SEELGEYMESKGAS---------
----------------SPGILTLTTSLSKPFTR-------LERYPA-LLK
ELDRHMQDQ-HPDRADLQMCMAAFKSLTAQCQEMRKKKDLELQIL-----
--------------------------------------------------
--------------------------------------TEPIRNW-EGDD
IQSLGPILHMSQTTVHTPTCQELSECYLVL--------------------
--------------FPHTLLMLSASPRMSGFIYQGRM-------------
--------------------------------------------------
-------------PLSGMLISRIEDGENLRNAF--EIS-GSHN-------
-------ERMQVACITQQDLQDWLDLLTKHTHTPTPHTPSYKHQSV-CHT
LPSHPG-------------------TPSRLSESHGGSTVQTYHTLPHPT-
-----SFGTLH-SNSLTWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---ST--------QKPWSLSCLRPAPPLRPS-------------------
AAHCQKEDLSKS--PKNMKKLLPKRKPERKPS------------------
EEDFTVRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSTWQGTDLMHNHVLADNS
LSVAGFPGN-------LPCSDQSEDSDYDSIWTATSYRTA----------
------SISRSSRK---------DV----------QMLFPEEEKIIIE--
--ETKSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------VEER---------------------------------
----------------------------------SLVDTIYSLK------
----------------DE--------------------------------
--------------------------------VQELKQDNKRMRR-----
--------------------------------------------------
-------------TLEEEQRARKELERIIRRVLKNMNDPSWDETNL
*
>P1;ENSGACG00000002891

MNSAEQTVTWLITLGVLES---------------PKKTISDP--------
--------------------------------------------------
---------EAFLQTSLR------------------------------DG
VVLCRLLERLSPGS--------------TEKIYQEPKNDGESL-------
----SNIKEFLKGCASFR--VEP---------------------------
--------------------------------------------------
-------------------------------------FEASDLL------
-----------------------------------------LGLNFSKVL
SSLVSLSKVTA--DIGVG-SDSVCARHSS-A---HRIKSFESLSS-----
-----QASLGRSSKLLQN--QFRSL-------DMSENSG-QQLLVRARFN
FLQNNEDELTFDKGDLI---GVIRQEEGGWWEGIINGRTGWFP--SNYVR
EVK----------------------------GS-----------------
------------------------DKQV-SPKSGTL-----KSPPKGF--
-----DTSA-----------------------------ISKTYYNLVL--
---QNILETETEYSRD--LQSLLTNY------LR----------------
--------------------------------PLQSIDKLSSSDVALILG
NLEEICTFQQMLVQSLEECTKLPETQQ-RVAGFFLNLMPQMKAL------
-------YVGYCSNHPSAVSLLTQH--SEVLGEFMEGRGAV---------
----------------PPGILTLTTGLSKPFMR-------LDKYPN-LLK
ELERHMEES-HPDRPDILKCMASFKNLSAQCQEVRKRKELELQIL-----
--------------------------------------------------
--------------------------------------SESIRLW-EGDD
IKTLGSVLYMSQVLVQSPGSEEKSERYLML--------------------
--------------FPHVLLMLSASPRMSGFIFQGKL-------------
--------------------------------------------------
-------------PLASMSVTKLEDCEAHKNAF--ELN-GTLF-------
-------DRLQVVCTNQPDLQDWVEHLTRQIRHTASIGPSHKPLTVPCHT
LPTHPL-------------------TPSRHSEGRGMTVAPTYHTLPHPS-
-----SHGTPH-S-TMMWGP------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---NT--------PKPWSLSCLRPAPPLRPS-------------------
AALCYKEDLSKS--PKSVKKLLPKRKPERKQS------------------
EEEFALRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSRLQG-------------
--------------------------------------------------
-------------E-S-------EL----------LVIVPGERKILVE--
--DPRRNGQST---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------IEEK---------------------------------
----------------------------------SLVDVVYALR------
----------------EE--------------------------------
--------------------------------VQELKQDNKKMKR-----
--------------------------------------------------
-------------SLEEEQRARKDLEKVVKRVLKSMNDPTWDETNL
*
>P1;ENSGACG00000014843

MNSAEQTVTWLITLGVLES---------------PKKSISDP--------
--------------------------------------------------
---------EAFLQTSLQ------------------------------DG
AVLCRLLERLRPGT--------------VDKFFQEPRGESECQ-------
----RNVTEFVKGCAAFG--VEP---------------------------
--------------------------------------------------
-------------------------------------FEVNDLL------
-----------------------------------------QGLNFSKVL
NSLVALNKATE--DFGVS-EDSVFVPPAS-H---LRIKSFDSLNT-----
-----Q---SRSSKVLQP--QYRSL-------DMSEGSACGHVLFRARFT
FQQTNEDELSFSKGDII---SVSRQEEGGWWEGSFNGRSGWFP--SNYVR
ELK----------------------------GS-----------------
------------------------DKTLDKPKSGAL-----KSPPKGF--
-----DTTI-----------------------------ISKTYYNVVL--
---QNILEAEREYSRE--LQSLLGSY------LR----------------
--------------------------------SLHPTERVSSVDISHIQG
NLEEISTFQQMLVQSLEEHTKLSEKQQ-RIGGFFLNLMPQMKLL------
-------YVAYCSNHPSAVNVLIQH--SEELGQYMEAKGSP---------
----------------TPGILTLTTSLSKPFTR-------LERYPT-LLK
ELDRHMEDQ-HPDRADLVAAMMDFKNFAAQCQEVRKKKDLELQIL-----
--------------------------------------------------
--------------------------------------TEPIRNW-EGDD
IRTLGPVIHMSHSTVHTQDCQESNERYLVL--------------------
--------------FPHTLLVLSASLRMSGFIYQGRL-------------
--------------------------------------------------
-------------PLSGMLISRIEDGENLRNAF--EIS-GSQC-------
-------DRMQVACNTQHDLQEWLDLLTQHTHTPATHAHLQKPQSV-CHT
LPPQPA-------------------APSRHSESRGGSIGHAYHTLPHPP-
-----SFGAAL-GCSPSWGA------------------------------
--------------------------------------------------
--------------------------------------------------
-------LEPP---------------------------------------
--------------------------------------------------
--------------------------------------------------
---NT--------PKPWSLSCLRPAPPLRPS-------------------
AALCMKEDLNKS--PKNMKKLLPKRKPDRKPS------------------
EEDFTVRKST--AALEEDAQILKVIEAYCTSAK-----------------
----------------------------------T---------------
---------------------------RQTLNSSS---------------
--------------------------------------------------
-----------SRK---------EV----------HMLFPEEEKIIVE--
--ETRSNGQTV---------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------VEER---------------------------------
----------------------------------SLVDTVYSLK------
----------------DE--------------------------------
--------------------------------IQGLKQDNKRMRR-----
--------------------------------------------------
-------------TLEEEQRARKELEKIVRRVLKDMNDPTWDETNL
*
>P1;ENSLOCG00000000567

MEPVEPTAGQKPTKEPREKNPLQRKWVSEPTAGTKRSTFADPDGKRHSQR
DVLHSSGGSITVSAQQYGPGNLQLSSTVGQPSQENQYPQVFPSTYSYQLP
HSFPQQSIPERFLQSGKPQPGLEAHAWQFVNPLQSVTSEDLFSVHSRGHG
GVFPRRKSPSLPASYARFSQSGMEQSEEVHKKDQKPKKPGKYICHYCGRA
CAKPSVLKKHIRSHTGER--PYPCVPCGFSFKTKSNLYKHRKSHAHAIKA
GLVPFSELAATRPDMDQASSVGEAEVHSDGDQSTDTDEETALCVEGPGFL
DKSSPIPQISFEAEKSTTEKFGELAYADSADELAVAPMKVPILIVPKQGI
QPVGEGPQFAETETSPLSAQGGRVDEPHAVKQKLALRLTEKKGQDSEQSL
NLLSPHSKGST--DSGYF-SRSESAEQQI-SPPNTNAKSYEEIMFGKYYR
LNPRTSMTVGMTAVVCQDTNVMNIK-------DKSDH-I-SQLLTNNETL
VNPIKLNAKMFPRGDSSESQMVTGCDLKQYPTGTCQGSTGHLETPSDTGT
LIRSNSMPTSSASNLNVPQGIRGSHSFDERMTSDDVFYPGSGGLSHRSML
RRQGAFELPPAHEGHVELDSYGNVSKNI-VPPSGSVKLGSLMSELKGSGG
ERNLFECELCGTSYRRWEDWETHKKLECPEMRAKYGRMGMEAYSDLLSQS
LLMQHRQSTETATRKRRKEKSVGDDEDLPSQYSSDQGSMEMLVSASDFDS
KQANQEASRVTPTGKAHSYSQHSQSDSFETGGVLSTSTSMSAEDVVLV--
----------------PDADKLTDTSSRKAVGNVISVIQHTNSLSRPSSF
EKSESIEYPTYQQEKPTSQHSEQSD--SENIEEVQSPDSAMRAESMDQQQ
SEGEPATLPTNHQQYHIPPRLVRQPNIQVPEIRVTEEPDKPEKEPEVQTK
EPEKHVEEFQWPQRSETLSQLPAEKL-P------PKKKRLRLAEMEHSSG
ESSFESTCTSLSRSPSQESNLSHSSSFSMSFDRDETIKAVSPTKLDDFGK
QPEFLTVPGSGNSLSIPSQHQQREMRRSSSEQAPCALPTEVPEVRSKSFD
YGSLSSTSLQGESYASASGMKERRRGYLVRQASLSVYPESGIQEQCTDHS
IKQEYSEHVQSAHHSSHTTWHSSSSPLLHGV-PTGDVPRSKRGTQAVLGS
HHHPLQLSISEDSQPESHALIQKSSYVPSQHPSESERQTHDLPSREIMQY
SSFHSSLAQAPFLPFQQGMFWHPESSQRHKHHLAFQTH-QKLHIRHPNLQ
SFHQKTHPALQLQQVQDQGDAKAVESPSSQNYQYLSRASSHHPGHLPAKI
YSTSTVLVQQVQPIFATQNAGTQPSLPGMLVPVRIQTHVPSYGSVMYTSV
SQILVTHSQSTSS-TMVICKVTDNTAQGSFTNTGTKHGIGFSLSQILGNP
GGLLRYPLWKVPQPLPGRLDTGIPLCLTTGSISTTDASSSIGGSKRMLSP
ASSLELFMETKQQKRVKEEKMYGQIVEELSAVELSNSNVTKGNTKSQKTD
HLRHDGTGEYPERMSPSLLDFSSSRAPLLKTSSHSKEAPSVDNFTPPRQI
VTKTPDGRESPEELDIDEAVPDISLSPQSVHSMSDTQEENKMAMSSNIPV
NMLVQLAANQGGTAVGSTILLTDVADVQQFFQFPSLRTTTSVSWCFLNYT
KPNHTQTTPLSSVYASWCVSSYNPNPPNLNTKTTLSLLRSKQRKNTETYT
MAAMYRPGTGKLVSSVSWKQNLDQVKPELMQVEASKFEKKIKGSSTRERE
KEDHHGEKDG--SAKQAEPTRIKIFEGGYKSNEDYVYVRGRGRGKYICEE
CGIRCKKPSMLKKHIRTHTDVRPYVCKFCNFAFKTKGNLTKHMKSKAHMK
KCLELGVSVTSVDDVEAEEADNADDVQRETEKMGVSGATAEHQFSDADDS
EGVE-EEGD-------EIDEDDDEDDEYEGDSTPKTRSRSTSPQPCGISS
LSVTAAAASQSTASDLSTKPPLVSYFVTLPSIQITQLMVPSEKASDPQMA
EYQRLLQGALGESYKNRLDVPCSMDEDFMLSPEYSSSSTDFSPSRLSSPG
CDSSPHRESSPTPRRYLSPRRDLSPRGRLSPRREASPLRHLSPKRDVTFK
RDLSPRRDLSPRRHLSPISLGRPMSPGKDMSSRRELSPRSRHRGMIRAAS
PRRGLHHHNAPWALGQYLQSDILPLGRTNINRGNYTLGLMGLPSQERYFL
HLCTSLFHEGPYLTCPLPVLSPARVGALFSVFPLGGLDVVLCVRVCVCGV
SSASELSFPLSESSIRGAEDSFKQQEKLVSSQVLAGSPRMPNSASQRAKE
ETAEGAEKESEQEESIQTCTKAIASLRIASEDVGPLDKPTKAMDHRHDHH
HPLESVQFGIEHFSGSETRHVPVSVSATPPDCSAEKDNSTLKTAAVHSTF
YSKSADERLLGQQSLRELPSSTKTGKDSAREVVENR----------
*
