>P1;ENSAMXG00000004831

----------------------------------------MAR---S---
L-SPWLWL--------------RKPIYIQA--------RF----------
---------------SYLHMKYLFFSWLAVFVGSWVVYVEYSSYTELCRG
HECKNAICDKFRRGVIDGTACSSLCEKDTLYFGKCLSAKPSNQVYSGSWG
DM-----------------------------------EGIIKCHMEEVHH
-YDLAAEL---EPRKEP--------------------------V--SF--
--------------------------------------------------
--NRPTKGTSVEKF------------------------------------
--------KEMVMSHLKVK-----VGDQANLLDL--VALVLGVADADKDG
QISLAEARSAWALLQ-----------------------------LN-EFL
LAVVLQGREHTPRLLGFCGDLYVMEKVPYAPLYGISLPWVVELWIPAGLR
RSMDQWAS-PSWPRKAKIAIGLLELVEDVFHGTFGSFL-MC------DV-
-----------------------------SAAGFGY--------------
---------------TERHDLKVVDARRIVPEAAFQEVMRERR-------
---------CDVDADCIYGADCHTSCDL---TKHRCTTEVT-RPNLAK--
-----------------------------------------ACGALKDYL
LRGAPSDVREELEK---------------------------QLYACIALK
GSTEQMEMEHSLILNNLKTLLWKKIS------------------------
--------------------------------------------HTKDSK
-----------------------
*
>P1;ENSTRUG00000005129

----------------------------------------LHT---V---
NGMQHLLG--------------RIPFPAEA--------RI----------
---------------SFVRVKYLFLTWLTVLVGSWVIYVQYSAYTELCRG
HECRNAICDKYKKGVIAGSACSSLCDKETLYMSRCLSTLPNNQVYTGSWG
DH-----------------------------------DGIIHCKLGEIVH
-YDLGEEP---EPRREA--------------------------P--VF--
--------------------------------------------------
--DKPTRGTSVEKF------------------------------------
--------REMVFNHLKSK-----LGEQANLASL--VGKILSFSDGNKDG
RVSLPEARSAWALLQ-----------------------------MD-EVL
LGLLLQDRGHTPRLLGYCGDLYMTERVPYGPLYGLSLPWPLVSWVPSGVQ
RTMDQWFT-PSWPRKAKISMGLLELVEDIFHGTYGSFL-IC------DL-
-----------------------------AAAHFGY--------------
---------------TERHELRLTNTRAVVPEHELRRTMRTLR-------
---------CDTDDDCVYGADCRTTCDL---SEKRCREEPL-QPNLAK--
-----------------------------------------ACGALKDYL
LRGAPSELREELER---------------------------QLYACMALN
GNAGQMNMEHSLILNNLKALLWRQIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSDARG00000062955

----------------------------------------MAR---G---
L-FSRAWL--------------SKTHHFQA--------RL----------
---------------SYIRVKYLFLTWLAVFVSSWVVYVQYSTYTELCRG
RECKSIICDKYSKGIIDGSACSSLCEESKLYFGRCLSTKPNNQVYTGSWG
DQ-----------------------------------DGVIKCQLSDVLH
-YELGEEL---EPKKEI--------------------------T--LF--
--------------------------------------------------
--EKPTRGTSVEKF------------------------------------
--------KEMVASHLKAK-----VGEQANLSNL--VSLILSVADSNKDG
HISLPEAKSAWALLQ-----------------------------LN-EVL
LAVVLQGREHTPKLLGFCGDLYVVERVPHAPLFGITLPWPMDLWIPAGMR
RSMDQWFT-PSWPRKAKIFIGLLELIEDIFHGTFGSFL-MC------DM-
-----------------------------RASSFGY--------------
---------------TDRHDLRLVDGRRVVAEEAFKQAMILQR-------
---------CKDHEDCVYGADCRTSCDL---SEQRCTAEVA-QPNLAR--
-----------------------------------------ACGAMKDYL
LRGAPFHLQEELEK---------------------------QLYACMALK
GSAEQMEMEHSLILNNLKTLLWKQIS------------------------
--------------------------------------------HTTDS-
-----------------------
*
>P1;ENSXMAG00000004088

----------------------------------------MAK---G---
L-FPRAWV--------------KKSFYFQA--------RI----------
---------------SFVRVKYLFLTWLTVLVGSWVLYVQYSAYTELCRG
HECKNAICDKYRRGIIDGSACSSLCEKETLYMGRCLSTLPNNQVYTGSWG
DH-----------------------------------GGIIRCKLGEVGH
-YELGEEP---EPRRET--------------------------P--VF--
--------------------------------------------------
--DKPNRGTSVEKF------------------------------------
--------KEMLFNHLKSK-----LGEHADLRSL--VSQILSVADGNRDG
RVSLPEARSTWALLQ-----------------------------MD-EVL
LGLLLQDRGHTPRLLGYCGDLYMTERIPNGPLYGFSLPWPLVSWVPAGLQ
RTMDQWFT-PSWPRKAKISMGLLELVEDIFHGTYGSFL-IC------DL-
-----------------------------AAMHFGY--------------
---------------TDRHELRLTNTQVLVPEEEFRHTMRVLK-------
---------CETDADCVYGADCQTSCDP---SEKRCREEPV-QPNLAK--
-----------------------------------------ACGVLKDYI
LRGVPSEMREELER---------------------------QLYACMALR
GNAGQMNMEHSLILNNLKALLWKRIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSONIG00000010561

----------------------------------------MAK---G---
L-FPRAWV--------------KKSFYFQA--------RI----------
---------------SFVRVNYLFLTWLTVLVGSWVFYVQYSAYTELCRG
HECKNAICDKYRRGIIDGSACSSLCDKETLYMGRCLSTLPNNQVYTGSWG
DH-----------------------------------DGIIHCKLGEVVH
-YELGEEP---EPRRET--------------------------P--VF--
--------------------------------------------------
--DKPTRGTSVEKF------------------------------------
--------KEMVFNHLKSK-----LGEQANLASL--VSQILSVADGNRDG
RVSLPEARSTWALLQ-----------------------------MD-EVL
LGLLLQDRGHTPRLIGYCGDLYMTERVPYGPLYGLSLPWPLVSWVPSGLQ
HSMDQWFT-PSWPRKAKISMGLLELVEDIFHGTYGSFL-IC------DL-
-----------------------------AAAHFGY--------------
---------------TDRHELRLTNTQAVVPEEEFRRTMRALK-------
---------CETDADCIYGADCETSCDL---SERRCREEPF-RPNLAK--
-----------------------------------------ACEALKDYL
LRGAPSGMREELER---------------------------QLYACMALK
GSAGQMNMEHSLILNNLKALLWKQIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSORLG00000013740

----------------------------------------LHL-IKS---
L-THMLII--------------PCSKLQLA--------KF----------
---------------SFLHMKYLFFSWLALFVGSWIVYVEYSSYTELCRG
KDCKNSICDKYRKGVIGGSACSSLCEKDTLYLAKCLTAKVSSQVYSGNWA
DL-----------------------------------EGIIKCQM-EAPH
-DGLEGEM---EPRKEA--------------------------T--VF--
--------------------------------------------------
--DKPTKGTSVETF------------------------------------
--------REMINNHFKAK-----VGDRVSLVDL--TTQVLSIADVNKDG
YISLPEARSTWALLQ-----------------------------LN-EFL
LAFVLQGQGHTPKILGFCGDLYVMEKVPNSPLYGISLPWIMEMSIPVSLR
RSMDQWFT-PQWPHKAKISIGLLELVEDIFHGTFGSFL-MC------DV-
-----------------------------STGSFGY--------------
---------------NDRHDFKVVDARYIVPEATFQERIRQQH-------
---------CSADEDCLYGADCLTSCDL---TKHRCTTEVT-RPNLAK--
-----------------------------------------VCETLKDYI
LRGAPADVSEELEK---------------------------QLYVCIALK
GSADQMEMEHSLVLNNLKTLLWKKIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSXMAG00000003141

--------------------------------------------------
----------------------FETCLQQA--------RF----------
---------------SYLHMKYLFFSWLAVFVGSWIVYVRYSSYTELCRG
HDCKNSICDKYRKGVIDGTACSSLCEKETLYLEKCFTAKPNNQVYSGNWG
DL-----------------------------------QGVIKCQMEEAPH
-YDLGGEM---EPRKEA--------------------------APVAF--
--------------------------------------------------
--NKPTKGTSVEKF------------------------------------
--------REMIISHLKAK-----VGDQANLADL--ATQVLSFTDSNKDG
HISLPEARSTWALLQ-----------------------------LN-EFL
LALVLQERDHTPKLLGFCGDLYMMEKVPYSPLYGISLPWIVELWIPAGLR
RSMEQWFT-PSWPHKAKISIGLLELVEDIFHGTYGSFL-MC------DV-
-----------------------------RTTTFGY--------------
---------------NERYDFKVVDARYIIPEATFQERIRQQR-------
---------CDVDEDCLYGTDCLTSCDL---TKHRCTPEVT-RPNLAK--
-----------------------------------------VCDTLKNYI
VRGAPSDLSDELEK---------------------------QLYACMALK
GSAEQMEIEHSLILNNLKTLLWKKIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSGACG00000004224

----------------------------------------MAR---G---
R-FPWGLC--------------RKPLHIQA--------RL----------
---------------PYLHMKYLFFSWLAVFVGSWIVYVEYSSYTELCRG
HDCKNSICNKYKKGIIDGSACSSLCEKDTIYLGKCFTAQPKSQVYSGIWG
DL-----------------------------------EGVIKCQMEEAPH
-YDLGSEM---EPRKEA--------------------------A--AF--
--------------------------------------------------
--TLPTKGTSVEKF------------------------------------
--------REMILNHVKAK-----VGDQANIADL--ATQVLSITDANRDG
HISLPEARSTWALLQ-----------------------------LN-EFL
LALVLQDREHTPKLLGFCGDLYVMEKVPHTPLYGISLPWIVEAWIPAGLR
RSVDQWFT-PSWPHRAKISIGLLELVEDVFHGAFGSFL-MC------DV-
-----------------------------SAASFGY--------------
---------------NGRHDLKVMDARYIVPEAVFQEEVRQRR-------
---------CDADEDCLYGADCVTSCDL---TKHRCTPEVT-RPNLAK--
-----------------------------------------ACEALKDYV
LRGAPADVREELEK---------------------------QLYSCVALK
GSTEQMEIEHSLILNNLKTLLWKKIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSTNIG00000006968

----------------------------------------MAK---A---
L-FPRAWV--------------KKSFYFQA--------RI----------
---------------SFVRVKYLFLTWLTVLVGSWVVYVQYSAYTELCRG
RECRSAICDKYRKGVIAGSACSSLCDKETLYMSRCLSTLPNNQVYTGSWG
DH-----------------------------------DGIIRCKLGEVLH
-YELGEEP---EPRREA--------------------------P--VF--
--------------------------------------------------
--DKPTRGTSVEKF------------------------------------
--------REMVFNHLRSK-----LGEQANLAGL--VGQILAFSDGNKDG
RVSLAEARSAWALLQ-----------------------------MD-EVL
LGLLLQDRGHTPRLLGYCGDLYMVERVPYGPLYGLSLPWPLVSWVPGGLQ
RTMDQWFT-PSWPRKAKISMGLLELVEDIFHGPYGSFL-IC------DL-
-----------------------------AAVHFGY--------------
---------------TERHELRLTNTRAVVPERQLRRAMRTLK-------
---------CESDGDCVYGVDCRTTCDL---SENRCREETL-QPNLAK--
-----------------------------------------ACGALKDYV
LRGAPSALREELER---------------------------QLYACMALN
GNAGQMNMEHSLILNNLKALLWRQIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSAMXG00000006694

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------VYTGSWG
DV-----------------------------------DGVIKCQLNDVLH
-YELGEEL---EPRKES--------------------------A--LF--
--------------------------------------------------
--DKPTRGTSVEKF------------------------------------
--------KEMVSSHLKAK-----VGEQANLSSL--VSLILTVADGNKDG
RVSLPEAKSAWALLQ-----------------------------LN-EVL
LAVVLQDREHTPKLLGFCGDLYVVERVPYTPLYGLSLPWPLELWVPAGFR
RSMDQWFT-PSWPRKAKISIGLLELVEDVFHGPFGSFL-MC------DM-
-----------------------------RPGSFGY--------------
---------------TDRHDLRLVDGRLVVPEEAFGSTMRLQR-------
---------CREDGDCVYGVDCRTSCDR---AEGHCTPRVS-QPNLAR--
-----------------------------------------ACGALKDYL
LRGAPAHLRDELEK---------------------------QLYSCMALR
GSAQHMEMEHSLILNNLKTLLWKQIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSGACG00000015666

----------------------------------------MAK---G---
L-FPRAWV--------------KKSFYFQA--------RV----------
---------------SFVRVKYLFLTWLTVLVGSWVLYVQYSAYTELCRG
HECRNAICDNYRKGIIDGSACSSLCDKDTLYMSRCLSTLPNNQVYTGSWG
DH-----------------------------------DGIV-CRLGEVTH
-YELGEEP---EPRRES--------------------------P--RV--
--------------------------------------------------
--RQAHQRHIVEKF------------------------------------
--------REMVFNHLKSK-----LGEQANLAGL--VGQILSVADGNKDG
RVSLPEARSTWALLQ-----------------------------MDEEVL
LGLLLQDRGHTPRLLGYCGDLYMTERVPYGPLYGLSLPWPLAGWVPSGVQ
RTVDQWFT-PSWPRKAKISMGLLELVEDVFHGTYGSFL-IC------DF-
-----------------------------AAAHFGY--------------
---------------TDRHELRLTNARAVVPEAAFRRAMRART-------
---------CEADGDCVYGVDCHTSCDV---AEKRCRGEPL-RPNLAK--
-----------------------------------------ACGTLKDYL
LRGAPSGLREELER---------------------------QLYACMALR
GNAGQMNMEHSLILNNLKALLWRQIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSTNIG00000013765

----------------------------------------MAR---G---
P-FSRGFF--------------RKLLYVQA--------RF----------
---------------SYLHMKYLFLSWLAVFVGSWVVYVEYSSYTELCRG
RECKNSICDKYRRGLIDGSACSSLCEKGTLSLGTCFSARAKSQVYTGSWG
DL-----------------------------------EGVIKCRMEEAQR
-YDLENQV---EPRKKA--------------------------A--GF--
--------------------------------------------------
--DQPSRGTSVEKF------------------------------------
--------REMILDHLKSK-----VGDQANLADL--AAQVLSMTDANKDG
HISLPEAHSTWALLQ-----------------------------LN-EFL
LALVLQDREHTPKLLGFCGDLYVTEKVPYSPLYGVGLPWILEVWIPASLR
HSMDQWFT-PSWPFKAKISIGLLELVEDVFHGTFGSFL-MC------DV-
-----------------------------SAGSFGY--------------
---------------NDRHDLKVTDARYIVPEAVFQEDIRQQR-------
---------CDDDRDCRFGADCLTSCDL---TKHRCTTEVT-RPNLAK--
-----------------------------------------ACETMKNYV
LRGAPPDVREELEK---------------------------QLYACMALK
GSAEQMEMEHSLILNNLKTLLWKRIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSTRUG00000000590

----------------------------------------FTALTRL---
T-HILLQY--------------RILWQFQA--------RF----------
---------------SYLHMKYLFFSWLAVFVGSWIVYVEYSSYTELCRG
HECKNSICDKYRRGLIDGSACSSLCEKSTLYLGKCFTTKPISQVYTGIWG
DL-----------------------------------EGVIKCQMGEAHR
-YDLENQV---EPRKEA--------------------------A--GF--
--------------------------------------------------
--NKPSKGTSVEKF------------------------------------
--------REMILHHLKSK-----VGDQANLADL--AAQVLSITDANKDG
HISLPEAHSTWALLQ-----------------------------LN-EFL
LVLVLQDREHTPKLLGFCGDLYVMEKVPYSPLYGISLPWILEAWIPAGLR
HSMDQWFT-PSWPFKAKISIGLLELVEDVFHGAFGSFL-MC------DM-
-----------------------------SANSFGY--------------
---------------NDRHDLKVMDARYIVPEAVFQEDIRQQR-------
---------CDVDQDCLYGADCLTSCDL---TKHRCTTEVT-RPNLAK--
-----------------------------------------ACETIKNYI
LRGAPADVREELEK---------------------------QLYACIALK
GSTEQMEIEHSLILNNLKTLLWKRIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSDARG00000061362

MLLIAREVRRLRSITLFIIRSPYGEKHPGLVSAVKCGVSIMAR---G---
L-IPWIWL--------------KRPVYIQA--------RF----------
---------------SYLHMKFLFFSWLAVFVGSWVVYVEYSSYTELCRG
HECKNTICDKFQKGVIDGSACNSLCEKDTLYLGKCLSAKPSNQVYSGSWG
DM-----------------------------------EGIIKCQMKEDPH
-YDLGFEL---EPRKES--------------------------A--SF--
--------------------------------------------------
--SRPTKGTSMQKF------------------------------------
--------KEMVFNHLKAK-----VGDQANLADL--LTLVLGVADSNKDG
EISLSEAHSAWALLQ-----------------------------LN-EFL
LSVVLQEREHTPRLLGFCGDLYVMEKVPYVPLYGVSLPWMVELWIPASLR
RSIDQWAT-PSWPRKAKIAIGLFELVEDVFHGTFGSFL-MC------DV-
-----------------------------SAAGFGY--------------
---------------TERHDIKVVDARQIVPEVGFQEVMRERR-------
---------CEEDTDCLYGRDCFTSCDL---TKHRCTTEVT-QPNLAK--
-----------------------------------------VCSTLKDYI
LYGAPSDIKDELDK---------------------------QLYACIALK
GASEQMEMEHSLILNNLKTLLWKKIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSORLG00000005089

----------------------------------------LQR---NKQL
L-LIILLV--------------VSVHVIQA--------RI----------
---------------SFMRVKYLFLTWLTVLVSSWVVYVQYSAYTELCRG
HECKNAICEKYRRGVIDGSACSSLCDKGTLYFGRCLSSLPNNQVYTGSWG
DH-----------------------------------SGVIRCQLGEAAR
-YDLSDEP---EPRREA--------------------------P--AF--
--------------------------------------------------
--DQPSKGTSVEKF------------------------------------
--------REMVFSLLKSK-----LGEQVNLSGL--VSQILSVTDGNKDG
RVSLPEARSTWAVLQ-----------------------------RD-EVL
LGLVLQERGHTPRLLGFCGDLYMTDRVPYGPLYGFALPWPLVSWVPGSLQ
RTMDQWFT-PSWPRKAKISMGLLELVEDVFHGTYGSFL-MC------DL-
-----------------------------AAVHFGY--------------
---------------TDRHELRLTDTQVLVPEDEFRRNMRALR-------
---------CETDADCVYGADCQTSCDL---SEKRCGEQPL-RPNLAK--
-----------------------------------------ACRTLKDYL
LRGAPSGMSEELER---------------------------QLFACMALR
GNSRQLDMEHSLILNNLKALLWRQIS------------------------
--------------------------------------------HTKDS-
-----------------------
*
>P1;ENSLOCG00000005068

----------------------------------------MAE---K---
R-LQKGGEESLSCSSTVPCVWIMGTTASAAQQTVAVAPPYESIHGNGMAD
NRRSLSINSFQTVNIHSSKAKSIITNKVAPVVITYNCRQEFQIHDDLFKA
E---------YTLGRISDTMPEHYLVQGKYFMVQDVYSKADVLNTTGSYG
APNFRQAKGSYPLFGMGQPSLSGFKQVLQRLQTQGYEEVIFICVREEPVV
FLHLENNFVPYTPRRKENLHENLHGLGKDVKVEKLELSIRKELY--DFAK
LSENVYYVYNDIEHFKDEPQHITITCEEDIHVTEEVYKRPAFIMPSYRYY
RLPLPMEGSPLEEQFDGFVNILRENPNLLLIRDSTRPPPALLFSCQVGVG
RTTLAMILGALVMFHLKGAPEKPPVDETVSAAPKVHFQIIQSLVSKLPNG
QRVIEEVDSAIALCSEMHDIKEAIYENKKKLEGIGEDYQIQGSSTK-EYF
LQRTMQSLECYFYLIAFN--AYLHEQYPLV------------------FA
LNFSKWMCSHPWIYRLLACMNLSELSAPADLVTKGTRVLVSDDFLAPDVL
STVKEMKVANFRRVPKMSVYGMAQPNSEGAGAVLGYLTDEKRKYSHILWL
NLQEELVLEGNGQIFTPREPSR-LETRIPVPASSPQEIEKLETAVKEEIL
KAQKWLEVSLEQEKQMKMFKTCVTVQEIFNQHKSTCKGLVYKRIPLSDCC
APKEQDFDQLMEAMKAALAEDSRTAFVFNCHNGKGSTTTAMVIATLILWH
FNGFPEFSEDEIVSVPDAKYTKGEFEVVMQLVRLLPEGHKMKKEVDMALD
AVSETMTPMHYH-LREIIICTYRQIKTAKKEKESQLLKSLQYLERYIYLI
LFNAYLHLEKKDSWQRPFSVWMHEVAARAGVYDVLNQLGFSEFENPQDVP
LARLRYRWPQQNVHLLPFRGQFI
*
