>P1;ENSXMAG00000004190

M----R-------SSAQFVARCALI-LYT----LF------FIDGS-KG-
---------QRQ---CTEIDYYYEYTECDSTGSRW---------------
---RVAIPQNPGFCTGLPQPVRGTECTFSCRAGEFLEMSAQECTQCAAGS
YSLGSGIRFDQWDAMPAGFRSVATSLGNDPKRD-AQP---TCNS----SS
WVPQGN--------------------Y---LESNRDECTVSLIYAVH---
-LKKQGSVSFEYQ------------------------------YPD----
-KSLLFEFFIQNDQCQEMDQ-STDTKWLQLTNHGE-WGTHTVNLK---SG
TNILYWRTGGVVMRSSVVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCK
PGSFSRIPGS------------------ST-----CESCPRDTYSGHGAS
SCTPCNATTEYAEEGSSECKNRPPCSK------KDYFQIHTPCDHEGKTQ
VIYK-WIEPKICLE-GIFGAEALPESGEQEECPPCNPGFYNNDTATCSPC
--PT----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GMYSDGLKPCHRCPAGTEPILGYEYKWWNVLPSNMKTS
CFNVGNTKCDHMNGWEAARDHIHSGA---------------GSSDNDYLI
LNIHV------------PGFKLPTS-------------------------
-------VPSQSVTEFGRITFEFETSCMA----DCEFYFMMDINRKSTTV
V-------QS---------WEKTQKRQTYTHTM-SKNAAVSYT-WAFQRT
NQPSDVRRYINDVARIFSITVTNA---VDGVSSSCRACALS---TQPSSS
ACVPCPPGHYIDTLTRKCLECPRNS----YLEPH----------------
--------------------------------------------------
------------------------------ATPGSDACKACGP---ASRS
DKDHRLCYSDCHFIHTEGNVTLTFDFSPLGSAGSLMNGPKFTS-------
-----------------------------------KGTKYFHMFNISLCG
GQD-RMAVCADNTTDMSVSSSQKEKAEGSSAV------------------
KTFICQSTIIPASRQGFLAALSSQSINLADTF--LGAT-VDDNLEGIKAR
PDLFPQ-KSKKVPDINFFFRSFEGTSSCESGRSTVVTLHCNPDMSTKGEL
SVPSQCPEGTCDGCTFHFFWESSGACPTCTVRDYHLIEGVCKGGQ-QDML
YVWTEPKLCIGGVTLPDKKTVPCQ---------SMEFWVHLGAGTGIFTA
VLLICLTCYFWKKNK--RLEYKYSRLVMSANKECEMPVADSCAVMEGENE
GDMEDEVVYT--KPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKGN-GERYEN---------VQLNSSHSKAL---VWS---
*
>P1;ENSGACG00000020052

--------------------------------------------------
-----------------QTDYYYQYTECDSTGSRW---------------
---RVAIPLSPSSCSDLPPPARGTDCSFSCPAGMFLEMGTQQCTPCAAGS
YSLGSGLRFDQWDAVPAGFTSLASFLDPGPNGE-DVQ---ACNS----SS
WTPQGV--------------------Y---LESNRDECTVSLVYAVH---
-LEKKGSVSFTYQ------------------------------YPD----
-NNIFFEFYVQNEQCQEMAQ-TDDQKWIRVTNTGE-WDTHTVNLK---SG
TNILYWRTTGILVGGKMVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFLCR
PGWFSPAPGS------------------SS-----CQPCPTNTFSSKGAS
SCTNCP-EHQYAHEGWGECKRRPPCSE------KDYFQIHTACDGEGKTQ
VLYR-WVEPKICVE-NVTGAVQLPTAVQREPCPPCNPGYYNSNSNDCLPC
--PP----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTYSDGTYVCTECPAGTEPVLGYEYKWWNVLPSNMKTS
CFNVGNSKCDDMSGWAVAGDHIRSAA---------------GSSDNDYLI
LSLHV------------PGFKVPAS-------------------------
-------LSGMTGSEFGWITFVFETICSG----DCELYFMMDVNMKSTTV
V-------ES---------WEGSKEKQSYSHSM-SRNASVTFT-WAFQRT
NHALDVRRYVSDMVKLYSISVTNA---LDGVASACRACALVPQNSQRAGS
SCVPCPAGFYIDTGTNRCQECPPNT----HLAGH----------------
--------------------------------------------------
------------------------------HTYGQDACVACGM---GSIS
NKEHSRCYSDCSFSHTENNRTLTFDLSPLSDVASLIIGPSFTS-------
-----------------------------------KGTKYLHLFNISLCG
HEGRRAAVCTDNVTDVSSKDDQSDSAQLVNSV------------------
DSFVCQSTIIPADGRGFRMAISSQSISLADAF--VGAT-VDSVLDWVDAK
PDLFPA-KTKDLPDINFFYRSTQPTASCDHGRSSVITVRCNPEKSDRGEL
SVPSSCPAGTCDGCTFHFLWESASGCPRCAEDDYHPIEGACKGGV-QETL
YVWNEPKVCTKGVSLPPRSSSPCE---------AIALWLKVGVGGGAFVA
VLLIALTCYFWKKNK--RLEYKYSRLVMSANKECELPAADSCALAEGE--
-EPDDDVVYTKKKPSLLGKLRAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------AHKHERGESCES---------VQLNSSQCDRW---VLG---
*
>P1;ENSTNIG00000019203

------------------------------------------------P-
---------DSV---CVQKDYYYQYTECDSTGSRW---------------
---RVAIPQTPGDCAGLPEPVRGTECTFSCKAGEFLEMSAQQCTQCAAGS
YSLGSGVRFDQWDSMPAGFSSLATSLESGSHGD-GGP---SCNS----SS
WLPQGN--------------------Y---LMSNRDECTVSLIYAVH---
-LKKQGSVSFEYQ------------------------------YPD----
-NNLLFEFFIQNDQCQEMDQ-SSEAKWLKLTNHGE-WATHTVNLK---SG
TNILYWRTGGVLMGSKVLKPVFLRNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCK
AGTFSSSPGS------------------SA-----CVPCPRDTYSGHGAS
SCTPCDTATQYAGEGSAACADRPLCSK------KDYFQIHTACDQEGKTQ
VMYK-WIEPKICLE-GVSGAEPLPPSGEREPCPPCNPGFYNNDTPTCSPC
--PA----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GSFSDGTKPCSQCPAGTEPTLGYEYKWWNVLPANMKTS
CFNVGNSKCDNMNGWEVAGDHIRSGA---------------GSSDNDYLI
LNIHI------------PGFKLPTS-------------------------
-------VSSQSGTEFGRITFEFETVCTA----DCELYFMMDVNRKSTTV
V-------ES---------WEGTKTRRSYTHVM-AKNASVSYT-WAFQRT
NQPSDLRKRLNDVSRIYTISVSNA---VDGVSSGCRACALS---SQPSSS
ACVPCPAGHYINTSTSQCTECPSNT----HLVSH----------------
--------------------------------------------------
------------------------------ATPSPDACKPCGP---ASRS
DEDHRLCYSDCHFTHTVGNATLTFDFTPLGSVGSLMNGPSFTS-------
-----------------------------------KGTKYFRQFNISLCG
GQS-QLAVCTDNVTDLSIADSQSERGEAANTV------------------
KTFICQSTIIPANGRGFHTALSSQSITLADIFLVLGVT-VENSLDGIEAM
PEQYTQ-SSKKVPDINFFYRSLEATSSCPSGRSTVVTLRCNPEKSTRGDL
SVPSRCPAGTCDGCTFYFLWESAGACPTCTERDYHQIEGACKGGQ-QDLL
YVWTEPKLCIGGAALPRKRTLACA---------GVEFWVQLGAGLGAFTA
VLLVSLTCYFWKKNK--RLEYKYSRLVMSANKECEMPGTDSCAVMEGENE
GDLEDEVVYT--KPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKGN-RENFEH---------VQLNSSHPKA------L---
*
>P1;ENSXMAG00000003572

MWGAVR-------T-S-CFSRCLLS-IHLLFLLLLIISAHRSAASADGD-
---------LQP---CDKGDYYYQYTECDSTGSRW---------------
---RVAIPLSPGSCSDLPSPTRGTDCSFSCPAGMFLEMSSQLCTPCAAGS
YSLGSGLRFDQWDAIPAGFTSLASFLDPGPNGE-DIQ---ACNS----SS
WTPQGV--------------------Y---LESNRDECTVSLVYAVH---
-LEKQGSVSFNYQ------------------------------YPD----
-NNIFFEFYVQNEQCQEMSQ-TDDQKWIKVTSSGE-WGTHTVSLK---SG
TNILYWRTTGILVGGKMVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCR
PGWFSPMPGS------------------SS-----CQACPSNTYSRKGAS
ACSACP-EHYYSHEGWAECKVRPPCSE------KDYFQIHTACDSEGKTQ
VLYR-WVEPKICVE-NVTGAVKLPATGQREPCPPCNPGYYNSNDSTCLPC
--PP----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTHSDGIYACVECPAGTEPVLGYEYKWWNVLPSNMKTS
CFNVGNSKCDDMNGWEVAGDHIRSGA---------------GSSDNDYLI
LSLTA------------PGFKVPAS-------------------------
-------LSGMTGGEIGKITFVFETICSA----DCELYFMMDVNRKSTTV
V-------ES---------WQGSKGKQAFSHSM-TRNASVTYT-WAFQRT
SHALDVRRYVSDTVKIYSIKVTNV---LDGVASACRACALVPQNSQRAGS
SCVPCPAGFFIDRETNRCQECPANT----HLAGR----------------
--------------------------------------------------
------------------------------HTYGQDACIACGP---GSIS
NKEHSRCFSDCFFTHTENNRTLTFDLSPMSNVASLILGPSFTS-------
-----------------------------------KGTKYLHLFNVSLCG
HEGKRAAVCTDNVTDVSSKDDQSDLSQFVNTV------------------
DSFLCQSTIIPGDGRGFRMAISSQSISLADTF--IGAT-VDTVLSGVNAK
PDLFPE-NPNDVLDINFFYRSTQATASCDQGRSSVITVRCDPEASDRGEL
SVPSSCPAGTCDGCTFHFLWQSASACPRCTEADYHLIEGACRGGI-QETL
YVWNEPKLCTEGVALPSRSSAPCE---------VIALWLKVGLGVGAFVA
VLLVSLTFYFWKKNK--RLEYKYSRLVMSANKECELPAADSCALAEGE--
-EAEDDVVYTQ-KPSLLGKLRAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKHEGGESSES---------VQLNSSHADRW---VLG---
*
>P1;ENSAMXG00000009791

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----FFIQIQNDQCQEMDQ-TADQKWIKLTSNGE-WGTHTVNLK---SG
TNILYWRTTGILLGGKPVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YASECFPCR
PGTFSKTPGS------------------SS-----CDLCPRNTYSNKGAS
SCTPCP-GTQYSEEGWAECKERPACSE------KDYFQIHTACDSTGKTQ
VLYR-WVEPKVCVEDSVSGAVALPPSGEKEDCPPCNPGFYTHNSSTCLPC
--PT----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTFSDGTTDCQACPAGTEPSLAYEYKWWNILPRNMKTS
CFNVGNSKCDDMNGWEVAGDHIHSGI---------------GGSDNDYLI
LSLRV------------PGFKLPTS-------------------------
-------IAGVTASEFGRITFVFETICSA----DCELYFMMTLNISSVAE
S-------EN---------TGAGQRIRAFLHLI-VRKSKAHLKFFNFPKL
HSISQVRRYVNDIVKIYSITVTNA---LDGSASSCHACALV---SQESGS
SCVPCPPGHFIDKDTNQCQECPPNT----FLSGH----------------
--------------------------------------------------
------------------------------HIYGQEACQSCGP---GSRS
NKEHSVCFSDCSFSHTDQNRTFTYDLSALSSVGSIMNGPSFTS-------
-----------------------------------KGTKYFHQFNISLCG
AEGRKVAVCTDNVTDLATKDLQSESAGLNNYV------------------
QTFVCQSTIIPADGRGFRTALSSQSISLADTF--LGAT-VDSTLDGVSVR
PDLFPG-RSWKLPDINFFFRSPLVTASCEHGRSAVITLRCNPEKGERGEL
TVSSKCPAGTCDGCMFYFLWESSSACPICTDADYHSIEGACKGGM-QDTL
YVWNEPKLCTKGVSLPEKSSTPCE---------AVPLWLKVGIGGGAFMA
VLLISLTCYFWKKNK--KLEYKYSRLVMSANKDCELPAADSCALAEGEGE
-ENEDDVVYSN-TPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKEK-SHLFTT---------I-------------------
*
>P1;ENSORLG00000009407

--------------------------------------------------
-----------Q---CSEADYYFEYTECDSTGSRW---------------
---RVAIPRTPGACTGLPEPVRGTECTFSCRAGEFLEMSSQDCTQCPAGT
YSLGSGIRFDQWDSLPPGFSSLATSLENGQDRD-IKA---TCNS----SS
WLPQGN--------------------Y---LESNSDECTVSLIYAVH---
-LKKKGSVSFDYQ------------------------------YPD----
-SNLLFEFFIQNDQCQEMDQ-SADTKWLKLTKHGE-WASHTLNLK---SG
TNVLYWRTGGILMGTKVVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFRCK
PGTFSRAPGS------------------SS-----CDLCPQDTFSGHGAS
SCTPCNTSTQYAGEGSDKCKARPPCSK------KDYFKIHTACDNDGKTQ
IIYK-WIEPKICLE-GVPGAQTLPSSGDREPCPPCNPGFYNNDTATCSPC
--PP----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTYSDGMKPCQSCPAGTEPTLGYEYKWWNVLPSNMKTS
CLNVGNSKCDKMHGWEVAGDHIYSGA---------------GGSDNDYLI
LNLHI------------PGFKLPTS-------------------------
-------ASSDSATEYGRITFEFETLCTA----DCVMYFMMDVNRKSTTI
V-------ES---------WGKTQTRQTYTHIM-TKNASVAYT-WAFQRT
GQPYDTRLYMNDVARIYSITVNNA---VDGQSSGCRVCALS---AQSTSS
ACVPCPPGHYIDTDSNQCKECPSNT----YLVSH----------------
--------------------------------------------------
------------------------------ASLGSEACKACGP---ASRS
DEDHRLCYSDCHFTYTDGNLTLTYNFSLLGATGSLMNGPSFTS-------
-----------------------------------KGTKYFHLFNISLCG
GQVSKLATCTDNVTDLSVSDSQGEKGDGPSAV------------------
KTFICQSTIIPATGRGFNSALSSQSINLADTF--LGAT-VEDHFEGISAK
PDQYPQ-ISKKVPDVNFYYRSLEPTSSCESGRSTVVTLRCNPEMSIKGQL
SVPSQCPAGTCDGCTFYFLWESSGACPICTERDYHQIEGVCRGGN-QEIL
FVWAEPKLCMGGVTLPEKKTLPCK---------SMELWVRLSAVMGTFTA
VLLVSLTCYFWKKNKSARLEYKYSRLIMSANKECEMPGADSCAVMEGENE
GDMEDEVVYT--KPSILGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKRN-GDHYEN---------VQLNSSQSRAL---VWS---
*
>P1;ENSAMXG00000000958

MF-----------------------------CSLC------VIAGA-ES-
---------LSE---CSEGDYYFEYTECDSTGSRW---------------
---RVAIPQRPGECTGLPDPVQGTDCSFSCAAGEFLEMSAQECTQCAAGS
YSLGSGIRFDEWDDIPRGFSSVATYLDNTPHGQ-QGP---SCNG----SS
WIAQGS--------------------Y---VESNRDECSVSLVYAVH---
-LKKQGSVSFEYQ------------------------------YVD----
-NNIFFEFFIQNDQCQEMEK-TSDQKWIKLTSNGQ-WSKHTVSLK---SG
TNVLYWRTTGVTVGAKIVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YMSECLPCK
PGTFSKSPGS------------------SS-----CELCPRNTYSGRGAS
SCTPCNTTTHYALEGSSVCKARPACSK------KDYFQIHSVCDEEGKTQ
IIYK-WIEPKICLE-EVPDAVTLPPSGEREPCPPCNPGFYNNNTATCLPC
--PQ----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTYSDGLKECQPCPAGTEPALGYEYKWWNILPANMKSS
CFNVANTKCDGMNGWEVAGDHIRSGA---------------GGSDNDYLI
LNLKV------------PGFRKPWS-------------------------
-------MLQKWCVS---VSAVIKTACNKLFSLSLAIPFKSQLNQTGDNH
T-------SE---------WKA----QKYKYILFEKSCDSSVD-YALSLS
LARSQVRQYVNDMVKIYLITVTNA---LDGVASSCRACAIE---SQQPGS
ACVPCPAGYYIDEETNQCQECPPNT----FLSGH----------------
--------------------------------------------------
------------------------------HVYGRDACQPCGP---GSRS
NKEHSLCFSDCSFTHTELNHTLQFDFSSLGSTGSIMNGPSFTS-------
-----------------------------------KGTKYYHLFNISLCG
LEAHRPAVCSDNVTDLSDKDPHGS---EANKV------------------
EAFICQSTVIPSDGRGFRVALSSQSTSLADSF--LGAT-LEKSLNGVTAR
PELFPT-QPKRVPDINFYYRSPQTTSSCENGRNTVVTLRCSPEKTAKGEI
SVPRQCPAGTCDGCTFHFLWESSSACPCCTEADYHQIEGACKGGV-QDTV
YVWTEPRLCTGGVGLPVKRSTPCE---------MIDFWLKVGAGVGAFCA
VLLVSLTCYFWKKNK--KLEFKYSKLVMSTNKECELPAADSCAIMEGEGE
-EVEDEVVYS--KPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ATK--------------------------------------
*
>P1;ENSGACG00000012746

--------------------------------------------------
-----------------QTDYYYEYTECDSTGSRW---------------
---RVPIPQSPGACTGLPEPVRGTECTFSCEAGEFLEMSAQECTPCAAGS
YSLGSGIRFDQWDSMPAGFSSLATSLEYNAHRD-ERL---TCNS----ST
WVPQGS--------------------Y---LESNRDECTVSLIYAVH---
-LKKQGSVSFEYQ------------------------------YAD----
-NNLLFEFFIQNDQCQEMDQ-SADAKWLKLTNHGE-WATHTVNLK---SG
TNILYWRTGGVMM-AKGVKPVLLKNVQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCK
PGSLSRVPGS------------------TA-----CEPCPRDTYAGHGAS
SCTPCNATTQYAAEGSAYCKYRPPCSK------KDYFQFHTACDNEGKTH
VIYK-WIEPKICLD-GVTGAEPLPPSGEKEPCPPCNPGFYNNDTAICSPC
--PP----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTFSDGMKPCDRCPAGTEPTLGYEYKWWNILPANMKTS
CFNVGNSKCDGMNGWEVARDHIQSGA---------------GSSDNDYLI
LNIHI------------PGFKLPTS-------------------------
-------MSSHSGTEFGRITFEFEIVCVA----DCEFYFMMDVNRKSTTV
V-------ES---------WEGTKTRQTYTHVM-TQNASVSYT-WAFQRT
NQPSDVRRYVNDVVRIYSVSVSNA---VDGVASRCRACALS---TRPSSS
TCVPCPPGHYIDARTSRCTECPRNT----HLVPH----------------
--------------------------------------------------
------------------------------ATPGPDACKPCGP---ASRS
DKDHSLCYSDCHFTHTEGNVTLTYDLSLLGSVGSLMNGPSFTS-------
-----------------------------------KGTKYFHLFKIGLCG
G---KMAVCTDNVTDLSIADSQREKGEGISAV------------------
KTFICQSTIIPATGRGFHTALASQSINLADTL--LGVT-VASTLDGIRAR
PELYPQ-TTKKVPDVNFYYRSLEPTSSCESGRSAVVTLRCNAEKSTKGEL
AVPSQCPAGTCDGCTFHFLWESSAACPTCTERDYHQIEGACKGGHPQDLL
YVWTEPKLCVGGLSLPEKKTLPCE---------GVEFWVRLGAGLGAFTA
VLLVSLTCYFWKKNK--RLEYKYSRLVISANKECEMPGADSCAVMEGENE
GDMEDEIVYT--KPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKGN-GEHYEH---------VQLNSSHSKAL---VWS---
*
>P1;ENSONIG00000014986

M----Q-------TSAWLVGRCALI-LCA----LQ------LMDGA-KG-
---------QKQ---CTETDYYFEYTECDSTGSRW---------------
---RVAIPQIPGACTGLPAPVQGTECTFSCKAGEFLEMSAQECTQCAAGS
YSLGSGIRFDQWDYMPIGFSSLATSLENSLPGY-NSL---TCNS----SS
WVPQGN--------------------Y---LESNRDECTVSLIYAVH---
-LKKQGSVSFEYQ------------------------------YPD----
-SNLLFEFFIQNDQCQEMDQ-SDDKKWLKLTKHGE-WATHTVNLK---SG
TNILYWRTGGVTMGKKVVNPALLKNIHIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCK
PGSFSRVPGS------------------SS-----CEPCPRDTYSGHGAS
SCTPCNTSTQYAAEGSSSCKDRPPCSM------KDYFQIHTACDQERKTQ
VIYK-WVEPKICLE-NVTGAVTLPPSGEREPCPPCNPGFYNNDTATCSQC
--PP----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTFSDGMKPCQQCPAGSEPTLGYEYKWWNVLPSNMKTS
CFNVGNSKCDSMNGWEVAGNHIQTGA---------------GSSDNDYLI
LNLHV------------PGFKLPTS-------------------------
-------VSSHSGEEFGRITFEFETSCTA----DCELYFMMDVNRKSTKI
V-------ES---------WEKNKTRQTYTHIM-TKNASVSYT-WAFQRT
NQASDIRQYVKDVARIYSITVSNA---VDGASSGCRVCALG---AQPSSS
ACVPCPPGHYIDASTSQCTECPPNT----YLMPH----------------
--------------------------------------------------
------------------------------AAPGPDACKSCGP---SSKS
DKEHSLCYSDCHFTYTEGNATLTFDFSSLGPVGSLMNGPSFTS-------
-----------------------------------KGTKYFHHFNISICG
GKG-QLAVCTDNVTDLSITDSQREK-EGPNAI------------------
TTFICQSTIIPASGRGFHTALSSQSINLADTF--VGAT-VDDNLEGISVT
PDLFPK-TSKKVPDVNFYYRSLDTTSSCELGRSVVVRLRCNPDKSTTGEL
SVPSQCPAGTCDGCTFQFLWESSGACPTCTERDYHQIEGVCKGGN-QDLL
YVWNEPKLCMGGVTLPAKKTQACE---------GIEFWIQLGAGLGAFTA
VLLVFLTCYFWKKNK--RLEYKYSRLVMSANKECEMPVADSCAVMEGENE
ADMEDEVVYT--KPSLFGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKRN-GDNYEN---------VQLNSAHSKTL---VWS---
*
>P1;ENSDARG00000004386

MEKR-----------A-LWSSCYIVRFVTLF----------LCARASGN-
---------LPQ---CKETDYYFEYTECDSTGSRW---------------
---RVAIPHRQESCTGLPEPVRGTDCTFSCEAGEFLEMSSQQCISCAAGS
YSLGSGVRFDQWDSIPAGFSSLATYMDSGGSGD-ESM---TCNN----SS
WTAQGT--------------------H---LESNRDDCTVSLVYAVH---
-LMKQGSVSFDYQ------------------------------YVD----
-SNVFFEFFIQNDQCQEMDQ-QGSEKWIKLTTSGE-WGTHTVNLK---SG
TNILYWRTTGMLLGGKPVKPVLLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCR
PGTFSKTPGS------------------SS-----CDLCSRNTYSGKGAS
SCTHCT-ESQYSQEGWSQCKERPPCSE------KDYFQIHTACDSEGKTQ
ILYR-WVEPQVCLE-NVTGAVKLPPSGEKEDCPPCNPGFYMHNSSTCLPC
--PQ----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GTYSDGTTECQRCPGGTEPSLGYEYKWWNVLPRNMKTS
CFNVGNSKCDEMNGWEVAGDHIRSGV---------------GGSDNDYLI
LNLRV------------PGFKLPTS-------------------------
-------VDDASATEFGRITFIFETNCSA----DCELYFMIDVNRKSTNV
V-------ES---------WVGNIVRRAYTHIM-TKNASVSYT-WAFQRT
NKATDVRQYVNDIAKIYSITVTNA---MDGSASGCHACAMM---SQQDGS
SCVPCPAGHFINKDTNQCQECPPNT----FLYGH----------------
--------------------------------------------------
------------------------------HIYGHEACQPCGP---GSKS
NKEHSVCFNDCTFSHMDQNRTLNYDLSALSSVGSIMNGPSFTS-------
-----------------------------------KGTKYYHQFNISLCG
AEGRKVAVCTDNVTDMSSKDLQNESADLNNFV------------------
ETFVCQSTIIPADGRGFRSALSSQSISLADTF--LGAS-VESSLDGVTVN
SDLFLK-SSQKVPDINFFYRSPQPTASCLNGRSTVVTLHCSPEKSARGEL
TVPIKCPAGTCNGCEFHFLWESSSACPLCTEADYHSIEGACKGGQ-QDTL
YVWNEPKLCTKGVALPNKSSAHCE---------VVSLWVKAGIGGGAFMA
VLLVSLTCYFWKKNK--RLEYKYSRLVMSANKDCELPAADSCALAEGEGE
-ENEDDVVYSN-TPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKAD-GDNSES---------VQLKSSQSERW---VWG---
*
>P1;ENSTRUG00000014368

QRSTMR-------ASAWFVASCALI-LCT----LR------LTNAA-KG-
---------RRQ---CGEKDYYYEYTECDSTGTRW---------------
---RVAIPQLPGDCAGLPEPVRGTECTFSCKAGEFLEMSAQQCTQCAAGS
YSLGSGVRFDQWDSMPAGFSSLATSLESGSRGD-GRL---SCNSWRRSSS
WLPQGN--------------------Y---LMSNRDECTVSLIYAVH---
-LKKQGSVSFEYQ------------------------------YPD----
-NNLLFEFFIQNDQCQEMDQ-SSEAKWLKLTNHGE-WATHTVNLK---SG
TNILYWRTGGVLMGSKVLKPVFLKNIQIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCK
PGTFSSVPGS------------------SA-----CVPCPRDTYSGHGAS
SCTPCDTATQYAGDGSAMCKDRLPCSK------KDYFQIHTACDQEGKTQ
VMYK-WLEPKICLE-GVSGAEPLPPSGDREPCPPCNPGFYNNDTPTCSPC
--PA----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GSYSDGTKPCSQCPAGTEPTLGYEYKWWNVLPANMKTS
CFNVGNSKCDSMNGWEVAGDHIRSGA---------------GSSDNDYLI
LNIHI------------PGFKLPTS-------------------------
-------MSTQSGAEFGRITFEFETLCTA----DCEFYFMMDENRKSTTV
V-------ES---------WEGTKTRRSYTHVM-TKNASVSYT-WAFQRT
NTPSDLRKRVNDVARIYAISVSNA---VDGVSSGCQACALS---SQPSGS
ACVPCPDGHYIDSSTSQCTECPPNT----YLVSH----------------
--------------------------------------------------
------------------------------ATPNPDACKPCGP---ASKS
DKDHRSCYSDCHFTHPVGNATLTFDFTPLGSVGSLMNGPSFTS-------
-----------------------------------KGTKYFHQFNISLCG
GQN-QLAVCTDNVTDLSVADSQRERGEGANTV------------------
KTFICQSTIIPANGRGFHAVLSSQSITLADTF--LGVT-VENTLDGIEAV
PKQFPQ-TSKKVPDINFFYRSLEAMSSCPSGRSTVVTLRCNPEKSTRGDL
SVPSRCPAGTCDGCTFYFLWESSGACPTCTERDYHRIEGACKGQQ-QDLL
YVWTEPKLCIGGASLPKKKTVPCE---------GMEFWVQLGAGLGAFTA
VLLVSLTCYFWKKNK--RLEYKYSRLVMSANKECEMPGTDSCAVMEGENE
GDMEDEVVYS--KPSLLGKLKAI---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ASKGK-RESFEH---------VQLSSSHPKAL---VWS---
*
>P1;ENSDARG00000042213

RQAMERTRSIIVRHRERFIRNCLGW-IFWVFILNA------FVASS-VN-
---------LRQ---CKETDYYFQYTECDSTGSRW---------------
---RVAIPLNPGECTGLPDPVKGTDCTFSCKAGEFLEMSAQECTQCAAGT
YSLGSGLRFDEWDDIPSGFSSLATNPDNSANED-NST---SCSS----AK
WAAQGS--------------------Y---LESNRDECTVSLIYTVH---
-LKKPGSVSFDYQ------------------------------YVD----
-NSIFFEFFIQNDQCQEMDQ-DSSNKWIKLTNHGE-WGAHSVNLK---SG
TNILYWRTTRILLGSKAVKPVLLKNIWIEGVA------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------YTSECFPCK
PGTFSHSPGS------------------SS-----CDSCQRDTYSGRGAS
SCTPCNTKTHYASEGSAMCKTRPPCTE------KDYIQTYSTCDSDGKTR
AIYK-WVEPQICLD-SAPDAVTLPPSGQRKPCPPCNPGFYNNDTATCSPC
--PP----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------GSYSDGVKACQPCPAGTEPVLGYEYKWWNVLPANMKTS
CFNVANNNCDGLNGWEVAGDHIQSGA---------------GRSDNDYLI
LTLRV------------PGFKLPLS-------------------------
-------VRAASGSEFGRITFEFETSCKA----DCEFYFMMDVNKRITNV
V-------ES---------WEGSKAKQSYTHIM-TENTSASFT-WAFQRT
SQASDVRQYANDVVKIYSITVSNA---MDGVASACRACALQ---SQQAGS
SCVPCPAGHYIDKETNQCHECPPNT----VLSGH----------------
--------------------------------------------------
------------------------------HIYGKEMCQPCGP---GSKS
NKEHSVCFNDCSFTHTDHNQTLQFDFSALASAGFIMNGPSFTA-------
-----------------------------------KGTKYYHLFNISLCG
AEGH-KAVCRDNVTELSNEDTEGG--QSGSSV------------------
DAFLCQSTIIPSDGRGLRTALSSQSISLADTF--QGAT-VEKSLNGVTAR
PELFPSPSSEKIPDVHFFYRSPQVTASCQRGRNAVVSLRCNPEKTERGEI
SVPSACPAGTCDGCTFLFLWESSSVCPRCTEADYHAIEGACKAGV-QDTI
YVWTEPRLCTSGLTLPLKRTSPCE---------AIDFWLKVGAGLGAFCA
ALLVSLTCYFWKKNK--KLEYKYSKLVMSANKECELPAADSCAIMEGEAE
--EEEEAVYAK-KSSLLAKLKAA---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------ATKGN-KMSTEA---------VQLKFSNTDKS---VWG---
*
>P1;ENSLOCG00000014740

MVALSL---------KICVRQCNVV-KTM-----Q------FEPST-AVY
DACRIIRERVPEAQTGQASDYGLFLSDEDPRKGIWLESGRTLDYYMLRNG
DILEYKKKQRPQKIKMLDGAVKTIMVDDSKTVGELLVTICSRIGITNYEE
YSLIQEVVEEKKEDGTGTLKKDRTLLRDERKMEKLKAKLHTDDD----LN
WLDHSRTFREQGVDENETLLLRRKFFYSDQNVDSRDPVQLNLLYVQARDD
ILNGSHPVSFDKACEFGGIQAQIQFGPHVEHKHKPGFLDLKEFLPKEYIK
QRGAEKKIFQEHKNCGEMTEIEAKVKYVKLARSLRTYGVSFFLVKEKMKS
KNKLVPRLLGITKDSVMRVDEKTKDVVQEWPLTTVKRWAASPKSFTLDFG
EYQESYYSVQTTEGEQISQLIAGYIDIILKKKQSKDRFGLEGDEESTMLE
ESVSPKKSTILQQQFNRVGRVEHGCVALPAVMRSGSSGPESFNMGSMPSA
QQQIMTGQMHRGHMPPLSSAQQALMGTINTSMQAVQQAQADLSEVDNLPP
LGQDMASRVWIQNKVDESKHEIHSQVDAITAGTASVVNLTAGDPADTDYT
AVGCAITTISSNLTEMSKGVKLLAALMEDEVGSGQDLMRAARTLAGAVSD
LLKAVEPASGEPRQTVLTAAGSIGQASGDLLRHIGESETDERFQDVLMNL
AKAVANAAAMLVLKAKNVAQVAEDTVLQNRVIAAATQCALSTSQLVACAK
VVSPTISSPVCQEQLIEAGKLVDRSVEGCVKACQSATEDGELLQQVSAAA
SVVSQALSDLLQHVRHYASRGEPIGRYDQATDTIMTVTESIFSSMGDAGE
MVRQARVLAQATSDLVNAMRSDAEAEIDVDNSKKLLAAAKLLADATARMV
EAAKGAAANPENEDQQQRLREAAEGLRVATNAAAQNAIKKKLINRLENAA
KQAAAAATQTIAASQNAAASNKNTAAHQQLVQSCKAVADHIPQLVQGVRG
SQAQPEDLSAQLALIIASQNFLQPGSRMVTSAKSAVPTVTDQAAAMQLGQ
CAKNLATCLAELRTAAQKAHEACGPMEIESALTAVQTLKNELQDAKMAAA
EGQLKPLPGESLEKCAQDLGSTSKAVGSSMAQLLTCAAQGNEHYTGVAAR
ETAQALKTLAQAARGVAASTVDPQAAAAMLDSARDVMEGSAMLIHEAKQA
LVSQGDAESQQRLA-QVAKAV----SHSLNNCVNCLPGQKDVDMALKSIG
EASKKLLVDSLPPSTKSFQEAQSELNQAAADLNHSAGEVVHASRGTSSEL
AVASGKFSEDFDEFLDAGIEMAGQTQCKEDQIQVIGNLKNISMASSKLLL
AAKSLSVDPGAPNAKNLLAAAARAVTESINQLITLCTQQAPGQKECDNAL
RELEAVKGMLDNPNEPISDLSYFDCIESVMENSKVLGESMAGISQNCKTG
DLPAFGECVSVASKALCGLTEAAGQASYLVGVSDPNSQAGHQGLVDPIQF
ARANQAIQMACQNLVDPASSPSQVLSAATIVAKHTSALCNACRLASSKTA
NPVAKRHFVQSAKEVANSTANLVKTIKALDGDFSEENRDKCRVATTPLIE
AVENLTAFASNPEFASVPAQISNEGSAAQEPILRSARAMLDSSANLIKTA
RSLVINPK--DPPTWSILAGHSRTVSDSIKSLITSIRDKAPGQRECDYSI
DNINKCIRDIEQASLAAVSQNLPTRDDISLEPLQDQLTSAVQEIGHLIDP
ISTAARGEAAQLGHKVTQLASYFEPLILA----SVGVASKILDHQQQMTV
LDQTKTLAESALQMLYAAKEGGGNPKAAHTHDA-IAEAAQL---------
-----MKEAVDDIMVT----LNEAASEVGMVGGMVDSIAEA---MGRLDE
GTLPEPEGSFVDYQTTMVKYSKAIAVTAQEMMTKSVTSPEELGGLASQVT
TDYGHLAHQGRLAAATAEPEEIGFQIKTRVQELGHGCIFLVQKAGALQIS
PTDSFTKRELIECARAVTEKVSMVLSALQAGNKGTQACITAASAVSGIIA
DLDTTIMFASAGTLNSENEESF-------------------ADHRENILK
TAKALVEDTKMLVAGAASSQDKLAQAAQSSAKTITQLTDVVKLGAASIGS
DDPETQVVLINAVKDVAK-----ALAELIGATKSAAGKPADDPSMYQLKS
AAKLYKGTRITATGHGSAP-VS--DTNIKDIL--VMVTNVTSLLKTVKAV
EDEA-----------TRGTRALEATIECIKQELTVFQSKEVPERTSTPED
FIRMT-----------------KG----ITTATAKAVAAGNSARQ-EDVI
STANLSRKAISDMLLTCKQAACHQEVSEEVRNRALHFGTECTVGYVELLE
HVLVVLQKPTPELKQ--QL-AVFSKRVAGAVTEL----IQAAEAMKGNEW
VDPEDPTVIA--ETELLGAAASIEAAAKKLEQLKPRAKPKQADENLDFEE
QILEAAKSIAAATSALVKSASAAQRELVAQGKVGSIPANAVDDGQWSQGL
ISAARMVAAATSNLCEAANASVQGHASEEKLISSAKQVAASTAQLLVACK
VKADQDSEAMRRLQAAGNAVKRASDNLVRAAQKAAFDKADDDAVVVETKF
VGGIAQIIAAQEE-MLRKERELEEARKKLAQIRQQQYKFLPTELRGDEN
*
