>P1;ENSTNIG00000002563

---------------------MADPD-LDFQTGESGASATFPMQCSALRK
NGY------------VLLKGHPCKIVEMSTSKTGKHGHAKVN-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDMC----------PSTHN-MDV
PSIKR---------------------TEYQLLNITDDYMTL---------
------------------------------MSDNGDIREDL---------
-----------RVPDNEVGKEIMTKFQANEEF--------------YVSV
MS------AMGEECAIGTKTMGNK-------------
*
>P1;ENSAMXG00000004061

---------------------MADPD-LDFTSGDAGASVTYPQQCSALRK
NGF------------VVLKGRPCKIVEMSTSKTGKHGHAKVH-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDIC----------PSTHN-MDV
PNIKR---------------------NDFQLVDINEGFLSL---------
------------------------------MMDNGDVREDL---------
-----------RVPDGDLGKEIESKHGAGEDM--------------MITV
LS------AMGEEAAVGIKAFT-K-------------
*
>P1;ENSGACG00000012551

GSLNCHLTHRGSSKSPLTHRTMSDPD-LDFTVGESGASATYPMQCSALRK
NGY------------VVLKGHPCKIVEMSTSKTGKHGHAKVN-------L
V-----GIDIF---------------------------------------
----------------------TNKKHEDMC----------PSTHN-MDV
PSIKR---------------------LDYQLVNINDGYMCL---------
------------------------------MSDTGDIREDL---------
-----------RVPDSEIGREIEGKFEAGDEF--------------MVTV
IA------AMGEECAVATKVLA-G-------------
*
>P1;ENSORLG00000011487

---------------------MADD---DFSTADAGASTTFPMQCSALRK
NGF------------VMLKGRPCKIVEMTTSKTGKHGHAKVH-------L
T-----GLDIF---------------------------------------
----------------------TQKKYEDIC----------PSTHN-MDV
PNVIR---------------------KDYQAIDVSDGFLSL---------
------------------------------MDDNGETREDL---------
-----------KVPEGDLGKEIIKKISNGELF--------------MVSV
LK------AVDEEQIVGTKNMT-S-------------
*
>P1;ENSORLG00000002907

---------------------MADPD-LDFTTGESGASATYPMQCSALRK
NGY------------VVLKGRPCKIVEMSTSKTGKHGHAKVN-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDMC----------PSTHN-MDV
PSIKR---------------------IDYQLVNINENYMSL---------
------------------------------MSDNGDIREDL---------
-----------RVPENEVGKEIEAKFEAGEEF--------------MVTV
IS------AMGEECAVATKVLASK-------------
*
>P1;ENSXMAG00000009045

---------------------MADD---DFSTADAGASATFPIQCSALRK
NGF------------VMLKGRPCKIVEMSTSKTGKHGHAKVH-------L
T-----GIDIF---------------------------------------
----------------------TAKKYEDIC----------PSTHN-MDV
PNVIR---------------------KDYQVLDIIDGFLTL---------
------------------------------MEDNGETREDL---------
-----------RLPDGDMGKEIVKKLESGDQF--------------LVKI
-------------------------------------
*
>P1;ENSDARG00000056186

---------------------MADLD-TDFTSGDAGASLTFPMQCSALRK
NGF------------VVLKGRPCKIVEMSTSKTGKHGHAKVH-------M
V-----GIDIF---------------------------------------
----------------------TGKKNEDIC----------PSTHN-MDV
PNIKR---------------------QDYQLVGIIDGYLSL---------
------------------------------MKDNGDLRDDL---------
-----------KLPEGDLGKEIESKFESGDEF--------------LVSV
LA------AMGEECPIAIKPMS-S-------------
*
>P1;ENSGACG00000010995

---------------------MADE---DFECGHSGASSTFPQQCSALRK
NGF------------VMIKGRPCKIMEMSTSKTGKHGHAKVH-------L
T-----GLDIF---------------------------------------
----------------------TQKKYEDIC----------PSTHN-MDV
PHVTR---------------------KDYQVIDVADGFLSL---------
------------------------------MDDGGATREDL---------
-----------KLPEGDIGKEIEKKFDNGDNF--------------MVTV
LK------ALDEENVVATKAQ--N-------------
*
>P1;ENSTRUG00000011948

------------------PITMSDD---EYQPVGSGASETYPAQCSSLRK
NGH------------VMLKGRPCKIVNMTTSKTGKHGHAKVH-------L
T-----GIDIF---------------------------------------
----------------------TSKKYEDIC----------PSTHN-MDV
PNTRR---------------------KDFQVISENEGYLHL---------
------------------------------MDDEGNVREDL---------
-----------RIPEGDLGKEIQAKLTNDDEF--------------MVTV
LT------AMGEEAIVTIKNTQ-K-------------
*
>P1;ENSXMAG00000012044

---------------------MADPD-LDFTTGESGASATYPMQCSALRK
NGY------------VVLKGRPCKIVEMSTSKTGKHGHAKVN-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDMC----------PSTHN-MDV
PAIKR---------------------TDYQLVNIAESYMSL---------
------------------------------MSDNGDIREDL---------
-----------RVPESDIGKEIESKFEGGEEF--------------MVTV
IS------AMGEECAVATKVLASK-------------
*
>P1;ENSTRUG00000003482

---------------------MADPDGFDFQTGESGASATFPMQCSALRK
NGY------------VLLKGHPCKIVEMSTSKTGKHGHAKVN-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDMC----------PSTHN-MDV
PSIKR---------------------TEYQLLNIADDYMTL---------
------------------------------MSDNGDIREDL---------
-----------RVPENEVGKEIMGKFQASEEF--------------YVSV
MS------AMGEECAIGTKTMGNK-------------
*
>P1;ENSONIG00000000879

---------------------MADD---DFSTADAGASTTYPMQCSALRK
NGY------------VMLKGRPCKIVDMSTSKTGKHGHAKVH-------L
T-----GLDIF---------------------------------------
----------------------TQKKYEDIC----------PSTHN-MDV
PNITR---------------------KDYQVLDVADGFLAL---------
------------------------------MDDNGETREDL---------
-----------KLPDSDLGKEIEKRFTNGDQF--------------MVSV
LK------AIDEEHVVGTKTMT-S-------------
*
>P1;ENSONIG00000017664

---------------------MADPD-LDFQTGESGASATYPMQCSALRK
NGY------------VVLKGRPCKIVEMSTSKTGKHGHAKVN-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDMC----------PSTHN-MDV
PSIKR---------------------IDYQLVNINENYMSL---------
------------------------------MSDNGDIREDL---------
-----------RVPDNEVGKEIESKFEAGEEF--------------MVTV
IA------AMGEECAVATKVLASK-------------
*
>P1;ENSDARG00000017235

---------------------MADPD-LDFASGDAGASATYPMQCSALRK
NGF------------VVLKGRPCKIVEMSTSKTGKHGHAKVH-------L
V-----GIDIF---------------------------------------
----------------------TNKKYEDIC----------PSTHN-MDV
PNIKR---------------------NDYQLVDISEGFLSL---------
------------------------------MMDNGDVREDL---------
-----------RVPDGDLGKEIENKFAAGEEM--------------LVTV
LS------AMGEESAVALKPMT-K-------------
*
>P1;ENSTNIG00000006661

-----------------------DE---DFEGGKSGASETYPAQCSSLRK
NGF------------VMLKTCPCKIVEMTTSTTGKHGHAKVH-------L
T-----GVDIF---------------------------------------
----------------------TGKEYEDIC----------PSTHN-MDV
PHVVR---------------------KDYTLVDVTDGFVHL---------
------------------------------MDDDGSIREDL---------
-----------KLPESELGKDIKTKFDNGEEL--------------MLTV
LK------GVGEEQVIGIKGAG-K-------------
*
>P1;ENSLOCG00000011556

---------------------YSCT----FLS-PSLKDREIMRVCWLVRK
DGCHAPIRLPHLQTVILGRGPETTIVDKKCSREQVHLRADYNKGYITVKQ
LGVNPTSVDLVEVGRGNEVSFRPGQLLHVVNQLYAYTVQFSPEETSGSKR
PHQPRVENRTSDGRAPSRKIPRTGEPEENSDPSSYERLHVSPAPKNPADA
PEKKQIQGHWSQGLKASMQDPKMQVYKDEKVVVIKDKYPKARYHWLVLPW
ESISSLKALRREHAGLLRHMHSVAEKMVRDCPDSGSLQFRLGYHAIPSMS
HVHLHVISQDFDSPCLKNKK-HWNSFTT-DYFLESQAVMEMLEQNGTVTV
QDGISELLKLPLRCHVCQKDMPTIPQMKLHLKSHLPR
*
