>P1;ENSDARG00000089790

FYLVPGFR-LCFWSQVTICGQLPSKPITPEKPSIQRGKKHTKVWNHLRKS
KWFYRGDYHIDVCINDYLDVYCPHYMDTVPEERTERYVLYMVNYDGYSSC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STLAENGRRSCLRLKVFVRPTNNCDKS---HDRVDKFDDRSINSIENNND
GTSHESAEPSRSD-VNSAG-RVQTVGPLLASVLVLLASLS----SL----
--------------------------------------------------
---------------
*
>P1;ENSXMAG00000015959

MLQVEMVLFVCLVLLMCVLSQEPGSKVV--------ADRYAVFWN--RTN
AKFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVAPNGKKTCLKLKVFVRPSNSCLKT----DRVFDIDDRVESTL-PR-D
ETSHETAAPSRSE-TNAAQ-RLQKTSSLLALLLVTLVGLF----T-----
--------------------------------------------------
--------------L
*
>P1;ENSDARG00000098625

-------------------------------------------WS--VLF
CRFQRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SMITETGRRSCLKLKVFVRPPNGCEKTIGVHDRVF-VDDKVDNALEPR-D
DTSHE-AEPSRSD-VSTSGLRHQTSRPLLALLLLCISLYL----LL----
--------------------------------------------------
---------------
*
>P1;ENSTRUG00000015156

------------------KNVKKQRKCL--------GASYPTTD---ERR
HRFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVAENGRKTCLKLKVFVRPSNSCTKTI--HDRVFDVNDKVDNTLEPR-D
DTSHDPAEPSRSDETNAAL-QLQKTSPILALLL-GLGQLR----ELPPMG
GLLCDGRISAVSLYGMRMNSKTCNRKKTKKQKKICLKRLVFCSCVVLAHF
HYVWVGFYFCWCCCI
*
>P1;ENSORLG00000003965

---------------MCVFSQEPGSKVV--------ADRYAVFWN--RTN
TKFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIAQNGRKTCLKLKVFVRPSNNCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHETAAPSRSE-TNAVS-HLHKTSPLLASLLVSLAALF----T-----
--------------------------------------------------
--------------L
*
>P1;ENSTRUG00000012828

LLFQRMMLFFLYLITSTI-MSIPWQNTF--------QSHYI--FR--SSK
QIFYRGDYHIDVCINDYLDVYCPHYTGAVPDERAERYILYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SITDRKGRRSCLRLKVFVRPQNNCIKHSGSTQEAVEFEDNSHNSLEPR-D
GIGHESPEPARRD-VNSAS-RYHTSVLLLSSLL---AAVL----SV----
--------------------------------------------------
---------------
*
>P1;ENSAMXG00000009088

MPQVGVLVFLALLLWMCVLGQEPASKVV--------ADRYAVYWN--RTN
PRFYRGDYHIDVCINDYLDVYCPHYLESVPEERTERYMLYMVNYDGYSSC
DHTATGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVGENGRRTCLRLKVFVRPANNCVKTVSVHDRVFDVNDRVDNSIEPR-D
DTSHESAEPSRGD-VNSAG-SVRLDVLLLASALLLVASIVSSSSSL----
--------------------------------------------------
---------------
*
>P1;ENSORLG00000013262

--------------------------------------------------
------DYHIDVCINDYLDVYCPHYASPVSDDRAERYVLYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SVSDVRRRRSCLRLKVFVRPQNNCVKNPGSEQEGVDFEENNHNSLEPR-D
GISHESPEPSRTD-VNSAG-RHQYTMLPLSSALMLLAAIM----SL----
--------------------------------------------------
---------------
*
>P1;ENSXMAG00000005010

MPQVDMILFLILIIGMCVFGQDPASKVV--------SDRYAVFWN--RTN
PKFYRGDYHIDVCINDYLDVYCPHYASPVSDDRAERYVLYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SITDDRGRKNCLRLKVFVRPQNNCVKNSGSSQEGVEFDENSHNSLEPR-D
GINHESPEPARQD-VNAAG-RRQFSILLLSSALMLLAAIL----SL----
--------------------------------------------------
---------------
*
>P1;ENSTNIG00000016669

--------------------------------------------------
-RFHRGDYHIDVCINDYLDVYCPHYDDSVPEERTERYVLYMVNYDGYSTC
DHTSKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIVENGRKMCLKLKVFVRPSNSCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHEPAEPSRSDETNAAS-QLQKSSPFLALLLVCLLSFL----T-----
--------------------------------------------------
--------------L
*
>P1;ENSAMXG00000021030

MLQVEMIIFVCLILWMCVFSQEPSSKVM--------ADRYAVYWN--RTN
PRFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DDTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SMVTETGRKGCLKLKVFVRPANSCVKIIGVHDRVFDVNDKVDNSLEPR-G
--------------------------------------------------
--------------------------------------------------
---------------
*
>P1;ENSGACG00000006791

--------------------------------------------------
------DYHIDVCINDYLDVYCPHYEETVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIAENGRKTCLKLKVFVRPSNSCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHEPAEPSRSDETNAAP-HLQNTSPVLALLLLCLSALF----T-----
--------------------------------------------------
--------------S
*
>P1;ENSONIG00000015197

MLQVEMVVFVCLVLLMCVFSQEPSSKVV--------ADRYAVFWN--RTN
TKFHRGDYHIDVCINDYLDVYCPHYEDTVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVAENGKKTCLKLKVFVRPANSCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHEPAEPSRSE-TNDVP-RLQKTSPLLASMLICLAALS----T-----
--------------------------------------------------
--------------L
*
>P1;ENSONIG00000012804

MPQVDMILFLILIIGMCVYGQDPASKVV--------SDRYAVFWN--RTN
PKFYRGDYHIDVCINDYLDIYCPHYVGPVADDRAERYVLYMVNYDGYSSC
DHNSKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SISDDRGRRSCLRLKVFVRPQNNCVKNSGTVEEGVNFDDNSHNSLEPG-D
GVSHESPEPARRD-VNSAG-LCQTSVLLLSSTLILLAVIL----SL----
--------------------------------------------------
---------------
*
>P1;ENSGACG00000017948

--------------------------------------------------
-RFYRGDYHIDVCINDYLDVYCPHYVGPVSDDRAERYILYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SITDDKGRRSCLRLKVFVRPQNNCVKSPGTAQEGVDFDDSSQNSLEPR-G
G--------------------------------------------L----
--------------------------------------------------
---------------
*
>P1;ENSLOCG00000009155

MLHVEMLIFVFLILWMCAISQEPGSKVV--------ADRYAVYWN--STN
PRFHRGDYHIDVCINDYLDVFCPHYEDSVPEDKTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIAENGRRTCLKLKVFVRPTNSCMKTIGVHDRVFDVNDKVENSLEPA-D
DTVHESAEPSRSD-SNAAE-KTRITNLLLASVLFFLAALL----S-----
--------------------------------------------------
--------------L
*
