>P1;ENSTRUG00000010189

LG--------Q---------------------VPRRGMSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNTYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVKP----------GNNTQSSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRAEPSLLHSPSSHF-------P
*
>P1;ENSTNIG00000009086

-----------------------------------RSMSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNTYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPFKPKP--------ANNTESSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRAEPSGLPSPGSHF-------P
*
>P1;ENSXMAG00000014072

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNKYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPDQS-------NNSTVSSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRGESSILQSPSSQF-------P
*
>P1;ENSGACG00000017024

-----------------------------------FDMSPNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNSYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNCVQESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVKPK-S-------SNATISAGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRGESSILQSPSSHF-------P
*
>P1;ENSONIG00000010831

-----------------------------------FAMSLNEHSMQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLERDHKYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLKSNA------DEKNGTISSGEAAA
IASTCIMVPFGLVFIMFAVHFYRTLVSHKTDRQIRELEQVI---RLQNQL
EHRAENDDLKAA-VHF-------P
*
>P1;ENSGACG00000011865

ESD-------S---------------------QDVFGMSLNEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLERDHEYPAGLLIAFSAC
TTVLVAVHLFALMVSTCILPNLEAVSNVHNLNSVHESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLK-------------------SAAA
IASTCIMVPFGIVFIMFAIHFYRTLVSHKTDRQIKELEQVI---QLQNQL
DHRAHELCS--H-GFLGGQGGLQA
*
>P1;ENSDARG00000004154

-----------------------------------MKMSRSEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDTNHDYPPGLLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPKDQ-------KNGTVSAGVAAA
ITSTSIMVPFGLVFIVFAVHFYRSLVSHKTDRQFQELEELE---DLQNEL
DHREEVSTLQSPGSLY-------P
*
>P1;ENSDARG00000011515

----------------------------------PRTMSLNEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVECQLEEDHNYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSIKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPLSQTPVTQKENVTQAPGISEGKAAA
IASTTIMVPFALVFIVFAVHFYRSLVSHKTERQHEELEVLAKITQMQNQL
DQRGDASSIH--------------
*
>P1;ENSTRUG00000005503

-----------------------------------FVMSLSEHSMQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLEREYTYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLKNKDD----AKGNNGTLSSGEAAA
IASTCIMVPFGLVFIMFAVHFYRTLVSHKTDRQIRELEQVI---RLQNQL
DHRSETDDLKTT-VEF-------P
*
>P1;ENSONIG00000013881

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNSYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPNKS-------SNSTVSSGVAAA
ITSTSIMVPFGLVFIVFAVHFYRSLVSHKTDRQFEELEELSNLTRLQNEL
DNRGESSILQSPSSHF-------P
*
>P1;ENSAMXG00000005846

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLERDYDYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVKESPHERMHHHIELAW
AFSTVIGTFLFLAEVLLLCWVKFLPLKKDRE---PRNNDNSTVSAGEAAA
YASTCIIVPCGLVFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNQL
DHRVEGPNIQSAPGMF-------P
*
>P1;ENSXMAG00000015181

-----------------------------------VRMSLNEHSMQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLEPTHTYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLKKE---------TNTTISSGEAAA
IASTCIMVPFGLVFIVFAVHFYRTLVSHKTDRQIRELDQVI---QLQKQL
NHGAENDELKAA-GHF-------P
*
>P1;ENSORLG00000012949

-------------------------------------VMSSEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLEADHVYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHHHIELAW
AFSTVIGTFLFLTEVTLLCWVKFLPLKNNK------EVNNGTITSGEAAA
IASTCIMVPFGLVFIVFAVHFYRTLVSHKTDRQIRELEQVI---NLHNQL
DHTAENEELK-P-VHF-------P
*
>P1;ENSAMXG00000020637

-------------------------------------MS-SARSLQALTW
RRLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDTSHDYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNIEAVSNVHNLNAVLESPHERMQRYIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVRPRNQ-------KNGTMPAGVAAA
ITSTSIMVPFGLVFIVFAVHFYRSLVSHKTDRQFQELEELE---DLQNEL
DQGGDASVLQSPTSQ---------
*
>P1;ENSORLG00000008491

SSPGIKTLLDSVTACSSKRSKSQKENSDRAARTVFFNMSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNSYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHDRMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPNKS-------SNNTMSSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTKLQNEL
DNRGEASI----------------
*
>P1;ENSLOCG00000005126

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLEPNHDYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVKRNPLSPSGEHNATETISAGEAAA
IASTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNFARLQNQL
DHREAP--MQSPSS----------
*
