>P1;ENSGACG00000007189

MWQANYRRMHHLADWISGTVMGGCVGRSSMEGQ-QGSARS-STRS-KKRG
GRNEPLKKERPKWRSEYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALR
AAALAAECNDLELAQAIVDGACITVPHGSLTESYDELGNRYQLPAYTLAP
PVNLISETSSESKVSDATQKQAQPPPCRQEFQLRVRLSTGKDLRLTASMA
DSIAELKKQLEKKEEISISRQRWFFSGKLLTDKTRLQDANIQKDFVVQVI
LNMNSPVVV-------------------------------N
*
>P1;ENSTNIG00000016521

--------------------MGGCVGRSRMDA--QESDRS-VTRS-KKCG
GRNEPLKKERPKWKSEYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALR
AAALAAECNDLELAQAIVDGACITLPHGSLTESYDELGNRYQLPKYTLSP
PVNLITESSSQSKGSESAQKACQSPVCRAEFQLRVRLSTGKDVRLSASMA
DSIGQLKKQLKEQEDIDVSCQRWFFFGKLLTDQTRLQDTKIQKDFVVQVI
VNINAETIT-------------------------------K
*
>P1;ENSONIG00000019734

--------------------MGGCMGRYLEGWE-DSQSRG-SSRN-GGRG
GRNEPLKKDRPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALECNDHELAQAIVDGASITLPHGTLTECYDELGNRYQLPVYCLAP
PINLISERSDE-DPSDSPEPPV---ASKKEFQLKVRLSTGKDLRLSVSMV
DTIGQLKKQLQAQEDIDAVHQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VNPQALQAPQ-----------------PSPPTTTASSPVPE
*
>P1;ENSGACG00000004908

--------------------MGGCVGRYWEGWE-DSQSRG-SSRN-GGRG
ARNEPLKKERPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALEGSDHDLAQAIVDGANITLPHGNLAECYDELGTRYQLPVYCLAP
PINLISERCDD-DPSDSAEPPV---APKKEFQLKVRLSTGTDLRLSASMA
DTIGLLKKQLQAQEDIDTSHQRWFFSGKLLPDKTRLQDTKIQKDFVIQVI
VNPQALQGPKTPPSPTTTTTTEVGAANPSPT-ST-SSPESE
*
>P1;ENSXMAG00000013492

MWQANCRRMHNIADWISGTVMGGCVGRSRMDG--QGSAHG-STRT-KKRG
ARNEPLKKDRPKWKSEYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALR
AAALALECNDLELAQAIVDGACITLPHGSLTESYDELGNRYQLPAYTLAP
PINLITETSGDSKLSESAQKQAQPPPSREEFQLRVRLSTGKDVRLTASLA
DSIALLKKQLEKQEDIEVIRQRWFFSGKLLTDKTRLQDAKIQKDYVVQVI
VNINPSVIP-------------------------------N
*
>P1;ENSXMAG00000009567

--------------------MGGCVGRYWG----DSHNRG-SARN-GGRG
GRNEPLKKDRPKWKSEYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALECNDHELAQAIVDGASITLPHGTLTECYDELGNRYQLPVYCLAP
PVNLISECSDE-DCSDSPEPPI---ASKKEFQLKVRLSTGKDVRLNASMA
DTIGQLKKQLQAQEDIDVLQQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VNSQASGAPK-----------------PSPI-TTPSSPKSQ
*
>P1;ENSDARG00000079623

--------------------MGGCVGRERAE----TRGRG-SRTQ-RKRG
GRNEPLKKDKPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALECSDHELAQAIVDGANITLPHGSLTECYDELGNRYQLPVYCLAP
PVNLISERSEE-DLTDNPEPQT---TQKKEFQLKVRLSTGKDLRLNASMS
DTIGLLKKQLQAQEDIDIGHQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VNQPAPNH---------------------------------
*
>P1;ENSTRUG00000011970

--------------------MGGCVGRSRMDV--QGSDRR-ATQS-KKRG
GRNEPLKKERPKWKSQYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALR
AAALAAECNDLELAQAIVDGACITLPHGSLTESYDELGNRYQLPVYTLSP
PVNLITESPSETKGSASAQKQAQPPPCRQEFQLRVRLSTGKDVHMAASMA
DSIGQLKKQLEEQEDIDVSCQRWFFSGKLLTDKTHLQDTKIQKDFMVQVI
VNTNTPVV--------------------------------A
*
>P1;ENSORLG00000008611

--------------------MGGCVGRSSVDG--QGRAPG-SMRG-KKRG
ARNEPLKKECPKWKSEYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALR
AAALAVECNDLELAQAIVDGACITLPHGSLTESYDELGNRYQLPAYTLAP
PINLITETSSDCKVSDCTQKQAQASPCREDFQLRVRLSTGKDVRLTASMA
DSIAELKKQLEEREDIEVTRQRWFFSGKLLTDKTRLQDAKIQKDFVVQVI
VNINPSVI--------------------------------T
*
>P1;ENSAMXG00000003096

--------------------MGGCVGRERQESRGQGSSRG-GRSQ-RKRG
GENK-LMNEKLVWTLKLPSITNAVNTTLDQFIITAPLEQTRLGCIWRILK
SLAIGLFCNEEAVACKIITTGDLFVLKGSLTECYDELGTRYQLPVYCLAP
PVNLITERSEE-DTVDSSEPQT---TSKKEFQLKVRLSSGKDLRLNASMA
DSIGLLKKQLQAQEGIDVVHQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VNQPAPPNH--------------------------------
*
>P1;ENSDARG00000007382

--------------------MGSCFGVIRQRS--RLSSRNAPSNG-NKRG
GRNEPLKKDKPKWKSDYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALK
AAAVAIECNDHQLAQAIVDGASITLPHGSLMECYDELGNRYQLPAYCLSP
PVNLVSECNDH-NASENAEPQE---KKEKEFQLKVRLSTGKDLRLSVTMA
DSIRQLKKQLQIQEDIDTAHQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VSQP--IVT-------------------------------S
*
>P1;ENSORLG00000020311

--------------------MGGCVGRYWRGWD-ESQSRG-SSGNVRRLA
GRNEPLKRDRPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALECNDHELAQAIVDGASITLPHGTLTECYDELGTRYQLPVYCLAP
PINLISERSDE-DANESPELSA---TSKKEFVLKVRLSTGKDLRLSASMA
DTVGLLKKQL----------------------------------------
-----------------------------------------
*
>P1;ENSTNIG00000004701

-----------------------CRGSGHH-P--RARLNW-VFCL-VSFS
GRNEPLKKERPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALEGSDHELAQAIVDGASITLPHGSLTECYDELGNRYQLPVYCLAP
PVNLISERSDE-DASDSPEPPV---ATKKEFQLKVRLSTGRDLRLSASMA
DTIGQLKKQLQAQHDIDTAHQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VN---------------------------------------
*
>P1;ENSTRUG00000017108

--------------------MGGCMGRYLDGWE-DAQSRG-SSRN-GGRG
GRNEPLKKDRPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAVALECNDHELAQAIVDGASITLPHGTLTECYDELGNRYQLPVYCLAP
PVNLISERSDE-DTSDSPEPPA---APKKEFQLKVRLSTGKDLRLNASMA
DTIGQLKKQLQAQNHIDTAHQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VNPQALQ---------------------------------D
*
>P1;ENSAMXG00000012889

--------------------MGVANSR----------DA-YTSVT-VLLK
RRNEPLKKDKPKWKSDYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALK
AAAVAIECNDHELAQAIVDGASITLPHGSLTECYDELGNRYQLPAYCLAP
PVNLILERSDI-DVSENAEQQE--KKEKEEFQLKVRLSTGKDLRLSVSMA
DSICQLKKQLQVQEDIDAANQRWFFSGKLLTDKTRLQDTKIQKDFVIQVI
VKPA--VIP-------------------------------S
*
>P1;ENSONIG00000009526

MWQANCRRMHNLADWISGTVMGGCVGRSRMDG--QGSARS-STRS-KKRG
GRNEPLKKERPKWKSEYPMTEGQLRSKRDEFWDTAPAFDGRK-EIWDALR
AAALAAECNDLELAQAIVDGACITLPHGSLTECYDELGNRYQLPAYTLAP
PVNLITETSSDSKVSESTQKQSQPSPSREEFQLRVRLSTGKDVRLTASMA
DTIAELKKLLEEQEEIDICRQRWFFSGKLLTDKTRLQDTKIQKDFVVQVI
VNINPSVIT-------------------------------N
*
>P1;ENSLOCG00000003833

-------------------VMGGCVGRERGSS--QGSGR---SGA-RKRG
GRNEPLKKDKPKWKSDYPMTEGQLRSKRDEFWDTAPAFEGRK-EIWDALK
AAAIAIECNDHELAQAIVDGASITLPHGSLTECYDELGNRYQLPVYCLAP
PVNLITERSEE-EPVENPEPLV---IPKKEFQLKVRLSTGKDLRLSASMA
DTIGQLKKQLQVQEDISPAHQRWFFSGKLLTDKTRLQETKIQKDFVIQVI
VNQP--AIT-------------------------------N
*
