>P1;ENSTRUG00000002503

-----------------------------------------MKIPLWYLV
VLLACLFTPGRSDCQGECVACGLLMQQQ-LQQAFNTMV-CLLECEGRVSG
SLTWEVCQHVMKVP-RDPTPPVGGVASSRTGEELGLTS-FEL--------
---LESAAAESFQDGDQ----DEASFE----QRSVQYDSAL---------
--------LGS---S--EEGEGTQGR---HEERQPREALALSKRFGGFQR
GRHGYRKLIGSPMRPLQKRYGGFIGVRKSARKWNSQKRVN--QLLRQYLG
M--RSSRSGRFN-VP-MTRL-WMQN--
*
>P1;ENSDARG00000025024

GNKQKLAKGEYKRLYIQQICSGQVPEPHTAQTVLQLLTHFVMKAPLWTL-
-LLLGLCNPAWCDCQKDCLFCSQKLPNE---YAFNNLV-CLVECHGKLSP
GDTWEMCRRTIVEQKPKALLSVEGSILKRAEEEPDTSLPVDQ------DD
--EQLSETLQRFDHITRALGADDQD-----RQLSKKYKF---------LQ
VQ-----SAQ---E-SE-EERDGDSEI---EGDEQESAIHLIKRFGGFLK
NKYGYRKFI-DPGRSLQKRYGGFIGVRKSARKWNNQKRFS--EFLKQYLG
M---SSRASEYN-SM-SADL-TQQN-E
*
>P1;ENSORLG00000014513

-----------------------------------------MRTVV-AL-
-LFLCLCDPGHSDCQADCLSCNNILSKH---LSFDPTV-CLIECEGNLSP
SFYWNFCQTTLTSP----ISTINSSIKKRSREEAEALFPKEDE----QME
EDLLLPLALQRFDHVTRALGINEKDLGDESNQLNTAYKS---------LN
ALSLENEYD----E-----QEGEDA-N--VAGREK-GDAGFSKRFGGFVK
GRHGYRRLM-SPGRSYQKRYGGFIGIRKSARKWNNQKRFS--EFLKQYLG
M---STRATEFN-SL-SEDL-TEQNEV
*
>P1;ENSONIG00000001305

-----------------------------------------MKIPLWCLV
VLLACLFTPGRSDCQGQCMTCGLLLQQQQLEQTFNTMV-CLLECEGRISS
SLTWEVCKRAVKLS-LHPTLSEGGALFKRTGEELELTS-LDL-----NSD
SELVQSTAAERFQEGDR----DETPFE----VRSVHLTDE----------
--------EQK---PREERNVESDGQLE-ANEGESSEGITLSKRFGGFQR
GRHAYRKLLGSSMRPLQKRYGGFIGVRKSARKWNSQKRVN--QLLRQYLG
M--RSNRSGRFN-PMPMSRL-WRQHKL
*
>P1;ENSAMXG00000009761

L-----------------------------------LCKEAMKTPLWTL-
-LLLSLCAPGHSDCQGDCLTCGLLLPPQ---QAFNTLV-CLLECEAQASP
AHTWDLCKRAVGLN-SPALPPEEGAVSKRSENEADEMEPLAMVS--VEND
GSVEFSEALERFRHAAQALGSS----------YEAQL-------------
----DSQMQE-----E--AEQGQNMNA--EEEQDGSNGIDLSKRFGGFLK
GRHGFRKLV-GSGRPLQKRYGGFIGIRKSARKWNNQKRVS--QLLRQYLS
LTARSGRSGRFN-NL-STAVVRQKNEV
*
>P1;ENSGACG00000014805

-----------------------------------------MKTVV-AL-
-LLLCLCDPGQSDCQADCVSCSNMLPRQ---LSFNPMV-CLTECEADVSP
NFFWDFCGKVLSSP----ISTLAGTIQKRSREEVEALFSEEEEEE-EPLK
EGLLLPFAPQRYNPMTRALGLDERHQL------NTAHNA---------PN
APSLEDEYEE---D-AG-QEEGGATDM--AAGGQDGAGLSVFKRFGGFVK
GRHGYRKLI-SPGRLYQKRYGGFVGIRKSARKWNNQKRFS--DLLKQYLG
R---SAKATELN-SV-SKDL-DQQNEV
*
>P1;ENSONIG00000003025

-----------------------------------------MKTVV-AL-
-LLLCLCDPGQSDCQADCLSCNNILPKQ---LSFNTMV-CFIECESSVSP
SSSWDLCREALLSQ----ILSPSGSVWKRSQEEVEALFPGEDE----QMK
GRLFLPIALQRVDHVTHGLDAEERDLGGKGNHLNTAYNS---------QN
AMSLEDEYAE---E-EE-GQEGGDP-D--VAAGQG-DAALISKRFGGFVK
GRHGHRRLM-SPGRSYQKRYGGFVGIRKSARKWNNQKRFS--EFLKQYLG
M---STRATEFN-SV-SEDL-TQQNEV
*
>P1;ENSORLG00000016198

-----------------------------------------MKIPLWCLV
VLLACLFSPGHCDCQGECVACGLLLQQHQLQQAFNTIV-CLLECEGHASS
SLTWEVCKRALKH---QETLQEGGAFLKRGGEQDQDLDDADL-----R--
-SVQYDSSLQESSEEVQ----SL----------DPRLEGK----------
--------EET---QRDDRDVKGQSEM--DEDNDSLQVVSLSKRFGGFQR
GRHGYRKLIGSPMRPLQKRYGGFIGVRKSARKWNSQKRVN--QLLRQYLG
M--RSSRSGRFN-AS-MNRA-WRQNKL
*
>P1;ENSGACG00000004461

-----------------------------------------MKIPVWYLL
VLLASVFTPGRGDCQGECVACGALLQQQQLPQAFNALV-CFLECEGGVSS
SFTWEVCQRAMKLS-RRPSLPGGGAVLGRTGEGLELTY-LDM-----NPD
SQLPQSAAA-----AEQ----DGAPFE----QRSAPYDSSL---------
--------LES---Y-----GQPEG----LRGQEASGAVTLSKRFGGFQR
GRHGYRKLIGSSMRPLQKRYGGFIGVRKSARKWNSQKRVN--QLLRQYLG
L--RSSRSGRVGYAP-VTRV-WRQNQL
*
>P1;ENSAMXG00000018464

------------------------------------VTQCRMKTPLWTL-
-LLLGLCVPGHSDCQKDCLFCGQILPKD---LTFNTLV-CLVEC-GKASP
GLNWEMCRTAMEEG-PQASLSVGGTMLKRAEEEVESVLPLEQ------SD
GGLVYSNALQRFDHVARAMGLDQLGRESQSTQYSASYQS---------QQ
SQ--QSQSAE---GDGE-DEEDGGREM---ENDQDGAPVNLTKRFGGFLK
SKYGYRKFM-DPGRSLQKRYGGFIGVRKSARKWNNQKRFS--EFLKQYLG
M---TTRASEFN-SV-STGI-AQQNEV
*
>P1;ENSTRUG00000005668

-----------------------------------------MKTVL-VL-
-LLLCLSDPGQSDCQADCLSCSNILPRH---LSFNAKE-CLTQCEGDVPS
SSYLDFCRKTLSAQ----ISSISRMMQKRAKEEVEALFPEEEKEVVGHLE
GDLLLPVELQRFDDMTQALRVDERSLG---------------------GN
TLSIDDKYEE---E-AE-QE-EGPSDM--AAGGQGDYGLALSKRFGGFVK
GRHGYRKLV-YPGRSYQKRYGGFIGIRKSARKWNNQKRFS--EFLKQYLG
M---SARATEFN-SV-SEDL-GQQDEV
*
>P1;ENSTNIG00000019171

-----------------------------------------MKIPLWYLV
VLLACLFTPGRSDCQGECAACGLLMQQQ-LQQAFNTMV-CLLECEGHVSG
SLTWEVCRQAAKVP-RYPALTGGGAESSRTGEELDLTS-FDL-----DAG
NELLESAAARSFQAGDP----EEVPFE----PRGVPYDSSL---------
--------LEQ---PREERYAGGNGQLK-TDEGDTREATALSKRFGGFQR
GRHGYRKLIGSPVRPLQKRYGGFIGVRKSARKWNSQKRVN--QLLRQYLG
M--RSSRSGRFN-VP-VTRP-WRQNKL
*
>P1;ENSXMAG00000011640

-----------------------------------------MRTVV-AL-
-LLLCLCDPGRSDCQTDCLSCSKILPKQ---LSFNTVV-CLIGCKSSASP
SSPWDICRKALPS------SSSDGTVRRRSQEEADILLPEGEE----QMD
GGLFLPMALQRFNHMTRALDLNDRGLVSQSSQLSSLYGS---------QD
ALSLADEYEE-DEE-EA-GQEGEDAGK--AAIGQDDPEPSISKRFGGFVK
GRHGYRKLV-SPGRSYQKRYGGFIGIRKSARKWNNQKRFS--EFLKQYLG
M---STRSSEFN-SV-SGEL-TQQNEV
*
>P1;ENSXMAG00000007809

-----------------------------------------MKIPVWCLV
VLLGCFFTPARCDCQGECVACGLLLQQQQLEEAFDTIV-CLLECEGHVST
SLTWEVCRRAVKLS-HQPTLAEGGALFKRAGEEPDLTP-LDL-----NAE
-----SAAAQQLPEQDQ----DETPWD---NERSVQYDSSPLGSSEEGGS
LRGLDVRLTEEEAQQRRERGSESDGQ---LEGDASSEGVTLSKRFGGFQR
GRHGYRKLIGSPARGLQKRYGGFIGVRKSARQWNSPKWMNVNQQLRYRSS
S--RSGRPGTGG-LP-TNRR-WRQSKL
*
>P1;ENSDARG00000024189

-----------------------------------------MKTPFWTL-
-LLLCLCASSHSDCQGDCLTCGLILPEH---QAFNTLV-CILECEAQASP
ALTWDLCYQAAGLK-HLPLPLQDEETSKRSDDEAEPVATV---S--IEND
NGVEYTEALERFRHALQPSEELE--------KLTASY-------------
----DPDLDP-----R--TQEDQDDLG--D-EKSDDAAVSVSKRFGGFMK
GRHGLRKLV-SSGRPLQKRYGGFIGIRKSARKWNNQKRVS--QLLRQYLS
LTGRSGRSGHIN-SL-STRI-RRQSEV
*
>P1;ENSTNIG00000011906

-----------------------------------------MKTVL-VL-
-LLLCLSDPGQSDCQADCLSCSNFLPRH---LAFNAMVECLTQCQGGASR
SPYLDLCGVLASAH----V----SSVHRRSKEEAEALFPGQ-------LG
GDLLLPVELQRFDHMTQALEVDERSLD---------------------GN
GDQLNTGFQ---------AQ-PGPSDL--GAGGQGDYGPTLSKRFGGFVK
GRHGYRKLA-YPGRSYQKRYGGFVGIRKSARKWNNQKRFS--EFLKQYLG
M---SARTTDFT-GA-AADL-GQQKSV
*
>P1;ENSLOCG00000015967

-----------------------------------------MKTPLLTL-
-LLLGLCVPGRCDCQRDCLSCSQRLFQQ---DSFNTLV-CIMECEDKVST
SVTWDICRKATGKS----SSTLGANALKRGEEIAQL--PLDL------DE
AGLLYTGALKQFADLIRDFDVNKLEEENRVSKIRRAYHT---------E-
---------E---E-SE-ERPLGGDNVPGEEYSPPEGAIDLTKRFGGFLK
GKYGYRKLM-DPGRSLQKRYGGFIGVRKSARKWNNQKRFS--EFLKQYLG
M---STRSSEYD-SI-SADI-TEQNEI
*
