>P1;ENSONIG00000011749

-------------------MAGLPRRIVKETQRLMAEPVPGITATPDEGN
ARYFHVFIAGPQDSPFEGGTFRLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKK
NESQAIETARTWTRLYAGN-SEV
*
>P1;ENSAMXG00000020296

-------------------MAGLPRRIIKETQRLLAEPVPGIKAEPDEGN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKT
NEAQAIETARTWTRLYAGNNIEV
*
>P1;ENSDARG00000045877

-------------------MAGLPRRIIKETQRLLAEPVPGIKAEPDEGN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKS
NEAQAIETARTWTRLYAGNNIEV
*
>P1;ENSGACG00000011725

-------------------MAGLPRRISKETQRLIAEPVPGIKAEPDECN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEKWKS
SEVEAIETAKSWTRLYAGNQNDL
*
>P1;ENSTRUG00000016580

-------------------MAGLPRRIIKETQRLMAEPVPGITATPDERN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKK
NESAAIETARAWTRLYAGN-TEV
*
>P1;ENSORLG00000013513

-------------------MAGLPRRIIKETQRLMAEPVPGITATPDEGN
ARYFHVIIAGPQDSPYEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKK
HEMHAIETGSDFLSSQAAKIISV
*
>P1;ENSXMAG00000004059

-------------------MAGLPRRIIKETQRLMAEPVPGITATPDEGN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKK
NESHAIETARTWTRLYASN-TEV
*
>P1;ENSDARG00000008748

-------------------MAGLPRRIIKETQRLLAEPVPGIKAEPDEGN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKT
NEAQAIETARTWTRLYAGNNIEV
*
>P1;ENSGACG00000018807

-------------------MTGLPRRIVKETQRLMAEPVPGITALPDEAN
ARYFHVIIAGPQDSPFEGGIFKLELFLPEEYPMAAPKVRFITKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVADLWKR
DESNAIERARSWTRQYAI-----
*
>P1;ENSORLG00000011286

-------------------MAGLPRRIIKETQRLLAEPVPGIKAEPDESN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEKWKS
NEAEAIDIAKTWTRLYAGNKNEV
*
>P1;ENSXMAG00000001424

-------------------MAGLPRRIIKETQRLLAEPVPGIKAEPDEGN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEKWKS
SEAEAIETAKTWTRLYAGNKNEV
*
>P1;ENSTRUG00000007221

-------------------MSGLSSRIMKETRRLVTEHVPGIKAQPDESN
GRYFHVVIDGPQDTPFEGGVFKLELFLPEEYPMAAPKVRFITKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKS
SEAEAMKTAKAWTRLYARNS---
*
>P1;ENSTNIG00000018477

-------------------MAGLPRRIIKETQRLMAEPVPGITATPDERN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKK
NESAAIETARAWTRLYAGN-TEV
*
>P1;ENSONIG00000014682

-------------------MAGLPRRIIKETQRLLAEPVPGIKAEPDEAN
ARYFHVVIAGPQDSPFEGGTFRLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEKWKT
SEAEAIETAKTWTRLYAGNKNEV
*
>P1;ENSTNIG00000012146

-------------------MAGLPRRITKETQRLITDHVPGIKAEPDESN
ARYFHVDIDGPPDSPFEGGVFKLELFLPEEYPMAAPKVRFITKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKS
SEAEAIKTAKAWTRLYASKS---
*
>P1;ENSLOCG00000015285

MQVRGEAARESELKPHYDKMAGLPRRIIKETQRLLAEPVPGIKAEPDEGN
ARYFHVVIAGPQDSPFEGGTFKLELFLPEEYPMAAPKVRFMTKIYHPNVD
KLGRICLDILKDKWSPALQIRTVLLSIQALLSAPNPDDPLANDVAEQWKT
NEAQAIETARTWTRLYAGNNIEV
*
