>P1;ENSTRUG00000012428

Y--KGGLNNRSDCKRSKRRWWQQEMGLFYCSSVFSVSIEQIAVLHKRFRQ
LSHNDEKLRREHFMAIPDLACNPIRSQIIQAFFDRRNFHQKDDGTVEEIS
FEQFLVVMSHFRPPSPHMTEEQRESVRRDKLRFLFNMHDTDNDGMITLEE
YRHVVEELLSRSGALGKETAKSIADAAMLEVASISMGHMEPDEFYEGITF
EHFLKLLGSFEIESKMSIRFLNMDTFTL-C---K-
*
>P1;ENSORLG00000008146

---MGSLQSSPSHQDY-----------VDLAEKTGFSFEQISILHKRFKQ
LSHNEDKLRREHFGQITDLHANPIREQIVEAFFDRRNFYQEIEEPVSEIS
FENFLVVMSNFRPPSDNMSQEKLVKVRKEKLRFLFNMHDTDKDGTITLEE
YRHVVEELLSYYEALETETARGIADAAMLEVASITRGHMEPDEFYEGITF
EHFLKLLEGFDIESRMNIRFMNMDTTTL-CK--L-
*
>P1;ENSGACG00000014094

---MGASQTRPE-HRH-----------QDLADRTGFSLEQIKNLHKRFQQ
LSGDEDTISKENLESIPTLANNPIRKQIIGAFFDKRNQHRGEAGSCDQIG
FEQFLMVMSHFRPPTLKMTAEEKEAMRREKLRFLFNMHDTDNDGTITLVE
YRKVVEELLSKSGSIGQEAAEAIADAAMLEVASTNVPTMGPDDFYEGITF
EHFEQILKGLEMESRMHIRFLDVDTTTMRCGKSTS
*
>P1;ENSORLG00000000922

---MGAATTRIG-QQD-----------PELVDRTGFSPEQINNLHKRFLQ
LSGNKDTISRENLNDIPALTYNPIKSQIIEAFFDKRNQHDSEVGSLEEIT
FEQFLMVMSHFRPPTLEMTAEEKQAMRKEKLRFLFNMHDTDGDGKITLEE
YRKVVEELLS-SGSIEQESAKEITDAAMLEVASTNVPHMGPEDFYEGITF
EHFEQILKGLEMESRMHIRFLDTA--TVHCGKS--
*
>P1;ENSTNIG00000015605

---MGASQTRSE-HKY-----------QSLVEKTGFSLEQIKNLHKRFQQ
LSRNEETISREDLNSIPALANNPIRKQIVDAFFDKRNQHQNEVGSLQEIS
FEQFLMVMSHFRPPTLKTTEEEKEALRKEKLRFLFNMHDTDHDGTITLEE
YRKVVEELLSKSGAIGQEAAQAIADAAMLEVASTNVPHMDPDDFYEGITF
EHFEQILKGLEMESRMHIRFLDVDTTTMRCGKSSS
*
>P1;ENSGACG00000016945

--------------------------------------------------
--------------------------------------------------
-------MSHFRPPSLHVTEEQREAVRRDKLRFLFNMHDTDNDGTITLEE
YRHVVEELLSLSEALEKDTAKSIADAAMLEVASISMGHMEPDEFYEGITF
EHFLKLLNGFEIESRMNIRFLNMDTTTL-C---K-
*
>P1;ENSXMAG00000002448

---MGATQTHSE-YQY-----------ENMVGKTGFSTEQIKNLHMRFQQ
LCGNEKTLRKEHLENIPTLADNPIKTEIIKAFFDKRNQHNNELGSYEEIG
FEEFLMVMSHFRPPSIKTSAEEKAAMRKRKVRFLFNMHDTDGDGKITLEE
YRKIVEGLLSESESIGQEVARAIADAAMLEVASTNVPNMGPDDFYEGITL
EHFEQILKDLEMESRMYVRFLDMNTANLHCGK---
*
>P1;ENSONIG00000013959

---MGALQSLPGRPEY-----------SDLAEKTGFSFEQIGVLHKRFKQ
LSHNEETLRRDHFNEIHDLAFNPIRAQIIEAFFDRRNFHQDGEGKVQEIG
FEEFVVVMSHFRPPSDHMTEEQREKTRREKLRFLFNMHDTDNDGTITLEE
YRHVVEELLSRSGTLEKETAKCIADAAMLEVASISVGHMEPDEFYEGITF
EHFLKLLDGFEIESRMTIRFLNMDTTTL-C---K-
*
>P1;ENSTRUG00000016423

---MGASQTRSD-HKY-----------QNLVEKTGFSLEQIKNLHKRFQQ
LSGNEETISKENLNSIPALANNPIRKQIVDAFFDKRNQHQNEVGSFHEIS
FEQFLMVMSHFRPPTLKTTEEEKEALRKEKLRFLFNMHDTDNDGTITLEE
YRKVVEELLSKSGAIGQEAAKTIADAAMLEVASTNVPHMAPDDFYEGITF
EHFEQILKGLEMESRMHIRFLDVDTTTMRCG---K
*
>P1;ENSAMXG00000007002

---MGAFHSVPDDHQY-----------HILSEKTGFSLEQIGILHNRFKQ
LSHNSDVLRRDDLNTIPDLASNPIKSQIVEAFFDGRNLRKDSEGPVQEIG
FEEFLIVMSYFRPPSVHMTEEQREGIRRDKLRFLFNMHDTDNDGTITLEE
YRHVVEELLSRSGSLGRETAKGIADAAMLEVANMSVGRMGPDEVYAGITF
EHFLKILKGIEIETRMHIRFLNMDTTVL-C---K-
*
>P1;ENSDARG00000028346

---MGAAQSGGQAQKY-----------QDLADKTGFSTEQIRKLHSRFQY
LTQDEDTLRREHLENLTNLALNPIKRQIIEAFFDKRNLGQNEKGCLQEIG
FEEFVTVLSVFRPTKPRTAEDKKKTIKEEKLRFLFNMHDTDNDGVITLDE
YRRVVEELLSSYETIEAETAKAISDAAMLEVASVTVGRMSPDEFYEGITF
EQFMQILKDIEIETKMNVHFWNLDTRTMHCGK---
*
>P1;ENSTNIG00000009068

---MGALQSSPAPRDQ-----------ADLAEKTGFSLEQIAVLHKRFKQ
LSHNEETLRREHFKAIPDLACNPIRSQIIQAFFDRRNFHQNDDGTVEEIS
FEEFLVVMSHFRPPSQHMSEEQRESVRKEKLRFLFNMHDTDNDGMITLEE
YRHVVEELLSRSGALGKETAKSIADAAMLEVASISMGHMEPDEFYEGITF
EHFLKLLGSFEIESKMSIRFLNMDASTL-C---A-
*
>P1;ENSXMAG00000001381

---MGALKSTPDPIEY-----------ADLSEKTGYSLKQIRVLHKRFRE
LSDGDDVLRREHFRCISSLKYNPIRVEIIEAFFNRRNFSPSHQGSADEIG
FEEFLVVMSHFRPPSPKITDEQRKNIRREKLQFIFNMHDSDGDGLVTLED
YRHVVEELLSRSGALGKETAKAIADAAMFEVAR-TVGHKDPNEFYEGITF
EHFLKLLSNFDIESRMNIRFLKSDVNPF-CQLCC-
*
>P1;ENSDARG00000030839

---MGSFQSLPDDHQY-----------RTLSQKTGFSLEQIGILHNRFKQ
LSQNEDTLRRDDLKTIQDLESNPIRSQIIEAFFDKRNFQKDATGSVQEIG
FEEFLTVMSYFRAPAHQITEEQREEIRRAKLRFLFNMHDTDNDGTITLEE
YRHVVEELLSRSGALGRETAKGIADAAMLEVASITVGPMAPDEFYEGITF
EQFLKILKGVEIETRMHIRFLNMDTTVL-C---K-
*
>P1;ENSLOCG00000003578

TVVMGAFHSGPHEQQF-----------RQLADKTGFSLEQIETLHKRFKQ
LSQDEDTLQRENFDNVPNLDCNPIKTQIIEAFFDKRNFEKGGAGTVQEIT
FEQFLTVMGHFRPPELRMNDEQRDKVRKEKLRFLFNMYDTDNDGTITLEE
YKHVVEELLSRSGTLEKKTASAIADAAMLEVASITVGHMEPDEFYEGITF
DHFIKILNGLEIETRMNIHFLYVDTTTL-C---K-
*
