>P1;ENSTNIG00000002563

---------------------MADPD-LDFQTGESGASATFPMQCSALRK
NGYVLLKGHPCKIVEMSTSKTGKHGHAKVNLVGIDIFTNKKYEDMCPSTH
NMDVPSIKRTEYQLLNITDDYMTLMSDNGDIREDLRVPDNEVGKEIMTKF
QANEEFYVSVMSAMGEECAIGTKTMGNK
*
>P1;ENSAMXG00000004061

---------------------MADPD-LDFTSGDAGASVTYPQQCSALRK
NGFVVLKGRPCKIVEMSTSKTGKHGHAKVHLVGIDIFTNKKYEDICPSTH
NMDVPNIKRNDFQLVDINEGFLSLMMDNGDVREDLRVPDGDLGKEIESKH
GAGEDMMITVLSAMGEEAAVGIKAFT-K
*
>P1;ENSGACG00000012551

GSLNCHLTHRGSSKSPLTHRTMSDPD-LDFTVGESGASATYPMQCSALRK
NGYVVLKGHPCKIVEMSTSKTGKHGHAKVNLVGIDIFTNKKHEDMCPSTH
NMDVPSIKRLDYQLVNINDGYMCLMSDTGDIREDLRVPDSEIGREIEGKF
EAGDEFMVTVIAAMGEECAVATKVLA-G
*
>P1;ENSORLG00000011487

---------------------MADD---DFSTADAGASTTFPMQCSALRK
NGFVMLKGRPCKIVEMTTSKTGKHGHAKVHLTGLDIFTQKKYEDICPSTH
NMDVPNVIRKDYQAIDVSDGFLSLMDDNGETREDLKVPEGDLGKEIIKKI
SNGELFMVSVLKAVDEEQIVGTKNMT-S
*
>P1;ENSORLG00000002907

---------------------MADPD-LDFTTGESGASATYPMQCSALRK
NGYVVLKGRPCKIVEMSTSKTGKHGHAKVNLVGIDIFTNKKYEDMCPSTH
NMDVPSIKRIDYQLVNINENYMSLMSDNGDIREDLRVPENEVGKEIEAKF
EAGEEFMVTVISAMGEECAVATKVLASK
*
>P1;ENSXMAG00000009045

---------------------MADD---DFSTADAGASATFPIQCSALRK
NGFVMLKGRPCKIVEMSTSKTGKHGHAKVHLTGIDIFTAKKYEDICPSTH
NMDVPNVIRKDYQVLDIIDGFLTLMEDNGETREDLRLPDGDMGKEIVKKL
ESGDQFLVKI------------------
*
>P1;ENSDARG00000056186

---------------------MADLD-TDFTSGDAGASLTFPMQCSALRK
NGFVVLKGRPCKIVEMSTSKTGKHGHAKVHMVGIDIFTGKKNEDICPSTH
NMDVPNIKRQDYQLVGIIDGYLSLMKDNGDLRDDLKLPEGDLGKEIESKF
ESGDEFLVSVLAAMGEECPIAIKPMS-S
*
>P1;ENSGACG00000010995

---------------------MADE---DFECGHSGASSTFPQQCSALRK
NGFVMIKGRPCKIMEMSTSKTGKHGHAKVHLTGLDIFTQKKYEDICPSTH
NMDVPHVTRKDYQVIDVADGFLSLMDDGGATREDLKLPEGDIGKEIEKKF
DNGDNFMVTVLKALDEENVVATKAQ--N
*
>P1;ENSTRUG00000011948

-----------------P-ITMSDD---EYQPVGSGASETYPAQCSSLRK
NGHVMLKGRPCKIVNMTTSKTGKHGHAKVHLTGIDIFTSKKYEDICPSTH
NMDVPNTRRKDFQVISENEGYLHLMDDEGNVREDLRIPEGDLGKEIQAKL
TNDDEFMVTVLTAMGEEAIVTIKNTQ-K
*
>P1;ENSXMAG00000012044

---------------------MADPD-LDFTTGESGASATYPMQCSALRK
NGYVVLKGRPCKIVEMSTSKTGKHGHAKVNLVGIDIFTNKKYEDMCPSTH
NMDVPAIKRTDYQLVNIAESYMSLMSDNGDIREDLRVPESDIGKEIESKF
EGGEEFMVTVISAMGEECAVATKVLASK
*
>P1;ENSTRUG00000003482

---------------------MADPDGFDFQTGESGASATFPMQCSALRK
NGYVLLKGHPCKIVEMSTSKTGKHGHAKVNLVGIDIFTNKKYEDMCPSTH
NMDVPSIKRTEYQLLNIADDYMTLMSDNGDIREDLRVPENEVGKEIMGKF
QASEEFYVSVMSAMGEECAIGTKTMGNK
*
>P1;ENSONIG00000000879

---------------------MADD---DFSTADAGASTTYPMQCSALRK
NGYVMLKGRPCKIVDMSTSKTGKHGHAKVHLTGLDIFTQKKYEDICPSTH
NMDVPNITRKDYQVLDVADGFLALMDDNGETREDLKLPDSDLGKEIEKRF
TNGDQFMVSVLKAIDEEHVVGTKTMT-S
*
>P1;ENSONIG00000017664

---------------------MADPD-LDFQTGESGASATYPMQCSALRK
NGYVVLKGRPCKIVEMSTSKTGKHGHAKVNLVGIDIFTNKKYEDMCPSTH
NMDVPSIKRIDYQLVNINENYMSLMSDNGDIREDLRVPDNEVGKEIESKF
EAGEEFMVTVIAAMGEECAVATKVLASK
*
>P1;ENSDARG00000017235

---------------------MADPD-LDFASGDAGASATYPMQCSALRK
NGFVVLKGRPCKIVEMSTSKTGKHGHAKVHLVGIDIFTNKKYEDICPSTH
NMDVPNIKRNDYQLVDISEGFLSLMMDNGDVREDLRVPDGDLGKEIENKF
AAGEEMLVTVLSAMGEESAVALKPMT-K
*
>P1;ENSTNIG00000006661

-----------------------DE---DFEGGKSGASETYPAQCSSLRK
NGFVMLKTCPCKIVEMTTSTTGKHGHAKVHLTGVDIFTGKEYEDICPSTH
NMDVPHVVRKDYTLVDVTDGFVHLMDDDGSIREDLKLPESELGKDIKTKF
DNGEELMLTVLKGVGEEQVIGIKGAG-K
*
>P1;ENSLOCG00000007318

-----------------NQTTMADPD-IDFTSGDAGASSTIPMQCSALRK
NGFVVLKGRPCKIVEMSTSKTGKHGHAKVHMIGIDIFTGKKYEDICPSTH
NMDVPNIKRNDFQLIGITDGFLSLLMDNGEVREDLRLPEGDLGKEIESKY
EAGEEMLISVLSAMGEESAVAIKPMT-K
*
