>P1;ENSTNIG00000010005

----------MADRDSGSEQGGAA--MGPG--------------------
FASMHLATGGAGLASGLQHETQELASKRVDIQNKRFYLDVKQNPKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTHPGLVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWSKFGNTFSKYAEEMKKIQEKQREKRA
CEE-------M-QADDGDED
*
>P1;ENSAMXG00000024949

----------MADRDSGSEHGGFA--TGGGGIGGGGGGGPGGGGPGGGGG
LGL--PHPGAVGAASRLQHDTEELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSHPDTAQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRVRQTVNRGPGLGTAQGQTIAL
PAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSLAVDNKRFFFDVGANKY
GVFMRVSEVKPAYRNSITVPCKVWSKFGATFCKYADEMKRIQERSRERRA
RELLPE---GL-HGDDGDED
*
>P1;ENSAMXG00000025364

----------MADRDSGSEQGGAP--TGPG--------------------
VG-LHAVAGGAGSASGLQHDTQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDAAQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGTSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWAKFGSTFCKYAEEMKKIQDKQRERRA
CEQQQQQPGEM-HADDGDED
*
>P1;ENSGACG00000018680

-------GSRGCSRQRETVEGKAGRQHHGGQ-------------------
R----QWQCAMGAMSRLQHDTEELASKRVDIQNKRFYLDVKQNVKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTNPDIVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQTIAL
PAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPCKVWSKFGNTFCKYAEEMRKIQERNREKRA
S-------------------
*
>P1;ENSTNIG00000004639

----------MADRDSGSDHGGPT--GGPG--------------------
S----LPAGAMSAMSRLQHDTEELASKRVDIQNKRFYIDVKQNVKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDVVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQTIAL
PAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSFTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPCKVWSRFGNTFCKYAEEMKKIHERSREKRA
SELLPE---GS----HGEDD
*
>P1;ENSDARG00000067591

----------MADRDSGSEQGGAA--TGPG--------------------
VGSMHPVTGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDMPQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGTSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWSKFGSTFCKYADEMKKIQEKQREKRA
CELQQQQQEEM-HGDDGDED
*
>P1;ENSTRUG00000006789

----------MADRDSGSDHGGPT--GGPG--------------------
S----LPAGAMGAMSRLQHDTEELASKRVDIQNKRFYIDVKQNVKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTNPDIVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQTIAL
PAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSFTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPCKVWSRFGNTFCKYAEEMKKIHERSREKRA
SELLPE---GS----HGEED
*
>P1;ENSONIG00000021362

----------MADRDSGSEQGGAA--TGPG--------------------
FGSVHLATGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPGMVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGFTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEEMKKIQEKQREKRA
CELQQQ--EEM-QQDDGDED
*
>P1;ENSXMAG00000019887

----------MADRDSGSEQGGAA--TGPG--------------------
FGSMHLAAGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPGMVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEDMKKIQEKQREKRA
CELQQQ--EEM-QADDGDED
*
>P1;ENSGACG00000020655

QRGRRQAGSIMADRDSGSEQGGAP--TGPG--------------------
FGSMHPATGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPALVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEEMKKIQEKQREKRA
CELQQQ--EEL-QADD---D
*
>P1;ENSORLG00000006100

--------------------------------------------------
---MHLPTGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPGMIQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGSSLTVDNKRFFFDVGSNKY
GVFMRVSENYHK---------KEEGKKKSHLCQLMTDKQPAQTVVKVRR-
--------------------
*
>P1;ENSDARG00000099614

----------MADRDSGSEHGGFA--TGPG--------------------
AGP--MH---PGAASRLQHDTEELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDLVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGTSQGQTIAL
PAQGLIEFRDALAKLIDDFGVDEDPAELPEGTSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPCKVWSKFGATFCKYADEMKKIQERSRERRA
REMLPE---GL-HGDDGDED
*
>P1;ENSONIG00000020655

----------MADRDSGSDHGGPT--AGPG--------------------
S----LPPGAMGAMSRLQHDTEELASKRVDIQNKRFYLDVKQNVKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPTNPDMVQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSAQGQTIAL
PAQGLIEFRDALAKLIDDYGVDEEPAELPEGTSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPCKVWSKFGNTFCKYAEEMRKIQERSREKRA
SELLPE---GPHGGDDGDDD
*
>P1;ENSLOCG00000018317

EKAGRQAGSIMADRDSGSEQGGAA--TGPG--------------------
AGSLHPVAGGAGSASGLQHETQELASKRVDIQNKRFYLDVKQNAKGRFLK
IAEVGAGGNKSRLTLSMSVAVEFRDYLGDFIEHYAQLGPSNPDIAQDEPR
RALKSEFLVRENRKYYMDLKENQRGRFLRIRQTVNRGPGLGSTQGQTIAL
PAQGLIEFRDALAKLIDDYGVEDEPAELPEGTSLTVDNKRFFFDVGSNKY
GVFMRVSEVKPTYRNSITVPYKVWSKFGNTFCKYAEEMKKIQEKQREKRA
SELQQQ-QEEI-HGDD---G
*
