>P1;ENSXMAG00000010210

-----MDKVEATATV--CDFDPMSGSIPATKVEITVSC-RNLLDRDTFSK
SDPLVVLYTQGVESKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDVYDIDSKSPDLAKH------DFLGQVYCTLGEIVGSPASRLEKQLV-
--------------------------GIPGKTCGTIILSAEELGNCR-DY
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WEPFSIPVRALCNGDYERTIKVEVYDWDRDGSHDFIGEFTTSYKELCRGQ
SQLNLYEVVNPKKKLKKKRYINSGTVSLLSFSVESEH--TFLDYIKGGTQ
IHFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNVENPYCNGMEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDVRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQLISYMKSRAIKPNPVPPPYSS------------CKQPET-ESV

*
>P1;ENSTRUG00000006293

-----MDKLEDMSSV--YDFDPITGNIPATKVEITVSC-RNLLDKDTFSK
SDPLCVLYTQGVETKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDLYDVDSKSPDLSKH------DFLGQTFCTLGEIVGSPASRLEKPLGI
G----VLNTNGRIGG---LFHLVSKRGIPGKKCGTIVLSAEELSNCR-DS
ATLQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDFDRTIKVEVYDWDRDGSHDFIGDYTTSYRELARGQ
SQFNVYEVINTKKKMKKKKYVNSGTVTLLSFSVESEF--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQLNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNMENPYCNGIEGILEAYHQSL
RTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTH----H

*
>P1;ENSONIG00000019343

---------------------------------------RNLLDKDTFSK
SDPMCVLYTQGVETKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDLYDVDSKSPDLSKH------DFLGQMFCTLGEIVGSPASRLEKPLGA
G----FFSVHRATSVLQKPPSASSNTGIPGKKCGTIILTAEELSNCR-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGDFTTSYRELARGQ
SQFNVYEVINTKKKMKKKKYVNSGTVTLLSFSVESEF--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQLNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDWRVSHEFPLNGNIENPYCNGIEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNGAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTH----H

*
>P1;ENSTNIG00000015121

-----MDKVEATATV--RDFDPISGSVPATKVEITVSC-RNLLDRDTFSK
SDPLVVLYTQGVECKQWREFGRTEVIDNTLNPDFVRKFILDYFFEEKQNL
RFDVYDIDSKSPDLAKH------DFLGQVHCTLGEIVGSPASRLEKSLGF
G----SFFLGPHLFT---PPPPRLSGGIPGKKCGTIVLSAEELIICRQDC
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQAFSIPVRALCNGDYERTIKAEIYDWDRDGSHDFIGEFTTSYKELCRGQ
GQSNVYEVMNAKKKLKKKRYINSGTVSLLSFSVESEH--TFLDYIKGGTQ
IHFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNTENPYCNGMEGILEAYHQSL
KTVQLYGPTNFSPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKMAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQLISYMKSRAIKPSPVPPAYSTGTQ--------PPSNPVH-YYI

*
>P1;ENSONIG00000011820

-----MDKVEATATV--RDFDPISGSIPATKVEITVSC-RNLLDRDTFSK
SDPLVVLYTQGVESKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDVYDIDSKSPDLAKH------DFLGQVFCTLGEIVGSPASRLEKPLGI
ERHIKAFQLHLDTST---SFPKITESGIPGKKCGTIILSAEELGNCR-DY
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WEPFSIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGEFTTSFKELCRGQ
NQLNVYEVVNAKKKIKKKRYINSGTVSLLSFSVESEH--TFLDYIRGGTQ
IHFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDWRVSHEFPLNGNVDNPYCNGMEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDVRISSRGKVAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQLISYMKSRAIKPNPVP-VYSPSDEPPTNPVRAPPASCCH-IDI

*
>P1;ENSTNIG00000007260

VTSA----VFSLLLLFNCDF---------------LSD-RNLLDKDTFSK
SDPLCVLYTQGVETKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDLYDVDSKSPDLSKH------DFLGQTFCTLGEIVGSPASRLEKPLGL
------------------------KQGRKWKKCGNIILSAEELSNCR--F
VTFNFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGDYTTSYRELARGQ
SQFNVYEVINTKKKMKKKKYVNSGTVTLLSFSVESEF--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNP-QLNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNMENPYCNGIEGILEAYHQSL
RTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP----------------------

*
>P1;ENSORLG00000016068

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------Q-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGDFTTSYRELARGQ
SQFNVYEVINTKKKMKKKKYVNSGTVTLLSFSVESEF--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQLNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNLENPYCNGIEGILEAYHESL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRVSSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGVKPNPAPPPYTP------------PGHTHHHTQI

*
>P1;ENSAMXG00000007156

--------------------------------------------------
--------------------------------------------------
----------------------------MFCTLGEIVGSPASRLDKPLG-
--------------------------GIPGKKCGTIILSAEELGNCR-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQSFTIPVRALCNGDFDRTIKVEVYDWDRDGSHDFIGEFTTSYRELARGQ
SQFNVYEVVNPKKKMKKKKYVNSGTLTVENFSFKTSYFFFFLAYLFHRTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNIENPYCNGIEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YVLQ
DKHLSLFFLLLTRTCTISLDLPKTKSGLKLNGAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTHH-TQI

*
>P1;ENSDARG00000061466

-----MDKLEDMASV--CEFDPITGNIPATKVEITVSC-RNLLDRDTFSK
SDPLCILYTQGAESKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDIYDIDSKSPDLAKH------DFLGQTFCTLGEIVGSPGSRLEKPLG-
--------------------------GIPGKNCGTIILTAEELGNCR-DC
ATMQFCANKLDKKDFFGRSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPI
WQPFTIPVRALCNGDYDRSIKVEVYDWDRDGSHDFIGEFTTSYRELSRGQ
SQFNVYEVVNPKKKLKKRRYINSGTVTLLSFLVEAEH--TFLDYIKAGLQ
IHFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNVDNPYCNGMEGILEAYHESL
KTVQLYGPTNFAPVINHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDVRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQLILYMKSRGIKPNQTPPEYSP------------PGLSPT-STI

*
>P1;ENSXMAG00000004086

-----FEKE---------------------------------IDRL----
------------------------------------------------TC
R--------------------------------------------FPH--
-------------------------RGIPGKKCGTIILTAEELSNCR-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGDFTTSYRELARGQ
SQFNVYEVINTKKKMKKKKYVNSGTVTLLSFSVESEF--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQLNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNMENPYCNGIEGILEAYHQSL
KTVQLYGPTNFAPIVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTHHHTQI

*
>P1;ENSAMXG00000007702

-----M--------------------------------------------
--------------------------------------------------
---------------LH------IWLG--------------------FR-
--------------------------GIPGKKCGTIILAAEELGNCR-DC
VTMQFCANKLDKKDFFGRSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WKPFSIPVRALCNGDYDRSIKVEIYDWDRDGSHDFIGEFTTSYKELTRTQ
SQFSVFEVVNAKKKLKKRRYINSGTVTLLSFSVEAEH--TFLDYIKAGTQ
IHFTVAIDFTASNELLGNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNMDNPYCNGMEGILDAYHQSL
KTVQLYGPTNFAPVVNHVARSCTLPCVSFSLQEPVTSMMTVIVFNRYAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQLILYMKSRGIKPNQSPPECSP------------EAGLSPTSAI

*
>P1;ENSORLG00000006371

----------KFYPL--KEFVTKGALLESNTVEICLSCYRNLLDRDTFSK
SDPMVVLYTQGVESKQWREFGRTEVIKNTLNPDFVRKYILDYFFEEKQNL
RFDVYDIDSKSPDLGKH------DFLGQVYCTLGEIVGSPASRLEKPLGI
P----SFRKQNRSGK---TQPASSFVGIPGKTCGTIILSAEELGNCR-DY
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPM
WQPFSIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGEFSTSYKELCRGQ
SESNVYEVVNAKKKLKKKRYINSGTVSLLSFSVESEH--TFLDYIKGGTQ
IHFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNVENPYCNGMEGILEAYHQSL
KLVQLYGPTNFAPVVNHVAR--------------------------YAAA
VEDGSQYFILLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDVRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQLISYMKSRAIKPNPVPPPYST------------CNNPET-TPL

*
>P1;ENSGACG00000008082

-----MDKVEATATV--CDFDPDSGSIPATKVEITVSC-RNLLDRDTFSK
SDPLVVLYTQGVESKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDVYDIDSKSPDLAKH------DFLGQVYCTLGEIVGSPASRLEKPLG-
--------------------------GIPGKKCGTIILSAEELGNCR-DY
ATMQFSANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFSIPVRGLCNGDYDRTIKVEVYDWDRDGSHDFIGEFTTRYKDLCRGL
NQINVYEVVNAKKKVKKKRYINSGTVSLLSCSVESEH--TFLDYIKGGTQ
IHFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNVENPFCNGMEGILEAYHQSL
KTVQLYGPTNFSPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPEQLISSMKSRGIKPNAVPPVHSP------------GEQ-LQ-TNL

*
>P1;ENSDARG00000070919

MEGDIMDKLEDMASV--YEFDPLTGNIPATKVEITVSC-RNLLDRDTFSK
SDPLCVLYTQGVETKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDLYDVDSKSPDLSKH------DFLGQMFCTLGEIVGSPASRLEKPLG-
--------------------------GISGKNCGTIVLSAEELGNCR-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGEFTTSYRELARGQ
SQFNVYEVVNPKKKMKKKKYVNSGTVTLLSFSVESES--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYALALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNIENPYCNGIEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFILLIITDGVISDMSQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTHH-TQI

*
>P1;ENSGACG00000007585

---------------------------------------RNLLDKDTFSK
SDPLCVLYTQGVETKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDLYDVDSKSPDLSKH------DFLGQTFCTLGEIVGSPASRLEKPLG-
--------------------------GIHGKKCGTVVLSAEELSNCR-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQPFTIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGDYTTSYRELARGQ
SQFNVYEVVNTKKKMKKKKYINSGTVTLLSFSVESDF--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQLNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGDMDNPYCNGIEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNGAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTHHHTQI

*
>P1;ENSLOCG00000011204

MEGDVMDKLGDMASM--SEFDPITGNIPATKVEITVSC-RNLLDKDTFSK
SDPLCVLYIQGIETKQWREFGRTEVIDNTLNPDFVRKYILDYFFEEKQNL
RFDLYDVDSKSPDLSKHMIFWYYDFLGQAFCTLGEIVGSPGSRLEKPLS-
--------------------------GIPGKKCGIIILSAEELGNCR-DS
ATMQFCANKLDKKDFFGKSDPFMVFYRSNEDGTFTICHKTEVVKNTLNPV
WQAFSIPVRALCNGDYDRTIKVEVYDWDRDGSHDFIGEFTTSYRELARGQ
SQFNVYEVVNPKKKMKKKKYINSGTVTLLSFTVESEY--TFLDYIKGGTQ
INFTVAIDFTASN---GNPSQSTSLHYMNPYQMNAYAMALKAVGEIIQDY
DSDKMFPALGFGAKLPPDGRVSHEFPLNGNIENPYCNGIEGILEAYHQSL
KTVQLYGPTNFAPVVNHVAR--------------------------YAAA
VQDGSQYFVLLIITDGVISDMAQTKEAI-VNAAKLPMSIIIVGVGQAEFD
AMVELDGDDIRISSRGKLAERDIVQFVPFRDYMDRTGNHVLSMARLAKDV
LAEIPDQFISYMKSRGIKPNPAPPPYTP------------PGHTLH-TQI

*
