#!/bin/bash

 ./algndna_new Full_pir/Pillar228_pro.pir output/Pillar228.fas -c:Full_pir/TGD_CDS_withGar/Pillar228_CDS.fas -s
 ./algndna_new Full_pir/Pillar271_pro.pir output/Pillar271.fas -c:Full_pir/TGD_CDS_withGar/Pillar271_CDS.fas -s
 ./algndna_new Full_pir/Pillar285_pro.pir output/Pillar285.fas -c:Full_pir/TGD_CDS_withGar/Pillar285_CDS.fas -s
 ./algndna_new Full_pir/Pillar287_pro.pir output/Pillar287.fas -c:Full_pir/TGD_CDS_withGar/Pillar287_CDS.fas -s
 ./algndna_new Full_pir/Pillar295_pro.pir output/Pillar295.fas -c:Full_pir/TGD_CDS_withGar/Pillar295_CDS.fas -s
 ./algndna_new Full_pir/Pillar335_pro.pir output/Pillar335.fas -c:Full_pir/TGD_CDS_withGar/Pillar335_CDS.fas -s
 ./algndna_new Full_pir/Pillar339_pro.pir output/Pillar339.fas -c:Full_pir/TGD_CDS_withGar/Pillar339_CDS.fas -s
 ./algndna_new Full_pir/Pillar357_pro.pir output/Pillar357.fas -c:Full_pir/TGD_CDS_withGar/Pillar357_CDS.fas -s
 ./algndna_new Full_pir/Pillar358_pro.pir output/Pillar358.fas -c:Full_pir/TGD_CDS_withGar/Pillar358_CDS.fas -s
 ./algndna_new Full_pir/Pillar366_pro.pir output/Pillar366.fas -c:Full_pir/TGD_CDS_withGar/Pillar366_CDS.fas -s
 ./algndna_new Full_pir/Pillar367_pro.pir output/Pillar367.fas -c:Full_pir/TGD_CDS_withGar/Pillar367_CDS.fas -s
 ./algndna_new Full_pir/Pillar455_pro.pir output/Pillar455.fas -c:Full_pir/TGD_CDS_withGar/Pillar455_CDS.fas -s
 ./algndna_new Full_pir/Pillar505_pro.pir output/Pillar505.fas -c:Full_pir/TGD_CDS_withGar/Pillar505_CDS.fas -s
 ./algndna_new Full_pir/Pillar518_pro.pir output/Pillar518.fas -c:Full_pir/TGD_CDS_withGar/Pillar518_CDS.fas -s
 ./algndna_new Full_pir/Pillar530_pro.pir output/Pillar530.fas -c:Full_pir/TGD_CDS_withGar/Pillar530_CDS.fas -s
 ./algndna_new Full_pir/Pillar540_pro.pir output/Pillar540.fas -c:Full_pir/TGD_CDS_withGar/Pillar540_CDS.fas -s
 ./algndna_new Full_pir/Pillar547_pro.pir output/Pillar547.fas -c:Full_pir/TGD_CDS_withGar/Pillar547_CDS.fas -s
 ./algndna_new Full_pir/Pillar718_pro.pir output/Pillar718.fas -c:Full_pir/TGD_CDS_withGar/Pillar718_CDS.fas -s
 ./algndna_new Full_pir/Pillar725_pro.pir output/Pillar725.fas -c:Full_pir/TGD_CDS_withGar/Pillar725_CDS.fas -s
 ./algndna_new Full_pir/Pillar728_pro.pir output/Pillar728.fas -c:Full_pir/TGD_CDS_withGar/Pillar728_CDS.fas -s
 ./algndna_new Full_pir/Pillar729_pro.pir output/Pillar729.fas -c:Full_pir/TGD_CDS_withGar/Pillar729_CDS.fas -s
 ./algndna_new Full_pir/Pillar730_pro.pir output/Pillar730.fas -c:Full_pir/TGD_CDS_withGar/Pillar730_CDS.fas -s
 ./algndna_new Full_pir/Pillar731_pro.pir output/Pillar731.fas -c:Full_pir/TGD_CDS_withGar/Pillar731_CDS.fas -s
 ./algndna_new Full_pir/Pillar733_pro.pir output/Pillar733.fas -c:Full_pir/TGD_CDS_withGar/Pillar733_CDS.fas -s
 ./algndna_new Full_pir/Pillar736_pro.pir output/Pillar736.fas -c:Full_pir/TGD_CDS_withGar/Pillar736_CDS.fas -s
 ./algndna_new Full_pir/Pillar738_pro.pir output/Pillar738.fas -c:Full_pir/TGD_CDS_withGar/Pillar738_CDS.fas -s
 ./algndna_new Full_pir/Pillar742_pro.pir output/Pillar742.fas -c:Full_pir/TGD_CDS_withGar/Pillar742_CDS.fas -s
 ./algndna_new Full_pir/Pillar746_pro.pir output/Pillar746.fas -c:Full_pir/TGD_CDS_withGar/Pillar746_CDS.fas -s
 ./algndna_new Full_pir/Pillar788_pro.pir output/Pillar788.fas -c:Full_pir/TGD_CDS_withGar/Pillar788_CDS.fas -s
 ./algndna_new Full_pir/Pillar790_pro.pir output/Pillar790.fas -c:Full_pir/TGD_CDS_withGar/Pillar790_CDS.fas -s
 ./algndna_new Full_pir/Pillar802_pro.pir output/Pillar802.fas -c:Full_pir/TGD_CDS_withGar/Pillar802_CDS.fas -s
 ./algndna_new Full_pir/Pillar809_pro.pir output/Pillar809.fas -c:Full_pir/TGD_CDS_withGar/Pillar809_CDS.fas -s
 ./algndna_new Full_pir/Pillar851_pro.pir output/Pillar851.fas -c:Full_pir/TGD_CDS_withGar/Pillar851_CDS.fas -s
 ./algndna_new Full_pir/Pillar858_pro.pir output/Pillar858.fas -c:Full_pir/TGD_CDS_withGar/Pillar858_CDS.fas -s
 ./algndna_new Full_pir/Pillar864_pro.pir output/Pillar864.fas -c:Full_pir/TGD_CDS_withGar/Pillar864_CDS.fas -s
 ./algndna_new Full_pir/Pillar919_pro.pir output/Pillar919.fas -c:Full_pir/TGD_CDS_withGar/Pillar919_CDS.fas -s
 ./algndna_new Full_pir/Pillar958_pro.pir output/Pillar958.fas -c:Full_pir/TGD_CDS_withGar/Pillar958_CDS.fas -s
 ./algndna_new Full_pir/Pillar1056_pro.pir output/Pillar1056.fas -c:Full_pir/TGD_CDS_withGar/Pillar1056_CDS.fas -s
 ./algndna_new Full_pir/Pillar1058_pro.pir output/Pillar1058.fas -c:Full_pir/TGD_CDS_withGar/Pillar1058_CDS.fas -s
 ./algndna_new Full_pir/Pillar1059_pro.pir output/Pillar1059.fas -c:Full_pir/TGD_CDS_withGar/Pillar1059_CDS.fas -s
 ./algndna_new Full_pir/Pillar1060_pro.pir output/Pillar1060.fas -c:Full_pir/TGD_CDS_withGar/Pillar1060_CDS.fas -s
 ./algndna_new Full_pir/Pillar1069_pro.pir output/Pillar1069.fas -c:Full_pir/TGD_CDS_withGar/Pillar1069_CDS.fas -s
 ./algndna_new Full_pir/Pillar1076_pro.pir output/Pillar1076.fas -c:Full_pir/TGD_CDS_withGar/Pillar1076_CDS.fas -s
 ./algndna_new Full_pir/Pillar1079_pro.pir output/Pillar1079.fas -c:Full_pir/TGD_CDS_withGar/Pillar1079_CDS.fas -s
 ./algndna_new Full_pir/Pillar1081_pro.pir output/Pillar1081.fas -c:Full_pir/TGD_CDS_withGar/Pillar1081_CDS.fas -s
 ./algndna_new Full_pir/Pillar1085_pro.pir output/Pillar1085.fas -c:Full_pir/TGD_CDS_withGar/Pillar1085_CDS.fas -s
 ./algndna_new Full_pir/Pillar1086_pro.pir output/Pillar1086.fas -c:Full_pir/TGD_CDS_withGar/Pillar1086_CDS.fas -s
 ./algndna_new Full_pir/Pillar1095_pro.pir output/Pillar1095.fas -c:Full_pir/TGD_CDS_withGar/Pillar1095_CDS.fas -s
 ./algndna_new Full_pir/Pillar1098_pro.pir output/Pillar1098.fas -c:Full_pir/TGD_CDS_withGar/Pillar1098_CDS.fas -s
 ./algndna_new Full_pir/Pillar1115_pro.pir output/Pillar1115.fas -c:Full_pir/TGD_CDS_withGar/Pillar1115_CDS.fas -s
 ./algndna_new Full_pir/Pillar1161_pro.pir output/Pillar1161.fas -c:Full_pir/TGD_CDS_withGar/Pillar1161_CDS.fas -s
 ./algndna_new Full_pir/Pillar1214_pro.pir output/Pillar1214.fas -c:Full_pir/TGD_CDS_withGar/Pillar1214_CDS.fas -s
 ./algndna_new Full_pir/Pillar1238_pro.pir output/Pillar1238.fas -c:Full_pir/TGD_CDS_withGar/Pillar1238_CDS.fas -s
 ./algndna_new Full_pir/Pillar1271_pro.pir output/Pillar1271.fas -c:Full_pir/TGD_CDS_withGar/Pillar1271_CDS.fas -s
 ./algndna_new Full_pir/Pillar1275_pro.pir output/Pillar1275.fas -c:Full_pir/TGD_CDS_withGar/Pillar1275_CDS.fas -s
 ./algndna_new Full_pir/Pillar1276_pro.pir output/Pillar1276.fas -c:Full_pir/TGD_CDS_withGar/Pillar1276_CDS.fas -s
 ./algndna_new Full_pir/Pillar1277_pro.pir output/Pillar1277.fas -c:Full_pir/TGD_CDS_withGar/Pillar1277_CDS.fas -s
 ./algndna_new Full_pir/Pillar1279_pro.pir output/Pillar1279.fas -c:Full_pir/TGD_CDS_withGar/Pillar1279_CDS.fas -s
 ./algndna_new Full_pir/Pillar1280_pro.pir output/Pillar1280.fas -c:Full_pir/TGD_CDS_withGar/Pillar1280_CDS.fas -s
 ./algndna_new Full_pir/Pillar1297_pro.pir output/Pillar1297.fas -c:Full_pir/TGD_CDS_withGar/Pillar1297_CDS.fas -s
 ./algndna_new Full_pir/Pillar1301_pro.pir output/Pillar1301.fas -c:Full_pir/TGD_CDS_withGar/Pillar1301_CDS.fas -s
 ./algndna_new Full_pir/Pillar1309_pro.pir output/Pillar1309.fas -c:Full_pir/TGD_CDS_withGar/Pillar1309_CDS.fas -s
 ./algndna_new Full_pir/Pillar1315_pro.pir output/Pillar1315.fas -c:Full_pir/TGD_CDS_withGar/Pillar1315_CDS.fas -s
 ./algndna_new Full_pir/Pillar1351_pro.pir output/Pillar1351.fas -c:Full_pir/TGD_CDS_withGar/Pillar1351_CDS.fas -s
 ./algndna_new Full_pir/Pillar1363_pro.pir output/Pillar1363.fas -c:Full_pir/TGD_CDS_withGar/Pillar1363_CDS.fas -s
 ./algndna_new Full_pir/Pillar1393_pro.pir output/Pillar1393.fas -c:Full_pir/TGD_CDS_withGar/Pillar1393_CDS.fas -s
 ./algndna_new Full_pir/Pillar1412_pro.pir output/Pillar1412.fas -c:Full_pir/TGD_CDS_withGar/Pillar1412_CDS.fas -s
 ./algndna_new Full_pir/Pillar1431_pro.pir output/Pillar1431.fas -c:Full_pir/TGD_CDS_withGar/Pillar1431_CDS.fas -s
 ./algndna_new Full_pir/Pillar1432_pro.pir output/Pillar1432.fas -c:Full_pir/TGD_CDS_withGar/Pillar1432_CDS.fas -s
 ./algndna_new Full_pir/Pillar1554_pro.pir output/Pillar1554.fas -c:Full_pir/TGD_CDS_withGar/Pillar1554_CDS.fas -s
 ./algndna_new Full_pir/Pillar1557_pro.pir output/Pillar1557.fas -c:Full_pir/TGD_CDS_withGar/Pillar1557_CDS.fas -s
 ./algndna_new Full_pir/Pillar2056_pro.pir output/Pillar2056.fas -c:Full_pir/TGD_CDS_withGar/Pillar2056_CDS.fas -s
 ./algndna_new Full_pir/Pillar2064_pro.pir output/Pillar2064.fas -c:Full_pir/TGD_CDS_withGar/Pillar2064_CDS.fas -s
 ./algndna_new Full_pir/Pillar2065_pro.pir output/Pillar2065.fas -c:Full_pir/TGD_CDS_withGar/Pillar2065_CDS.fas -s
 ./algndna_new Full_pir/Pillar2068_pro.pir output/Pillar2068.fas -c:Full_pir/TGD_CDS_withGar/Pillar2068_CDS.fas -s
 ./algndna_new Full_pir/Pillar2070_pro.pir output/Pillar2070.fas -c:Full_pir/TGD_CDS_withGar/Pillar2070_CDS.fas -s
 ./algndna_new Full_pir/Pillar2088_pro.pir output/Pillar2088.fas -c:Full_pir/TGD_CDS_withGar/Pillar2088_CDS.fas -s
 ./algndna_new Full_pir/Pillar2091_pro.pir output/Pillar2091.fas -c:Full_pir/TGD_CDS_withGar/Pillar2091_CDS.fas -s
 ./algndna_new Full_pir/Pillar2102_pro.pir output/Pillar2102.fas -c:Full_pir/TGD_CDS_withGar/Pillar2102_CDS.fas -s
 ./algndna_new Full_pir/Pillar2116_pro.pir output/Pillar2116.fas -c:Full_pir/TGD_CDS_withGar/Pillar2116_CDS.fas -s
 ./algndna_new Full_pir/Pillar2117_pro.pir output/Pillar2117.fas -c:Full_pir/TGD_CDS_withGar/Pillar2117_CDS.fas -s
 ./algndna_new Full_pir/Pillar2118_pro.pir output/Pillar2118.fas -c:Full_pir/TGD_CDS_withGar/Pillar2118_CDS.fas -s
 ./algndna_new Full_pir/Pillar2127_pro.pir output/Pillar2127.fas -c:Full_pir/TGD_CDS_withGar/Pillar2127_CDS.fas -s
 ./algndna_new Full_pir/Pillar2140_pro.pir output/Pillar2140.fas -c:Full_pir/TGD_CDS_withGar/Pillar2140_CDS.fas -s
 ./algndna_new Full_pir/Pillar2141_pro.pir output/Pillar2141.fas -c:Full_pir/TGD_CDS_withGar/Pillar2141_CDS.fas -s
 ./algndna_new Full_pir/Pillar2142_pro.pir output/Pillar2142.fas -c:Full_pir/TGD_CDS_withGar/Pillar2142_CDS.fas -s
 ./algndna_new Full_pir/Pillar2169_pro.pir output/Pillar2169.fas -c:Full_pir/TGD_CDS_withGar/Pillar2169_CDS.fas -s
 ./algndna_new Full_pir/Pillar2233_pro.pir output/Pillar2233.fas -c:Full_pir/TGD_CDS_withGar/Pillar2233_CDS.fas -s
 ./algndna_new Full_pir/Pillar2337_pro.pir output/Pillar2337.fas -c:Full_pir/TGD_CDS_withGar/Pillar2337_CDS.fas -s
 ./algndna_new Full_pir/Pillar2338_pro.pir output/Pillar2338.fas -c:Full_pir/TGD_CDS_withGar/Pillar2338_CDS.fas -s
 ./algndna_new Full_pir/Pillar2340_pro.pir output/Pillar2340.fas -c:Full_pir/TGD_CDS_withGar/Pillar2340_CDS.fas -s
 ./algndna_new Full_pir/Pillar2379_pro.pir output/Pillar2379.fas -c:Full_pir/TGD_CDS_withGar/Pillar2379_CDS.fas -s
 ./algndna_new Full_pir/Pillar2517_pro.pir output/Pillar2517.fas -c:Full_pir/TGD_CDS_withGar/Pillar2517_CDS.fas -s
 ./algndna_new Full_pir/Pillar2529_pro.pir output/Pillar2529.fas -c:Full_pir/TGD_CDS_withGar/Pillar2529_CDS.fas -s
 ./algndna_new Full_pir/Pillar2535_pro.pir output/Pillar2535.fas -c:Full_pir/TGD_CDS_withGar/Pillar2535_CDS.fas -s
 ./algndna_new Full_pir/Pillar2782_pro.pir output/Pillar2782.fas -c:Full_pir/TGD_CDS_withGar/Pillar2782_CDS.fas -s
 ./algndna_new Full_pir/Pillar2788_pro.pir output/Pillar2788.fas -c:Full_pir/TGD_CDS_withGar/Pillar2788_CDS.fas -s
 ./algndna_new Full_pir/Pillar2794_pro.pir output/Pillar2794.fas -c:Full_pir/TGD_CDS_withGar/Pillar2794_CDS.fas -s
 ./algndna_new Full_pir/Pillar2842_pro.pir output/Pillar2842.fas -c:Full_pir/TGD_CDS_withGar/Pillar2842_CDS.fas -s
 ./algndna_new Full_pir/Pillar2851_pro.pir output/Pillar2851.fas -c:Full_pir/TGD_CDS_withGar/Pillar2851_CDS.fas -s
 ./algndna_new Full_pir/Pillar2852_pro.pir output/Pillar2852.fas -c:Full_pir/TGD_CDS_withGar/Pillar2852_CDS.fas -s
 ./algndna_new Full_pir/Pillar2853_pro.pir output/Pillar2853.fas -c:Full_pir/TGD_CDS_withGar/Pillar2853_CDS.fas -s
 ./algndna_new Full_pir/Pillar2862_pro.pir output/Pillar2862.fas -c:Full_pir/TGD_CDS_withGar/Pillar2862_CDS.fas -s
 ./algndna_new Full_pir/Pillar2863_pro.pir output/Pillar2863.fas -c:Full_pir/TGD_CDS_withGar/Pillar2863_CDS.fas -s
 ./algndna_new Full_pir/Pillar2882_pro.pir output/Pillar2882.fas -c:Full_pir/TGD_CDS_withGar/Pillar2882_CDS.fas -s
 ./algndna_new Full_pir/Pillar2885_pro.pir output/Pillar2885.fas -c:Full_pir/TGD_CDS_withGar/Pillar2885_CDS.fas -s
 ./algndna_new Full_pir/Pillar2904_pro.pir output/Pillar2904.fas -c:Full_pir/TGD_CDS_withGar/Pillar2904_CDS.fas -s
 ./algndna_new Full_pir/Pillar2907_pro.pir output/Pillar2907.fas -c:Full_pir/TGD_CDS_withGar/Pillar2907_CDS.fas -s
 ./algndna_new Full_pir/Pillar2954_pro.pir output/Pillar2954.fas -c:Full_pir/TGD_CDS_withGar/Pillar2954_CDS.fas -s
 ./algndna_new Full_pir/Pillar2957_pro.pir output/Pillar2957.fas -c:Full_pir/TGD_CDS_withGar/Pillar2957_CDS.fas -s
 ./algndna_new Full_pir/Pillar2958_pro.pir output/Pillar2958.fas -c:Full_pir/TGD_CDS_withGar/Pillar2958_CDS.fas -s
 ./algndna_new Full_pir/Pillar3011_pro.pir output/Pillar3011.fas -c:Full_pir/TGD_CDS_withGar/Pillar3011_CDS.fas -s
 ./algndna_new Full_pir/Pillar3014_pro.pir output/Pillar3014.fas -c:Full_pir/TGD_CDS_withGar/Pillar3014_CDS.fas -s
 ./algndna_new Full_pir/Pillar3015_pro.pir output/Pillar3015.fas -c:Full_pir/TGD_CDS_withGar/Pillar3015_CDS.fas -s
 ./algndna_new Full_pir/Pillar3037_pro.pir output/Pillar3037.fas -c:Full_pir/TGD_CDS_withGar/Pillar3037_CDS.fas -s
 ./algndna_new Full_pir/Pillar3286_pro.pir output/Pillar3286.fas -c:Full_pir/TGD_CDS_withGar/Pillar3286_CDS.fas -s
 ./algndna_new Full_pir/Pillar3292_pro.pir output/Pillar3292.fas -c:Full_pir/TGD_CDS_withGar/Pillar3292_CDS.fas -s
 ./algndna_new Full_pir/Pillar3300_pro.pir output/Pillar3300.fas -c:Full_pir/TGD_CDS_withGar/Pillar3300_CDS.fas -s
 ./algndna_new Full_pir/Pillar3308_pro.pir output/Pillar3308.fas -c:Full_pir/TGD_CDS_withGar/Pillar3308_CDS.fas -s
 ./algndna_new Full_pir/Pillar3310_pro.pir output/Pillar3310.fas -c:Full_pir/TGD_CDS_withGar/Pillar3310_CDS.fas -s
 ./algndna_new Full_pir/Pillar3382_pro.pir output/Pillar3382.fas -c:Full_pir/TGD_CDS_withGar/Pillar3382_CDS.fas -s
 ./algndna_new Full_pir/Pillar3388_pro.pir output/Pillar3388.fas -c:Full_pir/TGD_CDS_withGar/Pillar3388_CDS.fas -s
 ./algndna_new Full_pir/Pillar3442_pro.pir output/Pillar3442.fas -c:Full_pir/TGD_CDS_withGar/Pillar3442_CDS.fas -s
 ./algndna_new Full_pir/Pillar3452_pro.pir output/Pillar3452.fas -c:Full_pir/TGD_CDS_withGar/Pillar3452_CDS.fas -s
 ./algndna_new Full_pir/Pillar3453_pro.pir output/Pillar3453.fas -c:Full_pir/TGD_CDS_withGar/Pillar3453_CDS.fas -s
 ./algndna_new Full_pir/Pillar3456_pro.pir output/Pillar3456.fas -c:Full_pir/TGD_CDS_withGar/Pillar3456_CDS.fas -s
 ./algndna_new Full_pir/Pillar3476_pro.pir output/Pillar3476.fas -c:Full_pir/TGD_CDS_withGar/Pillar3476_CDS.fas -s
 ./algndna_new Full_pir/Pillar3486_pro.pir output/Pillar3486.fas -c:Full_pir/TGD_CDS_withGar/Pillar3486_CDS.fas -s
 ./algndna_new Full_pir/Pillar3651_pro.pir output/Pillar3651.fas -c:Full_pir/TGD_CDS_withGar/Pillar3651_CDS.fas -s
 ./algndna_new Full_pir/Pillar3805_pro.pir output/Pillar3805.fas -c:Full_pir/TGD_CDS_withGar/Pillar3805_CDS.fas -s
 ./algndna_new Full_pir/Pillar3814_pro.pir output/Pillar3814.fas -c:Full_pir/TGD_CDS_withGar/Pillar3814_CDS.fas -s
 ./algndna_new Full_pir/Pillar3868_pro.pir output/Pillar3868.fas -c:Full_pir/TGD_CDS_withGar/Pillar3868_CDS.fas -s
 ./algndna_new Full_pir/Pillar3934_pro.pir output/Pillar3934.fas -c:Full_pir/TGD_CDS_withGar/Pillar3934_CDS.fas -s
 ./algndna_new Full_pir/Pillar3950_pro.pir output/Pillar3950.fas -c:Full_pir/TGD_CDS_withGar/Pillar3950_CDS.fas -s
 ./algndna_new Full_pir/Pillar3955_pro.pir output/Pillar3955.fas -c:Full_pir/TGD_CDS_withGar/Pillar3955_CDS.fas -s
 ./algndna_new Full_pir/Pillar3978_pro.pir output/Pillar3978.fas -c:Full_pir/TGD_CDS_withGar/Pillar3978_CDS.fas -s
 ./algndna_new Full_pir/Pillar4002_pro.pir output/Pillar4002.fas -c:Full_pir/TGD_CDS_withGar/Pillar4002_CDS.fas -s
 ./algndna_new Full_pir/Pillar4006_pro.pir output/Pillar4006.fas -c:Full_pir/TGD_CDS_withGar/Pillar4006_CDS.fas -s
 ./algndna_new Full_pir/Pillar4023_pro.pir output/Pillar4023.fas -c:Full_pir/TGD_CDS_withGar/Pillar4023_CDS.fas -s
 ./algndna_new Full_pir/Pillar4050_pro.pir output/Pillar4050.fas -c:Full_pir/TGD_CDS_withGar/Pillar4050_CDS.fas -s
 ./algndna_new Full_pir/Pillar4053_pro.pir output/Pillar4053.fas -c:Full_pir/TGD_CDS_withGar/Pillar4053_CDS.fas -s
 ./algndna_new Full_pir/Pillar4055_pro.pir output/Pillar4055.fas -c:Full_pir/TGD_CDS_withGar/Pillar4055_CDS.fas -s
 ./algndna_new Full_pir/Pillar4060_pro.pir output/Pillar4060.fas -c:Full_pir/TGD_CDS_withGar/Pillar4060_CDS.fas -s
 ./algndna_new Full_pir/Pillar4233_pro.pir output/Pillar4233.fas -c:Full_pir/TGD_CDS_withGar/Pillar4233_CDS.fas -s
 ./algndna_new Full_pir/Pillar4242_pro.pir output/Pillar4242.fas -c:Full_pir/TGD_CDS_withGar/Pillar4242_CDS.fas -s
 ./algndna_new Full_pir/Pillar4290_pro.pir output/Pillar4290.fas -c:Full_pir/TGD_CDS_withGar/Pillar4290_CDS.fas -s
 ./algndna_new Full_pir/Pillar4304_pro.pir output/Pillar4304.fas -c:Full_pir/TGD_CDS_withGar/Pillar4304_CDS.fas -s
 ./algndna_new Full_pir/Pillar4311_pro.pir output/Pillar4311.fas -c:Full_pir/TGD_CDS_withGar/Pillar4311_CDS.fas -s
 ./algndna_new Full_pir/Pillar4312_pro.pir output/Pillar4312.fas -c:Full_pir/TGD_CDS_withGar/Pillar4312_CDS.fas -s
 ./algndna_new Full_pir/Pillar4322_pro.pir output/Pillar4322.fas -c:Full_pir/TGD_CDS_withGar/Pillar4322_CDS.fas -s
 ./algndna_new Full_pir/Pillar4488_pro.pir output/Pillar4488.fas -c:Full_pir/TGD_CDS_withGar/Pillar4488_CDS.fas -s
 ./algndna_new Full_pir/Pillar4499_pro.pir output/Pillar4499.fas -c:Full_pir/TGD_CDS_withGar/Pillar4499_CDS.fas -s
 ./algndna_new Full_pir/Pillar4516_pro.pir output/Pillar4516.fas -c:Full_pir/TGD_CDS_withGar/Pillar4516_CDS.fas -s
 ./algndna_new Full_pir/Pillar4527_pro.pir output/Pillar4527.fas -c:Full_pir/TGD_CDS_withGar/Pillar4527_CDS.fas -s
 ./algndna_new Full_pir/Pillar4568_pro.pir output/Pillar4568.fas -c:Full_pir/TGD_CDS_withGar/Pillar4568_CDS.fas -s
 ./algndna_new Full_pir/Pillar4609_pro.pir output/Pillar4609.fas -c:Full_pir/TGD_CDS_withGar/Pillar4609_CDS.fas -s
 ./algndna_new Full_pir/Pillar4657_pro.pir output/Pillar4657.fas -c:Full_pir/TGD_CDS_withGar/Pillar4657_CDS.fas -s
 ./algndna_new Full_pir/Pillar4686_pro.pir output/Pillar4686.fas -c:Full_pir/TGD_CDS_withGar/Pillar4686_CDS.fas -s
 ./algndna_new Full_pir/Pillar4697_pro.pir output/Pillar4697.fas -c:Full_pir/TGD_CDS_withGar/Pillar4697_CDS.fas -s
 ./algndna_new Full_pir/Pillar4698_pro.pir output/Pillar4698.fas -c:Full_pir/TGD_CDS_withGar/Pillar4698_CDS.fas -s
 ./algndna_new Full_pir/Pillar4700_pro.pir output/Pillar4700.fas -c:Full_pir/TGD_CDS_withGar/Pillar4700_CDS.fas -s
 ./algndna_new Full_pir/Pillar4722_pro.pir output/Pillar4722.fas -c:Full_pir/TGD_CDS_withGar/Pillar4722_CDS.fas -s
 ./algndna_new Full_pir/Pillar4726_pro.pir output/Pillar4726.fas -c:Full_pir/TGD_CDS_withGar/Pillar4726_CDS.fas -s
 ./algndna_new Full_pir/Pillar4883_pro.pir output/Pillar4883.fas -c:Full_pir/TGD_CDS_withGar/Pillar4883_CDS.fas -s
 ./algndna_new Full_pir/Pillar4923_pro.pir output/Pillar4923.fas -c:Full_pir/TGD_CDS_withGar/Pillar4923_CDS.fas -s
 ./algndna_new Full_pir/Pillar4924_pro.pir output/Pillar4924.fas -c:Full_pir/TGD_CDS_withGar/Pillar4924_CDS.fas -s
 ./algndna_new Full_pir/Pillar4927_pro.pir output/Pillar4927.fas -c:Full_pir/TGD_CDS_withGar/Pillar4927_CDS.fas -s
 ./algndna_new Full_pir/Pillar4933_pro.pir output/Pillar4933.fas -c:Full_pir/TGD_CDS_withGar/Pillar4933_CDS.fas -s
 ./algndna_new Full_pir/Pillar4948_pro.pir output/Pillar4948.fas -c:Full_pir/TGD_CDS_withGar/Pillar4948_CDS.fas -s
 ./algndna_new Full_pir/Pillar4978_pro.pir output/Pillar4978.fas -c:Full_pir/TGD_CDS_withGar/Pillar4978_CDS.fas -s
 ./algndna_new Full_pir/Pillar4992_pro.pir output/Pillar4992.fas -c:Full_pir/TGD_CDS_withGar/Pillar4992_CDS.fas -s
 ./algndna_new Full_pir/Pillar5105_pro.pir output/Pillar5105.fas -c:Full_pir/TGD_CDS_withGar/Pillar5105_CDS.fas -s
 ./algndna_new Full_pir/Pillar5112_pro.pir output/Pillar5112.fas -c:Full_pir/TGD_CDS_withGar/Pillar5112_CDS.fas -s
 ./algndna_new Full_pir/Pillar5149_pro.pir output/Pillar5149.fas -c:Full_pir/TGD_CDS_withGar/Pillar5149_CDS.fas -s
 ./algndna_new Full_pir/Pillar5209_pro.pir output/Pillar5209.fas -c:Full_pir/TGD_CDS_withGar/Pillar5209_CDS.fas -s
 ./algndna_new Full_pir/Pillar5232_pro.pir output/Pillar5232.fas -c:Full_pir/TGD_CDS_withGar/Pillar5232_CDS.fas -s
 ./algndna_new Full_pir/Pillar5262_pro.pir output/Pillar5262.fas -c:Full_pir/TGD_CDS_withGar/Pillar5262_CDS.fas -s
 ./algndna_new Full_pir/Pillar5267_pro.pir output/Pillar5267.fas -c:Full_pir/TGD_CDS_withGar/Pillar5267_CDS.fas -s
 ./algndna_new Full_pir/Pillar5308_pro.pir output/Pillar5308.fas -c:Full_pir/TGD_CDS_withGar/Pillar5308_CDS.fas -s
 ./algndna_new Full_pir/Pillar5313_pro.pir output/Pillar5313.fas -c:Full_pir/TGD_CDS_withGar/Pillar5313_CDS.fas -s
 ./algndna_new Full_pir/Pillar5315_pro.pir output/Pillar5315.fas -c:Full_pir/TGD_CDS_withGar/Pillar5315_CDS.fas -s
 ./algndna_new Full_pir/Pillar5317_pro.pir output/Pillar5317.fas -c:Full_pir/TGD_CDS_withGar/Pillar5317_CDS.fas -s
 ./algndna_new Full_pir/Pillar5318_pro.pir output/Pillar5318.fas -c:Full_pir/TGD_CDS_withGar/Pillar5318_CDS.fas -s
 ./algndna_new Full_pir/Pillar5320_pro.pir output/Pillar5320.fas -c:Full_pir/TGD_CDS_withGar/Pillar5320_CDS.fas -s
 ./algndna_new Full_pir/Pillar5325_pro.pir output/Pillar5325.fas -c:Full_pir/TGD_CDS_withGar/Pillar5325_CDS.fas -s
 ./algndna_new Full_pir/Pillar5341_pro.pir output/Pillar5341.fas -c:Full_pir/TGD_CDS_withGar/Pillar5341_CDS.fas -s
 ./algndna_new Full_pir/Pillar5362_pro.pir output/Pillar5362.fas -c:Full_pir/TGD_CDS_withGar/Pillar5362_CDS.fas -s
 ./algndna_new Full_pir/Pillar5370_pro.pir output/Pillar5370.fas -c:Full_pir/TGD_CDS_withGar/Pillar5370_CDS.fas -s
 ./algndna_new Full_pir/Pillar5412_pro.pir output/Pillar5412.fas -c:Full_pir/TGD_CDS_withGar/Pillar5412_CDS.fas -s
 ./algndna_new Full_pir/Pillar5546_pro.pir output/Pillar5546.fas -c:Full_pir/TGD_CDS_withGar/Pillar5546_CDS.fas -s
 ./algndna_new Full_pir/Pillar5552_pro.pir output/Pillar5552.fas -c:Full_pir/TGD_CDS_withGar/Pillar5552_CDS.fas -s
 ./algndna_new Full_pir/Pillar5567_pro.pir output/Pillar5567.fas -c:Full_pir/TGD_CDS_withGar/Pillar5567_CDS.fas -s
 ./algndna_new Full_pir/Pillar5572_pro.pir output/Pillar5572.fas -c:Full_pir/TGD_CDS_withGar/Pillar5572_CDS.fas -s
 ./algndna_new Full_pir/Pillar5583_pro.pir output/Pillar5583.fas -c:Full_pir/TGD_CDS_withGar/Pillar5583_CDS.fas -s
