>P1;ENSDARG00000034453

--------------------------------------------------
----------------MKVKQGC---DAGVPYTTEEDLLNSPEITPEDVL
GLQKIT--DNYLCGPEQNVHKIDFTRFKIRDMETGTVLFEITKPPTS--E
T-GEDRMDFEQNAGRFVRYQFTPAFLRLRQVGATVEFTVGDSPINNFRMI
ERHYFRGQLLKSFDFEFGFCIPSSKNTCEHIYEFPPLSEDIMREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGP
*
>P1;ENSAMXG00000024390

--------------------------------------------------
----------------MK------------------------KILMDN-I
LLCFFT--LDYLCSPEDNVYNIDFTRFKIRDMETGTVLFEITKPPAL--D
K-GGDKRDIDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMI
ERHYFRDQLLKSFDFEFGFCIPSSKNTCEHIYEFPPLSEDIMREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSGACG00000008624

--------------------------------------------------
----------------MKVQQGCHSSNMGIPVTTEEELRRNTVITPDDVL
GLQKIT--KNYLCSPEENVHMIDFTRFKIRDMETGTVLFEITKPPTDVSR
Q-AEGRKQCDPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMI
ERHYFRDQLLKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDIMREMILNPY
ETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSTRUG00000012195

MSYSCTN---RGNSQDPSSA--KKAAGNNPGRDT------GG-TD-----
--------SSPKQTATMKVKKGCNSAEVGVPVTTEEDLLTSAVVTPEDVL
GLQKIT--ENYLCSPDENIFNIDFTRFKIRDMETGTVLFEITKPPST--D
K-TGDKRDMDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDLPIENFRMI
ERHYFRERLLKSFDFEFGFCMPKSKNTCEHIYEFPPLSEDSIREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSORLG00000002577

---------------------------------S------SG--------
-------TSSPKQT-AMRVKKGCNSAEVGVPETTEEDLLANAVISPEDVL
GLQKIT--ENYLCSPDENIYNIDFTRFKIRDMETGTVLFEITKPPST--D
K-SGEKRDIDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPIENFRMI
ERHYFREKLLKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDVIREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSGACG00000020475

------------------AA--KKPAGDNPGRDT------GG-TDR----
-----SSSSSPQDTAAMKVKKGCNATDAGVPVTTEEDLLGGSGVTPEDVL
GLQKIT--ENYLCSPDENIFNIDFTRFRIRDMETATVLFEITKPPAA--D
K-AGEKRDVDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPIENFRMI
ERHYFREKLLKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDIIREMVLHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSTRUG00000016070

--------------------------------------------------
----------------MKVQQGCNSSDMGIPVRTEEELRRNTVITPEDVL
GLQKIHKDVNYLCSPEDNVHMIDFTRFKIRDMETGTVLFEITKPPTP---
--AGDKKLSDPNAGRFVRYQFTPAFLHLRQVGATVEFTVGETPINNFRMI
ERHYFRDQLLKSFDFEFGFCMPSSKNTCEHIYEFPALSEEIMREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSONIG00000008183

--------------------------------------------------
----------------MKVQQGCNSSDMGIPVTTEEELRKHTVITPEDVL
GLQKIT--KNYLCSPEENVHMIDFTRFKIRDMETGTVLFEITKPPTP---
--AGGKKQCDPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMI
ERHYFRDQLLKSFDFEFGFCMPSSKNTCEHIYEFPTLSEETMREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSONIG00000008702

MSYSCTS---RGNSQDPSSA--KKPAGSNPARDA------GG-TDSG---
TD--STSNGSPKQTAAMKVKKGCNSTDVGVPVTTEEQLLASTVITPEDVL
GLQKIT--ENYLCSPEENIYNIDFTRFKIRDMETGTVLFEITKPPST--D
K-ASEKRDIDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDRPIENFRMI
ERHYFREKLLKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDIIREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSTNIG00000016130

MSYSCTN---RGNSQDPSSA--KDAAGDNPGRDT------GG-TD-----
--------ASPKQTAAMKVKKGCNSAEVGVPVTTEEDLLSSAVITPEDVL
GLQKIT--ENYLCSPDENIFSIDFTRFKIRDMETGTVLFEITKPPTT--D
K-TGDKRDIDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDLPIENFRMI
ERHYFRERLLKSFDFEFGFCMPRSKNTCEHIYEFPPLSEDSIQEMILHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGR
*
>P1;ENSXMAG00000007806

MSYSCTS---RGNSQDPSNA--------NPARTT------GG-TDGG---
TD--STGNGSPKQTAVMKVKKGCNSAEVEVPVTTEEELLGRTVITPEDVL
GLQKIT--EHYLCSPDENVFNIDFTRFKIRDMETSTVLFEITKPPST--D
K-SGEKRDIDLNAGRFVRYQFTPAFLRLRQVGATVEFTVGDMPIENFRMI
ERHYFREKLLKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDTIREMVLHPY
ETQSDSFYFVDNKLVMHNKADYSYNGGT
*
>P1;ENSXMAG00000011781

--------------------------------------------------
----------------MKVQQGCNSSDMGIPVRTEEELRKNTVITPEDVL
GLQKIT--ENYLCAPEENVHMIDFTRFKIRDMETGTVLFEITKPPTP---
---GGLKQCDPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMI
ERHYFRDKLLKSFDFEFGFCMPSSKNTCEHIYEFPTLSEETMHEMIQHPY
ETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSORLG00000008116

--------------------------------------------------
----------------MKVQQDCNSADMGIPVRTEEELRKNTVITPEDVL
GLQKIT--KNYLCSPEENVHRIDFTRFKIRDMETGTVLFEITKPPTP---
---GGVKLCDPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMI
ERHYFRDKLLKSFDFEFGFCMPSSKNTCEHIYEFPALSEEMMREMIQHPY
ETQSDSFYFVDNKLVMHNKADYSYCGGP
*
>P1;ENSAMXG00000017747

--------------------------------------------------
----------------MRVKAGN---DAGLPCTTEQELLQNQTIRPEDVL
GLQNIT--ENYLCSPDDNVHKIDFTRFKIRDMETGIVLFEITKPPLA--E
S-SEDRKDIDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMI
ERHYFRGQLLKSFDFEFGFCIPSSKNTCEHIYEFPPLSEELIHEMILHPY
ETQSDSFYFVDNKLVMHNKADYSYTGAQ
*
>P1;ENSDARG00000044362

MSYSCTS---TGNSQDPSSS--KKSGGVNPGSCSSSNGDTGNGNNRH-SI
RG--SKANSKPDSTEAMKVKKGCNTTDLGVPVTTEEELLANKTISPEDVL
GLQKIT--ENYLCSPEDNLYNIDFTRFKIRDMETGTVLFEITKPPST--D
R--GDKRDVDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMI
ERHYFREQLLKSFDFEFGFCIPSSKNTCEHIYEFPPLSEDLIREMILHPY
ETQSDSFYFVDNKLVMHNKADYSYSGGP
*
>P1;ENSLOCG00000005507

MSYSCIGTEAVCNSQDSSSSSAQRSGTSKSNNPS------GG-SGRSAES
SDHQTQDTPTPKPLVAMRVKKGCNSTETGVPVTTEEELLRKPVITPEDVL
GLQKIT--ENYLCSPDENVYSIDFTRFKIRDMETGTVLFEITKPPAA--E
RGQGDKKDLDPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPINNFRMI
ERHYFREQLLKSFDFEFGFCIPSSKNTCEHIYEFPPLSEEIMREMILHPY
DTQSDSFYFVDNKLVMHNKADYSYSGGP
*
