>P1;ENSAMXG00000019311

MAAIPSSGSLVATTDYYRRRLGSTSS-SSSCGSSEYSGEVIPHHPGLPK-
QDSGHWWSSFFFGKPNQPGMGTLTEEAQQKGGV-MSVSDGQVMCIARDMV
MKRQA----SESSDAGKSEAGTSPP--S
*
>P1;ENSGACG00000011977

MAAIPSTGSLIATHDYYRRRLGSNSS-NSSCGSAEYTGEVIPHPPGLQR-
QDSGHWWTSFFFAKQNQPGMPNGS-DT-QKNST-YTVANGQVTCVAREMV
LNRKL----SVSSDNGKSETSTPPPTSA
*
>P1;ENSTRUG00000005031

MAAIPAGGSLVATTDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPK-
QDSGHWWSSFFFGKQ--PGMSPLTE---EKAGV-S-AAATNISCVAREMV
MQRQA----SESSDAGSPAS-------S
*
>P1;ENSAMXG00000007577

MAAIPSGGSLVATHDYYRRRIGSTSS-NSSCGSSEYTGEVIPHHPALPR-
QDSGHWWSSFFFGKQNQIGTPNGF-DAQQKTGT-YTVTNGQVTCIAREMV
MKRQL----SESSDSGKPELTTPPA--S
*
>P1;ENSDARG00000031317

MAAIPASGSLVATHDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPK-
QDSGHWWSSFFFGKQNLPGMGTVAEEAQQKSGV-VSVTNGQVTCVAREMV
M-RQA----SESSDGGKSEAGN-----S
*
>P1;ENSONIG00000014865

MAAIPAGGSLVATTDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPK-
QDSGHWWSSFFFGKQ--PGMTPLTEEAQHKAGVSGVVTNGQITCVAREMV
MQRQA----SESSDAGSPTS-------S
*
>P1;ENSONIG00000016786

MAAIPSSGSLIATHDYYRRRIGSTSS-NSSCSSAEYTGEAIPHHPALPR-
QDSDHWWTSFFFAKQNQPGMQNGS-ENQNRNST-YTVANGQVTCIARQMV
LNRQI----SESSENGKSEPMSPPP--V
*
>P1;ENSXMAG00000009169

MAAIPAGGSLVATTDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPK-
QDSGHWWSSFFFGKQ--PGMTPLTEEAHQKVGVSGAVTTGQITCIAKEMV
LQRQA----SESSEAGSPVS-------S
*
>P1;ENSDARG00000007682

MAAIPSSGSLIATHDYYRRRIGSTSS-NSSCSSSEYTGEVIPHPPGLAR-
QDSGHWWSSFFFGKQNQMGTPNGF-ESQQKTGT-YTVTNGQVTCVAREIV
MKRHL----SESSDSGKEP-GSPLP--S
*
>P1;ENSORLG00000018263

MAAIPAGGSLVATTDYYRRRIGSTSSSSSSCGSSEYSGEVIPHHPGLPK-
QDSGHWWSSFFFGKQ--PGMTTLTEEAQQKVGV-LGAAGGQLTCVAREMV
-QRQA----SESSDAGSPAS-------S
*
>P1;ENSGACG00000010310

MASIPAGGSLVATNDYYRRRIGSTSS-SSSCGSSEYTGEVIPHHPGLPK-
QDSGHWWSSFFFGKQ--PGMTPLTEEAQQKAGVQGTVTNGQITCVAQEMV
MQRQSRPDPSRTSEGGRVE---------
*
>P1;ENSORLG00000014723

MAAIPSSGSLIATHDYYRRRLGSSSS-SSSCGSSEYTGEVIPHHPALPR-
QDSGHWWTSFFFTKQNP-A--NGS-D-NQKTRS-YTVANGQVSCIAKEMV
LNRQL----SESSESGKVEPTTPP--PV
*
>P1;ENSTRUG00000005040

MAAIPSSGSLVATHDYYRRRLGSASS-SSSCGSAEYTGEVIPHHPGLPR-
QDSGHWWTSFFFAKQNQPGLQNGS-D-LQKNGT-YTVANGQVTCIAKEMV
LKRQL----SETSDSGKPEQQQTTPVPP
*
>P1;ENSTNIG00000002328

MAAIPSSGSLVATHDYYRRRLGSASS-SSSCGSAEYTGEVIPHHPGLPR-
QDSGHWWTSFFFAKQNQPGLQNGS-D-PQKSGT-YTVANGQVTCIAREMV
QKRQL----SETSEGGKPEQPAPPTPPS
*
>P1;ENSLOCG00000005173

MAAIPSSGSLIATHDYYRRRLGSTSS-NSSCGSSEYAGEVIPHHPGLPKH
QDPGHWWSSFFFGKHNQPTMTTLT-ESPQNSGT-FSVTNEKVTCGLAQEV
MKRQL----SDASESGKPEAGSS----A
*
