>P1;ENSORLG00000010277

--------LQPNMDRKIPDFSGTWEMKSSENFEELLKAL---GVNIMLRM
IAVKAASKPLVEITQDGETLSIKTSTTVRTTHITFTVGQEFNETTVDGRP
CTSFPVWETDNKISCEQTLQKGDGPKTSWTREITSDGKLILTMRADDVIC
TRVYERQ
*
>P1;ENSTNIG00000017548

--------LSINMERKTADFSGKWTMKSSENFEELLKVL---GVNVFFRK
IAVAAASSPVVEITQQGDDLSIKTSTSVRTTNVSFTVGQSFSETTVDGRA
CTSFPKWETDSKISCEQTLQKGDGPKTGWTRELTNDGELILTMSAGDVVC
TRVYQRE
*
>P1;ENSONIG00000006388

LS-----KLSPNMERRIPDFSGTWEMKSSENFEELLKVL---GVNVMLRK
IAVKAASKPLVEITQDGETLSIKTSTTVRTTHITFTVGQEFNETTVDGRP
CTSFPRWETDSKISCEQTLQKGEGPKTSWTREITSDSKLILTMRADDVIC
TRVYERQ
*
>P1;ENSORLG00000002668

--------AHSEMENKATDFSGKWRMKSSENFEELLKAL---GVNVFLRK
IAVAAASSPAVEIAQQGDNLSIKTSTSVRTTHVSFTVGQSFSEATVDGRP
CTSFPKWETDRKISCEQTLLKGDGPKTSWTRELTNDGELILTMTAGEVVC
TRVYERE
*
>P1;ENSGACG00000003295

----------------TTDFSGKWKMKSSERFEDLLKALA--GVNVFLRK
IAVRAASSPAVEITQQDESLSIKTSTSVRTTHVSFTVGQSFNETTVDGRP
CTSFPQWETDSKISCEQTVPKGEGPKTAWTRELTNDGELILTMTAGDVVC
TRVYERE
*
>P1;ENSGACG00000011813

----------------IPDFSGTWEMKSSENFEELLKKL---AVNKMLRL
IAVKAASKPLVEITQDGETLSIKTSTTVRTTHITFTVGQEFNEATVDGRP
CTSFPRWETDSKITCEQTLPKGEGPKTSWTREITNDGKLILTMAADDVIC
TRVYERQ
*
>P1;ENSONIG00000019709

PIILISASACTEMENKVTDFSGKWKMKSSENFEELLRAL---GVNVFLRK
IAVAAASSPAVEITQQEETLSIKTSTSVRTTNVSFTVGQSFSETTVDGRP
CTSFPKWETDRKISCEQTLQKGDGPKTAWTRELTNDGELILTMTAGDVVC
TRVYERE
*
>P1;ENSXMAG00000014642

AHNQTAALICTEMENKVTDFSGKWKMKSSENFEELLKALESVGVNVFLRK
IAVAAASSPAVEITQQGETLSIKTSTSVRTTNVSFTVGQSFNEATVDGRP
CTSFPKWETDRKISCEQTLPKGDGLKTAWTRELTNDGELILTMTAGDVVC
TRVYERE
*
>P1;ENSDARG00000030449

--------MESNTEKTFADFSGSWKMKSSENFEELLKAL---GVNVFLRK
IAVAAASKPAVEISQQGESLSVQTSTSVRTTHVSFTVGESFNETTVDGRP
CTSFPKWETDCKISCEQTLQKGEGPETSWTRELTNDGQMILTMRAGDVVC
TRVYERD
*
>P1;ENSAMXG00000009966

------------MEGKITDFSGTWKMKSSENFEELLKAL---GVNVFLRK
IAVAAASKPSVEISQQGETLSIQTSTSVRTTHVSFTVGESFNEATVDGRP
CTSFPKWETDRKITCEQTLQKGEGPKTSWTRELTNDGELILTMSAADVVC
TRVYERE
*
>P1;ENSDARG00000073978

------------MDRKIPDFAGTWKMKSSENFEELLKAL---GVNVMLRK
IAVAAASKPSVEITQEGETLTIKTSTSVRTTNVTFTVGQEFNEATVDGRP
CTSFPRWVTDSKISCEQTLQKGEGPKTSWTREITNDAELILTMTADDVVC
TRVYVRE
*
>P1;ENSTNIG00000008055

--------IKSAMERKVPNFAGTWEMKSSENFDELLKKL---GVNVMMRV
IAVKAASKPLVEITQDGETLSIKTSTSVRTTHITFTVGQEFNEATVDGRP
CTSFPRWESDRKISCEQTLLKGEGPKTSWTRELTNAGQLILTMQADDVVC
TRVYERQ
*
>P1;ENSXMAG00000016304

------------MERQIPDFSGTWEMKSSENFEELLKTL---GVNVMLRK
IAVKAASKPLVEITQNGETLSIKTSTTVRTTHINFTVGQEFNEATVDGRP
CTSFPRWETDSKISCEQTLQKGEGPKTSWTREITSDGKLILTMRADDVIC
TRVYERQ
*
>P1;ENSTRUG00000011951

------------MERKTADFSGKWTMKSSENFEELLKALG-SGVNVFFRK
MAVAAASSPVVEISQQGEELSIKTSTSVRTTNISFTVGQSFSETTVDGRA
CTSFPRWETDSKISCEQTLQKGDGPKTGWTRELTNDGELILTMTAGDVVC
TRVYQKE
*
>P1;ENSLOCG00000006421

------------MEGKIPDFSGNWKMKSSENFEELLKAL---GVNVMLRK
IAVAAASKPAVEIRQDNETFYIKTSTTVRTTEINFTVGQEFSEQTVDGRP
CTSFPCWEGENKIVCEQTLLKGDGPKTAWTREMTNDGELILTMTADDVVC
TRVYVKE
*
