>P1;ENSONIG00000015040

LNWATWH--------------------------VKSSL---ICHI-----
------------LYYFQPKCKISASRKLSLKILLLTRATEDLEA-EKAAN
EEEKVRYLREKLPPLQLSGLNIDDLQKVCKEIHEKIHLVDEDRYDCEAKV
LKNYRDINELQLKVQDLGGKFKKPALRKVRVSADEMLKALFGSKTKGSMD
LRANLKSVKKEDIKQEKELTMEVGDWRKNVEAMSGMQGRKKMFDAAGGA-
-Q
*
>P1;ENSXMAG00000005430

------------------------------------------MNP-----
-------------KGDKPKSKISASRKLSLKMLLLQRACEDLER-ERQER
EEEKGRYLKEKLPPLQLSGLSLDDLQKLCKQLHEKIDIVDEERYDCEHKV
SKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTGGGA-
-Q
*
>P1;ENSAMXG00000005689

QGRPK-------------------------------------GNP-----
------------KAFDKPKCKISASRKLSLKMLLLNRAMEDLER-EKQDR
DEEKIRYLDEKMPPLQLAGLSLADLQNLCRELYEKIDVVDEERYDCENKV
IKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDIKQEKVLTSEVGDWRKNVEAMSGMEGRKKMFDAAGGG-
-Q
*
>P1;ENSGACG00000019744

--------------------------------------------------
--------------SHKKLPIVSSGHCLTLYISTETR----LQVKKAAAF
LCEKVRYIGENLPPLQLSGLSVDELQKMVKELHSRIDVVDEERYDCESKV
GKHNKDIHELKLKIQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRSNLKSVKKED-----VLTSEVGDWRKNVEAMSGMEGRKKMFDTAGGP-
-Q
*
>P1;ENSORLG00000014669

PHRT-------------------------------R-----AMNP-----
-------------KWDKPKSKISASRKLSLKMLLLTRACEDLEK-EKLER
EEEKVRYLGEKLPPLQLSGLSLDELQKLCKQLHEKIDVVDEERYDCEHKV
VKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTGGGA-
-Q
*
>P1;ENSGACG00000012962

L-------------------------------------------------
-------------YYFQPKSKISASRKLSLKILLLTRATEQLEA-EKAAR
EEEKVRYLAEKLPPLQLLGLNRDDLQKVCTEIHEKIDNADEERYDYEHKV
FKNSRDIHQLNLKVQDLGGKFKKPALRKVRVSADEMLKALFGSKNKASMD
LRANLKSVKKEDIKQEKELTLEVGDWRKNVEAMSGMEGRKKMFDFSSRPL
MK
*
>P1;ENSTRUG00000015573

MN------------------------------------------------
-------------KGEKPKSKITASRKLSLKKLLLTKACEDLEQ-EKQER
EEEKVRYLGDKIPPLQVSGMAMEDLQNLCKQLHSKIEVVDEERYDCESKV
KKHNNDIHELKLKIQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTGGAG-
-Q
*
>P1;ENSDARG00000073766

MGDPI-----------------------------RR-----PGNP-----
------------KVDNKPKSKISASRKLSLKIMLLNRAMEDLER-EKQER
LEEKNCYLKEKHPPLQLSGLSLEELQNLCKQLYSKIDTVDEERYDYEDKV
KKHNKDINELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDIKQEKVLTSEVGDWRKNVEAMSGMEGRKKMFDAAGGG-
-Q
*
>P1;ENSDARG00000042559

MADDD----------------------------TPQ-----PLGP-----
------------RVQAKPKSKISASRKLSLKILLLQRAMEELEQ-EKVSR
DEEKVKYLSEKLPPLQITGLQLEELQKLCRQLHAKIDSVDEERYDFEAKV
VKNNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDIKQEKVMSTEVGDWRKNVEAMSGMEGRKKMFDAAGGG-
-Q
*
>P1;ENSAMXG00000003900

SSMQD----------------------------APS-----PMSP-----
------------RPQAKPKSKISASRKLSLKILLLQRAMEDLEQ-EKTDR
DEEKVRYLGEKLPPLQLSGLAMDELQKLCKQLHAKVDAVDEERYDFEAKV
VKNNKEIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDIKQEKVLTTEVGDWRKNVEAMSGMEGRKKMFDAAGG--
-Q
*
>P1;ENSONIG00000011575

MN------------------------------------------P-----
-------------RGEKPKSKISASRKLSLKMLLLTRACEDLEK-ERQER
EEEKVRYLGEKLPPLQLSGMPLKELQELCKQLHTKIDIVDEERYDCESKV
NKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTGGGA-
-Q
*
>P1;ENSTNIG00000011034

MN------------------------------------------------
-------------KGEKPKSKISASRKLSLKKLLLTKACEDLEQ-EKQER
EEEKVRYLGEKIPPLQVSGLSLEELQNLCRQLHSKIDVVDEERYDCESKV
KKHNNDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHKGSMD
LRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTGGVA-
-Q
*
>P1;ENSLOCG00000016892

MTDDQ-QGELFTETVIEETEMETVVEEEQEAEPEPEPEPPKPAPPKKAAP
SPNTEPPSKIVVETHDKPKSKISASRKLSLKMLMLGKAKEELEK-EKVDR
DEEKVKYLAERVPPLQLTGLTLEDLQKLCRQLHEKIDVVDEERYDIEAKV
NKNAREIHDLNLKIMDLRGKFKRPALRRVRVSADAILHSLLGSKHKASLD
LRANLKSVKKEDT--EKVLTSEVGDWRKNVEAMSGMEGRKKMFDAAGSA-
-Q
*
