>P1;ENSXMAG00000011880

M-----SF--SGEAMLKAVEAPLFWLGVLTAAWLSVCSVYRLLSGFRVWV
LGNGRLISPNKLGKWAVVTGATDGIGKAYAEEL-ARRGFAIV-LISRSQE
KLDDVSKAIASKCGVETKTIAADFSA-IDIYAKIEEGLAGLEIGLLVNNV
GTSYSYPEFFLNIPNLDTFIDTMININITSVCQMTRLVLPQ--MVERKKG
AILNISSASGMYPVPLLTVYSASK--AFVDFFSRGLQAEYKSKGIIIQSI
LPFFVATKMSRIRRPTLDRPSPEHYVAAELNTVGLQTQTNGYLPHAIMGW
VTTALLPAKMLNSYVMGMGLSQRARYLKKQKQ-----G---------
*
>P1;ENSAMXG00000013705

I-----EVFSELEKMLHGAESVLLWVGALTTASLALWILYRLLSGFRIWV
MGNGDLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFSMM-LISRTQE
KLDDVAQSLERRYKVETKTVAVDFGQ-VDIYPKIETALSGLEIGVLVNNV
GISYPYPEFFLHIPDLDNFINTMINVNITSVCQMTRLVLPR--MEARAKG
VILNISSASGMYPVPLLTVYSSTK--AFVDFFSRGLQAEYKSKGIIIQSV
LPFFVATKMTKIRKPTLDKPTPDRYVAAELTTVGLQDQTNGYFPHAVMGW
LTTVLVPINLVIYFGMRMNKAQRGGYLRRRKLR--------------
*
>P1;ENSTRUG00000016257

V-----NTMSTGEALLRAAEAPLFWLGALTASWASLCLVYRLLSGFKVWV
LGNGRFMSPHKLGKWAVVTGATDGIGKAYAEDL-ARRGFAIV-LISRSQD
KLDELSKAIASKCGVETKTIAADFSC-LDIYSKIEAGLAGLEIGVLVNNV
GISYSYPEFFLDVPNLDTVSDSVISGLFVAIFPLAHVSLLS---VCRKRG
AILNISSASGMYPVPLLTIYSASK--AFVDFFSRGLQAEYKSRGIVIQSV
LPFFVVTKMSKIRRPTLTAPSAEHYVSAELNTVGLQTQTNGYLPHAIMGW
VTTALLPAKILTGHIMRMNLSMRAYNLKKQKE-----K---------
*
>P1;ENSGACG00000006929

M-----QTC--SEQGFP-LKKQQAWLIVMFSLFRGMWLFLFLLSSSADSL
RPPRGLRRP-N-SRGIIVTGATDGIGKSYAEEL-ARRGFAMM-LISRSQD
KLDDVAMSLKEQFKVETRTIAADFGK-TDIYNKIEAGLAGLEIGVLVNNV
GVSYPYPEYYLQIPDLDNFITNMINVNITSVCQMTRLVLPK--MTERSKG
VILNISSASGMYPVPLLTAYSSTK--AFVDFFSRGLHEEYRRQGIIIQSV
LPFFVVTKMTRIKKPTLDKPTPDRYVAAELATVGLQDQTNGYFPHAVMGW
LTTKLVPMKLVIFFGARMNRLQRTGYLQRKKLREQ------------
*
>P1;ENSTNIG00000009599

--------------------------------------------------
-------------SFIVVTGATDGIGKAYAEDL-ARRGFAIV-LISRSQD
KLDEISKAISSKCGVETKTIAADFSC-LDIYSKIEAELAGLEIGVLVNNV
GISYSFPEFFLDVPNLDTFIDTMVNINIMSVCKMTHLVLPQ--MVERKRG
AILNISSASGMYPVPLLTVYSASK--AFVDFFSRGLQAEYKSRGVVIQSV
LPFFVATKMSKIRRPTLTVPSPESYVSAALSTVGLQTQTNGYLPHAIMGW
VTTALLPAKILTGHVMRMNLSMRAYNLKRQKDKQ---K---------
*
>P1;ENSTNIG00000010384

-----------VEETLRAAEAPLFWVGACTVASLALWLLYRLVSGFRIWV
LGNGSLLSP-KLGKWAVVTGATDGIGKSYAEEVRAAPGVALAWQISRSQE
KLADVAATLKELYSVETKTIAVDFGR-SDIYSKIEEGLAGLEIGVLVNNV
GVSYSYPEYYLHIPDLENFITNMIHVNVTSVCQMTRLVLPR--MADRSRG
VILNISSASGMYPVPLLTVYSATK--AFVDFFSRGLQEEYRRQGIIIQSV
LPFFVATKMTRIRKPTLDKPTPERYVAAELSTVGLQSQTNGYFPHAVMGW
VTTKLVPSSIVIFLGARMNRLQRTGYLQRRRLR--------------
*
>P1;ENSORLG00000001004

M-----SS--SGEAVLRAVEVPLFWLGAVTAVWLSFCSVYRLLSGLRVWV
LGNGRLVSPNRLGKWAVVTGATDGIGKAYAEEL-ARRGFSIV-LISRSQE
KLDEVSKAIAGKCGVETKTIAVDFSS-VDIYPKIEAGLAGLEIGVLVNNV
GISYSHPEFFLNVPNLDTFIDTMVNINITSVCQMTRLVLPR--MVERKKG
AILNISSASGMYPVPLLTIYSASK--AFVDFFSRGLQAEYKSKGIIIQSV
LPFFVATKLSKIRRATLDKPNPDRYVAAEINTVGLQTQTNGYLPHAVMGW
VTTALLPAKMLTSYMMGMGLSQRARYLKKQKQ-----G---------
*
>P1;ENSDARG00000015709

M-----ESFN-VVETLQPAERALFWVGALITASLALYVVYKTITGFRIWV
LGNGDLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFSMM-LISRSQE
KLDDVAKSLESTYKVETKTIAVDFSQ-IDVYPKIEKGLAGLEIGILVNNV
GISYSYPEFFLHIPDLENFITTMINVNITSVCQMTRLVLPR--MEARAKG
VILNISSASGMFPVPLLTIYSSTKAIAFVDFFSRGLQTEYKCKGIIIQSV
LPFFVATKMTKIRKPTLDKPTPERYVAAELNTVGLQDQTNGYFPHAVMGW
VTTILAPIDLVLNLGLRMNKAQRGGYLRRRKLR--------------
*
>P1;ENSGACG00000017131

M-----WS--AGEAALRAAETPLLWLGALTAAWLSVCSVYRLLSGIRVWG
LGNGRLVSPDKLGKWAVVTGATDGIGKAYAEEL-ARRGFCIV-LISRSQE
KLDDVSKFISSKCGVETRTIVADFSA-LDIYSRIEDGLVGLEIGVLVNNV
GISYSYPEFFLNVPSLDTFIDTMVNVNMTSVCQMTRLVLPG--MVERKKG
AILNISSASGMYPVPLLTVYSASK--AFVDFFSRGLQAEYKSKGIIIQSV
LPFFVATKLSKIRRATLDKPSPERYVSAELNTVGLQAQTNGYLPHAVMGW
VTTSLLPAAILNSHVMGMGLSQRARYLKKQKQ-----G---------
*
>P1;ENSDARG00000035872

M-----E----------PFADALFWVGAVTVLWLSVSSLWSLINGIRVWI
LGNGNLMRASSLGKWAVVTGATDGIGKAYAEEL-ARRGFAIV-LISRTQE
KLDEVSKAIESKYKVETKTISADFGS-VDIYPKIESGLAGLEIGVLVNNV
GVSYSYPEFFLNIPDVDSFINNMININIMSVCQMTRLVLPR--MVDRSKG
VILNVASASGMYPVPLLTLYSSTK--AFVDFFSRGLDAEYKSKGIIIQSV
LPFYVTTKLSKIRKPTLDIPTPERYVKAQLSTIGLQTQSNGYLPHAIMGW
VTASLLPAKLLNKYVMGMGLSQRARYLKKQKQDS---LSFILEL--A
*
>P1;ENSONIG00000015599

V-----NWMN-VEEMISWAETPLFWVGAFTVASLTLWLLYRLLTGFRIWV
LGNGQLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFAMM-LISRSQE
KLDDVARSIEEQFKVETRTIAVDFGK-TDIYPKIEEGLAGLEIGVLVNNV
GVSYPYPEYYLHIPDLENFITNTINVNMTSVCQMTRLVLPR--MCERSKG
VILNISSASGMYPVPLLTVYSATK--AFVDFFSRGLQEEYRRRGIIIQSV
LPFFVATKMTRIRKPTLDKPTPERYVAAELTTVGLQSQTNGYFPHAVMGW
ATTRLVPSSIVIFLGARMNRLQRTGYLHRRKLR--------------
*
>P1;ENSAMXG00000011213

--------------------------------------------------
--------------------------------------------------
---------ESKYKVQTKTISADFGC-VDIYPKIQAGLANLQIGILVNNV
GVSYSYPEFFLNVPNLDNVISSMININISSVCQVSTSLQTRICFVLRSKG
VILNISSASGMYPVPLLTLYSSSK--AFVDFFSRALDAEYKSKGVIIQSV
LPFYVTTKLSKIKRASLDIPTPERYVRSQISTVGLQNQTNGYLPHAVMGW
VTTALLPARLVSNLVMKMGLSQRARYLKKQKQG--------------
*
>P1;ENSONIG00000005893

MCSAAMSF--SGEAVFRAVEAPLFWLGALTAAWLSLCTVYRLLSGFRVWV
LGNGRLLSPAKLGKWAVVTGATDGIGKAYAEEL-ARKGFAIV-LISRSQE
KLDDVSKAIASKCGVETKTIQADFSA-VDIYSKIEGGLTGLEIGVLVNNV
GMSYPYPEFFLSVPNVDTFIDTLVNINITSVCQMTRLVLPQ--MVERKKG
AILNISSASGMYPVPLLTVYSASK--AFVDYFSRGLQAEYKSKGIIIQSV
LPFFVATKLSKIRRATLDKPSPERYVASQLNTVGLQTQTNGYLPHAIMGW
VTTALLPAKILNSYLMGMSLSQRARYLKKQKQ-----G---------
*
>P1;ENSTRUG00000015387

--------------------------------------------------
-----------------------------------------M-LISRSQE
KLDDVARMLQELYNVETKTIAVDFGK-SDIYCRIEAALAGLEIGVLVNNV
GVSYSYPEYYLHIPDLENFISNMINVNMTSVCQMTRLVLPR--MAERSKG
VILNISSASGMYPVPLLTVYSATK--AFVDFFSRGLQEEYRRQGIIIQSV
LPFFVATKMTRIRKPTLDKPTPDRYVAAELSTVGLQSQTNGYFPHAIMGW
VTTKLVPSSIVIFLGARMNRLQRTGYLQRRRLREQRNG-T--GLKSE
*
>P1;ENSORLG00000001421

M-----NRMN-AEEMIRRAEPLFFWVGAFTLAFFALWLLYRLVTGFRIWV
LGNGTLLSP-KLGKWAVVTGATDGIGKSYAEEL-ARRGFAMM-LISRSQE
KLDDVAKSLEEQFGVETKTIAVDFGK-TDIYPKIEAGLVGLEIGVLVNNV
GVSYHYPEYYLNIPDLDNFLTNMINVNMTSVCQMTRLVLPG--MVSRAKG
VILNISSASGMYPLPLLTVYSATK--AFMDFFSRGLQEEYRRQGIIIQSV
LPFFVATKMTRIRKPTLDKPTPERYVAAELTTVGLQNQTNGYFPHAVMGW
VTTKLVPTSIVIFLGASMNRVQRSGYLHRRKLREMKNG-A--SLKSE
*
>P1;ENSLOCG00000001197

A----MQS--SLEAFLRLSEAPLYWVGALTAAWVSLRLACRLLAGFRVWV
VGNGQQVGP-RLGKWAVVTGATDGIGKAYAEEL-ARRGFFIF-LISRSQE
KLDLVSKSLESQFGVETKTIAVDFGEGREIYRKIELGLTGLDIGVLVNNV
GVSYTYPEFFLNIPDAENVINKMINVNITSVCQMTRLVLPG--MVERSKG
VILNISSASGMYPIPLLTLYSATK--AFVDFFSRGLHAEYKSRGIIVQSV
LPFFVATKMTKIRKPTLDKPSPETYVRAELNTVGLEDQTNGYLPHAVMGW
VTTCLVPVQVVIHVSMNMNKRLRARYLKRQKEQ--------------
*
