>P1;ENSORLG00000009782

----------------------MSYAEKQDDITKDEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
VQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLKETEAALEFAQSQ
LADQGEESRECLSEMERTLALLAFDNPEESPFGDLLNTMQRQKVWSEVNQ
CVLDYENRESTPKLSKLLKLLLWAQNELDQKKVKYPKMTDLSKGTIEDPK
-
*
>P1;ENSTRUG00000005472

----------------------MSYSEKPEDVTREEWMDKVNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRVESGIEPSVDLDSLDERIKIREMILKGQ
IQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQSQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
CVLDYENRESTPKLAKLLKLLLWVQNELDQKKVKYPKMTDLSKGTIDEPK
-
*
>P1;ENSDARG00000022768

----------------------MSYSEKPEDITKEEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPNVDLDSLDERIKIREMVLKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQSQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYSRMTDLSKGTIEDPK
-
*
>P1;ENSONIG00000017394

---------------------IMSYAEKPEDITREEWMEKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
IQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQSQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
CVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSKGTIEDPK
-
*
>P1;ENSXMAG00000011369

---------------------MMSYAEKPEDITKEEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETESALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSTGAIEDPK
-
*
>P1;ENSORLG00000014687

----------------------MSYAEKPEDITKEEWMEKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETESALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSTGTIEDPK
-
*
>P1;ENSGACG00000011994

----------------------MSYAEKPEDITKEEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETESALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSSGTIEDPN
Q
*
>P1;ENSTNIG00000012488

---------------------MMSYAEKPDDITKEEWMEKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDTLDERIKIREMILKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETESALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSTGTIEDPK
-
*
>P1;ENSAMXG00000019186

---------------------MMSYAEKPEDVTREEWMEKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRLESGIEPSVDLDSLDERIKIREMILKGQ
IQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSKGTIEDPK
-
*
>P1;ENSGACG00000002635

----------------------MSYAEKPDDITREEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
IQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQSQ
LAEQGEESRECLTEMERTLALLAFDNPEDSPFGDLLNMMQRQKVWSEVNQ
CVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSKGTIEDPK
-
*
>P1;ENSTRUG00000004712

----------------------MSYAEKPDDITKEEWMEKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDTLDERIKIREMILKGQ
IQGAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETESALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSTGTIEDPK
-
*
>P1;ENSXMAG00000015662

----------------------MSYAEKPEDITKEEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIRELILKGQ
IQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQSQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNIMQRQKVWSEVNQ
CVLDYENRESTPKLAKLLKLLLWAQNELDQKKIKYPKMTDLSKGTIEDPK
-
*
>P1;ENSDARG00000037589

---------------------MMSYAEKPEDITRDEWMEKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMVLKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSKGTIEDPK
-
*
>P1;ENSTNIG00000017881

----------------------MSYSEKPEDMTREEWMDKVNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRVESGIEPSVDLDSLDERIKIREMILKGQ
IQDAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETEAALEFAQSQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
CVLDYENRESTPKLAKLLKLLLWVQNELDQKKVKYPRMTDLSKGTIEDPK
-
*
>P1;ENSONIG00000016792

---------------------MMSYAEKPEDITKEEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSVDLDSLDERIKIREMILKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRLRETESALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEESPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSTGTIEDPK
-
*
>P1;ENSLOCG00000004990

VVDAKCFICLIIQLFQFFSVFMMSYAEKPEDITKDEWMDKLNNVHIQRAD
MNRLIMNYLVTEGFKEAAEKFRMESGIEPSIDLDSLDERIKIREMILKGQ
IQEAIALINSLHPELLDTNRYLYFHLQQQHLIELIRQRETEAALEFAQTQ
LAEQGEESRECLTEMERTLALLAFDNPEDSPFGDLLNMMQRQKVWSEVNQ
AVLDYENRESTPKLAKLLKLLLWAQNELDQKKVKYPKMTDLSKGTIEDPK
-
*
