>P1;ENSGACG00000010656

MMEEIDRFQVPSAVQEAEMQAEMQP---L---DPASSTASEADSDTREVE
PVTINYKPSPLQRKIEKQRELARKGSLKNSNAVGSPVNQQPKKNNNVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-R
HLRSQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATS
STTCQIQ
*
>P1;ENSXMAG00000018218

MMEEIDRFQVPPV------NGETQP---L---DPAASSTLEVASDT-KGE
SVAMNYKPSPLQVQIEKQRDLARKASVKNG-TVGSPVNQQPKKN----AR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAP
STACQIQ
*
>P1;ENSAMXG00000008635

MMEEIDRFQVPAG------NSETQP---L---DPAATSTSEPDADTREAE
TTAINYKPSPLQVKIEKQRELARKGSAKNG-TVGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQASS
STACQIQ
*
>P1;ENSONIG00000019458

MMEEIDRFQVPPV------NGETQP---LVRDDPAASSTSEAEPDT-KGE
SVAMNYKPSPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPKKN----AR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAP
STACQIQ
*
>P1;ENSORLG00000010685

MMEEIDRFQVPSAVQEAEMQSEMQP---L---DPAASTASEAHSVTREGE
PVTINYKLSPLQRKIEKQRELARTGSLKNCNTVGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAENIV
SAERQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQAAS
STTCQIQ
*
>P1;ENSONIG00000011791

MMEEIDRFQVPSAVQEAEMQAEMQP---L---DPASSTASEADSDTREGE
PVTINYKPSPLQMKIEKQRELARKGSLKNGNTVGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATS
STTCQIQ
*
>P1;ENSORLG00000008972

MMEEIDRFQVPPV------NGETQP---L--QDPAASSTSEAETDP-KGE
SVALNYKPSPLQVQIEKQRDLARKASVKNG-TVGSPVNQQPKKN----AR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAS
STACQIQ
*
>P1;ENSDARG00000013813

MMEEIDRFQVPT-------EAEMQP---F---DPASSTTSEADSDTRESE
PATLNYKPSPLHMKIDKQRELVRKGSLKNG-NAGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-R
SLREQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNSTCMCCQATS
STACQIQ
*
>P1;ENSXMAG00000001430

MMEEIDRFQVPSAVQEAEMQSEMQP---L---DPASSTASEAESDTREGE
AVTINYKPSPLQMKIEKQRDLARKGSLKNNNTVGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATS
STTCQIQ
*
>P1;ENSDARG00000016396

MMEEIDRFQVPPV------NPEMKL---L--QDPAETSTIENETAPREPE
SVAINYKPSPLQVKIEKQRELARKGSVKNG-TVGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATS
STACQIQ
*
>P1;ENSGACG00000008695

MMEEIDRFQVPPV------NGETQPLIPQ---DPAASSSSEADADA-KGE
TVAMNYKPSPLQVQIEKQRDHARKGSVKNG-TVGSPVNQQPKKN----AR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAP
STACQIQ
*
>P1;ENSTRUG00000015586

MMEEIDRFQVPPV------NGETQP---L---DPAASTTSEGQPDA-KGE
TVAMNYKPTPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPKKN----AR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-R
CLRDQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAP
STACQIQ
*
>P1;ENSTNIG00000010681

-MEEIDRFQVPPV------NGETQP---L---DPAASTPSEGQPDA-KGE
TVAMNYKPTPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPKKN----AR
TRLVVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAP
SAACQIQ
*
>P1;ENSLOCG00000004732

----------------------MQP---L---DPAASSISEGDSDTREGE
PVTINYKPSPLQMKIEKQRELARKGSLKNG-NMGSPVNQQPKKN-NVMAR
TRLVVPNKGYSSLDQSGSERHAFHLDVQDDDDFDMSRYSSSGYSSAE---
-----QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATS
SAACQIQ
*
