>P1;ENSGACG00000011447

MGK-D----PRKPKGRMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCS
ERWK--TMSQKEKGKFEDMAKLDKVRYEKDMKNYDPPKGQ-KKKRYKDPN
APKRPPSAFFLFCGDFRPKVKSEHPGLTIGDTAKKLGEMWNGSSAENKQP
YEKKAAKLKEKYEKDVVAYRTKGTVDSPA-AATA----------------
--DDDDD-EDED--DDDDD---------DDDD-----------DDE----
-
*
>P1;ENSXMAG00000006844

MVK-D----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCS
ERWK--TMSPKEKGKFEDMAKQDKLRYEREMKNYVPPKGQ-KKKRFKDPN
APKRPPSAFFLFCADFRPKVKGESPGLSIGDTAKKLGEMWNSLSGEEKQP
YEKKAAKLKEKYDKDIVAYRTKGSVDSAP-AAAA----------------
-NDDEDDDEEEG-DEEEEE---------EEED-----------DD-----
E
*
>P1;ENSAMXG00000014832

MVK-D----PRKPRGKMSSYAYFVQTCREEHKKKHPEASVNFSEFSKKCS
ERWK--TMSPKEKSKFEDMAKQDKVRYEREMKNYIPPKGE-KKKRFKDPN
APKRPPSAFFIFCGDYRPKIKGENPGLSIGDIAKKLGEMWNSSSPEVKQP
YEKKAAKLKEKYDKDIAVYRTKGVAGLSK-KAAG----------------
-DEDDDE-EDED-EDDDEE---------DDEE-----------DDE----
-
*
>P1;ENSXMAG00000008400

MGK-D----PTKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCS
ERWK--TMSAKEKGKFEDLAKQDKARYEREMLSYVPARGG-KKKKFKDPN
APKRPPSAFFIFCSEFRPKVKGENPGLSIGDVAKRLGEMWNSTASEDKQP
YEKKADKLKEKYKKDIAAYRKMGSSAPAKAPAKA-----E-------KD-
---DDDD-DEDD-DEEEED---------DDDE-----------DDD----
-
*
>P1;ENSGACG00000020545

MVR-E----PGKPRGKMSSYAYFVQTCREEHKKKHPEASVNFSEFSKKCS
ERWK--TMSLKEKGKFEDLARQDKARYEKEMMSYIPPRGT-KKKKFKDPN
APKRPPSAFFIFCAEYRSKVKGETPGLTIGDVAKKLGEMWNGTASEDKQP
FEKKASKLKEKYEKDVAAYRAKTKAQPKV-EKKVRIMCFE-------KK-
KK-KTPS-EYGC-VQSTED---------ENQKGTHSHTVHCGGNDA----
-
*
>P1;ENSORLG00000003400

MGK-D----PTKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCS
ERWK--TMSAKEKGKFEDMARQDKVRYDREMMSYVPAKGA-KTKKFKDPN
APKRPPSAFFIFCSEFRPKVKGESPGLTIGDVAKRLGEMWNSTSAEDKQP
YEKKAAKLKEKYGKDIAAYRAKGKTGGGA-PAKAPAK-VE-------KK-
MDDDDDD-DDDD-EEEEED---------DDDE-----------DDE----
-
*
>P1;ENSONIG00000005505

MVK-D----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCS
ERWK--TMSPKEKGKFEDMAKQDKLRYEREMKNYVPPKGQ-KKKRFKDPN
APKRPPSAFFLFCADFRPKIKSEYPGLSIGDTAKKLGEMWNSSSAEEKQP
YEKKAAKLKEKYDKDIVAYRTKGKVDSGP-AAAA----------------
-DDDDNEEEEEEGEEEEEE---------DEDD-----------DD-----
E
*
>P1;ENSAMXG00000003142

MGK-D----PTKPRGKMSSYAYFVQTCREEHKKKHPDTSVNFSEFSKKCS
ERWK--TMSAKEKGKFEEMARLDKARYEREMKNYVPPRGE-KKKRFKDPN
APKRPPSAFFIFCAEYRPKVKEETPGLSIGDVAKKLGEMWNKTSAEEKQP
YEKKAAKLKEKYEKDIAAYRK-GKVVGGA--AKAPSK-PD-------KA-
NDDDDDD-DDDD-DDDDDD---------DEDD-----------DDE----
-
*
>P1;ENSTRUG00000004822

MGK-D----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCS
ERWK--TMSPKEKGKFEDMAKQDKVRYEREMKNYVPPKGH-KKKRFKDPN
APKRPPSAFFLFCAELRPKVKSENPGLTIGDTAKKLGEMWNSKTAEEKQP
YEKKAAKLKEKYDKDIVAYRTKGKVDSES-AATA----------------
--DDDEE-EDDE-EEEEDD---------DDED-----------DDENDPG
P
*
>P1;ENSORLG00000003951

MVK-D----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCS
ERWK--TMSPKEKGKFEDMAKQDKVRYEREMKNYVPPKGQ-KKKRFKDPN
APKRPPSAFFLFCADFRPKIKSESPGLSIGDTAKKLGEMWNSSSAEEKQP
YEKKAAKLKEKYDKDIVAYRTKGKVDSES-ASAA----------------
--D-----------------------------------------------
-
*
>P1;ENSDARG00000030479

MGK-D----PRKPRGKMSSYAYFVQTCREEHKKKHPEASVNFSEFSKKCS
ERWK--TMSAKEKGKFEDMAKQDKVRYEREMKNYIPPKGE-KKKRFKDPN
APKRPPSAFFIFCGDYRPKIKGENPGLSIGDIAKKLGEMWNSSSAEVKQP
YEKKAAKLKEKYDKDIALYRTKGIAGFSK-KEGG----------------
-EDDEED-E-DD-DEEEDD---------EEEE-----------DDE----
-
*
>P1;ENSDARG00000099175

MGK-D----PTKPRGKMSSYAYFVQTCREEHKKKHPEATVNFSEFSKKCS
ERWK--TMSAKEKGKFEDMAKLDKARYEREMKNYIPPKGE-KKKRFKDPN
APKRPPSAFFIFCSEFRPKVKEETPGLSIGDVAKRLGEMWNKISSEEKQP
YEKKAAKLKEKYEKDIAAYRSKGKVGGGA--AKAPSK-PD-------KA-
NDEDEDD-DEEE-DEDDDD---------EEEE-----------DDE----
-
*
>P1;ENSONIG00000012706

MGK-D----PTKPRGKMSSYAYFVQTCREEHKKKHPEASVNFAEFSKKCS
ERWK--TMSAKEKGKFEDMARQDKARYEREMMNYVPARGGKKKKKYKDPN
APKRPPSAFFIFCSEFRPKVKGESPGLSIGDVAKRLGEMWNSTAAEDKQP
YEKKAAKLKEKYEKDIAAYRAKGKPGSGA-PAKAPAK-AE-------KK-
-DDDDDD-DDED-EEEEED---------DDDE-----------DDD----
-
*
>P1;ENSTNIG00000016258

MGK-D----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFAEFSKKCS
ERWKHKTMSPKEKGKFEDMAKQDKVRYEREMKNYVPPKGH-KKKRFKDPN
APKRPPSAFFLFCAEFRPKVKSENPGLTIGDTAKKLGEMWNSKTAEDKQP
YEKKAAKLKEKYDKDIVAYRTKGKVDSES-AATA----------------
--DD-NG-EEEE-EKESRHQRMMLRWQTWKSG-----------DD-----
E
*
>P1;ENSTNIG00000009909

MGR-DSGREAGKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSRKCS
ERWK--TMSVKEKGKFEDMAKQDKVRYDQEME-YVPAKGGKKKKKFKDPN
APKRPPSAFFIFCSEFRPKVKGEHPGLSIGEVAKKLGELWNNTSSEDKQP
YEKKASKLKEKYEKDVAAYRQKTKGGTGS-AGKAPAK-AE-------KKA
AAADDDD-DDED-EEEEDD---------DDDD-----------DDE----
-
*
>P1;ENSLOCG00000000187

MGKGD----PKKPRGKMSSYAYFVQTCREEHKKKHPDASVNFSEFSKKCS
ERWK--TMSAKEKSKFEDLAKQDKVRYEREMKTYIPPKGE-KKKRTKDPN
APKRPPSAFFIFCSDFRPKVKGESPGLSIGDVAKKLGEMWNKTTAEDKQP
YEKKAAKLKEKYEKDIAAYRAKGKTDGAK-KAPA--K-MEKAKKKKEEE-
EEDDDDD-DEEE-EEEEEE---------DDED-----------DDE----
-
*
