>P1;ENSTRUG00000008417

MFKE--------------------VPVDPMASTDSRLQ-QQSSQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVFRN
DKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDSFKAVQDWA
TQIKTYSWDNAQVILVGNKCDLEDDRLVPTEDGQRLAEELG--FQFFEAS
AKDNINVKQVFERLVDIICDKMSESMEGDNNFLSSQGKQSLKDSPSESS-
GGCA-----C
*
>P1;ENSORLG00000016555

-----------------------------QMALTEPRLRQQPTPNDTADP
DFNHMFKLLIIGNSSVGKTSVLFRYADDSFNPAYVSTVGIDFKVKTVFRN
EKRIKLQIWDTAGQERYRSITTAYYRGADGFLLMYDITNQESFNAVRDWA
TQVQHYSSKNAQVILVGNKCDMEDDRLITREDGQRLADERG--FLFFEAS
AKENINVKQVFEHLVDVICEQMNTSTDGNAI-NSNHNGLGPGQGP-EGG-
GGCA-----C
*
>P1;ENSDARG00000101534

-----------------------------MASVTDSRL--QPSQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVFRN
NKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMFDITNRDSFNAVRDWA
TQIKTYSWDNAQVILVGNKCDLEDERLIPTEDSQRLAHELG--FQFFEAS
AKDSINVKQVFECLVDVICDKMTESLDGDAA-VSNHKDCSLQDAADEGH-
SACA-----C
*
>P1;ENSONIG00000018082

-----------------------------MALARDPGA--AHEQRDPADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTIYRN
NKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQESFCAVQDWA
TQIKTYSWDNAQVVLVANKLDLEDDRQVPTEDGKRLAKELG--FHFFEAS
AKDNINVKQVFDKLVDVICEKMNESVNGDANPTTNHKGEGLKDTPNSSR-
GGCA-----C
*
>P1;ENSORLG00000003625

SPF-----------------------VRQMALAKVPVA--VQEQRDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRFADDSFTSAFVSTVGIDFKVKTIYRN
NKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQESFCAVQDWA
TQIKTYSWDSAQVVLVGNKLDLEEDRQVPRQDGQRVATELG--FQFFEAS
AKDNINVKQVFDRLVDVICEKMNQSFNGDASPSVSQKGDGLQEQPPPSQ-
GGCA-----C
*
>P1;ENSTRUG00000005632

LKL---------------------CPDRQMATARDPAA--GQDPGEASDQ
NFDDMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTIYRN
NTRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQESFCAVQDWA
TQIKTYSWGDAQVVLVGNKADLEEERQVPTEDAQRLATELG--FRFFEAS
AKDNINVKEVFDSLVDAICEKMKEGPNGDETPSSGNKGPNLNETPSPSQ-
RSCA-----C
*
>P1;ENSXMAG00000017368

-----------------------------MALARDLGV--GQEQRDAADQ
NFDYMFKVLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTIYRN
DKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQESFCAVQDWA
TQIKTYSWDSAQVVLVGNKMDLEDDRQVPKADAQRVATELG--FQFFEAS
AKDNINVKQVFDKLVDLICEKMNESVNGYTSQPVNQNGDTLKDKPDTSQ-
GGCA-----C
*
>P1;ENSDARG00000018107

-----------------------------MASANDTRH-QTQVQKDVADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVYRN
EKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDSFYAVQDWA
TQIKTYSWDNAQVILVGNKCDLEDDRLVAREDGQRLANELGTRFQFFEAS
AKDNINVKQVFERLVDIICDKMNESLDTDPSILTNQKGPSLQDTPPDGQS
GGCG-----C
*
>P1;ENSGACG00000019452

-----------------------------MALARDPAA--AAEQRDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRFADDSFTSAFVSTVGIDFKVKTIYRS
DKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQESFCAVQDWA
TQIKTYSWGNAQVVLVGNKLDLEEDRQVPTEDAQRLATELGC-FQFFEAS
AKDNVNVKQVFDELVDVICERMNESVNGDATPLANHDEAGLKETPRSGL-
AGCG-----C
*
>P1;ENSGACG00000006453

VQSARRQQTGPVITFPSNSVLWDTRQHKRMAS-NDSRLQQPPSQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVFRN
DKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNLDSFTAVQDWA
TQIKTYSWDNAQVILVGNKCDLEDDRLVPLEDGQRLSEDLG--FQFFEAS
AKDNINVKQVFECLVDVICQKMNESMEGDMGPEANHRNQALKDSPSESH-
GGCA-----C
*
>P1;ENSONIG00000008043

ML--------------------------QMASTESRLQ-QQPSQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVFRN
DKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDSFNAVQDWA
TQIKTYSWDNAQVILVGNKCDLEDDRLIPTEDGQRLAEELG--FQFFEAS
AKDNINVKQVFERLVDVICEKMNESMEGDANLIANHSNQGLKDSPSESH-
GGCA-----C
*
>P1;ENSXMAG00000008795

-----------------------------MAS-TDSRLHQPPSQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTPAFVSTVGIDFKVKTVFRN
NKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDVSNQDSFSAVQDWA
TQIKTYSWDNTQVILVGNKCDLEDERVIATEDGQRLAEELG--FRFFEAS
AKDNINVKQVFECLVDIICDKMNETMEEESNLTTNHVTHGSKDS-SESN-
GACA-----C
*
>P1;ENSAMXG00000000832

-----------------------------MASVSDPRQ-QTQAQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVYRN
EKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQESFYAVQDWA
TQIKTYSWDNAQVILVGNKCDLEDDRLVATEDGQRLANELG--FQFFEAS
AKDNINVKQVFERLVDVICDKMNESMDGEPSQMTNHKGPSLQDTPPAGQ-
SGCS-----C
*
>P1;ENSTNIG00000006074

-----------------------------MALARDPAA--GQDPRDASDQ
NFDYMFKLLIIGNSSVGKTSFLFRYADNSFTSAFVSTVGIDFKVKTIYRS
NIGIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQESFCAVQDWA
TQIKTYSWGNAQVVLVGNKVDLEEERQVPTEDAQRLATELG--FQFFEAS
AKDNVNVKEVFDSLVDAICEKMNESPNGDAAPSTNNKGPNLNETPNPSQ-
RGCT-----C
*
>P1;ENSLOCG00000008126

-----------------------------MASANDSR----QSQKDAADQ
NFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDFKVKTVYRN
DKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDSFNAVQDWA
TQIKTYSWDNAQVILVGNKCDLEDDRIIPTEEGRRLADELG--FQFFEAS
AKDNINVKQVFERLVDIICEKMNESMDSDPNMLGNHKATTLQESPPECQ-
QGTPPSVRPC
*
