>P1;ENSAMXG00000019209

V-MADQQRQRSLSTSGETLYLALGVSKTATPEDIKKCY---RKLALKFHP
DKNPDNPEAAEKFKEINNAHAILIDPTKRNIYDQYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGIATGCYCCCCLCCCCN----CCCGKCKPRP
PMDHEPDFYVSPEDLEAQMQSDERD------GDPILVQPSSATETTQLKS
DSHHSS-YRTDTGY-------
*
>P1;ENSXMAG00000011375

--MAEHQRQRSLSTAGESLYHVLGVDKVATSDDIKRSY---RKLALKFHP
DKNPDNPEAAEKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCGLATGCYFCCCLCCCCN----CCCGRCKPRP
REGQEQDFYVSPEDLEAQLQSDERE----AAGEPIVLQPS-ATETTQLTS
DGHY-S-YHTDTGF------N
*
>P1;ENSTRUG00000004830

--MAEHQRQRSLSTAGESLYHVLGVEKVATTDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVVCGLATGCYFCCCLCCCCN----CCCGRCKPRP
RDAQDQDFYVSPEDLEAQLQSDERE----AGGEPIMMQPS-ATETTQLTS
DGHY-S-YHTDTGF------N
*
>P1;ENSONIG00000016790

--MSEQQRQRSLSTAGESLYHVLGVDKMATTDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVLCGLATGCYFCCCLCCCCN----CCCGRCKPRP
REGQEQDFYVSPEDLEAQLQSDERE----AGGEPIVLQPS-ATETTQLTS
DGHH-S-YRTDTGF------N
*
>P1;ENSTNIG00000012487

--MAEHQRQRSLSTAGESLYHVLGVEKVATTDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVACGLAT--------------------GRCKPRP
RDAQDQDFYVSPEDLEAQLQSDERGGATEAGGEPIMMQPS-ATETTQLTS
DGHY-S-YHTDTGFN------
*
>P1;ENSDARG00000004836

--MAEQQRQRALSTSGESLYVVLGVEKNTAQEDIKKSY---RKLALKFHP
DKNPNNPEAADKFKEINNAHAILSDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGVATGCYFCCCLCCCCN----CCCGKCKPHP
PHSDDPDFYVSPEDLEAQMQSDERD-----GSSPIMMQPSSATESTQLTA
DSHHTS-YRTDANY-------
*
>P1;ENSGACG00000010366

--AMEQQRQRSLSTSGDSLYAVLGVDKSATTEDIKKSY---RKLALKFHP
DKNPDNPDAAEKFKEINNAHSILSDGTKKNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCCLST--------------------GKCKPRP
PMDQEPEFYVSPEDLEAQMTADERD-----GGDPVMVQPSSATENTQLTS
DAHQ-S-YRTD---A------
*
>P1;ENSAMXG00000007551

IAMAEQQRQRTLSTSGESLYHVLGVDKIATNDDIKKSY---RKLALKYHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCGLATGCYFCCCLCCCCN----CCCGKCKPRP
PEGQDPEFYVSPEDLEAQLQSDEREA---GGGEPIVLQPS-ATETTQLTS
DGHHTT-YRTDTGFN------
*
>P1;ENSONIG00000014869

--M-DHQRQRTLSTSGESLYAVLGVDKNATTEDIKKCY-IFRKLALKFHP
DKNPDNPEAAEKFKEINNAHSILVDATKKNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCCLATGCYFCCCLCCCCN----CCCGKFKPHP
PMDQDPEFYVSPEDLEAQMTAEERD-----GGDPIVMQPSSATETTQLTS
DAHQ-S-YKTKSH-S------
*
>P1;ENSORLG00000014705

--MTEQQRQRSLSTAGESLYLVLGVDKLATNDDIKRSY---RKLALKFHP
DKNPENPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGLATG-------------------GRCKPRP
REGQEQDFYVSPEDLEAQLQSDERE----AGGEPIVLQPS-ATETTQLTS
DGHY-S-YHTDTGFNKTKERS
*
>P1;ENSTRUG00000004022

--AMDPQRQRTLSTSGESLYVVLGVDKNATTEDIKKCYRNLRKLALKFHP
DKNPDNLEAAEKFKEINNAHAILSDATKKNIYDKYGSLGLFVAEQFGEEN
VNTYFVLSSWWAKALFVFCCLATGCYFCCCLCCCCN----CCCGKCKPRP
PMDQEPEFYVSPEDLEAQMNVEERG-----------LNPCCLTQTTQLTS
DAQH-TLTHTHTHTH------
*
>P1;ENSGACG00000011986

--MAEHQRQRSLSTAGESLYLVLGVEKVATPDDIKRSY---RKLALKFHP
DKNPDNPEAADKFKEINSAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFVFCGLAT--------------------GKCKPRP
REGQEQEFYVSPEDLEAQLQSDERA---EAGGDPIMLQPS-ATETTQLTS
DGHH-S-YHTDTGF------N
*
>P1;ENSDARG00000042948

--MAEQQRQRSLSTSGESLYHVLGVDKVATVDDIKKSY---RKLALKYHP
DKNPDNPEAADKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKALFIFCGLATGCYFCCCLCCCCN----CCCGKCKPRP
PDRPDPEFYVSPEDLEAQLQSDERET---VGGEPIVLQPSSATETTQLTS
DGYHTT-YHTDTGFN------
*
>P1;ENSLOCG00000004956

--MAEQQRQRSLSTSGETLYHVLGIDKNATPDDIKKSY---RKLALKYHP
DKNPDNPEAAEKFKEINNAHAILNDPTKRNIYDKYGSLGLYVAEQFGEEN
VNTYFVLSSWWAKVRQHSCGKLNCSGTECCVCCCFNFELFCKSGKCKPKP
PEGEEHEFYVSPEDLEAQLQSDERE-----GEAPIVMQPSSATETTQLTA
DSHP-S-YHTDTGFN------
*
