>P1;ENSGACG00000018427

-----MSASPAKVNRKE-NSNHDAADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSDLIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKALSKEFNV
NESGDPVSKSSEIKWKAGKDLTKRTGQTSNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLV---------------------
---------------------------------------
*
>P1;ENSAMXG00000012408

-----MSASAAKVSKKELNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLTRVEVTEFEDIKSGYRIDFYFDENMYFENKVLSKEIHL
NESGDPTPKSTEIKWKPGKDLTNRPSQTQSKAGKKRQHEE-PESFFTW-F
TDHSDSGADELGEVIKDDIWPNPLQYYLVPDMEDE-EGEGEDE---DEDE
EGLEDIDEEGEE-DGEEED--DD-------GEDDDGEDD
*
>P1;ENSXMAG00000002845

-----MSATATKVSKKELNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKVLSKEFHL
NESGDPSSKSTEIKWKSGKDLTKRSSQTQNKAGRKRQHEE-PESFFTW-F
TDHADAGADELGEVIKDDIWPNPLQYYLVPDMDDE-EGEGEED---EEDE
EGLEDIDEEGDE-DGEDDE-EDEGE----EGEEDEGEDD
*
>P1;ENSXMAG00000013718

-----MSASAAKVSRKE-NSNHDAGDETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSKVEVTEFEDIKSGYRIDFSFDENPYFENKVLSKEFNV
NEGGDPVSKSTEIKWKTGKDLTKRSSQTPNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMEDE-EGED-DE---EEDE
EGLEDIDEGEEE-EGEDE--DGEGE----DGE-DDGEDD
*
>P1;ENSTNIG00000016723

-----MSASAAKVSKKELNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKVLSKEFHL
NESGDPSSKSTEIKWKSGKDLTKRSSQTQNKAGRKRQHEE-PESFFTW-F
TDHADAGADELGEVIKDDIWPNPLQYYLVPDMDEE-EGEGEED---EEDE
EGLEDIDEEGDE-DGEDDE-EDDGE----DGEVRQ---T
*
>P1;ENSDARG00000031495

-----MSASAAKVSKKELNSNHDGGDETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLTRVEVTEFEDIKSGYRIDFYFDENMYFENKVLSKEIHL
NESGDPTSKSTEIKWKPGKDLTSRSSQTQSKAGKKRQHEE-PESFFTW-F
TDHADSGADELGEVIKDDIWPNPLQYYLVPDMEDE-EGEGEDE---DDDE
EGLDDIDEEGDD-DGEEED-DDD-------GEDDEGDDD
*
>P1;ENSORLG00000017766

-----MSASAAKASKKELNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKVLSKEFHL
NESGDPSSKSTEIKWKSGKDLTKRSSQTQNKAGRKRQHEENPLQYYLWCF
TFHSEA--------------------------------------------
---------------------------------------
*
>P1;ENSORLG00000012750

-----MSA---KASRKE-NSNHDAADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEDDEEALHYLSKVEVTEFEDIKSGYRIDFCFDENPYFENKTLSKEFNV
NEGGDPISKSTEIKWKTGKDLTKRSGQTSNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMEDE-EGDGDDD---DDDE
EGLEDIDEGEEE-GGEDD--DGEGD----DGE-DDGDED
*
>P1;ENSONIG00000011282

-----MSASSAKVSRKE-NSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSEIIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKALSKEFNV
NESGDPVSKSSEIKWKAGKDLTKRTGQTPNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMEDE-EGDGDDD---DEEE
EGLEDIDEGEEE-EGEDEDEDGDGE----DGEHDDGEDD
*
>P1;ENSDARG00000003920

-----MSASAAKVSRKEQNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLTRVEVTEFEDIKSGYRIDFYFDENPYFENKVFSKEFHL
NESGDPSSKSTEIKWKAGKDLTKRTGQTPNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMDEE-EGEGEEED-DEEEE
EGLEDIDEEGDEDDGEEDEEEDEGE----DGE-DDGEDD
*
>P1;ENSGACG00000014785

-----MSASAAKVSKKELNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKLLSKEFHL
NESGDPSSKSTEIKWKSGKDLTKRSSQTQNKAGRKRQHEE-PESFFTW-F
TDHADAGADELGEVIKDDIWPNPLQYYLVCSPDN----------------
---------------------------------------
*
>P1;ENSAMXG00000010484

-----MSASAAKVSRKEQNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLTRVEVTEFEDIKSGYRIDFYFDENPYFENKVLSKEFHL
NESGDPSSKSTEIKWKAGKDLTKRAGQTQNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMDDE-EGEGEDE--DDEEE
EGLEDIDEEGDEDEGEEDEEEDEGE----DGE-DDGEDD
*
>P1;ENSTRUG00000013980

-----MSASSTKVSRKE-NSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSDLIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSKVEVTEFEDIKSGYRIEFFFDENPYFDNKVLSKEFNV
NESGNPVSKSTEIKWRSGKDLTKRTGQTPNKAGKKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMEEEDEGEGDED---DDEE
EGLEDIDEGEEE-EGEDD--DEDGEVSRRRGPHDDGEED
*
>P1;ENSTRUG00000006019

PACENMSASAAKVSKKELNSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSRVEVTEFEDIKSGYRIDFYFDENPYFENKVLSKEFHL
NESGDPSSKSTEIKWKSGKDLTKRSSQTQNKAGRKRQHEE-PESFFTW-F
TDHADAGADELGEVIKDDIWPNPLQYYLVPDMDEE-EGEGEED---EEDE
EGLEDIDEEGDE-DGEDDE-EDDGE----DGEDDEGEDD
*
>P1;ENSTNIG00000003141

PQTATMSASSAKVTRKE-NSNHDGADETSEKEQQEAIEHIDEVQNEIDRL
NEQASEDILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLSKVEVTEFEDIKSGYRIEFFFDENPCFDNKVLSKEFNV
SESGHPVSKATEIKWKAGKDLTKRTGQTPNKAGKKRQHEE-PESFFTW-F
SDHSDAGSDELGEVIKDDIWPNPLQYYLV---------------------
---------------------------------------
*
>P1;ENSLOCG00000006027

-----PD---CKLCLK---NYH---LFLLEKEQQEAIEHIDEVQNEIDRL
NEQASEEILKVEQKYNKLRQPFFQKRSELIAKIPNFWVTTFVNHPQVSAL
LGEEDEEALHYLTRVEVTEFEDIKSGYRIDFYFDENPYFENKILSKEFHL
NESGDPSSKSTEIKWKAGKDLTKRSSQTQNKAGRKRQHEE-PESFFTW-F
TDHSDAGADELGEVIKDDIWPNPLQYYLVPDMDDE-EGEGEDDEDDDEEE
EGLEDIDEEGDEDDGEEDEEDDDGE----EGEDDDGEDD
*
