>P1;ENSORLG00000012926

TIMSHKLPLQVNSW---FSPQAGA---------------SSVWASCCGIL
NEVMGTGAVRGQQPGFGAGAGPFRFAPSAGYSTYPPTS--SGSPTLVCKA
CGQAFTVFRRKHVCCDCRKSFCFLCCVLQENLRICATCHLLKATAFQRPR
LMRLRVKDLRQYLQLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLRHQGIEEEE---------
------------------EDDPDAA----------SLRS---RSLY----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
AAPSTTQSA----------SELSA------------FA--ASQ--EEPL-
-SRSDSSDT-NQDMGDATSVSLLNLDP---NE-HT---------------
--------------------------------------------------
------PEGSPQMRRRARASLSDISSLR--DIEGLSVRQLKEILARNFVN
YSGCCEKWEL-----------VERVSRLYRETEENRKSLENVSST----V
T--------------SDGEI-CPLTIRDDNL-------------------
----------------------CRICMDATIDCVLLECGHMVTCTKC---
GK-------RMNECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSDARG00000054036

-------------------MKAGA---------------SSMWASCCGLL
NEVMGTGAVRTQQPGFGAGAGPFRFAPSAGYSTYPPSSTTSGSAGLACKA
CGLAFSVFRRKHVCSDCKKSFCSLCSVLQENLRRCSTCHLLWGTAFQRPR
LMRLRVRDLRQYLTLRNINTDTCR--------------------------
----------------------EKEDLVDLVLCHLGAELELGED----EE
----EE---------EEEEEEADTD----------SLPS-LPRSLS----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
PPASAARSS----------SQQSA------------LSAAASQ--GEAL-
-SRSDSSGTNNQDHGDAASVSLLNLES---HD-DM---------------
--------------------------------------------------
------LEASPATQRRARASLSDLAHED--DIESLTVRQLKEILARNFVN
FSGCCEKWEL-----------VERVHRLYRENQLNRRSMENVSNS----L
A--------------ADGVQVAQLGGADENL-------------------
----------------------CRICMDAVIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSTRUG00000010478

-----------------------------------------MWASCCGLL
NEVMGTGTVRAQPPGFGAGAGPFRFAPSAGYSTYPPTS--AGSAGQLCKA
CGLAFSVFRRKHICCDCKKSFCALCSVLQENLRCCATCHLLRGTAFQRPR
LMQLRVKDLRQYLLLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLCHRGMRESPGPVIEEEDE
EDSEEEEGEDEE-VAERDEGGDDTD----------SLHS-LPHSHA----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
SPPSSASS----------TSEQSV------------LS--ASQ--GDAP-
-SPSGSSGTNSQ-IPKVHQCSTEVLESEQQLESVT---------------
--------------------------------------------------
------LKVSPATQRRIRASLSDLDNEE--AIENLSVRQLKEILARNFVN
YSGCCEKWEL-----------LERVHRLYREYEQNRKSKSLVS-------
P--------------ADGVK-AQLA-ADENL-------------------
----------------------CRICMDAIIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFRS-----------------
*
>P1;ENSXMAG00000014052

-----------------------------------------MWASCCGLL
NEVMGTGTVRTPQPGFGAGAGPFRFAPSAGYSTYPPTS--SGSAGQLCKA
CGLAFSVFRRKHICCDCKKSFCALCSVLQENLRCCTTCHLLRGTAFQRPR
LMQLRVKDLRQYLLLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLCHQGTRETPRPVMEEDEE
----EDEDDD-TCGDEEEDGGEDTD----------SLHS-LPHSRA----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------A
SPPSATRS----------ASELSV------------LS--ASQ--GDAL-
-SPSDSSGTPSQEHEDTPTASLLNLEP---AE-NI---------------
--------------------------------------------------
------LEVSPATQRRIRASLSDLDNEE--AIENLSVRQLKEILARNFVN
YSGCCEKWEL-----------LDRVHRLYRENEQNRKSMENVSIT----A
G--------------KDGVR-AQLA-ADENL-------------------
----------------------CRICMDAIIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSONIG00000010826

-------------------MKAGA---------------SSMWASCCGLL
NEVMGTGAVRGQQPGFGAGAGPFRFAPSAGYSTYPPTS--SGSPSLVCKA
CGQAFSVFRRKYICCDCKKSFCSLCSVLQENLRICATCHLLKATAFQRPR
LMRLRVKDLRQYLLLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLCHQGIEEEE---------
--------------------DPDMT----------SLQS---RSLY----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
PTPSTTQSA----------SELSA------------FA--ASQ--EEAL-
-SRSDSSDT-NQDMGDGTSVSLLNLDP---SE-DT---------------
--------------------------------------------------
------PEVSPQTRRWARASLSDISSLR--DIEGLSVRQLKEILARNFVN
YSGCCEKWEL-----------VERVSRLYRETEENRKSLENVSST----V
TTVMTFPPPICNGAIGDGEN-CPLTIHDDNL-------------------
----------------------CRICMDAMIDCVLLECGHMVTCTKC---
GK-------RMNECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSGACG00000011849

ALGSRSSLLLSSSRRAAAAMKAGA---------------SSMWASCCGLL
NEVMGTGAVRGQQPGFGAGAGPFRFAPSAGYSTYPPSG--SGTPGLVCKS
CGQAFSVFRRKYICRDCKKSFCSLCSVLQENLRICATCHLLNATAFQRPL
LMRLRVRDLRQYLLLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLCHQGIEEEE---------
--------------------G-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--LSTAQSA----------SELSA------------FV--ASR--EEQL-
-SRSDSSDT-NQGTWESQGAVL------------S---------------
--------------------------------------------------
------RPQNPQTRCRARASLSDISSLR--DIEGLSVRQLKEILARNFVN
YSGCCEKWEL-----------VERVNRLYRETEENRKSLENVSTT----V
T--------------ADGEK-GPLTIQDDNL-------------------
----------------------CRICMDATIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSONIG00000013872

-------------------LKAGA---------------SSMWASCCGLL
NEVMGTGTVRAQQPGFGAGAGPFRFAPSAGYSTYPPTS--SGSAGQLCKA
CGLAFSVFRRKHICCDCKKSFCALCSVLQENLRCCTTCHLLRGTAFQRPR
LMQLRVKDLRQYLLLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLCHQGARQTPRP-------
----------------------DTD----------SLHS-LPHSRA----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------A
SPPSATRS----------TSEQSV------------LS--ASQ--GDVL-
-SPSDSSGTTSQEHDDTPTASLLNLEP---TE-SL---------------
--------------------------------------------------
------IEVSPATQRRIRASLSDLDNEE--AIENLSVRQLKEILARNFVN
YSGCCEKWEL-----------LERVHRLYRENEQNRKSMENVNI------
T--------------ADGVK-AQLA-ADENL-------------------
----------------------CRICMDAIIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSDARG00000038300

-------------------MKAGA---------------SSMWASCCGLL
NEVMGTGAVRGQQPGFGAGAGPFRFAPTAGYSTYPPAN--SNSTSLVCQA
CRQAFSVFRRRYICCDCTKSFCSLCSVLQENLRRCTTCHLLKGTAFQRSQ
LMRLRVKDLRQYLMLRNINTDTCR--------------------------
----------------------EKEDLVDLVLCHHGAESEDDP-------
----------------------DTP----------SLQS---HPLY----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------S
PPPLIEEP----------TSPLSA------------LS--PT---REPI-
-SRSNSSESTNQDIEDSTSVSLLNLDQ---TE-HT---------------
--------------------------------------------------
------PEVSPQTRRRARASLSDLSSLD--DVEQLTVRQLKEILARNFVS
FSGCCEKWEL-----------VERVRRLYRENEDNRKSMENVSNP----I
TAVVAYPPPICNGGIGDSCR-TQLS-NDDNL-------------------
----------------------CRICMDAVIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVIRAVHVFKS-----------------
*
>P1;ENSORLG00000008588

-------------------PQAGA---------------SSMWASCCGLL
NEVMGTGTVRAQQPGFGAGAGPFRFAPSAGYSTYPPTS--AGSAGQLCKA
CGLAFSVFRRKHICCDCKKSFCALCSVLQENLRCCTTCHLLRGTAFQRPR
LMQLRVKDLRQYLLLRNIPTDTCR--------------------------
----------------------EKEDLVDLVLCHQRTRESPRPGD-----
-----------------ALSPSDSS----------GTTSQLYRTSY----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------Y
SKPQAPCSGSTSFQMLNKNTLLSV------------FC--SGLQKRNKIS
SSPKESDNGEKKEHEDTPTASLLNLEN---SE-NI---------------
--------------------------------------------------
------LEVSPATQTRIRASLSDLDNEE--AIENLSVRQLKEILARNFVN
YSGCCEKWEL-----------LERVHRLYRENEQNRKSS-----------
---------------GDRIQ-AQLA-ADENL-------------------
----------------------CRICMDAIIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSAMXG00000005830

---------------------AGA---------------SCMWASCCGLL
NEVMGTGAVRGQQPGFG-GAGPFRFAPSAGYSTYPPNP-----ASQVCHA
CGQTFSVFRRMHVCCDCKKSFCSLCSVLQENLRRCATCHLLKGTAFQRPR
LMRLRVKDLRQYLKLRNINTDTCR--------------------------
----------------------EKEDLVDLVMCHQGTESEDDP-------
----------------------DTP----------TLQT---RPLY----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------S
-----SST----------TDPGPL------------LS--PSH--GEPV-
-SSSDSSES-SNQLSDADSTSLFNLEP---TE-HT---------------
--------------------------------------------------
------PEVSPVVRRSGRASLSDLSSVE--DVEQLTVRQLKEILARNFVN
FSGCCEKWEL-----------VERVRRLYRESEDNRKSMENVSSA----V
N--------------ADVGR-TQLF-NDENL-------------------
----------------------CRICMDAVIDCVLLECGHMVTCTKC---
GK-------RMNECPIC-RQYVIRAVHVFKS-----------------
*
>P1;ENSGACG00000017036

----------------------GA---------------SSMWASCCGLL
NEVMGTGTVRAQQPGFGAGAGPFRFAPSAGYSTYPPTS--AGSAGQLCKA
CGLAFSVFRRKHICCDCKKSFCALCSVLQENLRCCMTCHLLRGTAFQRPR
LMRLRVKDLRQYLLLRNISTDTCR--------------------------
----------------------EKEDLVDLVLCHRGTRESPRPV------
--------------------AEDTD----------SLHS-LPHSLPA---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------A
SPPPAPRS----------ASQQSG------------LS--ASP--GDAP-
-SPSDSSGTSSQEQEDTPTASLLNLEP---AE-SF---------------
--------------------------------------------------
------MEVSPATQRRIRASLSDLDNEE--AIENLSVRQLKEILARNFVN
YSGCCEKWEL-----------LERVHRLYRENEQNRKSMENVSIT-----
A--------------ADGVK-AQLA-ADENL-------------------
----------------------CRICMDAFIDCVLLECGHMVTCTKC---
GK-------RMSECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSXMAG00000015169

-------------------MKAGA---------------SSVWASCCGLL
NEVMGTGAVRGQQPGFGAGAGPFRFAPSAGYSTYPPNS--SGNPGLVCKA
CGQAFSVFRRKYTCCDCKKSFCSLCTVVLESLRICSTCHLLKATEFHRPR
LMRLRVRDLRQYLLLRNISTDTCR--------------------------
----------------------EKEDLVDLVLCHQAFEVEDEEE----EE
----EEEDD------DEEVEDPNTA----------SLLS---HIHR----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
LTDSITPPA----------SELSA----------------ATL--EESL-
-SRSESPET-NQDSDETTPVSLLNLDS---SE-QT---------------
--------------------------------------------------
------PQTSPQTRHGAGASVSDISGVR--DITGLSVRQLKEILARNFVN
YSGCCEKWEL-----------VERVNRLYREKEKNTNTLMAFPSPLCNGA
I--------------GDGEK-CPLTLQDDNL-------------------
----------------------CRICMDAVIDCVLLECGHLVTCTDC---
GK-------RMNQCPIC-RQYVVRAVHVFKC-----------------
*
>P1;ENSTNIG00000014690

--------------------QAGA---------------SSLWASCCGLM
NEVMGTGAVRGQQPVFGAGAGPFRFAPSAGYSTYPPAS--SGTSGLVCKA
CGQAFSVFRRKYICCDCKRTFCTLCSLLQENLPVCATCHLLKATAFQRPR
-MRLRVRDLRQYLLLHSIPIDTCR--------------------------
----------------------EKEDLVDLVLRHQSTEEEE---------
--------------------RADGG----------SLHS---SSFY----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------T
PSPSATQST----------SELSA------------YV--ASQ--DEPL-
-SRSDSSNT-NQDTGDAPSEPLLNMDS---SE-HT---------------
--------------------------------------------------
------PEASPRTWQRSRASLSDVSSVQ--DIEILSVKQLKEILARNYVN
YSGCCEKWEL-----------VERVSRLYRERKETRRSVKETAA------
G--------------PDSEK-APLTVHDDNL-------------------
----------------------CRICMDATIDCVLLECGHMVTCTKC---
GK-------RMNECPIC-RQYVVRAVHVFKS-----------------
*
>P1;ENSLOCG00000004397

-------------------MIPITELRYFADTQPAYRILKPWWDVFTDYI
SIVML-----------------------------------------MIAV
FGGTLQVTQDKMICLPCKWVVNKTCDPFSPKKYIN---------------
---SSVRPSPLVYEPKGIQYDLDRHQYNYVDAVCYENKLHWFAKYFPYLV
LLHTLIFLACSNFWFKFPRTSSKLEHFVSILLKCFDSPWTTRALSETV--
----------------VEESDPKPALGKMNGSMDKKASS-VSEDVEASVP
MLQRTKSRIEQGIVDRSETGVLDKKEGEQAKALFEKVKKFRTHVEEGDIV
YRLYIRQTIIKVIKFILIICYTGYYVNNIKFDVDCSVDIENLTGYQMYRC
AHPLATLFKILASFYISLVVVYGLICMYTLCWMLRRSLKKYSFESIREES
SYSDIPDVKNDFAFMLHMIDQYDPLYSKRFAVFLSEVSENKLRQLNLNNE
WTLDKLRQRITKNSHDKLELHLFMLSGIPDTVFDLLELEVLKLELIPDVT
IPPIIAQLT---------NLKEMWLYHTPAKIEAPALA--FL---RENL-
-KSLHIKFT-DIKEIPLWIYSLKNLSE---LH-LTGNLSAENNRYIVIDG
LRELKRLKVLRLKSNLTKLPQVVTDVGVHLQKLSVNNEGTKLMVLNSLKK
MVNLTELELIRCDLERIPHSIFSLHNLQEIDLKDNNLKTIEEIISFQHLH
RLVCLKLWYNQIAYIPIQIGTLTNLERLYLN----RNKIEKIPSQ----L
F--------------FCRKL-RFLDLSHNNLTYIPADIGFLQNLQYFAVT
ANRIENLPPELFQCKKLRTLNLGNNCLQSLP----SRFGELTSLTQLELR
GNRLECLPVELGECRLLKRSGVIVEEDLFNTLPSEVKEQLWRADKEQA
*
