>P1;ENSGACG00000009471

MTKTA----------------------------AKDLFSMWLPDIRMSKP
VEIEKI-GADSPMEGTADSERNGPESNHQAQSMKVNPFPLSP------SP
S------------------------S-NNKMEECGEMS------------
-------PALPLSH-------GP---------------------TPSQTA
LQHTQLMLT-----------------------------------------
------------------------------SSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLVPGHSLPPSAQFLLPQ-----TQQGQQ----------GLLSTPNLISL
PQQNQGGL-LSASNRMGLQAHQ----------------------RDKCVE
V-------S----GVTTVPSVTSHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSIDCTLPSPSSLSSSSMG
FDGLPGRRRKKRTSIETNVRVALERAFMTNQKPTSEEILLIAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPPTAQPAHKPPCYSPHMM-------S---------SQ
-LSQAVTSLSTT-VTT------------------MSPVCPLTSSLTSTH-
------PSLSSAPSPV-TPP----PPRSTASPATPSHSTLNLNTG-----
--------------------------------------------------
--------------------------------------------------
-----------LWRMGKKNGDVSNYIT-----------------------
-------------------------------------------DFAAN--
--------------------------LSPSSQWWPAASFQS---------
----------
*
>P1;ENSAMXG00000017950

MLPS-----------SDPRAWRLKSPLAL----------RAPADIRMSKP
VEVENPAAADSPMENTGDSERNGSDSNNQFLTVLTLSLSLSLSLSLTLSL
SL-----------------------S-QGKAEECAEMP------------
-------PAS---V-------QT---------------------TPTQTT
LSHTQLMLT-----------------------------------------
------------------------------GGQLAGLTALLPAQQQLLLQ
Q--AQLLAAAVQQTHAAHAASQQQ----TQHAA--NQQSSQQAALPQLQG
QSKSAQEQT--AA----PVPPPPHQLTLSQPIQLTA--QDIQQLLQLQQL
VLVPGHPLPSPAQFLLPQ-----AQQGQQ----------GLLSTPNLIPL
PQQNQGGL-LAAPPTLGLQAQRDK-----------------------IME
S------------SASTVTPVTPHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSMDSTLPSPSSLSSPSLG
FEGLPARRRKKRTSIETSVRVALERSFCTNQKPTSEEILLIAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPQ--PASHKPPCYSPHMM-------P---------GQ
GPSQPITSLSTA-ATT------------------MSSVCPLTPT----G-
------PSSSSTPSPV-AP-----SPRSDTSPIPASHSTISLNTGSWRNK
---------N----------------------------------------
-------------------------------GDVS--------------N
YITDFAANLR-NTVIGVNTGMNQTLRGNNPIATIQALAASGGQPPIS--S
LESGSKVLMGACGGQRSGLPSSLYLNHPSLMSMATSLGLGN--PATPK--
--------SG----KAVF-----LGGMSPSPCSSPASSCSSSEL---VHS
PHLMGGAKIE
*
>P1;ENSDARG00000019658

MFVPLPVPFVLPRTASDLHAWRLKSPLALRSHSGENSYGRLLDYIRMSKP
VEVENP-AADSPMEST-DSERNGSDSNNQVQPMKINPFSISP------TL
SS-----------------------SIKAKVEDCGEMS------------
-------PTT------------A---------------------TPAQTA
LTHTQLMLT-----------------------------------------
------------------------------GGQLAGLTALLPAQQQLLLQ
Q--AQLLAAAVQQSHVAHAANQQQ----AQQQA--QQQANQQAAQQQSQG
QSQSTQEQAA-AAPVPPPPPPPPHQLPLSQPIQLTA--QDIQQLLQLQQL
VLVPGHTLPSPAQFLLPQ-----TQQGQQ----------GLLSTPNLIPL
PQQNQGSL-LAAPPRLSLQAQREK-----------------------IAE
S------------SLNTVTTVTSHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLT-----DAAFFNVYSETMSMDSTLPSPSSLSSPSLG
FEGLPGRRRKKRTSIETNVRVALEHSFLANQKPTSEEILLISEKLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPQ--PTSHKPPCYSPHMM-------S---------SQ
GPRQTVGSLSTA-VTT------------------MSSVCPMTPS----G-
------PSLSSTPSPV-TP-----PPRGDSSPAPPTHSTLNLSTGSWHKK
---------N----------------------------------------
-------------------------------GDVS--------------N
YITDFAASLR-NTVRGVNTGLNQALLGSNPLATIQALAASGGQLPIS--S
LEGSSKVLIGGSGAQGAGLPSSLFLNHSSMLPLATGPGMGLGGSAVGK--
--------TS----F-PV-----TGGMSPSPCSSPASSYSSGEM---LHS
PHSIGGAKIE
*
>P1;ENSORLG00000013228

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------LLPAQQQLLLQ
QAQAQLLAAAVQQSNAAHAAHAAR----AAAQA--NH-------------
-------------------PPPPPQLTLSQPIQLTA--QDIQQLLHLQQL
VFVPGHPLQS--QFLLPQ-----AQQCQQ----------GLLSTPNLIPL
PQQNQGSL-LSAPTRMGLQPQVLCA-----------------LQRDKTTD
V-------S-ASGGVTMAPSVTSHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSIDSTLPSPSSLSSPSLG
FEGVPGRRRKKRTSIETNVRVALERSFLTNQKPTSEEILLIAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPPTA----------PQ-M-------S---------SQ
-LSQAVTTLSSTTVTT------------------MSPVCPMTSSLTSTHP
SLSSAHPPLSSAPSPA-TPPP---PPRSTASPATPSHSTLNLNTGNLFLR
---------RANPV--------------------------------CLCD
LLFTVYGVWQVSALYMCWEEVYPPPVLASKTAVIFPHLSSSGCLSSCTCL
HACGCVCHNR-NNVMGVNTGMNQALLGNNPLATIQALAASGGQLPLS--T
LEGGSKAIVGASGGQGGALASSLFLNHPTLLHMGQNPGAGLVSGAVAK--
--------VSQASPF-PSVSSISPTPCSPSPCSSPASSCLSSEM---GHS
PPSLGGAKIE
*
>P1;ENSORLG00000007050

V---------------------------------------FPTDIKMAKA
SGEEKP-GVDYPGDSS-DSDRNSPDE--QVQTIKSSPYSLSP------ST
GTKLKARLLFLFYLTFSGKGWGFLCP-EGKSEERSEMT------------
-------HSIAPPV-------PP-------------------------SQ
HHHTQLMLA-----------------------------------------
------------------------------GSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLMPGHPLQSPAQFLLSQPTQ--AQQQQQ----------GLLSTPNLIQL
PQQSAGGL-ITTPPRMGLQAQKPE-----------------------RGQ
--------------------GAHMGEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGVAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLS-----DA-------ETMAVDSMLPSPSSLSSPLMG
MEGLPGRRRKKRTSIETNVRVILERNFSTNQKPTSEEILLMAEQLNMEKE
VIRV-WFCNRRQKEKRINPSSS----------------------------
--------------------------------------------------
-----TTPPLPSQTSP-VVTHKAPCYSPHMI-------S---------SQ
GLSQVTTSLSTTDITNVTNDLTGA-------SPSPSASCPMTPVS---S-
------ATI---SSSA-TPP-----PHSTASPAPPNFGSSGLNTGH----
--------------------------------------------------
--------------------------------------------------
------PHFR-NTMMGVSTGMNQALIGSNPLATMQGVCSIW---------
--------------------------------------------------
------------------------------P--------P----------
----------
*
>P1;ENSAMXG00000014322

LFPPLPRPCFVPRNSFLSHIEKNKR--H--------LKCMLNIDIKMSKA
IEDEKT-GADFPADST-DSERNSPEASDQTQPMKTSPFCLSP------TP
SH-----------------------T-KVKAEEPPEMP------------
-------SSHA--P--------P-----------------------PQPT
LQHTQLMLA-----------------------------------------
------------------------------GSQLAGLAALLPAQQQLLLQ
QAQAQLLAAAVQQSNAAHAAHAAQ----AAAAA--NQQQQ--AQQQQQQQ
QSSQAQIQQQAKPE-QSP-AQAPPPLALTQPIQLTA--QDIQQLLQLQQL
VLMPGHPLQSPAQFLLPQA-Q--AQQSQQ----------GLLSTPNLISL
PQQSPGAL-LTTPPRLSMQTQREK-----------------------SVE
STVSSAPS--AAPPMSSVTTVTPHTEEPNDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGMAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLS-----DA-------ETMAIDNMLPSPSSLSSPMLG
FEGLPGRRRKKRTSIETNVRVALERNFITNQKPTSEEILLMAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPPP--ATHKPPCYSPQMM-------S---------AQ
GLAQAATSLSATAVS-----------------PTPSVACPPNPTG---H-
------AAMSSAPSSV-TPP-----PLSTASPAPPSLSSPGLSTGSK---
---------G----------------------------------------
-------------------------------GKIL--------------L
HVTIFSLSLK-NTMMGVSTGMNQALISSNPLATMQALAASGGQMPIT--A
LDGSGQMFLGGAGGPGGGLRPSLFLNRHTLLPMAAGASMGLVSAAR----
-----------VSPP-PSMSRMSPDSCSASPCSSPASFCSFSEA-----S
PPPLGGAMAE
*
>P1;ENSDARG00000036816

MFVPLPVPLVFQRTAPDFSAWRLKSPLP--------LRSGNSVDIRMSKA
MEDDKM-GTELPVDST-DSERNSPEASDQTQPMKTSPFCLSP------AP
SN-----------------------T-KVKGEEAAEMT------------
-------SVHAPPP-------PP-----------------------AQPA
LPHTQLMLA-----------------------------------------
------------------------------GSQLAGLAALLPAQQQLLLQ
QAQAQLLAAAVQQSNAAHAAHAAA----AA-----NQQQS----QQQANQ
AAAQAQS--QAKAE------QAPPPL-LSQPIQLTA--QDIQQLLQLQQL
VLMPGHPLQSPAQFLLPQA-Q--AQQGQQ----------GLLSTPNLIPL
PQQSPGSL-LTTPPRLGLQAQREK-----------------------SVE
SVVSSAPS--SAPPMSSAPTVTPHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGMAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLS-----DA-------ETMAIDNMLPSPSSLSSPLLG
FEGLPGRRRKKRTSIETNVRIALERNFISNQKPTSEEILLMAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPTQPTA--PTHKAPCYSPHMM-------S---------SQ
ALAQVATSLSTTAVS-----------------PTPSVACPLTSSG---H-
------AAMSSAPSSV-TPP-----PLSTVSPTPPSLSSPGLNTG-----
--------------------------------------------------
--------------------------------------------------
-----------NTMMGVSTGMNQALISSNPLATMQALAASGGQMSIS--A
LDGSGQMFLGGAGGPGAGLRQSLFLNRPTLLPLARGAGMGLMGH-R----
-----------ASPP-P-----GPDSCSISPCSSPASFCSLGEA-----S
PPHLGGAMAE
*
>P1;ENSONIG00000004972

MMH----------------------------------ISLHRPDIRMSKA
GE-EKP-GADYPGDSS-DSDRNSPDEQLQAQTMKTSPFSLSP------TP
VG-----------------------N-KGKIEDGSEIT------------
-------HSAALPA-------PP---------------S----QQQQQTQ
HHHTQLMLA-----------------------------------------
------------------------------GSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLMPGHPLQSPAQFLLSQPAQ--AQQPQQ----------GLLSTPNLIQL
PQQSPGGL-LTSPPRLGLQAQAIS-----------------------SGL
SSG------------GHGGHGGHMGEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGVAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLS-----DA-------ETMAVDSMLPSPSSISSPMLG
IEGLPGRRRKKRTSIETNVRVVLERNFSTNQKPTSEEILLMAEQLNMEKE
VIRV-WFCNRRQKEKRINPSSS----------------------------
--------------------------------------------------
-----TTPPLPSQTSP-VVTHKAPCYSPHMI-------S---------SQ
GLSQVTTSLSTTDMTDD---LTGNKHSWKFIGPLSRASCPMTPVS---S-
------VAI---SSSV-TPP-----PHSTASPAPPSLGTSGLNAGI----
--------------------------------------------------
--------------------------------------------------
-----------------TPGI-----------------SWI---------
--------------------------------------------------
------------------------------PRW----KKS----------
----------
*
>P1;ENSGACG00000001968

-------------------------------------------DIRMSKA
AEEEKP-GTEYPGYETNSSQRRRNSPDDQVQPMKTSPSDVSP------TR
TV-----------------------S-KGKGEESCEMI------------
-------HTTIPPA-------PP---------------------------
--TPPLMLA-----------------------------------------
------------------------------GSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLMPGHPLQSPAQFLLSQP-A--QGQQQQ----------GLLATQNLIQL
PQQSQGGL-LTTPPRMGLQAQQEI-----------------------TAG
STMGSSLT----SALTPGGHGGHMGEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGVAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLS-----DA-------ENMAVDSMLPSPSSLSSPMLG
IEGLSGRRRKKRTSIETNVRVALERNFHMNQKPTSEEILLMAEQLNMEKE
VIRV-WFCNRRQKEKRINPSSS----------------------------
--------------------------------------------------
-----TTPPLPSQTSP-IGTHK-ACYSPHMI-------S---------SH
GLSQVTTCLSTTAAS-------------------SSASCPMTPVS---S-
------ATVGSSSSSV-TPP-----PHSTASPVPPTTGI-----------
--------------------------------------------------
--------------------------------------------------
------------TMMGVSTG------------------------------
--------------------------------------------------
--------------------------------------------------
----------
*
>P1;ENSXMAG00000010823

VTHF--------------------------------TRVFPAADIRMSKP
AEVEKV-GADSPLEGT-ESERNGPESNHQVQAMKVSPFSLSP------NL
NS-----------------------S-KNKMDECPEMS------------
-------PGLPPSH-------GP---------------------TPSQTA
LQHTQLMLT-----------------------------------------
------------------------------GSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLVPGHTLPSPAQFLLPQ-----AQQSQQ----------GLLSTPNLIPL
PQQNQGSL-LAAPTRMGLQSQVVEKTNPLPEQARFIHLMSCQVQRDKSID
V-------G-GGGGMTTVPSVTSH---------QADVASALKHLCFD---
--------------------------------------------------
--------------------------------------------------
----------LSCQQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSIDSTLPSPSSLSSPSLG
FDGLPGRRRKKRTSIETNVRVALERSFLTNQKPTSEEILLIAEQLNMEKE
VIRV-WFCNRRQKEKRINPTS-----------------------------
--------------------------------------------------
-----ATPPLPSQPPTAPQTHKPPCYSPHMVTIRPHQMS---------SQ
-LSQAVTSLNSTTVTT------------------MSSICPLTSSLTSTHP
SLTSAHPPLSSTPSPA-TPPP---PPRSTASPATPSHSTLNLNTG-----
--------------------------------------------------
--------------------------------------------------
-----------RPKSSQAFNLDPAIYG-----------------------
--------------------------------------------------
----------------------------------------T---------
----------
*
>P1;ENSTNIG00000008004

SV----------------------------------QPHVGKTEIRMSKS
AEAEKT-GANSPLEGA-DSERNGPESNHQVQPMKISPFPLSP------NL
NS----------------------TN-KNKMEECGEMS------------
-------PSLPLSH-------GP---------------------TPSQTA
LQHTQLMLT-----------------------------------------
------------------------------SSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLVPGHPLPSPAQFLLPQ-----AQQGQQ----------GLLSTPNLIPL
PQQNQGSL-LSAPGRMGLQTQRKTRT--------------------SLPP
F-------H-FHFPLHSCFHWTSHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSIDSTLPSPSSLSSPTLG
FDGIPGRRRKKRTSIETNVRVALERAFMTNQKPTSEEIMLIAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPPSAPATHKAPCYSPHMV-------RLISDPGGGQSQ
-LSQAVTSLSSTTATT------------------M---------------
--------------------------RSTASPATPSHSALNFATDGD---
----DAHMRNSFP-NMTLVPNPLT--------------------------
--------CQH------------------ANGNHCSH------------S
AAVLYNPHNR-NTVMGVNTGMSQALLGNNPLATIQALAASGGQLPLS--S
LEGGSKVMLGPSGGQGGGLPSSLFLNHPALLHMGQNPGAGLISAAVAK--
--------ASQSSPF-PLASSISPTPCSPSPCSSPA----S---------
----------
*
>P1;ENSTRUG00000007484

--------------------------------------------------
--------------------------------------------------
------------------------------MEECGEMS------------
-------PSLPLSH-------GP---------------------TPSQTA
LQHTQLMLT-----------------------------------------
------------------------------SSQLAGLTALLPAQQQLLLQ
QAQAQLLAAAVQQSNAAHAAHAAH----AAAQA--NQQAQ----------
----------------A--AAPPPQLTLSQPIQLTAQEQDIQQLLQLQQL
VLVPGHPLPSPAQFLLPQ-----AQQGQQ----------GLLSTPNLIPL
PQQNQGSL-LSAPGRMGLQSQALSYV----------------RQRDKSAE
V-------S-SGGGMTTVSTVTSHPEEPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSIDSTLPSPSSLSSPTLG
FDGIPGRRRKKRTSIETNVRVALERAFMTNQKPTSEEIMLIAEQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPSQPPSAPATHKPPCYSPHMM-------S---------SQ
-LPQAVTSLSSTTATT------------------MSSVCPLTSSLASTHP
-------SLSSAPSPV-TPPP---PPRSTASPATPSHSALSLNTGILMSC
FTLATAHVRRTVLVSPAVWSKRLIRAHAGTTASTVQRCSITLCVSVCVV-
FVFTAYGAWLF----------------------------PSAC-------
-LCSYVCLHM-NTVMGVNTGMSQALLGNNPLATIQALAASGGQLPLS--S
LEGGSKVMLGASGGQGGGLPSSLFLNHPALLHMGQNPGAGLISAAVAK--
--------ASQSSPF-PSASSISPTLCSPSPCSSPASSCSSSEM---A--
---------H
*
>P1;ENSXMAG00000016603

CVC----------------------------------VVVFSADIRMSKA
PGEEKP-GAEYPGDGS-DSDRNSPDDQLQVQKMRSSPYSLSP------TA
AG-----------------------S-KVKSEESSEIT------------
-------HSAAAAAAAAPPAAPP---------------SQQQQQQQQQAQ
HHHTQLMLA-----------------------------------------
------------------------------S----S--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLMPGHPLQSPAQFLLSQPAQ--AQQPQQ----------GLLSTANLIQL
PQQSAGGL-LTSPSRMGLQAQHLR-----------------------AAL
LSEKHLYLYLYHFSLNPGSQTVQMSEEPEE----RQTEHTKFSILIH---
--------------------------------------------------
--------------------------------------------------
----------YLLCQGDVGVAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLS-----DA-------ETMAVDSMLPSPSSISSPMLG
IEGLPGRRRKKRTSIETNVRVVLERNFSTNQKPTSEEILLMAEQLNMEKE
VIRV-WFCNRRQKEKRINPSSS----------------------------
--------------------------------------------------
-----STPPLPSQTSP-VVTHKVHCYSPHMV-------PSRTEPYKISSQ
SLSQVTTSLSTTGAS-----------------SSPSASCPMTPVS---S-
------VAM---SSSATPPP-----PHSTASPAPSSLGTAGLATG-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------
*
>P1;ENSONIG00000013106

CL----------------------------------SACFPVTDIRMSKP
GEAEKV-GADSPLEGT-DSERNGPESNHQTHSMKACPFPLSP------NL
SS-----------------------T-KNKMEECADMS------------
-------PALPSSH-------GP---------------------TPSQTA
LQHTQLMLT-----------------------------------------
------------------------------GSQLAG--------------
--------------------------------------------------
---------------------------------------DIQQLLQLQQL
VLVPGHPLPSPAQFLLPQ-----AQQSQQ----------GLLSTPNLIPL
PQQNQGSL-LSAPTRMGLQAQVQVLP----------------LQRDKGVE
V-------S-G-GGVTTVPSVTSHPEDPSDLEELEQFARTFKQRRIK---
--------------------------------------------------
--------------------------------------------------
----------LGFTQGDVGLAMGKLYGNDFS-QTT----ISRFEALNLSF
KNMCKLKPLLEKWLN-----DA-------ETMSIDSTLPSPSSLSSPSLG
FDGVPSRRRKKRTSIETNVRVALERSFMTNQKPTSEEILLIADQLNMEKE
VIRV-WFCNRRQKEKRINPSS-----------------------------
--------------------------------------------------
-----ATPPLPNQPPAAPPAHKPPCYSPHMM-------S---------SQ
-MSQAVTSLSSTSVTT------------------MSSVCPLTSSLTSTHP
SLSLTHTPLSSTPSPA-TPPPPPIPPRSTASPATPSHSTLNLN-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------
*
>P1;ENSLOCG00000003811

LYFFY-------------------SS----------SPSRALCTLRMLRQ
VLHEGL-RTS-------FSKLGHFVANHPVF-FASAPVLISI------LL
GSS---------------------FS-HYRVEENVEYLLAPKHSLAKIEG
NLVDSLFPVNR-SKHTLYSDLQTPGRYGRVIVTSSARGS--------ILD
QHHVDLILKLHGLVTKIQVHMNGFNYTFAHMCILDDNKSCIVDDILRVLE
ELRAARFANRTGGAVRYPITYLRDGREVYIGHQLGGVQS--PGKVQVK--
HAEAVQLTYYLQAVNSLNDVVAAKWETKFCETVERFQQAN----GELKM-
---------------------------YPFTSSSLQ--GDFQKTSKVSER
PLITSLALCVALAVLFCSMRDCVRTKPWLGLLAVVTMSLAMLTSAGIINL
TGGKYNSTFLGIP-FI----------------------------------
--------------------VLGH-GLCGTFEMLSSWRRTREDQHVKERA
AAVFADCMLPFTASTAMYMVTFGIGASPFTNIEAVRVFCRNTCISVFFNY
LYILTFYGSNLVFTGYLENNYQHNIFCKKVPKPELLQQKPAWYRFLMYTQ
YNEEGAESADMNAYEGHLLVSFMKRYYCDWITNTYVKPFVVLFYLVYISF
ALMGYLQVSEGSDLSNVVATET-------STIAYTTAQQKYFSNYSPVIG
FYIYESIEYW-NASV-------------------------QEDVLEYTKG
FVRISWFESYLNYLRKLNMTTGLPKRNFTELLRNAFLKLPQFCHFSDDII
FARRAGGEVDVVASRMFLVAKTTENKREEMYILLDTLRKLSLTSKVKFII
FNPSFVYMDRYASSLG--APLKNSCISALFL-------LFFS-AFLVADS
-LINIWVTLVVVSVEF----------------------------------
-------------------------------------G------------
--------------------------------------------------
---------------------------------VI--------------G
FITLWKVELDCISMLCLIYGLNYTIDSCAPLISTFVLGRDFTRTKWVKIT
LE-----------RHGVSMLQSYLCYTASLLPLAAVPSNLTRT--LFRCL
FLTAFISFFHCLAIL-PIMLTFLPPSKKKRKEKKPAENREEIECVEIVDS
TRVVDQITTV
*
