>P1;ENSTNIG00000009362

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------MFQYYGYNGYLSDRLPLDR--------
-PIPDLRPDGCRNT-----------------------T----YPLSLPQV
SIVFIFVNEALSVILRSIHS--------------------AINRTPSHLL
KEIILVDD--------NSSNNELKEKLEDFVSQTNSQR-PGFIKVVRHSK
QEGLIRSRVSGWRAATAPVVALFDAHVEFNIGWAEPILQRIQEDRTRII-
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWFKGNKSAPI-
-----QSPALIGCFVV-DRLYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIR-------------------VWQCGGSIEVLPCARIAHI
ERAHKPYTED-LT-------------------------------------
-----------------HVRRNASRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NIPHGAHQDSGID
IGDVS--DRKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNMYPE-----------MRMYS-DTVAYGSGQLKNSLKNDLC-
LDQGPDNDN-VPILYLCHGMTPQ-TVYYTSAQQIHIGLLSPTVDDDDNKC
LVDVNSRLRLIECSYAAAKRMKLHWL-FTQGGPIQNRKSKRCLELIASS-
DNEFGYQLALQKCTGQ----------------------------------
--------KWFITNVLFNGSL---------
*
>P1;ENSGACG00000015704

--------------------------------------------------
--------------------------------------MACTR---RTKT
LVSTCVILSGMTNIVCLLYVGWVTNYIANI-YIKVPMP-------LPERK
LEGDKRGDTLRIIERLDRLENVVNQHIQETPARGDGGQVDTSFS------
DSSLFA-HWGQELSPDNRRVALKMFQYYGYNGYLSDRLSLDR--------
-PIPDLRPDGCRNL-----------------------T----YPLNLPQV
SIVFIFVNEAFSVILRSIHS--------------------AINRTPSHLL
KEIILVDD--------NSNNNELKEKLHDFVSETNRQH-PGFIKMVRHAK
QEGLIRSRVSGWRAATAPVVALFDAHVEFNVGWAEPILERIKEDRTRIIS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWHKGNKSAPIQ
MFYPPRSPALIGCFVV-DRLYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIRVKELYSTILK---ALPLALVWQCGGSVEVLPCARIAHI
ERAHKPYTED-LTS------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NIPM---EDPGID
IGDIS--ERKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNIYPE-----------MRMYS-DTVAYG--VLKNSLKSDLC-
LDQGPENDN-VPILYLCHGMTPQ-NVYYTSAQQLHIGLLSPTVDDDDNKC
LVDVNGRPRLIECSYATTKRMKLHWL-FTQGGSIQNRKSKRCLELVVSS-
DNEFGYQLALQKCTGQ----------------------------------
--------KWSITNVLFSGSL---------
*
>P1;ENSONIG00000010691

--------------------------------------------------
--------------------------------------MLCTR---RTKT
LVSTCVILSGMTNIVCLLYVGWITNYVANS-GPKVAESGGGGGGGEAERK
LEEDSKGETLRIIERLDRLESVVNEHIKETPLKDGEDAASSSDA--ASDP
ASSLFN-HWGHDLGPESRRVALKKFRYYGYNGYLSDRISLTR--------
-PIPDLRPDGCRNM-----------------------S----YSSDLPQL
SVIFIFVNEALSVLLRSIHT--------------------AIQRTPSHLL
KEIILVDD--------HSNSLELKEHLQNFVDETNVQHGPGFIKVVRHDK
QEGLIRSRVSGWRAASAPVVALFDAHVEFNTGWAEPILQRIKEDRTRVVS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWTQHNNTAPI-
-----RSPALIGCFVV-DRKYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGIR-------------------VWQCGGSVEVLPCSRIAHI
ERAHKPYTEN-LTA------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDQYKSHVYMAW-NVPL---QNSGID
IGDIS--KRKALRSRLR---------------------------------
-------------------------------------------------C
RPFSWFLSNIYPE-----------LRSYS-DTVAYG--VLKNSLRDDLC-
LDQGPDTDN-VPIMYLCHGMTPQ-NVYYTSSQQLHLGVLSPTIDDDDNKC
LVDVNSKPRLLECSYATTKHMKLTWT-FTQGGPIQNIESQRCLELVESR-
QSGFSFQLAIQDCTDQ----------------------------------
--------KWTITNILTVLPQ---------
*
>P1;ENSXMAG00000015650

--------------------------------------------------
--------------------------------------MLCTR---RTKT
LVSTCVILSGMTNIVCLLYVGWITNYVANT-GSKVAESG----GGETDRK
LEEDGKGETLRIMERLERLESVVNEHIKETPLKDGEEAASSSDS--AADP
AASLFN-HWGRDLGPESRRVALKKFRYFGYNGYLSDRISLTR--------
-PIADLRPDGCRNM-----------------------S----YSSDLPQL
SVIFIFVNEALSVLLRSIHT--------------------VIQRTPSYLL
KEIILVDD--------NSNSLELKEHLQSFVDETNTQHGPGFIKVVRHTK
QEGLIRSRVSGWRVATAPVVALFDAHVEFNTGWAEPILQRIKEDRTRVVL
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWMLRNHTAPI-
-----RSPALIGCFVV-DRKYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGIR-------------------VWQCGGSVEVLPCSRIAHI
ERAHKPYTEN-LTA------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDQYRSHVYMAW-NVPL---QNSGID
IGDIS--ERKALRSRLR---------------------------------
-------------------------------------------------C
RPFSWFLSNIYPE-----------LRSYS-DTVAYG--VLKNSLRDELC-
LDQGPDSDN-IPIMYLCHGMTPQ-NVYFTSSQQIHLGVLSPTIDDDDNKC
LVDVNSRPRLLECSYAATKHMKLTWT-FAQGGAIQNIESQRCLELVESK-
QSAFTFQLAIQDCTGQ----------------------------------
--------KWTITNILTVLPQ---------
*
>P1;ENSONIG00000006002

--------------------------------------------------
--------------------------------------MACTR---RTKT
LVSTCVILSGMTNIVCLLYVGWVTNYIANI-YIKVPMP-------LPERK
LEGDKRGDTLRIMERLDRLENVVNQHIHETPGKDDDGQPDTSFS------
DSSLFA-HWGQELSPDNRRVALKQFQYYGYNAYLSDRLSLDR--------
-PIADLRPDGCRNI-----------------------T----YPLNLPQV
SIVFIFVNEALSVILRSIHS--------------------AVNRTPSHLL
KEIILVDD--------NSNNNELKEKLQDFVSETNSQR-PGFIKMVRHDK
QEGLIRSRVSGWRVATAPVVALFDAHVEFSVGWAEPILQRIKEDRTRIIS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWHKGNKTAPI-
-----QSPALIGCFVV-DRLYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIR-------------------VWQCGGSIEVLPCARIAHI
ERAHKPYTED-LTS------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NIPL---EDSGID
IGDVS--GRKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNIYPD-----------MRMYS-DTIAYG--VLKNSLKTDLC-
LDQGPDNDN-MPILYLCHGMTPQ-NVYYTSAQRLHIGLLSPTVDDDDNKC
LVDVNSRPRLIECSYAAEKRMKLHWL-FTQGGSIQNRKSKRCLELVASS-
DNEFGYQLALQKCTGQ----------------------------------
--------KWFITNVLFSSSL---------
*
>P1;ENSTRUG00000008973

--------------------------------------------------
--------------------------------------MLCTR---KTKT
LVSTCVILSGMTNIVCLLYVGWITNYVANG-GPKVAESG----GGEADRK
LEEDSKGESLRIMERLDRLESVVNEHIKEAPQKDGETAASSYTSDSASDA
ASLLFH-RWGHDLGPESRRVALKKFRYYGYNSYLSDRISLTR--------
-PIPDLRPDSCRNM-----------------------T----HSSDFPQL
SIIFIFVNEALSVLLRSIHT--------------------AIQRTPTHLL
KEIILVDD--------HSSNWELKDHLQSFVEETNAQHWPGFIKVVRHDK
QEGLIRSRVSGWRAASAPVVALFDAHVEFNTGWAEPILQRIMEDRTRVVS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKVWWAQRNHTAPI-
-----RSPALIGCFVV-DRKYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGIRVSGIMNTLDI---TGPL-QVWQCGGSVEVLPCSRIAHI
ERAHKPYTQN-LTA------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDQYKSHVYMAW-NIPL---QNSGID
IGDIS--GRKALRSRLR---------------------------------
-------------------------------------------------C
RPFSWFLSNIYPE-----------LRSYK-GIVAYG--VLKNSLRDNLC-
LDQGPDGDN-APIMYLCHGMTPQ-NVYYTSSQQLQLGVLSPTIDDDDNKC
LVDVNSRPRLLECSYAATKHMKLTWS-FTQGGAIQNIDTLHCLELVASK-
QSESTFHLALQDCTDQ----------------------------------
--------KWTITNILTLLPQ---------
*
>P1;ENSTRUG00000017462

--------------------------------------------------
--------------------------------------MACTR---KTKT
LVSTCVILSGMTNIVCLLYVGWVTNYIANI-YIKVPMP-------VAERK
LEGDKRGDTVRIMERLDRLENVVNQHIQETPGRGDEGQADTSFS------
DSSLFA-HWGQDLSPDNRRVALKMFQYYGYNGYLSDRLPLDR--------
-PMPDLRPDGCRNI-----------------------T----YPLNLPQV
SIVFIFVNEALSVILRSIRS--------------------AINRTPSHLL
KEIILVDD--------NSSNNELKEKLEDFVSQTNSQR-PGFIKVVRHLK
QEGLIRSRVSGWRAATAPVVALFDAHVEFNIGWAEPVLQRIQEDRTRIIS
PSFDNIKYDTFEIDEYPLSAQGFDWE-LWCRYLNPPKSWWYKGNKSAPI-
-----QSPALIGCFVV-DRLYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIRVSNDTKTDHCGICLAPV-TVWQCGGSIEVLPCARIAHI
ERAHKPYTED-LTS------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NVPM---EDSGID
IGDVS--ERKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNMYPE-----------MRMYS-DTVAYG--VMKNSLKNDLC-
LDQGPDNDN-VPILYLCHGMTPQ-TVYYTSTQQLHIGLLSPTVDDDDNKC
LVDVNSRLRLIECGYAAAKRMKLHWF-FTQGGPIQNRKSKRCLELVASS-
DNEFGYQLTLQKCTGQ----------------------------------
--------KWFITNVLFNNSV---------
*
>P1;ENSXMAG00000003053

--------------------------------------------------
--------------------------------------MACTR---RTKT
LVSTCVILSGMTNIVCLLYVGWVTNYIANI-YIKVPMP-------LAVGK
LEGDKKGDTLRIMERLDRLESVVNQHIQETPGKGEDGLPDTSFS------
DSSLFA-HWGQELSPDNRRVALKMFQYYGYNAYLSDRLSLSR--------
-PIPDLRPDGCRNI-----------------------T----YPLNLPQV
SIVFIFVNEALSVILRSIHS--------------------AINRTPSHLL
KEIILVDD--------NSNNDELKEKLQDFVSETNSQH-PGFIKIVRHTR
QEGLIRSRVSGWRAATAPVVALFDAHVEFNVGWAEPILLRIKEDRTRIIS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKTWWHRGNKSAPI-
-----QSPALIGCFVV-DRLYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIR-------------------VWQCGGSVEVLPCARIAHI
ERAHKPYTED-LTS------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NVPI---EDSGID
IGNIS--ERKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNIYPE-----------MRMYS-DTIAYG--VLRNSLKNDLC-
LDQGPDNDN-VPILYLCHGMTPQ-NVYYTSNQQFLVGLLSPTVDDDDNKC
LVDVNGRPRLIECNYAAAKRMKLHWL-FTQVLEDIRRIPFLWGHLFWRI-
YSEQKIKEMPRACGEQ----------------------------------
--------RQ--------------------
*
>P1;ENSGACG00000002430

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------ETPRKDGEEAASSSDS------
SSSLFD-HWGHDLGPESRRVALRKFRYYGYNGYLSDRISLTR--------
-PIADLRPDGCRNM-----------------------S----YSSDLPQL
SVIFIFVNEALSVLLRSVHT--------------------AIQRTPSHLL
KEIILVDD--------HSSSLELKENLQRFVEETNIQYGLGFVKVVRHDK
QEGLIRSRVSGWRAASAPVVALFDAHVEFNTGWAEPILQRIKENRTRVVS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPRSWWSQHNHTAPI-
-----RSPALIGCFVV-DRKYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGIR-------------------VWQCGGSVEVLPCSRIAHI
ERAHKPYTEN-LSA------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDQYKSHVYMAW-NVPL---QKSGID
IGDIT--ERKALRSRLQ---------------------------------
-------------------------------------------------C
RPFSWFLSNIYPE-----------LRSYS-NTVAYG--VLKNNLRDNLC-
LDQGPDTDN-VPIMYQCHGMTPQQNVYYTSSQQLHLGVLSPTIDDDDNKC
LVDVNSKPRLLECSYAATKHMKLTWT-FTQGGSIQNMESLCCLELIETG-
QSEFSFRLVIQDCTDQ----------------------------------
--------KWTITNILTVLPQ---------
*
>P1;ENSORLG00000007327

--------------------------------------------------
--------------------------------------MACTR---RTKT
LVSTCVILSGMTNIICLLYVGWVTNYIANI-YIKVPMP-------VAERN
SEVDKKGDTLRIMERLDRLETVVKQHIQETPGKDEVSQADASFS------
DSSLFT-HWGQELSSDDRRVALKMFQYYGYNTYLSDRLSLSR--------
-PIPDLRPDGCRNI-----------------------T----YPLSLPQV
SIVFIFVNEALSVILRSIHS--------------------AISRTPSHLL
KEIILVDD--------NSSNNELKEKLQDFVSETNKQR-PGFIKVVRHDK
QEGLIRSRVSGWRAATAPVVALFDAHVEFNVGWAEPILQRIKEDRTRIIS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWHKGNKNAPI-
-----QSPALIGCFVV-DRLYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIRVSDPQHSDLL---DLPC-RAWQCGGSVEVLPCARIAHI
ERAHKPYTED-LTS------------------------------------
-----------------NVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NIPM---EDSGID
IGDIS--ERKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNIYPE-----------MRMYS-DTIAYG--VLKNSLKSDLC-
LDQGPDGDN-VPILYLCHGMTPQ-SVYYTQTQELHIGLLSPTIDDDDNKC
LVDVNSKPRLTECSYAAAKRMKLQWL-LTQGGSIQNKKSKRCLELVTSS-
SNEFGFQLALQKCTGQ----------------------------------
--------KWFITNVLFSNLL---------
*
>P1;ENSDARG00000059438

--------------------------------------------------
--------------------------------------MACTR---RTKT
LVSTCVILSGMTNIVCLLYVGWVTNYIANV-YIKVPVP-------VPAKK
LEGDRKGETLRIIERLDRLENVVNQHIQESPLKGDDNQVDRSFA------
DSSLFN-HWGQDLGPESRRVALKMFQYYGYNGYLSDRLSMDR--------
-AIPDYRPDGCKNM-----------------------S----YPSNLPQV
SIVFIFVNEALSVILRSIHS--------------------VMNRTPSHLL
KEIILVDD--------NSNNDELKEKLQDFVKETNAKQ-PGFIKVVRHSR
QEGLIRSRVSGWRAASAPVVALFDAHVEFNIGWAEPILQRIKEDRTRIIS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWNLNNSTAPI-
-----RSPALIGCFVV-DRLYFAEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGVR-------------------VWQCGGSVEVLPCARIAHI
ERAHKPYTED-LTA------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NIPQ---EDSGID
IGDIA--ERKALRKKLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNIYPE-----------MRMYT-DTVAYG--VLRNSLKTDLC-
LDQGPDTDN-IPILYLCHGMTPQ-NVYYTSTQQLFVGILSPTVDDDDNKC
LVDVNGRPRLIECSYAVAKRMKLHWR-FTQGGSIQNTKSKRCLELVENN-
DNEFGFQLTLQKCTGQ----------------------------------
--------NWTITNMLPGSTL---------
*
>P1;ENSTNIG00000006208

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------KFRYYGYNSYLSDRISLTR--------
-SIPDFRPDSCRNM-----------------------T----YSSDFPQL
SLIFIFVNEALSVLLRSIHT--------------------AIQRTPSHLL
KEIILVDD--------HSNSWELRDHLQSFVEETNAQHSPGFIKVVRHDK
QEGLIRSRVSGWRIASAPVIALFDAHVEFNTGWTEPILQRIKEDRTRVVS
PSFDNIKFDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWAQRNHTAPI-
-----RSPALIGCFVA-DRKYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGIR-------------------VWQCGGSVEVLPCSRIAHI
ERAHKPYTEN-LAA------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDQYKSHVYMAW-NIPL---QNSGID
IGDIS--ERKALRSRLQ---------------------------------
-------------------------------------------------C
RPFSWFLSNIYPE-----------LRSYN-GIVAYG--VLKNSLRDNLC-
LDQGPDGDN-IPIMYLCHGMTPQ-NVYYTSSQQLQLGVLSPTIDDDDNKC
LVDVNSRPRLLECSYAATKHMKLTWA-FTQGGPIQNIDSQHCLELVAVK-
GSESAFHLAIQECTDQ----------------------------------
--------KWTITNILTLLPQ---------
*
>P1;ENSDARG00000100889

MTPSRTSRARVQPSCKTRCQTVRTSARETSTQIQTAAARCHIRCAGDAEP
KRYTRDRSFRLHESRTAAKRVEDFCTSFCARFARGDVAMACTR---RTKT
LVSTCVILSGMTNILCLLYVGWITNYVSNNGNVKVAGR-------THEKK
FDDDSKGETLRIIERLDRLESVVNQHIQEKPQSDIEDSADLSLS------
-ETLFA-HWGHELGPESRKVALRKFQYYGYNAYLSDRLSLDR--------
-AVPDLRPDGCRNI-----------------------S----YPTGLPQV
SIIFIFVNEALSVILRSVHS--------------------VIQRTPAHLL
KEIILVDD--------HSNNAELLENLQRFVDETNQQQ-RDFIKVVHHEK
QEGLIRSRVSGWRAASAPIVALFDAHVEFSIGWAEPILHRIQEDRTRVIS
PSFDNIKYDTFEIEEYPLSAQGFDWE-LWCRYLNPPKSWWMQKNQTAPI-
-----RSPALIGCFVV-DREYFEEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
VYGGENVELGIR-------------------VWLCGGSVEVIPCSRIAHI
ERAHKPYTED-LAT------------------------------------
-----------------HVRRNALRVA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NIPQ---QDSGID
IGDIR--DRKALRERLR---------------------------------
-------------------------------------------------C
KPFSWFLNNIYSE-----------MRTYM-DTIAYG--VLRNSLRPDLC-
VDQGPDSDN-IPILYICHGLTPQ-NVYFTSSQQLHVGGLSPTIDDDDNKC
LVDVNSRPRLLECSYASNKHMKLSWL-FTQGGSIQNKKSKRCLELVESA-
DVDHGYQLVLQKCSSQ----------------------------------
--------KWTITHILPGKVL---------
*
>P1;ENSAMXG00000010122

--------------------------------------------------
--------------------------------------MACTR---RTKT
LVSTCVILSGMTNIVCLLYVGWVTNYIASV-YIKVPVP-------VPARK
LDGDKKGETLRIIERLDRLENVVNQHIQETPLKGDDNQEDRSFA------
DSSLFN-HWGQELSPESRRVALKLFQYYGYNGYLSDRLSMDR--------
-PIPDYRPEGCKNI-----------------------S----YPSNLPQV
SIVFIFVNEALSVILRSIHS--------------------AMHTTPSHLL
KEIILVDD--------NSNSEDLKEKLQEFVEETNAKH-PGFIKVVRHSK
QEGLIRSRVSGWRAASAPVVALFDAHVEFNAGWAEPILQRIQEDRTRIIS
PSFDNIKYDTFEVEEYPLSAQGFDWE-LWCRYLNPPKSWWNLNNSTAPI-
-----RSPALIGCFVV-DREYFAEIGLLDEG-------------------
--------------------------------------------------
------------------------------------------------ME
IYGGENVELGVR-------------------VWQCGGSVEVLPCARIAHI
ERAHKPYTED-LTA------------------------------------
-----------------HVRRNALRMA-----------------------
--------------------------------------------------
--------------------------------------------------
---------------------EVWMDEFKSHVYMAW-NVPQ---EDSGVD
IGDIS--ERKALRKRLQ---------------------------------
-------------------------------------------------C
KTFRWYLVNIYPE-----------MRMYT-DTIAYG--TLKNSLKTELC-
LDQGPDTDN-VPILYLCHGMTPQ-NVYYTSTQLLYVGILSPTIDDDDNKC
LVDVNSRPKLIECSYAAAKRMKLHWL-FTQGGSIQNRKSKRCLELVESN-
DNEFGYQLALQKCTGQ----------------------------------
--------KWTITNILPGSTL---------
*
>P1;ENSLOCG00000014890

--------------------------------------------------
--------------------------------------MYHQPVLKNRRT
L-------------------------------------------------
------------LER---AEKFI---------------SDIYFT------
DCNLRGSAFHSQQPPSKRRLLVRSLKCVGYLNSIRTK-PLKRVKVWGWEI
TGAPSKNPHGYRGAHDSIWTGTQPPEMQGLTKEGEKTSYILSESLREEEA
HSVTLYVEVACNGLFGAGQGSMIAPPDPHRKYSVQRAELAVFNRGVQELL
TDFEMLIDVVKVLGENEQRGYQALFTANEMVNLCDPSD-PSTFSAARHLA
E--VFFSQRNGQ--SQHTVHAMGHCHIDSGRAPTRPVLCRHA---PVLLF
PHTSCLHLSSDSFIKFCLQAQQFEWVRKWYPGLYSQ------------I-
-----QQFASRGQFVPVGGTWVEMDGNLPSGESMVRQFLEGQRFFHQEFG
RYCTEFWLPDTFGYSAQLPQIMQGCGIKSFLTQKLSWNLVNTFPHNTFFW
EGLDGSQVLTHFPPGNSYEMKCKVEDLLNSVRNNRDKGRANHSAVLFGFG
DGGGGPTQLMLD-------------------RLQRVSDTDGLP--RVAHS
VKPCFPESQSSLKSQDSRCTTYRELNFLRCCMQTQVDSAKIKLGNRQCEA
LLHDIEIASSLALCRSSGFRYPAQELRELWRLLLLNQFHDVIPGSCIEMV
VQDALKYYQEIRSTGAGLLQEAYRGLWGVDPQGAGSMALNTLPWERTEVI
ALPGSGGAEPKLALVQVPSIGFATVTESEPVYPVTVAVQADGSILMENGI
LRVVVDKAGNVASLCLVKSNREAIADGFSGNQFVLFDDVPL---YWDAWD
VMDYHLQTRTPVREVLRPAEIACSGGLRGSVKFSLRISSKSSISQEVILD
AMCPCVKFHTQVDWAESHKFLKVEFPVRVRSPSATYEIQFGHLQRPTHRN
TSWDWARFEVWGHKWADLSEHGFGVALLNDCKYGYS--VYRNTLTLSLLR
APKAPDANADMGQHQFTYAVMPH------------AGSFQ---DSGVIQC
AYNLNLPLRVIPMVISD--PASSSWSAFSLSSP------AVILETVKQAE
DQKDALLLRLFESHGSSVTVTLTTALPVKEALLCDLLERPDSARPAAVMP
SGISLSFTPFQIVSLLLVLNKIQHKKEPPR
*
