>P1;ENSTNIG00000010005

----------M---ADRDSGSEQ-------GG----------AAMGPG--
------------------FASMHLATGGA---------------------
--------------------------GLASGLQHETQELASKRVDIQNKR
FYLDVKQNPKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPTHPGL--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSTQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGSSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPYKVWS-KFGNTFSKYAEEMKKIQEKQREKRACEE-----
--M-QADDGDED
*
>P1;ENSAMXG00000024949

----------M---ADRDSGSEH-------GG----------FATGGGGI
GGGGGGGPGGGGPGGGGGLGL--PHPGAV---------------------
--------------------------GAASRLQHDTEELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSHPDT--------
--------------------------------------AQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRVRQTVNRGP-------------------
---------------GLGTAQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVDEEPAE-
------------------LPEGTSLAVDNKRFFFDVGANKYGVFMRVSEV
KPAYRNSITVPCKVWS-KFGATFCKYADEMKRIQERSRERRARELLPE--
-GLH-GDDGDED
*
>P1;ENSAMXG00000025364

----------M---ADRDSGSEQ-------GG----------APTGPG--
------------------VG-LHAVAGGA---------------------
--------------------------GSASGLQHDTQELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPDA--------
--------------------------------------AQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSAQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGTSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPYKVWA-KFGSTFCKYAEEMKKIQDKQRERRACEQQQQQP
GEM-HADDGDED
*
>P1;ENSGACG00000018680

----------GSRGCSRQRETVE-------GK--------AGRQHHGGQ-
------------------R----QWQCAM---------------------
--------------------------GAMSRLQHDTEELASKRVDIQNKR
FYLDVKQNVKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPTNPDI--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSAQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVDEEPAE-
------------------LPEGTSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPCKVWS-KFGNTFCKYAEEMRKIQERNREKRAS-------
------------
*
>P1;ENSTNIG00000004639

----------M---ADRDSGSDH-------GG----------PTGGPG--
------------------S----LPAGAM---------------------
--------------------------SAMSRLQHDTEELASKRVDIQNKR
FYIDVKQNVKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPDV--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSAQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVDEEPAE-
------------------LPEGTSFTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPCKVWS-RFGNTFCKYAEEMKKIHERSREKRASELLPE--
-GSH----GEDD
*
>P1;ENSDARG00000067591

----------M---ADRDSGSEQ-------GG----------AATGPG--
------------------VGSMHPVTGGA---------------------
--------------------------GSASGLQHETQELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPDM--------
--------------------------------------PQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSTQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGTSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPYKVWS-KFGSTFCKYADEMKKIQEKQREKRACELQQQQQ
EEM-HGDDGDED
*
>P1;ENSTRUG00000006789

----------M---ADRDSGSDH-------GG----------PTGGPG--
------------------S----LPAGAM---------------------
--------------------------GAMSRLQHDTEELASKRVDIQNKR
FYIDVKQNVKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPTNPDI--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSAQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVDEEPAE-
------------------LPEGTSFTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPCKVWS-RFGNTFCKYAEEMKKIHERSREKRASELLPE--
-GSH----GEED
*
>P1;ENSONIG00000021362

----------M---ADRDSGSEQ-------GG----------AATGPG--
------------------FGSVHLATGGA---------------------
--------------------------GSASGLQHETQELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPGM--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGFTQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGSSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPYKVWS-KFGNTFCKYAEEMKKIQEKQREKRACELQQQ--
EEM-QQDDGDED
*
>P1;ENSXMAG00000019887

----------M---ADRDSGSEQ-------GG----------AATGPG--
------------------FGSMHLAAGGA---------------------
--------------------------GSASGLQHETQELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPGM--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSTQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGSSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPYKVWS-KFGNTFCKYAEDMKKIQEKQREKRACELQQQ--
EEM-QADDGDED
*
>P1;ENSGACG00000020655

QRGRRQAGSIM---ADRDSGSEQ-------GG----------APTGPG--
------------------FGSMHPATGGA---------------------
--------------------------GSASGLQHETQELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPAL--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSTQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGSSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPYKVWS-KFGNTFCKYAEEMKKIQEKQREKRACELQQQ--
EEL-QADD---D
*
>P1;ENSORLG00000006100

----------M---------------------------------------
----------------------HLPTGGA---------------------
--------------------------GSASGLQHETQELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPGM--------
--------------------------------------IQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSTQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVEDEPAE-
------------------LPEGSSLTVDNKRFFFDVGSNKYGVFMRVSEN
YHK---------KEEG-KKKSHLCQLMTDKQPAQTVVKVRR---------
------------
*
>P1;ENSDARG00000099614

----------M---ADRDSGSEH-------GG----------FATGPG--
------------------AGP--M---HP---------------------
--------------------------GAASRLQHDTEELASKRVDIQNKR
FYLDVKQNAKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPSNPDL--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGTSQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDFGVDEDPAE-
------------------LPEGTSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPCKVWS-KFGATFCKYADEMKKIQERSRERRAREMLPE--
-GLH-GDDGDED
*
>P1;ENSONIG00000020655

----------M---ADRDSGSDH-------GG----------PTAGPG--
------------------S----LPPGAM---------------------
--------------------------GAMSRLQHDTEELASKRVDIQNKR
FYLDVKQNVKGRFLKIA---------------------------------
-----------------------------------------------EVG
AGGNKSRLTLSMS--VAVEFRDYLGDFI-EHYAQLGPTNPDM--------
--------------------------------------VQ----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------DEPRRALKSEFLVR
ENRKYYMDLKEN---QRGRFLRIRQTVNRGP-------------------
---------------GLGSAQGQT--------------------------
-------------------IALPAQGLIEFRDALAKLIDDYGVDEEPAE-
------------------LPEGTSLTVDNKRFFFDVGSNKYGVFMRVSEV
KPTYRNSITVPCKVWS-KFGNTFCKYAEEMRKIQERSREKRASELLPE--
-GPHGGDDGDDD
*
>P1;ENSLOCG00000003942

----------M---SDHYVKVRVQLEQMRVAGLETEPEAASLLASSPG--
--------------------SVDLVSGGRRDAARSAVRTRARSKSRGKRS
ELDRNTAGADNKEDTPEPEYPPGPMDGTAGQLQHSRSPK-DAVLQIKGTG
KIPQGKAEANGKTEKEGKTQQGKDDGNKLPKKRKMVTVDTSKAKTSLEAL
KVSIKQLKWKEFPLGRRVACDIYWHGVSFHDNENVFSGLVNKFPGMIEML
RKINLSRAVRTMQELFPEEYNFYPRSWILPEEFQLFAAQVRIAKDKDPSW
KPTFIVKPDGGSQGDGIYLIRDPGDVRVMGNAQSKHAVVQEYIQKPLLVD
KLKFDIRLYVLVRSLDPLEIYIAKEGLSRFCTEPYQEPNQKNLDHVFMHL
TNYSLNVHSGNFVHSDNTNTGSKRTFSSILYRLASKGVDIKKVWSDIISL
VIKTVIALVPELKVYYQADIPAGKPGPTCFQILGFDILLMKNLKPILLEV
NANPSMRIEHEQEVSPGVFEYVPSPVDEEVKVGVIRDTLRLVDPGQRKLT
NHQSHTPGNGSELQEDILDTVSPDKAEQDSGVKVENNLPSLCLKQVFPKY
TKQFNYLRTVERIATLFMRFLGVKGTMRLGPTGFRTFIRNCKLSNSNFSM
ASVDILYIDITRRWNGMGSDQKESGMGLQAFVEAFFYLAQRRFKSPPLHE
QVAALLDLCDCHLESLDEKRSLCGRGAAERRTALPSCLPE-GVHSAPSAP
APHHFNCPTAANRLLLRSVPDLSCLEDDAQLILLLAG-------------
-------------VLSNHLRSAHCHPAQ-GEKLKKKKRKHL---------
------------
*
