>P1;ENSDARG00000074073

--------------MAWPCITRACCINRFWSELDKGDIAVPLVFTKYSDV
AEV-QHLHPQPKPVL-SQ-----------------------KPVATESHL
AHS-AHQEASSRATHGAADAAAA-ASQ-DGSGASVMREDFKA-WSVRPER
SCKPRNQYQPSKTPFINETQYQKDYKPWPIPKKGDHPWIPKPTAAAAPCK
AESK---FSKH----EQ--A-AAEMETGVEKCEIEEKQHEKESKERRK--
-------------------------KVEKKEPV-------SEAS------
-------------------------------KME----------------
--------------------------------------------------
------------KD-VAV-EGKRRS---AAD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQIKQEVT--SG--SS---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------YRTEFKAYRDIKPVKPIKAKSQ--------
-----------------YKLLVGEK------------------TNLETSY
SATFKGEQAKPQTTDNKLMEHRRIRSLYS-------------EPSKESS-
KVERHNLSLTKPKKTPS----HSKTVKKAKEKPVAGSQPAKKKTSVSNQE
-PKPEGGVTKK-SKEMINRLAEAKD-------------------------
--------------------------------------------------
-----
*
>P1;ENSTNIG00000008576

DHKQQQTLGMVAMAMAWPCISRACCMARFWNQLDKADIAVPLVFT-YADA
SEM-QHVQPQPS----SQ-----------------------ARVAIETQP
SRA--ESRTR-TVA---RAPRRC-VSE-ERVCSSVMREDFKR-WNVRPEP
SCKPKNEYHEPEAPFYSETQYQKDFKPWPIPKRYDHPWIQKAPRLDN--R
GPDR---PRQP----KRAAA-PTAADGDVEKSAIADKVQEKDLLQGHE--
-----------R--------------KK-GSRREAE-------A------
-------------------------------RR-----------------
--------------------------------------------------
-------------A-VEG-EGRGRR---STD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQIKEEIT--GG--SSY--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------RAEYKAYADVKPTRMIRAKSQ--------
-----------------YLP-PEEK------------------TRLETSY
SATFRA-QAPAQPADNKALDRRRVRSLYA-------------DPSKQVD-
RYSL---PRSKAKQPGAAASGQGTPLKKAKDKQGGAHRGSRKMAAEK---
--QPV-GNKEK-SKEMNNKLAEAK--------------------------
--------------------------------------------------
----E
*
>P1;ENSTNIG00000003291

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
Q----HLPHHPQPKQSAA-----------------------GAIAIETQP
HPQRAEQEA---------------GTE-DGLTASVMRQDFKA-WRVRPEP
SCKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPKPSPGSAS-R
GPER---SAKL----EH--A-AGEAESGVEKSEIEEKIHEKETKEVTR--
-------------------------REK-SAER-------DAGE------
-------------------------------KTE----------------
--------------------------------------------------
------------PA-CAE-ARKGRA---AAD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQLKEVMS--TS--SSYRYFCQLPSAGETDRWDWCY-------------
------------------------------------------I-------
--------------------------------------------------
-----------------PAASTATLHNTSSQVRPVTVPE-----------
--RTTEHIRAPCVHRAAAATQLNQQPSETIIHTSPN--------------
-------------------FRRTEFKAYKDVKPTKPIKAPSQ--------
-----------------YKP-PGEE------------------TNLETSY
SATFKGEQVKAHPADNKAMERRRIRSLYS-------------EPSKASP-
KVDKP-ASHAKSRKTSSTATTAGKMAKKTKEKQISSSQSAKKKPPLVTAE
-PRPEGVITKK-SKEISNRLAEAKQ-------------------------
--------------------------------------------------
-----
*
>P1;ENSORLG00000012570

--------------MAWPCISRACCMARFWNQLDHADIAVPLVFTKYTDA
SEM-QHIQLQPQ-LPRPQ-----------------------ARVAIETQP
SRS--KPRTA---------------PG-KACPAVLVRKHLKG-N----CP
KCRRK-DFFPVDCALSRKPAVQKGFAACRDEEDADPP-------------
--------------------------SRGSKLLKKKRIPEKDGWAIYQ--
-----------NSLKRINLSYTTTTHLK-SSRRASS-------S------
--------------------------------------------------
--------------------------------------------------
-------------Q-SRG-DGRGRGVKPGVD-------------------
--------------------------------------------------
------------------------------------------------RI
HSQPTTNCV--SS--STY--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------KDETEFKAYRDVRPVRMIRAKSQ--------
-----------------YLP-PDER------------------PSLETSY
SATFKV-QTPLQPADNKAQERRRIRSLYS-------------EPYIDPSK
QVDRYSPTCSKPKKSGATSAGQGKPLKKAKDKQTTPLKGSKKATLENQPQ
-DRPAVGDKEK-SKEINNKLAEAK--------------------------
--------------------------------------------------
----E
*
>P1;ENSAMXG00000008868

--------------MAWPCIARACCMARFWTQLDKADIAVPLVFVKYSEV
SEETQQLQRDRE-REKDRDRERNRERDREKDRHRDRTRDRLQEKSQERDP
ERN--RQEV------------TR-DGR-ENAPGSVMRQDFKA-WKVRPEP
SCKPKCEYHGPEVPFDSQTQYRQDYKPWPIPRRGDHPWIPKPA-------
------------------------LECGLEKSQTADKVQEKEMLMGEK--
-----------K--------------KR-QVKRVEKEKKVITGK------
-------------------------------EGS----------------
--------------A-----------------------------------
------------EA-PVN-VGKGRE---AVD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQIKQEVG--GG--SSY--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------RTEFKAYTDVKPVKLIRAKSQ--------
-----------------YHP-PDEK------------------TNLETSY
SATFRGEQAKLQPADNKALERRRIRTLYS-------------EPYLDSS-
KGERSSLPRSKPKKTTSSSTSQGKTVKKSKEKQTASVRGSKKKSSENQPE
-RRAAQGDKEK-SKEMNNKLAEAKE-------------------------
--------------------------------------------------
-----
*
>P1;ENSDARG00000074521

--------------MAWPCISRACCMARFWSQLDKADIAVPLVFTKYSDV
SEM-QHLHLQQP-VQK---------------------------IAIETQP
LHH--DHEPV---T---RAP-HA-GHD-EHSFGSVMRQDFKH-WKVRPEP
SCKPKNEYHGPEIPFNTETQYQKDYKPWPIPKKGDHPWIPKPSPSIS--A
GKH------------S--SP-EMMMDSGVEKSEIADKVPEKEILSSER--
-----------K--------------KR-QVKKVAVVSENNAGV------
-------------------------------KLD----------------
--------------R-----------------------------------
------------DA-SAV-EGKGRA---AVD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQIKREVS--SG--SSY--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------RTEFKAYTDVKPVKLIRAKSQ--------
-----------------YKP-PDDK------------------TDLETSY
SATYRAYQSSQQPDDNKALERRRIRTLYH-------------EPYRESS-
KVEKTSLPRSKPKKSSSTSATPGKPLKKSKEKQATSVRGSKKKSSENQPE
-SRAVQADKEK-SKEINNKLAEAKEVMLKQYHYIQLCQPIRDIGWVQTLK
QHLWRCALPDPRECESGVGRVSDYYSAGTSGGEPLVERPEPRSRGVVRFA
PDVKY
*
>P1;ENSGACG00000010429

--------------MAWPCLTRACCINRYWTELDKADVAVPLVFGKYSDA
ADA-QHLPHHPQPRHKRA-----------------------GAIAIETQP
HRA--EQGPG-KAP---PATAAA-AGK-DGSAASVMRQDFKA-WSVRPEP
SCKPRNEYQRSAAPFNTETQYQKDYKPWPIPKKRDHPWIPPQRRERK---
AGSR-----GR----ER--R-GEERDRGENAGERVNRGGEDEREEGKV--
-------------------------RRE-GNGR-------EDGQ------
-------------------------------SGA----------------
--------------RG----CE----------------------------
------------RR-AEERQGGRRR---AEQADQAAIGEFIPPQPIAIKK
PLLRPFQNEFADIFSRLSTQSSIRVSISTQYFKWFFNKITPKSSVIKHLE
NILSKINGARTGMTNRPCVPVITAVRMCFVSRKQNTRSEGQDEATWQLSL
NYRITYVLIKTLF--SP---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------CRTEFKAYKDVKLVKAIKAPDQ--------
-----------------YKP-PVKE------------------ASLETSY
SATYKGEQMKAQPTDNKLVERRRIRSLYS-------------EPGKEAA-
KVDKP-VSRTKQKKTPT--TTTGKMVKKSKEKQIASSQSAKKKPSSCAPK
-PKPDGAVTKK-SKEISNRLAESKQ-------------------------
--------------------------------------------------
-----
*
>P1;ENSONIG00000011169

--------------MAWPCITRACCINRFWSELDKADIAVPLVFARYSDV
ADV-PHVPHHPQPKLKKA-----------------------GAIAIETQP
HPG--EQEAG-KAP---PATGAA-AGK-DGSTASVMRQDFKA-WRVRPEA
SCKPRNEYQPSPAPFNNETQYQKDYKPWPIPKKHDHPWIPKSSPTAG---
GPERSAGSGKL----EQ--V-AAEAESGVEKSEIEEKTQEKESQEVVK--
-----------R----------SVKREK-SSER-------KTGE------
-------------------------------KTE----------------
--------------GQ----VA----------------------------
----------A-DV-SAE-QRKGRA---AAD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQIKEVMS--TS--SS---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------YRTEFKAYKDVKPVKPIKAPSQ--------
-----------------YKP-PGEE------------------TSLETSY
SATFKGEQVKAHPMDNKLLERRRIRSLYS-------------EPSKEPA-
KVDKP-VSRTKPKKSSSTPTTTGRMQKKAKEKQISSSQSAKKKPSLGASE
-PKPGGAVTKK-SKEISNRLAEAGK-------------------------
--------------------------------------------------
-----
*
>P1;ENSTRUG00000007180

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHFPHHPQPKQNRA-----------------------GAIAIETQP
HPHRGEPEAG-KAP---PATGAA-AGD-DG--LSVMRHDFKA-WRVRPEP
SCKPRREYQRSAAPFNTETQYQKDYKPWPIPKKNDHPWIPKASPGSTS-K
GPER---SAKL----EQ--A-ASEAESGVEKSEIEEKIHEKESKEVTK--
-------------------------REK-SAER-------EVGE------
-------------------------------KTE----------------
--------------------------------------------------
------------PA-CAE-TRKGRA---AAD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQLKEVMS--TS--SSYRF------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------TK--------------
-------------------KYRTEFKAYKDVKPTKPIKAPSQ--------
-----------------YKP-PGEE------------------TNLETSY
SATYKGEQVKAHPADNKVMERRRIRSLYS-------------EPSKAGA-
KVDKP-ASHTKPKKTPT---TAGKMGKKSKEKQISGSQSAKKKPSLVSAE
-PKPEGVITKK-SKEISNRLAEAKH-------------------------
--------------------------------------------------
-----
*
>P1;ENSXMAG00000001705

--------------MAWPCITRACCINRFWTELDKADIAVPLVFTKYSDV
ADV-QHLPHHPQPRQKQA-----------------------AAIAIETQP
HPE--EREAA-KAP---PAAGGAAAAKGGASAASVMRQDFKA-WRVRPEP
SCKPRNEYQPPPAPFSNETQYQKDYKPWPIPRKHDHPWIPKPSPTAG---
SK----LEHAA----AA--A-AGESESGVEKSEIEEKIQEKESKEAAR--
-------------------------REK-SAER-------KAAE------
-------------------------------KTE----------------
--------------GP----------------------------------
----------A-EV-SAE-QRRGRA---AAD-------------------
--------------------------------------------------
------------------------------------------------AL
NRQIKEVMS--TS--SS---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------YRTEFKAYKDVKPVKPIKAPSQ--------
-----------------YKP-PGEE------------------TSLETSY
SATYKGEQVKAQPTDNKLLERRRIRSLYS-------------EPGKEPA-
KVDKP-TSRTKPKKAPT--TTTGKMVKKSKEKQIAGSQLAKKKPSAKTPE
-AMPEGTVTKK-SKEISNRLAEAKH-------------------------
--------------------------------------------------
-----
*
>P1;ENSTRUG00000017372

R-PLERSLVFGALAMAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQPS----AQ-----------------------ARVAIETQP
PRA--QSRTR-TAA---HAPRRC-VSE-ERVCNSVMREDFKR-WNVRPEP
SCKPKNEYHEPETPFYSETQYQKDFKPWPIPKRCDHPWIQKAPRVDN--R
VPDR---PR------Q--QA---AADGEAEKSAVADRVQEKDLLQGHG--
-----------R--------------SK-ASRKEAE-------L------
-------------------------------KKV----------------
--------------V-----------------------------------
------------LR-VEG-EGRGRR---STD-------------------
--------------------------------------------------
------------------------------------------------AV
NRQIKE-IA--GS--SSY--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------RAEYKAYADVKPTRMIRAKSQ--------
-----------------YLP-PDEK------------------TRLETSY
SATFKA-QAPAPPADNKALDRRRVRSLYT-------------DPSKQPP-
QMDRYSLPRSKPRQSGAAASGQGTPVKRAKDKQGVAQRGSRKMAVEK---
--QPV-GSKEK-SKEINNKLAEAK--------------------------
--------------------------------------------------
----E
*
>P1;ENSORLG00000005434

--------------MAWPCITRACCINRFWTELDKGDIAVPLVFTKYSDA
AEV-HHLPHHPQPKQRVV-----------------------GTIAIETQP
HPE--EQEAA-RAP---PATGAA-AGR-TGTATSVMRQDFKA-WGVRPEP
SCKPRNEYQPPPSPFNNETQYQKDYKPWPIPKKHDHPWIPKPSSTAA---
-PER---SSKK----EH--A-AAEADSGGEESGWQTGAAG--VCKGER--
-------RAAEE----------QGSRRR-SQQT-------DQGGHVHFQL
LQVNIITPLGPAGRTDHQPSPHHLQPIEETHSMEPWIKNSMDTSEDHKSL
KKKCSAHCLVGLDDPTPNVKVPRIAQGLNHFLASLYLRRDTIRLGYLSVR
DPKPKRIQSRRRYYDAKQ-GGKGSL---SYF-------------------
--------------------------------------------------
------------------------------------------------AE
TMQQEEAAA--SGVQFT---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------CRTEFKAYKDVKPVKAIKATSQ--------
-----------------YKP-PMEE------------------TSLETSY
SATYKGEQVKPKESDNKLLERRRIRSLYS-------------EPGKEAA-
KVDKP-ESRLKPKKAP---TTTGKMLKKAKERQIASSQSTKKKPSAGPSE
---PEGTVTKK-SKEISNRLAEAKQ-------------------------
--------------------------------------------------
-----
*
>P1;ENSGACG00000020200

--------------MAWPCISRACCMARFWNQLDKADIAVPLVFTKYTDV
SEM-QHIQLQPP-LHPPR-----------------------GRVAIETQP
TRA--E----------------C-VSE-ERVCGSVMREDFKH-WNVRPET
SCKPKYEYHEPETPFNCESQYQKDFKPWPIPKRYDHPWIPKPPASDE--R
APDR---SRH-----R--KQ-PAEADSGVEKSAIADKVQEKDLVQGPH--
-----------R--------------KK-KSSKQEG-------P------
-------------------------------KKV----------------
--------------S-----------------------------------
------------LK-VEG-EGKGRA---AAD-------------------
--------------------------------------------------
------------------------------------------------AV
NRQIKQEIA--GD--SLYNNQSYVNLGGNV---SWCAQESPCFRDKRFQP
AASQSPAPSGLYLAANQLHYEMEAGKAGSVRSDSGYVKYCNPIQPAVLTK
LSGHWKSSLLRLQKVGVTQKKGPSHTAMYRCSSQLLAVSIEPLPEKLQRG
RELETRPTGPTGKREYRPGARPSPAHTPRNTARTGSLPPAQIDSFKDHER
GGLASETIDAPSYMHASACSCIHTQPCKHLTSTTHNSGVSEGWGTYINRK
LGSLLGLALHKEVELTMSYTNRTEYKAYRDVKPAKMIRARSQ--------
-----------------YLP-PDEK------------------TSLETSY
SATYKG-QAPLRPAGNKALDRRRIRSLYS-------------EPYIDPIK
QVDRYSALRTKPKKPGASAAGQVKQAKKAKDKQSAGLRGSKKTASENQLE
-NRPAVGDKEK-SKEMNNKLAEAK--------------------------
--------------------------------------------------
----E
*
>P1;ENSLOCG00000009984

------------------------HVSSFFI-------TVKEFLA-----
--------------------------------------------------
----------------------------------KAKEDFLRKWE-NPAQ
NTASLDQFERIKTL------------------------------GTGS-F
GRVM---LVKHKETGQHYAMKILDKQKVVKLKQIEHTLNEKRILQAVSFP
FLVRLEYSF----------------KDN-SNLY-------MVME------
-------------------------------YVPG---------------
---------------G----E-----------------------------
------------MF-SHL-RRIGRF---SEP-------------------
--------------------------------------------------
------------------------------------------------HA
RFYAAQIVL--TF--EY---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------LHSLDLIYRDLKPENLLIDQQGYIQVTDFG
FAKRVKGRTWTLCGTPEYLA-PEIILSKGYNKAVDWWALGVLIYEMAAGY
PPFF-A-DQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFG-
NLKNA-VSDIKNHKWFATTDWIAIYQRKVEAPFIPKCKGPGDTSNFDDYE
EEEIRVSFTEKCAKEFSEF-------------------------------
--------------------------------------------------
-----
*
