>P1;ENSDARG00000089626

----------M-----------HPAA--------------------AKWY
DRR-----------------------DFVFIEFL-----VE---------
--------DSKD-------------------------VKVNFDKSKFG--
-------------------------------FSCLSGADNVKYSN---E-
--------------------------------------------------
--------IDLFGSIDQDGSKHK-----------------------RTDR
SILCCLQKAETGKSWPRLTKDKAKLNWLSVDFNNWKDWEDDSDEEISNYD
RFSEMMGNMGGEDDLPDLDGADD--ESADSDDEKMPDL-E
*
>P1;ENSDARG00000037284

----------M-----------QPAT--------------------AKWY
DRR-----------------------EAVFIEFC-----IE---------
--------DSKD-------------------------VQVKFDKTKLD--
-------------------------------FSCVGGTDNMKHHN---E-
--------------------------------------------------
--------VDLLEAIDPNDSKHK-----------------------RTDR
SVFCCLKKAEPGKSWPRLTKEKAKLNWLSVDFNNWKDWEDDSDEELSSFD
RFSEMMNNMGGEDDLPDVDGADEE-ESPDSDDEKMPDL-E
*
>P1;ENSGACG00000008508

----------M-----------QPAT--------------------AKWY
DRR-----------------------DAVFVDFC-----VE---------
--------DSKN-------------------------VKVNFENSKFD--
-------------------------------FGCVGGTDNIKQQN---T-
--------------------------------------------------
--------VDLFGEINPKDSKYR-----------------------RTDR
SVLVCLRKVEPGKAWPRLTKDKTKCNWLSVDFNNWKDWEDDSDEDLSSFD
KFSEMMNTMGR-DDVPDFDGAGEEHDFENSDDEQMPAL-E
*
>P1;ENSGACG00000015239

----------M-----------HPAT--------------------AKWY
DRR-----------------------DSVFIEFC-----VA---------
--------DSKD-------------------------VKINFDKAKFG--
-------------------------------FSCFGGTDNVKHEN---E-
--------------------------------------------------
--------MDLFEAIDVNESKHN-----------------------RTDR
SVLVYLRKAQPGKPWPRLTKEKAKLSWLSVDFNNWKDWEDDSDEEMGNFD
QFSNIMNNMGGEDDLADLDGPEE--ESADSDDEKMPDL-E
*
>P1;ENSONIG00000011940

LFLMH-----R-----------QPAA--------------------AKWY
DRR-----------------------DSVFIEFC-----VE---------
--------DSKD-------------------------VQVNFDKSKFS--
-------------------------------FSCVSGTDDIKHQN---A-
--------------------------------------------------
--------VELFGEIDPKESKHR-----------------------RTDR
SVLCCLRKAEPGKSWPRLTKDKAKCNWLSVDFNNWKDWEDDSDEDLSSFD
KFSEMMNSMGG-DDLPDLDGADDEHESADSDDEKMPDL-E
*
>P1;ENSORLG00000012236

----------R-----------HPAT--------------------AKWY
DKR-----------------------DSVIIEFC-----IA---------
--------DSKD-------------------------VKVNFDKTKFA--
-------------------------------FSCLGGADNEKHEN---E-
--------------------------------------------------
--------VELFEAIDENESKHK-----------------------RTDR
SVLCYLRKAQPGKAWPRLTKDKTKLSWLSVDFNNWKDWEDDSEEEMGNFD
QFSDMMNNMGGEEDLPDLDGADDD-DSADSDDEKMPDL-E
*
>P1;ENSAMXG00000004536

PHFKHVLQNFR-----------QSAT--------------------AKWY
DRR-----------------------DSVFIEFC-----VE---------
--------DSRD-------------------------VEVKFDKSKLD--
-------------------------------FSCVGGVDTVKYHN---E-
--------------------------------------------------
--------VDLFEAIDPNESKHK-----------------------RTDR
SVYCCLKKAESGKSWPRLTKDKAKLNWLSVDFNNWKDWEDDSDEELSSYD
RFSEMMNNMGGEDDLPDMDGADDE-ESADSDDEKMPDL-E
*
>P1;ENSTRUG00000015676

----------A-----------QHAA--------------------ARWY
DRR-----------------------EAVFVEFC-----VE---------
--------DSQD-------------------------VKVNFDSSKFE--
-------------------------------FSCVTGAADKKHHN---T-
--------------------------------------------------
--------VDLFSEINPKESKHK-----------------------RTDR
SVLCCLRKAQPGISWPRLTKLKEKVSWLSVDFNNWRNWEDDSDDDLSSFD
KFSEMINKMGG-DDLPDLEGVDDE-YEPDSHCRRLSSR-N
*
>P1;ENSAMXG00000002019

----------M-----------HPAT--------------------AKWY
DRR-----------------------DYVFIEFC-----VE---------
--------DSKD-------------------------VTVNFETAKFG--
-------------------------------FSCLGGTDNVKHLN---E-
--------------------------------------------------
--------IDLFGAIDQNESKHR-----------------------RTDR
SVLCCLRKAESGKAWPRLTKEKAKLNWLSVDFNNWKDWEDDSDEELSNFD
RFSEMMNSMGGDDELPDLDGAEDG-ESADSDDEKMPDL-E
*
>P1;ENSTNIG00000012596

----------M-----------QPAT--------------------AKWY
DTR-----------------------DIVCIEFC-----VA---------
--------DSKD-------------------------VKVNFAKRKFG--
-------------------------------FSCVRGTDNIKHEH---E-
--------------------------------------------------
--------IDLFEEIDENESKHK-----------------------RTDR
SVLCYLRKAQPGKKWPRLTQDKVKLAWLGTDFNNWKDWEDDSDEEMGKFD
QLSDMMNSMGGGDDLPDLDGDD---DSADSDDENLPGLED
*
>P1;ENSTNIG00000015101

----------MEI--------AQHAA--------------------ARWY
DRT-----------------------EAVFVEFC-----VE---------
--------DSQN-------------------------VQVNFDTSKLD--
-------------------------------FSCVSRTADKKLQN---T-
--------------------------------------------------
--------VDLFSEINPKESKHK-----------------------RTDR
SVLCCLRKAQPGISWPRLTKLKEKVSWLSVDFINWRNWEEDSDDDLSSFD
RFSEMINKMGG-EDLPDLEGGDDE--SLSSFHSVLVFL-E
*
>P1;ENSTRUG00000002456

----------R-----------QPAT--------------------AKWY
DTR-----------------------DFVCIEFC-----VA---------
--------DSKD-------------------------LKVNFGKKKCG--
-------------------------------FSCVRGTDNVKHEN---E-
--------------------------------------------------
--------IDLFDEIDENESKHK-----------------------RTDR
SVLCYLRKAQPGKAWPRLTEDKVKLTWLGTDFNNWKDWEDDSDEEMGKFD
QLSDMMNSMGGGDDLPDLDGDD---DSADSDDENLPGL-E
*
>P1;ENSXMAG00000010616

----------MAHLPQHGPFPTLCAI--------------------AKWY
DRR-----------------------DFVFVEFC-----VE---------
--------DSKD-------------------------VHVQFDKSKFE--
-------------------------------FSCVSRRD--KYYN---D-
--------------------------------------------------
--------IELFGEIDPKQSKHS-----------------------RTDR
SVQCCLQKAEVGKPWPRLTKEKAKFKWLSVDFNNWRDWDDDSDEDMSSFD
NFSEMMNNMGG-DDLPDFDGAEEH-DSADGDDEKMPDL-E
*
>P1;ENSLOCG00000008482

----------M-----------PMYQVKPISGGDIQIDLPTCMYTLANIH
DQRSGCAQAHQDGEADPAVRALEARQDEILRRLLELKAAVEGLSKAIATP
DADVDVTSVSRDVGHAPGAGAAGLDSLLGKDNGALRDIVVNANPTRPPLA
LLVLHSLLRQRYRVLSTAHVHSSVPSVPPGLLACLGPRDPVSCSRHDFQL
GFTLIWKDGLVPKPQMKFSIQNMCHIEGEGNIARFLYRLLGCGPQDAVMA
TVVDSWVDTAFFQLV-EGSSKEKAAALRALNGALGRSPWLAGSELSLADI
VCFCAVLQSASTSSV----------------PTNVQKWIK-SCENSGYFT
CVSQLMR---------------------------------
*
