>P1;ENSTNIG00000013477

MLSHAD-------------------------------------------L
LDARLG------------------------------------MKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGSG------------------------------GP
DPGHS-GELGP------------VS-DG---------------VEGATML
PGEDISGGGGG-----------SNAV-QVSNK-N----------------
---------------PNQSGAQ--QT---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTHHGLPQFP-----
---MGDSLCSFHANDTRWATAGMPGVS-----------------------
---------QLQLPPALGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LG-GPPPNSMALSN-MSSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---SGSPQLCSSPDSDAWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSXMAG00000018825

MLSHAD-------------------------------------------L
LDARLG------------------------------------MKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------GP
DPGHS-GELGP---------------DG---------------VEGATML
PGDDISGGGGGGG------GGGSNPV-QVNSK-EQEKQQ-----------
-QQQQQNNNNSSGNNPNQSGGQ--QS---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTHHGLPQFPSAAAA
AAAMGDSLCSFHANDTRWATAGMPGVS-----------------------
---------QLQLPPALGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGPPPNSMGLSN-MSSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---AGSPQLCSSPDSDVWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSORLG00000003238

MLSHAD-------------------------------------------L
LDARLG------------------------------------MKDA-AEL
LGHRDALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------VA
DQGHP-GDMAP------------GS-DS---------------VEGTTLL
PGEDITTVGSN-----------STGM-SVNGK-EQEKQQ-----------
-QP-------------QQNTSQTASQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTP-GLPQFSA----
AAAMENSLCSFHANDSRWAT-GMPGVS-----------------------
---------QLQLPPALGRQPSMAQSLSQ--------------------C
S-------------------------------------------------
------------LGPGPPPNSMGLSNGLSSNGSGLQSHLYQSPFPGM-SA
SLSGPTNV---SGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSXMAG00000016614

MLSHAD-------------------------------------------L
LDARLGELSS---------------L-------NS-GPKLQWMKDA-AEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------VP
DQGHP-GDMAP------------GS-DS---------------VEGTTLL
PGEDITTVGSN-----------SAGM-PVNGKQEQEKQQ-----------
-QQQQ---------QPQQSSGQSASQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTP-GLPQFSA----
AAAMENSLCSFHANDSRWAT-GMPGVS-----------------------
---------QLQLPPALGRQPGMAQSLSQ--------------------C
S-------------------------------------------------
------------LGPGPPPNSMGLSNGLSSNGSGLQSHLYQSPFPGM-SA
SLSGPTNV---SGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSAMXG00000005573

MLSHAD-------------------------------------------L
LDARLG------------------------------------MKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LAGGGGGGGGG---------------------GAGA
DPVHP-GELPP------------GS-DT---------------VEGATLL
PGDDISSAA--------------AGV-PVNGK-DQDKHQHHQQQQHQQQH
QQQQQQN-----QQNQQQNPAQ--QT---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTHHGLPQFPS----
--AMGDGLCSFHANDTRWAAAGMPGVS-----------------------
---------QLQLPPALGRQQAMAQSLSP--------------------C
S-------------------------------------------------
------------LSAGPPPTSMGLSN-MSSNGSSLQSHLYQPAFPGMVPA
SLSGPTSAAAAGGSPQLCSSPDSDVWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSDARG00000014201

MLSHAD-------------------------------------------L
LDARLGELST---------------P-------NS-GLQLYWMKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------GT
DPVHP-GDLAP------------VS-DA---------------VEGATLL
PGDDINSAGSN-----------PPGV-AVNSK-DQEKQQ-----------
-QQQQ---------NPTQSSSQ--QS---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTHHGLPQFPSAAAA
AAAMGDSLCSFHANDTRWAAAGMPGVS-----------------------
---------QLQLPPALGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGPPPNSMSLSN-MSSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---TGSPQLCSSPDTDVWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSDARG00000058379

MLSHAD-------------------------------------------L
LDTRLGELSP---------------P-------NS-GLQLHWMKDAAAEL
LVHREALKCR----------------------------------------
--------------------------------------------------
--------------LGG--------------------------------T
DSGHP-GDLTS------------AT-ET---------------VEGTTLL
PGEEISNGGSN-----------PNGMQQVNAK-DQEKQQ-----------
-QQN-----------SNQTGGQQ-NQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTH-GLPQFPSA--A
AAAMGDSLCSFHANDTRWAAAGMPGVS-----------------------
---------QLQIPPSLGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGPPPNNMGLSGSLSSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---TGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSGACG00000015770

MLSHAD-------------------------------------------L
LDARLGELSS---------------P-------NS-GLQLYWMKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------GP
DPGHSGGELGP------------GP-DG---------------VEGATML
PGDDISN-----------------AV-QVNSK-EQEKQQ-----------
-QS---------------GGGQQSQS---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRSPGTLLPTHHGLSQFP-----
---MGDSLCSFHANDGRWATAGMPGVS-----------------------
---------QLQLPQALGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGQPHNSMGLSN-M-SNGSGLQSHLYQPTFPGMVSA
SLSGPTNM---THSPQLCSSPESEVWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSAMXG00000008190

MLSHAD-------------------------------------------L
LDARLGELSP---------------P-------NS-GLQLHWMKDAAAEL
LGHRDALKCR----------------------------------------
--------------------------------------------------
--------------LGA--------------------------------A
DGGHP-GDLSS------------GAVDA---------------VEGTTLL
PGEDISNGGSN-----------PNGLQQVGSK-EQDKQQ-----------
-QQQ----------SSAQGGGQ--QS---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTH-SLPQFPSAAAA
AAAMGDGLCSFHANDTRWAAAGMPGVS-----------------------
---------QLQLPPSLGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGPPPNSMGLSNSLQSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---SGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSTRUG00000013760

MLSHAD-------------------------------------------L
LDARLGELSS---------------L-------NS-GPKLQWMKDA-AEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------VP
DQGHP-GDMAP------------GS-DS---------------VEGTTLL
PGEEIATVGSN-----------SAGM-QVNGK-EQEKQQ-----------
-QQQ----------QPQQSSGQTSSQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRSPGTLLPTP-GLPQFSA----
AAAMENSLCSFHANDSRWAT-GMPGVS-----------------------
---------QLQLPPALGRQPGMPQSLSQ--------------------C
S-------------------------------------------------
------------LGPGPPPNSMGLSNGLGSNGSGLQSHLYQSHFPGM-SA
SLSGPTNV---PGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSGACG00000006004

MLSHAD-------------------------------------------L
LDARLGELSS---------------L-------NS-GPKLQWMKDA-AEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------VP
DQGHP-GDMVP------------GS-DS---------------VEGTTLL
PGDDITTVGSN-----------SGGM-TVNGK-S----------------
-------------------SSQSASQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRSPGTLLPTA-GLQQFSA----
AAAMENSLCSFHANDSRWAT-GMPGVS-----------------------
---------QLQLPPALSRQPGM-QSLSQ--------------------C
S-------------------------------------------------
------------LGPGPPPNSMGLSNGLSSNGSGLQSHLYQSHFPGM-SA
SLSGPTNV---SGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSTRUG00000018317

MLSHAD-------------------------------------------L
LDARLGELSS---------------P-------NS-GLQLYWMKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------GP
DPGHS-GELGP------------GS-DG---------------VEGATML
PGEDISSGGG------------SNAV-QVNNK-EQEKQQ-----------
-QQHQQQQ----NNNPNQSGAQ--QS---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTHHGLPQFPSAAAA
AAAMGDSLCSFHANDTRWATAGMPGVS-----------------------
---------QLQLPPALGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGPPPNSMGLSN-MSSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---TGSPQLCSSPDSDAWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSTNIG00000015382

MLSHAD-------------------------------------------L
LDARLG------------------------------------MKDA-AEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------VP
DQGHP-GDMAP------------GS-DS---------------VEGTTLL
PGEEIATVGSN-----------SAGM-QVNGK-EQEKQQ-----------
-QP------------PPQSSGQTSSQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------R-FAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTP-GLPQFSA----
AAAMENSLCSFHANDSRWAT-GMPGVS-----------------------
---------QLQLPPALGRQPGMPQSLSQ--------------------C
S-------------------------------------------------
------------LGPGPPPNSMGLSNGLSSNGSGLQSHLYQSHFPGM-SA
SLSGPTNV---SGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSONIG00000015466

MLSHAD-------------------------------------------L
LDARLGELTS---------------P-------NS-GLQLYWMKDAAAEL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------GP
DPGHS-GELGP------------GP-DG---------------VEGTTML
PGDDITSGG-G-----------SNPV-QVNSK-EQEKQQ-----------
-QQQQQNNNS--NNNPNQSGGQ--QP---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTHHGLPQFPSAAAA
AAAMGDSLCSFHANDTRWATAGMPGVS-----------------------
---------QLQLPPALGRQQAMAQSLSQ--------------------C
S-------------------------------------------------
------------LGAGPPPNSMGLSN-MSSNGSGLQSHLYQPTFPGMVPA
SLSGPTNV---TGSPQLCSSPDSDVWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSONIG00000014459

MLSHAD-------------------------------------------L
LDARLG------------------------------------MKDA-ADL
LGHREALKCR----------------------------------------
--------------------------------------------------
--------------LGGG------------------------------VP
DQGHP-GDMPP------------GS-DS---------------VEGTTLL
PGEDIATVGSN-----------SAGM-PVNGK-EQEKQQ-----------
-QQ------------PQQNSGQPTSQ---QKQKRHRTR----------FT
PAQLNELE------------------------------------------
--------------------------RSFAKTHYPDIFMREELALRIGLT
ESRVQVWFQNRRAKWKKRKKTTNV---FRAPGTLLPTP-GLPQFSA----
AAAMENSLCSFHANDSRWAT-GMPGVS-----------------------
---------QLQLPPALGRQPGMAQSLSQ--------------------C
S-------------------------------------------------
------------LGPGPPPNSMGLSNGLSSNGSGLQSHLYQTPFPGM-SA
SLSGPTNV---SGSPQLCSSPDSDMWRGTSIASLRRKALEHTVSMSFT
*
>P1;ENSLOCG00000010387

MEIGTEISKKIRAAIKGKLQELGAYVDEELPDYIMVMVANKKNAQQMADD
LSLFLGNNTIKFTIWLHGVLEKLRSVAVVRAEPSVLKPQLA-CTDASAEL
LAGKGRPPCGGSANRRDEEPRGLAVSSSRADRTDSWVSTSSSQEHQVSSG
RRSTERNVPRLMSTVKPLVEPLSEEAIIDIKPEPDDDLIDEDLRFAGDAA
SSAGLRKRPLVTLTYSSGRPT-AEPSRPPPGSQQSASMSDSSSQPAG-RA
DEGRP-CSYRPAEALGPTETSLGLY-SRLQDSSGQSIRSVFFRRRGHSMI
TEEDMSWKRKAPVVSSIVRVSKTAEE-DLDSD-EQEEEE-----------
-EEN----------YGARSGGLSSSVSLPSKPER-RPTLPPSKQANKNLI
LKAISEAQESVSKTTNYPTAAAPQRQMVPVAPRTRSASEDMGAAVQQVQE
SLRSAEFSLQTRAPMETVSERRPVQTRSLGSRLQPDTQEESLRRLQAGVS
EMSA-VKPNDTRSFILKRSQLEDVGSVRSRLGTLVPVE-FKEVSTS----
VAQTRDASEPRHCPSPKFIV-TLDGVPSPQGYMDEEDRDAEDTVLKENVK
IIKSKLSARQLDRKPKMNVHQRLERELDYSDDEGETDVVPIKRQKVLERC
KYWPVCKSGAECVYHHPTTLCKTFPSCKFGDKCLFVHPNCKYDAKCTKAD
CPYTHASRRGPALPVKPVPQSSGNICRFFPDCRKLDCQFYHPKPCR----
-------------FTTQCKRPDCNFYH-PSVSLPPRHALKWTKAQNRY
*
