>P1;ENSAMXG00000009211

MIGKL-----KQNLLVACL-------------------------VISSVT
---VFYLGRHAMEC------HQRFEEHGQP--------------------
-----------------LLGSLHATLRTG----HNLSS------------
-----PFVYNKDMPLIFIGGVPR----------SGTTLMRAMLDAHPEVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDSAMQAF--------------LLEIIVKHGEPATYLCNK----
-------------------------------------------------D
PFALKSLTYLAKIF-----------------------------PRAKFIL
MIRDGRASVHSMISR---------------KVTIAGFDLNSYRDCLTKWN
R----------------------------AIET----------------M
YTQ-CLE--AA-DKCLPVHYEQLVL-------------------------
--------------------------------------------------
-----------HPEKWMRTLLKFLNIPWNEAVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPV
DVLRDMPVIAPMLARLGYDPHANPPNY-----------------------
------------G--RPDPRVL--DNTR----------------------
--------------RVS-A-DLIHC-RH----------------------
--------------P-----------------------------------
-------------
*
>P1;ENSTRUG00000005781

MIGKL-----KQNLLVACL-------------------------VISSVT
---VFYLGRHAMEC------HHRIEGRSQLG-------------------
----------GVLPLSALGGSMRTALRTG----QNLSA------------
-----PFVYNKDMPLIFIGGVPR----------SGTTLMRAMLDAHPEVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDAAMQAF--------------LLEIIVKHGEPANFLCNK----
-------------------------------------------------D
PFALKSLSYLAKIF-----------------------------PRAKFVL
MIRDGRASVHSMISR---------------KVTIAGFDLGSYRDCLTKWN
R----------------------------AIET----------------M
YTQ-CLE--AA-DKCLPVHYEQLVL-------------------------
--------------------------------------------------
-----------HPEKWMRTLLKFLDIPWNDAVLRHEELIGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPA
DVVRDMAVIAPMLSRLGYDPHANPPNY-----------------------
------------G--RPDPKVL--DNTR----------------------
--------------RVF-K-GEFQL-PD---------------FLKEQSQ
---------EK-FNNTSPFLQ------------------FK---------
-------------
*
>P1;ENSORLG00000002471

SMRST-----RTNLLLACV-------------------------LLCSVS
---LLYLGMSGGGC------PPKSHRYRW---------------------
---------------------MELNLHSG-N--QNLSL------------
-----TEQIPEDTPIIFIGGFPR----------SGTTLMRVMLDAHNAVR
CGEETQVIPRLLTMRASWSKSAKERIRLDEAGVTDQV-------------
------LDSAVRAF--------------LLEVIIGHGEPAPRLCNK----
-------------------------------------------------D
PFSLKSLSYLARIF-----------------------------PKAKFVL
MLRDGRATVHSMISR---------------KVTISGFDLTSYRDCLTKWN
S----------------------------AVET----------------M
FSQ-CQA--AGEVRCMAIRYEQLVL-------------------------
--------------------------------------------------
-----------HQELEMRKLLNFLELQWDPSVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVMKPVNTEALSKWVG-------
----------------------------------------------HVPS
DVINDMAEIAPMLARLGYDPHANPPDY-----------------------
------------T--KAESTVYPFNTSQ----------------------
---------------VS-P-------------------------------
---------------RIPDN------------------------------
------------S
*
>P1;ENSXMAG00000007886

MRG-------RTNMLLGCV-------------------------LLCSAF
---LLYLGMNTIDC------PRKSHRYHW---------------------
---------------------MELNMASG-N--Q--SL------------
-----P-HFPEDTPLIFIGGFPR----------SGTTLMRVMLDAHSAVR
CGEETRVIPRLLAMRATWSRSVRERIRLDEAGVTDQV-------------
------LDAAVRAF--------------LLEVIVGHGEPAARLCNK----
-------------------------------------------------D
PFALKSLSYLARIF-----------------------------PKAKFVL
MLRDGRATVHSMISR---------------KVTISGFDLSSYRDCLTKWS
S----------------------------AVEA----------------M
FSQ-CQA--VGETRCLPVRYEQLVL-------------------------
--------------------------------------------------
-----------HPEQQMRDLLHFLELKWDSSVLHHEELIGKAGGVSLSR-
---------------------VERSTDQVVKPVNTEALSKWVG-------
----------------------------------------------NIPS
NVIDDMAEIAPMLARLGYNPHANPPDY-----------------------
------------T--KADPITSPFNHLQ----------------------
---------------RE-KTA-----------------------------
--------------ADSPHP------------------------------
------------S
*
>P1;ENSTNIG00000014384

MIGKL-----KQNLLVACL-------------------------VISSLT
---VFYLGRHAMEC------HHRMEERRPPG-------------------
----------GVLPLS----ALRSTLRTG----QNLSA------------
-----PFVYSKDMPLVFIGGVPR----------SGTTLMRAMLDAHPEVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDAAMQAF--------------LLEIIVKHGEPANFLCNK----
-------------------------------------------------D
PFALKSLSYLAKIF-----------------------------PRAKFVL
MIRDGRASVHSMISR---------------KVTIAGFDLGSYRDCLTKWN
R----------------------------AIET----------------M
YSQ-CLE--AA-DKCLPVRYEQLVL-------------------------
--------------------------------------------------
-----------HPEKWMRTLLKFLDIPWNDAVLHHEE-VGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPA
DVVRDMAVIAPMLFRLGYDPQANPPNY-----------------------
------------G--QPDPKVL--DNTR----------------------
--------------RVF-K-GEFQL-PD---------------FLKEQSQ
---------NE-LVS-----------------------------------
-------------
*
>P1;ENSONIG00000008675

TMRST-----RSNLLLGCV-------------------------LLCSIS
---LLYLGMSGVDC------PPKSHRRRW---------------------
---------------------MELTLGSG-N--QSLSL------------
-----ADHFPEDTPIIFIGGFPR----------SGTTLMRVMLDAHNAVR
CGEETRVIPRLLTMRATWSRSVKERIRLDEAGVTDHV-------------
------LDSAVRAF--------------LLEVIVGHGEPAPRLCNK----
-------------------------------------------------D
PFALKSLSYLAHIF-----------------------------PKGKFVL
MLRDGRATVHSMISR---------------KVTISGFDLTSYRDCLTKWS
S----------------------------AVET----------------M
FSQ-CQA--VGYARCQPIRYEQLVL-------------------------
--------------------------------------------------
-----------HPEEEMRKLLHFLDLQWDPSVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVMKPVNTEALSKWVG-------
----------------------------------------------QIPP
DVVNDMAEIAPMLARLGYDPHANPPDY-----------------------
------------T--KTEPLAPEFNYSH----------------------
---------------KA-K-S-----------------------------
--------------ADVPHP------------------------------
------------S
*
>P1;ENSAMXG00000006004

M-RKQ-----THSVLLACV-------------------------VISSIT
---IFYLSLSAMEC------PNSRSRG-----------------------
-------------------V-WGPNQHLSRNLSYPMPV------------
-----SVEYNEDSPLIFVGGVPR----------SGTTLMRAMLDAHPEVR
CGEETRVIPRLLAMQATWSRSARERLRLDEAGVTDEV-------------
------LDSAIRAF--------------LLEIIVGHGEPAPRLCNK----
-------------------------------------------------D
PFALKSLTYLSKLF-----------------------------PRAKFVL
MLRDGRATVHSMISR---------------KVTITGFDLTSYRDCLVKWN
R----------------------------AVEA----------------M
YDQ-CMA--VSERTCLPVLYEELVL-------------------------
--------------------------------------------------
-----------HPEQVMQKLLQFLELPWDLSVLHHEQLIGKVGGVSLSK-
---------------------VERSTDQVVNPVNTEALSKWVG-------
----------------------------------------------KIPD
DVVKDMADIAPMLKRLGYDPLANPPDY-----------------------
------------G--KPDSLPL--NNTK----------------------
---------------LL-Q-GAKTN-------------------------
--------------TDVFHPS-----------------------------
-------------
*
>P1;ENSORLG00000015045

MLGKL-----KQNLLVACL-------------------------VISSVT
---VFYLGRHAMEC------HHRFEERSLPG-------------------
----------GVLPLSALGGSMRTTLRTG----QNLST------------
-----PFVYNKDMPLIFIGGVPR----------SGTTLMRAMLDAHPDVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDAAMQAF--------------LLEIIVKHGEPASFLCNK----
-------------------------------------------------D
PFALKSLSYLAKIF-----------------------------PRAKFLL
MIRDGRASVHSMISR---------------KVTIAGFDLNSYRDCLTKWN
R----------------------------AIET----------------M
YTQ-CLD--AA-DKCLPVHYEQLVL-------------------------
--------------------------------------------------
-----------HPEKWMRTLLKFLDIPWNDAVLHHEDLIGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPP
DVVRDMAVIAPMLSRLGYDPHANPPNY-----------------------
------------G--QPDPKVL--DNTR----------------------
--------------RVF-K-GEFQL-PD---------------FLKEQSQ
---------TV-SRE-----------------------------------
-------------
*
>P1;ENSTNIG00000016138

M-RNP-----RLSLLLGCV-------------------------LLCSAS
---LLYLGMSGIEC------PPKSHRHRW---------------------
---------------------MELNLGSA-N--QNLSL------------
-----PEHFPEGAPLIFIGGFPR----------SGTTLMRVMLDAHKHVR
CGEETRVIPRLLTMRATWSRSVKERIRLDEAGVTDQV-------------
------LDAAVRAF--------------LLEVIVGHGEPAPRLCNK----
-------------------------------------------------D
PFALKSLSYLSHIF-----------------------------PKAKFVL
MLRDGRATVHSMISR---------------KVTISGFDLSSYRDCLTKWS
S----------------------------AVET----------------M
LDQ-CQA--AGRDRCLPVRYEHLVL-------------------------
--------------------------------------------------
-----------YTEEEMRKLLRFLELQWDPAVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVMKPVNRDALSKWVG-------
----------------------------------------------QIPA
DVLSEMAEIAPMLSRLGYDPQANPPDY-----------------------
------------T--RPETTPSPFNSSQ----------------------
---------------SL-K-------------------------------
-------------------P------------------------------
------------T
*
>P1;ENSONIG00000010509

MIGKL-----KQNLLVACL-------------------------VISSVT
---VFYLGRHAMEC------HHRIEEYSQPG-------------------
----------GILPLSGLGGSMRTTLRTG----QNLST------------
-----PFIYNKDMPLIFIGGVPR----------SGTTLMRAMLDAHPEVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDAAMQAF--------------LLEIIVKHGEPASFLCNK----
-------------------------------------------------D
PFALKSLSYLAKIF-----------------------------PRAKFVL
MIRDGRASVHSMISR---------------KVTIAGFDLGSYRDCLTKWN
R----------------------------AIET----------------M
YTQ-CLD--AA-DKCLPMHYEQLVL-------------------------
--------------------------------------------------
-----------HPEKWMRTLLKFLDIPWNNAVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPA
DVVRDMAVIAPMLSRLGYDPHANPPNY-----------------------
------------G--QPDPKVL--DNTR----------------------
--------------RVY-K-GEFQL-PD---------------FLKEQPQ
---------TQ-SVC-----------------------------------
-------------
*
>P1;ENSDARG00000044513

M-RKQ-----TCNVLLVCG-------------------------VISSIT
---VFYLGLSTIEC------PNARSRASQH--------------------
-------------------G-WVVNLHAGRNLSDPLQL------------
-----PEEYNEETPLIFVGGVPR----------SGTTLMRAMLDAHPIVR
CGEETRVIPRLLAMQATWSHSARERVRLDEAGVTDDV-------------
------LDSAVRAF--------------LLEIIVGHGEPAPRLCNK----
-------------------------------------------------D
PFALKSMSYLSKLF-----------------------------PKAKFIL
MLRDGRATVHSMISR---------------KVTITGFDLTSYRDCLVKWN
R----------------------------AVEV----------------M
YDQ-CLA--AVDGNCLPVHYEQLVL-------------------------
--------------------------------------------------
-----------HPERVMRRLLQFLDLPWDTAVLHHEQLIGKVGGVSLSK-
---------------------VELSTDQVVKPVNTEALSKWVG-------
----------------------------------------------KIPA
DVVKDMPSLAPMLSRLGYDPLANPPNY-----------------------
------------N--KPDLLYL--NNTK----------------------
---------------IHAK-SLLEL-------------------------
--------------RTCIDKT-------------------ESLFHTKTII
VSYKVSSSFNVVF
*
>P1;ENSDARG00000073872

MIGKL-----KQNLLVACL-------------------------VISSVT
---VFYLCRHAMDC------HHRIEERSQP--------------------
-----------------LLSSLHATLRTG----QNLST------------
-----PFIYNKDMPLIFIGGVPR----------SGTTLMRAMLDAHPDVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDSAMQAF--------------LLEIIVKHGEPANYLCNK----
-------------------------------------------------D
PFALKSLTYLAKIF-----------------------------PHAKFIL
MVRDGRASVHSMISR---------------KVTIAGFDLSSYRDCLTKWN
R----------------------------AIET----------------M
YTQ-CLE--AA-DKCLPVHYEQLVL-------------------------
--------------------------------------------------
-----------HPEKWMRTLLRFLNIPWNDAVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPL
DVQRDMAVIAPMLARLGYDPHANPPNY-----------------------
------------G--RPDPLVL--DNTR----------------------
--------------RVF-R-GEFQL-PD---------------FLKEQTQ
---------LQ-KSPEKPNPS-----------------------------
-------------
*
>P1;ENSGACG00000013486

MIGKL-----KQNLLVACL-------------------------VISSVT
---VFYLGRHAMEC------HQRIEEHGQLG-------------------
----------AILPLSALGGSMRTTLRTG----QNLSM------------
-----PFVYNKDMPLIFIGGVPR----------SGTTLMRAMLDAHPEVR
CGEETRVIPRILAMKQMWSRSGREKMRLDEAGVTDEV-------------
------LDAAMQAF--------------LLEIIVKHGEPANFLCNK----
-------------------------------------------------D
PFALKSLSYLAKIF-----------------------------PRAKFVL
MIRDGRASVHSMISR---------------KVTIAGFDLGSYRDCLTKWN
R----------------------------AIET----------------M
YTQ-CLE--AA-DKCLPMHYEELVL-------------------------
--------------------------------------------------
-----------HPEKWMKTLLKFLDVPWNDAVLRHEELIGKAGGVSLSK-
---------------------VERSTDQVIKPVNVEALSKWVG-------
----------------------------------------------KIPA
DVVRDMAVIAPMLSRLGYDPHANPPNY-----------------------
------------G--RPDPKVL--DNTR----------------------
--------------RVF-K-GEFQL-PD---------------FLKEQSQ
---------IQ-KSAERPKPS-----------------------------
-------------
*
>P1;ENSTRUG00000013179

M-RNN-----RLSLLLGCV-------------------------LLCSAS
---LLYLGMSGIEC------PPKSHRHRW---------------------
---------------------MELNLGLA-N--QNLSL------------
-----NEHFPEDTPLIFIGGFPR----------SGTTLMRVMLDAHRHVR
CGEETRVIPRLLTMRATWSRSVKERMRLDEAGVTDQV-------------
------LDSAVRAF--------------LLEVIVGHGEPAPRLCNK----
-------------------------------------------------D
PFALKSLSYLSHIF-----------------------------PKAKFVL
MLRDGRATVHSMISR---------------KVTISGFDLTSYRDCLTKWS
S----------------------------AVET----------------M
FSQ-CQA--AGEDRCLPIRYEHLVL-------------------------
--------------------------------------------------
-----------HTEEEMRKLLRFLELQWDPAVLHHEELIGKVGGVSLSK-
---------------------VERSTDQVMKPVNTEALSKWVG-------
----------------------------------------------QIPA
DVISEMDEIAPMLSRLGYDPQANPPDY-----------------------
------------T--KPEPMLSPFNSSQ----------------------
---------------IL-K-------------------------------
-------------------P------------------------------
------------T
*
>P1;ENSGACG00000020467

AMRNT-----RSSLLLGCM-------------------------LLCSAS
---LIYLGMSGTGC------PPKSHRYRW---------------------
---------------------MELNMGSA-N--QSSSL------------
-----NEHLPEDTPLIFIGGFPR----------SGTTLMRVMLDAHIAVR
CGEETRVIPRLLAMRATWSRSVKERIRLDEAGVTDQV-------------
------LDSAVRAF--------------LLEVIVGHGEPAPRLCNK----
-------------------------------------------------D
PFALKSLSYLSRIF-----------------------------PKAKFVL
MLRDGRATVHSMISR---------------KVTISGFDLTSYRDCLTKWS
S----------------------------AVET----------------M
FSQ-CQA--AGESTCLPVRYEQLVL-------------------------
--------------------------------------------------
-----------HTEEEMRKLLHFLELQWDPSVLHHEELIGKAGGVSLSK-
---------------------VERSTDQVMKPVNTDALSKWVG-------
----------------------------------------------HIPS
DVISDMAEIAPMLARLGYDPHANPPDY-----------------------
------------T--RPEPALSPFNYSQ----------------------
---------------NL-K-S-----------------------------
--------------ADTPHP------------------------------
------------S
*
>P1;ENSLOCG00000001436

MSQVTLLEEITQWSVEICQQELRSVLPKLLSIYHHTADWDEYIRVLKILT
QMFLPHLSLTELEGEFFSKVLPKVVK-MFNDLTEEISNQVGELSSQNIEL
RVLLRNILQIMVQVLEALSGCVRHICSFE----ENLASFDSIRSLPSCIL
KILKNTFQHCKESETAYQGRLSLVADLLQALFKEAYSLQKGFMELL----
-----------------------DRISLGNSATEEEVSDMVTVIHSLLDI
CSVISNLDLAMHANTWKFIVKQSVKYQVLLEDQLRHSDIVSSLCDDVLAS
FHSCMELAEQMKQSGVQESSQSAECKFFQKTAKICRFFANTLVHYIKEFQ
PFLSKSCGQFHRLYLQIYSKFPPSLSSPVISERHCNEISNVLVPMDPFIT
QLLPFRPFAEAVLAEEQQSCPELCLPQCLLLVNILGKLPSLPEDVLDLWC
QGSQFPEETPRLSVFQALFLSFQRCSLERAIPILLPGVMMNGQAQSKVTL
YQHVCIQLSACIASLPPAHFSQLEHSLLGALLSSDVQTALLATDVWCFLA
RFGTAELCQHHGMIIAHLIKSCPGDCYQLSHLALLLRRMIFLMTPNHQVQ
FISKFSPKEAENLTLWQHVLLKALSLDVRKQV--EEDIMKSATAVCASWM
EEGCKLGQLEKVNTALSAMLSVRQGSGQVLESEAEQSVSRLVTQLWPRIS
VKQVLTQPALQCTLRPLLCLSATAVQCIDHQVICQALTCLTSLLPLKCPD
DIVLAALDLLASLGRLFIPPEIQSQVLPKLSSLFSSLLAEGSWLLHQCTL
EAFAQFAEVTNHEHVIPESLAS--EETKNKVVKFLSKAVHLEENKEERLE
RLKSERCVIERHRHRLE-T-GAVEVTGDAEPCPKRPRQETCEEEQYEMVL
QTAENALKTLQSLTEQTPPPQWVAARLQSLQTQITHINQVKLKGT-----
-------------
*
