>P1;ENSGACG00000010527

------MAQRYDELAHYGG-MDG--V------------------------
-------------SASMYGDPHAPRPLPQVHHLNHGPPLHASQH------
--------------------------------YGAHA--------PHPNV
MPASMGSAVNDVLKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPD------------KDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LA-D----------------------TGLTILQVNTGKFINARRRIVQPM
IDQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGLPGMP
GEYVPQSGPMG-MSMAAPTYANPHQMTPHLSQLRRGPH-LHAYLPDHAHH
--PHHHPHHAMLMHGGPSSHPGMTMSAQRPPLLTPIDPSAGGQGLDIHAQ

*
>P1;ENSGACG00000005610

----TEMAQRYDELSHYGGALDG--VG-----------------------
------------VPTSMYGDPHAPRPLPQVHHLNHGP--HPTQH------
--------------------------------YGAHA--------PH--I
MPSSMGSAVNDALKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGA-AGGDVCSSD
SFNEDIAVFAKQIRAEKPLFSSNPELDNLMVQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIEERDV-CKSDFDDLSGSSTNLADHNPAS
WRDMDDTHSTPSVGTPGPSSGGHVSHSGDNTSELGDTLDNSLA-------
---------SPGTGDEDD--------------QDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRA-------VSQGSTYSPDGQPMGGFVIDGQQHMGLRPGGPM---
-------GGMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSDARG00000098240

------MAQRYDELAHYGG-MDG--V------------------------
---------------GMYGDPHAPRPLPQVHHLNHGPPLHASQH------
--------------------------------YGTHA--------PHPNV
MPTSMGSAVNDVLKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGLASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPD------------KDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRA-------VSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGPM---
-------SGMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSTNIG00000017241

------MAQRYDELAHYGG-MDG--V------------------------
-------------TASMYGDPHAPRPLPQVHHLNHGPPLHSSQH------
--------------------------------YGTHA--------PHPNV
MPTSMGSAVNDVLKRDKDAIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPE------------KDKRRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAAD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGPM---
-------SGMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSTRUG00000013943

------MAQRYDELAHYGG-MDG--V------------------------
-------------TASMYGDPHAPRPLPQVHHLNHGPPLHSSQH------
--------------------------------YGTHA--------PHPNV
MPTSMGSAVNDVLKRDKDAIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPE------------KDKRRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAAD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGLPGMP
GEYVPQTGPMG-MSMAPHTYTDPHQMAPHPSVLRHGPP-LHAYLPDHPHG
HHAHHHSHHTMLMHGGPSSHPGMAISAQRPPLLTPIDPSTGGQGLDIHAQ

*
>P1;ENSXMAG00000009557

------MAQRYDELAHYGG-MDG--V------------------------
-------------PASMYGDPHAPRPLPQVHHLNHGPPLHASQH------
--------------------------------YGAHA--------PHPNV
MPTSMGSAVNDVLKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPD------------KDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRA-------VSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGLPVMP
GEYVPQSSPMG-MSMGPPTYSNPHQMPSHPSQLRPGPPPRHAYLTDHPH-
------APHTMLMHGGPSLHPGMTMSAQRPPLLSPIDPSTGGYGLDIHA-

*
>P1;ENSONIG00000001639

------MAQRYDELTHYGGAMDG--V------------------------
-------------PSSMYGDPHAPRPLPQLHHLSHGAPPHPTQH------
--------------------------------YGAHA--------PH--N
---IMGSSVSDALKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQIRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIEERDV-CKSDFDDLSGSSTNLADHNPAS
WRDMDDSHSTPSVGTPGPSSGGHVSQSGDNTSELGDGLDNSLA-------
---------SPGTGDEDD--------------QDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRA-------VSQGTAYSPDGQPMGGFVLDGQQHMNLRPGGPM---
-------GSMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSORLG00000013127

------MAQRYDELAHYGG-MDG--V------------------------
-------------PTSMYGDPHAPRPLPQVHHLNHGPPLHASQH------
--------------------------------YGAHA--------PHPNV
MPTSMGSAVNDVLKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPD------------KDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGLPGMP
GEYVPQNSPIG-MTMAPHTYANPHQMTSHPAHLRHGPP-LRGYLPDHAH-
-----HSHHAMLMHGGPSSHPGMPMPAQRPPLLTPIDPSTGGQGMDIHAQ

*
>P1;ENSDARG00000077840

----MLMAQRYEDLAHYGGGMDG--VG-----------------------
------------VPTSMYGDPHAPRPLPQVHHLNHGPPPHANQH------
--------------------------------YGAHA--------PHS-I
MPSSMGSAVNDALKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQIRAEKPLFSSNPELDNLMIQSIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDG-CKSDFDDLSGSSTNLADHNPAS
WRDMDDAHSTPSVGTPGPSSGGHASQSGDNSSELGDGLDNSLA-------
---------SPGTGDEDD--------------QDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRA-------VSQGTAYSPDGQPMGGFVLDGQQHMGLRPGGPM---
-------GGMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSONIG00000001403

------MAQRYDELAHYGG-MDG--V------------------------
-------------PASMYGDPHAPRPLPQVHHLNHGPPLHASQH------
--------------------------------YGAHA--------PHPNV
MPTSMGSAVNDALKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPD------------KDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGLSGMP
GEYVPQSGPMG-MSMTPPTYTNPHQLTSHPSQLRHGPP-FHAYLPDHPHV
----HHTHHAMLMHGGPSSHPGMTMSAQRPPLLSPVDPSTGGQGLDIHAQ

*
>P1;ENSAMXG00000009455

----MLMAQRYEDLGQYGG-VDG--V------------------------
---------------GLYADPHGPRALG---HLHHAPP---QGH------
--------------------------------YGTHT--------PHS-I
MGTGMGTGINDSLKRDKDHIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------DPGAGAGGDVCSSH
SFNEDIAVFAKQIRAEKPLFTSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDDRDG-CKSDFEELSGS-TNLTD-NPAS
WRDLDDAHSTPSVGTPGPSSGGLASQSGDNSSELGDGLENNLA-------
---------SPGT-DEDD--------------PDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRA-------VSQGTPYSPDGQPMGGFVLDGQQHMGLRPAGPM---
-------GGMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSAMXG00000014706

------MAQRYDELAHYGG-MDGVGV------------------------
-------------PASMYGDPHAPRPLPQVHHLNHGPPLHASQH------
--------------------------------YGAHA--------PHPNV
MPTSMGSAVNDVLKRDKDQIYGHPL------FPLLALVFEKCELATCTPR
------------------------------------EPGV-AGGDVCSSD
SFNEDIAVFAKQVRAEKPLFSSNPELDNLMIQAIQVLRFHLLELEKVHEL
CDNFCHRYISCLKGKMPIDLVIDERDGSSKSDHEELSGSSTNLADHNPAS
WRDHDDATSTHSAGTPGPSSGGHASQSGDNSSEQGDGLDNSVA-------
---------SPGTGDDDDPD------------KDKKRQKKRGIFPKVATN
IMRAWLFQH-----------------------------------------
-------------------------------------LTHPYPSEEQKKQ
LAQD----------------------TGLTILQVNN-WFINARRRIVQPM
IDQSNRAGFLLDPSVSQGAAYSPEGQPMGSFVLDGQQHMGIRPAGPM---
-------SGMG-MNMGMD--GQWHYM------------------------
--------------------------------------------------

*
>P1;ENSLOCG00000013643

DLTFALAAMENSDSAEQGG-SEQ--SEAQRQRQRDRLNREEAFYQFVNNL
SEEDYRLMRDNNLLGTPVGEITEEELLSRLQQIKDGPEQQNANERSEESA
GAEGSEEGSNGDTILDWLNSVRRTGNTTRSGHRGNQSWRAVSRTNPNSGD
FRFSLEINVNRNITEQQARAEGEPLEGETEPVPGTAVVEQPMETVAAEVE
EPAIIVHPEAEPPESPLLIRPPIEQLDLPDPQSPPVEEAV-RRGQRRARS
RSPEQRRTRARNERSRSPLNHDGVEGPR----------------------
------RARRSTSSQSPHHISEPQMEGSSRTRQHILSRQSTVEYDAQ---
----LDSASAEPV---------NAPQEVENPSDGGAGVETNSSSRRPPTI
MLDLQVRRVRPGEYRQRDSIASRTRSRSQTSNNTFLYESERGGFRRTFSR
SERAGVRTYVSTIRIPIRRISDAGLSEATSMALQTMIRQIMTGFGELSYF
MDSDSDSDSNRGPSQSTEPTELHNTTNSTNTVNSSQESTEPRTAEERQDV
ASESASVPTVGREGRAGRSPISLEEPGSLPFLRLAH-FFLLND-------
---------------------DDDDQPRG-LTKEQIDNLSTRNFGEN---
-------DALKTCSVCITEYAE-------GNKLRKLPC-SH---------
------EYHVHCIDRWLSENSTCP-ICRRAVLVSTRES------------

*
