>P1;ENSGACG00000015133

MRRSA---AVFL-----------------------------L---L-SL-
--------------------------------------------------
------------LKASVCIQVNVPETERSTMLFSSVTLRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSANLQEVLL-TWRFKSFCKDPVLEYYS---
---------SAY-----------------------------QSALQLGQD
PANDCPDRQRTVRTVIQRRGNSQPTLGSEYRER-----------------
--------------------------------------------KITIQ-
-NTADLVITEVMWWDNGVY--------------------FCTV-------
---------------------------------------DAPGDTTGDSD
KEVKLIVYHW----------------------------------------
-------------------------------LTVLLIVIGALLLIILFG-
-ICCCQCCPQKCCCYVRCPCCPQQCCCPEKAVM-----------------
-----QHRMM------------------------------RDAQKAMAP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMGGQPVY-----
----------------------GPIS-P----------------------
-------------SP-----------SQMNPLLYSGSSSG----KSYPMK
PMPLPPPQ-------SSAYSAP----------------------------
APSV---HGTHT-----P--A-------------NSNHMLD---------
------------------YLEN-----------------QVRGLDMATPL
LQM--------------------------P-----------------PP-
---PQHLL-HAPFSPGPPSMISALEDGP---TERRV-IT--LPPIREQPP
ARSR-P----------AAPRTR----------------------------
-PP-SSRIPRSYS-------------------------------------
-------------------EESL-DGRRHSG--------------PRG--
GMD-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
SR-------SRDDLFDS-------RSRENYSAPASRHAAGGSWS------
--------------------------------------------------
------S-DDEGSSRRG---------------------------------
----------------G---EGFAEKPPNYS-------------------
------------EYE----PGQKPGAR-----------------------
----KN---------------------QRYS-------------------
-DKSSRSGTS----------------------VVI
*
>P1;ENSDARG00000040910

MKQKL--RLKVL------------------------------VLLLCVF-
--------------------------------------------------
------------PEEIFSIQVTVPETERHTMLFGSVTLRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSASQQDVLV-TWRYKSFCLDPVLEYYS---
---------AAY-----------------------------QAALNMKQD
PANDCPDSKRTVRIVIQKRGINEPVLGTEYRQR-----------------
--------------------------------------------KISIK-
-NNADLSMNEIMWWDNGMY--------------------FCSI-------
---------------------------------------DAPGDVVGDSD
KEIRLIVYNW----------------------------------------
-------------------------------LTVLLIILGALLLIILFG-
-VCCCQCCPQNCCCYVRCPCCPRTCCCPEKAVM-----------------
-----RHKMM------------------------------REAQKAMVP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WFHGQPIY-----
----------------------APIASN----------------------
-------------AS-----------SQANPLLYSGSFSEHSSKHNLPMA
PMAIPPPQ-------PVPQFVP----------------------------
SHGY---HANGSM---NGNVR-------------ANNQMLD---------
------------------FLEN-----------------QVQGMDMAVPM
LQPQHHYT-------------------GVPFQNHQPQYAAQQPHYASPP-
---PQSIPQAVTFPARPPSMLSALDEMGVQGVERRV-IQ--LPPILGRP-
KQSS-RRTND------QRPRQSSQSSGSSNRNGV--------HR----DP
ASS-RRGNQRSYS-------------------------------------
-------------------DESDWDDRRGGRSS----------SGRRGES
NRS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
VR-------SKAELLEELEHA-TNNGNRSYSSP-----HRGSWS------
--------------------------------------------------
------S-DEEDSYR-----------------------------------
--------------KGRRSQGKLSENPPAYS-------------------
------------SIDI-L-PGH---SR-----------------------
----RG---------------------EQLS-------------------
-DKSSRSGTS----------------------VVI
*
>P1;ENSORLG00000003688

M----------C-----------------------------V---C-CL-
--------------------------------------------------
------------STESVCVQVVVSKTEYSTTLFASVTLRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSANIQDILV-TWRFKSFCQDPVLNYYS---
---------TAY-----------------------------QSALQLGQD
PSNDCPDRQRTIRTVVQKKGGNEAILGGEYVNR-----------------
--------------------------------------------KITIQ-
-NKADLVISEVMWWDNGVY--------------------LCSV-------
---------------------------------------DAAGDTSGNPV
QEVKLIVYNW----------------------------------------
-------------------------------LTVLLIIIGAFLLILLFG-
-ICCCQCCPQKCCCYVRCPCCPQKCCCPEKAMM-----------------
-----EHRMM------------------------------KEAKQA----
--------------------------------------------------
--------------------------------------------------
-------------------------------------WQNGQ-VY-----
----------------------MPLS-H----------------------
-------------VS-----------SQMNPALYGGSVTG----NSNPMK
PMPLPAPY--------SPYSFP----------------------------
PPSV---QGNHP----------------------PGNHMID---------
------------------YLEN-----------------QVRGLDLTSPL
MQINGRMHHFQTAPQKQSQPAPPPHMQQMP-----------------PP-
---PQQMPINIPYSPGPPSMISALDEPP---RERRI-IT--LPPIREQPQ
GRGP-P----------PAPKTRPPSSSESNRSGYSR-RDERGGADR-RYP
SPSRSRGLPRSYS-------------------------------------
-------------------EESL-DGRSRGR--------------SRG--
GMN-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------PPR
SR-------SRDDLFDS-------RSRDNYSPPASRR-SRGSFS------
--------------------------------------------------
------S-DEETSSRGR---------------------------------
--------------RGG---GGWTEYEP----------------------
--------------------GQKPGPR-----------------------
----RN---------------------DPYS-------------------
-DKSSRGGTS----------------------IVI
*
>P1;ENSTRUG00000017115

MLKTV--AVVCG-----------------------------CVTIICLA-
--------------------------------------------------
------------LAVSVCIQVNVPEQQRSTFLFASVIIRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSASLQDVLV-TWKYKSFCKDPVLEYYS---
---------TAY-----------------------------QSALQLGQD
PSNDCPDRQRTVRTVLQKRGSNEAILGVEYRER-----------------
--------------------------------------------KISIQ-
-NKADLVINEVMWWDNGVY--------------------YCTV-------
---------------------------------------DAPGDTSGDSD
KEVKLIVYHW----------------------------------------
-------------------------------LTVLFIIIGILLLIMLFC-
-ICCCQCCPQKCCCYVRCPCCPQTCCCPEKAVM-----------------
-----QHRMI------------------------------KEAQRAMAP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMGGQPVY-----
----------------------GPIS-H----------------------
-------------AS-----------TQMNPLLYSGVYTYFLNGKSIPLK
AMPLPPPQ-------SSAYSMP----------------------------
PPSH---NGNIT-----P--A-------------NTNHMLD---------
------------------YLES-----------------QVRGMDMTSPL
LQASQD--LYFSTTV---QPHPPNHMQQVP-----------------PP-
---HQHMPAAIAFSPGPPSMISALDDAP---TERRI-IT--LPPIREQRP
NRNP-P----------SAPKTRPPSSSESSRSGFGR-RDERGAAGR-RYP
SPARSRGIPRSYS-------------------------------------
-------------------EDSM-DGRSHGR--------------ARA--
GMD-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
SR-------SRDDLFDS-------RSRANYSPPAGRRSRGGSWS------
--------------------------------------------------
------S-DDEDSSRRGGA-------------------------------
--------------RGGRG-GGYGDKPPLYT-------------------
------------EYE----PGQKP--------------------------
-----G---------------------ARYS-------------------
-DKSSRSGTS----------------------IVI
*
>P1;ENSTNIG00000013897

VTRGN--MILAT------------------------------L-VLLLL-
--------------------------------------------------
------------PSELLCIQVIVPETERRTTLFASIILRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSANPQDVLV-TWKFKSFCKDPVLEYYT---
---------TGY-----------------------------QAALQLGQD
PANDCPDRQRTIRTVIQKRGINEPTLGPEYRER-----------------
--------------------------------------------KITIQ-
-NKADLVITEVMWWDNGVY--------------------FCSI-------
---------------------------------------DAAGDTSGDSD
REVKLIVYHW----------------------------------------
-------------------------------LTVLLIILGALLLIMLLC-
-ICCCQCCPQACCCYVRCPCCPQTCCCPEKAVM-----------------
-----QHRML------------------------------KEAQKAMVP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WVHGQPIY-----
----------------------APISSH----------------------
-------------AS-----------SQGVPILHSGSFSDYPVKQNFAMT
PVQLSAMA-------LQQQ--P----------------------------
PPPR---HGNGSV---QPGLH-------------GNGQVLD---------
------------------YLEH-----------------QVRELDAGPPP
PAPH----------------------------------------------
----GVPPPAVPYTPRPPSMLSALDGLGVQVSPVEA-PT--APQEVS--P
TAAVGSGTPSF------LPNAESCAITTTTQT--GR-T------------
--------------------------------------------------
---------------------DEEERRRGS----------------RG--
RGE-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------EPR
AG---------------------------PERPR---RRKESWS------
--------------------------------------------------
------S-DEEEGGK-----------------------------------
--------------NWSKG-KDWAEKPPS---------------------
--------------------------------------------------
-----------------------------FS-------------------
-DRSSHGSNS----------------------VVI
*
>P1;ENSDARG00000103929

MMRGM--IRCVL------------------------------L-LLSVL-
--------------------------------------------------
------------ISDVMSIQVILTNQQMSTTLFATVTLRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSAQLQNVLV-TWVYKSFCKDPVLDYYS---
---------AAY-----------------------------QSALQLGQN
PANDCTDSQRTIRTVAQKLGTNEAVLGAEYRDR-----------------
--------------------------------------------KIYIQ-
-NKADLVIQEVMWWDNGVY--------------------YCKV-------
---------------------------------------DAPGDTIGDPD
KEMNLIVYNW----------------------------------------
-------------------------------LTVLLILIGALLLIILFC-
-ICCCQCCPQKCCCYVRCPCCPQTCCCPEKAVM-----------------
-----QHRLM------------------------------KEAQRAMTP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMNGQPLY-----
----------------------APMSNH----------------------
-------------SS----------SYQMNPLLYAGSTAG-----KGPMT
PLPLPPPQMPVTQMPLMQM--P----------------------------
PPSM---HGNGSA-------H-------------GTNQVLD---------
------------------YLEN-----------------QMRGIDVNSPL
LP---------------------------------------------PP-
---PQHVPQHVPFSAGPPSMLSGLEDVP---A-KRPRGHPHANS------
-------------------------SGSS---AYG--------P---RRG
PP---TSLPRSYS-------------------------------------
-------------------QEDVLEGRRG------------------A--
GAH-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
SR-------SRDDLLHTG---------PQYSPA-----RRGSWS------
--------------------------------------------------
------S-TDEGSRRG--P-------------------------------
--------------WGG-------------R-------------------
------------EYE----PGKKPA-K-----------------------
----RP---------------------ERFS-------------------
-DKGSRSGNS----------------------III
*
>P1;ENSONIG00000014174

MRNM----ILMA------------------------------L-LLVRL-
--------------------------------------------------
------------PTELLSVTVNVPETERSTMLFASVILRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSANQQEVLV-SWKFKSFCKDPVLEYYS---
---------TAY-----------------------------QAALQLGQD
PSNDCPDRQRTVRTVIQKRGINEPILGAEYRNR-----------------
--------------------------------------------KITIR-
-NNADLVITEVMWWDNGVY--------------------FCTI-------
---------------------------------------DAPGDTTGDSD
REVKLIVYHW----------------------------------------
-------------------------------LTVLLIIIGGLLLIMLFC-
-ICCCQCCPQNCCCYVRCPCCPRTCCCPEKAVM-----------------
-----EHKML------------------------------KEARKAMLP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMNGQPIY-----
----------------------APISSN----------------------
-------------AS-----------SQGVPILYSGSYPDYPTKHNFAMA
PMQLSPMG-------LQQQPPP----------------------------
PPSH---HGNSSV---GGSIY-------------GNNQVLE---------
------------------YFEN-----------------QVRGLDVIAPG
MAPHAVQN-------------------VPP-----------------LQ-
---AQPAPPQVSYTPGPPSMLSALDEMGTRGMERRV-IT--LPPIIQRVP
SFSS-RRGPGGGDGARGAPRMSSQSSGSTNRSAGGLHRNGRGSRDRYRSA
SPP-RRGILRDYI-------------------------------------
-------------------DDSDRDNRRGRASHRSSRNE-------RG--
SSS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RRR
AR-------SRDDLMDELQSR-APRRQRSYSPPL---HRNGSWS------
--------------------------------------------------
------S-DEEDSMRR----------------------------------
--------------KGGRG-RDWPELPPSYH-------------------
------------SIDI-Q-SPRSNNQR-----------------------
----NY---------------------DRLS-------------------
-DRSSHSNTT----------------------VVI
*
>P1;ENSAMXG00000015960

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------AY-----------------------------QAAIQLGQD
PSNDCPDRQRTVRIVAQKQGTNAATLGPEYSQR-----------------
--------------------------------------------KIAIQ-
-NKADLVISEVMWWDNGVY--------------------YCSI-------
---------------------------------------DAAGDMTGGGD
KFVKLVVYHW----------------------------------------
-------------------------------LTVLLIIIGALLLIILFG-
-VCCCQCCPQRCCCYIRCPCCPRTCCCPEKAVM-----------------
-----QHRMM------------------------------KDAQKAMSA-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WANGQQIY-----
----------------------APLSNH----------------------
-------------SS----------SYQMNPLLYGGSASG-----KMPLT
PMPLPPPQ-------PMMM--P----------------------------
PPSI---HGNGSV---HGSVH-------------GTNQVLD---------
------------------FLEG-----------------QVRGMDMAGPI
IQPQPLLQ-------------------HLP-----------------PP-
---PQHMPQNVPFSAGPPSMLSALGEGP---NVRRPQGT--RPP------
-------------------------SGSS---GYG--------R---HYP
PPA-GRNMTRSYS-------------------------------------
-------------------QEDMLDNQSHA----------------GG--
PGY-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
SR-------SRDDLVAEPRRPGPSRNDRNYSPQ----HRRGSWG------
--------------------------------------------------
------SASDEDSRRGG-S-------------------------------
--------------RGGRG-GDWSDHPPSYR-------------------
------------EYE----PGQKPM-K-----------------------
----RP---------------------ERF--------------------
--TSSRSGTS----------------------IVI
*
>P1;ENSXMAG00000011785

MG----NVILVV------------------------------F-LLLHL-
--------------------------------------------------
------------PTELLSIQVVVPQVERATALFAWVTIRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------TTSANQQEVLV-TWKFKSFCKDPVLEYYS---
---------TAY-----------------------------QAALQMGQD
PANDCPDRQRTVRTVIQKRGVNEPTLGSEYRNR-----------------
--------------------------------------------KITIQ-
-NKADLVINEVMWWDNGMY--------------------YCSI-------
---------------------------------------DAPGDTTGDSD
REVRLIVYHW----------------------------------------
-------------------------------LTVLFIIIGALLLIMLFC-
-ICCCQCCPQKCCCYVRCPCCPQTCCCPEKAVM-----------------
-----QHRML------------------------------KQAQKAMAP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMYGQPVY-----
----------------------ANVS-N----------------------
-------------TS-----------SQGVPLLYSASVSDYPTKQNISMT
PIPLGPMA-------LQQQ--Q----------------------------
PPLHAQYMVNGSL---RSSNQ-------------SANPMLD---------
------------------YLEN-----------------QMRGLDVGPPQ
MAPHAVRN-------------------MAP-----------------LQ-
---PQPSPPAVPYAPGPPSMLSALDDMGVKGVERRV-IT--LPPIIQRGP
AG----------DGAGGYPRMSSHSSGSTNRSGRGQRGDNRGYRT--RED
LLP-RQGVLREYS-------------------------------------
-------------------DDSDWDNRRGRATHRSSRNERGSSSGRRE--
RGS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
AR-------SRDDLMEELHSR-SARRERSYSPPT---HHKGSWS------
--------------------------------------------------
------S-DEGSSQK-----------------------------------
--------------KGRKV-KDWSEKPPSYY-------------------
------------ASEV-Q-P----DRR-----------------------
----NY---------------------SHLS-------------------
-DRGSHSSTS----------------------VVI
*
>P1;ENSTNIG00000009485

AMRRL--FAALL-----------------------------LLSILNGF-
--------------------------------------------------
------------LAGSLCIQVNVPQQERSTALFASVILRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSASLQDVLV-TWKFKSFCKDPVLEYYS---
---------TAY-----------------------------QSALQLGQD
PSNDCPDRQRTVRTVVQKRGSNEAILGAEYRER-----------------
--------------------------------------------KISIQ-
-NKADLVINEVMWWDNGVY--------------------FCTV-------
---------------------------------------DAPGDTTGDSD
KEVKLIVYHW----------------------------------------
-------------------------------LTVLFIIIGFLLLIILFG-
-ICCCQCCPQRCCCYVRCPCCPQQCCCPEKAVM-----------------
-----QHRMI------------------------------KEAQRAMVP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMGGQPVY-----
----------------------GPLS-H----------------------
-------------AS-----------SQMNPLLYSGSASG----KSFPLK
AMPLPPPQ-------SSAYSMP----------------------------
PPSV---NGNLT-----P--A-------------NTNHMLD---------
------------------YLES-----------------QVRGIDMASPL
LQV--------------------------------------------PP-
---HQHMPAAVPFAPGPPSMISALDDGL---TERRV-IT--LPPIREQR-
NRNP-P----------PAPKTR----------------------------
-PP-SSSIPRSYS-------------------------------------
-------------------EESL-DGRSHGR--------------ARA--
GMD-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
SR-------SRDDLFDG-------RPRGKYSPPAGPRSRGGSWS------
--------------------------------------------------
------S-DDEDSSRRG---------------------------------
---------------------GWGDKPSIYT-------------------
------------EYE----PGQKP--------------------------
-----G---------------------GRYS-------------------
-DKSSRSGTS----------------------IVI
*
>P1;ENSGACG00000003173

LSCKLRNKNPVT------------------------------L-MQIFT-
--------------------------------------------------
------------HSELLSIQVIVPQRERSTTLFASVILRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSANPQDVLV-TWRFKSFCKDPVLEYYS---
---------TAY-----------------------------QASLQLGQD
PTNDCPDRQRTIRTVIQKRGINEPTLGVEYRIR-----------------
--------------------------------------------KITIQ-
-NKADLVINEVMWWDNGVY--------------------FCSI-------
---------------------------------------DAAGDTAGDSD
QEVKLIVYHW----------------------------------------
-------------------------------LTVLLILIGALLLITLFC-
-ICCCQCCPQKCCCYVRCPCCPQTCCCPEKAVM-----------------
-----QHRMI------------------------------RDAQKAMSP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMNGQPIY-----
----------------------APISSN----------------------
-------------AS-----------SQGVPILYSGSYSDYPTKQNFAMV
PMELSPMA-------LQHQ--P----------------------------
HPNH----MNGSV---HGGH---------------PGQVLD---------
------------------FLEN-----------------QMRGLDMGAPQ
AVPYSHQN-------------------MLP-----------------LQ-
---PQAAPQAVPYTPGPPSMLSALDEMGVRGVERRV-IT--LPPIIQRVP
SFPS-RRGPADGDGARDGSRISSQSSGSTSRRGG----DSRGYR----DV
SQP-RQGILRDYS-------------------------------------
-------------------DDSEWENRRAGAPRGSSRNRRGGPSGRRG--
GGS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
TR-------SRDDLMEELHGT-AARRERSYSPPQ---RREGPWS------
--------------------------------------------------
------S-DEEDSGRR----------------------------------
--------------KGGRG-RDWPEKPPSYF-------------------
------------SIES-Q-LGSSNGRR-----------------------
----NY---------------------DRFS-------------------
-DRSSRSGTS----------------------VVI
*
>P1;ENSTRUG00000012684

AKQKT--SLFCL------------------------------ISSFFWR-
--------------------------------------------------
------------VPELLSIQVIVPETERSTTLFASVILRCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSANPQDVLV-SWKFKSFCKDPVLEYYS---
---------TAY-----------------------------QAALQLGQD
PANDCPDRQRTIRTVIQKRGINEPTLGPEYRER-----------------
--------------------------------------------KITIQ-
-NKADLVITEVMWWDNGMY--------------------FCTI-------
---------------------------------------DAAGDTSGDSD
REVKLIVYHW----------------------------------------
-------------------------------LTVLLIILGALLLIMLLC-
-ICCCQCCPQKCCCYVRCPCCPQTCCCPEKAVM-----------------
-----EHRML------------------------------KEARKAMVP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMNGQPIY-----
----------------------APISSN----------------------
-------------AS-----------TQGVPILHSGSFTDYPVKQNFAMA
PMQLSPIP-------LQQQ--P----------------------------
PPPH---HMTGSV---QHNNH-------------RNGHMLD---------
------------------YLEN-----------------QVRELDMGPLQ
AAPHSAQH-------------------MLP-----------------LQP
QVQRQPGPTAVPYMPGPPSMLSALDEFGVRGMERRV-IT--LPPIVKRVP
SFSS-GRGPAGGDRARGGPLLSSQSSGSTSRSAGGL-PNSRGYR---DAS
PPP-RRGILRDYN-------------------------------------
-------------------NESEWEKRRGRTPQRELWNESGGSDRRRG--
GGS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------GLR
SR-------SRDDLMEELHSR-RPKRERSFSPPR---RRKEPWS------
--------------------------------------------------
------S-DDEEAGR-----------------------------------
--------------KWNKG-KDWVEKPPSYF-------------------
------------SIEN-Q-RGRSNNRK-----------------------
----KY---------------------HQFS-------------------
-DRSSRSSNS----------------------VVI
*
>P1;ENSORLG00000012732

SREEL--WFGIS------------------------------P-HILCL-
--------------------------------------------------
------------FLELLSVQVVVPQTERSTMLFSNVILYCDY--------
--------------------------------------------------
--------------------------------------------------
------------------STSASSQDVLV-SWKFKSFCKDPVLEYYS---
---------TAY-----------------------------QAALQLGQD
PANDCPDRQRTVRTVVQKRGGNEPVLGVEYRNR-----------------
--------------------------------------------KITIQ-
-NKADLVINEVMWWDNGMY--------------------YCSI-------
---------------------------------------DAAGDTTGDSD
REIKLIVFHW----------------------------------------
-------------------------------LTVLLIIMGALLLIMLCC-
-ICCCQCCPQKCCCYVRCPCCPQTCCCPEKAVM-----------------
-----QHRMV------------------------------REAQKAMAP-
--------------------------------------------------
--------------------------------------------------
-------------------------------------WMKGQPIY-----
----------------------APISSN----------------------
-------------MS-----------SQGGPLLYPGFYSDYPTKQSFAMT
PMQPSPMA-------LQQQAPP----------------------------
PPPH---QYSGSF---QGSIQ-------------GTNQVLD---------
------------------FLEN-----------------QVKGLDVGVPQ
MSPYAHQI-------------------MFQ-----------------PQP
--RLEPAPHAVPYAPGPPSMLSALDEMGVKGVERRV-IT--LPPIVQRIP
GLSS-HGGAAGRHGARG-YRASSHSSGSTNPSA-------RGYA----DN
TPA-RHGILRDYS-------------------------------------
-------------------DDSDLDFRRGRAPHRGSRNEGGGSSGRSR--
GGS-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------RPR
TR-------SQDDLLEEMYER-AARKGRSLTPPQ---RPKEPWS------
--------------------------------------------------
------S-DEEDRRRR----------------------------------
--------------KGGRG-KGWTEQPPSYS-------------------
------------TIDI-Q-HGNSSSHK-----------------------
----NY---------------------APLS-------------------
-DRGSHSSSS----------------------VVI
*
>P1;ENSLOCG00000001031

MNGGR--SVWAITPEERDKHDKQFDALQPTMGFVSGDQARKFF-LQSSLP
APVLAEIWALADLNKDGKMDRLEFSIAMKLIKLKLQGHCLPSALPIIMKQ
PPVQSPLTSSRFGMGSMPNLSVVPAMPMTMPMFAPLPLTTSMSPLSPMGL
SAPLVPSVSPSALPNGTAGILQPSPASFTTILPLTSSVPSSSVGLGGTGM
TKTQSLLDLGSSSSNSSSTTSLTSNSPKAGSGDWAVPQSSRLKYRQIFNS
IDKAMTGYLSGPQVRNALATSNLTQTQLATIWNLADVDKDGKLKADEFIL
AMHLVDMAKTGQPLPLTLPTDLIPPSLRSGKSGDTVNGTVPISKGTLEED
P---EPPQKKTLATFEDRRKENFDRGNAELEKRRQALLEQQRREEERAAQ
KAREERERREREAWEQELRRRQEQERRLERQRELERQREEERLKELERKE
KAKQELERQRKLEWEKTRRQELLSQRNQEQEDIVKLKAKKKSLEMELEAV
GDKHKQISNRLHEAQSKRKIQKGELDLTNQKWDRRIMEINNLQQEFEDYQ
KELSRLVPEQQKLNDKLRNMKSSGFQTSAVTTLKKNITEKDVSCRKLKEQ
LDALEKETSAKLAEMNQFNKEFKFEDMDDCVLQCLLSLLGCLSNLFLLIK
ELRDSQNKQQ--------TALDKLCKIKEEKIKELQRRKEQELERKQREE
EEAIRRAKLEKERLWQEKVKRDEEERQRRLQEERLQKQREEEEQEALARQ
REAEEAAERERRAAEERKRREREEEQRRKAEEERRREEERRREEERKREE
EERQREKERKREEERRRQEEREREEERRRQEEKRRREEERRLEEQRNREE
EEKRRQRAEEAAVRDAEERKRQQLQEEMSRKQQQQQQQQNSEPFTSTKID
IHEKLSALLKGIDERQNSRKGTRPVSKGHRKSAFLVTYRALYPFAARNTD
ELTFETNDLIEVDETTKGEPGWLYGSHQGRTGWFPESYVEKPSNNETPSV
AKQDTLPQN-------SAISSTSVFSGKSEEEAGSQQKLVSGVVGQNSAF
TPTH----SPGSSSADRGRVVTNFQAQALCSWTAKTDNHLNFSKDDIITV
TEQQENWWLGELNGVQGWFPKDYVKVLNASDAQNEPIYACVEGFEMPTDL
TQHEE----------------------YVA-----------------LYT
--YESPEPGDLTFCEGDTILVTEREGEWWKGCIGDR-SG--LFPSNYVKP
KETD-NSGVAGRTGASGK-KPEIAQV-TSAY-------TATGTE----QL
SLAPNQLILILSKNSSEWWLGELQARGKKRQKGWFPANHVKILGPSSGKT
TPAPAPICQVIAMYDYKAANEDEMSFSKGQIINVLNKDNADWWKGEYN--
GITGLFPTNYVKMTTDSDPSQQWCADLMSLDTMSPLERKRQGYIHELIAT
EERYMDDLQLVLEVFHKPMAESGMLTENEMSMIFVNWNELITSNTKLLKA
LRVRKKTGGEKMPVQMIGDILASELAHMQAYIRFCSCQLNGAALLQQKTD
QEPDFKESLKRFATDNRCKGMPLSSFLLKPMQRITRYPLLIKNILESTPE
SHPDHSHLREALEKAEELCSQ-VNEGVREKENS-----DRLEWIQTHVQC
EGITEHLVFNSLTNCLGPRKLLHSGKLFKTKSNKELYGFLFNDFLLLTYM
VKQFTSS-GVEKVFSPK-SNSQFKMYKSPVFLNEVLVKLPSDPSSDEPVF
HISHIDRVYTLRTENINER-TAWVQKIKAASEHFLDTEKKKREKAYQARS
QKASGIGRLLVTILEASELKSSKPNGRSNSYCEVTMGAQCFTTRTINDTS
NPKWNFNCHFFIKDLYQDVLCITIFGRDQFSPDDFLGRTEVPVATIKKEL
ENKGAATRRLLLHEVPTGEVWVRLDLQLYDQKTLV
*
