>P1;ENSTNIG00000012496

---------------------------------MGVEVET----IVPGDG
QTFPKKGQRVVVHYVGTLMNGQMFDSSRDRGKPFKFK-------------
--------------------------------------------------
-------IG----------HGEVIR-------------------------
--------------------GWEEGVA------QMSVGQRAKLI----CS
PDFAYGSKG-----------------------------------------
---------HPGIIPPNATLIFDVELLGL---------------------
-----------EV--------------------
*
>P1;ENSDARG00000033567

---------------------------------MGVEIET----ITPGDG
RTFPKKGQTCVVHYVGSLTDGRKFDSSRDRDKPFKFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWEEGVV------QMSVGQRAKLT----CS
PDFAYGNKG-----------------------------------------
---------HPGIIPPNATLIFDVELLSL---------------------
-----------Q---------------------
*
>P1;ENSAMXG00000012980

---------------------------------MGVEVET----ITPGDG
STFPKKGQTCVVHYVGSLTDGRKFDSSRDRGKPFKFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWDEGVA------QMSVGQRAKLT----CT
PDFAYGSKG-----------------------------------------
---------HPGIIPPNATLIFDVELLGL---------------------
-----------E---------------------
*
>P1;ENSAMXG00000003590

---------------------------------MGVEIET----ITPGDG
RTFPKKGQTCVVHYVGSLTDGRKFDSSRDRDKPFKFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWEEGVV------QMSVGQRAKLT----CS
PDFAYGNKG-----------------------------------------
---------HPGIIPPNATLIFDVELLSL---------------------
-----------E---------------------
*
>P1;ENSONIG00000001640

MRNIRRRSAQTDGLREECCRVRGQQQQQLQDAEMGVEIET----ITPGDG
RTFPKKGQTCVVHYVGSLTDGRKFDSSRDRDKPFRFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWEEGVV------QMSVGQRAKLT----CS
PDYAYGNKG-----------------------------------------
---------HPGIIPPNATLIFDVELLGL---------------------
-----------E---------------------
*
>P1;ENSTRUG00000003030

---------------------------------MGVQVDT----ITPGDG
QTFPKKGQQVAVHYVGTLVDGTTFDSSRDRGRPFRFK-------------
--------------------------------------------------
-------IG----------RGEVIR-------------------------
--------------------GWEEGVA------QMSVGERAKLT----CS
PDYAYGAKG-----------------------------------------
---------HPGVIPPNATLIFDVELLSL---------------------
-----------EA--------------------
*
>P1;ENSORLG00000002452

---------------------------------MGVEIET----ITPGDG
RTFPKKGQTCVVHYVGCLTDGRKFDSSRDRDKPFRFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWEEGVV------QMSVGQRAKLT----CS
SDFAYGNKG-----------------------------------------
---------HPGIIPPNATLVFDVELLGL---------------------
-----------E---------------------
*
>P1;ENSONIG00000016814

------------------------PEEGYSGAKMGVEIQT----ITPGDG
RTFPKKGQRVVVHYVGTLADGKVFDSSRSRGKPFKFK-------------
--------------------------------------------------
-------IG----------HQEVIR-------------------------
--------------------GWEEGVA------QMSVGQRAKLI----CS
PDYAYGSKG-----------------------------------------
---------HPGIIPPNATLTFDVELIGL---------------------
-----------E---------------------
*
>P1;ENSXMAG00000018066

-----------------------------SNAKMGVEIET----ITPGDG
RTFPKKGQRVVVHYVGTLDDGKVFDSSRSRGKPFKFK-------------
--------------------------------------------------
-------IG----------HQEVIR-------------------------
--------------------GWEEGVA------QMSVGQRAKLI----CS
PDFAYGSKG-----------------------------------------
---------HPGVIPPNATLTFDVELLGL---------------------
-----------E---------------------
*
>P1;ENSORLG00000014598

------------------------RKK-HRENIMGVEIET----LTPGDG
RTFPKKGQRVVVHYVGTLADGKVFDSSRSRGKPFKFK-------------
--------------------------------------------------
-------IG----------HQEVIR-------------------------
--------------------GWEEGVA------QMSVGQRAKLI----CS
PDYAYGSKG-----------------------------------------
---------HPGVIPPNATLTFDVELLGL---------------------
-----------EA--------------------
*
>P1;ENSGACG00000012061

---------------------------------MGVDIET----ITPGDG
RTFPKKGQRVVVHYVGTLADGKVFDSSRSRGKPFKFK-------------
--------------------------------------------------
-------IG----------HQEVIR-------------------------
--------------------GWEEGVA------QMSVGQRAKLI----CS
ADFAYGSKG-----------------------------------------
---------HPGIIPPNATLTFDVELLSL---------------------
-----------EA--------------------
*
>P1;ENSGACG00000004338

---------------------------------MGVEIET----ITPGDG
RTFPKKGQTCVVHYVGSLTDGRKFDSSRDRDKPFRFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWEEGVV------QMSVGQRAQLT----CT
PDFAYGNKG-----------------------------------------
---------HPGIIPPNATLIFDVELLGL---------------------
-----------E---------------------
*
>P1;ENSXMAG00000016714

---------------------------------MGVEIET----VTPGDG
RTFPKKGQTCVVHYVGSLTDGRKFDSSRDRDKPFRFK-------------
--------------------------------------------------
-------LG----------KQEVIR-------------------------
--------------------GWEEGVG------QMSVGQRAKLI----CS
PDFAYGNKG-----------------------------------------
---------HPGIIPPNATLIFDVELLSL---------------------
-----------E---------------------
*
>P1;ENSDARG00000022684

---------------------------------MGVEVET----ITPGDG
STFPKKGQTCVVHYVGSLTDGRKFDSSRDRGKPFKFK-------------
--------------------------------------------------
-------IG----------KQEVIR-------------------------
--------------------GWDEGVA------QMSVGQRAKLT----CT
PDFAYGSKG-----------------------------------------
---------HPGVIPPNATLIFDVELIGL---------------------
-----------E---------------------
*
>P1;ENSLOCG00000014246

---------------------------------MLPDKDGTRGELGCGSG
ATCRGHSEDTAVSLFREYLRIRTVHPEPDYDAALKFLDRVAGELELPMRT
VEVCPNRIVAIVTWEGTDPRLRSVLLNSHTDVVPVFQEQWKYDAFAAVKD
KEGNIFARGAQDMKCVTIQYIEAIRRLKSEGRRLARTVHLMFVPDEEVGG
HKGMEAFVNHPEFRALNVGFALDEGLANPEETFTVFYGERNPWWITIKCT
GSPGHGSRFVENTAAEKLRKIINSFLDFREREKNRLNTSECLTLGDVTTV
NMTKLQGGVAYNVIPAEMDVSFDIRIPPTADLQEFEEQIKEWCRVAGDGI
TYQFAQKHMQQDVTSTAESDPWWKAFTAACGAM
*
