>P1;ENSGACG00000020505

---M-ASAGLQIMGIFLAAIGFIGAIITCAL-P-------MWKVS-----
--------------------------------------------------
--------AFIGSNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VEAQTYWDGLWMNCVMQSTGQMQCKIYPSML-
-----------------------------------------------ALA
SDLQAARALMVL-------------------------------------S
ILVSAMGLLLAVVGGK------CTNCIEDDAAKSKVAIAAGVFFIVGGIL
CLIPASWTAHEVIRNFYSPIM-LEAQKRELGASLF-----IG--------
-----------------------------WGSAGLLLVGGALLCCQCRQC
EEDRFS--------VKYSAPRKASSGAYVKLSPSPKAYTRQRFL
*
>P1;ENSAMXG00000026083

---M-ASAGLEILGMILSVAGWLGVMVACCL-P-------MWRVA-----
--------------------------------------------------
--------AYVGQNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VITQVVWEGLWMSCVVQSTGQMHCQIYDSML-
-----------------------------------------------GLP
EDLQAARALTVV-------------------------------------S
TFVGVVGISLAVAGAK------CTNCTSDVSNKPRIMMGAGGAFIGAGLL
LLVAVCWTANTIILEFHDPML-QETQKREFGNSLY-----FG--------
-----------------------------WGASCLLILGGAILSCSCPSR
RQSNHAS-----ARADYSAVKSMAS----------TGYDRRDYV
*
>P1;ENSXMAG00000019833

---M-YSAGLEILGMILAVAGWLGVMVACGL-P-------MWRVA-----
--------------------------------------------------
--------AFIGQNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VISQVIWEGLWMNCSVQSTGQMHCRVHESML-
-----------------------------------------------GLP
TDLQAARALVIV-------------------------------------S
MVMSIVGIGLAVAGAK------CTNCSRDVSSKPRLVAAAGVTFVAAGLL
MLVAVSWMAHAIVLGFYDPML-EETGKREFGNALY-----FG--------
-----------------------------WAASCLLILGGALLCCSCPSK
AAAAPSGAVSAAPRVDYSAVKSTSV----------NGYTRKDYV
*
>P1;ENSXMAG00000014346

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------HLTQTSWVKCKYLHIGREVTKVYDSML-
-----------------------------------------------ALS
QDLQAARAMVII-------------------------------------S
VIVGVFGMLMAIAGGK------CTNCMDDEASKAQACIVSGVIFIITALL
IMIPVSWSAHNAIRDFYNPLV-TAAQRRELGAALY-----IG--------
-----------------------------WGSAALLLIGGGLLCNNCPPK
DNRPYI-------PAKF---------------------------
*
>P1;ENSDARG00000069888

---M-VSAGLQMVGIALAVIGWIGVIVVCIL-P-------MWQVT-----
--------------------------------------------------
--------AFIGQNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VTAQVTWEGIWMSCVVQSTGQMQCKVYDSML-
-----------------------------------------------ALS
SDLQAARALCII-------------------------------------S
ILVGVVGILLAAAGGK------CTTCIEEERAKAKVCVISGAIFIVAGVL
CLIPVCWTANNIIRDFYNPMT-NSAQKRELGASLF-----IG--------
-----------------------------WGASALLIIGGSLLCANCPPQ
DQ--YK--------ATYTA-RSG---------------GTKGYV
*
>P1;ENSAMXG00000025942

---M-AGSGMQILGFALALLGWIGVITACAL-P-------MWKVT-----
--------------------------------------------------
--------AFIGQNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VTAQTFWEGLWMNCVMQSTGQAQCKVYDSML-
-----------------------------------------------ALP
QDLQAARALVVI-------------------------------------A
ILVALVGLALAAAGGD------CTNCVEDDTAKARVSVTAGVCLVVAGVL
CLIPVSWSANTVITDFYNPQV-TDAQRRELGASLF-----IG--------
-----------------------------WGAAALLLLGGALHCCRCPQN
ENRRYT--------AKYTAPRSAAP-------------STGAYV
*
>P1;ENSTRUG00000016044

---M-ASVGLEILGVSLGVLGWILAIVSCIV-P-------MWRVS-----
--------------------------------------------------
--------AFIGMNIVTAQITWEGIWMNCVVQSTGQMQCKVHDSMLALSA
DLQAARALTIISIVLGVMGIVVAMMGSKCTNCVGEDSAKARVMIAAEIRK
TFDLSTDRSEAAHAHCEVSWLELIGISLCVLGWIIGIVACALPMWRVTAF
VGSNI-------------VTAQVIWEGLWMTCVVQSTGQMQCKVYDSML-
-----------------------------------------------ALS
QDLQAARALTVI-------------------------------------A
ILLAILAVMIGIAGAK------CTNCIEEEASKAKVMIISGVFFIVSGVM
QLIPVSWSANTIIRDFYNPLI-TDAQRRELGAALY-----IG--------
-----------------------------WAAAALLILGGGLLCCSCPPR
ETRYNP------SRMAYSASRSAG----------GPAIERKDYV
*
>P1;ENSTRUG00000010140

TVKM-VSTGFQMLGAALGIVGWIGAIIACAL-P-------MWKVT-----
--------------------------------------------------
--------AFIGSSI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------ITAQTTWEGIWMNCVVQSTGQMQCKVYDSML-
-----------------------------------------------ALG
SDLQAARALVII-------------------------------------S
IMVGIIGILLAVAGGK------CTNCVEDPTAKAKVGIAAGVAFIVAGIL
CLIPTCWTAHVVVRDFNNPLV-PAAMKRELGAALY-----IG--------
-----------------------------WGAAALMLIGGALLCCNCPKK
DKGSYT--------ARYNAARSEAS----------APASGKDYV
*
>P1;ENSGACG00000012742

---M-YSAGLEILGMILAVAGWLGVMVACGL-P-------MWRVA-----
--------------------------------------------------
--------AYIGQNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VISQVIWEGLWMNCSVQSTGQMHCRVHDSML-
-----------------------------------------------GLP
VDLQAARALVIV-------------------------------------S
MVLCVVGIGLSVAGAK------CTNCSRDVSSKPRLVVTAGVTFVVAGLL
LMVAVSWTAHAIVLGFYDPLL-QETGKREFGNALY-----FG--------
-----------------------------WASSCLLLVGGALLCCSCPPR
AAAAPSGSGSAAPRVDYSAVKMLSV----------NGYPRRDYV
*
>P1;ENSORLG00000002904

---I-MSMGLELVGICLGFIGFIGAIIICIL-P-------QWRTT-----
--------------------------------------------------
--------AFIGSNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VTAQVIWEGLWMNCVTQSTGQMQCKIYDSML-
-----------------------------------------------ALP
QDLQASRAMTVV-------------------------------------A
IILGVLGVLISIVGAK------CTNCIEDETGKAKVMIISGIFFILAGLL
VLIPVSWSASAIIRDFYNPVV-VEALKREVGASLY-----IG--------
-----------------------------WGAAALLLIGGALLCTRCPPK
EEKYKP------TRMAYSAPRSVSA---------GGGYDKKDYV
*
>P1;ENSTNIG00000016115

---M-VSTGFQMLGAALGILGWIGAIVSCAL-P-------MWKVT-----
--------------------------------------------------
--------AFIGSSI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------ITAQITWEGLWMNCVVQSTGQMQCKVYDSML-
-----------------------------------------------ALS
SDLQAARALLVV-------------------------------------A
ILVGIVAILLSVAGGK------CTNCVQDPTAKSKVGIAAGVTFIVAGVL
ILIPTCWTAHQVISDFNNPLV-PAAMKRELGAALY-----IG--------
-----------------------------WGAAALMLIGGGLLCCNCPEK
KDGSYT--------ARYNAARSEAS----------APASGKGYV
*
>P1;ENSDARG00000087096

---M-ASQGIQILGIMLSMIGWLGTIIACGM-P-------MWRVT-----
--------------------------------------------------
--------AFVGANI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VTAQIIWEGLWMSCVVQSTGQMQCKVYDSML-
-----------------------------------------------ALS
QDMQASRAMVII-------------------------------------S
IMVGIFGFLMAVVGGK------CTNCLEDEAAKAKACIFSGVVLIIAGLL
ILIPICWSAHTLIRDFYNPLL-TASQRRELGACLY-----IG--------
-----------------------------WGSGGLLLLGGGLLCWNCPSN
NTRPYI-------AAKYTHGRSMT--------------PTINYV
*
>P1;ENSONIG00000020465

---M-YSTGLEILGIILAVAGWLGVMVTCGL-P-------MWRVA-----
--------------------------------------------------
--------AYIGQNI-----------------------------------
--------------------------------------------------
--------------------------------------------------
------------------VISQVIWEGLWMNCSVQSTGQMHCKVHDSML-
-----------------------------------------------GLP
VDLQAARALVII-------------------------------------S
LVLCIVGIVLSVAGAK------CTNCSRDVSSKPRLMVAAGVTFVVAGLL
LLVAVSWTAHAIVLGFYDPML-EETGKREFGNALY-----FG--------
-----------------------------WAASCLLILGGALLCCSCPRR
STTAPSGGG-PAP------------------------------S
*
>P1;ENSLOCG00000007693

---LTVGPGLVRLGL-LSLCGWLLAQ-GCGPGPGHGRRPKMRKLTPIPYK
HSVPNFSENNLGASGRAEGKITRSSERFKDLVANYNPDIIFKDEENTSAD
RLMTKRCKDCVNALAIAVMNQWPGVRLRVTE-------------------
--------------------------GWDEDGHHPPNS------------
-----------------------------------------------LHY
EGRAVDITTSDRDPRKYGTLAQLAVEAGFDWVYYESKSHVHCSVKSDHSV
TVEKGGCFPGSAQVSLAGGGQVSLSTVSSGMHVLAVDKAGLLVPSRVLLF
LDRDAGRKACFIVLETKEETRLRLTPSHLLFLSSKRTLDLSLYQASFASE
AMPGKF-VLVKSEGGELHPSQILSVSLEEDVGVYAPLTEHGT-LFVDGVL
VSCYAELNDHSLAHWVFAPLRVLLAFAQELGLVTYQSSLRAHWSRASPRE
YAARGPLLSLSRGLGFGIYQLTDQDPGVHWYARLLHVLGRMLLD---PKK
F------------------------------------------H
*
