>P1;ENSORLG00000006799

AKEGLHSGRLQTDGEVWKMGDEKPFVCG-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFDQD-----
--DDEKRAKNSV-------------TA-NSVALDMS-LQT----------
--------PS-------------------DV----KVKEEEAPVEVD---
---------------------------------------------SSPPG
SPESISGM------------------------------------------
---------------SDSSQD--------PI-------------------
-D---MPP---RNSAPTPAIVRP---------------------------
GSLPLHLGF-DA-----------------------------LQPTMPSPT
SVITQAPPSNRT-L------------------------------------
---GSPTSHYPMM-MLPGGQA--------------VPVLPGPV--PSVIN
--------------------------------LARPMCMVPNI-------
------------PGIPGPPLGGSSSGSNS---------------------
---------------PSGYSNHSEAKMRLK-----AALSQQSPLGQNMGV
--------------------------------------MAMGNSAMVPQK
M----------------------------------------EQSQLLVQH
PDAPSPAQPQVSPAQPTGGRRRRTADDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVSSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LSTLNV
---------------------------SLS-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKK--------------------------
-----NAYLAA--ED-GIRD-TSEPTGS-PAPVIQHSSL----APSPSA-
-GQNGLS-----------------SRAAAEAMA-----------------
------------------------------MSVLAGMGQQ-QRVESGPSH
VIMAPGAQQQPSGN
*
>P1;ENSTNIG00000014570

RKLSLFVF---LSEHLSEMGDDRPFVCN-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLSV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQELSKAH
--DDEHRTKHPPL-----------FKA-------AP-LQT----------
--------PS-------------------EV----KIEN-EGPLEVD---
---------------------------------------------SSPPD
SPGSSSSM------------------------------------------
---------------SDDSRD--------S--------------------
-----RPV---VSSAPTPTIVRP---------------------------
GSLPLHLSN-DA-----------------------------LHPTLPSPT
SVITQAPPSNRQ-L------------------------------------
---SSPTSSYPLVRHLPNGQT--------------VPLLPSPVQLTSVIS
--------------------------------LARPVNSVPNV-------
------------PGIPGPPV------------------------------
-----------------GYSLHAETKLRLK-----AALTNQGTQDGA-VG
--------------------------------------VAGSSIPAVPQR
Q----------------------------------------EQSQQPSQN
SDAPSPVQPQVSPAQPTGGRRRRASEMDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVNSLE-------KK
--------------------------------------------------
------------AED-----------------------------LANMNI
---------------------------TLT-------------NEVTLLR
NEVAQLKQLLLAHKDCPVTIMQKK--------------------------
-----AAFLAAGGEE-PSRDVSAEATGS-SAAVIQHGPSPPTSVSSPGS-
-TINGLS-----------------VHA-AEAVA-----------------
------------------------------MSVLAGMGSG-Q-----PGA
INMAVQSQPAP--R
*
>P1;ENSGACG00000000679

------------------MGDDRPFVCT-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLSV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ATSFENEFTKAH
--EDDQRTKHPA----------------------AP-LQT----------
--------PS-------------------EV----KVKH-EGPLQVD---
---------------------------------------------SSSPG
SPDSSSSM------------------------------------------
---------------SDNSRD--------SR-------------------
-EILTKPV---VSSAPTPTIVRP---------------------------
GSLPLHLSN-DA-----------------------------LHPTLPSPT
SVITQTPPSNRQ-L------------------------------------
---SSPTSVFPLV-RLPNGQT--------------LPLLPSPGQMTSVIS
--------------------------------LARPATAVPNI-------
------------PGIPGPPVGGASSGSSS---------------------
---------------PSGYSLHSETKMRLK-----AALTNQGPGAQDGAC
--------------------------------------GGAGSIPAVPQR
P----------------------------------------EQGQQPTQN
SDAPSPAQPQVSPAQPTGGRRRRASEMDPDERRERFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVNSLE-------KK
--------------------------------------------------
------------ADD-----------------------------LAGMNV
---------------------------SLS-------------NEVSLLR
NEVAQLKQLLLAHKDCPVTVMQKK--------------------------
-----AAFLGN---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------
*
>P1;ENSDARG00000055481

------------------MGDDRPFVCT-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GQART---------------------------DTVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFSEL--AGSFEQDLRKTH
-EEEERRIKGTH----------------------PA-LQT----------
--------PT-------------------EV----K-ER-EGPLEID---
---------------------------------------------SSPPD
SPDSASSM------------------------------------------
---------------TNSKDTVAMAKEAIALRKA----------------
KD---VPPRTAASSTPTPTIVRP---------------------------
GSLPLHQGF-DS-----------------------------MNPTQPSPT
SVITRTPPSNR--L------------------------------------
---SSPSGSFPMLMQLPNGQT--------------VPLLPSPGQ-TSVIS
--------------------------------LARSSNTVPNI-------
------------PGIPGPPIGGSSSGSSS---------------------
---------------PSGYSTHSDAKTRLK-----AALSQPSPSG-----
--------------------------------------------PAPIQK
-----------------------------------------------TDH
TETPSPAQPQVSPAPPKGGRRRRGADIEPDERRRRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKVWVSALE-------KR
--------------------------------------------------
------------AEE-----------------------------LANANV
---------------------------SLT-------------GEVSLLR
TEVTRLKELLLAHKDCPVTAMQKK--------------------------
-----A-YLAAGVDE-SSVSALVMPVTV-PAPV-----------------
-SVNGLS-----------------VRA-AEA-------------------
------------------------------VAVLAGMGSG-QWSN---SA
GDASSQSQPTS--R
*
>P1;ENSTRUG00000015923

------------------MGDDRPFVCS-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQD-----
--EDDKRAKHSI-------------PASNNVALDMS-LQT----------
--------PS-------------------DV----KVKK-EAPVEVD---
---------------------------------------------SSPPD
SPESISGN------------------------------------------
---------------SDHSRE--------ALVKA----------------
KD---TPP---RSSAPTPTIVRP---------------------------
GSLPLHLGF-DA-----------------------------LQPTMPSPT
SVITQAPPSNRTSL------------------------------------
---GSPTSHYPMM-MLPTGPA--------------LSVLPGPVHIPSVIN
--------------------------------LARPMCMVPNI-------
------------PGIPGPPLGGSSSGSNS---------------------
---------------PSGYSIHSEAKMRLK-----AALSQQSPSGHSMGI
--------------------------------------MSTGSSPMVPQR
A----------------------------------------EQNQLLVQQ
PDAPSPAQPQVSPAQPTGGRRRRTVDDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVFSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LGTLNI
---------------------------SLS-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKK--------------------------
-----TAYLAA--EG-NMKD-TSEPTGS-PAPVIQHSSL----APGPSL-
-GQNGLS-----------------SRAAAE--A-----------------
------------------------------MAVLAGMGHQ-QRAEGGTSH
IIMAAQSQSAA--R
*
>P1;ENSDARG00000011298

------------------MGDDKPFMCS-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQEFPKAQ
-EDEDKRAKNPL-------------PAPNSGAIDMS-LQT----------
--------PS-------------------DV----KVKE-EDPVEVD---
---------------------------------------------STPPT
SPDSISSM------------------------------------------
---------------SDSSKE--------PVGRG----------------
KD---SPPRHAFSSAPTPAIVRP---------------------------
GSLPLHLGY-DG-----------------------------LHPTMPSPT
SVITHTPPSNRT-L------------------------------------
---GSPTVPYPMM-MLPNGQT--------------VPVLPGPMQMPSVIS
--------------------------------LARPLCMVPNI-------
------------PGIPGPPLGGSSSGSSS---------------------
---------------PSGYNPHAEAKMRLK-----AALSQQTSSAQGCLG
--------------------------------------VAMGSSAMVPQR
V----------------------------------------EQSQLLVQH
PDAPSPAQPQVSPAQPTGGRRRRTADDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKIWVNSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LTSINV
---------------------------SLS-------------NEVSHLR
NEVAHLKQLLLAHKDCPVTNLQKK--------------------------
-----AAYLGD---E-HMKE-TSEPTGS-PAPVIQHSSL----APSPSSV
VGPNGLS-----------------SRAAAEAVA-----------------
------------------------------MSVLAGMGSQ-QGGSGGPSH
VIMATQSHPSS--R
*
>P1;ENSAMXG00000001508

------------------MGDDRPFVCS-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GQTRT---------------------------DTVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFSEL--DGSFEQELRKTQ
QEEEERRAKTAL----------------------SA-LQI----------
--------PS-------------------EM------ER-DGPLEID---
---------------------------------------------SSPPD
SPSSSSSM------------------------------------------
---------------TDSKDSVTMTKEPVALRKT----------------
KD---MPTRTTASSAPTPTIVRP---------------------------
GSLPLHLGY-DSS----------------------------MNPTQPSPT
SVITRTPPSNR--L------------------------------------
---SSPSGSFPVMMQLPNGQT--------------VPLLPSPGQ-TSVIS
--------------------------------LARSSNPVPNI-------
------------PGIPGPPIGGSSSGSSS---------------------
---------------PSGYSSHSDAKMRLK-----AALSPQSVSG-----
--------------------------------------------PLPTQK
-----------------------------------------------TEP
NETPSPAQPQVSPAPPRGGRRRRGAETEPDERRRRFLER-----------
--------------------------------NRAAAYRCRQ--------
-----------------------K--------RKVWVNALE-------KR
--------------------------------------------------
------------AED-----------------------------LATNNV
---------------------------TLT-------------NEVSLLR
GEVTRLKELLLAHKDCPVTAMQKK--------------------------
-----A-YLAAGVDE-SAVSALVLPVSV-PAPV-----------------
-SVNGLS-----------------VRA-AEA-------------------
------------------------------VAVLAGMGSG-QWSS---PA
GDVPSQSQPTS--R
*
>P1;ENSXMAG00000010537

------------------MGDDRPFVCN-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQD-----
--DEDKKAKNSL-------------PAANSAALDMS-LQT----------
--------SS-------------------DV----KVKR-ESPVEVD---
---------------------------------------------SSPPG
SPESISGK------------------------------------------
---------------SDSNQE--------PVVRG----------------
KD---TPP---RSSAPTPTIVRP---------------------------
GSLPLHLGF-DA-----------------------------LHPTMPSPT
SVITQAPPSNRT-L------------------------------------
---GSPTSHYPMM-MLPTGQA--------------VPVLPGPVQIPSVIN
--------------------------------LARPMCMVPNI-------
------------PGIPGPPLGGSSSGSNS---------------------
---------------PSGYSIHSEAKMRLK-----AALSQQSPSGQNLGS
--------------------------------------MVMGSSPMVPQK
A----------------------------------------EQSQLLVQH
PDAPSPAQPQVSPAQPTGGRRRRTADDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVSSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LSSLNV
---------------------------SLS-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKK--------------------------
-----TAYLAA--EE-SLKE-TSEPTGS-PAPVIQHSSL----APSPSA-
-IHNGLS-----------------TRAAAEAMA-----------------
------------------------------MSVLAGMGQQHQRVEGGPSH
IIMAAQSQSAA--R
*
>P1;ENSONIG00000011905

------------------MGDDRPFVCN-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQD-----
--DDEKRAKNSL-------------PASNSVALDMS-LQT----------
--------PS-------------------EV----KVKQ-EAPVEVD---
---------------------------------------------SSPPG
SPESSSGK------------------------------------------
---------------SDSNRE--------PIVKG----------------
KD---TPP---RNSAPTPTIVRP---------------------------
GSLPLHLGF-DA-----------------------------LQPTMPSPT
SVITQAPPSNRT-L------------------------------------
---GSPTSHYPMM-MLPSGQA--------------VPVLPGPVQMPSVIN
--------------------------------LARPMCMVPNI-------
------------PGIPGPPLGGSSSGSNS---------------------
---------------PSGYSIHSEAKMRLK-----AAL--QSPSGQSMGI
--------------------------------------MAMGSSPMVPQK
A----------------------------------------EQSQLLVQQ
PDAPSPAQPQVSPAQPTGGRRRRTTDDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVNSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LSTLNV
---------------------------SLS-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKK--------------------------
-----TAYLAA--EE-SMKD-TSEPTGS-PAPVIQHSSL----APSPST-
-GQNGLS-----------------SRAAAEAMA-----------------
------------------------------MSVLAGMGQQ-QRAESGPSH
IIMAAQSQSAA--R
*
>P1;ENSORLG00000018868

------------------MGDDRPFVCT-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLSV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQEFCKSQ
--DDEQRTKPPV-------------RTNHEQHIYHSVGQT----------
--------PS-------------------EV----KEED-EGPLQVD---
---------------------------------------------SSPPG
SPDSSSSM------------------------------------------
---------------SENSGD--------SGVRG----------------
QEMITKPL---ASSAPTPTIVRP---------------------------
GSLPLHLSN-DA-----------------------------LHPTLPSPT
SVITQAPPSNRQ-L------------------------------------
---GSPTSAYSLMRHLPNGQT--------------VPLLPSPVQMTSVIS
--------------------------------LARPVNTVANI-------
------------PGIPGPPVRGISSGSSS---------------------
---------------PSEFSLHSETKMRLK-----AALSQ-GPSAPDGAG
--------------------------------------IGSGSIPAVPQR
Q----------------------------------------EESQQPTPN
SDAPSPAQPQVSPAQPTGGRRRRAAEMDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVNSLE-------KK
--------------------------------------------------
------------AED-----------------------------LANMNV
---------------------------SLT-------------SEVTLLR
NEVAQLKQLLLAHKDCPVTVMQKK--------------------------
-----AAMLAAGGEE-HHGGISTEPVGS-AAGVIQHGPSPPASASSPRA-
-TINGLN-----------------VRA-AEAVA-----------------
------------------------------MSVLAGMGSG-Q-----AGG
VVMATQSQQSP--R
*
>P1;ENSGACG00000008417

------------------MGDDRPFVCS-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--DNSFDQD-----
--DEDKRAKNAL-------------PAPSSGAVDMS-MQT----------
--------AS-------------------DV----KVKE-EEPVEVD---
---------------------------------------------SSPPS
SPDSYSGD------------------------------------------
---------------SENYYE--------PLVRG----------------
KD---TPP---RISGPTPTIVRP---------------------------
GSLPLHLGF-DA-----------------------------LQPTMPSPT
SVITQAPPSNRN-L------------------------------------
---GSPTSHYPMM-MLPSGQA--------------VPVLPGPIQIPSVIN
--------------------------------LARTMSMVPNI-------
------------PGIPGPPLGGSSSGSNS---------------------
---------------PSGYSIHSEAKMRLK-----AALSQQSPSGYSMGM
--------------------------------------MAMGGSPMVPQR
A----------------------------------------EQSQLLVQH
PDAPSPAQPQVSPAQPTGGRRRRTAEDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKQWVSSLE-------RK
--------------------------------------------------
------------AEE-----------------------------LCTLNV
---------------------------SLS-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKR--------------------------
-----TAYLAV--EE-SMKD-NSEPTGS-PAPVIQHSSL----AHSPSA-
-GHNGLS-----------------SRAAAEAMA-----------------
------------------------------MSVLAGMGQQ-QRAESGPSH
IIMAAQSQSAA--R
*
>P1;ENSXMAG00000002160

------------------MGDDRPFVCT-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLSV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIQDQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--AGSFDQEFGKTQ
--EDDHRTKHPA----------------------AP-LQT----------
--------PS-------------------EV----KDED-ESSLQVD---
---------------------------------------------SSPPD
SPDSSSSM------------------------------------------
---------------SENSRD--------SR-------------------
-EFLSKPV---ASSAPTPTIVRP---------------------------
GSLPLHLTG-DP-----------------------------LHPTLPSPT
SVITQAPPSNRQ-L------------------------------------
---GSPTSAYPLVRHLPNGQT--------------VPLLPSPVQMTSVIS
--------------------------------LARTVNTVPNI-------
------------PGIPGPPIGGASSGSSS---------------------
---------------PSGYGLHSETKMRLK-----AALSHQGPAAQDGAG
--------------------------------------GGSGSIPAIPQR
Q----------------------------------------EQGQQPNQN
SDTPSPAQPQVSPAQPTGGRRRRASEMDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVNSLE-------KK
--------------------------------------------------
------------AED-----------------------------LANMNI
---------------------------SLT-------------NEVTLLR
NEVAQLKQLLLAHKDCPVTVMQKK--------------------------
-----AAFLAAGGEE-ASREAPTEHIGS-PAAVIQHVPSPATVASSPGP-
-TINGLS-----------------VRA-AEAVA-----------------
------------------------------MSVLAGMGSG-Q-----PGG
VVIAPQSQPTP--R
*
>P1;ENSAMXG00000004711

------------------MGDDKPFVCN-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--SMPFESEFRKAQ
-EDDDKRAKNPL-------------PAPGSSALDMT-LQT----------
--------PS-------------------DV---VKVKE-EELVEVD---
---------------------------------------------SSPPA
SPDSISSR------------------------------------------
---------------SDSNNE--------SYMRG----------------
KE---SPPRPPVSSAPIPTIVRP---------------------------
GSLPLHLGY-DA-----------------------------LHPTMPSPT
SVITQAPPSNRT-L------------------------------------
---GSPTGPYPMM-MLPNGQA--------------VPLLPGPVQMPSVIS
--------------------------------LARPMCMVPNI-------
------------PGIPGPPLGGGGSGSSS---------------------
---------------PSGYIPHSEAKMRLK-----AALSHQSSAAQGCVG
--------------------------------------VAMGSSAMVPQR
M----------------------------------------EQSQLLVQH
PDAPSPAQPQVSPAQPTGGRRRRTADDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKVWVNSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LTSMNV
---------------------------SLT-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKK--------------------------
-----AAYLGE--SE-HERR-SVN-----------HKS------------
--------------------------------------------------
--------------------------------------------------
--------------
*
>P1;ENSTRUG00000007560

------------------MGDDRPFVCN-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLSV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ASSFEQELCKAH
--EDDHRTKHPF-------------KA-------AP-LQT----------
--------PS-------------------EV----KIEN-EESLQVD---
---------------------------------------------SSPPD
SPDSSSSM------------------------------------------
---------------SDDSRD--------SRIKKSINNGILVHSGKIATN
NEILSKPV---ASSAPTPTIVRP---------------------------
GSLPLHLSN-DA-----------------------------LHPTLPSPT
SVITQAPPSSRQ-L------------------------------------
---SSPTSSYPLVRHLPNGQT--------------VPLLPSPVQLTSVIS
VSHHSGTTTSVNVPRGQIFYFHTYACLCYNVQLARPVNSVPNI-------
------------PGIPGPPVGGASSGSSS---------------------
---------------PSGYSLHTETKL-----------------------
--------------------------------------------------
--------------------------------------------------
----------VSPAQPTGGRRRRAAEMDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVNSLE-------KK
--------------------------------------------------
------------ADD-----------------------------LANMNV
---------------------------SLTATTLTRSHIVLLNSEVTLLR
NEVAQLKQLLLAHKDCPVTIMQKK--------------------------
-----AAFLGG--EE-PSRDVSSEATSS-PAAVIQHGPSPPTSVSSPGP-
-TINGLS-----------------VHA-AEAVA-----------------
------------------------------MSVLAGMGSG-Q-----PGA
INMAVQSQPAP--R
*
>P1;ENSTNIG00000015107

------------------MGDDRPFVCS-------------------APG
CGQRFTNED-----------------------------------------
--------------------------------------------HLAV--
--------------------------------------------------
--------------------------------------------------
---------------------HKHKH-----EMTLKF-------------
---GPART---------------------------DSVIIADQTPTPTRF
LKNC----------------------------------------------
-----------------EEV------------------------------
------------------------------GLFNEL--ANSFEQD-----
--EDDKRAKHSI-------------PAANSVALDMS-LQT----------
--------PS-------------------DV----KVKK-EAPVEVD---
---------------------------------------------SSPPD
SPESISGT------------------------------------------
---------------SDHSRE--------ALVKA----------------
KD---TPP---RISAPTPTIVRP---------------------------
GSLPLHLGF-DA-----------------------------LQPTMPSPT
SVITQAPPSNRTSL------------------------------------
---GSPTSHYPMM-MLPTGPG--------------LSVLPGPVHIPSVIN
--------------------------------LARPMCMVPNI-------
------------PGIPGPPLGGSSSGSNS---------------------
---------------PSGYNIHSEAKMRLK-----AALSQQSPSGHSMGV
--------------------------------------MATGSSPMVPQR
A----------------------------------------EQSQLLVQQ
P-APSPAQPQVSPAQPTGGRRRRTVDDDPDERRQRFLER-----------
--------------------------------NRAAASRCRQ--------
-----------------------K--------RKLWVFSLE-------KK
--------------------------------------------------
------------AEE-----------------------------LGTLNI
---------------------------SLS-------------NEVSLLR
NEVAHLKQLLLAHKDCPVTTLQKK--------------------------
-----SVYLAA--EE-TMKD-ASEPTGS-PAPVIQHSSL----APSPSS-
-GQNGLS-----------------SRAAAE--A-----------------
------------------------------MAVLAGMGQQ-QRPESGASH
IIMAAQSQSAA--R
*
>P1;ENSLOCG00000008620

------------------MGSRRGAALSLAMGILQLAALPAAGAPLPDPP
AGQLAAGELSLSLAVSVVGLLVLVFLLLNCTSCCKEQEIIFKEFEDNFED
EIDFTPPAEDTPSIQSPAEVYTLAVPPLALPGPPHLQASRTGEGSTGSQV
ARHSLSYIQEVGSGWFGKVLLSEIYTDPRPDRVVVKELKANANAKEQNDF
LQHGDPYRVLQHPNILQCLGQCVESIPFLLVFEYCDLGDLKGYLSQQEWI
YGSSELLQLQKMACEIAAGLAHLHKHNFLHSDLALRNCFLTTDLTVKVGD
YGIGPSRYKEDYISTEEELAVPLRWMAPELVAELHGGVVTADQTKPGNVW
ALGVTLWELFENATQPYPHLSDREVLIRVIKEQQTKPFKPQLELPYSDRW
YEVLQFCWLPPDKRATTEEVHRLLTYLRMQGQKESEDDFEQRWNALKPNP
SARPTTVSHSSFPILEQFVDDGPGRELDEVLTVTETSRGLSFEYVWEAAK
--HDHYNDRGPSCADTTLNYHSMFFPV-------PP-YEKPAALQTGAQR
GADGGAQAPSAGVPGVLPVFDAHKTATGSEYYIQLEEQG-EGSLEVDENQ
GPLGSREAPDRELPQDRQSQQYVVLRDIRLDESSTDVDFFHRSIDSKDSN
LPESQAGSSSDLESPYHTNIFRESATKLEDSGSWSRSFLELPELNGNRFQ
KGVSLEVGPESDLKTTEKSFGS--------SFLG----------------
DD---QEAVYLESTRESPDSVRLLNVEKLTDNFLFLKENNLMKDGETSSR
GTKALSVGFLDAELNGIPEPNFSEVSADSLDIKSSGKDEIAEKADLKSPS
TCEGDSVPSKKE-LLHFLSPGVNDPLQPLGNKETLLPSSSLIIGESCSDH
LQCKSSSSNEECV-VLNSSETETEFSLDSTSRRAEVPTSPSTYHQPTLFP
--------------------------------ESATNNILCNVAKTHSLE
EDLGAPEEDEPLAVIEDPANHGSLSGPSACDRKAALDIGLANEDSVSNTV
KDIQGNEQHVPSSLQPINDSEQKEALINFESNDISDDLSSHTTSAHCLDQ
ISQDSLLEDSMSTTMLTIEHSAETPDSLDSLDMHGMVGPAETLNTTAPQK
LQPPYKTADSGYETENLESPEWSSQSAVKDSSPEEYVPSISEEPAPVLL-
----PPPEIIISEVETMLGVEEEATATHPQDARAPGVELFSSANQNSYRD
SAYFSDNDSEPDKKLEEVSGSSTHEVCDSSDADIAVSARCTPGLDTAAAE
AGELAMALLEGRAAEAAVDRPQEDRAEEPRPVDRVGQNSLPELVLTTEED
WDREVPVSIDGSEELEGPDLEVLSGPESAAGVDPAGSTDPPRAAEPPDFA
EASFPASQLHSTGDTMLHEKLSLSHQGEGHKLKEPDIEGKYLGKLDSLTM
AGVLEDGMEADEEDENSDDSDDDMRAYHLH-------------STSSDSE
EDIVHPVPIIISNNDASAMNLKSRLKGSSPCGARPPPPEGDSELRRKAVS
FFDDVTVYLFD--QETPTKE-LGDPSSSRPDSRVSEFSS----PVSSSS-
-YLNRFTNSESSTDEEGGGFEWDDDFSSPEASFMSGAAGRLILAKTSPAA
SSRYFSPPPPTRAAEPSWASPSAYSRFSISPASLAGFSLT-HLTD---SD
IEQGGSSEDGEK-D
*
