>P1;ENSXMAG00000017409

MKERRLPQPFVARCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLVKDCYPEVFTPLEVEKLSVCNLELEDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDG---------------------
--------------------------------------------------
---ALKK-------------------------------------------
--------------------------------------------------
------------------------------------WKAEIQDFCPNTRI
LLIGCKTDLRTDVCTRMELSNQKQAPVSHEQGSSLAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
ALACMN------KLQPPNKPSPVRRLSKRLLHLPN---------------
--------KTDLLS----KDKSKSCSIM----------------------
------------
*
>P1;ENSGACG00000008549

MKERRNNQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELEEQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDS---------------------
--------------------------------------------------
---SLKK-------------------------------------------
--------------------------------------------------
------------------------------------WKTEILDFCPSTRI
LLIGCKTDLRTDVCTLMELSNQKQTPITYEQGSAMAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
AMACIN------KLQPLPKPSPTRRLSKRLLHLPS---------------
--------KSDLLSSTFKKEKTKSCSVM----------------------
------------
*
>P1;ENSDARG00000004218

MKERRNAQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELDDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDIFDS---------------------
--------------------------------------------------
---GLKK-------------------------------------------
--------------------------------------------------
------------------------------------WRAEILDFCPSTRI
LLVGCKTDLRTDVCTLMELSNQKQTPITHEQGSAMAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
ALACIN------KLQPLAKPSPTRRLSKRLLHLPS---------------
--------KSELLSSTFKKEKAKSCSVM----------------------
------------
*
>P1;ENSTRUG00000015649

MKERRNTQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELEEQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDS---------------------
--------------------------------------------------
---SLKK-------------------------------------------
--------------------------------------------------
------------------------------------WKTEILDFCPSTRI
LLIGCKTDLRTDVCTLMELSNQKQTPVTYEQGSALAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
AMACMN------KLQALPKNSPTRRLSKRLLHLPS---------------
--------KSDLLSSTQEGEDQELLSDVSGELTVDSDRITPSPSPSLVLG
KGGGHGFIRASC
*
>P1;ENSAMXG00000004513

MKERRNTQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELDDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVES---------------------
--------------------------------------------------
---GLKK-------------------------------------------
--------------------------------------------------
------------------------------------WRTEIMDFCPNTRI
LLIGCKTDLRTDVCTLMELSNQKQTPITHEQGSAMAKQLGAETYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
ALACIN------KLQPLAKPSPSRRLSKRLLHLPS---------------
--------RSELLSSTFKKEKAKSCSIM----------------------
------------
*
>P1;ENSONIG00000011943

MKERRNTQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELEEQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDS---------------------
--------------------------------------------------
---SLKK-------------------------------------------
--------------------------------------------------
------------------------------------WKTEILDFCPSTRI
LLIGCKTDLRTDVCTLMELSNQKQTPITYEQGSAMAKQLGAEAYL-----
ECSAFTSEKSIHSIFR--------------------------------TA
AMACIN------KLQPLPKPSPTRRLSKRLLHLPS---------------
--------KSDLISTTFKKEKAKSCSVM----------------------
------------
*
>P1;ENSTNIG00000015099

MKERRNTQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELEDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDG---------------------
--------------------------------------------------
---SLKK-------------------------------------------
--------------------------------------------------
------------------------------------WKTEILDFCPSTRV
LLIGCKTDLRTDVCTLMELSNQKQTPVTYEQGSALAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
AMACMN------KLQALPKNSPTRRLSKRLLHLPS---------------
--------KTDLLS-SFKKEKTKSCSVM----------------------
------------
*
>P1;ENSORLG00000012314

MKERRTPQPCVARCKLVLVGDV-------QCGKTAMLQ------------
--------------------VFVKDSYPETYVPTVFENYTAS-LDLEDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDA---------------------
--------------------------------------------------
---ALKK-------------------------------------------
--------------------------------------------------
------------------------------------WKAEIQDFCPSTRV
LLIGCKTDLRTDVCTRMELSHQKQAPISQEQGSCFAKQLGAAAYL-----
ECSAFTSEKSIHSVFR--------------------------------SA
ALACTN------KLQVAEKLSPVRRLSKRLLHLPS---------------
--------KTELLSSSFSKDKSKSCSIM----------------------
------------
*
>P1;ENSGACG00000003002

MKERRLAQPRVARCKLVLVGDV-------QCGKTAMLQ------------
--------------------VVAKDCYPETYVPTVFENYTSC-LELEDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDAVDG---------------------
--------------------------------------------------
---ALKK-------------------------------------------
--------------------------------------------------
------------------------------------WKAEIRDFCPSTRI
LLIGCKTDLRTDVCTRMELSNQKQTPVSHEQGSSLAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
ALACLN------QLQPADKPSPVRRLSKRLLHLPS---------------
--------KTELLSSTFGKDKSRSCSVM----------------------
------------
*
>P1;ENSONIG00000017051

MKERRLTQPFVGRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLVKDCYPETYVPTVFENYTAC-LELEDQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDG---------------------
--------------------------------------------------
---ALKK-------------------------------------------
--------------------------------------------------
------------------------------------WKAEIQDFCPSTRI
LLVGCKTDLRTDVCTRMELSNQKQAPISHEQGSSLAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
ALACMN------KLQPANKPSPVRRLSKRLLHLPS---------------
--------KTELLSSTFSKDKSKSCSIM----------------------
------------
*
>P1;ENSXMAG00000010632

MKERRNTQPLVVRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LELEEQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTMDS---------------------
--------------------------------------------------
---SLKK-------------------------------------------
--------------------------------------------------
------------------------------------WKSEILDFCPSTRI
LLIGCKIDLRTDVCTLMELSNLKQTPITYEQGSAMAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
AMACIN------KLQPLPKSSPTRRLSKRLLHLPS---------------
--------KSDLLSSSFKKEKTKSCSVM----------------------
------------
*
>P1;ENSTRUG00000000426

MKERRLTQPFVARCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAC-LEVEEQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDSDAVLLCFDISRPDTVDT---------------------
--------------------------------------------------
---ALKK-------------------------------------------
--------------------------------------------------
------------------------------------WKAEIQDFCPSTRI
LLIGCKTDLRTDVCTRIELSNQKQTPISHEQGSSLAKQLGAEAYL-----
ECSAFTSEKSIHSVFR--------------------------------TA
ALACMN------KIQPASKSSPDRRLSKRLLQLPS---------------
--------KTDL-SSTFSKDKSRSCNIM----------------------
------------
*
>P1;ENSDARG00000030547

MKERRISQPLVMRCKLVLVGDV-------QCGKTAMLQ------------
--------------------VLAKDCYPETYVPTVFENYTAG-LELEEQR
VE------------------------------------LSLWDTSGSPYY
DN------------------------------------------------
--------------------------------------------------
---VRPLCYSDADAVLLCFDISRPDTVES---------------------
--------------------------------------------------
---SLKK-------------------------------------------
--------------------------------------------------
------------------------------------WKAEIMDFCPSTRI
ILVGCKTDLRTDVCTLMELSNQRLTPISHEQGTLLAKQVGAEVYL-----
ECSAFTSEKSIHSVFR--------------------------------SA
SLTCLN------KLQPPIKQSPTRRLSKRLLHLPS---------------
--------KAELLTSSFSKERTKSCTII-----------SLCP-------
------------
*
>P1;ENSLOCG00000008458

MWGPGGRRPLLGDSSRSF-GPVFRTELAGRRGDSLALQFAEEEEDDDDLQ
FDTSDSPEQCEAVEKYSAIKEFASAIPNQLLLGSLLEHLCCV-YEKEPHR
SHLLFKVISQQLAAMNLLSPLAFSDEFSTVRLQHNRAFTELLRAASSTIH
SQDRRLLGKGAQGHTVRSKEDLFQRQTSRYLSEFEEISKLGKGSYGKVFK
VKNKLDGQYYAVKKILIKKATRNDCMKVLREVKVLAGLQHANIVGYHTAW
MEHVQPAGKSTASLHNNLLALERPSQMEDGEESSNSSNGVSVVFESSAAS
KKAKEDVAMPKPLPQDSQGTGAQRQEQKPAVCPKGMHNPKGSIPCVYLGP
SGQAAEGWDGAVLAEEGCSRDKLNLQSSCLEGDSQTWSSVCPLREACVHR
SSEVQYHLMLYIQMQLCESSLMDWILERNERPAADSTAAASGYSLVDTKL
TMSILGQILEGVQYIHSRGVMHRDLKPRNIFLHGRDCRVRIGDFGLACRD
MIVDDSGPSFPDTCT---------------IGSAHTTGVGTYVYAAPEQR
EGSRYDYKSDMYSVGIIALELFQPVRTEMERARTLEQLRVGTIPEAFAQR
WPVLAKYIQRLISPDPALRPSAAQLLQSELFHHTDEVIHSLQRKVAEQEV
EIVQLRRQISELLQAQRSEDPR----------------------------
------------
*
