>P1;ENSXMAG00000011880

M-----SF--SGEAMLKAVEAPLFWLGVLTAAWLSVCSVYRLLSGFRVWV
LGNGRLISPNKLGKWAVVTGATDGIG----KAYAEEL-ARRGFAIV-LIS
RSQEKLDDVSKAIASKCG--VETKTIAADFSAIDIYAKIEEGL-------
-------------------------------------------AGLEIGL
LVNNVGTSYSYPEFFLNI----------------------PNLDT-----
---------------FID--------------------TMININITSV--
---------CQMTRLVLPQ--MVERKKGAILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SASKA--FVDFF---SRGLQAEYKSKGIIIQSILPFFVATKMSRIRRPTL
DRPSPEH-----------------YV--------AAELNTVGLQTQTNGY
LPHAIMGWVTTALL-------PAKMLNSY---------------------
------------------VMGMGLSQRARYL-------------------
-------------------------------------------------K
KQKQ-----------------------------------------G----
-------------------------------------
*
>P1;ENSAMXG00000013705

I-----EVFSELEKMLHGAESVLLWVGALTTASLALWILYRLLSGFRIWV
MGNGDLLSP-KLGKWAVVTGATDGIG----KSYAEEL-ARRGFSMM-LIS
RTQEKLDDVAQSLERRYK--VETKTVAVDFGQVDIYPKIETAL-------
-------------------------------------------SGLEIGV
LVNNVGISYPYPEFFLHI----------------------PDLDN-----
---------------FIN--------------------TMINVNITSV--
---------CQMTRLVLPR--MEARAKGVILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SSTKA--FVDFF---SRGLQAEYKSKGIIIQSVLPFFVATKMTKIRKPTL
DKPTPDR-----------------YV--------AAELTTVGLQDQTNGY
FPHAVMGWLTTVLV-------PINLVIYF---------------------
------------------GMRMNKAQRGGYL-------------------
-------------------------------------------------R
RRKLR---------------------------------------------
-------------------------------------
*
>P1;ENSTRUG00000016257

V-----NTMSTGEALLRAAEAPLFWLGALTASWASLCLVYRLLSGFKVWV
LGNGRFMSPHKLGKWAVVTGATDGIG----KAYAEDL-ARRGFAIV-LIS
RSQDKLDELSKAIASKCG--VETKTIAADFSCLDIYSKIEAGL-------
-------------------------------------------AGLEIGV
LVNNVGISYSYPEFFLDV----------------------PNLDT-----
---------------VSD--------------------SVISGLFVAI--
---------FPLAHVSLLS---VCRKRGAILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTIY
SASKA--FVDFF---SRGLQAEYKSRGIVIQSVLPFFVVTKMSKIRRPTL
TAPSAEH-----------------YV--------SAELNTVGLQTQTNGY
LPHAIMGWVTTALL-------PAKILTGH---------------------
------------------IMRMNLSMRAYNL-------------------
-------------------------------------------------K
KQKE-----------------------------------------K----
-------------------------------------
*
>P1;ENSGACG00000006929

M-----QTCS--EQGF-PLKKQQAWLIVMFSLFRGMWLFLFLLSSSADSL
RPPRGLRRP-N-SRGIIVTGATDGIG----KSYAEEL-ARRGFAMM-LIS
RSQDKLDDVAMSLKEQFK--VETRTIAADFGKTDIYNKIEAGL-------
-------------------------------------------AGLEIGV
LVNNVGVSYPYPEYYLQI----------------------PDLDN-----
---------------FIT--------------------NMINVNITSV--
---------CQMTRLVLPK--MTERSKGVILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTAY
SSTKA--FVDFF---SRGLHEEYRRQGIIIQSVLPFFVVTKMTRIKKPTL
DKPTPDR-----------------YV--------AAELATVGLQDQTNGY
FPHAVMGWLTTKLV-------PMKLVIFF---------------------
------------------GARMNRLQRTGYL-------------------
-------------------------------------------------Q
RKKLR-----------------------------------EQ--------
-------------------------------------
*
>P1;ENSTNIG00000009599

--------------------------------------------------
-------------SFIVVTGATDGIG----KAYAEDL-ARRGFAIV-LIS
RSQDKLDEISKAISSKCG--VETKTIAADFSCLDIYSKIEAEL-------
-------------------------------------------AGLEIGV
LVNNVGISYSFPEFFLDV----------------------PNLDT-----
---------------FID--------------------TMVNINIMSV--
---------CKMTHLVLPQ--MVERKRGAILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SASKA--FVDFF---SRGLQAEYKSRGVVIQSVLPFFVATKMSKIRRPTL
TVPSPES-----------------YV--------SAALSTVGLQTQTNGY
LPHAIMGWVTTALL-------PAKILTGH---------------------
------------------VMRMNLSMRAYNL-------------------
-------------------------------------------------K
RQKDK-----------------------------------Q----K----
-------------------------------------
*
>P1;ENSTNIG00000010384

V-----------EETLRAAEAPLFWVGACTVASLALWLLYRLVSGFRIWV
LGNGSLLSP-KLGKWAVVTGATDGIG----KSYAEEVRAAPGVALAWQIS
RSQEKLADVAATLKELYS--VETKTIAVDFGRSDIYSKIEEGL-------
-------------------------------------------AGLEIGV
LVNNVGVSYSYPEYYLHI----------------------PDLEN-----
---------------FIT--------------------NMIHVNVTSV--
---------CQMTRLVLPR--MADRSRGVILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SATKA--FVDFF---SRGLQEEYRRQGIIIQSVLPFFVATKMTRIRKPTL
DKPTPER-----------------YV--------AAELSTVGLQSQTNGY
FPHAVMGWVTTKLV-------PSSIVIFL---------------------
------------------GARMNRLQRTGYL-------------------
-------------------------------------------------Q
RRRL----------------------------------------------
-----------------R-------------------
*
>P1;ENSORLG00000001004

M-----SS--SGEAVLRAVEVPLFWLGAVTAVWLSFCSVYRLLSGLRVWV
LGNGRLVSPNRLGKWAVVTGATDGIG----KAYAEEL-ARRGFSIV-LIS
RSQEKLDEVSKAIAGKCG--VETKTIAVDFSSVDIYPKIEAGL-------
-------------------------------------------AGLEIGV
LVNNVGISYSHPEFFLNV----------------------PNLDT-----
---------------FID--------------------TMVNINITSV--
---------CQMTRLVLPR--MVERKKGAILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTIY
SASKA--FVDFF---SRGLQAEYKSKGIIIQSVLPFFVATKLSKIRRATL
DKPNPDR-----------------YV--------AAEINTVGLQTQTNGY
LPHAVMGWVTTALL-------PAKMLTSY---------------------
------------------MMGMGLSQRARYL-------------------
-------------------------------------------------K
KQKQ-----------------------------------------G----
-------------------------------------
*
>P1;ENSDARG00000015709

M-----ESFN-VVETLQPAERALFWVGALITASLALYVVYKTITGFRIWV
LGNGDLLSP-KLGKWAVVTGATDGIG----KSYAEEL-ARRGFSMM-LIS
RSQEKLDDVAKSLESTYK--VETKTIAVDFSQIDVYPKIEKGL-------
-------------------------------------------AGLEIGI
LVNNVGISYSYPEFFLHI----------------------PDLEN-----
---------------FIT--------------------TMINVNITSV--
---------CQMTRLVLPR--MEARAKGVILNISSASGM-FPVPL-----
--------------------------------------------------
----------------------------------------------LTIY
SSTKAIAFVDFF---SRGLQTEYKCKGIIIQSVLPFFVATKMTKIRKPTL
DKPTPER-----------------YV--------AAELNTVGLQDQTNGY
FPHAVMGWVTTILA-------PIDLVLNL---------------------
------------------GLRMNKAQRGGYL-------------------
-------------------------------------------------R
RRKLR---------------------------------------------
-------------------------------------
*
>P1;ENSGACG00000017131

M-----WS--AGEAALRAAETPLLWLGALTAAWLSVCSVYRLLSGIRVWG
LGNGRLVSPDKLGKWAVVTGATDGIG----KAYAEEL-ARRGFCIV-LIS
RSQEKLDDVSKFISSKCG--VETRTIVADFSALDIYSRIEDGL-------
-------------------------------------------VGLEIGV
LVNNVGISYSYPEFFLNV----------------------PSLDT-----
---------------FID--------------------TMVNVNMTSV--
---------CQMTRLVLPG--MVERKKGAILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SASKA--FVDFF---SRGLQAEYKSKGIIIQSVLPFFVATKLSKIRRATL
DKPSPER-----------------YV--------SAELNTVGLQAQTNGY
LPHAVMGWVTTSLL-------PAAILNSH---------------------
------------------VMGMGLSQRARYL-------------------
-------------------------------------------------K
KQKQ-----------------------------------------G----
-------------------------------------
*
>P1;ENSDARG00000035872

M-----EP----------FADALFWVGAVTVLWLSVSSLWSLINGIRVWI
LGNGNLMRASSLGKWAVVTGATDGIG----KAYAEEL-ARRGFAIV-LIS
RTQEKLDEVSKAIESKYK--VETKTISADFGSVDIYPKIESGL-------
-------------------------------------------AGLEIGV
LVNNVGVSYSYPEFFLNI----------------------PDVDS-----
---------------FIN--------------------NMININIMSV--
---------CQMTRLVLPR--MVDRSKGVILNVASASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTLY
SSTKA--FVDFF---SRGLDAEYKSKGIIIQSVLPFYVTTKLSKIRKPTL
DIPTPER-----------------YV--------KAQLSTIGLQTQSNGY
LPHAIMGWVTASLL-------PAKLLNKY---------------------
------------------VMGMGLSQRARYL-------------------
-------------------------------------------------K
KQKQD-----------------------------------S----L----
---------SFILEL--A-------------------
*
>P1;ENSONIG00000015599

V-----NWMN-VEEMISWAETPLFWVGAFTVASLTLWLLYRLLTGFRIWV
LGNGQLLSP-KLGKWAVVTGATDGIG----KSYAEEL-ARRGFAMM-LIS
RSQEKLDDVARSIEEQFK--VETRTIAVDFGKTDIYPKIEEGL-------
-------------------------------------------AGLEIGV
LVNNVGVSYPYPEYYLHI----------------------PDLEN-----
---------------FIT--------------------NTINVNMTSV--
---------CQMTRLVLPR--MCERSKGVILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SATKA--FVDFF---SRGLQEEYRRRGIIIQSVLPFFVATKMTRIRKPTL
DKPTPER-----------------YV--------AAELTTVGLQSQTNGY
FPHAVMGWATTRLV-------PSSIVIFL---------------------
------------------GARMNRLQRTGYL-------------------
-------------------------------------------------H
RRKLR---------------------------------------------
-------------------------------------
*
>P1;ENSAMXG00000011213

--------------------------------------------------
--------------------------------------------------
-------------ESKYK--VQTKTISADFGCVDIYPKIQAGL-------
-------------------------------------------ANLQIGI
LVNNVGVSYSYPEFFLNV----------------------PNLDN-----
---------------VIS--------------------SMININISSV--
---------CQVSTSLQTRICFVLRSKGVILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTLY
SSSKA--FVDFF---SRALDAEYKSKGVIIQSVLPFYVTTKLSKIKRASL
DIPTPER-----------------YV--------RSQISTVGLQNQTNGY
LPHAVMGWVTTALL-------PARLVSNL---------------------
------------------VMKMGLSQRARYL-------------------
-------------------------------------------------K
KQKQG---------------------------------------------
-------------------------------------
*
>P1;ENSONIG00000005893

MCSAAMSF--SGEAVFRAVEAPLFWLGALTAAWLSLCTVYRLLSGFRVWV
LGNGRLLSPAKLGKWAVVTGATDGIG----KAYAEEL-ARKGFAIV-LIS
RSQEKLDDVSKAIASKCG--VETKTIQADFSAVDIYSKIEGGL-------
-------------------------------------------TGLEIGV
LVNNVGMSYPYPEFFLSV----------------------PNVDT-----
---------------FID--------------------TLVNINITSV--
---------CQMTRLVLPQ--MVERKKGAILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SASKA--FVDYF---SRGLQAEYKSKGIIIQSVLPFFVATKLSKIRRATL
DKPSPER-----------------YV--------ASQLNTVGLQTQTNGY
LPHAIMGWVTTALL-------PAKILNSY---------------------
------------------LMGMSLSQRARYL-------------------
-------------------------------------------------K
KQKQ-----------------------------------------G----
-------------------------------------
*
>P1;ENSTRUG00000015387

--------------------------------------------------
---------------------------------------------M-LIS
RSQEKLDDVARMLQELYN--VETKTIAVDFGKSDIYCRIEAAL-------
-------------------------------------------AGLEIGV
LVNNVGVSYSYPEYYLHI----------------------PDLEN-----
---------------FIS--------------------NMINVNMTSV--
---------CQMTRLVLPR--MAERSKGVILNISSASGM-YPVPL-----
--------------------------------------------------
----------------------------------------------LTVY
SATKA--FVDFF---SRGLQEEYRRQGIIIQSVLPFFVATKMTRIRKPTL
DKPTPDR-----------------YV--------AAELSTVGLQSQTNGY
FPHAIMGWVTTKLV-------PSSIVIFL---------------------
------------------GARMNRLQRTGYL-------------------
-------------------------------------------------Q
RRRLR-----------------------------------EQRN-G----
------------TGLKSE-------------------
*
>P1;ENSORLG00000001421

M-----NRMN-AEEMIRRAEPLFFWVGAFTLAFFALWLLYRLVTGFRIWV
LGNGTLLSP-KLGKWAVVTGATDGIG----KSYAEEL-ARRGFAMM-LIS
RSQEKLDDVAKSLEEQFG--VETKTIAVDFGKTDIYPKIEAGL-------
-------------------------------------------VGLEIGV
LVNNVGVSYHYPEYYLNI----------------------PDLDN-----
---------------FLT--------------------NMINVNMTSV--
---------CQMTRLVLPG--MVSRAKGVILNISSASGM-YPLPL-----
--------------------------------------------------
----------------------------------------------LTVY
SATKA--FMDFF---SRGLQEEYRRQGIIIQSVLPFFVATKMTRIRKPTL
DKPTPER-----------------YV--------AAELTTVGLQNQTNGY
FPHAVMGWVTTKLV-------PTSIVIFL---------------------
------------------GASMNRVQRSGYL-------------------
-------------------------------------------------H
RRKLR-----------------------------------EMKN-G----
------------ASLKSE-------------------
*
>P1;ENSLOCG00000003780

M-----EMERLGNPGPKAAPKSNKLLKAMLAVFVCLSLV--LL-------
---------------AVIILASRGSINLQSEEYCSTL-ECIEAAGS-IIS
KMDTSVPPCADFYQYACGGWLHDNTIPEDSSSYGIYPWLRQNVDIKLKEL
LEKPIDPREIEAIRKAKVLYRSCMNETAIEMEDAKPLLALLRRSELRWPV
LGGSLGPQWQWEERRFSLADTLALLRGQHSKSVLLRMYVAPDDKNSNQYI
IKLDQASLSLSSREDYITNTTEAELYRQALLKLMTDVAVMLGANQYDAAT
QMKDVLEFEIKLAEILIP---FENRTSEAMYNKYSLSRLQRTVPQFNWLE
YIKAVVDTRLYPELRSLTSSEQVIVRVPQYFKDLFKLLETTDKRTVANYI
MWATVYSRITTLSRRFLYRYLDFARVTTGTTSLTPRWDKCVNYVESTLIY
ATGRM--FVDEHFQEDKKLMMEELTEGIRWAFI--DMLEKENDWMDRETK
NKAKEKAYAVLAKVGYPDFIMNNTYINEDLKMLEFSEKDYFGNVLQTLQY
IAQSDIGWLRKSVPRTQWFTNPTTVNAFYSSTTNQIRFPAGELQKPFFWG
LKYPRSLSYGAIGVIVGHELTHGFDNNGRKYDKDGNLDQWWTDASTANFN
KKTQCMVEQYNDYYWKEAGMNVRGKRTLAENIADNGGIRQAFRAYRKWVN
EERSGKEEPLLPGVGLTNDQLFFLSYAHVRCNAYRREAARDQIQSGAHSP
PKYRVIGAMSNYEEFRKAFNCPETSLMNRGSRSCRVW
*
