>P1;ENSTNIG00000017347

-------------------------------------GEASMFQLPI-LN
FSPQQVAGV-------------------------CETLEESGDV-ERLGR
FLWSLP--------------------VA----------------------
-----P---------AA---------------------------------
------------CEVL------NKN----------ESVLRARAVVAFHTG
NFRELYH--------ILENHKFT-KESHTKLQALWLEA------------
-------------------------------------------------H
YQEAEKLRGRPLGPVDK---YRVRKKFPLPRTIWDGEQKTHCFKERTRHL
LREWYLQDPYPNPSKKRELAQATGLTP-TQVGNWFKN--RRQRDRAAAAK
NRLQQQV--LS-GGS-------------------GCS-----L-ADE---
-------DATVDRLGN-SSSPEAN---LSSKAA-------ASA-------
----------I-SITSSDSECD----I
*
>P1;ENSDARG00000025187

-----------------------------------------MFQLPI-LN
FSPQQVAGV-------------------------CETLEESGDV-ERLGR
FLWSLP--------------------VA----------------------
-----P---------SA---------------------------------
------------CDVL------GKN----------ESVLRARAVVAFHAG
NFRELYH--------ILENHKFT-KDSHAKLQALWLEA------------
-------------------------------------------------H
YQEAEKLRGRPLGPVDK---YRVRKKFPLPRTIWDGEQKTHCFKERTRHL
LREWYLQDPYPNPSKKRELAQATGLTP-TQVGNWFKN--RRQRDRAAAAK
NRLQQQV--LS-GGS-------------------VRS-----L-GDD---
-------DTTVDRLGP-ASSPEVS---LSSKAA-------TSA-------
----------I-SITSSDSECD----I
*
>P1;ENSGACG00000008430

--------------------------------------EASMFQLPI-LN
FSPQQVAGV-------------------------CETLEESGDV-ERLGR
FLWSLP--------------------VA----------------------
-----P---------AA---------------------------------
------------CEVL------NKN----------ESVLRARAVVAFHTG
NFRELYH--------ILENHKFT-KESHTKLQALWLEA------------
-------------------------------------------------H
YQEAEKLRGRPLGPVDK---YRVRKKFPLPRTIWDGEQKTHCFKERTRHL
LREWYLQDPYPNPSKKRELAQATGLTP-TQVGNWFKN--RRQRDRAAAAK
NRLQQQV--LS-GGS-------------------VRS-----L-ADD---
-------DGTVDRLGN-SSSPEAS---LSSKAA-------ASA-------
----------I-SITSSDSECD----I
*
>P1;ENSTRUG00000010571

---------------------GGGRKNEETGGGEGNTGEASMFQLPI-LN
FSPQQVAGV-------------------------CETLEESGDV-ERLGR
FLWSLP--------------------VA----------------------
-----P---------AA---------------------------------
------------CEVL------NKN----------ESVLRARAVVAFHTG
NFRELYH--------ILENHKFT-KESHTKLQALWLEA------------
-------------------------------------------------H
YQEAEKLRGRPLGPVDK---YRVRKKFPLPRTIWDGEQKTHCFKERTRHL
LREWYLQDPYPNPSKKRELAQATGLTP-TQVGNWFKN--RRQRDRAAAAK
NRLQQQV--LS-GGS-------------------GCS-----L-ADE---
-------DATVDRLGN-SSSPEAS---LSSKAA-------ASA-------
----------I-SITSSDSECD----I
*
>P1;ENSORLG00000015761

-----------------------------------------MSILPS-FG
FTQEQVACV-------------------------CEVLQQGGNL-ERLGR
FLWSLP--------------------A-----------------------
--------------------------------------------------
------------CDHL------HKN----------ESVLKAKAVVAFHRG
NFRELYK--------ILESHQFS-PHNHPKLQQLWLKA------------
-------------------------------------------------H
YVEAEKLRGRPLGAVGK---YRVRRKFPLPRTIWDGEETSYCFKEKSRGV
LREWYTHNPYPSPREKRELAEATGLTT-TQVSNWFKN--RRQRDRAAEAK
ERENSEN--NN-AGGNKQNQLSPLD--------GGKSLMS--S-SEDEFS
PPQSPDQNSALLLQGN-MNHPGAS---AYPMSG----LGAPQSVHGMHGH
PHQLQ--DSLLGPLTSSLVDLG----S
*
>P1;ENSAMXG00000019354

-----------------------------------------MSMLPS-FG
FTQEQVACV-------------------------CEVLQQGGNL-ERLGR
FLWSLP--------------------A-----------------------
--------------------------------------------------
------------CDHL------HKN----------ESVLKAKAVVAFHRG
NFRELYK--------ILESHQFS-PHNHPKLQQLWLKA------------
-------------------------------------------------H
YIEAEKLRGRPLGAVGK---YRVRRKFPLPRTIWDGEETSYCFKEKSRGV
LREWYTHNPYPSPREKRELAEATGLTT-TQVSNWFKN--RRQRDRAAEAK
ERENSEN--NN-SGANKQSQLSPLD--------GGKSLMS--S-SDEEFS
PPQSPDQSSVLLLQGN-MSHPGAP---AYTMSG----LGATQTVHGMQGH
PHQLQ--DSLLGHLTSSLVDLG----S
*
>P1;ENSGACG00000002799

MVFRSPLDFFSASRILRPHFADGPPTQARSRSPEDPPSACPPLALPG-LC
FSAAQIASV-------------------------CETLEETGDI-ERLAR
FLWSLP--------------------VT----------------------
-----A---------DG---------------------------------
------------RDSI------SEH----------ESVQRARAVVAYHTG
SFRELYH--------ILETHRFT-RTSHGKLQAMWLEA------------
-------------------------------------------------H
YREAEKLRGRPLGPVDK---YRVRKKFPLPRTIWDGEQKTHCFKERTRGL
LREWYLQDPYPNPGKKRELAHATGLTP-TQVGNWFKN--RRQRDRAAAAK
NRLQHHR--MC-PDG-------------------ARS-----F-SG----
---------------G-ECSPDGS---GERADG-------ETL-------
----------L-SVTDSDSDLD----V
*
>P1;ENSAMXG00000021319

--------------------------------------RAPMLHLPA-LS
FSPQQVARV-------------------------CETLEESGDV-ARLSR
FLWALP--------------------P-----------------------
--------------------------------------------------
-------------DPQ------RET----------EAVVRARAVVAFHAG
EYGELYR--------LAQSRSFSTPESRASLQRLWLEA------------
-------------------------------------------------R
YREAESARGRPLGAVDR---YRVRRKFPPPPTVWDGERRAHCFRERARRV
LRQSYLREPYPDTRAKSELARATGLTA-TQVGNWFKN--RRQRDRAAA--
NRIQAEV--LS-GGS-------------------VHS-----LLGDD---
-------EGPVDPLSD-SSGLGPS---NNVTVA-------FST-------
----------V-SISSSDSECE----V
*
>P1;ENSONIG00000020118

-----------------------------------------MSILPS-FG
FTQEQVACV-------------------------CEVLQQGGNL-ERLGR
FLWSLP--------------------A-----------------------
--------------------------------------------------
------------CDHL------HKN----------ESVLKAKAVVAFHRG
NFRELYK--------ILESHQFS-PHNHPKLQQLWLKA------------
-------------------------------------------------H
YVEAEKLRGRPLGAVGK---YRVRRKFPLPRTIWDGEETSYCFKEKSRGV
LREWYTHNPYPSPREKRELAEATGLTT-TQVSNWFKN--RRQRDRAAEAK
ERENSEN--NN-AGGNKQNQLSPLD--------GGKSLMS--S-SEDEFS
PPQSPDQNSALLLQGN-MSHPGAS---AYPMSG----LGAPQPVHGMHGH
PHQLQ--DSLLGPLTSSLVDLG----S
*
>P1;ENSXMAG00000013923

-----------------------------------------MFPLPM---
FTPDQVARV-------------------------CENLEETGDI-ERLGR
FLWSLP--------------------AA----------------------
-----VPG-------SA---------------------------------
------------GEAL------NRH----------ESVMRARALVAFHTG
NFEALYQ--------ILQSHRFT-RESHAKLQDLWLDA------------
-------------------------------------------------H
YREAERLRGRPLGPVEK---YRIRKKFPLPRTIWDGEQKTHCFKERTRSL
LREWYLQDPYPNPSRKRHLAQATGLTP-TQVGNWFKN--RRQRDRAASAK
NRLQQDPSVLPSEGSTD-GALQERHPHPHLLPTSPRHLGSPEA-SDC---
-------STETERRGTGASTPEIS---VS---------------------
----------------SDGEFE----S
*
>P1;ENSDARG00000026473

-----------------------------------------MSMLPS-FG
FTQEQVACV-------------------------CEVLQQGGNL-ERLGR
FLWSLP--------------------A-----------------------
--------------------------------------------------
------------CDHL------HKN----------ESVLKAKAVVAFHRG
NFRELYK--------ILESHQFS-PHNHPKLQQLWLKA------------
-------------------------------------------------H
YIEAEKLRGRPLGAVGK---YRVRRKFPLPRTIWDGEETSYCFKEKSRGV
LREWYTHNPYPSPREKRELAEATGLTT-TQVSNWFKN--RRQRDRAAEAK
ERENSEN--NN-TGANKQNQLSPLD--------GGKSLMS--S-SEDEFS
PPQSPDQNSVLLLQGN-MSHPGAS---AYSMTG----LGAAQSVHGMQGH
PHQLQ--DSLLGPLTSSLVDLG----S
*
>P1;ENSLOCG00000005729

-----------------------------------------MSALRKKFG
D-DYQVVTTSSSGSGFNHPAPKRKRQRFVDKNGRCNV--QHGNLGSETSR
YLSDLFTTLVDLKWRWNLFIFILTYTVAWLFMASMWWVIAYIRGDLNRAH
DDKYTPCVANVYNFPSAFLFFIETEATIGYGYRYITDKCPEGIILFLFQS
ILGSIVDAFLIGCMFIKMSQPKKRAETLMFSEHAVISMRDGKLTLMFRVG
NLRNSHMVSAQIRCKLLKSRQTP-EGEFLPLDQLELDVGFSTGADQLFLV
SPLTICHVIDTKSPFYDLSQRSMQTEQFEIVVILEGIVETTGMTCQARTS
YTEDEVLWGHRFFPVISLEEGFFKVDYSQFHATFEVPTPPYSVKEQEEML
LMSSPLMAPSLSNSGEKNN-SVDGLETLEDTSTKLPSKLQKITGREDLPR
KLLRMSS--TT-SEK-------------------AYS-----L-GDL---
-------PMKLQRI---SSVPGNSEEKLVSKTTKISSDPMSQSVADLPPK
LQRLATGGRMDGHLPPKLRKMNSDRFT
*
