>P1;ENSXMAG00000016537

I--MT-FEEV----------------------------------------
--------------------------------------------------
--------------------LIQK------------------P------A
ERAQCAGAALEEVLVSAKDNQSLTVGVYECAKVMNLD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----SFCVLA--T------
-DEQFEWDVALQIHFT---------------LIQSFCFDNDISIVRVSDT
------QRLAAIVGD----EQEDAHCVLIT---VRAGAERRGGLRGAAAQ
QSYINVLINTNITGENELEL------------TEYI--------------
------------------------------
*
>P1;ENSTRUG00000015127

---MT-LEEI----------------------------------------
--------------------------------------------------
--------------------HEQE------------------NA-M-ENT
DRVQSAGAALEELLVAAKKQDYITVGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--T------
-DEEYQCDIALQIHFT---------------LIQAFCFDNDINVVRVNDI
------ERLADLVGADESGEPKDVHCILVT---SPSANPWK----NP---
-----SLDKLSLFCEESRSV------------YDWV--------PTITLP
ER----------------------------
*
>P1;ENSDARG00000044676

---MV---------------------------------------------
--------------------------------------------------
--------------------------------------------------
----NEGKALSEALLSAKAEGRLTVGVYECAKIMNED-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----SFCLLA--T------
-D-DFECDIALQIHFT---------------LIQAFCFDNDISIVRVNDL
------KRLNALVGG-K-GQLEEAHCVLIT---NPTEDSWE----DP---
-----ALEKLHLFCEESRSY------------NEWV--------PEITLP
ER----------------------------
*
>P1;ENSGACG00000017938

---MT-FEEV----------------------------------------
--------------------------------------------------
--------------------LIQK------------------P------A
ERAQCTGKALEEVLVSAQDNDALTVGVYECAKVMNLD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----SFCVLA--M------
-DEDFQCDIALQIHFT---------------LIQSFCFDNDISIVRVSDT
------QRVAEIVGD-K-AQLEDAHCVLIT---NPAEGSWE----DP---
-----ALEKLHLFCEESRNV------------NDWV--------PEIVLP
ER----------------------------
*
>P1;ENSGACG00000006793

---MT-LEEI----------------------------------------
--------------------------------------------------
--------------------RGQE------------------NA-M-EIP
DRVQSAGAALEELLQAAKKQEYLTVGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--T------
-DEEYECDIALQIHFT---------------LIQAFCFDNDINVVRVNDI
------ERLADLVSAGEPGEPKDAHCILVT---SPSANPWK----DP---
-----ALDKLSGFCEERRSV------------YDWV--------PTVTLP
ER----------------------------
*
>P1;ENSDARG00000019417

---MT-FEEL----------------------------------------
--------------------------------------------------
--------------------SGQD------------------NT-A-TTG
DRMQTAGTALEELLVSAKKQDCLTVGVYESAQVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--T------
-DEEYEYDIALQIHFT---------------LIQAFCFDNDINIVRVNDI
------ERLADIVGCDQDEEPKDAHCILVT---RPNDDSWK----DS---
-----ALDKLGLFCEESRNV------------YEWV--------PSITLP
ER----------------------------
*
>P1;ENSAMXG00000005863

SV-MT-FEEV----------------------------------------
--------------------------------------------------
--------------------CGQE------------------ND----TS
DRMRSAGSALEELLLSAKKNDCLTVGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--T------
-DEEYECDMALQIHFT---------------LIQAFCFDNDINIVRVSDI
------ERLADIVGNDETGEPKDAHCILVT---NPNLESWK----DP---
-----SLEKLSVFCEERRSV------------YEWV--------PAITLP
ER----------------------------
*
>P1;ENSAMXG00000009069

LI-MT-LEEV----------------------------------------
--------------------------------------------------
--------------------PVQQ------------------NN----CI
EKARRTGEALQEALESAQANDCLTIGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--M------
-DEEFECDIALQIHFT---------------LIQAFCFDNDISIVRVSDA
------QRLAELLGD-KAGQLEDAHCVLIT---NPTDGSWE----DP---
-----ALEKLHVFCSESRSC------------HEWV--------PEVTLP
AR----------------------------
*
>P1;ENSTNIG00000016668

---MT-LEEI----------------------------------------
--------------------------------------------------
--------------------RGQE------------------KD-M-ESA
DRVQSAGAALEELLVAAKKQDYITVGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--T------
-DEEYQCDIALQIHFT---------------LIQAFCFDNDVNVVRVTDI
------ERLADIVGADETGESKDVHCILVT---SPSANPWK----NP---
-----ALDKLGLFCEESRSV------------YDWV--------PTITLP
ER----------------------------
*
>P1;ENSONIG00000015195

IITMT-LEEI----------------------------------------
--------------------------------------------------
--------------------HGQE------------------NT-M-ENA
DRVQSAGAALEELLIAAKKQDYLTVGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCILA--T------
-DEEYECDIALQIHFT---------------LIQAFCFDNDINVVRVNDI
------DRLADLVGADETGEPKDAHCILVTQLQSPSANPWK----DP---
-----ALDKLSVFCEERRSV------------YDWV--------PTITLP
ER----------------------------
*
>P1;ENSORLG00000014766

---MT-FEEV----------------------------------------
--------------------------------------------------
--------------------PIQK------------------P------T
ERAQCAGKALEEVLETAKDNESLTVGVYESAKVMNLD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----SFCVLA--M------
-DEQFQCDIALQIHFT---------------LIQSFCFDNDISIVRVSDM
------QRLADIVGD-KAEELEDAHCVLIT---NPADGSWE----EP---
-----ALEKLHLFCEESRRL------------NDWV--------PEISLP
ER----------------------------
*
>P1;ENSTRUG00000012938

---MT-FEEV----------------------------------------
--------------------------------------------------
--------------------LIQE------------------A------V
ERVQCTGKALEEVLVSAIENHSVTVGVYECAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----SFCVLA--M------
-DEEFECDIALQIHFT---------------LIQSFCFDNDISIVRVSDM
------QRLAEIVGN-KADQLEDAHCVLIT---SPAEGSWE----DP---
-----SLEKLHLFCEESRRL------------NDWL--------PEINLP
AR----------------------------
*
>P1;ENSORLG00000003982

---MT-LEEI----------------------------------------
--------------------------------------------------
--------------------NGQC------------------LNEMRFSL
FRVQSAGAALEELLLAAKKQDYLTVGVYESAKVMNVD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----AFCVLA--T------
-DEEYECDIALQIHFT---------------LIQAFCFDNDINVVRVNDI
------ERLADLVGADETGEPKDVHCILVT---SPSANPWK----DP---
-----SLDKLSLFCEESRNA------------YDWV--------PTITLP
ER----------------------------
*
>P1;ENSONIG00000012799

---MT-FEEV----------------------------------------
--------------------------------------------------
--------------------LIQK------------------P------A
ERAQCAGTALEEVLVTAKDNDSLTVGVYECAKVMNLD-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------PDSV-----SFCVLA--M------
-DEEFECDIALQIHFT---------------LIQSFCFDNDISIVRVSDM
------QRLVEIVGD-KAEQFEDAHCVLIT---NPADGSWE----DP---
-----ALEKLHLFCEESRRL------------NDWV--------PEISLP
ER----------------------------
*
>P1;ENSLOCG00000004444

---MATVREKAASLNLSAAIFSPMHRPPATHRMENKPFRATFIWSSIIRH
LQSRVEVKRRRHNLKYHNDCFVGSEAVDVILAHVVQNKFFGDAEIPRVKV
VRVCQALMDYKVFEGVDTKVFGKEKKRAAFEDSSCSLYRFLNSP-S-LTA
DSVENGGSSPYQRTLFNRPCGRTEEIVYSSATPIKTDKSLEDLLDNLNLS
PANPSQIKINLGLPQNVVNEVWHEQTLLRLLQLVELPLLDALLEGRAHEL
PAGSADREDGEPSLLFTSNYLDREILKAFGDSQADDWLSAAVDCLEFLPD
QMVVDVSRSLPKCSEGTQQCKRLLYDTIVKHYNQNNREPLLTNHLFDIHT
GIAELLVNGKSAHALEALQLCLKLLDPRSREELRRLLCFMAAAADPSEFR
LHREVENRMAVKRSFTKAIVSSKNLAKGKVDLLVLFLLDNQKDAFKIPGS
LHKLVSDKLACLV-------------------------RGK----DP---
-----DQATGSTFCQRVSSQAYSETTLKTTKDELWVLLRTIHENPKLSTK
EKKRVLGQFYKSHPDIFIQYFGNRAPNVCM
*
