>P1;ENSTRUG00000017768

-MVLLTMIARLADGL-PLAASMQEDEQVKNQKLGRDLQQYQSQAKQLFRK
LNEQSPTRCTLEAGSMAFHYLIEKGVCYLVLCEGSFPKKLAFAYLEDLQA
EFHEQHGKRVPIVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
SINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYVRFWWL
*
>P1;ENSAMXG00000016628

-MVLLTMIARLADGL-PLAASMQEDEQG-NEKMGRDLQQYQSQAKQLFRK
LNEQSPTRCTLEAGSVAFHYVIEKGVCYLVLCEAGFPKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
NINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYVRFWWL
*
>P1;ENSXMAG00000004514

-MIFLTVIARLADGL-PLAASIQEDEQ-----SGRDLQHYQSQAKQLLRK
LDAQSPDRCMLEAGNMNFCYFISQGVCCLCLCDASFPKKMAFGYLEDLHN
EFCEQYGKRVPAVTRPYSFIEFD-----TYIQKTKKSYVDSR--ARRNLS
SVSTELQDVQRIMVANIEEVLQRGEALSALDTKASNLRSQAEKYRSDARF
LNTRSTYAKVAAVVLVFVTLIIYVRFWWL
*
>P1;ENSGACG00000016000

-MTSLTMIARVTDGL-PLAASVQEDEK-----SGRDLQHYQSQAKQLCRK
LDAQSPERCTLEAGDMSFHYLIAQDVCYLFLCEASFAKRSAFAYLEDLRG
EFNGRYGRRVAAVTRPYSFIEFD-----TYIQKTKKSFVDRR--APRNFG
SINTELQDVQRIMVANIEEVLQRGESLSALDTKASNLTSLSKKYRSDAKY
LNTRSTYAKVAAVSVFLITLIIYVRFWWL
*
>P1;ENSONIG00000010664

-MILLTMVARVADGL-PLAASVQEDEQG-STKSERDLQQYQSQAKQLCRK
LDAQSPERCTLEAGDMNFHLLIAQGVCYLSLCEASFPRKMAFAYLEDLSN
EFYDQYGKRIPTVTRSILHVVPD-----TYIQKVKKSYVDSR--ARRTLS
SVNTELQDIQRIMVGNIEEVLQRGEALSAISTKASNLSNMAEKYHKDAKY
LNTRSTYAKFAAVAVFFITLIIYVRFWWL
*
>P1;ENSORLG00000004111

-MVLLTMIARLADGL-PLAASMQEDEQ-----LGRDLQQYQSQAKQLFRK
LNEQSPSRCTLEAGSMAFHYCIEKGVCYLVLCEASFPKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
NINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYVRFWWL
*
>P1;ENSTNIG00000007830

-MILLTMIARVADGL-PLAASIQEDEQ-----SERDLQQYQSQAKQLFRK
LNAQSPDRCTLVAGDLNFHYIIAQGVCYLVLCEASFPKKMAFACLEDLHT
EFFDQYGRRVPTVTRPYSFIEFD-----TYIQKNKKAYVDSR--ARRNLG
SINAELQDVQRIMVANIEEVLQRGEALSTLDTKAMDLSTQSKKYRSDAKY
LNTRSTYAKVAAVAVVFITLIIYVRFWWL
*
>P1;ENSORLG00000008357

-MILLTMIARVADGL-PLAASIQEDEQ-----SGRDLQQQQSQAKQLFRK
LNANSPERCTLEAGSMNFHYLIAQGICYLSLCEAKFPKKMAFAFLEDLHN
EFHEQYGKRASTVTRPYSFIEFD-----TFIQKKKKSYVDIR--TRRNLG
SVSTELQDVQRIMVTNIEEVLQRGEALSSLDTKASHLSDLSQKYRSDAKY
LNTRSTYAKVAAVAVVFITLIIYVRFYWL
*
>P1;ENSDARG00000100435

-MVLLTMIARLADGL-PLAASMQEDEQG-SEKMGRDLQQYQSQAKQLFRK
LNEQSPNRCTLEAGSMSFHYVIEKGVCYLVLCEAGFPKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLS
NINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYIRFWWL
*
>P1;ENSXMAG00000012926

-MLLLTMIARLADGL-PLAASMQEDEQ-----VGRDLQQYQTQAKQLFRK
LNEQSPTRCTLEAGSMAFHYFIEQGVCYLVLSEASFSKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEIN-----IFVQILTHAHIHKR--LKLNMH
LLSCHKKKRKSLLLLCIHRLLPHL-PHTALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYIRFWWL
*
>P1;ENSGACG00000012421

-MVLLTMIARLADGL-PLAASMQEDEQ-----LGRDLQQYQSQAKQLFRK
LNDQSPTRCTLEAGSMSFHYAIEKGVCYLVLCEASFAKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
SINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYQRDAKY
LNTRSTYAKLAAGGVFFIMLIVYVRFWWL
*
>P1;ENSDARG00000030108

-MVLQTMIVRVADSL-PLAASMQEDEQ-----SGRDLQKYQSQAKQLCRK
LNEQSPARCTLEAGKMCFHYVIEKGVCYLALCEAGFPKKLAFAYLEDLEG
EFSEQYGAKVPSVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
NINSELHDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKVAAGAVIIITLIIYVRFWWL
*
>P1;ENSONIG00000004730

-MVLLTMIARLADGL-PLAASMQEDEQG-SEKLGRDLQQYQSQAKQLFRK
LNEQSPTRCTLEAGSMAFHYCIEKGVCYLVLCEASFPKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
SINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYVRFWWL
*
>P1;ENSTRUG00000003315

-MILLTMIARVADGL-PLAASIQEDEQ-----SGRDLQQYQSQAKQLFRK
LNAQSPDRCTLEAGDVNFHYMIAQGVCYLLLSEASFPKKMAFAYLEDLHT
EFFDQYGRRVPTVTRPYSFIEFD-----TYIQKNKKAYIDSR--ARRNLG
SINTELQDVQRIMVANIEEVLQRGEALSTLDTKASNLSTLSKKYRSDAKY
LNTRSTYAKVAAVAVVFITLIIYVRFWWL
*
>P1;ENSTNIG00000006639

EMVLLTMIARLADGL-PLAASMQEDEQ-----LGRDLQQYQSQAKQLFRK
LNEQSPTRCTLEAASMAFHYLIEKGVCYLVLCEGSFPKKLAFAYLEDLQA
EFHEQHGKKVPTVSRPYSFIEFD-----TYIQKTKKSYIDSR--ARRNLG
SINTELQDVQRIMVANIEEVLQRGEALSALDSKASNLSSLSKKYRSDAKY
LNTRSTYAKLAAGGVFFIMLIVYVRFWWL
*
>P1;ENSLOCG00000017367

-MYRTLLFSVLLAGVLMMVVESRKNRP-----QGEIPSPYKNKSNTSDRR
TRKQEVLASSQEALVV---------------TEKKYLKS-DWCKTQPLRQ
TVSEE-GCVSRTIINRFCYGQCNSFYIPRHIKKEQESFQSCAFCKPQKFT
TLTVEL-DCPGLQPTFRHRKIQRVKQCRCISV---NVSESGKQ-------
-----------------------------
*
