>P1;ENSGACG00000010656

MMEEIDRFQVPSAVQEAEMQAEMQPL---DPASSTASEADSDTREVEPVT
INYKPSPLQRKIEKQRELARKGSLKNSNAVGSPVNQQPK---KNNNVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-
RHLRSQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTC------
--------------------------------------------------
----------------------------------------MCCQATSST-
---------------TCQIQ----------
*
>P1;ENSXMAG00000018218

MMEEIDRFQVPPV------NGETQPL---DPAASSTLEVASDT-KGESVA
MNYKPSPLQVQIEKQRDLARKASVKNG-TVGSPVNQQPK---KN----AR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTC------
--------------------------------------------------
----------------------------------------MCCQAAPST-
---------------ACQIQ----------
*
>P1;ENSAMXG00000008635

MMEEIDRFQVPAG------NSETQPL---DPAATSTSEPDADTREAETTA
INYKPSPLQVKIEKQRELARKGSAKNG-TVGSPVNQQPK---KN-NVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTC------
--------------------------------------------------
----------------------------------------MCCQASSST-
---------------ACQIQ----------
*
>P1;ENSONIG00000019458

MMEEIDRFQVPPV------NGETQPLVRDDPAASSTSEAEPDT-KGESVA
MNYKPSPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPK---KN----AR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTC------
--------------------------------------------------
----------------------------------------MCCQAAPST-
---------------ACQIQ----------
*
>P1;ENSORLG00000010685

MMEEIDRFQVPSAVQEAEMQSEMQPL---DPAASTASEAHSVTREGEPVT
INYKLSPLQRKIEKQRELARTGSLKNCNTVGSPVNQQPK---KN-NVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAENI
VSAERQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTC------
--------------------------------------------------
----------------------------------------MCCQAASST-
---------------TCQIQ----------
*
>P1;ENSONIG00000011791

MMEEIDRFQVPSAVQEAEMQAEMQPL---DPASSTASEADSDTREGEPVT
INYKPSPLQMKIEKQRELARKGSLKNGNTVGSPVNQQPK---KN-NVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTC------
--------------------------------------------------
----------------------------------------MCCQATSST-
---------------TCQIQ----------
*
>P1;ENSORLG00000008972

MMEEIDRFQVPPV------NGETQPL--QDPAASSTSEAETDP-KGESVA
LNYKPSPLQVQIEKQRDLARKASVKNG-TVGSPVNQQPK---KN----AR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTC------
--------------------------------------------------
----------------------------------------MCCQAASST-
---------------ACQIQ----------
*
>P1;ENSDARG00000013813

MMEEIDRFQVPT-------EAEMQPF---DPASSTTSEADSDTRESEPAT
LNYKPSPLHMKIDKQRELVRKGSLKNG-NAGSPVNQQPK---KN-NVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-
RSLREQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNSTC------
--------------------------------------------------
----------------------------------------MCCQATSST-
---------------ACQIQ----------
*
>P1;ENSXMAG00000001430

MMEEIDRFQVPSAVQEAEMQSEMQPL---DPASSTASEAESDTREGEAVT
INYKPSPLQMKIEKQRDLARKGSLKNNNTVGSPVNQQPK---KN-NVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTC------
--------------------------------------------------
----------------------------------------MCCQATSST-
---------------TCQIQ----------
*
>P1;ENSDARG00000016396

MMEEIDRFQVPPV------NPEMKLL--QDPAETSTIENETAPREPESVA
INYKPSPLQVKIEKQRELARKGSVKNG-TVGSPVNQQPK---KN-NVMAR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTC------
--------------------------------------------------
----------------------------------------MCCQATSST-
---------------ACQIQ----------
*
>P1;ENSGACG00000008695

MMEEIDRFQVPPV------NGETQPLIPQDPAASSSSEADADA-KGETVA
MNYKPSPLQVQIEKQRDHARKGSVKNG-TVGSPVNQQPK---KN----AR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTC------
--------------------------------------------------
----------------------------------------MCCQAAPST-
---------------ACQIQ----------
*
>P1;ENSTRUG00000015586

MMEEIDRFQVPPV------NGETQPL---DPAASTTSEGQPDA-KGETVA
MNYKPTPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPK---KN----AR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-
RCLRDQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTC------
--------------------------------------------------
----------------------------------------MCCQAAPST-
---------------ACQIQ----------
*
>P1;ENSTNIG00000010681

-MEEIDRFQVPPV------NGETQPL---DPAASTPSEGQPDA-KGETVA
MNYKPTPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPK---KN----AR
TRLVVPNKGYSSLDQSP-DEKPLVALDTDSDDDFDMSRYSSSGYSSAE--
------QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTC------
--------------------------------------------------
----------------------------------------MCCQAAPSA-
---------------ACQIQ----------
*
>P1;ENSLOCG00000010498

KMSGFDNFNTDFY------QTS-YSI---DDQ------------TQNAYD
YNNAADPYNNRPYGNYDYSQQ-----A-GCGSPGMMQPQQPYTG-QIYQP
TQTFTPASAQSVYGSSFEDEPPLL--------------------------
----------------EELGINFDHIWQKTLTVLHPLKAADGSIMNETDL
AGPMVFCLAFGATLLLAGKIQFGYVYGISAIGCLGMYCLLNLMSMTGVSF
GCVASVLGYCLLPMIILSSFGVLFSLQGMMGIVITAVIIGWCCFSASKIF
ISALAMEGQQLLVAYPCALLYGVFALISVF
*
