>P1;ENSAMXG00000018807

--EGLSNFRM--KLKSSRLGYLLLQFMTLLFYTQ----------------
--------------TTMQSVSVPNFKHHVTEHSRLSDRMSRRLTRTYQLY
SRTSGKHVQVLGNKRVVANGEDGDAH--AKLVVETDTFGSRIRIRGAKTG
FYICMNKKGKLVGRRKGHGRDCIFTEIVLENNYTALQNAKYKGWYMAFTR
KGRPRKATHTRQHQREAHFMKRLPRGHLL---TERKPFDVVP-----YQL
NKRTKHNHR--PGV----N
*
>P1;ENSXMAG00000000105

MKQYLNYYRM--RLRTSRLGYLFLQLAALCFYAQ----------------
--------------DTVQS--PPNFKQHVTEQSRLSDRMSRRLTRTYQLY
SRTSGKHVQVLANKRVNANGDDGAVH--AKLEVETDSFGSRVRIKGVKTG
YYICMNKRGKLIGKRKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFTR
KGRPRKASKTKQHQREAHFMKRLPRGHLL---SDRRPFDVLPLPVPVQPL
SRRTKHSHHQRSGG----R
*
>P1;ENSGACG00000003803

---------RAICFMLPRLNK-CLHLFSFCYFAQ----------------
--------------VTNQS--PPNFTQHVSEQSKVTDRVSRRLIRVYQLY
SRTSGKHVQVLPNKKINAMADDGDVH--AKLIVETDTFGSRVRIKGAETG
FYICMNKKGKLIGKNNGHGRDCIFTEIVLENNYTALRNARYESWYMAFTR
RGRPRKGSRTRQHQREVHFMKRLPKGQQPAHTSHHRPFDFVH-----YPF
RQRTKRTRY--SSE----R
*
>P1;ENSTRUG00000000925

---------M--RPIPSRLSYLFLHLFAFCYYAQEAFDPTWREFSMELAA
IFIRDHTPQSIVAQVTNQS--PPNFTQHVSEQSKVTDHVSRRLIRVYQLY
SRTSGKHVQVLPNKKINAMADDGDVH--AKLIVETDTFGSRVRIKGAETG
FYICMNKRGKLVGKKNGQGRDCIFTEIVLENNYTALRNARYEGWYMAFTR
RGRPRKGSRTRQHQREVHFMKRLPKGQQPVHPSHHRPFDFIH-----YPF
NQRTKRTRH--SSERPNPR
*
>P1;ENSONIG00000013179

---------M--RPIPSRLSCVFLHLFALFYYAQ----------------
--------------VTNQS--PPNFTQHVSEQSKVTDRTSRRLIRIYQLY
SRTSGKHVQVLPNKKINAMAEDGDVH--AKLIVETDTFGSRVRIRGAETG
LYICMNKRGKLIGKKNGQGRDCIFTEIVLENNYTALKNVRYEGWYMAFTR
QGRPRKGSRTRQHQREVHFMKRLPKGHQPTHPSHHQPFDFIH-----YPF
SQRTKRT------------
*
>P1;ENSORLG00000000919

---------F-TSLIPPVIGHGFLHLFAFCHYAQ----------------
--------------VTNQS--SPNFTQHVSEQSRVTDHVSRRLIRVYQLY
SRTSGKHVQVLSNKKINAMAEDGDVH--AKLIVETDTFGSQVRIKGAQTG
LYICMNKKGKLIGKKNGQSRDCIFTEIVLENNYTALRNAHYNDWYMAFTR
RGRPRRGSQTRQHQREVHFMKRLPRGQQVIHSSQHRPFDFIH------SF
SQRTKRTRY--SSE----R
*
>P1;ENSONIG00000018818

MKQYLNYYKM--RLRTSRLGYLLLQFTALCFYAQ----------------
--------------NTVQS--PPNFKHHVTEQSRLSDRMSRRLTRTYQLY
SRTSGKHVQVLANKRVNANGEDGAAH--AKLEVETDSFGSRIRIKGVKTG
YYICMNKKGKLIGKRKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFTR
KGRPRKASKTKQHQREAHFMKRLPRGHLL---SEKRPFDVLPLPVPAHPF
NKRTKHSHHQRSGG----R
*
>P1;ENSTRUG00000014840

---------M--RLRTSRLGYLLIHFTALCFYAQ----------------
--------------NTAQS--PPNFKHHVTEQSRLSDRMSRRLTRTYQLY
SRTSGKHVQVLANKRVNANGDDGAVY--AKLEVETDSFGSRIRIKGVKTG
YYICMNKRGKLIGKRKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFTR
KGRPKKASKTKQHQREAHFMKRLPRGHLL---SERRPFDVLPLAVPVHSL
NKRTKLPHQQRSAP----R
*
>P1;ENSDARG00000039615

---------M--RLKSSRLGYLFLQFMTLCFYTQ----------------
--------------MTMQSISMPNFKHHVTEQSRLSDRMSRRLTRTYQLY
SRTSGKHVQVLGNKRVNANAEDGDIHGKAKLVVETDTFGSRVRIRGAKTG
YYICMNKKGKLIGRRKGRGKDCIFTEIVLENNYTALQNAKYKGWYMAFTR
KGRPRKAMQTRQHQREAHFMKRLPRGHLL---TEQKPFDLIP-----YPL
NKRTKHHQR--ASV----N
*
>P1;ENSDARG00000003399

---------M--RLIPSRLSYLFLHLFAFCYYAQ----------------
--------------VTIQS--PPNFTQHVSEQSKVTDRVSRRLIRTYQLY
SRTSGKHVQVLANKKINAMAEDGDVH--AKLIVETDTFGSRVRIKGAETG
FYICMNRRGKLIGKKNGLGKDCIFTEIVLENNYTALQNVKYEGWYMAFTR
KGRPRKGSKTRQHQREVHFMKRLPKGHQI---AEHRPFDFIN-----YPF
NRRTKRTRY--SGE----R
*
>P1;ENSTNIG00000006362

---------M--QTISSRLSYLFLHLFAFCYYAQ----------------
--------------VTNQS--SPNFTQHVSEQSKVTDHVSRR-IRIYQLY
SRTSGKHVQVLPNKKINAMADDGDVHV-AKLIVETDTFGSRVRIKGAETG
FYICMNKRGKLIGKKNGQGRDCIFTEIVLENNYTALRNARYEGWYMAFTR
RGRPRKGSRTRQHQREVHFMKRLPKGQQPVHPSHHRPFDFIH-----YPF
NQRTKRTRY--SSE----S
*
>P1;ENSAMXG00000012018

---------M--RLIPSRLSYLFLHLFAFCYYAQ----------------
--------------VTIQS--PPNFTQHVNEQSRVTDRVSRRLIRTYQLY
SRTSGKHVQVLANKKINAMADDGDVH--AKLIVETDTFGSRVRIKGAETG
FYICMNRRGKLIGKKNGQGKDCIFTEIVLENNYTALQNVKYEGWYMAFTR
KGRPRKGSKTRQHQREVHFMKRLPKGHHI---AEHRPFDFIN-----YPF
NRRTKRTRY--SGE----R
*
>P1;ENSGACG00000018276

---------M--RLRTSRLGYLLLQFTALCFYAQ----------------
--------------NTVQS--PPNFKHHVTEQSRLSDRMSRRLTRTYQLY
SRTSGKHVQVLANRRVNANGDDGAVH--AKLEVETDSFGSRVRIKGVKTG
YYICMNKRGKLIGKKKGRGKDCIFTEIVLENNYTALQNAKYEGWYMAFTR
KGRPRKASKTKQHQREAHFMKRLPRGHLL---SERRPFDALPLRVPAHPL
SKRTKHSHHQRSGG----R
*
