>P1;ENSONIG00000005940

MEENDHG-NRDVVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDGGA-NREES--S---LAS---RE------SHN-----SPT
APQTEP----VGST-VPAEGT-STPHTVT-GTKKPAIAAEEPLKPRG-EN
GDQCLS-SDSDSSQASSNPSMSQPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKT-------TSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQ
ELGLNESQIKIWFQNKRAKIKKASGTKNSLALHLMAQGLYNHSTVTSKDE
KSDSD
*
>P1;ENSAMXG00000002112

MEEGEQSAPRDEPNRATDRSTDRSTIRPVQGNPP-P-LPHRITNFFIDNI
LHPDFGRKKEASA-LRADS--CP--TGA---GD------SAG-----SPA
TPGSGR----LSVS-GPTEST-STPLPES-AAKKPEIE--EPFTAKGSNS
KDQCLSSSESDTSQPGTNTSQNRPMLWPAWVYCTRYSDRPSSGPRTRKPK
KKNTTTTTTTTTKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQSLAQ
ELGLNESQIKIWFQNKRAKIKKASGTKNTLALHLMAQGLYNHATT-TKED
KSDSD
*
>P1;ENSONIG00000009704

MERNARR---DPERPRDSGEQSNRAILPLLQPPGNQ-QSHRITNFYIDNI
LRPDFGLKRKDGAPDRQGD--A---LGVLIQRE------ELTGRKPPKSA
NPRQGG----AGGKEEENPGENEDQHPDT-DARRPGVVARDV------AA
NDRCR------S-PQASTATAAKPMLWPAWVYCTRYSDRPSSGPRSRKPK
KAP------TPSKEDKRPRTAFTAEQLQRLKTEFQNNRYLTEQRRQSLAR
DLGLNESQIKIWFQNKRAKIKKASGNKNSLALHLMAQGLYNHST--AKDA
KSDSD
*
>P1;ENSTNIG00000012777

MEENDHG-NRDVVERPESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDGGT-NRDES--S---LAS---RE------SHN-----SPA
APQTES----EGST-VPAEGT-STPHTVT-GAKKSAIAAEEPLKPRR-EN
GDQCLS-SDSDSSQASSNPSMSQPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKS-------TSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQ
ELGLNESQIKIWFQNKRAKIKKATGSKNSLALHLMAQGLYNHSTVTSKDE
KSDSD
*
>P1;ENSTRUG00000017873

MEENDHG-NRDVVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDGGT-NRDES--S---LAS---RE------SHN-----SPA
APQTES----EGST-VPAEGT-STPHTVT-GTKKPAIAAEESLKPRR-EN
GDQCLS-SDSDSSQASSNPSMSKPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKS-------TSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQ
ELGLNESQIKIWFQNKRAKIKKATGNKNSLALHLMAQGLYNHSTVTSKDE
KSDSD
*
>P1;ENSXMAG00000002496

MEENDHG-NRDAVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRKKDVDA-HLDES--S---PAS---RE------SRG-----SPA
APQTEP----VGST-VPAEGT-STPHTVT-GPKKPAKAAEESLKPSG-ES
GDQCLS-SDSDSSQASSNPSMSQPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKT-------TSKEDKRPRTAFTAEQLQRLKSEFQTNRYLTEQRRQNLAQ
ELGLNESQIKIWFQNKRAKIKKASGTKNSLALHLMAQGLYNHATVTSKDE
KSDSD
*
>P1;ENSGACG00000014426

MEENAHR---HPERAEDSGEESNRAIRPLL-PPGNQ-QSHRITNFYIDNI
LRPDFGRKRKNGTLVRDGD--R---PGGIIRRD------EQTGRKSSKTR
DPQPAA----AGGEE-EDTGASEEQHPET-EARRPEP-------------
-------------IAGDGLVKSKPMLWPAWVYCTRYSDRPSAGPRSRKPK
KAP------TPSKEDKRPRTAFTAEQLHRLKTEFQNNRYLTEQRRQNLAL
DLGLNESQIKIWFQNKRAKIKKATGNKNSLALHLMAQGLYNHAG--SKDA
KSDSE
*
>P1;ENSAMXG00000008331

MEEKDRS-PRGA---EDSGDES-----MLLHAPGNL-HAHRVTNFYIDNI
LRPDFGRRKEGIA-SIPAN--DHDHHHQ---HYNHHQHSAVT-----SEP
SAATEP----VGAP-VTGEGT-SGPRPGT-GAKRTSDG------AGA-ES
ADQCLS-SDSECSQSSAH-PNSQPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKS-------LSKEDKRPRTAFTAEQLQRLKTEFQTNRYLTEQRRQSLAQ
ELGLNESQIKIWFQNKRAKIKKATGTKNSLALHLMAQGLYNHATT-SKDD
KSDSD
*
>P1;ENSORLG00000008039

MEEKNPQ---DPGGPQNFRQESSRGVWPLLQPPGH---QHQPTNFYIDNI
LRPDFGLRGKRGK-EAPE--------------------------------
APE-RC----TGRR-APKPGS-PGAAGPR-GKQSGDLDRGSHLKP-----
GDDEVK-V--RAHEQGTETNAAKPMLWPAWVYCTRYSDRPSAGPRSRKPK
TAA------APCKEDKRPRTAFTSEQLQRLKEEFQRNRYLTEQRRQSLAR
DLGLKESQIKIWFQNKRAKIKKASGGKNSLALHLMAQGLYNHST--TKDG
KSDSD
*
>P1;ENSDARG00000026599

MDENEQS-ARDV-EQRGASDESNSAIRPLLQAPGNLQLPHRITNFFIDNI
LRPDFGRKKEANI-TRYED--N---HGA---RE------NH------NPT
GPSTGQ----VGST-VPAEEA-STTHTSS-GGKEAEIESEEPLKPRG-EN
VDQCLG-SESDSSQSNSNGQTGQGMLWPAWVYCTRYSDRPSSGPRSRKPK
KKA-------ASKEDKRPRTAFTAEQLQRLKAEFQTNRYLTEQRRQSLAQ
ELGLNESQIKIWFQNKRAKIKKASGVKNGLAIHLMAQGLYNHSTT-SKED
KSDSD
*
>P1;ENSDARG00000038868

MEENDHS-NRDV-ERQDSGDESNRAILPLLQAPGNV-LPHRITNFYIDNI
LRPDFGRRKEGS--RRDEI--I---IVE---RE------NR------CPS
APGSGQ----V-AP-VSGEGT-SSPRAVN-ASKKTDISTDESLKSRA-ET
GDQCLS-SDSDCSQSS-AAQAKQPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKT-------PTKEDKRPRTAFTAEQLQRLKNEFQNNRYLTEQRRQALAQ
ELGLNESQIKIWFQNKRAKIKKATGNKNTLAVHLMAQGLYNHATV-TKDD
KSDSD
*
>P1;ENSGACG00000003888

MEENDRG-NRDAVERQESADESNRAILPLLQPPGNPQIPHRVTNFFIDNI
LRPDFGRKKDGDA-NRDAS--S---LAS---RE------SPG-----SPD
APQTEP----VGNT-VPAEGT-STPHTVTVSSKKPAIAADEPQDPRG-ER
GDQCLS-SDSDSSQASSNPPASKSMLWPAWVYCTRYSDRPSSGPRSRKPK
KKT-------TSKEDKRPRTAFTAEQLQRLKTEFQTNRYLTEQRRQNLAQ
ELGLNESQIKIWFQNKRAKIKKSTGAKNSLALHLMAQGLYNHATVSSQDA
KSDSD
*
>P1;ENSORLG00000010437

MEENDRG-SRDVVERQESADESNRAILPLLQAPGNLQIPHRVTNFFIDNI
LRPDFGRRKDAGA-NREES--L---AGE----Q------PQQ-----PRR
TPD-RA----CGEH-RSSRGDLHSTHSHR-RKEAHYIRRGATATPGG-EW
RP-VPK-LRLRQFPSQLEPIRFQPMLWPAWVYCTRYSDRPSSGPRSRKPK
KKS-------TSKEDKRPRTAFTAEQLQRLKTEFQTNRYLTEQRRQNLAQ
ELGLNESQIKIWFQNKRAKIKKASGTKNTLALHLMAQGLYNHATVTSKDE
KSDSD
*
>P1;ENSXMAG00000001344

MEENVQG-EPE--RPKSSGEESNRAILPLLQQPGIQ-QSDRVTNFYIDNI
LRPDFGRKRKKGT-LCVRGGHG---LEE---RS------EAS-----GRK
ASKTDSKRGRAGGR-EDSLGK-SD-------HQPAESEASGPGLTAC-DS
GISCRS-PESSEAPAAPAAPAAKPMLWPAWVYCTRYSDRPSSGPRSRKPK
KAP------TPSKEDKRPRTAFSAEQLQRLKAEFQKNRYLTEQRRQNLAL
ELSLNESQIKIWFQNKRAKIKKASGKKNSLAEHLMAQGLYNHSAGREAEA
HSDSD
*
