>P1;ENSDARG00000034453

--------------------------------------------------
--------MKVKQGC---DAGVPYTTEEDLLNSPEITPEDVLGLQKIT--
DNYLCGPEQNVHKIDFTRFKIRDMETGTVLFEITKPPTS--ETGEDRMDF
EQNAGRFVRYQFTPAFLRLRQVGATVEFTVGDSPINNFRMIERHYFRGQL
LKSFDFEFGFCIPSSKNTCEHIYEFPPLSEDIMREMILHPYETQSDSFYF
VDNKLVMHNKADYSYNGGP
*
>P1;ENSAMXG00000024390

--------------------------------------------------
--------MK------------------------KILMDN-ILLCFFT--
LDYLCSPEDNVYNIDFTRFKIRDMETGTVLFEITKPPAL--DKGGDKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMIERHYFRDQL
LKSFDFEFGFCIPSSKNTCEHIYEFPPLSEDIMREMILHPYETQSDSFYF
VDNKLVMHNKADYSYSGGP
*
>P1;ENSGACG00000008624

--------------------------------------------------
--------MKVQQGCHSSNMGIPVTTEEELRRNTVITPDDVLGLQKIT--
KNYLCSPEENVHMIDFTRFKIRDMETGTVLFEITKPPTDVSRQAEGRKQC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDQL
LKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDIMREMILNPYETQSDSFYF
VDNKLVMHNKADYSYSGGP
*
>P1;ENSTRUG00000012195

MSYSCTNRGNSQDPSSAKKAAGNNPGRDT------GG-TD----------
SSPKQTATMKVKKGCNSAEVGVPVTTEEDLLTSAVVTPEDVLGLQKIT--
ENYLCSPDENIFNIDFTRFKIRDMETGTVLFEITKPPST--DKTGDKRDM
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDLPIENFRMIERHYFRERL
LKSFDFEFGFCMPKSKNTCEHIYEFPPLSEDSIREMILHPYETQSDSFYF
VDNKLVMHNKADYSYNGGT
*
>P1;ENSORLG00000002577

----------------------------S------SG------------T
SSPKQTA-MRVKKGCNSAEVGVPETTEEDLLANAVISPEDVLGLQKIT--
ENYLCSPDENIYNIDFTRFKIRDMETGTVLFEITKPPST--DKSGEKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPIENFRMIERHYFREKL
LKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDVIREMILHPYETQSDSFYF
VDNKLVMHNKADYSYNGGT
*
>P1;ENSGACG00000020475

---------------AAKKPAGDNPGRDT------GG-TD------RSSS
SSPQDTAAMKVKKGCNATDAGVPVTTEEDLLGGSGVTPEDVLGLQKIT--
ENYLCSPDENIFNIDFTRFRIRDMETATVLFEITKPPAA--DKAGEKRDV
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDKPIENFRMIERHYFREKL
LKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDIIREMVLHPYETQSDSFYF
VDNKLVMHNKADYSYNGGT
*
>P1;ENSTRUG00000016070

--------------------------------------------------
--------MKVQQGCNSSDMGIPVRTEEELRRNTVITPEDVLGLQKIHKD
VNYLCSPEDNVHMIDFTRFKIRDMETGTVLFEITKPPTP----AGDKKLS
DPNAGRFVRYQFTPAFLHLRQVGATVEFTVGETPINNFRMIERHYFRDQL
LKSFDFEFGFCMPSSKNTCEHIYEFPALSEEIMREMILHPYETQSDSFYF
VDNKLVMHNKADYSYSGGP
*
>P1;ENSONIG00000008183

--------------------------------------------------
--------MKVQQGCNSSDMGIPVTTEEELRKHTVITPEDVLGLQKIT--
KNYLCSPEENVHMIDFTRFKIRDMETGTVLFEITKPPTP----AGGKKQC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDQL
LKSFDFEFGFCMPSSKNTCEHIYEFPTLSEETMREMILHPYETQSDSFYF
VDNKLVMHNKADYSYSGGP
*
>P1;ENSONIG00000008702

MSYSCTSRGNSQDPSSAKKPAGSNPARDA------GG-TDSG--TDSTSN
GSPKQTAAMKVKKGCNSTDVGVPVTTEEQLLASTVITPEDVLGLQKIT--
ENYLCSPEENIYNIDFTRFKIRDMETGTVLFEITKPPST--DKASEKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDRPIENFRMIERHYFREKL
LKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDIIREMILHPYETQSDSFYF
VDNKLVMHNKADYSYNGGT
*
>P1;ENSTNIG00000016130

MSYSCTNRGNSQDPSSAKDAAGDNPGRDT------GG-TD----------
ASPKQTAAMKVKKGCNSAEVGVPVTTEEDLLSSAVITPEDVLGLQKIT--
ENYLCSPDENIFSIDFTRFKIRDMETGTVLFEITKPPTT--DKTGDKRDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDLPIENFRMIERHYFRERL
LKSFDFEFGFCMPRSKNTCEHIYEFPPLSEDSIQEMILHPYETQSDSFYF
VDNKLVMHNKADYSYNGGR
*
>P1;ENSXMAG00000007806

MSYSCTSRGNSQDPSNA------NPARTT------GG-TDGG--TDSTGN
GSPKQTAVMKVKKGCNSAEVEVPVTTEEELLGRTVITPEDVLGLQKIT--
EHYLCSPDENVFNIDFTRFKIRDMETSTVLFEITKPPST--DKSGEKRDI
DLNAGRFVRYQFTPAFLRLRQVGATVEFTVGDMPIENFRMIERHYFREKL
LKSFDFEFGFCMPSSKNTCEHIYEFPPLSEDTIREMVLHPYETQSDSFYF
VDNKLVMHNKADYSYNGGT
*
>P1;ENSXMAG00000011781

--------------------------------------------------
--------MKVQQGCNSSDMGIPVRTEEELRKNTVITPEDVLGLQKIT--
ENYLCAPEENVHMIDFTRFKIRDMETGTVLFEITKPPTP-----GGLKQC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDKL
LKSFDFEFGFCMPSSKNTCEHIYEFPTLSEETMHEMIQHPYETQSDSFYF
VDNKLVMHNKADYSYSGGP
*
>P1;ENSORLG00000008116

--------------------------------------------------
--------MKVQQDCNSADMGIPVRTEEELRKNTVITPEDVLGLQKIT--
KNYLCSPEENVHRIDFTRFKIRDMETGTVLFEITKPPTP-----GGVKLC
DPNAGRFVRYQFTPAFLQLRQVGATVEFTVGDTPINNFRMIERHYFRDKL
LKSFDFEFGFCMPSSKNTCEHIYEFPALSEEMMREMIQHPYETQSDSFYF
VDNKLVMHNKADYSYCGGP
*
>P1;ENSAMXG00000017747

--------------------------------------------------
--------MRVKAGN---DAGLPCTTEQELLQNQTIRPEDVLGLQNIT--
ENYLCSPDDNVHKIDFTRFKIRDMETGIVLFEITKPPLA--ESSEDRKDI
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMIERHYFRGQL
LKSFDFEFGFCIPSSKNTCEHIYEFPPLSEELIHEMILHPYETQSDSFYF
VDNKLVMHNKADYSYTGAQ
*
>P1;ENSDARG00000044362

MSYSCTSTGNSQDPSSSKKSGGVNPGSCSSSNGDTGNGNNRHSIRGSKAN
SKPDSTEAMKVKKGCNTTDLGVPVTTEEELLANKTISPEDVLGLQKIT--
ENYLCSPEDNLYNIDFTRFKIRDMETGTVLFEITKPPST--DR-GDKRDV
DPNAGRFVRYQFTPAFLRLRQVGATVEFTVGDIPINNFRMIERHYFREQL
LKSFDFEFGFCIPSSKNTCEHIYEFPPLSEDLIREMILHPYETQSDSFYF
VDNKLVMHNKADYSYSGGP
*
