>P1;ENSTRUG00000009493

----------------------------MADRFDCDNCKESLYGRKYIQS
DDSPYCIPCYDSLFSNTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDEALLCNDCYCNEFSSKCVACDKIVMPGTRKLEYAG-ST
WHEGCFICHSCEQPIGSKSFIPDKDEHYCVACYEDKFAPRCTRCKKTLSK
GGVTYRDEPWHKECFVCTNCTTQLAGQHFTSRDDSPYCLKCFGNLYAKKC
EACAKPITGKTSSPFVPGFGGGKYISFEDRQWHQPCFTCSQCSVSLVGAG
FFPTGDKILCRECNSNL----------C
*
>P1;ENSONIG00000016304

FALRRNG----K------V-FYSKTEITMTDRFDCDNCKESLYGRKYIQS
DDSPYCIPCYDSLFSNTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDDALLCNDCYCNEFSSKCVACDKIVMPGTRKLEYAG-ST
WHEGCFICHSCSQPIGSKSFIPDKDEHYCVPCYEDKFAPRCTRCKKTLTK
GGVTYRDEPWHKECFVCTSCKTQLAGQHFTSRDDSPYCLKCFGNLYAKKC
EACSKPIT---------GFGGGKYISFEDRQWHQPCFTCSQCSVSLVGAG
FFPDGDRILCRDCHTS-----------L
*
>P1;ENSAMXG00000020826

--------------------GVVLCRVRMSEQFNCENCKDSLYGRKYIQV
DDVPHCVPCYDRLFANICQGCKELIGHNSRELYYDDHHYHEECFRCSRCE
RSLAEEPFTCQDDALLCNDCYCSEFSSKCVACNKTVMPGTSCVSYNKDST
PNSTLTTLNRC----GVSVVINVDGQNTCLPV-QTEYMLTCTESQKALVQ
GGVTYRDEPWHRECFLCTGCKTQLAGQPFTSQGESPYCVKCFSSLYAQKC
SACNKPIT---------GFGDGKYVSFEDRQWHQSCFKCAGCSASLVGAG
FFPSGGKVYCKDCNDN------------
*
>P1;ENSORLG00000014671

VSFIQHD----F------VLSSLSVKTTMADRFDCDNCKESLYGRKYIQS
NDSPYCIPCYDSLFSNTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDNALLCNDCYCNEFSSKCVACDKIVMPGTRKLEYAG-ST
WHEGCFICHSCEQPIGSKSFIPDKDEHYCVPCYEDKFAPRCTRCKKALSK
GGVTYRDEPWHKECFVCTSCETQLAGQHFTSRDESPYCLKCFSSLYAKKC
EACCKPIT---------GFGGGKYISFEDRQWHQSCFTCSQCSVSLVGAG
FFPNGDRILCRDCNSN-----------L
*
>P1;ENSONIG00000013661

---------------------------IMSDRFDCKNCNESLYGRKYILA
EDNPHCIPCYDRLYANTCQECKEIIGHNAKELFYENRHYHEHCFRCFRCD
RSLADEPFTSQDDALVCSDCYCNEFSSKCVACDKTVMPGSRMLEYGG-ST
WHEDCFACHACEKPIGTESFIPDKNNYYCVPCYEGRFAPQCSHCKKALTK
GGVTYKDEVWHKECFLCTGCKTPLAGQPFTSQGESPYCVKCFSNMYAKKC
AGCNTAIT---------GFGDGKYVSFQERQWHQPCFKCSRCSVSLVGSG
FFPDRDLILCTDCNNE-----------D
*
>P1;ENSGACG00000002619

---------------------------IMSERFDCKNCNESLGGRKYIQV
EDHPHCIPCYDRLYANTCEECKEIIGHNAKELFYENRHYHAHCFRCFRCD
RSLADEPFTSQEDALVCSDCYCNEYSSKCVSCDKTVMPGSRMLEYGG-ST
WHEDCFACHGCLKPMGAEAFVPDNDNYYCVPCYEGRVAPQCSHCKKALTK
GGVTYKDEVWHKECFLCTGCKAPLAGQPFTSQGESPYCVKCFSSLYAKKC
AGCNTAIT---------GFGDGKYVSFEERQWHQPCFKCSRCSVSLVGSG
FFPDRDQILCTDCNND-----------D
*
>P1;ENSGACG00000013685

QYTFLCLLKLDAIFELKHP-GPSSWRVTMADSFDCVNCKESLYGRKYIQS
EASPYCIPCYDSLFSNTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDDALLCNDCYCNEFSSKCVACDKVVMPGTRKLEYGG-ST
WHEGCFICHSCQQPIGSKSFIPDKDEHYCVSCYEDKFASRCTRCKKTLAK
GGVTYRDEPWHKECFVCASCKTQLAGQHFTSRDESPYCLKCFGNLYAKKC
EACSKPIT---------GFGGGKYVSFEERQWHQPCFTCSQCSASLVGAG
FFPDGERILCRDCNSG-----------V
*
>P1;ENSORLG00000009622

----------------------------MSERFDCRNCKASLYGQQYIKV
ENEPHCINCYDQLHANTCQECTEIIGHNDKELTFKDRYYHEHCFRCFRCD
RSLSNASFTSHEDVLLCNDCYCNEFSSKCVSCNKIVMPGSKILEFDG-SS
WHEDCFVCHSCEKPIGGESFVPNENQYYCVPCYEGRFTPRCSHCNKALTK
GGVSYQGGVWHRECFLCTGCSAPLAGQPFTSQGETPYCVKCFSNLYAKKC
AGCNSAIT---------GFGDGKYISFEDREWHQPCFKCSRCSVSLVGSG
FFPYRDQILCRDCNDD-----------D
*
>P1;ENSDARG00000034643

----------------------------MSERFDCDNCKESLYGRKYIQA
EENPYCIPCYDSLFANTCDECKELIGHDSRELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDDALLCNDCYCNEFSSKCVACDKTVMPGTRKLEYAG-ST
WHEGCFICNSCQQPIGSKSFIPDKDDHYCVPCYENKFAPRCTRCKQALAK
GGVTYRDEPWHKECFVCTSCKVQLAGQHFTSRDDSPYCIKCFGNLYAKKC
EACNKPIT---------GFGGGKYISFEDRQWHQPCFTCSRCSVSLVGAG
FFPEQDEILCRNCNSTL-----------
*
>P1;ENSTRUG00000010010

----------------------------MSDQFSCKNCQESLCGRKYIQV
EDRPHCISCYERLYANTCQECKELIGHNAKELSYEDRYYHAHCFRCFHCE
RSLADQPFTSQGDALVCSDCYGSRFSSKCSACDQTVTPGSRMLEYDG-ST
WHEDCFACHGCGKAIGTEAFIPDKNNYYCVPCYEGRVAPQCSHCKQALTK
GGVTYKDEVWHKECFLCTGCSAPLAGQPFTSQGESPYCIRCFSSLYAKKC
AGCNTAIT---------GFGDGKYVSFEDRQWHQPCFKCSRCSVSLVGSG
FFPDRGHILCMDCNND-----------D
*
>P1;ENSXMAG00000013212

VLPYRHR----Y------V-KP-HEKTTMADRFDCDNCKESLYGRKYIQS
DDNPYCIPCYDSLFSNTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDDALLCNDCYCNEFSSKCVACDKIVMPGTRKLEYAG-ST
WHEGCFICHSCEQPIGSKSFIPDKDDHYCVPCYEEKFAPRCTRCKKALAK
GGVTYRDEPWHKECFVCTNCKTQLAGQHFTSRDDSPYCLKCFGSLYAKKC
EACSKPIT---------GFGGGKYISFEDRQWHQPCFTCSQCSISLVGAG
FFPDGDKILCRDCNSN-----------L
*
>P1;ENSDARG00000104315

----------------------------MSEPFDCESCKESLYGQKYIQV
DDKPHCVPCYDRLHANTCHECKELIEHNSRELYHEDRHYHEQCFRCSRCS
RSLAKESFTCQEDALVCNNCYCNEFSSNCVACGKTVMPGSKRLEYED-CV
WHEECFVCCGCEQPIGAQSFIPDKDEYYCVPCYEGRFAPRCAHCKQTLVQ
GGVTYRDEPWHKECFLCTGCKVQLAGQPFTTQGEDPYCVKCFSNLYAQKC
AACEKPIT---------GFGEGKYVSFEERQWHKPCFKCSVCSLSLVGAG
FFPHGSMILCKGCNTKKLFQIVCEQTIE
*
>P1;ENSAMXG00000020305

MCNLI---------------HILNRTITMTERFDCDNCKESLYGRKYIQA
EDNPYCIPCYDSLFANTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDDALLCNDCYCNEFSSKCVACDKTVMPGTRKLEYGG-ST
WHEGCFICNSCEQPIGSKSFIPDKDDHYCVPCYENKFAPRCTRCKQVLAK
GGVTYRDEPWHKECFLCTGCKVQLAGQHFTSRDDSPYCLKCFGNLYAKKC
EACSKPIT---------GFGGGKYISFEERQWHQTCFTCSRCSVSLVGAG
FFPERDEILCRDCNSNL-----------
*
>P1;ENSTNIG00000006814

----------------------------MADRFDCDNCKESLYGRKYIQS
DDSPYCIPCYDSLFSNTCDECKELIGHDARELFYEDRHYHEHCFRCFRCD
RSLADEPFTSQDEALLCNDCYCNEFSSKCVACDKIVMPGTRKLEYAG-ST
WHEGCFICHSCEQPIGSKSFIPDKDEHYCVACYEDKFAPRCTRCKKTLSK
GGVTYRDEPWHKECFVCTSCKTQLAGQHFTSRDDSPYCLKCFGNLYAKKC
EACTKPIT---------GFGGGKYISFEDRQWHQPCFTCSECSVSLVGAG
FFPYRGQDLVPRMQQQ-----------P
*
