>P1;ENSXMAG00000010764

LSSG--S--PAIAASLIPPELCGSTA-NTKKAQVKNNSGVTPAGQCGTWV
KEPSGGCFTSPNYPEKYPPERECIYIIEASPRQCIDLFFDEKYSIEPSWE
CRFDHIEIRDGPFGFSPIIGRYCGQESPAYVRSSGRYLYIKFVADGELEA
IGFSARYNFTQDPEFEGIGELSALPACDFELSGPEGFVESTQIAKEGKAQ
LTEAVDCRWYIRAPPRAKIYMRFLEYEMHNSNECKRNFVAIYDGSSGVEH
LKNKFCSTVANDVMLVTSVGVVRLWADEGSRKSRFKILFTTFHEPPCEGD
TFFCHSNMCINHTLVCNGVQNCVYPWDENRCKE-KRKASILDTLDNTNLT
IIGITCGLVVILLIISVIIQIKQPRKKYVIRSILRDDFDPALLHPGF-DP
PHYELCTLRRAP------SGDLTDAALADDFDKFHKLRRSESKCIRDHHC
GSHQ--GSI---------HGSRSNLSLRDATI-A---PDGGAAVPPMSPR
LATQMSPHLS--HH-NTPACRRSILVMKHSYSQDGAEA--YRA--ED--E
-ED-----------------------------------------------

*
>P1;ENSDARG00000068483

MVPRVKL--LVVVASIVNLGFSGAPTAPPKKAIVKNNSGVTPVGLCGSWI
KETNGGLFTSPNYPEKYPPDRECIYIIEAAPRQCIDLYFDYKYAIEPSWE
CKFDHIEVRDGPFSFSPIIGRYCGQVSPNYVRSSGRYLWIKFVADSELEA
TGFSARYNFTQDPEFKDLGAQPPLPICEFDMSGPEGIVESVMVSKEGKAL
QTEAVDCRWFIRAPPGSKIFLRFLDYEMQNSNECKRNFVAVYDGSSSVEH
LKNKFCSTVANDVMLLNSLGVIRMWADETSRRSRFRILFTTFHEPPCGSD
TFFCHSNMCINHTLVCNGIQNCVYPWDENGCKE-KRKATILDSLDNTNVT
IIGVTCGVVLILLTVSIIIQIKQPRKRYIIR---RDEFDPTLLHEAF-EP
PHYELCTLRQTT------SCDNED--LPEDFP---NLQRTSSKCIHGHHC
GSQV--SST---------RGSRSDLSLRDAAA-I--LSEM----------
---ETSTQTPFPLQ-ATPNVRRNIVVMKHSYSHDGAEE--CDL--DD--E
FYDGPTTS-------RGRSM-----DRTVHRSI-----SNDF--------

*
>P1;ENSTNIG00000006336

--------------------------------------------QCGTWV
KEPDGGYFTSPNYPEKYPPDRECVYIIEASPRQCIDLFFDDKYSIEPSWE
CKFDHIEVRDGPFGFSALIGRYCGQESPAYVRSSGRYLYIKFVADGELEA
IGFSARYNFTQDPEFEYLGEVPALTPCDFELSGPEGFVESSQISGETRVL
QSEAVDCRWHIRAPPRSKIYMRFLEYEMHNSNECKRNFVAIYDGSSSVEH
LKNKFCSTVANDVMLGSSVGVVRLWADEGSRKSKFRILFTTFHEPPCEGD
TFFCHSNMCINHTLVCNGIQNCVYPWDENHCKE-RRKHSILETLDHTNLT
IIGVTCGLVLILLIISVIIQLKQPRKKYIIR---REDFDPALLHPGV-EP
PHYELCTLRRAP------SGDLADAALDEDFDKFHKLHRSSSKCIRDHHC
GSQQ--GSVHG-----SLHGSRSNLSLRDAAI-P---ADGGALVPP-GP-
-LSQQSPRLS--QH-VAPAGRRSVVVMKHSCSQDGAER--YRM--DE---
---GSTISRHHHHFHHYSSGH----EHAVH-----------R--------

*
>P1;ENSONIG00000009024

--------------------------------------------ECGTWV
KEPDGGYFTSPNYPEKYPPERECIYIIEASPRQCIDLFFDEKYSIEPSWE
CKFDHIEVRDGPFGFSPIIGRYCGQESPSYVRSSGRYLYIKFVADSELEA
IGFSARYNFTKDPEFKELGELPALPFCEFEMNGPEGYVDSTQIAKEGRAQ
QTEAVDCRWYIRAPPRAKIYMRFLEYEMHNSNECKRNFVGIYDGSSSVEH
LKNKFCSTVANDVMLVTSVGVVRLWADEGSRKSRFKILFTTFHEPPCERD
TFFCHSNMCINHTLVCNGIQNCVYPWDENHCKE-KRKPSILDTLDNTNLT
IIGVTCGLVVILLIISVIIQVKQPRKKYIIR---RDDFDPALLHPGF-EP
PHYELCTLRRAP------SGDLTDPALAEDFDKFHKLRRSESKCIRDHHC
GSHQ--GSV---------HGSRSNLSVRDATI-V---PDGGALVSQLQPV
MVNQQSPRLS--HH-NTPTSRRNIVVMKHSYSQDAAGG--YRAEEEEDLM
MDDGPTTS------QHHMYHH-----------------------------

*
>P1;ENSAMXG00000020348

MVHGRSF--LHVVASLLILGLSGAT---KKE-AVKNNSGVQPAGQCGTWV
KNPEGGLFTSPNYPNKYPPERECIYIIEAPPRQCIDLFFDEKYSIEPSWE
CKFDHIEVRDGPFGFSPIIGRYCGQQSPQYIRSSGRYLWIKFVADGELEA
IGFSANYNFTADPDFKDMGIPKPLPFCEFEMGGPEGIIESQQITKDGKAS
PTEAVDCKWFIRAPPRSKIYLRFLDYEMQNSNECKRNFVAVYDGSSSVED
LKVKFCSTVASDVMLLSALGVVRMWADEGSCRSRFKILFTTFQEPPCEAD
TFFCHSNMCINNSLVCNGIQNCVYPWDENHCKE-KRKANLLDNLNNTNGT
IIGVTCCVVLILLVVSVVVQIKQPRKKYILR---RDDFDPTVFQEVFQEP
PHYELCTLRSAAA----ASADLAE--LAEDLESFHRLRRSSSRCVHDHHC
GSNQPPG------------AKSANLSP------AALMTE----M------
---QPQP--TRPLLPPNTANRRSILVMKHSYSQDA-----CEL--DD--E
LDEVPTTS-------HRLARH----EKAVQRFCLIGSLSKHESEYNTTRV

*
>P1;ENSONIG00000014342

MLHGHSF--HHVVASLLILGLCGAT---KKDTAVKNNSGVKPAGQCGTWV
KEAEGGLFTSPNYPNKYPPDTECVYILEAPPRQCIDLHFEENYSIESSWE
CKFDNIEVRDGPFGFSPILGRYCGQHSPPDIRSSGRYLWIKFVTDGELEA
VGFSANYNFTADPDFADLGIPPPLPSCQYDMVGPEGIVESHQITRDGKAG
ATEAVDCKWYIRAPPRSKIYLRFLDYEMANSNECKRNFVAVYDGGSSVED
LKSKFCSTVANDIMLVSTLGVIRMWADEASRKSRFRILFTTYQEPPCDAD
AFFCHSNMCINNTLVCNGMQNCVYPWDENQCKE-KRKANILDNLNNTNGT
IIGVTCCIVFILLIISVIVQIKQPRKKYILR---REDFDPTMFQEVF-EP
PHYELCTLRSATTP-TAASADLVD--LAEDFENYHALRRASSRCVHDHHC
GSSSNPGSAHISQLSLSGRGSRGNLSARDAAA-ATLLTD----L------
---PQPSMAVRPLL-PATGNRRSILVMKHSYSQEAADN-GCDL--DD--D
LEEVPTTS-------HRLSRH----EKAVQRFCLIGSLSKHESEYNTT--

*
>P1;ENSTNIG00000008169

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--FVGRFSVCPYPDFADLGVPPPLPSCQYDMVGPEGIVESHQITRDGKAG
ATEAVDCKWYIRAPPRSKIYLRFLDYEMANSNECKRNFVAVYDGGSSVED
LKSKFCSTVANDLMLVSTLGVIRMWADEASRRSRFRILFTTYQEPPCDAD
AFFCHSNMCINNTLVCNGVQNCVYPWDENQCKEENRKASILDNLNNTNGT
IIGVTCCIVLVLLIVSVIVQIKQPRKKYILR---REDFD-TMFQEVF-EP
PHYELCTLRSAAAA-TAASADLVD--LAEDFENYHGLRRASSRCIHDHHC
GSSPNPGPAHLSQLSLSGRGSRSNLSARDT-----LLTD----L------
---PQPPMAVRPLL-PASGARRSIMVMKHSYSQEAADA-GCDL--DD--D
LEEVPTTS-------HRLSRH----EKAVQRFCLIGSLSKHESEYNTTRV

*
>P1;ENSTRUG00000010454

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---SSLLRSISDPDFADLGVPPPLPSCQYDMVGPEGIVESHQITKDGKAG
ATEAVDCKWYIRAPPRSKIYLRFLDYEMANSNECKRNFVAVYDGGSSVED
LKSKFCSTVANDIMLVSTLGVIRMWADEASRRSRFRILFTTYQEPPCDAD
AFFCHSNMCINNTLVCNGVQNCVYPWDENQCKE-NRKASILDNLNNTNGT
IIGVTCCIVLILLIVSIIVQIKQPRKKYILR---HEDFDSTMFQEVF-EP
PHYELCTLRSASAA-ATTSADLVD--LAEDFENYHALRRASSRCIHDHHC
GSSPNPGSTHLSQLSLSGRGSRGNLSSRDSGA-ATLLTD----I------
---PQPPMAVRPLL-PTSGNRRSIMVMKHSYSQEAADNGGCDL--DD--D
LEEVPTTS-------HRLSRH----EKAVQRFCLIGSLSKHESEYNTTRV

*
>P1;ENSGACG00000014515

A-RG--L--LLLAASLLSLELSGAS----ATE-IK-AQDVTPAGQCGTWV
KEPDWGYFTSPNYPQKYPPEKECVYIIEASPRQCIDLFFDDKYSIEPSWE
CKFDHIEVRDGPFGFSPILGRFCGEDSPASVRSSGRYLYIKFVADGELEA
IGFSARYNFTQDPEFKGLGELPPLPFCEFEMSGPEGYVESVQITGEGRAL
PTEAVDCRWYIKAPPKSRIYMRFLEYEMHNSNECKRNFVAIYDGSSSVEH
LKNKFCSTVANDVMLVSSVGVVRLWADEGSRKSKFRILFTTFHEPPCGAE
TFFCHSNMCINQTLVCNGIQNCVYPWDENHCKE-KRKASILDTLDNTNIT
IITVTCGLVVILLVISVIIQVKQPRKKYIIR---RDDFDPALLHPGL-EP
PHYELCTLRRDP------SGDLTDAAMAEDYEKLHKLRRSSSKCIRDHHC
GSFQ--GSV---------HGSRSNLSLRDATI-A---AEPQAMV------
--GQQSPGLP--QH-AAPTGRRSVLVMKHSYSQDGAEG--YRAE-EEDSM
VDDCPATS------LHHMHHH--------------------Q--------

*
>P1;ENSAMXG00000018352

MLPPPALQALLVLAAFIKLGFFGAPS-GPKKAQVTNNSGVTPEGLCGAWV
KEPDGGYFTSPNYPEKYPPDRECTYIIEASPRQCIDLYFDEKYSIEPSWE
CKFDHIEVRDGPFSFSPIIGRYCGQQSPMYVRSSGRYLWIKFVADSELEA
TGFSARYNFTQDPDFKDIKTPLSLPVCEFEMSGPEGIVESVMVSKEGRAQ
QTEAVDCRWFIRAPPGAKIYLRFLEYEMQNSNECKRNFVAVYDGSSSVEH
LKNKFCSTVANDVMLLTSVGVIRMWADEGSRKSRFRILFTTFHAPPCEGD
TFFCHSNMCINHTLVCNGIQNCVYPWDENGCKE-KRKATILEHLDHTNVT
IIGITCGVVIILMTVSIIIQIKQPRKKYIVR---RDDFDPALLHEAF-EP
PHYELCALRQAA------SAEGEA--LPEDFP---KLQRSSSKCVHGHHC
GSQA--SSV---------RGSRTDLSLRDAAA-I--LSEMQAVT------
---PQPPLLQHH---TLPGSRRNIVVMKHSYSQDGAEV--CDL--DD--D
LEDGPTTS-------HGYGHGRMGMERTVQRSV-----SNDF--------

*
>P1;ENSDARG00000071596

MVHGNRF--LHVVAGLLMLGLSGAT---KKE-AVKNNSGVQPAGQCGTWV
KEPEGGLFTSPNYPNKYPPERECIYIIEAPPRQCIDLFFDEKYSIEPSWE
CKFDHIEVRDGPFGFSPIIGRYCGQQNPPYIRSSGRYLWIKFVADGELEA
MGFSASYNFTSDPDFKDIGVPKPLPFCEFEMGGPEGIIESQQITKDGRAL
QTEAVDCKWYIRAPPRSKIYLRFLDYEMQNSNECKRNYVAVYDGSSSVED
LRNKFCSTVANDVMLVSALGVIRMWADEGSRKSRFRILFTTFQEPPCEAD
TFFCHSNMCINNTLVCNGIQNCVYPWDENHCKE-KRKANILDSLNNTNGT
IIGVTCCIVLILLIVSVIVQIKQPRKKYILR---REDFDPTMFQEVFQEP
PHYELCTLRSAAA----TSADLAE--LAEDFESYHKLRRASSRCIHEHHC
GSSQISS----------NKGSRTNLSARDAAA-AAILTD----L------
---PPQP--MRPL-PPQ-TNRRNILVMRHTYSQDATDA--CEL--DD--E
LEEVPTTS-------HRLSRH----EKAVQRFCLIGSLNKHESEYNTTRV

*
>P1;ENSORLG00000007770

MVHGRSF--HHDIFKLHFIILHWSV---QKSASKTQRKGVQDSGQCGTWV
KEAEGGLFTFPNYPNKYPPNTECVYILEAPPRQCLDLHFEENYSIESSWE
CKFDNIEVRDGPFSFSPILGRYCGQHSPPDIRSSGRYLWIKFETDGELEG
VGFSASYNFTADPDFGDLGVPPPLPSCQYDMVGPEGIVESHQITRDGKAG
AAEAVDCKWYIRAPPRSKIYLRFLDYEMANSNECKRNFVAVYDGGSSVED
LKSKFCSTVANDIMLVSTLGVVRMWADELSRKSRFRILFTTFQEPPCDAD
AFFCHSNMCINYTLVCNGLQNCVYPWDENQCKE-KRNTKFLDNLNTTNGA
IIGVTCCIVFILLIVSVIVQIKQPRKKYVLR---REDFDPTMFQEVF-EP
PHYELCTLRSAPTP-TAASADLVD--LAEDFDNYHALRSASSRCVHDHHC
GSSSNPGSAHISQLSLSGRGSRSNLSVRDSAA-ATLLAD----L------
---PQPPMAVRPLL-PTTGNRRSILVMKHSYSQEAADT-GCDL--DD--D
LEDVPTTS-------HRLSRH----EKAVQRFCLIGSLSKHESEYNTTRV

*
>P1;ENSXMAG00000018539

MC------------------------------------------------
------------------------YISFPFLQQCT---------------
-----------P--------------------------------------
--------------------------------------------------
-FSQLICFCPICSLVLFQIYLRFLDYEMANSNECKRNFVAVYDGGSSVED
LKSKFCSTVANDIMLVSTLGVIRMWADELSRKSRFRILFTTYQEPPCDAD
AFFCHSNMCINYTLVCNGMQNCVYPWDENQCKE-KTNTKFLDNLNSTNGA
IIGVTCCIVFILLIVSVIVQIKQPRKKYILR---REDFDPTMFQEVF-EP
PHYELCTLRSAATP-TAASADLVD--LAEDFENYHALRQASSRCIHDHHC
GSPSCPGSAHISQLSLSGRGSRSNLSARDSGAAAALLAD----L------
---PQPPMSVRPLL-PATGNRRSILVMKHSYSQEAADN-GCDL--DD--D
LEEVPTTS-------HRLSRH----EKAVQRFCLIGSLSKHESEYNTTRV

*
>P1;ENSGACG00000002682

MVHGHSF--HHVVASLLILGLSGAT---RKDTSVKNNSGVKPAGQCGTWV
KEPEGGIFTSPNHPNKYPPDTECVYILEAPPRQCIDLHFDENYSIESSWE
CKFDNIEVRDGPFGFSPILGRYCGQHRPPYIRSSGRYLWIKFVTDGELEA
VGFSASYNFTADPDFADMGVPPPLPSCQYDMVGPDGIVESLQITRDGKAD
ATEAVDCKWYIRAPPRSKIYLRFLDYEMANSNECKRNFVAVYDGGSSVED
LKNKFCSTVANDIMLVSTLGVIRMWADEASRKSRFRILYTTYQEPPCEPE
AFFCHSNMCINNTLVCNGLQNCVYPWDENQCKE-KRKTNILDNLNNTNGT
IIGVTCCIVLILLIVSVIVQIKQPRKKYILR---REDFDPTMFQEVF-EP
PHYELCTLRSATAAAAAASADLVD--LAEDFENYHGLRRASSRCVHDHHC
GSFSNPGSAHLSQLSLSGRGSRGNLSARDSAG-GALLAD----L------
---PQAPMAVRPLL-PSTGNRRSILVMKHSYSQEAADN-GCDL--ED--D
LEEVPTTS-------HRLSRH----EKAVQRFCLIGSLSKHESEYNTTRV

*
