>P1;ENSDARG00000089790

FYLVPGF-RLCFWSQVTICGQLPSKPITPEKPSIQRGKKHTKVWNHLRKS
KWFYRGDYHIDVCINDYLDVYCPHYMDTVPEERTERYVLYMVNYDGYSSC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STLAENGRRSCLRLKVFVRPTNNCDKS---HDRVDKFDDRSINSIENNND
GTSHESAEPSRSD-VNSAG-RVQTVGPLLASVLVLLASL----SSL----
--------------------------------------------------
---------------
*
>P1;ENSXMAG00000015959

MLQVEMVLFVCLVLLMCVLSQEPGSKVVAD--------RYAVFWN--RTN
AKFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVAPNGKKTCLKLKVFVRPSNSCLKT----DRVFDIDDRVESTL-PR-D
ETSHETAAPSRSE-TNAAQ-RLQKTSSLLALLLVTLVGL----FT-----
--------------------------------------------------
--------------L
*
>P1;ENSDARG00000098625

-------------------------------------------WS--VLF
CRFQRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SMITETGRRSCLKLKVFVRPPNGCEKTIGVHDRVF-VDDKVDNALEPR-D
DTSHE-AEPSRSD-VSTSGLRHQTSRPLLALLLLCISLY----LLL----
--------------------------------------------------
---------------
*
>P1;ENSTRUG00000015156

------------------KNVKKQRKCLGA--------SYPTTDE---RR
HRFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVAENGRKTCLKLKVFVRPSNSCTKTI--HDRVFDVNDKVDNTLEPR-D
DTSHDPAEPSRSDETNAAL-QLQKTSPILALLL-GLGQL----RELPPMG
GLLCDGRISAVSLYGMRMNSKTCNRKKTKKQKKICLKRLVFCSCVVLAHF
HYVWVGFYFCWCCCI
*
>P1;ENSORLG00000003965

---------------MCVFSQEPGSKVVAD--------RYAVFWN--RTN
TKFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIAQNGRKTCLKLKVFVRPSNNCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHETAAPSRSE-TNAVS-HLHKTSPLLASLLVSLAAL----FT-----
--------------------------------------------------
--------------L
*
>P1;ENSTRUG00000012828

LLFQRMMLFFLYLITSTIM-SIPWQNTFQS--------HYI--FR--SSK
QIFYRGDYHIDVCINDYLDVYCPHYTGAVPDERAERYILYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SITDRKGRRSCLRLKVFVRPQNNCIKHSGSTQEAVEFEDNSHNSLEPR-D
GIGHESPEPARRD-VNSAS-RYHTSVLLLSSLLA---AV----LSV----
--------------------------------------------------
---------------
*
>P1;ENSAMXG00000009088

MPQVGVLVFLALLLWMCVLGQEPASKVVAD--------RYAVYWN--RTN
PRFYRGDYHIDVCINDYLDVYCPHYLESVPEERTERYMLYMVNYDGYSSC
DHTATGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVGENGRRTCLRLKVFVRPANNCVKTVSVHDRVFDVNDRVDNSIEPR-D
DTSHESAEPSRGD-VNSAG-SVRLDVLLLASALLLVASIVSSSSS-----
--------------------------------------------------
--------------L
*
>P1;ENSORLG00000013262

--------------------------------------------------
------DYHIDVCINDYLDVYCPHYASPVSDDRAERYVLYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SVSDVRRRRSCLRLKVFVRPQNNCVKNPGSEQEGVDFEENNHNSLEPR-D
GISHESPEPSRTD-VNSAG-RHQYTMLPLSSALMLLAAI----MSL----
--------------------------------------------------
---------------
*
>P1;ENSXMAG00000005010

MPQVDMILFLILIIGMCVFGQDPASKVVSD--------RYAVFWN--RTN
PKFYRGDYHIDVCINDYLDVYCPHYASPVSDDRAERYVLYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SITDDRGRKNCLRLKVFVRPQNNCVKNSGSSQEGVEFDENSHNSLEPR-D
GINHESPEPARQD-VNAAG-RRQFSILLLSSALMLLAAI----LSL----
--------------------------------------------------
---------------
*
>P1;ENSTNIG00000016669

--------------------------------------------------
-RFHRGDYHIDVCINDYLDVYCPHYDDSVPEERTERYVLYMVNYDGYSTC
DHTSKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIVENGRKMCLKLKVFVRPSNSCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHEPAEPSRSDETNAAS-QLQKSSPFLALLLVCLLSF----LTL----
--------------------------------------------------
---------------
*
>P1;ENSAMXG00000021030

MLQVEMIIFVCLILWMCVFSQEPSSKVMAD--------RYAVYWN--RTN
PRFHRGDYHIDVCINDYLDVYCPHYEDSVPEERTERYVLYMVNYDGYSTC
DDTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SMVTETGRKGCLKLKVFVRPANSCVKIIGVHDRVFDVNDKVDNSLEPR-G
--------------------------------------------------
--------------------------------------------------
---------------
*
>P1;ENSGACG00000006791

--------------------------------------------------
------DYHIDVCINDYLDVYCPHYEETVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STIAENGRKTCLKLKVFVRPSNSCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHEPAEPSRSDETNAAP-HLQNTSPVLALLLLCLSAL----FTS----
--------------------------------------------------
---------------
*
>P1;ENSONIG00000015197

MLQVEMVVFVCLVLLMCVFSQEPSSKVVAD--------RYAVFWN--RTN
TKFHRGDYHIDVCINDYLDVYCPHYEDTVPEERTERYVLYMVNYDGYSTC
DHTAKGFKRWECNRPHSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
STVAENGKKTCLKLKVFVRPANSCVKTIGVHDRVFDVNDKVDNTLEPR-D
DTSHEPAEPSRSE-TNDVP-RLQKTSPLLASMLICLAAL----ST-----
--------------------------------------------------
--------------L
*
>P1;ENSONIG00000012804

MPQVDMILFLILIIGMCVYGQDPASKVVSD--------RYAVFWN--RTN
PKFYRGDYHIDVCINDYLDIYCPHYVGPVADDRAERYVLYMVNYDGYSSC
DHNSKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SISDDRGRRSCLRLKVFVRPQNNCVKNSGTVEEGVNFDDNSHNSLEPG-D
GVSHESPEPARRD-VNSAG-LCQTSVLLLSSTLILLAVI----LSL----
--------------------------------------------------
---------------
*
>P1;ENSGACG00000017948

--------------------------------------------------
-RFYRGDYHIDVCINDYLDVYCPHYVGPVSDDRAERYILYMVNYDGYSSC
DHTAKGFKRWECNRPLSPNGPLKFSEKFQLFTPFSLGFEFRPGREYYYIS
SITDDKGRRSCLRLKVFVRPQNNCVKSPGTAQEGVDFDDSSQNSLEPR-G
G--------------------------------------------L----
--------------------------------------------------
---------------
*
