>P1;ENSXMAG00000017409

MKERRLPQPFVARCKLVLVGDVQCGKTAMLQVLVKDCYPEVFTPLEVEKL
SVCNLELEDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDGALKKWKAEIQDFCPNTRILLIGCKTDLRTDVCTRMELSNQKQAPVSH
EQGSSLAKQLGAEAYLECSAFTSEKSIHSVFRTAALACMNKLQPPNKPSP
VRRLSKRLLHLPNKTDLLS----KDKSKSCSIM-----------------
-----------------
*
>P1;ENSGACG00000008549

MKERRNNQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELEEQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDSSLKKWKTEILDFCPSTRILLIGCKTDLRTDVCTLMELSNQKQTPITY
EQGSAMAKQLGAEAYLECSAFTSEKSIHSVFRTAAMACINKLQPLPKPSP
TRRLSKRLLHLPSKSDLLSSTFKKEKTKSCSVM-----------------
-----------------
*
>P1;ENSDARG00000004218

MKERRNAQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELDDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDI
FDSGLKKWRAEILDFCPSTRILLVGCKTDLRTDVCTLMELSNQKQTPITH
EQGSAMAKQLGAEAYLECSAFTSEKSIHSVFRTAALACINKLQPLAKPSP
TRRLSKRLLHLPSKSELLSSTFKKEKAKSCSVM-----------------
-----------------
*
>P1;ENSTRUG00000015649

MKERRNTQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELEEQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDSSLKKWKTEILDFCPSTRILLIGCKTDLRTDVCTLMELSNQKQTPVTY
EQGSALAKQLGAEAYLECSAFTSEKSIHSVFRTAAMACMNKLQALPKNSP
TRRLSKRLLHLPSKSDLLSSTQEGEDQELLSDVSGELTVDSDRITPSPSP
SLVLGKGGGHGFIRASC
*
>P1;ENSAMXG00000004513

MKERRNTQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELDDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VESGLKKWRTEIMDFCPNTRILLIGCKTDLRTDVCTLMELSNQKQTPITH
EQGSAMAKQLGAETYLECSAFTSEKSIHSVFRTAALACINKLQPLAKPSP
SRRLSKRLLHLPSRSELLSSTFKKEKAKSCSIM-----------------
-----------------
*
>P1;ENSONIG00000011943

MKERRNTQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELEEQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDSSLKKWKTEILDFCPSTRILLIGCKTDLRTDVCTLMELSNQKQTPITY
EQGSAMAKQLGAEAYLECSAFTSEKSIHSIFRTAAMACINKLQPLPKPSP
TRRLSKRLLHLPSKSDLISTTFKKEKAKSCSVM-----------------
-----------------
*
>P1;ENSTNIG00000015099

MKERRNTQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELEDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDGSLKKWKTEILDFCPSTRVLLIGCKTDLRTDVCTLMELSNQKQTPVTY
EQGSALAKQLGAEAYLECSAFTSEKSIHSVFRTAAMACMNKLQALPKNSP
TRRLSKRLLHLPSKTDLLS-SFKKEKTKSCSVM-----------------
-----------------
*
>P1;ENSORLG00000012314

MKERRTPQPCVARCKLVLVGDVQCGKTAMLQVFVKDSYPETYVPTVFENY
TAS-LDLEDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDAALKKWKAEIQDFCPSTRVLLIGCKTDLRTDVCTRMELSHQKQAPISQ
EQGSCFAKQLGAAAYLECSAFTSEKSIHSVFRSAALACTNKLQVAEKLSP
VRRLSKRLLHLPSKTELLSSSFSKDKSKSCSIM-----------------
-----------------
*
>P1;ENSGACG00000003002

MKERRLAQPRVARCKLVLVGDVQCGKTAMLQVVAKDCYPETYVPTVFENY
TSC-LELEDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDA
VDGALKKWKAEIRDFCPSTRILLIGCKTDLRTDVCTRMELSNQKQTPVSH
EQGSSLAKQLGAEAYLECSAFTSEKSIHSVFRTAALACLNQLQPADKPSP
VRRLSKRLLHLPSKTELLSSTFGKDKSRSCSVM-----------------
-----------------
*
>P1;ENSONIG00000017051

MKERRLTQPFVGRCKLVLVGDVQCGKTAMLQVLVKDCYPETYVPTVFENY
TAC-LELEDQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDGALKKWKAEIQDFCPSTRILLVGCKTDLRTDVCTRMELSNQKQAPISH
EQGSSLAKQLGAEAYLECSAFTSEKSIHSVFRTAALACMNKLQPANKPSP
VRRLSKRLLHLPSKTELLSSTFSKDKSKSCSIM-----------------
-----------------
*
>P1;ENSXMAG00000010632

MKERRNTQPLVVRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LELEEQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
MDSSLKKWKSEILDFCPSTRILLIGCKIDLRTDVCTLMELSNLKQTPITY
EQGSAMAKQLGAEAYLECSAFTSEKSIHSVFRTAAMACINKLQPLPKSSP
TRRLSKRLLHLPSKSDLLSSSFKKEKTKSCSVM-----------------
-----------------
*
>P1;ENSTRUG00000000426

MKERRLTQPFVARCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAC-LEVEEQRVELSLWDTSGSPYYDNVRPLCYSDSDAVLLCFDISRPDT
VDTALKKWKAEIQDFCPSTRILLIGCKTDLRTDVCTRIELSNQKQTPISH
EQGSSLAKQLGAEAYLECSAFTSEKSIHSVFRTAALACMNKIQPASKSSP
DRRLSKRLLQLPSKTDL-SSTFSKDKSRSCNIM-----------------
-----------------
*
>P1;ENSDARG00000030547

MKERRISQPLVMRCKLVLVGDVQCGKTAMLQVLAKDCYPETYVPTVFENY
TAG-LELEEQRVELSLWDTSGSPYYDNVRPLCYSDADAVLLCFDISRPDT
VESSLKKWKAEIMDFCPSTRIILVGCKTDLRTDVCTLMELSNQRLTPISH
EQGTLLAKQVGAEVYLECSAFTSEKSIHSVFRSASLTCLNKLQPPIKQSP
TRRLSKRLLHLPSKAELLTSSFSKERTKSCTII-----------SLCP--
-----------------
*
