>P1;ENSTNIG00000012496

---------------------------------MGVEVETIVPGDGQTFP
KKGQRVVVHYVGTLMNGQMFDSSRDRGKPFKFKIGHGEVIRGWEEGVAQM
SVGQRAKLICSPDFAYGSKGHPGIIPPNATLIFDVELLGLEV
*
>P1;ENSDARG00000033567

---------------------------------MGVEIETITPGDGRTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRDKPFKFKIGKQEVIRGWEEGVVQM
SVGQRAKLTCSPDFAYGNKGHPGIIPPNATLIFDVELLSLQ-
*
>P1;ENSAMXG00000012980

---------------------------------MGVEVETITPGDGSTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRGKPFKFKIGKQEVIRGWDEGVAQM
SVGQRAKLTCTPDFAYGSKGHPGIIPPNATLIFDVELLGLE-
*
>P1;ENSAMXG00000003590

---------------------------------MGVEIETITPGDGRTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRDKPFKFKIGKQEVIRGWEEGVVQM
SVGQRAKLTCSPDFAYGNKGHPGIIPPNATLIFDVELLSLE-
*
>P1;ENSONIG00000001640

MRNIRRRSAQTDGLREECCRVRGQQQQQLQDAEMGVEIETITPGDGRTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRDKPFRFKIGKQEVIRGWEEGVVQM
SVGQRAKLTCSPDYAYGNKGHPGIIPPNATLIFDVELLGLE-
*
>P1;ENSTRUG00000003030

---------------------------------MGVQVDTITPGDGQTFP
KKGQQVAVHYVGTLVDGTTFDSSRDRGRPFRFKIGRGEVIRGWEEGVAQM
SVGERAKLTCSPDYAYGAKGHPGVIPPNATLIFDVELLSLEA
*
>P1;ENSORLG00000002452

---------------------------------MGVEIETITPGDGRTFP
KKGQTCVVHYVGCLTDGRKFDSSRDRDKPFRFKIGKQEVIRGWEEGVVQM
SVGQRAKLTCSSDFAYGNKGHPGIIPPNATLVFDVELLGLE-
*
>P1;ENSONIG00000016814

------------------------PEEGYSGAKMGVEIQTITPGDGRTFP
KKGQRVVVHYVGTLADGKVFDSSRSRGKPFKFKIGHQEVIRGWEEGVAQM
SVGQRAKLICSPDYAYGSKGHPGIIPPNATLTFDVELIGLE-
*
>P1;ENSXMAG00000018066

-----------------------------SNAKMGVEIETITPGDGRTFP
KKGQRVVVHYVGTLDDGKVFDSSRSRGKPFKFKIGHQEVIRGWEEGVAQM
SVGQRAKLICSPDFAYGSKGHPGVIPPNATLTFDVELLGLE-
*
>P1;ENSORLG00000014598

------------------------R-KKHRENIMGVEIETLTPGDGRTFP
KKGQRVVVHYVGTLADGKVFDSSRSRGKPFKFKIGHQEVIRGWEEGVAQM
SVGQRAKLICSPDYAYGSKGHPGVIPPNATLTFDVELLGLEA
*
>P1;ENSGACG00000012061

---------------------------------MGVDIETITPGDGRTFP
KKGQRVVVHYVGTLADGKVFDSSRSRGKPFKFKIGHQEVIRGWEEGVAQM
SVGQRAKLICSADFAYGSKGHPGIIPPNATLTFDVELLSLEA
*
>P1;ENSGACG00000004338

---------------------------------MGVEIETITPGDGRTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRDKPFRFKIGKQEVIRGWEEGVVQM
SVGQRAQLTCTPDFAYGNKGHPGIIPPNATLIFDVELLGLE-
*
>P1;ENSXMAG00000016714

---------------------------------MGVEIETVTPGDGRTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRDKPFRFKLGKQEVIRGWEEGVGQM
SVGQRAKLICSPDFAYGNKGHPGIIPPNATLIFDVELLSLE-
*
>P1;ENSDARG00000022684

---------------------------------MGVEVETITPGDGSTFP
KKGQTCVVHYVGSLTDGRKFDSSRDRGKPFKFKIGKQEVIRGWDEGVAQM
SVGQRAKLTCTPDFAYGSKGHPGVIPPNATLIFDVELIGLE-
*
