>P1;ENSTNIG00000013112

MGAVV-----GTLT-------MQT------------------K-QRRPSR
DKIDDDLEMTMVCHRPEGLEQLEAQTNFSKRELQVLYRGFKNECPSGVVN
EDTFKQIYSQFFPHG------------------------DASTYAHFLFN
AFDSAHTGSIKFEDFVTALSILLRGSITEKLQWTFNLYDINRDGYINKEE
MTDIVKAIYDMMGKYTYPVLKTDAPKQHVDAFFQ-KMDKNRDGVVTLDEF
ILSCQEDENIMRSLQLFENVI
*
>P1;ENSDARG00000102210

--------------------------------------------------
-----DLELSIVCHRPEGLEQLEAQTNFNKKELQVLYRGFKQECPSGVVN
EETFKQIYSQFFPHG------------------------DASTYAHYLFN
AFDSSHNGSIKFEDFVTALSILLRGTTTEKLEWTFNLYDINRDGYINKE-
--------------------------------------------------
---------------------
*
>P1;ENSTRUG00000007648

MGAVV-----GTL------T-MQAKQ-------------------RRPSR
DKADDELEMTTVCHRPEALDQLEAQTNFSKQELQILYRGFKNECPSGVVN
EETFKHIYAQFFPHGGCTEGC---------VA-DVMCAAYASMYAHYLFN
AFDTANNGSIKFKDFVTGMSILLRGTVREKLEWTFHLYDINRDGYINREE
MTEIVRAIYDMMGKYTYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEF
VIACQEDETMMRSMQLFENVM
*
>P1;ENSORLG00000010149

MGAVV-----GTL------T-MQTKQ-------------------RRPSR
DKTEDELEMTTVCHRPEGLDQLEAQTNFTKQELQILYRGFKNECPSGVVN
EETFKHIYAQFFPHGGRFYFLCNFLLNDLFVNRLIAVVADASTYAHYLFN
AFDTTNNGSIKFKDFVMGLSTLLRGTLREKLEWTFHLYDINRDGYINREE
MTEIVRAIYDMMGKYTYPAIKGDVPQQHVDAFFQQKMDKNKDGVVTLEEF
VVACQEDETMMRSMQLFENVM
*
>P1;ENSGACG00000020318

MGAVV-----GTL------T-MQTKQ-------------------RRPSR
DKIDDELEMTTVCYRPEGLDQLEAQTNFSKQELQILYRGFKNECPSGVVD
EDTFKHIYAQFFPHGA-----------------------DASMYAHYLFN
AFDTTNNGSIKFKDFVVGLSTLLRGSMREKLEWTFYLYDINRDGYINREE
MTEIVRAIYDMMGKYTYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEF
IMACQEDETMMRSMQLFENVM
*
>P1;ENSAMXG00000010139

MAGCTSRCRQGVL------KLIQSFQRLVS---------------GTLTK
DKVDDELEMTMVCHRPEGLEQLEAQTNFSKQELQVLYRGFKNECPSGVVN
EETFKHIYAQFFPHG------------------------DASTYAHYLFR
AFDTTNNGSIKFEEFVMGLSTLLRGTVRDKLEWTFHLYDINRDGFISKEE
MTDIVRAIYDMMGKYTYPALKGDVPKQHVDAFFQ-KMDKNKDGVVTLEEF
VLACQEDETMMRSMQLFENVM
*
>P1;ENSONIG00000001865

MGAVV-----GTL------T-MQTKQ---N---------------RRPSR
DKTDDELEMTMVCHRPEGLEQLEAQTNFTKQELQILYRGFKNECPSGVVN
EETFKHIYAQFFPHG------------------------DASMYAHYLFN
AFDTANNGSIKFKDFVMGLSILLRGTLREKLEWTFHLYDINRDGYINREE
MTEIVRAIYDMMGKYTYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEF
IVACQEDETMMRSMQLFENVM
*
>P1;ENSGACG00000017881

MGAVV-----GTLT-------MQTKTRRLSRGEKSLFVLTLSYALHTDKS
DKADDDLEMTTVCHRPEGLDQLEALTNFNKRELQVLYRGFKNECPSGIVS
EETFKQIYAQFFPHGA-----------------------DASTYAHYLFN
AFDTAHSGSIKFEDFVTALSILLRGSITEKLQWTFNLYDINRDGYINKEE
MTDIVRAIYDMMGKYTYPVLKNEAPKQHVEAFFL-KMDKNRDGVVTLDEF
ILSCQEDENIMRSLQLFENVI
*
>P1;ENSDARG00000034808

MGVVL-----GTF------S-MHTKQ-------------------VSYRT
DKVDDELEMTMVCHRPEGLEQLEAQTNFSKQELQVLYRGFKNECPSGVVN
EDTFKHIYAQFFPHG------------------------DASTYAHYLFH
AFDTRNNGSIKFEDFVMGLSTLLRGTVRDKLEWTFHLYDINKDGFINKEE
MTEIVRAIYDMMGKYTYPALKGDVPKAHVDAFFE-KMDKNKDGVVTLEEF
VLACQEDENMMRSMQLFENVM
*
>P1;ENSXMAG00000011426

MEGEEQ----RDNS-------LQTIAIVL-LCCG-AAKLLHLL-GVIAVE
DKADDDLEMTIVCHRPEGLDQLEAQTNFSKRELQVLYRGFKNECPSGVVN
EETFKQIYSQFFPHG------------------------DASTYAHYLFN
AFDTGHTGSIKFEDFVTALSILLRGSVTEKLQWTFNLYDINRDGYINKEE
MTDIVRAIYDMMGKYTYPVLKTDAPKQHVDAFFQ-KMDKNRDGVVTLDEF
IFSCQEDENIMRSLQLFENVI
*
>P1;ENSTNIG00000010772

MGAVV-----GTL------T-MQAKQ-------------------RRPSR
DKVDDELEMTTVCHRPEGLEQLEAQTNFSKQELQILYRGFKNECPSGVVN
EETFKHIYAQFFPHGD------------------------ASMYAHYLFN
AFDTSNNGSIKFKDFVTGLSILLRGTVREKLEWTFHLYDINRDGYINREE
MTEIVRAIYDMMGKYTYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEF
IIACQEDETMMRSMQLFENVM
*
>P1;ENSTRUG00000010568

RMEREQ----RDNS-------LHTIVIIL-LCCT-AVKLLHLLGVISVEA
DKIDDDLEMTMVCHRPEGLEQLEALTNFSKRELQVLYRGFKNECPSGVVN
EDTFKQIYSQFFPHG------------------------DASTYAHFLFN
AFDSAHTGSIKFEDFVTALSILLRGSITEKLQWTFNLYDINRDGYINKEE
MTDIVKAIYDMMGKYTYPVLKTDAPKQQVDAFFQ-KMDKNRDGVVTLDEF
ILSCQEDENIMRSLQLFENVI
*
>P1;ENSORLG00000003933

MEGEEQ----SENT-------LQTIVIVL-LGCL-AVKMLHLLGVITVKV
DNADDDFEMTVVCHRPEGLDKLEAQTNFNKRELQVLYRGFKNECPSGAVN
EDTFKQIYSQFFPHG------------------------DASTYAHYLFN
AFDTGHTGSIKFEDFVTALSILLRGSVTEKLQWTFNLYDINRDGYINKEE
MMDIVRAIYDMMGKFTYPVLKTDAPKQHVDAFFQ-KMDKNRDGVVTLDEF
ILSCQEDENIMRSLQLFENVI
*
>P1;ENSXMAG00000000405

MAGCT-----SRCRQGVQKL-IQSLQRLVS---------------GTLTK
DKADDELEMTMVCHRPEGLEQLEAQTNFSKQELQILYRGFKNECPSGVVN
EETFKHIYAQFFPHG------------------------DASMYAHYLFN
AFDTTNNGSIKFKDFVVGLSILLRGTLREKLEWTFHLYDINRDGYINREE
MTEIVRAIYDMMGKYTYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTMEEF
IIACQEDENMMRSMQLFENVM
*
>P1;ENSONIG00000005028

--------------------------------------------YYFYPL
DKADDDLEMTMVCHRPEGLDQLEAQTNFSKRELQVLYRGFKNECPSGVVN
EDTFKQIYSQFFPHG------------------------DASTYAHYLFN
AFDTGHTGSIKFEDFVTALSILLRGSVTEKLQWTFNLYDINRDGYINKEE
MTDIVRAIYDMMGKYTYPVLKNDAPKQHVDAFFQ-KMDKNRDGVVTLDEF
IFSCQEDENIMRSLQLFENVI
*
