>P1;ENSAMXG00000019311

MAAIPSSGSLVATTDYYRRRLGSTSS-SSSCGSSEYSGEVIPHHPGLPKQ
DSGHWWSSFFFGKPNQPGMGTLTEEAQQKGGV-MSVSDGQVMCIARDMVM
KRQA----SESSDAGKSEAGTSPP--S
*
>P1;ENSGACG00000011977

MAAIPSTGSLIATHDYYRRRLGSNSS-NSSCGSAEYTGEVIPHPPGLQRQ
DSGHWWTSFFFAKQNQPGMPNGS-DT-QKNST-YTVANGQVTCVAREMVL
NRKL----SVSSDNGKSETSTPPPTSA
*
>P1;ENSTRUG00000005031

MAAIPAGGSLVATTDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPKQ
DSGHWWSSFFFGKQ--PGMSPLTE---EKAGV-S-AAATNISCVAREMVM
QRQA----SESSDAGSPAS-------S
*
>P1;ENSAMXG00000007577

MAAIPSGGSLVATHDYYRRRIGSTSS-NSSCGSSEYTGEVIPHHPALPRQ
DSGHWWSSFFFGKQNQIGTPNGF-DAQQKTGT-YTVTNGQVTCIAREMVM
KRQL----SESSDSGKPELTTPPA--S
*
>P1;ENSDARG00000031317

MAAIPASGSLVATHDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPKQ
DSGHWWSSFFFGKQNLPGMGTVAEEAQQKSGV-VSVTNGQVTCVAREMVM
-RQA----SESSDGGKSEAGN-----S
*
>P1;ENSONIG00000014865

MAAIPAGGSLVATTDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPKQ
DSGHWWSSFFFGKQ--PGMTPLTEEAQHKAGVSGVVTNGQITCVAREMVM
QRQA----SESSDAGSPTS-------S
*
>P1;ENSONIG00000016786

MAAIPSSGSLIATHDYYRRRIGSTSS-NSSCSSAEYTGEAIPHHPALPRQ
DSDHWWTSFFFAKQNQPGMQNGS-ENQNRNST-YTVANGQVTCIARQMVL
NRQI----SESSENGKSEPMSPPP--V
*
>P1;ENSXMAG00000009169

MAAIPAGGSLVATTDYYRRRIGSTSS-SSSCGSSEYSGEVIPHHPGLPKQ
DSGHWWSSFFFGKQ--PGMTPLTEEAHQKVGVSGAVTTGQITCIAKEMVL
QRQA----SESSEAGSPVS-------S
*
>P1;ENSDARG00000007682

MAAIPSSGSLIATHDYYRRRIGSTSS-NSSCSSSEYTGEVIPHPPGLARQ
DSGHWWSSFFFGKQNQMGTPNGF-ESQQKTGT-YTVTNGQVTCVAREIVM
KRHL----SESSDSGKEP-GSPLP--S
*
>P1;ENSORLG00000018263

MAAIPAGGSLVATTDYYRRRIGSTSSSSSSCGSSEYSGEVIPHHPGLPKQ
DSGHWWSSFFFGKQ--PGMTTLTEEAQQKVGV-LGAAGGQLTCVAREMV-
QRQA----SESSDAGSPAS-------S
*
>P1;ENSGACG00000010310

MASIPAGGSLVATNDYYRRRIGSTSS-SSSCGSSEYTGEVIPHHPGLPKQ
DSGHWWSSFFFGKQ--PGMTPLTEEAQQKAGVQGTVTNGQITCVAQEMVM
QRQSRPDPSRTSEGGRV---------E
*
>P1;ENSORLG00000014723

MAAIPSSGSLIATHDYYRRRLGSSSS-SSSCGSSEYTGEVIPHHPALPRQ
DSGHWWTSFFFTKQNP-A--NGS-DN-QKTRS-YTVANGQVSCIAKEMVL
NRQL----SESSESGKVEPTTPPP--V
*
>P1;ENSTRUG00000005040

MAAIPSSGSLVATHDYYRRRLGSASS-SSSCGSAEYTGEVIPHHPGLPRQ
DSGHWWTSFFFAKQNQPGLQNGS-DL-QKNGT-YTVANGQVTCIAKEMVL
KRQL----SETSDSGKPEQQQTTPVPP
*
>P1;ENSTNIG00000002328

MAAIPSSGSLVATHDYYRRRLGSASS-SSSCGSAEYTGEVIPHHPGLPRQ
DSGHWWTSFFFAKQNQPGLQNGS-DP-QKSGT-YTVANGQVTCIAREMVQ
KRQL----SETSEGGKPEQPAPPTPPS
*
