>P1;ENSTRUG00000008417

MFKEVPVDPMASTDSRLQ-----------------------------QQS
SQKDAADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTVFRNDKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDS
FKAVQDWATQIKTYSWDNAQVILVGNKCDLEDDRLVPTEDGQRLAEELG-
-FQFFEASAKDNINVKQVFERLVDIICDKMSESMEGDNNFLSSQGKQSLK
DSPSESS-GGCAC
*
>P1;ENSORLG00000016555

---------QMALTEPRL----------------------------RQQP
TPNDTADPDFNHMFKLLIIGNSSVGKTSVLFRYADDSFNPAYVSTVGIDF
KVKTVFRNEKRIKLQIWDTAGQERYRSITTAYYRGADGFLLMYDITNQES
FNAVRDWATQVQHYSSKNAQVILVGNKCDMEDDRLITREDGQRLADERG-
-FLFFEASAKENINVKQVFEHLVDVICEQMNTSTDGNAI-NSNHNGLGPG
QGP-EGG-GGCAC
*
>P1;ENSDARG00000101534

---------MASVTDSRL------------------------------QP
SQKDAADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTVFRNNKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMFDITNRDS
FNAVRDWATQIKTYSWDNAQVILVGNKCDLEDERLIPTEDSQRLAHELG-
-FQFFEASAKDSINVKQVFECLVDVICDKMTESLDGDAA-VSNHKDCSLQ
DAADEGH-SACAC
*
>P1;ENSONIG00000018082

---------MALARDPGA------------------------------AH
EQRDPADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTIYRNNKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQES
FCAVQDWATQIKTYSWDNAQVVLVANKLDLEDDRQVPTEDGKRLAKELG-
-FHFFEASAKDNINVKQVFDKLVDVICEKMNESVNGDANPTTNHKGEGLK
DTPNSSR-GGCAC
*
>P1;ENSORLG00000003625

SPF---VRQMALAKVPVA------------------------------VQ
EQRDAADQNFDYMFKLLIIGNSSVGKTSFLFRFADDSFTSAFVSTVGIDF
KVKTIYRNNKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQES
FCAVQDWATQIKTYSWDSAQVVLVGNKLDLEEDRQVPRQDGQRVATELG-
-FQFFEASAKDNINVKQVFDRLVDVICEKMNQSFNGDASPSVSQKGDGLQ
EQPPPSQ-GGCAC
*
>P1;ENSTRUG00000005632

LKL-CPDRQMATARDPAA------------------------------GQ
DPGEASDQNFDDMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTIYRNNTRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQES
FCAVQDWATQIKTYSWGDAQVVLVGNKADLEEERQVPTEDAQRLATELG-
-FRFFEASAKDNINVKEVFDSLVDAICEKMKEGPNGDETPSSGNKGPNLN
ETPSPSQ-RSCAC
*
>P1;ENSXMAG00000017368

---------MALARDLGV------------------------------GQ
EQRDAADQNFDYMFKVLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTIYRNDKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQES
FCAVQDWATQIKTYSWDSAQVVLVGNKMDLEDDRQVPKADAQRVATELG-
-FQFFEASAKDNINVKQVFDKLVDLICEKMNESVNGYTSQPVNQNGDTLK
DKPDTSQ-GGCAC
*
>P1;ENSDARG00000018107

---------MASANDTRH-----------------------------QTQ
VQKDVADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTVYRNEKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDS
FYAVQDWATQIKTYSWDNAQVILVGNKCDLEDDRLVAREDGQRLANELGT
RFQFFEASAKDNINVKQVFERLVDIICDKMNESLDTDPSILTNQKGPSLQ
DTPPDGQSGGCGC
*
>P1;ENSGACG00000019452

---------MALARDPAA------------------------------AA
EQRDAADQNFDYMFKLLIIGNSSVGKTSFLFRFADDSFTSAFVSTVGIDF
KVKTIYRSDKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQES
FCAVQDWATQIKTYSWGNAQVVLVGNKLDLEEDRQVPTEDAQRLATELGC
-FQFFEASAKDNVNVKQVFDELVDVICERMNESVNGDATPLANHDEAGLK
ETPRSGL-AGCGC
*
>P1;ENSGACG00000006453

---------VQSARRQQTGPVITFPSNSVLWDTRQHKRMASNDSRLQQPP
SQKDAADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTVFRNDKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNLDS
FTAVQDWATQIKTYSWDNAQVILVGNKCDLEDDRLVPLEDGQRLSEDLG-
-FQFFEASAKDNINVKQVFECLVDVICQKMNESMEGDMGPEANHRNQALK
DSPSESH-GGCAC
*
>P1;ENSONIG00000008043

ML------QMASTESRLQ-----------------------------QQP
SQKDAADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTVFRNDKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQDS
FNAVQDWATQIKTYSWDNAQVILVGNKCDLEDDRLIPTEDGQRLAEELG-
-FQFFEASAKDNINVKQVFERLVDVICEKMNESMEGDANLIANHSNQGLK
DSPSESH-GGCAC
*
>P1;ENSXMAG00000008795

--------------------------------------MASTDSRLHQPP
SQKDAADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTPAFVSTVGIDF
KVKTVFRNNKRIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDVSNQDS
FSAVQDWATQIKTYSWDNTQVILVGNKCDLEDERVIATEDGQRLAEELG-
-FRFFEASAKDNINVKQVFECLVDIICDKMNETMEEESNLTTNHVTHGSK
DS-SESN-GACAC
*
>P1;ENSAMXG00000000832

---------MASVSDPRQ-----------------------------QTQ
AQKDAADQNFDYMFKLLIIGNSSVGKTSFLFRYADDSFTSAFVSTVGIDF
KVKTVYRNEKRVKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITNQES
FYAVQDWATQIKTYSWDNAQVILVGNKCDLEDDRLVATEDGQRLANELG-
-FQFFEASAKDNINVKQVFERLVDVICDKMNESMDGEPSQMTNHKGPSLQ
DTPPAGQ-SGCSC
*
>P1;ENSTNIG00000006074

---------MALARDPAA------------------------------GQ
DPRDASDQNFDYMFKLLIIGNSSVGKTSFLFRYADNSFTSAFVSTVGIDF
KVKTIYRSNIGIKLQIWDTAGQERYRTITTAYYRGAMGFLLMYDITSQES
FCAVQDWATQIKTYSWGNAQVVLVGNKVDLEEERQVPTEDAQRLATELG-
-FQFFEASAKDNVNVKEVFDSLVDAICEKMNESPNGDAAPSTNNKGPNLN
ETPNPSQ-RGCTC
*
