>P1;ENSTRUG00000010189

LG--------Q---------------------VPRRGMSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNTYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVKP----------GNNTQSSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRAEPSLLHSPSSHF-------P
*
>P1;ENSTNIG00000009086

-----------------------------------RSMSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNTYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPFKPK--------PANNTESSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRAEPSGLPSPGSHF-------P
*
>P1;ENSXMAG00000014072

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNKYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPDQ-------SNNSTVSSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRGESSILQSPSSQF-------P
*
>P1;ENSGACG00000017024

-----------------------------------FDMSPNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNSYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNCVQESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVKPK--------SSNATISAGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNEL
DNRGESSILQSPSSHF-------P
*
>P1;ENSONIG00000010831

-----------------------------------FAMSLNEHSMQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLERDHKYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLKSNA------DEKNGTISSGEAAA
IASTCIMVPFGLVFIMFAVHFYRTLVSHKTDRQIRELEQVI---RLQNQL
EHRAENDDLKAA-VHF-------P
*
>P1;ENSGACG00000011865

ES--------D--------------------SQDVFGMSLNEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLERDHEYPAGLLIAFSAC
TTVLVAVHLFALMVSTCILPNLEAVSNVHNLNSVHESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLK-------------------SAAA
IASTCIMVPFGIVFIMFAIHFYRTLVSHKTDRQIKELEQVI---QLQNQL
DHRAHELCSH---GFLGGQGGLQA
*
>P1;ENSDARG00000004154

-----------------------------------MKMSRSEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDTNHDYPPGLLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPKD-------QKNGTVSAGVAAA
ITSTSIMVPFGLVFIVFAVHFYRSLVSHKTDRQFQELEELE---DLQNEL
DHREEVSTLQSPGSLY-------P
*
>P1;ENSDARG00000011515

----------------------------------PRTMSLNEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVECQLEEDHNYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSIKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPLSQTPVTQKENVTQAPGISEGKAAA
IASTTIMVPFALVFIVFAVHFYRSLVSHKTERQHEELEVLAKITQMQNQL
DQRGDASSIH--------------
*
>P1;ENSTRUG00000005503

-----------------------------------FVMSLSEHSMQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLEREYTYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLKNKD---D-AKGNNGTLSSGEAAA
IASTCIMVPFGLVFIMFAVHFYRTLVSHKTDRQIRELEQVI---RLQNQL
DHRSETDDLKTT-VEF-------P
*
>P1;ENSONIG00000013881

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNSYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHERMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPNK-------SSNSTVSSGVAAA
ITSTSIMVPFGLVFIVFAVHFYRSLVSHKTDRQFEELEELSNLTRLQNEL
DNRGESSILQSPSSHF-------P
*
>P1;ENSAMXG00000005846

-------------------------------------MSLNEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLERDYDYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVKESPHERMHHHIELAW
AFSTVIGTFLFLAEVLLLCWVKFLPLKKDR---EPRNNDNSTVSAGEAAA
YASTCIIVPCGLVFIVFAVHFYRSLVSHKTDRQFQELEELSNLTRLQNQL
DHRVEGPNIQSAPGMF-------P
*
>P1;ENSXMAG00000015181

-----------------------------------VRMSLNEHSMQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLEPTHTYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHRHIELAW
AFSTVIGTLLFLTEVMLLCWVKFLPLKK---------ETNTTISSGEAAA
IASTCIMVPFGLVFIVFAVHFYRTLVSHKTDRQIRELDQVI---QLQKQL
NHGAENDELKAA-GHF-------P
*
>P1;ENSORLG00000012949

-------------------------------------VMSSEHSLQALSW
RKLYLSRAKLKATSRTSALLSGFAMVAMVEVQLEADHVYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNLEAVSNVHNLNSVNESPHERMHHHIELAW
AFSTVIGTFLFLTEVTLLCWVKFLPLKNNK------EVNNGTITSGEAAA
IASTCIMVPFGLVFIVFAVHFYRTLVSHKTDRQIRELEQVI---NLHNQL
DHTAENEELKP--VHF-------P
*
>P1;ENSAMXG00000020637

-------------------------------------MS-SARSLQALTW
RRLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDTSHDYPPGLLIAFSAC
TTVLVAVHLFALMISTCILPNIEAVSNVHNLNAVLESPHERMQRYIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPVRPRN-------QKNGTMPAGVAAA
ITSTSIMVPFGLVFIVFAVHFYRSLVSHKTDRQFQELEELE---DLQNEL
DQGGDASVLQSPTSQ---------
*
>P1;ENSORLG00000008491

SSPGIKTLLDSVTACSSKRSKSQKENSDRAARTVFFNMSLNEHSLQALSW
RKLYLSRAKLKASSRTSALLSGFAMVAMVEVQLDNSYPYPPALLIAFSAC
TTVLVAVHLFALMVSTCILPNIEAVSNVHNLNSVKESPHDRMHRHIELAW
AFSTVIGTLLFLAEVVLLCWVKFLPIKPNK-------SSNNTMSSGVAAA
ITSTSIMVPFGLIFIVFAVHFYRSLVSHKTDRQFQELEELSNLTKLQNEL
DNRGEASI----------------
*
