>P1;ENSDARG00000074719

--------------------MQKEHLFKVLVIGDLGVGKTSIIKRYVHQI
FSQHYRATIGVDFALKVLHWDSQTVVRLQLWDIA-GQERYGNMTRVYYRE
AVGALIVFDVTRSSTFDAVLKWKDDLDLKVSLNNGKPVPAVLLANKSDQS
REGLCSQIPKLDTFCKENGFVGWFETSAKENSNIEAAAKCLVDHILAHEE
NIV-N---------NTDPDVVALPGYNNNTKERVRSRCMTCSKS------
----
*
>P1;ENSORLG00000001857

-----------------VEMQQQEFLFKVLVIGDLGVGKTSIIKRYVHQI
FSQHYRATIGVDFVLKVLQWDNDRVVRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDVTRASTFDAVLKWKDDLDSKVTLSHGRPVPAVLLANKSDQM
----ASQVPKLDSFCRENGFVGWFGTSAKDNTNIEEAARCLVEHILTNEE
SPA-A---------ERESGSLILSGHTNTTKN--HFRCSSCVK-------
----
*
>P1;ENSXMAG00000000327

--------------------MQQELLFKVLVVGDLGVGKTSIIKRYVHQI
FSQHYRTTIGVDFALKVLQWDSDTVIRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDVTRASTFEAVLKWKDDLDAKVTLNHGRPIPAVLLANKSDQI
----ACQLPKLDFFCRENGFVGWFETSAKENTNIDEAARCLVEHIMNNEE
SSV-S---------EREPTSILLSGYASTARS--PLNCSSCLK-------
----
*
>P1;ENSTRUG00000004036

--------------------MQHERLLKVLVIGDIGVGKTSIITRYVHQV
FSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIAEGQERYGNMTRVYYKE
AVGALVVFDMTRLSTFQAVLKWKGDLDSKVALGNGRTVPAVLLANKCDQR
DHGLCPKLPKLESFSREYGFIGWYETSAKDDTNIDAAITCLVKSIMSLEE
ESATAD----------AAGANH----------------------------
----
*
>P1;ENSAMXG00000005910

--------------------MQQEHLFKVLVIGDLGVGKTSIIKRYVHQI
FSQHYRATIGVDFALKVLNWDSQTVIRLQLWDIA-GQERYGNMTRVYYRE
AVGALIVFDVTRASTFDAVLKWKDDLDSKVTLSNGKPVPAVLLANKSDQL
REGVCSQIPKLDTFCKENGFVSWFETSAKENTNIEAAARCLVQHILAHEE
NTV-N---------DSDPDTVTLPGYNNNTKDHGRTSCSACSKY------
----
*
>P1;ENSGACG00000020438

-------VMLRIKQICSAATMQQELLFKVLVIGDLGVGKTSIIKRYVHQI
FSQHYRATIGVDFALKVLQWDRDTVVRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDVTRASTFDAVLKWKEDLDSKVTLNPGRPVPAVLLANKSDQL
----ASQQPKLDSFCRENGFVGWFETSAKENANIEEAARCLVQHILNNEE
SPA-V---------ERDPGAAVLSAYTNTAKD--HLNCSSC---------
----
*
>P1;ENSDARG00000036499

--------------------MQQERLLKVLVIGDLGVGKTSIIKRYVHQI
FSQHYRATIGVDFALKVLNWDHRTVVRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDMTRASTFQAVLKWKKDLDSKVALGNGRPLPAVLLANKCDQQ
RYGLCSKLPKLEHFSRDHGFVGWYETSAKDNTNIDAAIMRLVENIMAVEE
ENVPV---------ESDPSVLILPAFDYNLKERSDSRCSVCTKFQSSIKP
HSEL
*
>P1;ENSTNIG00000003678

CCGSPPARALAVPTPAPVSAMQQERLLKVLVIGDLGVGKTSIITRYVHQV
FSQHYRATIGVDFALRVLDWDHKTVVRLQLWDIA-GQERYGHMTRVYYRE
AVGAL-VFDMTRMSTFQAVLKWKGDLDSKVALGNGRPVPAVLLANKCDQR
AQGLCPKLPKLEAFCRDSGFIGWYETSAKDDTNIEAAIMCLVRSIMSLEE
--------------------------------------------------
----
*
>P1;ENSGACG00000001952

-----------------ARGMQRERLLKVLVIGDLGVGKTSLIKRYVHRV
FSQHYRATIGVDFALKMLSWDQKTVVRLQLWDIAEGQERYGNMTRVYYRE
AVGALVVFDMTRLSTFQAVLKWKEDLDSKVALSNGTPVPAVLLANKCDQR
SHGLCPKLPKLENFSRQCGFVGWYETSAKDDTNIDAAVTCLVESIMAAED
ERATAAR------DEPEGGVLVLPRLDCDAKEKERRGCSGCASL------
----
*
>P1;ENSXMAG00000001484

--------------------MQQERLLKVLVIGDLGVGKTSIIKRYVHQV
YSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIA-GQERYGNMTRVYYRE
ALGALVVFDMTRLATFQAVLKWKRDLDSKVTLSNGKPVPAVLLANKCDQR
QLGLCPKLPKLEKFSQDHGFVGWFETSAKDDTNIDSAITCLVKAITSAEE
EKVSRDA--AP--SESDGGVIVLPRFDHSAKEKGLNDCAGCTSTKPRPGA
-S-D
*
>P1;ENSONIG00000006996

--------------------MQRERLLKVLVIGDLGVGKTSIIKRYVHQV
FSQHYRATIGVDFALKVLNWDHKTVVRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDMTRLSTFQAILKWKGDLDSKVALSNGRPVPAVLLANKCDQR
RHGLCPKLPKLENFSKEYGFVDWYETSAKDNTNIDAAITCLVKSIMSVEE
ERALGEATSGADKGDPDGSVLVLPRFDYNTTEKGLGGCAGCLSIKPKQD-
-Q-D
*
>P1;ENSONIG00000008546

-----------------PAAMQQELLFKVLVIGDLGVGKTSIIKRYVHQI
FSQHYRATIGVDFALKVLQWDSNTVIRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDVTRASTFDAVLKWKDDLDSKVTLNHGRPVPAVLLANKSDQL
----VSQQPKLDAFCRENGFVGWFETSAKENTNIEEAARCLVEHILRNEE
SLV-T---------EREPGSLILSGCTTTSKE--HLGCSSCSKW------
----
*
>P1;ENSAMXG00000003714

--------------------MQQERLLKVLVIGDLGVGKTAIIKRYVHQV
FSQHYRATIGVDFALKVLNWDHRTVIRLQLWDIA-GQERYGNMTRVYYRE
AVGALVVFDMTRASTFQAVLKWKMDLDSKVALNNGRPVPAVLLANKCDQQ
KQGLCARLPKLDTFSRDHGFVGWYETSAKDNTNIDAAIMCLVENILASDV
ENTAV---------DSDPSLLVLPSFDYNLRERSGPGCSACSRRRSTPRD
NSDF
*
