>P1;ENSORLG00000010187

-------------------MAPAQSVFLLAVHVLLISEFILAKRDYYDIL
GVPKDATERHIKKAFHKLALKYHPDRNKGPDAEAKFREIAEAYETLSDDK
RRREYDQFGHSASSTDGPGGEG-------SGHYNFKQHYQ--SFNFDDIF
KDFDAFGQ-Q-RHQHHFHSHNQAHQKRQFDGHFQAHREAMNKQRRVFQHS
SFGGGVFDDMFEDLEKMFSFNGHASRTDGRFQGSAKQHCRTVTQRRGNMV
TTFTDCS--
*
>P1;ENSTRUG00000016807

-------------------MATVQSVLLLAVHVLLISEFILAKRDYYEIL
GVPKDATERQIKKAFHKLALKYHPDRNKGPDAEAKFREIAEAYETLSDDK
RRQEYDQFGHGPSPGDGHRGGGGAD----GGNYNFRQHFQ--SFNFDDIF
KDFSHQ-----HHQHHFHSQNQANHKRHFDSHFQAHQEAMNRHRRQVHRE
GFGGGLFDNMFEDLEKMFSFNTH--RSESRFQGSAKQHCRTVTQRRGNMV
TTFTDCS--
*
>P1;ENSGACG00000004142

-------------------MATAQSAVTFAVCIFVIAELILAKKDYYDIL
GVPKDATERQIKKAFHKLAMKHHPDKNKSPDAEVRFREIAEAYETLSDET
KRREYDQFADTSAYFPGKTQGR-------Q-RQGAHQPF---SFNLNDIF
KDFDTSSQ-N---R-------HTRQQRHFNEDSGSHKESNGRHKRHFQ-G
GFGAGVFDDMYDDIERMFTYDRHAKQSDNRFHGASKQHCRTVTQRRGNMV
TTYMDCTAS
*
>P1;ENSXMAG00000017111

-------------------MAAVQSVLMFAVCVLVITELILAKKDYYDIL
GVPKGATERQIKKAFHRLAMKFHPDKNKSPDAEVRFREIAEAYEVLSDES
RRREYDQFGDDMYTGQTQRAG-------------THQPF---TFNFDDMF
KDFNIYSQ-N---R-------HSRHRRHFEEHSKSHKESHSRRRRHFQ-G
GFGAGILDDMFDDMDRMFTFDRHAKQTEGRFHGTTKQHCRTVTQRRGNMV
TTYTDCTAS
*
>P1;ENSONIG00000016823

-------------------MATAQSTLLLAVHILLISEFILAKRDYYDIL
GVPRDATERQIKKAFHKLALKYHPDRNKDPDAEAKFREIAEAYETLSDDK
KRQEYDQFGHSASSGEGQRGG----------DYDFNQHFKSFNFNFDDLF
KDFDPFGQ-QQQHQHHFHSHSNSHHKRHFDSHFQAHREAMNGHRRQFQQG
SFGGGVFDDMFEDLEKMFSFHTHSSRTENRFQGSGKQHCRTVTQRRGNMV
TTFTDCS--
*
>P1;ENSONIG00000008679

MTACVERKRQTTPRQDTAAMAAAQSVLTFAVCVLVITELILAKKDYYDIL
GVPKGATERQIKKAFHKLAMKYHPDKNKSPDAEVRFREIAEAYETLSDEA
RRREYDQFGDTDGYFNGETQGK-------H-RQGAHQPF---TFSFDDIF
KDFDIYSQ-N---R-------HARHRRHFDEHSRS----HSRHKRHFQ-G
GFGAGMINDMFDDIERMFTFDRHTKQTENRFHGTSKQHCRTVTQRRGNMV
TTYTDCTSS
*
>P1;ENSXMAG00000009211

-------------------MATAQSTLLLAVHILLISEFILAKRDYYEIL
GVPRDAAERQIKKAFHKLALKYHPDRNKGADAEAKFREIAEAYETLSDDK
RRREYDQFGHSASSGEAYQGGRGSRGGGSGDDYNFRQHYQSFHFNFNDIF
KDFDPFGQ-Q--HQHHFHSHHQSHQKRHFDSHFQAHKEAMNRQRRSFQQG
SFGGGMFDDMFEDLEKMFSFNTHTSRTESRFQGSAKQHCRTVTQRRGNMV
TTFTDCS--
*
>P1;ENSDARG00000016886

-------------------MATAQSVFTVAVSILLISELILAEKDYYEIL
GVPKDASDRQIKKAFHKLAMRFHPDKNKSPDAEAKFREIAEAYETLSDDN
RRKEYDQTRSRPFSGGG--------------SEHFHQHF---NFNFEDAF
RHSP-----------------HSHNQRHFQSHFKAHEEARSRHRRHFQ-S
SFGGDMFDDVFQDMERMFSFNGQQ----TRTQGSSRQHCRTVTQRRGNMV
TTYTECS--
*
>P1;ENSAMXG00000001484

-------------------MATAQSTLMFAVCILMITELILARKDYYDIL
GVPKDASERQIKKAFHKLAMKYHPDKNKSPDAEAKFREAAEAYETLSDEK
RRQDYDKLGHGAFSSEGMRGGG----------QYFHQTF---DFNFDEMF
RDFDIYSQ-N---R-------HARPKRHFEDHFRAHQQAHSRHKKHFQ-G
GFGAGVFEDLSDDIERMFTFDRHSKRTDSRFHGTAKQHCRTVTQRRGNMV
TTYTDCTSS
*
>P1;ENSGACG00000018888

-------------------MATVQSALVLAVHVLLISEFILAKRDYYDVL
GVPRDATERLIKKAFHKLALKYHPDRNKGPDAESKFREIAEAYETLSDDK
RRREYDQFGHGPSPGEGHRGGR--------GDYNFNQHYQ--SFNFDDLF
KDADTFGQ-H---RHHFHSQNHAHPQGHFDGHFQAHREAMNRQKRQFQQG
GFGGGLFDDMFEDLEKMFSFNAHGSRTDGRFQGSGKQHCRTVTQRRGNMV
TTFTDCS--
*
>P1;ENSDARG00000052072

-------------------MATAQSTLMFAVCILMITELILARKDYYDIL
GVPKDASERQIKKAFHKLAMKYHPDKNKSPDAENKFREIAEAYETLSDEK
RRREYDRLGHSAFTNDDTNGGG-------GAGQRFHHSF---DFNFDDMF
RDFDIYSQ-N---R-------HARPKRHFEEHFRAHQQQHNRHKRHYQ-G
SFGNGAFEDMFEDMEKMFTFDRHVKRTDSRFQGTTKQHCRTVTQRRGNMV
TTYTDCSSS
*
>P1;ENSTNIG00000018514

-------------------MATVQSVLLLAVHVLLISEFILAKRDYYEIL
GVPKDATERQIKKAFHKLALKYHPDRNKGPDAEAKFREIAEAYETLSDDK
RRQEYDQFGHGPSPGEGPRGGS-------NDNYNFREHFQ--SFNFDDIF
KDFNHFGHQQ-RHQHHFHSQNQANQKRHFDSHFQAHQEAMNRHRRQFHQG
GFGGGLFDDMFEDLEKMFSFNTH--RSESRFQGSAKQHCRTVTQRRGNMV
TTFTDCS--
*
