>P1;ENSTNIG00000009706

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSONIG00000019507

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSONIG00000001168

PFFPFSPRTTQADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSORLG00000017724

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSTNIG00000003843

----------MADQLSEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTSK
*
>P1;ENSAMXG00000009500

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSDARG00000034187

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSXMAG00000001696

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSDARG00000021811

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSTRUG00000003442

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTTK
*
>P1;ENSGACG00000012607

-----ADDDDDADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSXMAG00000009332

-----------ADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
>P1;ENSGACG00000005112

----------MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSL
GQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAF
RVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYE
EFVQMMTAK
*
