>P1;ENSTNIG00000017347

-------------------------------------GEASMFQLPILNF
SPQQVAGVCETLEESGDVERLGRFLWSLPVAP--AACEVLNKNESVLRAR
AVVAFHTGNFRELYHILENHKFT-KESHTKLQALWLEAHYQEAEKLRGRP
LGPVDKYRVRKKFPLPRTIWDGEQKTHCFKERTRHLLREWYLQDPYPNPS
KKRELAQATGLTPTQVGNWFKNRRQRDRAAAAKNRLQQQVL--SGGSG--
---------CS---LA---DEDA----------TVDRLGNSSSPEANLSS
KAA---ASA---------------I-S-ITSSDSECDI
*
>P1;ENSDARG00000025187

-----------------------------------------MFQLPILNF
SPQQVAGVCETLEESGDVERLGRFLWSLPVAP--SACDVLGKNESVLRAR
AVVAFHAGNFRELYHILENHKFT-KDSHAKLQALWLEAHYQEAEKLRGRP
LGPVDKYRVRKKFPLPRTIWDGEQKTHCFKERTRHLLREWYLQDPYPNPS
KKRELAQATGLTPTQVGNWFKNRRQRDRAAAAKNRLQQQVL--SGGSV--
---------RS---LG---DDDT----------TVDRLGPASSPEVSLSS
KAA---TSA---------------I-S-ITSSDSECDI
*
>P1;ENSGACG00000008430

--------------------------------------EASMFQLPILNF
SPQQVAGVCETLEESGDVERLGRFLWSLPVAP--AACEVLNKNESVLRAR
AVVAFHTGNFRELYHILENHKFT-KESHTKLQALWLEAHYQEAEKLRGRP
LGPVDKYRVRKKFPLPRTIWDGEQKTHCFKERTRHLLREWYLQDPYPNPS
KKRELAQATGLTPTQVGNWFKNRRQRDRAAAAKNRLQQQVL--SGGSV--
---------RS---LA---DDDG----------TVDRLGNSSSPEASLSS
KAA---ASA---------------I-S-ITSSDSECDI
*
>P1;ENSTRUG00000010571

---------------------GGGRKNEETGGGEGNTGEASMFQLPILNF
SPQQVAGVCETLEESGDVERLGRFLWSLPVAP--AACEVLNKNESVLRAR
AVVAFHTGNFRELYHILENHKFT-KESHTKLQALWLEAHYQEAEKLRGRP
LGPVDKYRVRKKFPLPRTIWDGEQKTHCFKERTRHLLREWYLQDPYPNPS
KKRELAQATGLTPTQVGNWFKNRRQRDRAAAAKNRLQQQVL--SGGSG--
---------CS---LA---DEDA----------TVDRLGNSSSPEASLSS
KAA---ASA---------------I-S-ITSSDSECDI
*
>P1;ENSORLG00000015761

-----------------------------------------MSILPSFGF
TQEQVACVCEVLQQGGNLERLGRFLWSLPA------CDHLHKNESVLKAK
AVVAFHRGNFRELYKILESHQFS-PHNHPKLQQLWLKAHYVEAEKLRGRP
LGAVGKYRVRRKFPLPRTIWDGEETSYCFKEKSRGVLREWYTHNPYPSPR
EKRELAEATGLTTTQVSNWFKNRRQRDRAAEAKERENSENN--NAGGNKQ
NQLSPLDGGKSLMSSS---EDEFSPPQSPDQNSALLLQGNMNHPGASAYP
MSGLGAPQSVHGMHGHPHQLQDSLLGP-LTSSLVDLGS
*
>P1;ENSAMXG00000019354

-----------------------------------------MSMLPSFGF
TQEQVACVCEVLQQGGNLERLGRFLWSLPA------CDHLHKNESVLKAK
AVVAFHRGNFRELYKILESHQFS-PHNHPKLQQLWLKAHYIEAEKLRGRP
LGAVGKYRVRRKFPLPRTIWDGEETSYCFKEKSRGVLREWYTHNPYPSPR
EKRELAEATGLTTTQVSNWFKNRRQRDRAAEAKERENSENN--NSGANKQ
SQLSPLDGGKSLMSSS---DEEFSPPQSPDQSSVLLLQGNMSHPGAPAYT
MSGLGATQTVHGMQGHPHQLQDSLLGH-LTSSLVDLGS
*
>P1;ENSGACG00000002799

MVFRSPLDFFSASRILRPHFADGPPTQARSRSPEDPPSACPPLALPGLCF
SAAQIASVCETLEETGDIERLARFLWSLPVTA--DGRDSISEHESVQRAR
AVVAYHTGSFRELYHILETHRFT-RTSHGKLQAMWLEAHYREAEKLRGRP
LGPVDKYRVRKKFPLPRTIWDGEQKTHCFKERTRGLLREWYLQDPYPNPG
KKRELAHATGLTPTQVGNWFKNRRQRDRAAAAKNRLQHHRM--CPDGA--
---------RS---FS---GGECSPDGSGERADG----------------
------ETL---------------L-S-VTDSDSDLDV
*
>P1;ENSAMXG00000021319

--------------------------------------RAPMLHLPALSF
SPQQVARVCETLEESGDVARLSRFLWALPP-------DPQRETEAVVRAR
AVVAFHAGEYGELYRLAQSRSFSTPESRASLQRLWLEARYREAESARGRP
LGAVDRYRVRRKFPPPPTVWDGERRAHCFRERARRVLRQSYLREPYPDTR
AKSELARATGLTATQVGNWFKNRRQRDRAAA--NRIQAEVL--SGGSV--
---------HS---LL--GDDEG----------PVDPLSDSSGLGPSNNV
TVA---FST---------------V-SI-SSSDSECEV
*
>P1;ENSONIG00000020118

-----------------------------------------MSILPSFGF
TQEQVACVCEVLQQGGNLERLGRFLWSLPA------CDHLHKNESVLKAK
AVVAFHRGNFRELYKILESHQFS-PHNHPKLQQLWLKAHYVEAEKLRGRP
LGAVGKYRVRRKFPLPRTIWDGEETSYCFKEKSRGVLREWYTHNPYPSPR
EKRELAEATGLTTTQVSNWFKNRRQRDRAAEAKERENSENN--NAGGNKQ
NQLSPLDGGKSLMSSS---EDEFSPPQSPDQNSALLLQGNMSHPGASAYP
MSGLGAPQPVHGMHGHPHQLQDSLLGP-LTSSLVDLGS
*
>P1;ENSXMAG00000013923

-----------------------------------------MFPLPM--F
TPDQVARVCENLEETGDIERLGRFLWSLPAAVPGSAGEALNRHESVMRAR
ALVAFHTGNFEALYQILQSHRFT-RESHAKLQDLWLDAHYREAERLRGRP
LGPVEKYRIRKKFPLPRTIWDGEQKTHCFKERTRSLLREWYLQDPYPNPS
RKRHLAQATGLTPTQVGNWFKNRRQRDRAASAKNRLQQDPSVLPSEGSTD
GALQERHPHPH---LLPTSPRHLGSPEASDCSTETERRGTG---------
------AST---------------P-EISVSSDGEFES
*
>P1;ENSDARG00000026473

-----------------------------------------MSMLPSFGF
TQEQVACVCEVLQQGGNLERLGRFLWSLPA------CDHLHKNESVLKAK
AVVAFHRGNFRELYKILESHQFS-PHNHPKLQQLWLKAHYIEAEKLRGRP
LGAVGKYRVRRKFPLPRTIWDGEETSYCFKEKSRGVLREWYTHNPYPSPR
EKRELAEATGLTTTQVSNWFKNRRQRDRAAEAKERENSENN--NTGANKQ
NQLSPLDGGKSLMSSS---EDEFSPPQSPDQNSVLLLQGNMSHPGASAYS
MTGLGAAQSVHGMQGHPHQLQDSLLGP-LTSSLVDLGS
*
