>P1;ENSDARG00000035056

MS--GKVAKPK--EEKDASKVQDDAAPGTQ----------------EYIM
LRQDSIHSADIRGKGSPFRAKCHEIFCCPLKQVVLKE--NSEPEEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEDSGFTMFNLIPVGLRVVAIQGVQ
TKLYLAMNSEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAVLNGG-KAVSQNES-T
*
>P1;ENSDARG00000056633

MS--GKA-------------------------------------------
------------------------------LLKTKED--KDATKEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEDNSFAIFNLIPVGLRVVAIQGVQ
TKLYLAMNNEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGQIMKGNHVKKTKPAAHFIPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAMLNGG-KTLSQNES-T
*
>P1;ENSAMXG00000008370

LC--FSH-------------------------------------------
--------------I---------------------S--PVNSTEPQLKG
IVTKLYSRQGFHLQLQADGTIDSTKEEDSSYAIFNLIPVGLRVVAIQGVQ
TKLYLAMNNEGYLYTSEHFTQECKFKESVFENYYVTYSSMIYRQ-QSGRG
WYLGLNKEGQIMKGNHVKKTKPAAHFIPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAMMNGG-KALSHNGS-T
*
>P1;ENSAMXG00000000040

MA--AAIASSLIRQKRQAREREKSNA----CR------------------
-----CVSSPSKNKGACEKPSRLSVFSRVKLFGSKKR--RRRRPEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEDSGFTMFNLIPVGLRVVAIQGVQ
TKLYLAMNSEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVTMYREPSLHDLTEFSRS
GSGTPTKSRSASAVLNGG-KAVSQNES-T
*
>P1;ENSONIG00000008596

MSRAAAIASSLIRQKRQAREREKANA----CR------------------
-----GSGSPSNSKGANEKPSKLNVFSRVKLFGSRKKRKRRRPPEPQLKG
IVTRLSSRQGFQLQMQPDGTIDGTKDEDSTYAVFNLIPVGLRVVAIQGVQ
TKLYLAMNNEGFLYTSEHFTPECKFKESVFENYYVTYSSMLYRQQASGRA
WYLGLNKEGGIMKGNHVKKNKPAAHFIPKPLKVAMYREPSLHDLTELSRS
GSGTPTKSRSASALLNGGGKTPSNND-LS
*
>P1;ENSXMAG00000000441

MSRAAAIASSLIRQKRQAREREKANA----CR------------------
-----GSSSPSNSKGANEKPSKLNVFSRVKLFGSRKKRKRRRPPEPQLKG
IVTRLSSRQGFQLQMQQDGTIDGTKDEDSTYALFNLIPVGLRVVAIQGVQ
TKLYLAMNNEGFVYTSEHFTPECKFKESVFENYYVTYSSMMYRQQQSGRA
WYLGLNKEGAIMKGNHVKKNKAAAHFIPKPLKVAMYREPSLHDLTELSRS
GSGTPTKSRSASALLNGG-RKTPSNDDLS
*
>P1;ENSTNIG00000016839

MA--AAIASSLIRQKRQAREREKNNA----CR------------------
-----CVSSPSKTKGNCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEENGYTMFNLIPVGLRVVAIQGVQ
TKLYLAMNSEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAMLNGG-KAVSQNES-T
*
>P1;ENSORLG00000001634

MA--AAIASSLIRQKRQAREREKSNA----CR------------------
-----CVSSPSKTKGNCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKG
IVTKLYSRQGFHLQLQSDGTIDGTKEEDNGYTIFNLIPVGLRVVAIQGVQ
TKLFLAMNSEGYLYTSEHYTLECKFKESVFENYYVTYSSMVYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAVLNGG-KAVSQNES-T
*
>P1;ENSXMAG00000013396

MA--AAIASSLIRQKRQAREREKSNA----CR------------------
-----CVSSPSKAKGSCEKPNRLNVFSRVKLFGSKKR--RRRRPEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEDSSYTMFNLIPVGLRVVAIQGVQ
TKLYLAMNSEGYLYTSEHFTAECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAVLNGG-KAVSQNES-T
*
>P1;ENSONIG00000002720

MA--AAIASSLIRQKRQAREREKSNA----CR------------------
-----CVSSPSKTKGSCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEDNGYTMFNLIPVGLRVVAIQGVQ
TKLYLAMNSEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAVLNGG-KAVSQNES-T
*
>P1;ENSTRUG00000007939

R--AAAIASSLIRQKRQAREREKANA----CR------------------
-----GSSSPSNSKGTNEKPSKLNVFSRVKLFGSRKKRKRRRPPEPQLKG
IVTRLSSRQGFQLQLQPDGTIDGTKDEDSTYTVFNLIPVGLRVVAIQGVQ
TKLYLAMNNEGFLYTSEHFTPECKFKESVFENYYVTYSSMLYRQQASGRA
WYLGLNKEGGIMKGNHVKKNKPAAHFIPKPLKVAMYREPSLHDLTELSRS
GSGTPTKSRSASALLKRW-SPHTHTH-TQ
*
>P1;ENSTRUG00000006744

MA--AAIASSLIRQKRQAREREKNNA----CR------------------
-----CVSSPSKTKGNCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEENGYTMFNLIPVGLRVVAIQGVQ
TKLYLAMNSEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASAMLNGG-KAVSQNES-T
*
>P1;ENSGACG00000020450

M--AFP--------------------------------------------
--------------------------------------LRRSTSEPQLKG
IVTRLSSSQGFQLQMQPDGTIDGTKDEDSTYGVFNLIPVGLRVVAIQGVQ
TKLYLAMNNEGFLYTSEHFTPECKFKESVFENYYVTYSSMLYRQQASGRA
WYLGLNKEGGIMKGNHVKKNKAAAHFIPKPLKVAMYREPSLHDLTELSRS
GSGTPTKSRSASALLNGGGKSPSKND-LS
*
>P1;ENSGACG00000017204

VC--GESSN-----------------PSSFCHGTTAVQDDAAPGTQEYIM
LRQDSIHSADIRSKGSPFRAKCHEIFCCPLKQAVNKE--STEPEEPQLKG
IVTKLYSRQGFHLQLQADGTIDGTKEEDNGYTVFNLIPVGLRVVAIQGVQ
TKLYLAMNSDGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRG
WYLGLNKEGEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRS
GSGTPTKSRSASALLNGG-KAVSQNES-T
*
