>P1;ENSTNIG00000000237

MVTHSKFDNV-MSSS-----LLDSNMRL-PHHYKTFNSKTQYQMVLATLH
KLQESGFYWGPVTGKEANAMLTAEATGTFLIRDSSDNRHLFALSVKTDSG
TKNLRIQCDSSSFHLQTDPKNIQAVPRFDCVLKLVHYYMSQSK-------
-------------------GNSLYYIYSGAEKIPLELIKPLSCSLSTLQH
LCRKTVNGLVGVSSRRDQLPHNLKEFLQEYDAPI
*
>P1;ENSGACG00000002975

VASSGRNPAA-MSSVTPPEGRVQGSNRT-LHHYKPFSSHEHYQQVMRALR
KLQESGFYWGAVGGREASARLRSEPPGTFLIRDSSDHHHFFTLSIQTSRG
PKNLRIHSEGGGFFLQPDPQNTQEPRQFDCVLKLVAHYMSKGPDGGRGRE
APCGGN------SREAEKSGCSAYLIHTSGEKIPLELRRPLSSSLSSLQH
MCRRALNNQE-GSGGAEQLPHRLKDFLEEYDATI
*
>P1;ENSXMAG00000012512

SSKLLDNPAV-NEDC-----FMVANMQK-QYHYKTFVSEDQFLMVLETLR
GLRESDFYWSAITGKEAGIVLARQAPGTFLIRESSDRQHLFTLSVKTKTG
TKNLRIVCEEDSFHLQTDPGNVEKAPRFNCVLKLVDFYIRLGT-------
-------------------SGFVYYINAGGERMPLMLVKPLYLSISPLKH
LCRKKINKDLDISGIKEKLPGKVKEYLDRYQIAL
*
>P1;ENSXMAG00000015743

MSSVTP-----SESS-----RIQGSDLA-PLHYKPFSSHEHYQQVMDAHR
KLLESGFYFGPIGGLEAKALLSKEEPGTFLIRDSSDRRYFFTLSVQTVYG
TRNLRIHSEEGGFFLENDYQNKEKVPRFDCVLKLITFYMGRGRDVQ----
LTMD---------GASEGSMETIYLMDSRGIKTPLELLKPLKISPSSLKH
ICRRALNRTG--QGEMQQLPQALRDFMEKYDASI
*
>P1;ENSONIG00000021386

MVTHSKFDSA-MSSS-----PLDSKMRL-SYHYKTFTSKTQYQMVLSTFQ
KLQESGFYWSTITGKEANAMLASEKVGTFLIRDSADHRHLFTLSVKTASG
TKNLRIQYDSNSFYLQTDPKNVQSVPHFDCVLKLVHFYMAQNKGN-----
-----------------IQSGNIYYIYCSGQKIPLELIRPLSCCMSTLQH
LCRKTVNGHLNISSKRDQLPHNLKDFLQEYDAPI
*
>P1;ENSDARG00000026611

MVTHSRLDSA-MSSS-----PFEGGVRLPPHRYKTFSSREQYQMVLAAVR
KLQESGFYWSTVSGKEASTLLSSEPPGTFLVRDSSDHHHFFTLSVKTATG
TKNLRIQCDSSSFFLQTDPRSEQVVPRFDCVLKLIHHYMPSA-GT----V
S-------------SSNAGEGSAYFIYSGGEKIPLELLRPLASSMSSLQH
LCRKTLNGHIDVSTKRDQLPHPLQEFLQEYDAPI
*
>P1;ENSORLG00000010833

MVALSGRDLLTMSAASASEDKVQGSNLT-PHHFKPFGSHEHYKQVMCAFH
KLQESGFYWGALGGREASSLLRSEPPGTFLIRDSSDHHYFFTLSVKTTLG
TRNLRIHSSEGGFFLQPDPQSTQRIPRFDCVLKLIAHFMGKGTDAG----
---------------GPRDEQNVYLIHTAGEKIPLELHRPLCTSLSTLQH
MCRRTLNDRGLVGTGTEDIPSTLRDFLKAYDAPI
*
>P1;ENSTRUG00000011640

MVTHSKFSNA-MSSS-----LFDSNMRL-PHHYKTFNSKSQYQMVLATLH
KLQESGFYWGAITGKDANVMLAAEDAGTFLIRDSSDNRHLFALSIKTASG
TKNLRIQCDSSSFYLQTDPKNIQTVPHFDCVLKLVHYYMSQSK-------
-------------------GSTLYYIYSGAEKVPLELIKPLSCSLSTLQH
LCRKTVNGLVDVSSRRDQLPHHIKEFLQDYDAPI
*
>P1;ENSGACG00000011015

MVTLSKFDSA-MSSS-----LLDSSMRF-PQRYKTFASKAQYQMVLATLH
KLQESGFYWAAITGKDANAMLADETIGTFLVRDSSDNRHLFALSVKTASG
TKNLRIQCDASSFYLQTDPKNIHSVPHFDCVLKLVHFYMPQSKVN-----
-----------------SRGGNMYFIYSGGEKIPLELVKPLSDSLSTLQH
LCRKTVNGHLDISAKRDQLPHPLREFLQDYDAPI
*
>P1;ENSDARG00000025428

MITHSKLDNA-MSSG-----LFDASMRLPFYHFKTFSSKVQFQLVQHTIR
MLQESGFYWGAISGKEANHLLSSEPSGTFLVRDSSDNRHFFTLSVKTESG
TKNLRVQCDNKSFFLQTDSKSMQSVPRFDCVLRLVQHYMPRSALS-----
----------------IGIPRSSYYIYTGGEKIPLELLRPLQCSMSSLQH
LCRKTVNGHTDVSSKREHLPQQLKDFLQEYDAPI
*
>P1;ENSAMXG00000025210

MVTHSRFDGA-MSSS-----PYQGGVRLSPHRFKTFSSGAQYEMVLAAVH
KLKESGFYWNAVSGKEASSLLSEQPPGTFLVRDSSDHHHFFTLSVKTATG
TKNLRIQCDACSFFLQTDPRSSQAVPRFDCVLKLIHHYMPCARGT----D
ATSSAVQAEGESVDCSSGVDGSAYYIYSGEEKIPLQLLRPLASGMSSLQH
LCRRTLNGHIDVSAKRDQLPQTLQEFLQDYDAPI
*
