>P1;ENSXMAG00000003552

-----PA--APAPAAAAAAPTAT-AA------------------------
----------------------------TE----EAPPVEAAA-AA-APA
TAAAPAEEEEEEEYVVEKVLDRRVVRGKVEFLLKWKGFSDEDNTWEPEEN
LDCPDLIAEYMQKHKEREEKKKESKRKASSEASGDAEERASKKRKEEGDK
ARGFGRGLQPERIIGATDSSGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPTEEEEKKEEEKKD
*
>P1;ENSORLG00000012360

DPPAALS--VRKQC-CRDSTDVVSSSLSRRRRGGHDTFPCSQASGAFRQQ
INQNNRAAFAQLHARHSPVVVIWCGWKFDI--TN-HEAKLTAV-EKKDKK
AEDVAEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSEEDNTWEPEDN
LDCPDLIAEFLQSQKAAH----DGKRKAAGDAEGD--DSKSKKKKDDTEK
LRGFARGLEPERIIGATDSTGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPSEDE-KKDDK--N
*
>P1;ENSTNIG00000003151

--------------------------------------------------
-----------------------------------------AG-KK-GTA
PTAAPAEEEEEEEYVVEKVLERRVVKGRVEFLLKWKGFPNEDNTWEPEEN
LDCPDLIAEFMQKHKEKEEKKKEGKRKVSNEASGDSEERGSKRKKEEGEK
ARGFGRGLQPERIIGATDSSGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPSGTEQRCEEK--R
*
>P1;ENSGACG00000005637

--------------------------------------------------
--------------------------------------------------
-------EEEEEEYVVEKVLDRRVVKGRVEFLLKWKGFSDEDNTWEPHDN
LDCPDLIAEYMQKHKEKEEKKKEGKRKIVSETSGDSEERGSKRKKEESEK
ARGFGRGLQPERIIGATDSSGELMFLMKW---------------------
----------------------------
*
>P1;ENSDARG00000054442

-----MS--QTSEP-SADAA-VT-EAP-----------------------
----------------------------VS---QSEPKQITA--GKKQNK
KKVEEVVEEEEEEYVVEKVLDRRVVKGKVEYLLKWKGFSDEDNTWEPDEN
LDCPDLIAEFLQSQKTAE----SG-GKRRAETDGDGKE--TKKRKDEPEK
LRGFARGLDPERIIGATDSSGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPTEEEEKKDDK--N
*
>P1;ENSAMXG00000010559

-----MS--QITETPPVEAPKVT-EVL-----------------------
----------------------------TDPPPQTEAKPVTAG-GKKQNK
KKVEEVVEEEEEEYVVEKVLDRRIVKGRVEYLLKWKGFTDEDNTWEPEEN
LDCPDLITEYLQSQRNAS----ESGFKRRSDTDGDVKESQSKKRKDEPEK
LRGFARGLDPERIIGATDSSGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPTDEEEKKDEK--N
*
>P1;ENSTRUG00000012203

-----MS--QTTES-SNDGPTVVVNG------------------------
----------------------------LS--DPTETTKMTSA-EK-EKK
PDDVPEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSDEDNTWEPEDN
LDCPDLIAEFLQSQKSAQ----EGKRKAGGEVEGE--ESKAKKKKDDPEK
LRGFARGLVPERIIGATDSTGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPTEDE-KKDDK--N
*
>P1;ENSONIG00000006190

-----VK--LATQAA-KKPKKAE-EE------------------------
----------------------------EQ---PAAAPPAAA--GA-AAA
PVAGAAEEEEEEEYVVEKVLDRRVVKGKVEFLLKWKGFSDEDNTWEPEEN
LDCPDLIAEYMQKHKEKEEKKKESKRKAASETSGDGEERGSKRKKEEGEK
ARGFGRGLQPERIIGATDSSGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPTEEEEKKEED--K
*
>P1;ENSONIG00000018212

--------------------------------------------------
---------------------------------------MTSA-EKKDKK
ADEVAEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSDEDNTWEPEEN
LDCPDLIAEFLQSQKSAH----DGKRKAAGEAEGD--DSKSKKKKDDTEK
LRGFARGLDPERIIGATDSTGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPSEDE-KKDEK--N
*
>P1;ENSGACG00000003918

-----MS--LTTEP-PNDVPAVT-QG------------------------
----------------------------FN--DQ-SNYVPCSDPSEPESK
M-AAVEKDKKPDEYVVERVLNRRVVKGRVEYLLKWKGFSEEDNTWEPDDN
LDCPDLIAEFLQSQKSAH----DGKRKAAGDAEGD--ESKTKKKKDDTEK
LRGFARGLDPERIIGATDSTGELMFLMKWKNSDEADLVPAKEANGKCPQV
VISFYEERLTWHSYSAEGE-KKEEK--N
*
>P1;ENSDARG00000004189

-----MSMSQPTET-VSDAPSVT-EE------------------------
----------------------------VS---PDSKLAATAG-KK-QTK
KKVEDVVEEEEEEYVVEKVLDRRVVKGRVEYLLKWKGFSEEDNTWEPEDN
LDCPDLIAEYMTKHKINDDKKESSAKRKESDTDGGGEDSRPKKRKDEQDK
PRGFARGLDPERIIGATDSSGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPSEEEEKKDDKN--
*
>P1;ENSTNIG00000010097

--------------------------------------------------
---------------------------------------VTSA-EK-EKK
PDDVPEEEEEEEEYVVEKVLNRRVVKGRVEYLLKWKGFSDEDNTWEPEDN
LDCPDLIAEFLQSQKSAQ----EGKRKAGGEVEGE--ESKAKKKKDDPEK
LRGFARGLVPERIIGATDSTGELMFLMKWKNSDEADLVPAKEANVKCPQV
VISFYEERLTWHSYPTEDE-KKEDK--N
*
