>P1;ENSGACG00000010656

MMEEIDRFQVPSAVQEAEMQAEMQPL---DPASSTASEADSDTREVEPVT
INYKPSPLQRKIEKQRELARKGSLKNSNAVGSPVNQQPKKNNNVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-RHLR
SQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATSSTT
CQIQ
*
>P1;ENSXMAG00000018218

MMEEIDRFQVPPV------NGETQPL---DPAASSTLEVASDT-KGESVA
MNYKPSPLQVQIEKQRDLARKASVKNG-TVGSPVNQQPKKN----ARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAPSTA
CQIQ
*
>P1;ENSAMXG00000008635

MMEEIDRFQVPAG------NSETQPL---DPAATSTSEPDADTREAETTA
INYKPSPLQVKIEKQRELARKGSAKNG-TVGSPVNQQPKKN-NVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQASSSTA
CQIQ
*
>P1;ENSONIG00000019458

MMEEIDRFQVPPV------NGETQPLVRDDPAASSTSEAEPDT-KGESVA
MNYKPSPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPKKN----ARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAPSTA
CQIQ
*
>P1;ENSORLG00000010685

MMEEIDRFQVPSAVQEAEMQSEMQPL---DPAASTASEAHSVTREGEPVT
INYKLSPLQRKIEKQRELARTGSLKNCNTVGSPVNQQPKKN-NVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAENIVSAE
RQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQAASSTT
CQIQ
*
>P1;ENSONIG00000011791

MMEEIDRFQVPSAVQEAEMQAEMQPL---DPASSTASEADSDTREGEPVT
INYKPSPLQMKIEKQRELARKGSLKNGNTVGSPVNQQPKKN-NVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATSSTT
CQIQ
*
>P1;ENSORLG00000008972

MMEEIDRFQVPPV------NGETQPL--QDPAASSTSEAETDP-KGESVA
LNYKPSPLQVQIEKQRDLARKASVKNG-TVGSPVNQQPKKN----ARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAASSTA
CQIQ
*
>P1;ENSDARG00000013813

MMEEIDRFQVPT-------EAEMQPF---DPASSTTSEADSDTRESEPAT
LNYKPSPLHMKIDKQRELVRKGSLKNG-NAGSPVNQQPKKN-NVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-RSLR
EQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNSTCMCCQATSSTA
CQIQ
*
>P1;ENSXMAG00000001430

MMEEIDRFQVPSAVQEAEMQSEMQPL---DPASSTASEAESDTREGEAVT
INYKPSPLQMKIEKQRDLARKGSLKNNNTVGSPVNQQPKKN-NVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATSSTT
CQIQ
*
>P1;ENSDARG00000016396

MMEEIDRFQVPPV------NPEMKLL--QDPAETSTIENETAPREPESVA
INYKPSPLQVKIEKQRELARKGSVKNG-TVGSPVNQQPKKN-NVMARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKSVNPTCMCCQATSSTA
CQIQ
*
>P1;ENSGACG00000008695

MMEEIDRFQVPPV------NGETQPLIPQDPAASSSSEADADA-KGETVA
MNYKPSPLQVQIEKQRDHARKGSVKNG-TVGSPVNQQPKKN----ARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAPSTA
CQIQ
*
>P1;ENSTRUG00000015586

MMEEIDRFQVPPV------NGETQPL---DPAASTTSEGQPDA-KGETVA
MNYKPTPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPKKN----ARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAEV-RCLR
DQQINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAPSTA
CQIQ
*
>P1;ENSTNIG00000010681

-MEEIDRFQVPPV------NGETQPL---DPAASTPSEGQPDA-KGETVA
MNYKPTPLQVQIEKQRDLARKGSVKNG-TVGSPVNQQPKKN----ARTRL
VVPNKGYSSLDQSPDEKPLVALDTDSDDDFDMSRYSSSGYSSAE------
--QINQDLNIQLLKDGYRLDEIPDDEDLDLIPPKAVNPTCMCCQAAPSAA
CQIQ
*
