>P1;ENSONIG00000015040

LNWATWHVKSSLICHILYYFQPKCKISASRKLSLKILLLTRATEDLEAE-
KAANEEEKVRYLREKLPPLQLSGLNIDDLQKVCKEIHEKIHLVDEDRYDC
EAKVLKNYRDINELQLKVQDLGGKFKKPALRKVRVSADEMLKALFGSKTK
GSMDLRANLKSVKKEDIKQEKELTMEVGDWRKNVEAMSGMQGRKKMFDAA
GGA--Q
*
>P1;ENSXMAG00000005430

-------------MNPK-GDKPKSKISASRKLSLKMLLLQRACEDLERE-
RQEREEEKGRYLKEKLPPLQLSGLSLDDLQKLCKQLHEKIDIVDEERYDC
EHKVSKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTG
GGA--Q
*
>P1;ENSAMXG00000005689

QGRP--------KGNPKAFDKPKCKISASRKLSLKMLLLNRAMEDLERE-
KQDRDEEKIRYLDEKMPPLQLAGLSLADLQNLCRELYEKIDVVDEERYDC
ENKVIKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDIKQEKVLTSEVGDWRKNVEAMSGMEGRKKMFDAA
GGG--Q
*
>P1;ENSGACG00000019744

------------------SHKKLPIVSSGHCLTLYISTETR----LQVKK
AAAFLCEKVRYIGENLPPLQLSGLSVDELQKMVKELHSRIDVVDEERYDC
ESKVGKHNKDIHELKLKIQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRSNLKSVKKED-----VLTSEVGDWRKNVEAMSGMEGRKKMFDTA
GGP--Q
*
>P1;ENSORLG00000014669

PHRT-------RAMNPK-WDKPKSKISASRKLSLKMLLLTRACEDLEKE-
KLEREEEKVRYLGEKLPPLQLSGLSLDELQKLCKQLHEKIDVVDEERYDC
EHKVVKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTG
GGA--Q
*
>P1;ENSGACG00000012962

L----------------YYFQPKSKISASRKLSLKILLLTRATEQLEAE-
KAAREEEKVRYLAEKLPPLQLLGLNRDDLQKVCTEIHEKIDNADEERYDY
EHKVFKNSRDIHQLNLKVQDLGGKFKKPALRKVRVSADEMLKALFGSKNK
ASMDLRANLKSVKKEDIKQEKELTLEVGDWRKNVEAMSGMEGRKKMFDFS
SRPLMK
*
>P1;ENSTRUG00000015573

-------------MN-K-GEKPKSKITASRKLSLKKLLLTKACEDLEQE-
KQEREEEKVRYLGDKIPPLQVSGMAMEDLQNLCKQLHSKIEVVDEERYDC
ESKVKKHNNDIHELKLKIQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTG
GAG--Q
*
>P1;ENSDARG00000073766

MGDPI-----RRPGNPKVDNKPKSKISASRKLSLKIMLLNRAMEDLERE-
KQERLEEKNCYLKEKHPPLQLSGLSLEELQNLCKQLYSKIDTVDEERYDY
EDKVKKHNKDINELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDIKQEKVLTSEVGDWRKNVEAMSGMEGRKKMFDAA
GGG--Q
*
>P1;ENSDARG00000042559

MADDD--T--PQPLGPRVQAKPKSKISASRKLSLKILLLQRAMEELEQE-
KVSRDEEKVKYLSEKLPPLQITGLQLEELQKLCRQLHAKIDSVDEERYDF
EAKVVKNNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDIKQEKVMSTEVGDWRKNVEAMSGMEGRKKMFDAA
GGG--Q
*
>P1;ENSAMXG00000003900

SSMQD--A--PSPMSPRPQAKPKSKISASRKLSLKILLLQRAMEDLEQE-
KTDRDEEKVRYLGEKLPPLQLSGLAMDELQKLCKQLHAKVDAVDEERYDF
EAKVVKNNKEIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDIKQEKVLTTEVGDWRKNVEAMSGMEGRKKMFDAA
GG---Q
*
>P1;ENSONIG00000011575

-------------MNPR-GEKPKSKISASRKLSLKMLLLTRACEDLEKE-
RQEREEEKVRYLGEKLPPLQLSGMPLKELQELCKQLHTKIDIVDEERYDC
ESKVNKHNKDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTG
GGA--Q
*
>P1;ENSTNIG00000011034

-------------MN-K-GEKPKSKISASRKLSLKKLLLTKACEDLEQE-
KQEREEEKVRYLGEKIPPLQVSGLSLEELQNLCRQLHSKIDVVDEERYDC
ESKVKKHNNDIHELKLKVQDLGGKFKKPALRKVRVSADEMMRALLGSKHK
GSMDLRANLKSVKKEDVKQDKVLTSEVGDWRKNVEAMSGMEGRKKMFDTG
GVA--Q
*
