>P1;ENSTRUG00000005896

--KP-------------KM-PSKN-DDGGWKKFMWNSETGELLGRTGGSW
FKILLFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTWQDRVAPPGLSHTPK
SDKTEMSYNPDEFETYLPYTKALREFLSKYDEEAQMDPMKFEDCGEEPAD
YKNRGELES-DMGVRKACRFSRTVLGPCSGLDD---REFGFKEGKPCVIV
KLNRIVNFRPRPPSSNDTIPEDAQHKVQPNVIPIFCTNKREEDAGKIGEI
KYYGIGG--GFPMQYYPYYGKLLHSHYLQPLVALQFTNLTRNTELRIECK
VFGDNIDYSEKDRYQGRFDIKFQINT-S
*
>P1;ENSORLG00000020664

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------D-NAGVRKACRFSRTLLGPCSGLED---ETFGFKDGKPCVIV
KLNRIVNFRPRPPSSNDSIPEEAWPKVQPNLIPLFCTNKREEDADKIGEI
KYYGING--GFPLQYYPYYGKRLHPHYLQPLVAVQFTNLTQNMELRIECK
VFGDNIDYNEKDRYQGRFDLKIQINS-V
*
>P1;ENSONIG00000019331

--MS----------------GNKD-SDGGWKNFVWNSEKKEFLGRTGGSW
FKILLFYVIFYGCLAGIFVGTIQALLLTLSKDKPTYQDRVAPPGLSHTPR
SDKSEISFTRSDQSSYSKYVQSMNEFLELYNDTKQNG-DPYEECGKFPGT
YKDRSMEE-----KKKVCKFLRSWLKNCSGITD---PDYGFMEGSPCVII
KLNRIVNFRPKAPS-NNSLLEELQAKITPNEIPIYCKPKRAEDKGQIEEI
KYFGISQ--GFPLQYYPYYGKQLHPDYLQPLMAVQFVNVTVGKEIRIECK
AFGDNIDYSEKDRYQGRFDIKLTVS---
*
>P1;ENSTNIG00000013777

K-MS----------------RNKE-NDGGWRTFLWNSEKGEFLGRTGCSW
FKILLFYVIFYLCLAGIFAGTIQVLLLTLSSYKPTYQDRVAPPGLSHFPR
SDKAEISFSLSDNKTYGAYIQSISKFLHLYHQDMQTDQMKYEDCAAVPAT
YTEREPLES-DAGQRKACRFSASLLGSCSGESD---PTYGFSKGRPCIIV
KLNRIVNYRPKAPS-VESLPEALQGKVSPFVIPIHCKTKRAEDENKIGEI
NYFGIGN--GFPLQYYPYYGKLLHPMYLQPLVAVQFNNVTLDQEIRIECK
AYGANIKYSDKDRYQGRFDIKLTISS--
*
>P1;ENSAMXG00000011833

--MP----------------ANKD-GDGGWKSFLWNSEKKEFLGRTGCSW
LKIFIFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTYQDRVAPPGLSHTPR
SEKAEISYSLSDEDTYRFLTKAMKELLEPYSEEKQTDENQFEDCGENPAM
YKNRGELES-DMGKRKACRFKKSWLGACSG-EDP---HFGFKDGKPCILV
KLNRIVNFRPKAPA-NSSLPVNLQGKVQANLIPIHCSSKKEEDAGKIGEI
KYHGMGS--GFPLQYYPYYGKLLHPQYLQPLVAVQFVNITQNTDLRIECK
VYGENIDYSEKDRYQGRFDLKLYVK--S
*
>P1;ENSXMAG00000016407

--MA----------------GKKE-SDGGWRKFLWNSEKREFLGRTGGSW
LKIFLFYVIFYGCLAAIFIGTIQALLLTIHEFKPTHQDRVAPPGLSHTPR
SDKSEISFKISDPASYQRYTASMMAFLKPYSKEEQDKDSNYEDCSESPKT
YTDRGKLED-DHGVRKSCYFYRSHLGSCSGETD---ESFGFSEGKPCLIV
KLNRIVNFRPKPPTNNSTLPDGLKGKTFENYIPIHCKNRREEDESKIGEI
KYFGLGGLAGFPLQYYPYYGKRLHPNYLQPLVAIQFTNLTLKEELRIECK
VYGDNIDYNEKDRYQGRFDVKFTVN--S
*
>P1;ENSGACG00000015312

--TT--------------M-SSTK-DDGGWKRFVWDSDKGELLGRTGGSW
LKIIGFYIIFYGCLAGVFVGTIQALLLTLSNYKPTWQDRVAPPGLSHTPR
SDKSEVSFNLNDVETYLPYTKALKDFMAKYNEDIQKDQMKFEDCTDSPAD
YKNRGDLES-DQGIRKACRFYRNLLGPCSGLDD---PDFGFKEGKPCIIV
KLNRIVNFRPKPPTSNESIPDEAQHKVQPNVIPIYCTNKREEDAGKIGEI
KYHGIGG--GFPLQYYPYYGKLLHPQYLQPLLALQFTNLTLNTELRIECK
VFGDNIGYSEKDRYQGRFEIKLSIN--S
*
>P1;ENSXMAG00000009766

--MP----------------SNK--DDGGWKEFLWNSEKGELLGRTGGSW
FKVALFYVIFFGILAGIFVGTIQAMLMTLSENKPTWQDRVAPPGLSHTPR
VDKAEVFFNVRESETYLRYVKAMRDFMKLYDDNIQTNNMLFEDCGEQPAD
YKHRGDLES-DMGGVKACRFPKTLLGPCSGIED---NDFGFKDGKPCLIV
KLNRIVNFRPRPPSNNDSIPEEAKPKVQANIIPLYCTNKREEDADKIGEI
KYYGIGE--GFPLQYYPYYGKRHHPQYLQPLVALQFTNLTRNTELRIECK
VFGENLYYNEKDRYQGRFDIKIQVD--S
*
>P1;ENSORLG00000015696

--MS----------------GNKESSDGGWRKFMWNSEKGEFLGRTGCSW
FKIFMFYLIFYGCLAGIFIGTIQALLLTLSNYKPTYQDRVAPPGLSHTPR
SDKSEISFKMSDNSTFKKYVDSMNELLLKYDEDRQTAQGKYESCGENPDT
YKEQGGLEE-GSGQRTSCRFLRKWLGDCSGLTD---NTYGFKEGKPCLIV
KLNRIVFFRPKGPSNNSTLPEALQGKSYNNLIPVYCKNKRPEDASKIGEI
KYFGFGG--GFPLQYYPYYGKQLHPNYLQPLVAIQFTNLTIGEDLRIDCR
VFGDNIAYSEKDRYMGRFDVKITVN--S
*
>P1;ENSDARG00000076833

--NSLLKWTN-KTLQY-TMPAQNK-DDGGWKKFVWNSEKKEFLGRTGGSW
AKIFLFYLIFYGCLAGIFIGTIQILLLTLSDYKPTWQDRVAPPGLTHFPR
SDKSEIAINLDDEVSFLNYVKVMREFLTSYDQEKQLDNMQFENCGESPLD
YKNRGDLES-DVGVRRACQFSREWLGPCSGLDD---PYFGFKEGKPCLIA
KLNRIVNFRPKPPVSNESIPEEVQHKVQPYLIPIHCTNKKEEDAGKLGEV
RYYGFGG--GFPLQYYPYYGKLLHPQYLQPLVAIQFLNITPNTDMRIECK
VYGENIYYHDKDRYQGRFDVKFNIKK-S
*
>P1;ENSONIG00000003739

--MP----------------SDKK-DDGGWKKFLWNSETGELLGRTGGSW
FKITLFYVIFYGCLAGIFIGTIQAMLLTLSEYKPTWQDRVAPPGLTHTPR
SDKAELAFNPRAVETFLPHTKALREFLNNYDESKQKDQMKYEDCGDEPAD
YKNRGDLDS-DVGVRKACRFPRALLGPCSGLED---TEFGFKEGKPCLIV
KLNRIVNYRPRPPTSNESIPEEAQPKVQPNVIPIYCTSKKEEDADKIGEI
KYYGIGE--GFPLQYYPYYGKKLHPQYLQPLVALQFTNLTRNTELRIECK
VFGDNIDYSEKDRYQGRFEIKIQVDE-S
*
>P1;ENSTNIG00000014477

--KP-------------KM-PSKN-DDGGWKKFMWNSETGELMGRTAGSW
FKIILFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTWQDRVAPPGLSHTPR
ADKAELSFNILEFETYLPHTKALREFLTKYDDEAQMDSMKFEECGNEPAE
YRNRGELES-DMGVRKACRFNRELLGPCSGLVD---REFGFKEAKPCVIV
KLNRIVNFRPRPPSSNDSIPEEAQYKVQPNVIPLYCTSKKEEDAGKIGEI
KYYGIGG--GFPMQYYPYYGKLLHPHYLQPLVALQFTNLTLNTELRIECK
VFGDNIHYSEKDRYQGRFDIKIQINT-S
*
>P1;ENSDARG00000013144

--MP----------------ANKD-GDGGWKSFIWNSDKKEFLGRTGCSW
LKIFIFYVIFYGCLAGIFIGTIQAMLLTLSNYKPTYQDRVAPPGLSHSPR
PDKAEISYNINDESTYMPYVNHIDAFLKAYNQDIQEDNTKFEDCGDKPEF
YTDRGELES-DNGVRKACRFRREWLGECSGQKDEKQKNYGFDDGQPCLIV
KLNRIVNFMPRPPASNDSIPEAVRPKLQGNVIPIHCSSKREEEANLLGQI
KYFGVGN--GFPLQYYPYYGKLLQPQYLQPLVAIKFYNITTDVDVRVECK
VYGENIDYSEKDRSQGRFDIKFTIKTKS
*
>P1;ENSTRUG00000004970

FKMS----------------RNKD-NDGGWRTFVWNSEKGEFLGRTGCSW
FKILMFYVIFYLCLAGIFAGTIQVLLLTLSNYKPTYQDRVAPPGLSHFPR
SEKAEIYFSLSDAGSYQTYTQSIEKFLDVYQDDKQLDQLNYDDCGAAPGT
YTERGSLES-TEGQRKACRFSKSLLGSCSGDGD---PTFGFSQGKPCIIV
KLNRIVNYRPKPPS-NESLPEALQGKVSPNVIPIHCKPKRAEDEDRIGEI
NYFGIGN--GFPLQYYPYYGKLLHPMYLQPLVAVQFTNVTLNQEVRIECK
AYGKNIDYSDKDRYQGRFDIKLTISS--
*
>P1;ENSGACG00000013647

--MQ----------------ANKD-SDGGWRTFVWNSEKKEFLGRTGSSW
LKIFLFYVIFYGCLAGIFIGTIQALLLTLSNYKPTYQDRVAPPGLSHTPR
SEKSEIAFSLSDASSYKKYTDAMTKFLKKYDDDKQTDQMKFEDCGGVPEN
YKDRGAPEDNNPGQRIGWRLKRSLVGVWPRLGN----RSGFHTREAWLIV
KLNRIVNFSFQPPM-NNSVEEFLLPKLKPNLIPIFCKNKREEDADKIGEI
KFFGLGE--GFPLQYYPYYGKLLHPQYLQPLVAIQFNNLTLNEELRIECK
VFGENIGYSEKDRYQGRFDVKFNIA--S
*
>P1;ENSLOCG00000008556

--LSKKKKSNSRTNTQKMAGANKE-GDGGWKKFIWDSEKKELLGRTGSSW
SKILLFYFIFYGFLAGIFIGTIQALMMTINSYKPTYQDRVAPPGLTHTPR
LTKTEISFNPNEEDSYRDYRIAMNNILKQYEEKTQMDDMKFENCGEIPST
YINRGDLNA-DQGTKKACRFKRSWLGNCSGIDD---PNFGYKYGKPCMIV
KLNRIVNFRPKPPATNESIPEEFRDRVQPNIIPVICTNRREEDAGKIGLI
QYYGFGG--GFPLQYYPYYGKLLHPQYLQPLVAIQFTNLTLNTELRIECK
AYGQNIEYHEKDRFQGRFDIKIEIK--S
*
