>P1;ENSTNIG00000013112

MGAVV-----GTLT------MQTKQ-R-----------------------
-----RPSRDKIDDDLEMTMVCHRPEGLEQLEAQTNFSKRELQVLYRGFK
NECPSGVVNEDTFKQIYSQFF----------PH----------------G
------------------------DASTYAHFLFNAFDSAHTGSIKFEDF
VTALSILLRGSITEKLQWTFNLYDINRDGYINKEEMTDIVKAIYDMMGKY
TYPVLKTDAPKQHVDAFFQ-KMDKNRDGVVTLDEFILSCQEDENIMRSLQ
LFENVI
*
>P1;ENSDARG00000102210

--------------------------------------------------
--------------DLELSIVCHRPEGLEQLEAQTNFNKKELQVLYRGFK
QECPSGVVNEETFKQIYSQFF----------PH----------------G
------------------------DASTYAHYLFNAFDSSHNGSIKFEDF
VTALSILLRGTTTEKLEWTFNLYDINRDGYINKE----------------
--------------------------------------------------
------
*
>P1;ENSTRUG00000007648

MGAVV-----GTLT------MQAKQ-------------------------
----RRPSRDKADDELEMTTVCHRPEALDQLEAQTNFSKQELQILYRGFK
NECPSGVVNEETFKHIYAQFF----------PH----------------G
GCTE---------GCVAD-VMCAAYASMYAHYLFNAFDTANNGSIKFKDF
VTGMSILLRGTVREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMGKY
TYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEFVIACQEDETMMRSMQ
LFENVM
*
>P1;ENSORLG00000010149

MGAVV-----GTLT------MQTKQ-------------------------
----RRPSRDKTEDELEMTTVCHRPEGLDQLEAQTNFTKQELQILYRGFK
NECPSGVVNEETFKHIYAQFF----------PH----------------G
GRFYFLCNFLLNDLFVNRLIAVVADASTYAHYLFNAFDTTNNGSIKFKDF
VMGLSTLLRGTLREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMGKY
TYPAIKGDVPQQHVDAFFQQKMDKNKDGVVTLEEFVVACQEDETMMRSMQ
LFENVM
*
>P1;ENSGACG00000020318

MGAVV-----GTLT------MQTKQ-------------------------
----RRPSRDKIDDELEMTTVCYRPEGLDQLEAQTNFSKQELQILYRGFK
NECPSGVVDEDTFKHIYAQFF----------PH----------------G
-----------------------ADASMYAHYLFNAFDTTNNGSIKFKDF
VVGLSTLLRGSMREKLEWTFYLYDINRDGYINREEMTEIVRAIYDMMGKY
TYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEFIMACQEDETMMRSMQ
LFENVM
*
>P1;ENSAMXG00000010139

MAGCTSRCRQGVLK-----LIQSFQ-R-----------------------
-LVSGTLTKDKVDDELEMTMVCHRPEGLEQLEAQTNFSKQELQVLYRGFK
NECPSGVVNEETFKHIYAQFF----------PH----------------G
------------------------DASTYAHYLFRAFDTTNNGSIKFEEF
VMGLSTLLRGTVRDKLEWTFHLYDINRDGFISKEEMTDIVRAIYDMMGKY
TYPALKGDVPKQHVDAFFQ-KMDKNKDGVVTLEEFVLACQEDETMMRSMQ
LFENVM
*
>P1;ENSONIG00000001865

MGAVV-----GTLT------MQTKQ-------------------------
---NRRPSRDKTDDELEMTMVCHRPEGLEQLEAQTNFTKQELQILYRGFK
NECPSGVVNEETFKHIYAQFF----------PH----------------G
------------------------DASMYAHYLFNAFDTANNGSIKFKDF
VMGLSILLRGTLREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMGKY
TYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEFIVACQEDETMMRSMQ
LFENVM
*
>P1;ENSGACG00000017881

MGAVV-----GTLT------MQTKT-RRLSRGEKSL---------FVLTL
SYALHTDKSDKADDDLEMTTVCHRPEGLDQLEALTNFNKRELQVLYRGFK
NECPSGIVSEETFKQIYAQFF----------PH----------------G
-----------------------ADASTYAHYLFNAFDTAHSGSIKFEDF
VTALSILLRGSITEKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMGKY
TYPVLKNEAPKQHVEAFFL-KMDKNRDGVVTLDEFILSCQEDENIMRSLQ
LFENVI
*
>P1;ENSDARG00000034808

MGVVL-----GTFS------MHTKQ-------------------------
----VSYRTDKVDDELEMTMVCHRPEGLEQLEAQTNFSKQELQVLYRGFK
NECPSGVVNEDTFKHIYAQFF----------PH----------------G
------------------------DASTYAHYLFHAFDTRNNGSIKFEDF
VMGLSTLLRGTVRDKLEWTFHLYDINKDGFINKEEMTEIVRAIYDMMGKY
TYPALKGDVPKAHVDAFFE-KMDKNKDGVVTLEEFVLACQEDENMMRSMQ
LFENVM
*
>P1;ENSXMAG00000011426

M--------------------EGEEQRDNSL--QTIAIVLLCCGAAKLLH
LL-GVIAVEDKADDDLEMTIVCHRPEGLDQLEAQTNFSKRELQVLYRGFK
NECPSGVVNEETFKQIYSQFF----------PH----------------G
------------------------DASTYAHYLFNAFDTGHTGSIKFEDF
VTALSILLRGSVTEKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMGKY
TYPVLKTDAPKQHVDAFFQ-KMDKNRDGVVTLDEFIFSCQEDENIMRSLQ
LFENVI
*
>P1;ENSTNIG00000010772

MGAVV-----GTLT------MQAKQ-------------------------
----RRPSRDKVDDELEMTTVCHRPEGLEQLEAQTNFSKQELQILYRGFK
NECPSGVVNEETFKHIYAQFF----------PH----------------G
------------------------DASMYAHYLFNAFDTSNNGSIKFKDF
VTGLSILLRGTVREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMGKY
TYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTLEEFIIACQEDETMMRSMQ
LFENVM
*
>P1;ENSTRUG00000010568

R-------------------MEREQ-RDNSL--HTIVIILLCCTAVKLLH
LLGVISVEADKIDDDLEMTMVCHRPEGLEQLEALTNFSKRELQVLYRGFK
NECPSGVVNEDTFKQIYSQFF----------PH----------------G
------------------------DASTYAHFLFNAFDSAHTGSIKFEDF
VTALSILLRGSITEKLQWTFNLYDINRDGYINKEEMTDIVKAIYDMMGKY
TYPVLKTDAPKQQVDAFFQ-KMDKNRDGVVTLDEFILSCQEDENIMRSLQ
LFENVI
*
>P1;ENSORLG00000003933

M--------------------EGEEQSENTL--QTIVIVLLGCLAVKMLH
LLGVITVKVDNADDDFEMTVVCHRPEGLDKLEAQTNFNKRELQVLYRGFK
NECPSGAVNEDTFKQIYSQFF----------PH----------------G
------------------------DASTYAHYLFNAFDTGHTGSIKFEDF
VTALSILLRGSVTEKLQWTFNLYDINRDGYINKEEMMDIVRAIYDMMGKF
TYPVLKTDAPKQHVDAFFQ-KMDKNRDGVVTLDEFILSCQEDENIMRSLQ
LFENVI
*
>P1;ENSXMAG00000000405

MAGCT-----SRCRQGVQKLIQSLQ-R-----------------------
-LVSGTLTKDKADDELEMTMVCHRPEGLEQLEAQTNFSKQELQILYRGFK
NECPSGVVNEETFKHIYAQFF----------PH----------------G
------------------------DASMYAHYLFNAFDTTNNGSIKFKDF
VVGLSILLRGTLREKLEWTFHLYDINRDGYINREEMTEIVRAIYDMMGKY
TYPALKGDVPQQHVDAFFQ-KMDKNKDGVVTMEEFIIACQEDENMMRSMQ
LFENVM
*
>P1;ENSONIG00000005028

--------------------------------------------------
---YYFYPLDKADDDLEMTMVCHRPEGLDQLEAQTNFSKRELQVLYRGFK
NECPSGVVNEDTFKQIYSQFF----------PH----------------G
------------------------DASTYAHYLFNAFDTGHTGSIKFEDF
VTALSILLRGSVTEKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMGKY
TYPVLKNDAPKQHVDAFFQ-KMDKNRDGVVTLDEFIFSCQEDENIMRSLQ
LFENVI
*
>P1;ENSLOCG00000009667

--------------------------------------------------
-------SVDKVEDELEMTMVCHRPEGLEQLESQTNFTRRELQVLYRGFK
NSVPPSSLTASVSASLQSLCSPLCVSCLYLLPHSLFLSLHHSSPCAPLSV
------------------------SASTYAHYLFNAFDSAHNGSIKFEDF
VMALSILLRGSVREKLQWTFNLYDINRDGYINKEEMTDIVRAIYDMMGKY
TYPALRVEAPKQHVDAFFQ-KMDKNKDGVVTLDEFIASCQEDENIMHSLQ
LFENVM
*
