>P1;ENSAMXG00000004364

RMYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSNNFMHQGLWRYCTPG
KCFTHTDSI----------------------AYWDATRAFMIL---SLLA
CFFGIIIGIMAFIHYSTF--ERFDKTFAAGTLFFISCFFVFLAMAVYTGV
TMNYYGKRYGSWRFSWSYIIGWVAVVLTFFS-GIFYMCAYRMHECPRNPA
PH
*
>P1;ENSONIG00000011143

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSSNYMHQGLWRYCVPG
KCMTHTDSI----------------------AYWDATRAFMIL---SLLA
CFIGIVIGVMAFIHYSSF--DGFDKTFAAGILFFISCFFVLLAMAVYTGV
TVNYYGKRYGSWRFSWSYIMGWVAVVLTFFS-GIFYMCAYRMHECPRNSN
SR
*
>P1;ENSGACG00000010543

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSSNYMHQGLWRYCVPG
KCMTHTDSI----------------------AYWDATRALMIL---SLLA
CFIGIVIGVMAFIHYSS---EGFDKTFAAGILFFISCFFVLLAMAVYTGV
TVNYYGKRYGSWRFSWSYIMGWVSVVLTFFS-GIFYMCAYRMHECPRNST
-R
*
>P1;ENSGACG00000020121

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRQSSNYMHQGLWRYCIPG
KCFPHNDSI----------------------AHLDATRALMIL---SLLA
CFIGIIIGIMAFIHYSSF--DRFDKTFAAGILFFISCFLVFLAMAVYTGV
TINYYGKRYGNWRFSWSYIIGWVSVVLTFFS-GIFYLCAYRMHECPRSNN
SH
*
>P1;ENSAMXG00000003038

-MYSFMGGGLFCAGVGNILLVVSTATDYWMQYRQSSGYMHMGLWRYCMPG
KCMTHTDSI----------------------AYWDATRAFMIL---AVLA
CFFGLMIGVMAFINYSSF--GGFDKTFAAGILYFISCFFVLLAMAIYTGV
TVNYYGKRYGNWRFSWSYIMGWVSVVLTFFS-GIFYMCAYRMHV-PRGPM
SR
*
>P1;ENSDARG00000037402

-MYSFMGGGLFCAGVGNILLVISTATDYWMQYRQSSSYMHQGLWRYCVPG
KCMTHTDSI----------------------AYWDATRAFMIL---ATLA
CFFGMIIGVMAFINYSSF--TGFDRTFAAGILYFISCFFVLLAMAVYTGM
TVNYYGKRYGNWRFSWSYIMGWVSVVLTFFS-GIFYMCAYRMHE-PRGPM
SR
*
>P1;ENSTNIG00000016178

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSSNYMHQGLWRYCVPG
KCMTHTDSI----------------------AYWDATRAFMIL---SLLA
CFIGIVIGVMAFIHYSSF--DGFDKTFAAGILFFISCFFVLLAMAVYTGV
TVNYYGKRYGSWRFSWSYIMGWVAVVLTFFS-GIFYMCAYRMHECPRNSN
SR
*
>P1;ENSORLG00000005308

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSSSYMHQGLWRYCVPG
KCIAHTDSI----------------------AYWDATRAFMIL---SLLA
CFIGIVIGIMAFIHYSSF--DGFDKTFAAGILFFISCFFVLLAMAVYTGV
TVNYYGKRYGNWRFSWSYIMGWVAVVLTFFS-GIFFMCAYRMHECPRNSN
SR
*
>P1;ENSDARG00000068974

-MYSFLGGGLFCAGVGNILLIVSTATDYWMQYRHSNNYMHQGLWRYCTPG
KCFTHTDSI----------------------AYWDATRAFMIL---SLLA
CFIGIIIGIMAFIHYSSF--DRFDKTFAAGILFFISCFFVFLAMAVYTGV
TINYYGKRYGNWRFSWSYIIGWVSVVLTFFS-GMFYMCAYRMHECPRSSN
PH
*
>P1;ENSXMAG00000001731

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSSNYMHQGLWRYCVPG
KCMTHTDSI----------------------AYWDATRAFMIL---SLLA
CFIGIVIGIMAFIHYSSF--DGFDKTFAAGILFFISCFFVLLAMAVYTGV
TVNYYGKRYGSWRFSWSYIMGWVAVVLTFFS-GIFYMCAYRMHECPRNSN
-S
*
>P1;ENSTRUG00000005724

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRQSGNYMHQGLWRYCMPG
KCFPHSESIGSAILHLLSFM-P-----DSSTAHLDATRALMIL---SLLA
CFFGIIIGIMAFIHYSSF--DRFDKTFAAGVLFFISCFLVFLAMAVYTGV
TINYHGKRYGNWRFSWSYIIGWVSVVLTFFS-GIFYLCAYRMHECPRTTN
AH
*
>P1;ENSTNIG00000008604

-MYSFMGGGLICAGVGNILLIVYTATDYWMQYRQSGNYMHQGLWRYCMPR
KCFPHSESI----------------------GLCNKEP-FSQTAFNSMVP
IF------KPGSAERSSLLKRIFSPATALTWGFGIQSFLVFLAMAVYTGV
TINYYGKRYGNWRFSWSYIIGWVSVVLTFFSAGIFYLCAYRMHECPRTTN
SH
*
>P1;ENSTRUG00000005013

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSSNYMHQGLWRYCVPG
KCMTHTDSIGKSRQSVTSRPTPPSTHTHTHTAYWDATRAFMIL---SLLA
CFIGIIIGVMAFIHYSSF--DGFDKTFAAGILFFISCFFVLLAMAVYTGV
TVNYYGKRYGSWRFSWSYIMGWVAVVLTFFS-GIFYMCAYRMHECPRNSN
SR
*
>P1;ENSLOCG00000005467

-MYSFMGGGLFCAGVGNILLIVSTATDYWMQYRHSGNYMHQGLWRYCVPG
KCYSHTESI----------------------AYWDATRAFMIL---SLLA
CFIGIIIGIMAFVHYSSF--DRFDKTFAAGILFFISCLFVLLAMAVYTGV
TVNYFGKRYGNWRFSWSYIIGWVAVVLTFFS-GIFYMCAYRMHECPRSSH
PH
*
