>P1;ENSORLG00000003835

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDDDFRDLERKVD
VTSKAVAEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKNPGYPQAEG
LLGECMAKYGRELGEDTNFGGALVDVGESMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLREIQHHLKKLEGRRLDYDYKKKRQGKIPDEEIRQALEKFH
ESKDVAETSMYNLLETDIEQVSQLSALVDSQLQYHRQAVQVLEELSDKLR
ERMN---EAQSRP---------RREYTPKPKPIFDFGD-N-SHSNGGYPT
-TM-APPPS-QNVSMRDGESWRRT----LSCSVYPAPPEQPSCKALYDFE
PENEGELGFHEGDVITLTNQIDENWYEGMLNGQSGFFPLNYVEVLVPLPH

*
>P1;ENSTRUG00000002216

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDDDFRDLERKVE
VTSKAVVEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKNPGYPQAEG
LLGECMTKYGRDLGEETNFGGALVDVGESMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLKEIQHHLKKLEGRRLDYDYKKKRQGKIPDEEVRQALEKFH
ESKEVAETSMYNLLETDIEQVSQLSSLVDSQLQYHRQAVQVLDELSDKLR
DRVN---EAQSRP---------RREYTPKPKPIFDFGD-D-SHSNGGYSA
-PM-APPPS-RNTGRHFL---LSF----ILPPVSSAALEQPSCKALYDFE
PENEGELGFHEGDIITLTNQIDENWYEGMLNGQSGFFPLNYVEVLIPLPH

*
>P1;ENSDARG00000002642

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDEEFKDLERKVD
VTNKAVVEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKSPGYPQAEG
LLGECMGKYGRELGEETNFGGALMEVGESMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLREIQHHLKKLEGRRLDYDYKKKRQGKIPDEELRQALEKFH
ESKEVAEISMYNLLETDIEQVSQLSSLVESQLQYHRQAVQILDELSDKLR
DRMK---DAQTRP---------RKEYIPKPKPVIDFGE-TNEQSNGGYTP
-SS-A-PPM-RNAESYHQ---FGR----ITTRKPRLPAEQACCKALYDFE
PENEGELGFHEGDIITLTNQIDENWYEGMLRGQSGFFPLNYVEVIVPLPH

*
>P1;ENSGACG00000012255

MSVAGFK-K--------QFYKASQMVSEKVGGAEGTKLDEDFKDLERKVD
VTSKAVVEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKNPGYPQAEG
LLGECMGKYGRDLGEETNFGGALVDVGESMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLREIQHHLKKLEGRRLDYDYKKKRQGKIPDEEVRQALEKFH
ESKEVAETSMYNLLETDIEQVSQLSSLVESQLQYHRQAVQVLEELSDKLK
DRMN---DAQTRP---------RREYTPKPKPIYDFGE-D-NQSNGGYST
-SA-APPPS-RNSGSGIR----V-----ASHRKATSAPEQPCCKALYDFD
PENEGELGFREGDVITLTNQIDENWYEGMLNSQSGFFPLNYVEVLVPLPH

*
>P1;ENSORLG00000014924

MSVAGLR-K--------QINKATQMINEKVGGAEGTKLDEDFKELERKAD
ITSKAMLEVISKTTEYLQPNPATRAKLTMLNTVSKIRGQVKSPGYPQPEG
LLGEAMLKYGRDMGDDTNFGGALLDVGETMKRMAEVKDSLDIDVKQNFID
PLQAVADKDIKDIQHHLKKLEGRRLDYDYKKKRQGKIPDEELRQALEKFH
ESRDLAETSMYNLLETDVEQVSQLSAFVDSLLQYHQEATQILQELNGRLK
ERVS---DAQSRP---------KREIPKKRQESFEYGHEQ-DDSNGGYSP
-AA-INPPS-YSAGKRED---IKPTE-TIIVMLGYKNKTDPCCKAMYDFE
PENDGELGFREGDIITLVSKIDENWYEGRLQGRSGYFPTNYVEVMVPLPY

*
>P1;ENSGACG00000015335

MSVAGFK-K--------QFYKASQMVSEKVGGAEGTKLDEDFKDLERKAD
ITSKAVVEILNKTTEYLQPNPATRAKLSMVSTVSKMRGQGNGPGYPQPEG
LLGECMTKYGRDMGEETNFGGALTDIGESMKRMAEVKDSLDIDVKQNFID
PLQAVAEKDIKDIQYQLKKLEGRRLDYDYKKKRQGKIQDEEIRQALEKFH
ESKETAEASMYNLLETDVEQVSQLSSLVESLLQYHKQASEILEELTGKLR
ERVN---EAQSRP---------RREYTPRPRPSYDYGE-V-EESNGGYAP
-AA-SSPPA-YS-------------------------PAEPCCKALYDFE
PENEGELGFHEGDIITLVNQIDDNWFEGAIRGRSGYFPNNYVEVMVPLQH

*
>P1;ENSONIG00000004676

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDDDFRDLERKVD
VTSKAVVEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVNNPGYPQAEG
LLGECMAKYGRELGEDTNFGGALVDVGEAMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLREIQHYLKKLEGRRLDYDYKKKRQGKIPDEEVRQALEKFH
ESKEVAEMSMYNLLETDIEQVSQLSSLVESQLQYHRQAVQVLEELSGKLG
DRMN---EAQSRT---------RREYTPKPKPVFDFGD-N-NHSNGGYST
-PM-APPPS-RISGFRGE---RRS----MST-RKPSAPEQPSCKALYDFE
PENDGELGFREGDIITLTNQIDENWYEGTLNGQSGFFPLNYVEVLVPLPH

*
>P1;ENSTNIG00000010690

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDDDFRDLERKVE
VTSKAVVEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKNPGYPQAEG
LLGECMSKYGRDLGEETNFGGALVDVGEAMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLKEIQHHLKKLEGRRLDYDYKKKRQGKIPDEEVRQALEKFH
ESKEVAETSMYNLLETDIEQVSQLSSLVDSQLQYHRQAVQVLEELSDKLR
DRVN---EAQSRP---------RREYTPKPKPIFDFGE-D-SHSNGGYSA
-PV-ALPPS-RTT----------------------AALEQPSCKALYDFE
PENEGELGFHEGDIITLTNQIDENWYEGMLNGQSGFFPLNYVEVLIPLPH

*
>P1;ENSDARG00000067958

MSVAGLK-K--------QFYKASQLMSEKVGGAEGTKLDEDFKDLERKAD
ITSKAISDVLCKTTEYLQPNPASRARLTMANTMSKMRGQVKSLGYPQAEG
LLGECMLKYGRDMGEDTNFGGALVEMGEAMKRLAEVKDSLDIDVKQNFID
PFQTIVDKDLKDIQHHLKKLEGRRLDYDYKKKRQGKIADEELRMAMEKFE
ESRDAAETSMQNLLDTDVEQVSQLCALVESQLQFHKQSMQVLEELAGAMR
ERVN---KAQSQP---------RQKRMPVSRPSIDYSD-P-EDSNGGWNP
-SA-AAPPS-YSSTAPSF---NR-----ASSRQKRNSADQPCCRALYDFE
PENEGELGFNEGDVITLTNQIDDNWYEGSFRGQTGLFPCNYVEVMVPLR-

*
>P1;ENSXMAG00000019300

MSVAGFK-K--------QFFKASQMMSEKVGGAEGTKLDEDFKELERKAD
VTSKAVVDVIGKTSEYLQPNPASRAKLTMLNTVSKIRGQVNSPGYPQPEG
LLGESMTKYGRDIGEDNSFGGALVDVGEAMKRLAEVKDSLDIDVKQNFID
PLQAVAEKDIKDIQHHLKKLEGRRLDYDYKKKRQGKIPDEEIRLSLEKFH
ESKDMAESSMQNLLETDVEQVSQLSAFVESLLQYHRQATEILEEVTERLK
ERVN---EAQSRP---------KREFKPKPRQSFDYGD-E-EHSNGGYAA
-GP-VSPPA-YTPAAQAQ---YPPPP--VKRPSVKSKPREPSCKALYDFV
PENDGELGFYEGEIITLVRQIDENWFEGRLRGQTGYFPNNYVEVIVPISH

*
>P1;ENSONIG00000010245

MSVAGFK-K--------QIYKATQLMSEKVGGAEGTKLDEDFKDLERKAD
ITSKAVVEVLNKTSEYIQPNPATRAKLSMLSTVSKIRGQVNSPGYPQAEG
LLGECMTKYGHEMGENSNFGGALIDAGESMKRLAEVKDALDIDVKQNFID
PLQGIAEKDIKDIQFHLKKLEGRRLDYDYKKKRQGKIQDEEIRQALEKFH
ESKELAERSMYNLLETDVEQVSQLSSFVESLLQYHRQATQIMEELSDKLR
ERVN---DAQSRP---------RQEYTPKPKPAFDFGE-V-EHSNGGYSS
-SA-SSPPA-YS-------------------------SAEPCCKAMYDFE
PENDGELGFQEGDIIKLVSQIDENWYEGSLRGKSGYFPTNYVEVMVPLPH

*
>P1;ENSAMXG00000009373

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDEEFKDLERKVD
VTSKAVVELISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKSPGYPQAEG
LLGECMGKYGRDLGEETNFGLALMDVGESMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLREIQHHLKKLEGRRLDYDYKKKRQGKIPDEEVKQALEKFH
ESKEVAEISMYNLLETDIEQVSQLSSLVESQLQYHKQAVQILEELSDKLK
DRIG---EAQSRP---------RKEYIPKPKPVFDFGE-TNDHSNGGFAP
-SS-A-PPT-RNSEPNLK---LGK----SSRKPRLTPAEQACCKALYDFE
PENEGELGFREGDIITLTNQIDENWYEGMLHGQSGFFPLNYVEVIVPLPH

*
>P1;ENSTRUG00000006047

WEVHAFMFAQLVTTAGCVLNPILQMVSEKVGGAEGTKLDEDFKDLERKAD
VTSRAVVEIISKTSEYLQPNPATRAKLTMLSTVSKIRGQVNSPGYPQPEG
LLGECMTKYGQDMGTNTSFGGALMDFGESMMRLAEVKDSLDIDVKQNFID
PLQTIADKDIKDIQHHLKKLGSRRLDYDYKKKRQGKIQDEEIRQSLEKFH
ESKDLAESSMHNLLETDVEQVSHLSSLVESLLQYHREASQILEVLSGNLA
QRWR---EPWAPQGVAASGTGCRYIYTQSIQMISSTVI------ELRWFP
-GL-TPPSSPLS-------------------------AAQPCCRALYDFE
SQNDGELSFREGDVINLLSQIDENWLEGSIGGRSGYFPVNYVEVTV----

*
>P1;ENSXMAG00000013049

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDDDFRDLERKVD
VTSKAVTEVISKTSEYLQPNPASRAKLSMLNTMSKIRGQVKNPGYPQAEG
LLGECMAKYGRELGEDTNFGAALVDVGEAMKRLAEVKDSLDIDVKQNFID
PLQSLCDKDLREIQHHLKKLEGRRLDYDYKKKRQGKIPDEEVRQALEKFH
ESKEVAETSMYNLLETDIEQVSQLSSLVESQLQYHKQAVQVLEELSDKLR
ERMT---EAQSRP---------RREYTPKPKPIFDFGE-N-NHSNGGYTS
-SM-APPPS-RNS-----------------------APEQPSCKALYDFE
PENEGELGFHEGDIIILTNQIDENWYEGMLNGQSGFFPLNYVDVLVPLPH

*
>P1;ENSTNIG00000015336

MSVAGFR-K--------QFYKASQMVSEKVGGAEGTKLDEDFKDLERKAD
VTSKAVVELISKTSEYLQPNPATRAKLTMLGTVSKIRGQVKSPGYPQPEG
LLGECMTKYGRDMGQNTGFGGALIDFGESMLRLAEVKDSLDIDVKQNFID
PLQTVADKDIKDIQHHLKKLEGRRLDYDYKKKRQGKIQDEEIRQALEKFH
ESKELAEGSMHNLLETDVEQVSHLSSLVESLVQYHRQASQILEELSENLA
KRNVQGRRTQSRP---------KREYTPKPRPSFDYGR-A-DNSNGGFTP
-AA-TSPSN-YS-------------------------AAEPCCRALYDFE
PENDGELGFREGDVIRLLSRIDENWLEGSLGSRSGYFPVNYVEVTVPLPN

*
>P1;ENSLOCG00000006631

MSVAGLK-K--------QFYKASQMVSEKVGGAEGTKLDEEFKDLERKVD
VTSKAVTEVISKTSEYLQPNPASRAKLSMLNTVSKIRGQVKSPGYPQAEG
LLGECMVKYGRELGEDTNFGGALLDAGESMKRLAEVKDSLDIDVKQNFID
PLQGLCDKDLREIQHHLKKLEGRRLDYDYKKKRQGKIPDEEVRQALDKFH
ESKEVAETSMYNLLETDIEQVSQLSALVEAQLQYHRQAVQILEELSEKLR
TSMS---EASSRP---------RREYTPKPKPSLDYGD-A-DQSNGGFYT
PAAAAAPAA-RSSAWHQD---FPGPVVPLSLPPFPHTMDQPCCKALYDFE
PENDGELGFREGDIITLTNQIDENWYEGMLHGQSGFFPLNYVEVLVPLPH

*
