>P1;ENSDARG00000044053

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPSGRLNLEEFQQLYVKFFPYGDASKFAQHAFRTFDKNSDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDRIFSKMDKNNDDQITLDEFKEAAKSDPS
IVLLLQCDMQK
*
>P1;ENSTNIG00000009720

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLEEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQISLEEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSXMAG00000010752

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFTKMDKNNDDQITLEEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSGACG00000004784

IHDPCAKLTKMFNNNTITGIMGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLEEFQQLYVKFFPYGDASKFAQHAFRTFDKNSDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPQQRVDKIFSKMDKNNDDQISLDEFKEAAKGDPS
IVLLLQCDLQK
*
>P1;ENSGACG00000011662

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPQQRVDKIFGKMDKNNDDQISLDEFKEAAKSDPS
IVLLLQCDMQK
*
>P1;ENSAMXG00000010008

--------------------MGKQNSKLTPEVLEDLVKSTEFNEHELKQW
YKGFLKDCPSGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQISLEEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSDARG00000023228

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQISLEEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSONIG00000001225

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPSGRLNLEEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQITLEEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSXMAG00000015237

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLEEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQISLEEFKEAAKSDPS
IVLLLQCDMQK
*
>P1;ENSORLG00000015960

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPSGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPQQRVDKIFSKMDKNNDDQISLDEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSTRUG00000006640

--------------------MGKQNSKLTPEVMEDLVKNTEFNEHELKQW
YKGFLKDCPTGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQISLEEFKEAAKSDPS
IVLLLQCDLQK
*
>P1;ENSLOCG00000016480

-----MSLWHGFL--EETETMGKQNSKLAPEVMEDLVKSTEFNEHELKQW
YKGFLKDCPSGRLNLDEFQQLYVKFFPYGDASKFAQHAFRTFDKNGDGTI
DFREFICALSITSRGSFEQKLNWAFNMYDLDGDGKITRVEMLEIIEAIYK
MVGTVIMMKMNEDGLTPEQRVDKIFSKMDKNNDDQITLDEFKEAAKSDPS
IVLLLQCDIQK
*
