>P1;ENSDARG00000035056

MS--GKVAKP----------KEEKDASKVQDDAAPGTQEYIMLRQDSIHS
ADIRGKGSPFRAKCHEIFCCPLKQVVLKE--NSEPEEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDSGFTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAVLNGG-KAVSQNES-T
*
>P1;ENSDARG00000056633

MS--GKAL------------------------------------------
-----------------------LKTKED--KDATKEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDNSFAIFNLIPVGLRVVAIQGVQTKLYLAMN
NEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GQIMKGNHVKKTKPAAHFIPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAMLNGG-KTLSQNES-T
*
>P1;ENSAMXG00000008370

LC--FSHI------------------------------------------
----------------------------S--PVNSTEPQLKGIVTKLYSR
QGFHLQLQADGTIDSTKEEDSSYAIFNLIPVGLRVVAIQGVQTKLYLAMN
NEGYLYTSEHFTQECKFKESVFENYYVTYSSMIYRQ-QSGRGWYLGLNKE
GQIMKGNHVKKTKPAAHFIPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAMMNGG-KALSHNGS-T
*
>P1;ENSAMXG00000000040

MA--AAIASSLIRQKRQAREREKSNACRCV--SSPS--------------
---KNKGACEKPSRLSVFSRVKLFGSKKR--RRRRPEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDSGFTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVTMYREPSLHDLTEFSRSGSGTPTKS
RSASAVLNGG-KAVSQNES-T
*
>P1;ENSONIG00000008596

MSRAAAIASSLIRQKRQAREREKANACRGS--GSPS--------------
---NSKGANEKPSKLNVFSRVKLFGSRKKRKRRRPPEPQLKGIVTRLSSR
QGFQLQMQPDGTIDGTKDEDSTYAVFNLIPVGLRVVAIQGVQTKLYLAMN
NEGFLYTSEHFTPECKFKESVFENYYVTYSSMLYRQQASGRAWYLGLNKE
GGIMKGNHVKKNKPAAHFIPKPLKVAMYREPSLHDLTELSRSGSGTPTKS
RSASALLNGGGKTPSNND-LS
*
>P1;ENSXMAG00000000441

MSRAAAIASSLIRQKRQAREREKANACRGS--SSPS--------------
---NSKGANEKPSKLNVFSRVKLFGSRKKRKRRRPPEPQLKGIVTRLSSR
QGFQLQMQQDGTIDGTKDEDSTYALFNLIPVGLRVVAIQGVQTKLYLAMN
NEGFVYTSEHFTPECKFKESVFENYYVTYSSMMYRQQQSGRAWYLGLNKE
GAIMKGNHVKKNKAAAHFIPKPLKVAMYREPSLHDLTELSRSGSGTPTKS
RSASALLNGG-RKTPSNDDLS
*
>P1;ENSTNIG00000016839

MA--AAIASSLIRQKRQAREREKNNACRCV--SSPS--------------
---KTKGNCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEENGYTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAMLNGG-KAVSQNES-T
*
>P1;ENSORLG00000001634

MA--AAIASSLIRQKRQAREREKSNACRCV--SSPS--------------
---KTKGNCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKGIVTKLYSR
QGFHLQLQSDGTIDGTKEEDNGYTIFNLIPVGLRVVAIQGVQTKLFLAMN
SEGYLYTSEHYTLECKFKESVFENYYVTYSSMVYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAVLNGG-KAVSQNES-T
*
>P1;ENSXMAG00000013396

MA--AAIASSLIRQKRQAREREKSNACRCV--SSPS--------------
---KAKGSCEKPNRLNVFSRVKLFGSKKR--RRRRPEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDSSYTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTAECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAVLNGG-KAVSQNES-T
*
>P1;ENSONIG00000002720

MA--AAIASSLIRQKRQAREREKSNACRCV--SSPS--------------
---KTKGSCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDNGYTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAVLNGG-KAVSQNES-T
*
>P1;ENSTRUG00000007939

RA--AAIASSLIRQKRQAREREKANACRGS--SSPS--------------
---NSKGTNEKPSKLNVFSRVKLFGSRKKRKRRRPPEPQLKGIVTRLSSR
QGFQLQLQPDGTIDGTKDEDSTYTVFNLIPVGLRVVAIQGVQTKLYLAMN
NEGFLYTSEHFTPECKFKESVFENYYVTYSSMLYRQQASGRAWYLGLNKE
GGIMKGNHVKKNKPAAHFIPKPLKVAMYREPSLHDLTELSRSGSGTPTKS
RSASALLKRW-SPHTHTH-TQ
*
>P1;ENSTRUG00000006744

MA--AAIASSLIRQKRQAREREKNNACRCV--SSPS--------------
---KTKGNCEKPSRLNVFSRVKLFGSKKR--RRRRPEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEENGYTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAMLNGG-KAVSQNES-T
*
>P1;ENSGACG00000020450

MA--FP--------------------------------------------
------------------------------LRRSTSEPQLKGIVTRLSSS
QGFQLQMQPDGTIDGTKDEDSTYGVFNLIPVGLRVVAIQGVQTKLYLAMN
NEGFLYTSEHFTPECKFKESVFENYYVTYSSMLYRQQASGRAWYLGLNKE
GGIMKGNHVKKNKAAAHFIPKPLKVAMYREPSLHDLTELSRSGSGTPTKS
RSASALLNGGGKSPSKND-LS
*
>P1;ENSGACG00000017204

VC--GESSNPS--------SFCHG-TTAVQDDAAPGTQEYIMLRQDSIHS
ADIRSKGSPFRAKCHEIFCCPLKQAVNKE--STEPEEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDNGYTVFNLIPVGLRVVAIQGVQTKLYLAMN
SDGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASALLNGG-KAVSQNES-T
*
>P1;ENSLOCG00000015157

MS--GKVAKP----------KEEKDASRVQDDAAPGTQEYIMLRQDSIHS
ADIRKKESPFRAKCHEIFCCPLKQVVLKE--SAEPEEPQLKGIVTKLYSR
QGFHLQLQADGTIDGTKEEDNGYTMFNLIPVGLRVVAIQGVQTKLYLAMN
SEGYLYTSEHFTPECKFKESVFENYYVTYSSMIYRQQQSGRGWYLGLNKE
GEIMKGNHVKKNKPAAHFLPKPLKVAMYREPSLHDLTEFSRSGSGTPTKS
RSASAVLNGG-KAVSQHES-T
*
