>P1;ENSDARG00000089626

-----------MHPAAAKWYDRRDFVFIEFLVEDSKDVKVNFDKSKFGFS
CLSGADNVKYSNEIDLFGSIDQDGSKHKRTDRSILCCLQKAETGKSWPRL
TKDKAKLNWLSVDFNNWKDWEDDSDEEISNYDRFSEMMGNMGGEDDLPDL
DGADD--ESADSDDEKMPDL-E
*
>P1;ENSDARG00000037284

-----------MQPATAKWYDRREAVFIEFCIEDSKDVQVKFDKTKLDFS
CVGGTDNMKHHNEVDLLEAIDPNDSKHKRTDRSVFCCLKKAEPGKSWPRL
TKEKAKLNWLSVDFNNWKDWEDDSDEELSSFDRFSEMMNNMGGEDDLPDV
DGADEE-ESPDSDDEKMPDL-E
*
>P1;ENSGACG00000008508

M-----------QPATAKWYDRRDAVFVDFCVEDSKNVKVNFENSKFDFG
CVGGTDNIKQQNTVDLFGEINPKDSKYRRTDRSVLVCLRKVEPGKAWPRL
TKDKTKCNWLSVDFNNWKDWEDDSDEDLSSFDKFSEMMNTMGR-DDVPDF
DGAGEEHDFENSDDEQMPAL-E
*
>P1;ENSGACG00000015239

-----------MHPATAKWYDRRDSVFIEFCVADSKDVKINFDKAKFGFS
CFGGTDNVKHENEMDLFEAIDVNESKHNRTDRSVLVYLRKAQPGKPWPRL
TKEKAKLSWLSVDFNNWKDWEDDSDEEMGNFDQFSNIMNNMGGEDDLADL
DGPEE--ESADSDDEKMPDL-E
*
>P1;ENSONIG00000011940

LFL-----MH-RQPAAAKWYDRRDSVFIEFCVEDSKDVQVNFDKSKFSFS
CVSGTDDIKHQNAVELFGEIDPKESKHRRTDRSVLCCLRKAEPGKSWPRL
TKDKAKCNWLSVDFNNWKDWEDDSDEDLSSFDKFSEMMNSMGG-DDLPDL
DGADDEHESADSDDEKMPDL-E
*
>P1;ENSORLG00000012236

-----------RHPATAKWYDKRDSVIIEFCIADSKDVKVNFDKTKFAFS
CLGGADNEKHENEVELFEAIDENESKHKRTDRSVLCYLRKAQPGKAWPRL
TKDKTKLSWLSVDFNNWKDWEDDSEEEMGNFDQFSDMMNNMGGEEDLPDL
DGADDD-DSADSDDEKMPDL-E
*
>P1;ENSAMXG00000004536

PHF-KHVLQNFRQSATAKWYDRRDSVFIEFCVEDSRDVEVKFDKSKLDFS
CVGGVDTVKYHNEVDLFEAIDPNESKHKRTDRSVYCCLKKAESGKSWPRL
TKDKAKLNWLSVDFNNWKDWEDDSDEELSSYDRFSEMMNNMGGEDDLPDM
DGADDE-ESADSDDEKMPDL-E
*
>P1;ENSTRUG00000015676

A-----------QHAAARWYDRREAVFVEFCVEDSQDVKVNFDSSKFEFS
CVTGAADKKHHNTVDLFSEINPKESKHKRTDRSVLCCLRKAQPGISWPRL
TKLKEKVSWLSVDFNNWRNWEDDSDDDLSSFDKFSEMINKMGG-DDLPDL
EGVDDE-YEPDSHCRRLSSR-N
*
>P1;ENSAMXG00000002019

-----------MHPATAKWYDRRDYVFIEFCVEDSKDVTVNFETAKFGFS
CLGGTDNVKHLNEIDLFGAIDQNESKHRRTDRSVLCCLRKAESGKAWPRL
TKEKAKLNWLSVDFNNWKDWEDDSDEELSNFDRFSEMMNSMGGDDELPDL
DGAEDG-ESADSDDEKMPDL-E
*
>P1;ENSTNIG00000012596

-----------MQPATAKWYDTRDIVCIEFCVADSKDVKVNFAKRKFGFS
CVRGTDNIKHEHEIDLFEEIDENESKHKRTDRSVLCYLRKAQPGKKWPRL
TQDKVKLAWLGTDFNNWKDWEDDSDEEMGKFDQLSDMMNSMGGGDDLPDL
DGDDD---SADSDDENLPGLED
*
>P1;ENSTNIG00000015101

MEI--------AQHAAARWYDRTEAVFVEFCVEDSQNVQVNFDTSKLDFS
CVSRTADKKLQNTVDLFSEINPKESKHKRTDRSVLCCLRKAQPGISWPRL
TKLKEKVSWLSVDFINWRNWEEDSDDDLSSFDRFSEMINKMGG-EDLPDL
EGGDDE--SLSSFHSVLVFL-E
*
>P1;ENSTRUG00000002456

-----------RQPATAKWYDTRDFVCIEFCVADSKDLKVNFGKKKCGFS
CVRGTDNVKHENEIDLFDEIDENESKHKRTDRSVLCYLRKAQPGKAWPRL
TEDKVKLTWLGTDFNNWKDWEDDSDEEMGKFDQLSDMMNSMGGGDDLPDL
DGDDD---SADSDDENLPGL-E
*
>P1;ENSXMAG00000010616

MAHLPQHGPFPTLCAIAKWYDRRDFVFVEFCVEDSKDVHVQFDKSKFEFS
CVSRRD--KYYNDIELFGEIDPKQSKHSRTDRSVQCCLQKAEVGKPWPRL
TKEKAKFKWLSVDFNNWRDWDDDSDEDMSSFDNFSEMMNNMGG-DDLPDF
DGAEEH-DSADGDDEKMPDL-E
*
>P1;ENSLOCG00000007299

------------QPASAKWYDRRDYVFIEFCVEDSKDVQVNFEKSKLSFS
CLGGTDSLKHQNEIELFEGIDPNESKNKRTDRSVLCCLRKTESGKSWPRL
TKDKAKLNWLSVDFNNWKDWEDDSDEELSSFDRFSEMMNNMGGDDDLPEV
DGAEDV-RS-------------
*
