>P1;ENSGACG00000014267

--------------------------------------------LLGGGI
YGIHRGGD-SHGPVLPPRVSQLISVFAQTEIFSLVVFASIVNEGYVNLGS
ERLHCVFNRNADACNYGVFVGLVGLLACSFFFMLDYKFSSISSVKDRKKA
IMLEIGFSGAWTFLFFVGFCFLANQWSETTADELPLNQGADAARAAIAFS
FFSIITWAGLTVRAVQKYLLGTDMTLFTTEHMDG---GA-PTQPYPSNSP
V--GVTA-EASETYQSPPFTESN--AAPTYQVPI---Y
*
>P1;ENSTRUG00000008610

--------------------------------------------MESAGA
YGAAKAGSISFDPVAFFKHPRTIL-RLMCWVFSIVVFSCIVNEGYINIGS
ERLLCVFNNNADACNYGVTVGVACFLGSVFFLVLDFYFPSMSSIKDRKRA
VLLDLVFSGLACFLWFVGFCFLANQWQATSPDELPLAQGSDAARATIAFC
FFSILTWAVLTFSALRRFLTGSNTNMFTWQHLDPALGHA-RATPYPIA--
N--GATI-VTTNPYQAPPFTETLDPQKLTQQRPM---A
*
>P1;ENSONIG00000015656

--------------------------------------------MDGVGS
FGAGRAGS-TIDPITFAKQPQTIL-RVLSWIFSLVVFASIVNEGYVNMGS
ERLHCIFNKNTDACNYGVFVGLVGLLACSFFFLLDYKFSSISSVKDRKKA
VMLEIGFSGFWTFLYFVSFCFLANQWSRTRAEELPLNQGADAARAAIAFS
FFSIITWAGLTVRAVQKYLLGTDMTLFTTEHMDG---GA-PTQPYPSNSP
GGGGTTT-ETTETYQSPPFTENN--AAPTYQVPI---Y
*
>P1;ENSTNIG00000002657

--------------------------------------------MDGVGS
FGAGRTGS-AVDPIAFAKQPQTIL-RVLSWIFSLVVFASIVNEGYVNIGS
ERLYCVFNKNADACNYGVFVGLVGLLACSFFGLLDYKFSSISSIKDRKKA
VMLEIGFSGFWTFLYFVSFCFLANQWSRTTPDEVPLDQGADAARAAIAFS
FFSIITWAGLTVRAVQKYLLGTDMSLFTTEHLD-----------------
--------------------------------------
*
>P1;ENSONIG00000003337

MDYTANICTDSMLTRSLASFDVYEDPNPGARPSTARVRHQKAGGMQPAGA
YGAGKAGSVSFDPVAFFTHPRTVL-RLLSWVFSIVVFSCIVNEGYINIGS
ERLLCIFNNNADACNFGVTVGVACFLGTIFFLILDAYFPSISSVRDRKRA
VLLDLVFSGLACFLWFVGFCFLANQWQATSPEELPLAQGSDAARATIAFC
FFSILSWAVLTLSALRRFLTGSNSNLFTWQHLDPVPSNT-RATPYPIA--
N--GATI-VTTNPYQAPPFTETLDPQKLTQQRPLAPAF
*
>P1;ENSORLG00000013084

--------------------------------------------MDGVGS
FGAGRAGS-TIDPITFAKQPQTIL-RVLSWIFSLVVFASIVNEGYYNMGS
ERLHCVFNKNADACNYGVFVGLVGLLACSFFFMLDYKFSSISSIKDRKKA
VMLEIGFSGFWTFLYFVSFCFLANQWSRTKKEDLPLNQGADAARAAIAFS
FFSIITWAGLTARAVQKYLLGTDMSLFTTEHMDG---GA-PTQPYPSNSP
G--GGTT-ETTEAYQSPPFTENN--AAPTYQVPI---Y
*
>P1;ENSAMXG00000004430

--------------------------------------------MNGTGS
YGAGRAGA-GLDPLSFAKRPQTVL-RLLAWIFSMVVFGSIINEGYVNMGS
ERLHCVYNKNADACNYAITIGLVAFLACLFFLGLDIYFPQISSVKDRKRV
VLFEMGFSGFWTFLWFVGFCFLANQWSRTSLEELPLEQATDAARAAIAFS
FFSILTWAALTACAVQKFLMGTDITLFTTVPTPG---QPEPKQPYPPNDV
T--GQTTIPVNNAYQSPPLIETMETTTPGYTITPA-SF
*
>P1;ENSDARG00000014871

--------------------------------------------MDGVGS
FGAGRAGA-AFDPFAFIQQPQTIL-RILSWIFSMVVFGSIINEGYVNHGS
QRLYCVFNKNNNACNYGTTIGLIAFLACIFFIILDIKFQQISSIKDRKKA
VMLDIGFSGFWAFLWFVGFCFLANQWQRTTTDELPLNQGADAARAAITFS
FFSIFTWAGLTVRAVQKYMLGTDMTLFTTEHIDG---NP-PIQPYPT---
---GPDT-IPNDTYKSAPFTENLDTTAPTYQVPI---Y
*
>P1;ENSTRUG00000001846

--------------------------------------------MDGVGS
FGAGRTGS-TVDPIAFAKQPQTIL-RVLSWIFSLVVFASIVNEGYVNVGS
ERLYCVFNKNADACNYGVFVGLVGLLACSFFGLLDYKFSSISSIKDRKKA
VMLEIGFSGFWAFLYFVSFCFLANQWSRTTPEEVPLNQGADAARAAIAFS
FFSIITWFKLSVRAVQKYLLGTDMSLFTTEHLDG---AA-PTQPYPSNSP
V--GGTT-ETTETYQSPPFTENN--AAPTYQVPI---Y
*
>P1;ENSAMXG00000010222

--------------------------------------------MDGVGS
FGAGRAGS-AFDPLAFIQQPQTIL-RILSWIFSMVVFGSIINEGYVNFDS
ETLYCVFNKNYDACNYGITIGLVAFIACIFFMILDMKFQQISSVKDRKKA
VMLEIGFSGFWTFMWFVCFCFLANQWQRTTTDELPLNQGADAARAAIAFS
FFSIFTWVRT-VSI------------------------------------
--------------------------------------
*
>P1;ENSXMAG00000000502

--------------------------------------------METASP
YGAMKAGRVPFDPVAFFTHPRTIL-RLLSWVFSIVVFSCIVNEGYINIGS
ERLLCVFNKNAHACNYGMTVGVACFLGSTCFLILDVYFPSMSNLKDRKRA
VLFDLIFSGVASFLWFVGFCFLANQWQATSPDELPLAQGSDAARAIITFC
FFSILSWVCTSFIHI-----------------------------------
--------------------------------------
*
>P1;ENSTNIG00000005449

SVG-----------------------------------------MEPAVA
YGAAKAGSVGFDPVAFFKHPRTIL-RLLCWVFSIVVFGCIVNEGYINIGS
ERLLCVFNNNADACNYGVTVGVACFLGSVFFLVLDFYFPSMSSIRDRKRA
VLLDLVFSGLACFLWFVGFCFLANQWQATSPDELPLAQGSDAARATIAFC
FFSILTWAVLTFSALRRFLTGSNPNMFTWQHLDPALGHA-RATPYPIA--
N--GATI-VTTNPYQAPPFTETLDPQKLTQQRAMAPAF
*
>P1;ENSGACG00000016792

--------------------------------------------MERAGA
YGAAKAGGVAFDPVAFFTHPRTIL-RLMSWVFSIVVFGCIINEGYINIGS
ERLLCVFNNNADACNYGVTVGVACFLGSIFFLILDIYFPSISSVKDRRRA
VMLDLAFSGLASFLWFVGFCFLANQWQATSPDELPLAQGSDAARATITFC
FFSILTWVVLTLSALRLFLTGSNRNLFTWQHMDP------PLRPYPIA--
N--GATI-VTTNPYQAPPFTETLDPQKLTQQRPV---A
*
>P1;ENSDARG00000025034

--------------------------------------------MDGAGS
FGAGRAGS-AFDLVAFVKQPQTIL-RALAWIFSMVVFASIINEGYVNMGS
ERLHCVFNKNADACNYAITIGIMAFLASVLFLALDVYFPQISSVKDRKRA
VLLEIAFSGFWTFLWFVGFCFLANQWSRTSDKELPLEQASDAARAAIAFS
FFSILTWAGLTVCAVQRFLLGTDMTLFTSEQVVN---QP-PKQTYPSNDV
I--GQTT-IPVNAYQSPPLIETVETRPPGYKVPPA--F
*
>P1;ENSLOCG00000006038

--------------------------------------------MEGVGS
FGAGRAGG-AFDPVAFIKQPQTIL-RILSWIFSIVVFGSIVNEGYINSGS
EKLYCIFNKNDDACSYGITIGVMAFFASIFFFVLDIYFPQISSVKDRKRA
VLLEMGFSGFWTFLWFVGFCFLANQWQRTSPKELPLNQGADAARAAVAFS
FFSILTWAGLTVKAVQRYRLGTDMSLFATDPVDG---TP-TVQPYPGY-P
T--GSGI-ETTDTYQSPPFTENLATNAKSYQVPT---Y
*
