>P1;ENSORLG00000008564

--------------------------------------------------
----------------------MALFCGCGHEALTQTEVLVETYFARNVQ
DYVVMASFIKYFQYVIYGLASFFFLYGILLLAEGFYATSAVKQTFGEFRS
TQCGRCLSLTFIIVTYILAFIWLAVFAFSAIPVFFLFNMEQTCHNINLLA
ETTASINQHSWICMDARQYGLLPW--NAVPGKSCGMTLASICKTSEFHLT
YDLYIAAFAGAGVTLLALFLYLIATTYNYAVLRFL---------------
--GRKGI---R----------------------
*
>P1;ENSAMXG00000014327

--------------------------------------------------
-----------------------------------------------DEC
NSLSLYFSIEYFQYIIYGLATFFFLYCIALLAEGFYTTSAARQTFGEFRS
TVCGRCLSTSFIVITYFLAVVWLLVFALSALPVFFFYNMSSTCRTVDVLS
ETPSSINQ---LCVDARQYGLLPW--NAMPGKACGMTLSNVCKTREFFLT
YDLYIAAFAGAGITLLALLTYVVSTTYNFAVLRYL---------------
--GRKGLAPRC----------------------
*
>P1;ENSDARG00000011929

M----------AASAVDWLGQLPQRLRGVDVKSSNLRRLRPKVTPGCYDC
CIRCLGAVPYTSLVATLLCYAGVGLFCGAGHEALTHTHTFVELHFARDVQ
DFTVMADFIKYFQYVIYGLASFFFLYGLLLLAEGFYTTSAVKQTFGEFRS
TQFGRCISLTFIILTYVLALIWLIVFGFTAVPVLFFINMKSSCHTVNVLS
ETTL-FNQQSRVCMDARMYGFLSW--NAMPGVVCGNALANICKAPEFHVT
YDLYICAFAGAGITLLALFVYMVATTYNYAILRFL---------------
--GRKGI--RC----------------------
*
>P1;ENSXMAG00000009555

--------------------------------------------MGCYDC
CMRCLGGVPYCSLVATLLCFSGIALFCGCGHQALTETERLIETYFARNLH
DYITLAYIIQYFQYVIYGLASFFFLYCIALLAEGFYTTSAAKQTFGEFRS
TMCGRCLSSSFIVMTYLLAVLWLLVFAFSALPVYFFYNMDATCSTIAVLT
ETPASINQ---LCVDARQYGLLPW--NAVPGKACGMTLSSICKTREYQMT
YNLYVAAFAGAGITLLALLTYTVSSTYNFAVLRYL---------------
--GRKGIGPRC----------------------
*
>P1;ENSXMAG00000011480

--------------------------------------------MGCYDC
CIRCIGAVPYPSLVATLLCYAGMALFCGCGHEALAQTEELVKT-FARDPK
DFEVMASFIKYFQFVIYGLASFFFLYGILLLAEGFYTTSAVKQTFGEFRS
TQCGRCLSLTFIIVTYILAFIWLAVFAFSAIPVFFLFNMEHTCHNINILA
ETTPSINQHSWICMDARQYGLLPW--DAMPGKSCGMTLAAICKTSEFHTT
YDLYIATFAGAGVTLLALILYLAPTTYNYAVLRFL---------------
--GRKGI---R----------------------
*
>P1;ENSAMXG00000007585

M----------FPVKQPWLCK----------------------ALGCYDC
CVRCLGAIPYASLAATLLCYAGVALFCAGGHQALTHTDTLVQMHFARSLQ
DYVVLADFIKYFQYVIYGLASFFCLFGILLLAEGFYTTSAVKQTFGEFRS
TQCSRCLSLTLIIVTYVLAVIWLVVFAFAGIPVYFLSNMASTCHTVNILS
ETTTSLNQHAWVCMDARQFGLLPW--NAMPGKVCGMTMANICKTPEFYVT
YDYYITAFAGAGITLLSLVLYIVPATYNYAVLRFL---------------
--GRKGI--RC----------------------
*
>P1;ENSORLG00000006441

---------------------------------------------GCYDC
CMRCLGGVPYCSLVATLLCFSGIALFCGCGHQALTETERIIETYFARNLQ
DYITLAYIIQYFQYVIYGLASFFFLYCIVLLAEGFYTTSAAKQTFGEFRS
TMCGRCLSSSFIVMTYVLAVLWLLVFALSALPVYFFYNMDATCHTIDVLT
ETPASINQ---LCVDARQYGLLPW--NAVPGKACGMTLSNVCKTREYQMT
YNLYIAAFAGAGITLMALNHLWTLVKYTFLYFKAL---------------
--VECHLYPPVVNKENKKLSISSNQIEQFDFHT
*
>P1;ENSDARG00000103732

--------------------------------------------MGCYEC
CMRCLGGVPYVSLAATLLCFSGIALFCGCGHQALTESERLIETYFARDNQ
DYYTLVYLIEYFQYIIYGLASFFFLYCIVLLAEGFYTTSAVRQSLGEFRS
TVCGRCLSTTFIVITYFLVVVWLLVFSLSAFPVYFFYNMAKTCQTINFLS
ETPSSINQ---LCIDARQYGLLPW--TAIPGKACGMTLSNVCKTREFSLT
YNLYIAAFAGAGMTVLALLTYTVSTTYNFAVLRYL---------------
--GRKGISPRC----------------------
*
>P1;ENSTRUG00000008916

---------------------------------------------GCYDC
CMRCLGGVPYCSLVATLLCFSGIALFCGCGHQALTETERLIETYFARNLQ
DYITLAYIIQYFQYVIYGLASFFFLYCIMLLAEGFYISSAARQTFGEFRS
TMCGRCLSSSFIVMTYGLAALWMLVFALSALPVYFLYNMTSTCNTIDVLT
ETPASINQ---LCVDARQYGVC-WMDNGSEFLKSSHSFIRLCKTREYQMT
YTLYVAAFAGAGITVLALVHCTLHLAANQAYLRKLRHDMREESRSYDLYG
RLQRDRGGTLC----------------------
*
>P1;ENSTNIG00000011791

M----------FPVRQPWLCK----------------------ALGCYDS
CIRCIGAVPYPSLVATLLCYAGMALFCGCGHQALSQTQVLVETYFARNAQ
DFAVMAAFIEYFQYVIYGLASFFFLYGIFLLAEGFYATSAVKQSFGEFRS
TQCGRCLSLTFIIVTYVLAFIWLAVFAFSAIPVFFLFNMEQTCHNINILA
ETTPSINQHGWICMDARQYGLLPW--SALPGKSCGMTLASVCKTTEFYVT
YDLYIAAFAGAGITLLALFVYMIATTYNYAVLRFL---------------
--GRKGI---R----------------------
*
>P1;ENSGACG00000020371

M----------FPVRQPWLCK----------------------ALGCYDC
CIRCIGAVPYPSLVATLLFYAGVALFCGCGHEALSQTEVLVETHFARNVQ
DFVVLASFIKYFQFVIYGLASFFFLYGILLLAEGFYTTSAVKQTFGEFRS
THCGRCLSLTFIIVTYILAFIWLAVFAFTAIPVFFLFNMEQTCHNINLLA
ETTPSINQHGWICMDARQYGLLPW--NAMPGKACGMTLANICKTSEFHVT
YDLYIAAFAGAGIALLALFVYLAATTYNYAVLRFL---------------
--GRKGV---R----------------------
*
>P1;ENSONIG00000004332

M----------FPVRQPWLCK----------------------ALGCYDC
CIRCIGAVPYPSLVATLLCYAGMALFCGCGHEALTQTEVLVETYFARNVQ
DYVVMASFIKYFQYVIYGLASFFFLYGILLLAEGFYTTSAVKQTFGEFRS
TQCGRCLSLTFIIVTYILAFIWLAVFAFSAIPVFFLFNMEQTCHTVNILS
ETTASINQHSWICMDARQYGLLPW--NAMPGKSCGTTLAAICRTSEFHVT
YDLYIAAFAGAGITLLALFLYLVATTYNYAVLRFL---------------
--GRKGI---R----------------------
*
>P1;ENSTRUG00000015475

M----------FPVRQPWLCK----------------------ALGCYDS
CIRCIGAVPYPSLVATLLCYTGMALFCGCGHEALSQTEVLVETYFARNAQ
DFAVLASFIEYFQYVIYGLASFFFLYGICLLAEGFYASSAVKQSFGEFRS
TQCGRCLSLTFIIVTYILAFIWLAVFALSAIPVFFLFNMEQTCHNINILA
ETTPSINQHGWICMDARQYGLLPW--NAMPGKSCGMTLASICKTSEFYVT
YDLYIAAFAGAGITLLALFVYMIATTYNYAVLRFL---------------
--GRKGI---R----------------------
*
>P1;ENSTNIG00000008976

A----------DIV-SMWCGW----------------------VAGCYDC
CMRCLGGVPYCSLVATLLCFSGIALFCGCGHQALTETERLIETYFARNLQ
DYIALVYIIQYFQYVIYGLASFFFLYCIVLLAEGFYTSSAARQTFGEFRS
TMCGRCLSSSFIVMTYVLAALWMLVFALSALPVYFLHNMTSTCRTIDVLT
ETPASINQ---LCVDARQYGLLPW--NAVPGKACGMTLSAVCKTREYQIT
YNLYVAAFAGAGITVLALLTYTVSTTYNFAVLRYL---------------
--GRKGIGARC----------------------
*
>P1;ENSGACG00000018292

--------------------------------------------MGCYDC
CMRCLAGVPYCSLVATLLCFSGIALFCGCGHQALTETERLIENYFARNLQ
DYITLAYIIQYFQYVIYGLASFFFLYCIVLLAEGFYTTNAAKQTFGEFRS
TMCGRCLSSSFIVLTYVLAVLWLLVFAFSALPVYFFYNMDATCHTIDVLT
ETPASINQ---LCVDARQYRLLPW--NAVPGKACGMTLSTICKTREYQTT
YDLYIAAFAGAGITLLALLTYTVSTTYNFAVLRYL---------------
--GRKGLGARC----------------------
*
>P1;ENSLOCG00000014819

ASDSKLCPAVGFSVPRDALL-----------------------LAGCYEC
CVRCLGGIPYTSLLATLLCFSGIALFCGCGHQALTETERIIETYFARNMQ
DYATLAYIIQYFQYIIYGLASFFFLYCIVLLAEGFYTTSAVKQTFGEFRS
TACGRCLSTTFIVVTYILAVIWLVVFAFSALPVYFFYNMATTCHTINILT
ETSSSINQ---LCMDARQYGLLPW--NATPGRVCGMTLVAVCKTKEFFLT
YDLYVAAFTGAGATLLALLTYMISTTYNYAVLKFL---------------
--GRKGIGTRC----------------------
*
