>P1;ENSTRUG00000009493

------------------------------------------------MA
DRFDCDNCKESLYGRKYIQSDDSPYCIPCYDSLFSNTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDEALLCNDCYCNEFSSKCV
ACDKIVMPGTRKLEYAG-STWHEGCFICHSCEQPIGSKSFIPDKDEHYCV
ACYEDKFAPRCTRCKKTLSKGGVTYRDEPWHKECFVCTNCTTQLAGQHFT
SRDDSPYCLKCFGNLYAKKCEACAKPITGKTSSPFVPGFGGGKYISFEDR
QWHQPCFTCSQCSVSLVGAGFFPTGDKILCRECNSNL----------C
*
>P1;ENSONIG00000016304

FAL-------------------RRN----GK------V-FY-SKTEITMT
DRFDCDNCKESLYGRKYIQSDDSPYCIPCYDSLFSNTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDDALLCNDCYCNEFSSKCV
ACDKIVMPGTRKLEYAG-STWHEGCFICHSCSQPIGSKSFIPDKDEHYCV
PCYEDKFAPRCTRCKKTLTKGGVTYRDEPWHKECFVCTSCKTQLAGQHFT
SRDDSPYCLKCFGNLYAKKCEACSKPIT---------GFGGGKYISFEDR
QWHQPCFTCSQCSVSLVGAGFFPDGDRILCRDCHTS-----------L
*
>P1;ENSAMXG00000020826

---------------------------------------GV-VLCRVRMS
EQFNCENCKDSLYGRKYIQVDDVPHCVPCYDRLFANICQGCKELIGHNSR
ELYYDDHHYHEECFRCSRCERSLAEEPFTCQDDALLCNDCYCSEFSSKCV
ACNKTVMPGTSCVSYNKDSTPNSTLTTLNRC----GVSVVINVDGQNTCL
PV-QTEYMLTCTESQKALVQGGVTYRDEPWHRECFLCTGCKTQLAGQPFT
SQGESPYCVKCFSSLYAQKCSACNKPIT---------GFGDGKYVSFEDR
QWHQSCFKCAGCSASLVGAGFFPSGGKVYCKDCNDN------------
*
>P1;ENSORLG00000014671

VSF-------------------IQH----DF------V-LSSLSVKTTMA
DRFDCDNCKESLYGRKYIQSNDSPYCIPCYDSLFSNTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDNALLCNDCYCNEFSSKCV
ACDKIVMPGTRKLEYAG-STWHEGCFICHSCEQPIGSKSFIPDKDEHYCV
PCYEDKFAPRCTRCKKALSKGGVTYRDEPWHKECFVCTSCETQLAGQHFT
SRDESPYCLKCFSSLYAKKCEACCKPIT---------GFGGGKYISFEDR
QWHQSCFTCSQCSVSLVGAGFFPNGDRILCRDCNSN-----------L
*
>P1;ENSONIG00000013661

-----------------------------------------------IMS
DRFDCKNCNESLYGRKYILAEDNPHCIPCYDRLYANTCQECKEIIGHNAK
ELFYENRHYHEHCFRCFRCDRSLADEPFTSQDDALVCSDCYCNEFSSKCV
ACDKTVMPGSRMLEYGG-STWHEDCFACHACEKPIGTESFIPDKNNYYCV
PCYEGRFAPQCSHCKKALTKGGVTYKDEVWHKECFLCTGCKTPLAGQPFT
SQGESPYCVKCFSNMYAKKCAGCNTAIT---------GFGDGKYVSFQER
QWHQPCFKCSRCSVSLVGSGFFPDRDLILCTDCNNE-----------D
*
>P1;ENSGACG00000002619

-----------------------------------------------IMS
ERFDCKNCNESLGGRKYIQVEDHPHCIPCYDRLYANTCEECKEIIGHNAK
ELFYENRHYHAHCFRCFRCDRSLADEPFTSQEDALVCSDCYCNEYSSKCV
SCDKTVMPGSRMLEYGG-STWHEDCFACHGCLKPMGAEAFVPDNDNYYCV
PCYEGRVAPQCSHCKKALTKGGVTYKDEVWHKECFLCTGCKAPLAGQPFT
SQGESPYCVKCFSSLYAKKCAGCNTAIT---------GFGDGKYVSFEER
QWHQPCFKCSRCSVSLVGSGFFPDRDQILCTDCNND-----------D
*
>P1;ENSGACG00000013685

QYT-------------------FLCLLKLDAIFELKHP-GP-SSWRVTMA
DSFDCVNCKESLYGRKYIQSEASPYCIPCYDSLFSNTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDDALLCNDCYCNEFSSKCV
ACDKVVMPGTRKLEYGG-STWHEGCFICHSCQQPIGSKSFIPDKDEHYCV
SCYEDKFASRCTRCKKTLAKGGVTYRDEPWHKECFVCASCKTQLAGQHFT
SRDESPYCLKCFGNLYAKKCEACSKPIT---------GFGGGKYVSFEER
QWHQPCFTCSQCSASLVGAGFFPDGERILCRDCNSG-----------V
*
>P1;ENSORLG00000009622

------------------------------------------------MS
ERFDCRNCKASLYGQQYIKVENEPHCINCYDQLHANTCQECTEIIGHNDK
ELTFKDRYYHEHCFRCFRCDRSLSNASFTSHEDVLLCNDCYCNEFSSKCV
SCNKIVMPGSKILEFDG-SSWHEDCFVCHSCEKPIGGESFVPNENQYYCV
PCYEGRFTPRCSHCNKALTKGGVSYQGGVWHRECFLCTGCSAPLAGQPFT
SQGETPYCVKCFSNLYAKKCAGCNSAIT---------GFGDGKYISFEDR
EWHQPCFKCSRCSVSLVGSGFFPYRDQILCRDCNDD-----------D
*
>P1;ENSDARG00000034643

------------------------------------------------MS
ERFDCDNCKESLYGRKYIQAEENPYCIPCYDSLFANTCDECKELIGHDSR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDDALLCNDCYCNEFSSKCV
ACDKTVMPGTRKLEYAG-STWHEGCFICNSCQQPIGSKSFIPDKDDHYCV
PCYENKFAPRCTRCKQALAKGGVTYRDEPWHKECFVCTSCKVQLAGQHFT
SRDDSPYCIKCFGNLYAKKCEACNKPIT---------GFGGGKYISFEDR
QWHQPCFTCSRCSVSLVGAGFFPEQDEILCRNCNSTL-----------
*
>P1;ENSTRUG00000010010

------------------------------------------------MS
DQFSCKNCQESLCGRKYIQVEDRPHCISCYERLYANTCQECKELIGHNAK
ELSYEDRYYHAHCFRCFHCERSLADQPFTSQGDALVCSDCYGSRFSSKCS
ACDQTVTPGSRMLEYDG-STWHEDCFACHGCGKAIGTEAFIPDKNNYYCV
PCYEGRVAPQCSHCKQALTKGGVTYKDEVWHKECFLCTGCSAPLAGQPFT
SQGESPYCIRCFSSLYAKKCAGCNTAIT---------GFGDGKYVSFEDR
QWHQPCFKCSRCSVSLVGSGFFPDRGHILCMDCNND-----------D
*
>P1;ENSXMAG00000013212

VLP-------------------YRH----RY------V--K-PHEKTTMA
DRFDCDNCKESLYGRKYIQSDDNPYCIPCYDSLFSNTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDDALLCNDCYCNEFSSKCV
ACDKIVMPGTRKLEYAG-STWHEGCFICHSCEQPIGSKSFIPDKDDHYCV
PCYEEKFAPRCTRCKKALAKGGVTYRDEPWHKECFVCTNCKTQLAGQHFT
SRDDSPYCLKCFGSLYAKKCEACSKPIT---------GFGGGKYISFEDR
QWHQPCFTCSQCSISLVGAGFFPDGDKILCRDCNSN-----------L
*
>P1;ENSDARG00000104315

------------------------------------------------MS
EPFDCESCKESLYGQKYIQVDDKPHCVPCYDRLHANTCHECKELIEHNSR
ELYHEDRHYHEQCFRCSRCSRSLAKESFTCQEDALVCNNCYCNEFSSNCV
ACGKTVMPGSKRLEYED-CVWHEECFVCCGCEQPIGAQSFIPDKDEYYCV
PCYEGRFAPRCAHCKQTLVQGGVTYRDEPWHKECFLCTGCKVQLAGQPFT
TQGEDPYCVKCFSNLYAQKCAACEKPIT---------GFGEGKYVSFEER
QWHKPCFKCSVCSLSLVGAGFFPHGSMILCKGCNTKKLFQIVCEQTIE
*
>P1;ENSAMXG00000020305

MCN-------------------L--------------I-HI-LNRTITMT
ERFDCDNCKESLYGRKYIQAEDNPYCIPCYDSLFANTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDDALLCNDCYCNEFSSKCV
ACDKTVMPGTRKLEYGG-STWHEGCFICNSCEQPIGSKSFIPDKDDHYCV
PCYENKFAPRCTRCKQVLAKGGVTYRDEPWHKECFLCTGCKVQLAGQHFT
SRDDSPYCLKCFGNLYAKKCEACSKPIT---------GFGGGKYISFEER
QWHQTCFTCSRCSVSLVGAGFFPERDEILCRDCNSNL-----------
*
>P1;ENSTNIG00000006814

------------------------------------------------MA
DRFDCDNCKESLYGRKYIQSDDSPYCIPCYDSLFSNTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQDEALLCNDCYCNEFSSKCV
ACDKIVMPGTRKLEYAG-STWHEGCFICHSCEQPIGSKSFIPDKDEHYCV
ACYEDKFAPRCTRCKKTLSKGGVTYRDEPWHKECFVCTSCKTQLAGQHFT
SRDDSPYCLKCFGNLYAKKCEACTKPIT---------GFGGGKYISFEDR
QWHQPCFTCSECSVSLVGAGFFPYRGQDLVPRMQQQ-----------P
*
>P1;ENSLOCG00000005810

MSVDAVAIERKKATFPLYQVRTTEA----SD------VVPG-LDSEDTMS
ERFDCDNCKESLYGRKYIQAEDNPYCIPCYDSLFANTCDECKELIGHDAR
ELFYEDRHYHEHCFRCFRCDRSLADEPFTSQEEALLCNDCYCNEFSSKCV
ACNKTVMPGTRKLEYGG-NTWHESCFICHSCEQPIGSKAFIPDKEDYYCV
PCYESKFAPRCTRCKQTLAKGGVTYRDEPWHKECFVCTGCKAQLAGQHFT
SRDDSPFCLKCFGNLYAKKCEACTKPIT---------GFGGGKYISFEER
QWHQTCFTCSRCSVSLVGKGFFPENDEILCRDCNSD-----------L
*
